### ISSUE TITLE
Rewrite Admin help function

### ISSUE THREAD

**Issue by phaidon** [zikula/core#1037]
The admin help function is imho not very well structured:

index.php?module=admin&type=admin&func=help

I would move the security notices to the security module and the help messages to the related place.

**Comment by Guite** [comment]
@craigh Would you agree that this is done?

**Comment by craigh** [comment]
I guess I have no idea. I'm not sure that 'admin help' even exists, much less is a) helpful or b) well structured. @Kaik restructured much of this already. IMO, I don't see any reason to change what is here now.
