### ISSUE TITLE
Change timezone handling to Location/Area format

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#1144]
I've been dealing with some issues in displaying dates and times in an module I am writing.  My experience suggests that the way Zikula stores timezones for users us really inadequate.  Here's the gist of it:  You may think that the continental US has 4 time zones, Eastern, Central, Mountain and Pacific.  However when considering daylight savings time rules, here is the true list:

http://www.timezoneconverter.com/cgi-bin/zonehelp.tzc?cc=US&ccdesc=United%20States

For the most part, each time zone follows the same rules.  However there are exceptions as to when DST changes, and wouldn't you you know it, some of the events I am tracking are in those exceptions.  But there is an established system for dealing with this.  Rather than saying that (for example) someone in Phoenix Arizona is GMT -7, or that it's Mountain time zone in the summer and Pacific time zone the rest of the time (because they don't do DST), you specify America/Phoenix using the Area/Location time zone format and php adapts accordingly.

**Comment by craigh** [comment]
@shefik do you still have this code and can I see it?

**Comment by Guite** [comment]
@craigh as this is a FR: move to 1.5.0 or 2.1.0?

**Comment by shefik** [comment]
@craigh I will need to check if I still have the code.

**Comment by Guite** [comment]
if I understand that correctly this is exactly what the timezone form type is providing: http://symfony.com/doc/current/reference/forms/types/timezone.html
The problem with that seems that it is not easy to derive the timezone offset (like -2) from that.

**Comment by craigh** [comment]
@robbrandt - WHERE are you requesting this be altered. It isn't clear (to me at least) what you mean here. Do you mean in the Profile module? if so, this ticket is misplaced. If you mean something in the Core, please be more specific. I have already changed the timezone handling at `/settings/locale` - this is for "anonymous guests" only. Are there other TZ settings that I have missed?

**Comment by robbrandt** [comment]
I am struggling to remember the specifics as this issue is approaching 4 years old.  I do acknowledge that this may be a Profile issue, or that things have changed in Core already enough that it is no longer an issue.  I haven't attempted to address the issue again (yet).  However I do remember the gist of it.

The gist is that users should not be identifying their timezone by offset number, because this changes when daylight savings flips.  Nor by time zone, because it's not specific enough.  Users should identify their "time zone" using the Country/City or Country/State/City format (America/Los_Angeles or America/Indiana/Indianapolis), and the web site should determine the time based on the date.

The problem I was trying to solve was in displaying event times accurately based on where the site visitor is located.  If the event is in Chicago (America/Chicago, "Central Time", -6 offset during standard time, -5 offset during daylight savings time) at 7:00pm and the site visitor is in Phoenix (America/Phoenix, Mountain Time, -7 offset during standard time and Pacific Time -7 offset during daylight savings time - in other words they don't "do" daylight savings time) the event should show as 6pm during standard time and 5pm during daylight savings time.

In Zikula <= 1.3x the end user had to change their offset manually at every time zone change.  By supplying the time zone in the new format, the offset should be able to be calculated using http://php.net/manual/en/datetimezone.getoffset.php.

**Comment by Guite** [comment]
> to be calculated using http://php.net/manual/en/datetimezone.getoffset.php.

nice function :smile:

**Comment by craigh** [comment]
yes. This needs to be a function of the Profile module. So closing here.

I agree 100% that your explanation is how it should be done

**Comment by robbrandt** [comment]
There still might be a related issue on Core on USING new style time zone values from Profile.  Basically, if there's anywhere in Core where a numerical offset is presumed in Profile, it needs to be updated to calculate the offset instead.  Core or not, this change will affect how other things are done.
