### ISSUE TITLE
System modules: Replace prototype by jquery

### ISSUE THREAD

**Issue by phaidon** [zikula/core#1214]
Done
====
- [x] Admin
- [x] Categories (#2189)
- [x] Errors
- [x] Extensions (#2179)
- [x] Groups
- [x] Mailer
- [x] PageLock (#2175)
- [x] Permission
- [x] Search
- [x] Security
- [x] Settings
- [x] Users (#2176)
- [x] Theme (#2177, #2178)
- [ ] Blocks (#2208)

**Comment by Guite** [comment]
Closing this issue, as the last stuff is covered by #2206 and #2208

**Comment by rallek** [comment]
:+1: 

great step forward!

**Comment by Portugao** [comment]
Wow!
Thx a lot, Axel! :smiley:
