### ISSUE TITLE
[WIP] What modules can do

### ISSUE THREAD

**Issue by ghost** [zikula/core#1286]
I need to think out aloud and I would like some discussion on this matter. First let me explain some background.

Here's what Symfony does
- The kernel initialises and attempts to compile the container (if it needs to)
- The container is compiled to PHP you can see it in `app/acche/dev/appDevDebugProjectContainer.php` - this comes from service   - definitions (defined in PHP, XML, YAML etc).
- To do this is lets each bundle define it's services. 
- Bundles load and verify their configurations with stuff in the bundles'   - DependencyInjection folder - the kernel reads these.
- Before compile it allows all bundles to alter the compile process though (compiler passes) these are defined in the bundles Bundle class.

So before we start, there is a compiled file of PHP code which is then included. All this is 'hard coded' and cannot be changed. The container will also have certain parameters.

Symfony allows you to override definitions because first it collects all the definitions from all bundles in order (as defined in the `app/ZikulaKernel.php`). This allows you to override which classes are used for which services by overriding the names in the XML files.

e.g. we override FrameworkBundle's standard EventDispatcher with ours (so we can have BC with `Zikula_EventManager` like this

```
<parameter key="event_dispatcher.class">Zikula_EventManager</parameter>
```

Then we reach the front controller:

```
$request = Request::createFromGlobals();
$core->init(Zikula_Core::STAGE_ALL, $request);
```

The core-init() is our legacy system.

```
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```

This starts the symfony [request cycle](http://symfony.com/doc/current/components/http_kernel/introduction.html)

Basically it fires off a bunch of events until something replies with a `Response` object. This is then filtered by other events and the final object is sent to the browser. An example of a filter is our `ThemeListener` which takes the `Response` from the modules and then wraps the theme around it.

So that's the background of what happens. But now onto the details

So in Symfony, Bundles are first class citizens. But in Zikula, modules are designed to be 2nd class - meaning we can do things like disable them. Zikula needs a certain amount of robustness since it's being operated from the browser. In Symfony, a Bundle has the power to transform anything, like CoreBundles does above with the `event_dispatcher` service. But in Zikula we might need to restrict things like this.

The questions come about now. If a module can alter the service container, that means the container will need to be recompiled. Normally Symfony freezes the container after compile because it doesnt make sense to add more services and parameters to the compiled container since now certain things cannot be changed. But I have altered that so the container is always a `ContainerBuilder` which means you can add service definitions to the container and they will build at runtime without compiling - with some caveats - you cannot change parameter that exist already (and I could add a system to allow changes, but again it would have certain caveats).

to be continued....

Some references:

Understanding the Symfony DIC is pretty essential to be able to get involved with this RFC.
- [DependencyInjection Component](http://symfony.com/doc/current/components/dependency_injection/index.html)
  Specifically of interest:
  - [Parameters](http://symfony.com/doc/master/components/dependency_injection/parameters.html)
  - [Definitions](http://symfony.com/doc/master/components/dependency_injection/definitions.html)
  - [Compilation](http://symfony.com/doc/master/components/dependency_injection/compilation.html)
  - [Tags](http://symfony.com/doc/master/components/dependency_injection/tags.html)
- [creating and extension class](http://symfony.com/doc/master/cookbook/bundles/extension.html#creating-an-extension-class)

**Comment by craigh** [comment]
Symfony 2.8+ now [forbids container 'cloning'](https://github.com/symfony/symfony/commit/ba129041ba19b6d5a62cfa34789d3b05e6efbacf). I'm not certain it relates to this discussion, but it seemed relevant.
