### ISSUE TITLE
Symfony Forms integration with Bootstrap

### ISSUE THREAD

**Issue by craigh** [zikula/core#1297]
Perhaps we should look for ways to integrate Bootstrap directly into Symfony Forms so the module doesn't have to apply styles to every control.

I found this: http://bootstrap.braincrafted.com which does this to some degree (and more).

We of course could also layer our own version of Forms over the top of Symfony forms.

/cc @drak @phaidon @cmfcmf @Guite

**Comment by craigh** [comment]
This is handled by Symfony directly now.

**Comment by Guite** [comment]
> This is handled by Symfony directly now.

Do you have a link/source for that?

**Comment by craigh** [comment]
http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig
