### ISSUE TITLE
Allow user to delete own account

### ISSUE THREAD

**Issue by damon18** [zikula/core#1322]
Feature Request and Discussion

In "My Account" a user can change their email and password. Similarly they should be able to delete their user account.
## Issues
- What happens to data throughout the site that is tagged with that users username or ID? I would think that at the least that data should no longer show their username.
- When a user deletes their account should they also be given the chance to delete items they have contributed such as forum posts/topics, uploads etc.?
- Should the username that they delete be immediately available for a new user to register?
- Others?

**Comment by craigh** [comment]
I think we should address this issue with 3.0. Either implement it or decide we never want it and close it.

**Comment by Kaik** [comment]
I think to solve this properly (my view) would be to add setting in users module like allow users to delete/disable their own account. Then when this is "checked" chose between deleting completely or deactivation or any other action.
This should be GPRD compliant which means including right to be forgotten/delete stuff as well (at least the core).

**Comment by Guite** [comment]
> Either implement it or decide we never want it and close it.

:+1: for implementing it.

> setting in users module like allow users to delete/disable their own account

Yes! A module variable would be helpful.

> compliant

Sidenote: As far as I know, it is not legally necessary to be able to implement this right at the push of a button. It would also be sufficient to be able to contact the admin to demand that the data be deleted.

**Comment by Guite** [comment]
Additional note:

All modules which store a user id need to implement user deletion handlers.

In ModuleStudio there are [three options](https://modulestudio.de/en/documentation/87-generatorreference/#account-deletion-handler):

- `ADMIN` - Sets the corresponding user id to 2 (admin user).
- `GUEST` - Sets the corresponding user id to 1 (guest).
- `DELETE` - Deletes the entity.

**Comment by craigh** [comment]
feels good when you can close an 8 year old ticket. 🎉 🎆

**Comment by damon18** [comment]
> feels good when you can close an 8 year old ticket. 🎉 🎆

@craigh That's got to be a record for a ticket I opened! Looks like I was ahead of my time on the need to allow users to delete their account and data. (GDPR)

Now if I could find a way to upgrade thebeachcats.com and other "orphan" sites still running Zikula 1.2.10 :confounded:

**Comment by Guite** [comment]
> a way to upgrade

I took a quick look. Looks like there are some nuts to crack :thinking:

**Comment by damon18** [comment]
> > a way to upgrade
> 
> I took a quick look. Looks like there are some nuts to crack 🤔

Yes, some great big hairy ones.. I'll send you an email (for your entertainment) rather than airing my dirty laundry here.
