### ISSUE TITLE
Make it possible to select language during registration

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1330]
Is there any reson against this?

**Comment by rallek** [comment]
isn't that done already?

**Comment by Guite** [comment]
Not sure whether I like this idea. If I speak/understand language X I would rather switch to it *before* starting the registration. Why should I do the registration in English and choose German as part of the data input? Or am I missing something?

**Comment by rallek** [comment]
The install begins always with english. Can we change that?

**Comment by Guite** [comment]
This is another story (please create a separate ticket). This issue is about user registration.

**Comment by craigh** [comment]
> Or am I missing something?

this ticket is about allowing a user to select their default language upon registration. This would allow a user to have the site automatically change languages upon login.

**Comment by rallek** [comment]
mmh, in this case this feature is not really important. I personally would not use it I guess.

**Comment by Guite** [comment]
Discussed with @craigh about different use cases.
Closing in favour of the newly created #4098 
If you have additional comments please add them there.
