### ISSUE TITLE
Add pageaddvar options for media, id, title and alternate in the case of stylesheets

### ISSUE THREAD

**Issue by espaan** [zikula/core#1331]
Adding pageaddvar to templates gives a stylesheet includion:

```
    {pageaddvar name="stylesheet" value="$stylepath/somestyle.css"}
```

but now you cannot do something like 

```
    <link href="{$themepath}/style/somestyle_green.css" media="print" id="colors" rel="alternate stylesheet" title="green" type="text/css" />
```

Would it be possible to enhance the pageaddvar ?

**Comment by Guite** [comment]
I think this is a "won't fix", because with the asset system you can define the `link` tag like you want.

@craigh ?

**Comment by Guite** [comment]
-"won't fix"
+"already done"

:-)

**Comment by craigh** [comment]
> you can define the `link` tag like you want

I don't know that this is true. example?

I don't know if this is already done.

**Comment by Guite** [comment]
If you use `pageAddAsset` you can not customise the link tag.
`{{ pageAddAsset('stylesheet', asset('bootstrap-jqueryui/bootstrap-jqueryui.min.css')) }}`
*but* you can also use `asset`:
`<link rel="stylesheet" type="text/css" href="{{ asset('bootstrap-jqueryui/bootstrap-jqueryui.min.css') }}" />`
And with this notation you can of course also add attributes like `media` or `alternative`.

Thus imo this issue can be closed.
