### ISSUE TITLE
[1.3.x] Upgrade.php has misleading screen

### ISSUE THREAD

**Issue by damon18** [zikula/core#1629]
When upgrading within 1.3.x as from 1.3.4 to 1.3.7 the upgrade works as expected to upgrade the version number and database. 

At the end of the process the user is presented with a confusing screen that has no exit. Instead the screen should state that the site has been upgraded from 1.3.x to 1.3.x and instructions to remove /install and upgrade.php and a link or button to move on to the site or admin.

![zikula-upgrade-already-up-to-date](https://f.cloud.github.com/assets/1587992/2189846/f0986e4a-981d-11e3-95f7-e20dee2b8e6a.jpg)

**Comment by Portugao** [comment]
Cannot reproduce this with 1.3.9.
Could you please check again with 1.3.9

**Comment by Portugao** [comment]
ping @damon18 
Please check again!

**Comment by craigh** [comment]
closing for lack of response
