### ISSUE TITLE
[General] Contribute to the GitHub Repository for .gitignore Templates

### ISSUE THREAD

**Issue by shefik** [zikula/core#1668]
GitHub maintains their own public repository of useful .gitignore templates. Zikula should submit a pull request to have the project included.

https://github.com/github/gitignore

Projects such as Drupal, WordPress, Symfony2, Joomla, and ZendFramework are already included.

**Comment by Guite** [comment]
Let's stick to `Symfony.gitignore` instead of inventing and maintaining our own stuff.
