### ISSUE TITLE
"Password Reminder" is not actually doing anything.

### ISSUE THREAD

**Issue by shefik** [zikula/core#1682]
In the Users module. it looks like the setting "Password Reminder" is not actually doing anything. Even if you set the field to mandatory or not mandatory, there is no functionality that uses the module var.

**Comment by craigh** [comment]
Honestly, I had no idea what this ticket was about. I've never used this feature.

![screen shot 2015-01-18 at 6 13 29 am](https://cloud.githubusercontent.com/assets/350048/5792171/2b1066e6-9ed9-11e4-9161-ee07c2c011aa.png)
![screen shot 2015-01-18 at 6 12 21 am](https://cloud.githubusercontent.com/assets/350048/5792172/2de0b916-9ed9-11e4-9eee-25a2914272ae.png)

but I don't know how to make this useful. When a user loses their password, it is regenerated and they have to create a new one, so sending them a reminder isn't helpful.

If we were to try to show it to the user as they login, we would have to probably count the failed logins and on a specified number (3?) show the reminder to the user IF the username is valid. But I think this might not be so secure and allow brute force logins.

I'm wondering if we should just remove the functionality altogether? Was is used in 1.3?

**Comment by rallek** [comment]
I will never use this feature. For me it sounds like a security risk. If a user has forgotten his passwort he can start the password reset process.

**Comment by Guite** [comment]
My proposal:

- completely remove password reminder (#1682)
- make lost password functionality easier to use (like described in #1781)

Any objections about this?
