### ISSUE TITLE
Fully implement Twig templating layer

### ISSUE THREAD

**Issue by craigh** [zikula/core#1753]
Fully implement Twig templating layer

- [x] provide required additional template functions
- [x] theming concept and prototype
- [x] convert system modules
  - [x] Admin #2856
  - [x] Blocks
  - [x] Categories #2923 
  - [x] Extensions
  - [x] Groups #2907 
  - [x] Mailer #2849 
  - [x] PageLock #2862 
  - [x] Permissions #2896 
  - [x] Routes #2921 
  - [x] Search #2853
  - [x] SecurityCenter #2890 
  - [x] Settings #2832 
  - [x] Theme
  - [x] Users #2851
- [x] convert themes
  - [x] Andreas08
  - [x] Atom
  - [x] Bootstrap
  - [x] Printer
  - [x] RSS
  - [x] SeaBreeze
- [x] overall review and bugfixing

**Comment by Guite** [comment]
Closed :smile:
