### ISSUE TITLE
implement bootstrap-datetimepicker

### ISSUE THREAD

**Issue by craigh** [zikula/core#1758]
https://github.com/Eonasdan/bootstrap-datetimepicker

refs #1123 (closed)

**Comment by craigh** [comment]
@Guite weren't you just working on something like this? care to share it to the core?

**Comment by Guite** [comment]
Actually there is not much to share. But here is what I did:

- include no special/additional vendor script
- render a datetime field using the `DateTime` form type from Symfony with the options shown below
- webshim will care for the rest

```
        'with_seconds' => true,
        'date_widget' => 'single_text',
        'time_widget' => 'single_text'
```

**Comment by Guite** [comment]
so my suggestion is removing `jQuery-Timepicker-Addon` without a replacement in 2.0, see https://github.com/zikula/core/issues/2416#issuecomment-290620181

**Comment by robbrandt** [comment]
👍 That's a really nice datepicker.

**Comment by Guite** [comment]
@robbrandt webshim already automatically provides this one as a polyfill if the browser does not provide a native one:

http://afarkas.github.io/webshim/demos/demos/cfgs/input-date.html
http://afarkas.github.io/webshim/demos/demos/cfgs/input-time.html

**Comment by craigh** [comment]
@Guite this is done then, right?

**Comment by Guite** [comment]
yes.
