### ISSUE TITLE
Upgrade failed ReflectionException: Class Dizkus_HookHandlers does not exist

### ISSUE THREAD

**Issue by Kaik** [zikula/core#1770]
Hi all I'm starting with zikula upgrade and this are few errors I experienced.

Upgrade from working zikula 135 database just downloaded and imported locally
Theme changed manually

Error log
1. in D:\xampp\htdocs\zikula_upgrade\src\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php line 959
2. at ReflectionClass->__construct('Dizkus_HookHandlers') in D:\xampp\htdocs\zikula_upgrade\src\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php line 959
3. at ContainerBuilder->createService(object(Definition), 'dizkus.hooks.comments') in D:\xampp\htdocs\zikula_upgrade\src\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php line 493
4. at ContainerBuilder->get('dizkus.hooks.comments', '1') in D:\xampp\htdocs\zikula_upgrade\src\lib\legacy\Zikula\ServiceManager.php line 117
5. at Zikula_ServiceManager->get('dizkus.hooks.comments') in D:\xampp\htdocs\zikula_upgrade\src\lib\legacy\Zikula\HookDispatcher.php line 310
6. at Zikula_HookDispatcher->loadRuntimeHandlers() in D:\xampp\htdocs\zikula_upgrade\src\lib\legacy\Zikula\HookDispatcher.php line 348
7. at Zikula_HookDispatcher->reload() in D:\xampp\htdocs\zikula_upgrade\src\lib\legacy\Zikula\HookDispatcher.php line 117
8. at Zikula_HookDispatcher->registerSubscriberBundle(object(SubscriberBundle)) in D:\xampp\htdocs\zikula_upgrade\src\lib\util\HookUtil.php line 157
9. at HookUtil::registerSubscriberBundles(array('subscriber.blocks.ui_hooks.htmlblock.content' => object(SubscriberBundle))) in D:\xampp\htdocs\zikula_upgrade\src\system\Zikula\Module\BlocksModule\BlocksModuleInstaller.php line 69
10. at BlocksModuleInstaller->upgrade('3.8.1')
11. at call_user_func(array(object(BlocksModuleInstaller), 'upgrade'), '3.8.1') in D:\xampp\htdocs\zikula_upgrade\src\system\Zikula\Module\ExtensionsModule\Api\AdminApi.php line 1106

Looks like BlocksModule upgrade checking for all hooks classes even that they might not exist. Fixed for now deleting all the hooks informations in tables. This might be related to my data in database as I played with hooks but still think It should not failed the upgrade.

Upgrade succeed at the end and looks like it is working. I had 2 more errors and I will post them in separate issues. 

I'm trying to get involved now so I will post all that stuff here if you don't mind? :)

**Comment by craigh** [comment]
refs https://github.com/craigh/core/commit/ff20010fcbbd54b3d7216141b0d3cb448c323154
