### ISSUE TITLE
Password Reset without Confirmation Code

### ISSUE THREAD

**Issue by shefik** [zikula/core#1781]
Most sites just send a "password" reset email to the email address on file, and the user clicks the link to create a password and that's it - the user can then select a new password.

We currently have a two-step password reset with the additional confirmation code. Is a confirmation code necessary? Or, can we just go with a password reset email sans the confirmation code?

Perhaps it can be an option for the site admin to choose whether they want password reset to require a confirmation code, or not.

**Comment by Guite** [comment]
My proposal:

- completely remove password reminder (#1682)
- make lost password functionality easier to use (like described in #1781)

Any objections about this?

**Comment by rallek** [comment]
:+1:

**Comment by cmfcmf** [comment]
👍

**Comment by craigh** [comment]
@Guite this feature should be implemented ONLY in ZAuth please. Users no longer manages passwords.
