### ISSUE TITLE
1Password Extension Causes Alerts from HTML5 Form Validation to Close

### ISSUE THREAD

**Issue by shefik** [zikula/core#1818]
The following error occurs at any form which uses HTML5 form validation and contains a "password" input field (such as the User Registration form):

When a user has the 1password extension installed on their desktop browser, the 1Password prompt overrides the HTML5 form validation alert, since it opens on top of the alert. As a result, the alert forces closes, since it believes that the user manually left focus on the form field in question.

More info on 1 Password:

https://agilebits.com/onepassword

Is there some way to make the alerts static?

**Comment by craigh** [comment]
why is this our problem? What do you mean by "Is there some way to make the alerts static?"

**Comment by shefik** [comment]
I'm closing this ticket. Doesn't seem to be an issue anymore, when using the latest 1Password version 5.1.
