### ISSUE TITLE
Remove reset.css

### ISSUE THREAD

**Issue by phaidon** [zikula/core#1819]
Bootstrap uses normalize.
See #1324

**Comment by craigh** [comment]
I think this file has been removed sometime. can someone else confirm?
@cmfcmf @Guite @phaidon @Kaik @shefik

**Comment by Guite** [comment]
Yes, was removed in https://github.com/zikula/core/commit/660a68f1ed0e481402f5dd72ba09bd2c18b41e11#diff-0b6ca66c1f61f9c99f315faaa6c24234
