### ISSUE TITLE
Need an Error Template when a Module is Deactivated

### ISSUE THREAD

**Issue by shefik** [zikula/core#1869]
When a module is "deactivated" (but, not "uninstalled"), if you attempt to load any of the module's page, it return an empty string.

Perhaps it will be better to have an error template loaded with one of the following server error codes in the header:

401 - Access denied.
403 - Forbidden.
404 - Not found.

**Comment by Guite** [comment]
> I think we need to add this twice: for old-style modules and new modules using routing.

Just tested and found that for new-style modules a 404 is returned.
Only for legacy modules an empty string is returned, so I propose to focus on that in order to solve this issue. Going to see whether I cope with this.
