### ISSUE TITLE
[Routes] Review route / url creation and redirection

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1878]
- [ ] Allow to edit module urls
- [ ] **Allow to make a custom route the default route:** Let's say a module defines a route _/modname/bla/test_ to it's TestController::test() action. Let's say the user adds a custom route (_/my-fancy-custom-route_) via the RoutesModule admin interface which also points to the TestController::test() action. It should be configurable which route is used by default by the generator (so whether `$router->generate('testmodule_test_test')` results in _/modname/bla/test_ or _/my-fancy-custom-route_).
- [ ] **Make sure to use redirects (and not have duplicated urls):** When there are two routes pointing to the same module/type/action (i.e. the user added a custom route), all routes except one should redirect to one single route). In the example above, either _/my-fancy-custom-route_ would redirect to _/modname/bla/test_ or vice versa.
- [ ] **Add url conflict checks:** When you add a new custom route, there should be a simple check in place _warning_ the user about _possibly_ duplicated urls. Example: There already is a route _/test/{id}_ and the user adds _/test/6562_ as a route, it should give a warning.
- [x] Allow reloading urls of one single module
- [x] Add _reload routes of one module only option_
- [x] 

> you should write a handler and catch the Symfony\Component\Routing\Exception\RouteNotFoundException:
> [22:55:54] Craig Heydenburg: handle it more gracefully and redirect admin to reload the routes
> [22:56:06] Craig Heydenburg: or auto-reload routes on extension install

**Comment by craigh** [comment]
@cmfcmf should we (or can we) postpone these other items until 2.0.0? if not, is there any way you can complete them before 31 Jan?

**Comment by cmfcmf** [comment]
I will have some time the next weekend and see what I can do.

**Comment by cmfcmf** [comment]
Turns out I won't have time the next weekend :-1: I think this isn't a blocker though, and might even be postponed to something like 1.4.1 (if it'll ever exist) or 2.0.0 otherwise.

**Comment by Guite** [comment]
Closing as won't fix as our custom routing system will be removed.
