### ISSUE TITLE
extmenu drag to nested doesn't save.

### ISSUE THREAD

**Issue by damon18** [zikula/core#1882]
Trying to create a new bootstrap dropdown menu with extmenu.

Created a new extmenu block and selected the blocks_block_extmenu_bootstrap.tpl template.

Added 7 menu items.

Drag last three items to be nested under the fourth item, which should create a drop menu.

Clicked Save and all the nested items went back to their previous positions.
#924

**Comment by craigh** [comment]
@espaan would you have the time to look into this?

**Comment by espaan** [comment]
Hi, I have not tested much in 1.4 yet, but I can take a look.

**Comment by espaan** [comment]
Testing, but I get a stack trace when opening e.g. the Main Menu block after default 1.4 install
```
 User Error: Smarty error: [in Admin/modify.tpl line 54]: syntax error: expecting '=' after attribute name 'visibility' (Smarty_Compiler.class.php, line 1558)
500 Internal Server Error - ContextErrorException 
```

**Comment by Guite** [comment]
#2239 is merged now.

**Comment by espaan** [comment]
:+1:

**Comment by Guite** [comment]
@craigh awesome!
