### ISSUE TITLE
How do we want to handle (core) translations

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1895]
I'm currently thinking about how to implement translation downloading in the ExtensionLibrary.
# Module translations

Module translations should be included in the module repositories themselves. Currently most modules still have their (german) translations in the `zikula-communities/*` repositories - they need to be moved into the module repositories at some time. See https://groups.google.com/d/topic/zikula-discussions/WI_q3dXkVQE/discussion for the discussion (thanks @craigh!).
# Core translations

Currently, core translations are placed somewhere in the `zikula-communities` repositories. There is no standard way of handling them yet, however, we need a standard way to be able to provide translations via the ExtensionLibrary. I see the following possibilities:

|  | handling | pros | cons |
| --- | --- | --- | --- |
| 1 | Include translations directly in the core repository | No need to download additional core translations. No need to handle core translations in the ExtensionLibrary. | The core gets bigger. |
| 2 | Add a `zikula/translations` repository and add translations in there. | One central place to have all the core translations. Pretty easy handling for the ExtensionLibrary | Translations aren't included in the Core -> The user has to download multiple files. |
| 3 | Stay with the current chaotic system | No need to change anything | It's hard to find translations. It cannot be handled by the ExtensionLibrary (meaning more work on core releases) |

Which way do you prefer? Do you have additional ideas? Did I oversee cons for solution 1?

**Comment by rallek** [comment]
Thinking about this issue...

My current ideas:
The translations should not be part of the core, module or theme. The developer/translator should be able to place his translations wherever he wants. But there is a file named zikula.manifest.json. All available translations should be listed here. And the core should be able to download a language for all installed extensions. This download can be made inside language setting of the general settings inside the admin area. If for one extension no language pack is listed inside the zikula.manifest.json than the download will be skipped.

Might be this idea is something for zk2.0.0

**Comment by Guite** [comment]
Going to take a thorough look at this and #2425 soon.

**Comment by craigh** [comment]
why delete all the comments?

**Comment by Guite** [comment]
merged and removed redundancies in order to get an overview of the overall todo

**Comment by craigh** [comment]
in the future, I'd prefer my comments not be removed. it helps me remember my own thoughts on the matter of discussion

**Comment by Guite** [comment]
okay... I won't do anything

**Comment by craigh** [comment]
you're being silly. did I ask you not to do _anything_? no. I asked you not to delete my comments. :roll_eyes:

**Comment by Guite** [comment]
if I intend to work on a task IMO one of my preparations is cleaning up longer discussions in order to reduce confusions and get to a precise todo plan

**Comment by craigh** [comment]
I think Core translations should stay in the core repo and be regenerated in the release phase/build.

**Comment by Guite** [comment]
> I think Core translations should stay in the core repo and be regenerated in the release phase/build.

Yes for English, but I tend to disagree for other languages, as the core team may not be able to update these.

**Comment by craigh** [comment]
> as the core team may not be able to update these.

not clear what you mean here.

**Comment by Guite** [comment]
e.g. we do not speak Chinese

**Comment by craigh** [comment]
yes, we won't be able to do the transition. what difference does that make? Some that does would open a PR. I don't understand the actual concern.

**Comment by Guite** [comment]
So you propose to eliminate `zikula-communities` entirely and move all translations into the core and module repositories?

**Comment by craigh** [comment]
yes

**Comment by craigh** [comment]
this is the sum total of activity in zikula-communities

![Screen Shot 2020-02-09 at 8 47 40 AM](https://user-images.githubusercontent.com/350048/74103275-d7cc2500-4b18-11ea-8d55-2176ec3b6961.png)

**Comment by Guite** [comment]
archived the repositories as a first step

**Comment by Guite** [comment]
Added a doc about this convention [here](https://github.com/zikula/core/blob/master/docs/Translation/Contributing.md) and linked to it at the README of all zikula-communities repositories.

Closing this issue now.
