### ISSUE TITLE
Update prototype from 171 to 172

### ISSUE THREAD

**Issue by espaan** [zikula/core#1896]
Prototype 1.7.2 was released on April 18 2014, http://prototypejs.org/download/
It would be nice if a next 1.3.x release would use this bugfix prototype release

**Comment by Portugao** [comment]
We have to clear what to do with this issue.
It seems to be very difficult, so i prefer to do only in 1.4 branch and move this issue to 1.4 milestone.
Any suggestions?

**Comment by espaan** [comment]
I would not do it in the 1.3.x branch indeed. Keep that stable and no all too new things. 
IMHO

**Comment by craigh** [comment]
moved to 1.4 milestone. don't know if there is time to get it in before release. A quick PR would help, but concerned about 

> It is super tricky as the compressed version needs to be done in a certain order. No quick merges if it happens please.

**Comment by espaan** [comment]
+1

**Comment by craigh** [comment]
once https://github.com/zikula/core/pull/2242 is merged, then (according to @espaan ) the prototype lib is back to its original (from vendor) state, so upgrading is much easier. But there remains the issue of the combined and compressed version - does anyone know how this was created?

**Comment by jusuff** [comment]
It was manually created. At least one time I did this using yui compressor.
Doing this one must remember about proper scripts order:
prototype 
effects 
builder 
controls 
dragdrop 
slider 
sound

**Comment by espaan** [comment]
Hi, that should be doable with a compressor indeed.. Are there specific things for testing/checking after making a minified version ?

**Comment by jusuff** [comment]
I was just testing this in local working copy. There shouldn't be any issues except script order and this will be easy to find (lots of undefined warnings).

**Comment by espaan** [comment]
Ok thanks !
description of things to do: http://www.boogdesign.com/b2evo/index.php/compressed_prototype_scriptaculous?blog=2

There does seem to be an action to remove parts for loading seperate scriptaculous scripts.

**Comment by jusuff** [comment]
There's not need to remove anything. Just combine scripts WITHOUT scriptaculous.js file. 
The only thing scriptaculous.js is doing is loading it's subscripts (effects, dragdrop etc). We don't need this if we're making combined file.

**Comment by espaan** [comment]
Clear, thanks

**Comment by craigh** [comment]
@espaan can you do this today?

**Comment by espaan** [comment]
Hi, sorry will be difficult, have a number of other things to pick up today.

**Comment by craigh** [comment]
if I have time I will look into it then.

**Comment by craigh** [comment]
@Guite @cmfcmf can this be automated in the build process? I see there are already [lines for YUI compressor](https://github.com/zikula/core/blob/1.4/build.xml#L279-L283)
