### ISSUE TITLE
Menutree - add 2nd sublevel option and more menus

### ISSUE THREAD

**Issue by espaan** [zikula/core#1926]
Hi,
Bootstrap 3 removed the multi level submenus. There is a reasoning behind that of course, but for people using multi level menus that want to go to a Bootstrap theme this is not handy.
- [ ] So getting the multi level part back in as option at least 
- [ ] Adding SmartMenus ( http://www.smartmenus.org/ ) MIT license
- [ ] Other jQuery / Bootstrap MIT licensed menus ?

Multi level Bootstrap3 menus:
https://github.com/twbs/bootstrap/pull/6342#issuecomment-11594010 discussion about this
https://github.com/djokodonev/bootstrap-multilevel-dropdown
http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3
http://www.jeffmould.com/2014/01/09/responsive-multi-level-bootstrap-menu/

This can go in a separate package again, but some more options in the Core for a full fledged menu would be welcome.
External package https://github.com/espaan/menus_menutree_extmenu where I made several extmenu & menutree options available as addon.

**Comment by craigh** [comment]
menutree is discontinued and will not be further developed.
