### ISSUE TITLE
implement Namespaced Plugin architecture

### ISSUE THREAD

**Issue by craigh** [zikula/core#1948]
The Plugin architecture is still entirely using Pear classes and doesn't appear to have any Namespaced alternatives.

**Comment by cmfcmf** [comment]
> but I do not understand why it is called a Module Plugin instead of simply a Plugin

There are system plugins and module plugins. Scribite is an example using module plugins.

**Comment by Guite** [comment]
@craigh at #2945:

> I also think the concept of a "System Plugin" should just be replaced by bundles that can be added to the core's composer/kernel.

**Comment by Guite** [comment]
Just saw that I said the same above :smile:

**Comment by craigh** [comment]
I think Module plugins (like scribite editors, etc) should be replaced by [Symfony Tagged Services](http://symfony.com/doc/current/service_container/tags.html). The module that utilizes the plugins would be responsible to manage them and provide a UI for config, etc.

SO - in order for this ticket to close, we simply need to document that all plugins are deprecated - make sure all related classes are marked as such and move them (if not already) into the legacy folder.

**Comment by cmfcmf** [comment]
:+1:
