### ISSUE TITLE
API vs. Util vs. services 

### ISSUE THREAD

**Issue by craigh** [zikula/core#1950]
I think we need to give extension developers more guidance on the purpose of API and better define an extension architecture to include Util classes or something like that.

In the past, we used module API functions as (somewhat) easily accessible "helper" functions to do the heavy lifting we wanted to keep out of the controller - database interaction, utility function and just a general "catch all" for code we don't want elsewhere. In addition, the term "API" has been misused here. If something is a "API" it might be assumed that the function is accessible from outside the component [see def](http://en.wikipedia.org/wiki/Application_programming_interface) and [ref News ticket](https://github.com/zikula-modules/News/issues/136)

As we move toward Symfony with Doctrine, the traditional API function seems less useful and relevant. Of course, there is nothing forcing a developer to use the published structure and utilizing API type classes except for the ability to call `ModUtil::apiFunc()` which IMO is becoming much clumsier than importing a Util class and issuing `MyModUtil::myFunc()`.

I guess I'm suggesting we do away with the traditional understanding of API classes and move to more Util classes and only use API for functions intended to be externally accessible.

thoughts/opinions?

**Comment by Guite** [comment]
Closing as fixed, since the 2.0 spec actively supports the usage of services.
