### ISSUE TITLE
Is there a chance to have a class "selected" in menutree

### ISSUE THREAD

**Issue by trichers** [zikula/core#1953]
In older versions of the menutree-block was the current item given a class="selected". Why not in the core-version of 1.3.9?
Or do you have another possibility to mark the active menu-item?

**Comment by Portugao** [comment]
Can you give information witch template you talk about?

**Comment by trichers** [comment]
I mean this https://github.com/zikula/core/tree/1.3/src/system/Blocks/templates/menutree
But I think it is in this plugin:
https://github.com/zikula/core/blob/1.3/src/system/Blocks/templates/plugins/function.menutree.php

For bootstrap we need the class "active" not "selected"

**Comment by Portugao** [comment]
How and in which template do you use the class 'selected'?
I think, it is not usefull in each template....

**Comment by trichers** [comment]
In the old module menutree it was a part of the menutree plugin. 
I think to use the bootstrap menu, it should be a standard that a active menu item is set class="active"

**Comment by trichers** [comment]
In the old module menutree it was a part of the menutree plugin. 
I think to use the bootstrap menu, it should be a standard that a active menu item is set class="active"

**Comment by trichers** [comment]
In the old module menutree it was a part of the menutree plugin. 
I think to use the bootstrap menu, it should be a standard that a active menu item is set class="active"

**Comment by Guite** [comment]
Moving to 1.3.11.

**Comment by Guite** [comment]
Closing as there won't be a 1.3.13 release.
