### ISSUE TITLE
Missing 1.3.10 ci builds, missing 1.3.10 milestone, http://go.zikula.org/download_latest points to 1.3.8, Zikula Admin Interface upgrade message still says 1.3.8 is newest version

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1954]

**Comment by Portugao** [comment]
Hi @drak.
Are you able to work with this issue?

**Comment by craigh** [comment]
drak tried to give me access today but it wouldn't work.

**Comment by Portugao** [comment]
Not so good.

**Comment by craigh** [comment]
@Guite can what you git in 1.4. with the github lookup be back-ported to solve this problem?

**Comment by Guite** [comment]
Fixed in 5e8296e2ec1bccc240877a507c88f01afa5bed21
