### ISSUE TITLE
[Extensions] Alert to notify an admin that modules need to be upgraded

### ISSUE THREAD

**Issue by shefik** [zikula/core#1965]
At this page, there should be an alert to notify an admin that modules need to be upgraded (similar to how there are already alerts for "Security analyser warnings" and "Developer notices (development mode on)":

/index.php?module=administration&type=admin&func=adminpanel

Right now, the indication is buried at the Extensions module list page, under "Actions":

/index.php?module=extensions&type=admin&func=view&startnum=0

**Comment by Guite** [comment]
Closing since we are now jusing Composer and Flex like Symfony default.
Hence, automatic upgrade notifications are possible by using [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) or similar services.
