### ISSUE TITLE
Hooks Not Working Anymore

### ISSUE THREAD

**Issue by shefik** [zikula/core#1968]
Hooks are not working anymore.

As an example, try hooking Scribite to a textarea. It does not transform the textarea anymore, even though the "Hooks" page is indicating that is hooked.

Zikula 1.4.0 build 182.

**Comment by craigh** [comment]
I just applied a similar fix in https://github.com/craigh/core/commit/ff20010fcbbd54b3d7216141b0d3cb448c323154 so am re-opening this just to force a check before re-closing

**Comment by craigh** [comment]
Hooks still work even with my change :+1:
