### ISSUE TITLE
Consider current language in ajax requests

### ISSUE THREAD

**Issue by Guite** [zikula/core#1985]
Check and verify that the current language is considered properly in ajax requests.
- for routes
- for legacy short urls

Related changes in 1.3:
- a8f0743f1da53516d013f980523b9dbcbe8629f0
- f1e8b6b62ae95a3666554e9ec8ac80b71a04e331

cc @craigh

**Comment by craigh** [comment]
@Guite has this been addressed by recent work on lang/locale tickets like #2351, #2320 ? perhaps it is solved?

**Comment by Guite** [comment]
I doubt that this is solved already. @cmfcmf any information to share (see comments above)?

**Comment by craigh** [comment]
I think that I just encountered an example of how this is broken in Core-2.0 ajax type requests. All the settings in config, etc are `en` but my ajax request just got translated to `pl`. hmmmm.

**Comment by craigh** [comment]
@cmfcmf It would be great if you could look into this today or tomorrow.

**Comment by craigh** [comment]
@cmfcmf I beg you to look into this...

**Comment by cmfcmf** [comment]
> what @craigh asked: is the language already set as route argument (also for ajax requests)?

`Routing.generate('zikulapermissionsmodule_ajax_test')` generates a route with the appropriate locale.
> whether the core actually uses this _locale route attribute

The Core is using the `_locale` to set the legacy `_lang` parameter which results in it being correctly used.

**Comment by craigh** [comment]
Something keeps setting my locale to `pl` and my local site converts to Polish... 
I guess the i18nRoutingBundle sets a cookie named `hl` (home language?) and mine keeps getting reset to `pl`. But my settings are correct in the config.

@Kaik would you have any ideas about this?

![screen shot 2016-09-21 at 4 04 06 pm](https://cloud.githubusercontent.com/assets/350048/18727124/47b88c96-8015-11e6-9185-2c3ae4a67745.png)
![screen shot 2016-09-21 at 4 05 12 pm](https://cloud.githubusercontent.com/assets/350048/18727120/40134c74-8015-11e6-9b52-7748f3a1ec31.png)
![screen shot 2016-09-21 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/350048/18727147/668801e2-8015-11e6-954f-30f9f08e21a9.png)

**Comment by Kaik** [comment]
I will need to test this hard to say when I will able to do it. But I do not understand your problem @craigh you screenshots show everything looks good. _locale at the very very beginning is set to en (this is how it starts it is hardcoded to en) then during the request it might be changed basing on data in url, cookie or session or browser settings. You should be able to generate url from route with different locale than default passing _locale - but I have not tested if this work in javascript `` Routing.generate()``

**Comment by craigh** [comment]
> But I do not understand your problem

everything is in Polish, but I never requested Polish. I even have multilingual *off*. It should be in English

**Comment by craigh** [comment]
@Guite let's test this - it may be solved

**Comment by Guite** [comment]
Confirmed: it's fixed.
