### ISSUE TITLE
Storing Sessions in File Not Working

### ISSUE THREAD

**Issue by shefik** [zikula/core#2001]
When a site is configured to store sessions in file (instead of a database), the sessions do not get get written to the file.

/index.php?module=security-center&type=admin&func=modifyconfig

**Comment by craigh** [comment]
I've looked into this a little. It is not an easy task to implement the ability to choose once again. Not impossible, but difficult.

**Comment by shefik** [comment]
I personally prefer having sessions in the database, especially in the case where a server cluster is needed for load balancing. Therefore, calling to the same database is efficient for session handling.

**Comment by craigh** [comment]
rescheduled to 2.0-beta1

**Comment by craigh** [comment]
this might help: http://stackoverflow.com/questions/24766260/symfony-set-the-cookie-domain-dynamically

basically - if we eliminate the session config from our config.yml file, then sessions are stored in a file.

my thinking is that we might be able to use this method to 'revert' the settings back to their default in a dynamic way. Also we could use this to set the cookie name (which is also dynamic) but we are doing this by setting the value in /Applications/MAMP/htdocs/core.git/src/app/config/dynamic/generated.yml

perhaps we could dynamically set the session config items in generated.yml too...

**Comment by craigh** [comment]
more ideas

http://blog.dixo.net/2015/02/dynamic-configuration-of-doctrine-and-other-services-in-symfony/
