### ISSUE TITLE
align htmlpurifier config settings w/ current version

### ISSUE THREAD

**Issue by craigh** [zikula/core#2010]
I believe the configuration for html purifier is not synchronized to current options. For example, in the `HTMLPurifier 'AutoFormat' configuration directives` section, the setting for `RemoveEmpty.Predicate` is not available at http://htmlpurifier.org/live/configdoc/plain.html#AutoFormat

other areas may need to be updated/added/removed as well.

**Comment by Guite** [comment]
This is fixed. Probably by https://github.com/zikula/core/commit/bd075041f79f9fede2b27e76044231b19e48ce07
