### ISSUE TITLE
Consider KnpMenuBundle for menu blocks

### ISSUE THREAD

**Issue by Guite** [zikula/core#2031]
* https://github.com/KnpLabs/KnpMenuBundle
* https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/index.md
* https://github.com/KnpLabs/KnpMenu
* https://github.com/KnpLabs/KnpMenu/tree/master/doc

Benefits:

* all blocks would use the same interface for building menus
* routing support already included
* twig support already included
* it becomes easier to merge the different menu blocks in a later step, too

See also http://vadikom.github.io/smartmenus/src/demo/

**Comment by craigh** [comment]
https://www.symfony.fi/entry/whats-on-the-menu-symfony

**Comment by craigh** [comment]
one of the libs mentioned in that article is https://github.com/kevintweber/KtwDatabaseMenuBundle

**Comment by Guite** [comment]
The idea here is to replace extmenu and menutree with one twig-based solution. So we could just introduce a new menu and mark the old blocks as deprecated.

**Comment by Guite** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RwknNCNK&#x2F;2-menu-blocks-2031-2675-2676"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Menu blocks #2031 #2675 #2676</a>

**Comment by craigh** [comment]
This is now implemented.
