### ISSUE TITLE
Remove Symfony Validator Compiler Pass

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2038]
The compiler pass added in https://github.com/zikula/core/pull/1871/files#diff-9cc922b068f517148fdca797477cb33dR23 should no longer be necessary, as https://github.com/symfony/symfony/issues/11909 got closed by https://github.com/symfony/symfony/pull/12151.

This needs to be tested of course.

**Comment by craigh** [comment]
@Guite can you check this again?

**Comment by craigh** [comment]
:+1:
