### ISSUE TITLE
Date mistakes with new user attribute put in

### ISSUE THREAD

**Issue by Alexalter** [zikula/core#2071]
WARN (4): E_WARNING: strftime() expects parameter 2 to be long, string given in DateUtil.php Zeile 831 <br />WARN (4): E_WARNING: strftime() expects parameter 2 to be long, string given in DateUtil.php Zeile 832 <br />WARN (4): E_WARNING: strftime() expects parameter 2 to be long, string given in DateUtil.php Zeile 833 <br />WARN (4): E_WARNING: strftime() expects parameter 2 to be long, string given in DateUtil.php Zeile 834 <br />WARN (4): E_WARNING: strftime() expects parameter 2 to be long, string given in DateUtil.php Zeile 837 <br />

Zikula 1.3.9
http://www.al-werner.de
Grüß Alex

**Comment by Portugao** [comment]
@Alexalter 
Ich bin etwas verwirrt, weil der Thread im deutschen Forum, den Du oben angegeben hast von 2012 ist.
Ausserdem kann ich das Problem mit 1.3.9 nicht nachstellen.
Mehr Infos sind hier notwendig.

**Comment by Alexalter** [comment]
Hi Michael!

Bei Benutzerprofil bearbeiten
bevor das Geb Datum eintragen in Feld steht so ein Fehler
![benutzerprofil_bearbeiten](https://cloud.githubusercontent.com/assets/9826965/5978144/dfa04806-a89d-11e4-96d3-a3b826cedc90.jpg)

in Atribut habe ich einfach so Geb Datum eingetragen in Zikula 1.3.9, auch in Zikula 1.2.9, aber in Zikula 1.2.9 sind kein so ein Fehler alles richtig funktioniert.

sieht so aus
![geb_dat_atribut](https://cloud.githubusercontent.com/assets/9826965/5978248/c7799588-a89e-11e4-9880-72886b811bad.jpg)

Ich hoffe reicht das zum Information

Schone Grüße Alex

**Comment by Alexalter** [comment]
und in Zikula 1.2.9 bevor Geburtsdatum eintragen steht heutige Datum.

**Comment by Portugao** [comment]
Yo. Jetzt ist klar, worum es geht und ich kann die Fehlermeldung reproduzieren.

**Comment by Portugao** [comment]
This is an issue in Profile, i think.
How to handle this? Profile is modified to 1.4 standards, if i'm right?
@Guite , @craigh , @cmfcmf

**Comment by craigh** [comment]
Profile is up-to-date but bugs in a few areas, yes.

**Comment by Guite** [comment]
The issue should be recreated at the Profile project's tracker:
https://github.com/zikula-modules/Profile/issues

The master branch containing version 2.0.0-beta is for Zikula 1.4.0.
There is another branch also at https://github.com/zikula-modules/Profile/tree/release-1.6.1 which is the latest release for 1.3.

**Comment by Portugao** [comment]
Will do that.

**Comment by Portugao** [comment]
Moved to:
https://github.com/zikula-modules/Profile/issues/47

**Comment by Alexalter** [comment]
Endlich gelöst:muscle:, in /lib/util/DateUtil.php Zeile 831
<code>
$trformat = preg_replace('/%a/', $day_of_week_short[(int)strftime('%w', $timestamp)], $format);
$trformat = preg_replace('/%A/', $day_of_week_long[(int)strftime('%w', $timestamp)], $trformat);
$trformat = preg_replace('/%b/', $month_short[(int)strftime('%m', $timestamp) - 1], $trformat); $trformat = preg_replace('/%B/', $month_long[(int)strftime('%m', $timestamp) - 1], $trformat);
$trformat = preg_replace('/%Z/', $timezone, $trformat);

return strftime($trformat, $timestamp);
</code>

Muss so aus, sehe (int)

<code>
$trformat = preg_replace('/%a/', $day_of_week_short[strftime('%w', (int)$timestamp)], $format);
$trformat = preg_replace('/%A/', $day_of_week_long[strftime('%w', (int)$timestamp)], $trformat);
$trformat = preg_replace('/%b/', $month_short[strftime('%m', (int)$timestamp) - 1], $trformat);
$trformat = preg_replace('/%B/', $month_long[strftime('%m', (int)$timestamp) - 1], $trformat);
$trformat = preg_replace('/%Z/', $timezone, $trformat);

return strftime($trformat, (int)$timestamp);
</code>
