### ISSUE TITLE
Use Symfony locking mechanism

### ISSUE THREAD

**Issue by Guite** [zikula/core#2079]
We should utilize the lock handler functionality introduced in Symfony 2.6.

http://symfony.com/blog/new-in-symfony-2-6-lockhandler
- [ ] Writing into files
- [ ] Editing and updating database content.
- [ ] PageLock

**Comment by craigh** [comment]
@Guite please give use case for this feature or close this ticket. This is a **file** locking method, which zikula doesn't typically have need for. please advise.
