### ISSUE TITLE
Double email to admin on user registration

### ISSUE THREAD

**Issue by craigh** [zikula/core#2089]
Wrong-ish admin mails on new registration

you as an admin get the same email twice: Once when the user registers, second when he verifys his email.

**Comment by cmfcmf** [comment]
Okay, I've just reproduced it:
1. Activate "moderate registrations"
2. Insert an "E-mail address to notify of registrations"
3. Register a new account -> both admin and user get an email
4. verify account using the link in the user's email
5. approve account using the admin interface
6. both user and admin receive an email saying that the account has now been activated. The admin shouldn't receive one though.

**Comment by craigh** [comment]
@cmfcmf will you be fixing this? If not, please move it to 1.4.1 or 2.0.0

**Comment by cmfcmf** [comment]
Moved to 1.4.1.

**Comment by rallek** [comment]
mmh, for me it sounds like a feature :-)

On one of my sites I do have several unexperienced users. They asked me: 'Hey, I registered at the site, but I still do not have access.' And I can say: 'Yes you registered but still you did not approve'

If I would be asked I would want to stay with that feature. But I did not checked right now if the emails are different.

**Comment by Guite** [comment]
This problem does not exist anymore. I found some other smaller issues in the approval process though (mainly mail-related). Going to provide a PR for these.
