### ISSUE TITLE
Check how we override the Request

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2115]
We still have the old Zikula_Request thing around, make sure we override the request the proper way: http://symfony.com/doc/current/components/http_foundation/introduction.html#overriding-the-request

**Comment by craigh** [comment]
I agree that this is a won’t-fix because I’ve already removed `Zikula_Request` from `master` and if this works as is for 1.4, I think we can leave it. But it is possible I do not understand the issue entirely.
