### ISSUE TITLE
LegalModule vs. ProfileModule vs. RoutesModule

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2125]
The LegalModule uses `Zikula\LegalModule\` as namespace.
The ProfileModule uses `Zikula\Module\ProfileModule\` as namespace.
The RoutesModule uses `Zikula\RoutesModule\` as namespace.

Should the ProfileModule be refactored to use `Zikula\ProfileModule\`?

**Comment by Kaik** [comment]
Hi I was away for some time but now I'm trying to back on track.
I have setted up new enviroment Fedora 20 Netbeans github and composer. I would like to finish Intercom module and I'm lost with this PSR thing I have thought that PSR-0 is "kind of better" as all the system modules are like that so Intercom module is PSR-0. Now all mentioned modules are PSR-4 and they load nicely via github. I have added Intercom into zikula composer.json and update but that did not work 
        "zikula/intercom-module": "3.0.0",
...
        {
            "type": "vcs",
            "url": "https://github.com/Kaik/InterCom"
        },  
no composer.jason error
        {
            "type": "vcs",
            "url": "https://github.com/Kaik/InterCom/Zikula/Module/IntercomModule"
        },
end with this
 [RuntimeException]                                                                                                                                                                                                                                     
  Failed to execute git clone --mirror 'https://aaee4666b11b027c3670b523ffacae9dbde34f4e:***@github.com/Kaik/InterCom/Zikula/Module/IntercomModule.git' '/home/Kaik/.composer/cache/vcs/git-github.com-Kaik-InterCom-Zikula-Module-IntercomModule.git/'  
  Cloning into bare repository '/home/Kaik/.composer/cache/vcs/git-github.com-Kaik-InterCom-Zikula-Module-IntercomModule.git'...                                                                                                                         
  fatal: repository 'https://aaee4666b11b027c3670b523ffacae9dbde34f4e:x-oauth-basic@github.com/Kaik/InterCom/Zikula/Module/IntercomModule.git/' not found

Could you please help me with doing same on PSR-0 or should I refactor to PSR-4?

**Comment by craigh** [comment]
If you have a choice, psr-4 is easier, imo.
