### ISSUE TITLE
[Distribution] Reconsider publishing "full CMS" versions of Zikula

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2130]
I know there was a time when Zikula was published in conjunction with some important modules. We could start doing so again.
It shouldn't even be that complicated, now that I understood how Jenkins works.

Do you generally like the idea? Do you remember why the "full CMS" builds were stopped?

**Comment by Guite** [comment]
Closing as for [Zikula 4 slimming diet](https://github.com/zikula/core/blob/main/ZIKULA-4.0.md) - we won't push self-made CMS again.
