### ISSUE TITLE
make the first zk-contact more polite

### ISSUE THREAD

**Issue by rallek** [zikula/core#2144]
feature request:

I uploaded the zip to my shared service hosting, logged in for ssh and unzip my download. Than I went to my browser and opend the root (mysite.de/). There I got an unfriendly message:

````
Whoops, looks like something went wrong.
1/1 RuntimeException in Kernel.php line 634: Unable to create the cache directory (/www/htdocs/w005fe6d/zk-test/Zikula_Core-1.4.0/app/cache/dev)
````

It would be great if we can provide an intruction page in this case. Something like all demands listet. And all things ok are listed in green, all nok are in read with a short message about how to solve this issue.

I am testing 1.4 ci build 358

**Comment by Portugao** [comment]
I just get 1.4.x installed and i noticed many folders and some files have to be writable.
It should help to communicate it, where we get a notice, what is ok and what is missed (like php version is ok or folder 'userdata' is not writable, make it writable and so on).

**Comment by craigh** [comment]
https://github.com/craigh/core/blob/InstallerToBundle/INSTALL-1.4.0.md

**Comment by Portugao** [comment]
And that means that also all subfolders and files must be writable?
Because I get the message, that 'app/config/parameters.yml' has to be writable.

**Comment by craigh** [comment]
currently that is true (same with `config/config.php` btw) but with the new installer this will not be true. `app/config` will need to be writable and `config/`

**Comment by Portugao** [comment]
Ok. Thx for your reply. 
By the way i wish to give thanks to you for your work on the core. :smile:

**Comment by craigh** [comment]
thanks for testing!

**Comment by craigh** [comment]
@rallek - In the installer refactor, I've tried very hard to make it as "polite" as possible. After you have tested it, please address this ticket again. thank you.

**Comment by rallek** [comment]
@craigh - the old installer was also not unpolite ;-)

What I want to see: The index.php should first check it the both directories are writable and give a polite message to make them writable.

I bet more than 50% of people who are trying to install will struggle with this topic already.

**Comment by Guite** [comment]
Maybe user-friendly is a more adequate word than polite here.

**Comment by rallek** [comment]
yes, you are right. That is what I mean

**Comment by Guite** [comment]
Closing. If you have more to add, please create separate issues for each aspect.
