### ISSUE TITLE
go.zikula.org is a 404

### ISSUE THREAD

**Issue by rallek** [zikula/core#2147]
fresh install of 1.4.0 dev.

The admin/extension (http://140.mysite.org/extensions/modules) is showing the note:
"Note: Modules are software that extends the functionality of a site. There is a wide choice of add-on modules available from the Extensions database."

Extensions database is a link: go.zikula.org/inappstore

following the link we are comming to http://zikula.org/?module=Wiki&tag=TryZikula13

This site is opening in the same window and is 404.

It should become a valid target and open in a new window.

**Comment by craigh** [comment]
ping @drak please.

**Comment by Guite** [comment]
Just thinking: another possibility to fix this (without access to go.zikula.org) would be a rewrite rule at zikula.org.

**Comment by rallek** [comment]
Or use go.ziku.la

**Comment by Guite** [comment]
To explain the suggestion of rallek: ziku.la is owned by me.

**Comment by craigh** [comment]
if we are replacing the subdomain anyway, we should probably just use the regular domain. see https://github.com/zikula/zikula.org/issues/23

**Comment by drak** [comment]
I've been using google's link thing for go.zikula.org but it might be better to just use server redirect rules on zikula.org

**Comment by craigh** [comment]
what is "google's link thing" ?

**Comment by cmfcmf** [comment]
@drak I think it would be easiest to keep using the current system, because it seems to work reliably. It would be great if you could give anyone of us access to it.

**Comment by Guite** [comment]
This problem does not exist in 1.4.3 anymore, because the note is gone (probably during switching to Twig).

**Comment by craigh** [comment]
yes - the error is gone for 1.4.3 but the problem will continue to exist for old installations.

**Comment by Guite** [comment]
I doubt we can do sth about it
