### ISSUE TITLE
[Mailer] Precheck which transport methods are actually working and available

### ISSUE THREAD

**Issue by rallek** [zikula/core#2148]
![mailer-module-settings-warning](https://cloud.githubusercontent.com/assets/935250/5567911/c6602856-8f4e-11e4-8153-087bcb292aa5.jpg)

for someone like me it would be better not to list smtp and sendmail in the dropdown and make an information instead a warning. The information should explain if you configure proc_* you can use also smtp and sendmail.

Not important but more user friendly ;). I do not like warnings in my installation if I can not fix it. In my case in shared hosting I can not fix.

**Comment by Guite** [comment]
Fixed in #3009
