### ISSUE TITLE
categories are labeled "undefined"

### ISSUE THREAD

**Issue by rallek** [zikula/core#2151]
![category-settings](https://cloud.githubusercontent.com/assets/935250/5569966/9f5f30f0-8f79-11e4-99e4-ec44443bdfba.jpg)

This is comming from a fresh 1.4.0 dev install. Even if I change one it remains as "undefined"

**Comment by craigh** [comment]
this is probably an issue with eh categories installer

**Comment by cmfcmf** [comment]
> this is probably an issue with the categories installer

I was thinking of a JavaScript problem due to the typical js-error "undefined".

**Comment by craigh** [comment]
I only thought that because in my new installer, the categories module is not installed properly. did it install without error for you?

**Comment by Guite** [comment]
This is very probably a JS problem. The tooltip contained in the screenshot shows that the titles are actually installed properly.

**Comment by Guite** [comment]
Fixed by #2163
