### ISSUE TITLE
Raise php requirement to >=5.3.8 ?

### ISSUE THREAD

**Issue by craigh** [zikula/core#2161]
Current requirement is 5.3.3 because [Symfony requires the same](http://symfony.com/doc/current/reference/requirements.html) but we note in our docs (as do they) that `<5.3.4` has problems and `<5.3.8` has problems. Which in my opinion means ZIkula won't run in those versions. Seems easier to just require `>=5.3.8` and also check for `5.3.16` as it is also buggy.

thoughts?

**Comment by Guite** [comment]
:+1:  from me

**Comment by cmfcmf** [comment]
:+1: Better to officially raise the requirement now instead of fiddling with weird error messages when users use these PHP versions.

**Comment by Guite** [comment]
While we are discussing here: As stated in http://symfony.com/blog/a-week-of-symfony-418-29-december-2014-04-january-2015 Symfony 3 is going to require PHP 5.5.9.

**Comment by Portugao** [comment]
Puh. That is a very high requirement.

**Comment by Guite** [comment]
Yeah, probably something for 2.0.0 instead of 1.4.0.

**Comment by Portugao** [comment]
:+1:

**Comment by craigh** [comment]
php usage stats: http://w3techs.com/technologies/details/pl-php/all/all
