### ISSUE TITLE
[Installer] ideas

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2162]
Here are some points I thought you might or might not want to add to the installer while re-doing it @craigh:
- [ ] Consider to add some kind of newsletter signup using the admin account address. It would send a request to `go.zikula.org/newsletter/<email>/` (or similar). It could include the following options (`i.` and `ii.` could be combined):
  1. Send me an email when there is a new ZK Version
  2. Send me an email when there is a security related fix
  3. Allow the Zikula Team to send me occasional emails about ZK development, roadmap updates, ...
- [x] Make sure the CI Build / the `build.xml` script makes all needed folders writable
- [x] If Zikula can be installed via a command, add this command to the Travis script and install Zikula with different databases on every Travis build and see if it works.
- [x] Set initial focus to the first input field of every page (using JS)
- [ ] Handle "mod_rewrite" not installed: Add another requirements check: 

``` php
if (function_exists('apache_get_modules') && !in_array('mod_rewrite', apache_get_modules())) {
    // Check if installed in a subdirectory TODO: Is this the correct way?
    if ($request->getBaseURI() != "/") {
        $error = true;
        $message = "You don't have the Apache module 'mod_rewrite' enabled. It is recommend to install / enable it. If you can't enable it, you need to make the .htaccess file in the Zikula root directory writable.";
    }
}
// later during installation:
// @todo @cmfcmf
```

```
# add to .htaccess
<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^\/tmp\/Zikula_Core-1\.4\.0\/$ /tmp/Zikula_Core-1.4.0/index.php
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>
```
- [ ] more?

**Comment by craigh** [comment]
reassigning this back to you. IMO, the news letter thing should wait until 2.0.0 and the other stuff is your areas.

**Comment by rallek** [comment]
Add some more information in the success Email about next typical steps )e.g. what to do in the admin like actvate leagel, profile do some settings, add some more modules, ...

**Comment by Guite** [comment]
:-1: for using `apache_get_modules()`, we discussed that yesterday: as this function does not work when PHP is used via CGI, it could lead to false positives

**Comment by Guite** [comment]
> Handle "mod_rewrite" not installed: Add another requirements check:

The core *should* now work even without mod_rewrite. See [this fallback](https://github.com/zikula/core/blob/master/public/.htaccess#L70-L78) which was copied from [this recipe](https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess#L58-L66)

**Comment by craigh** [comment]
I think we should close this ticket then.
