### ISSUE TITLE
[1.4] && [1.3] CHANGELOG modifications

### ISSUE THREAD

**Issue by craigh** [zikula/core#2167]
I suggest following the [symfony](https://github.com/symfony/symfony) model with regard to changelogs.

There, you can see multiple changelogs - one for each major version. And all at the **root level** of the repo.

We should do the same at the root of both 1.4 and 1.3 branch and split them into separate files:

```
CHANGELOG-1.3.md
CHANGELOG-1.4.md
```

this would make merging changes up easier and tracking changes easier.

refs https://github.com/zikula/core/pull/2166#issuecomment-68814708

**Comment by Guite** [comment]
:+1:

**Comment by craigh** [comment]
@cmfcmf is it possible to have the CI move files from the repository root to the `/docs` folder automatically?

**Comment by Guite** [comment]
Yes, it is possible (you know the `mv` command?).

**Comment by craigh** [comment]
sure, I know `mv`. I just don't know how to make CI use it :laughing: 

my thinking is that we keep the CHANGELOG and other files at the root of the repo but automatically move them to the /docs folder in the build so they aren't lost in the process.

**Comment by craigh** [comment]
done in #2172
