### ISSUE TITLE
Documentation via Github Pages

### ISSUE THREAD

**Issue by craigh** [zikula/core#2173]
we should consider using github pages as a documentation solution

https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by Portugao** [comment]
:+1: 
Good idea.

**Comment by Guite** [comment]
Like it, too.

**Comment by craigh** [comment]
refs #2503

**Comment by craigh** [comment]
https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Comment by Guite** [comment]
http://couscous.io

**Comment by Guite** [comment]
Docs are now automatically deployed to https://docs.ziku.la/

Closed.
