### ISSUE TITLE
Plugin "thumbs": Fixed withd and auto height

### ISSUE THREAD

**Issue by trichers** [zikula/core#2174]
How can I use the {thumbs} plugin to build an image, where the width is fixed (e.g. 200px) and the height gets automatically?

**Comment by espaan** [comment]
Hi, as mentioned in the German support forum:

It is not possible directly :-( But can be done via Imagine.

For example
http://imagine.readthedocs.org/en/latest/usage/introduction.html#architecture und die Kommentare
Quote

    ---
    How to resize maintaining aspect ratio ?
    ---
    $imagine = new \Imagine\Gd\Imagine();
    $image = $imagine->open( $_FILES['file']['tmp_name'] );

    $image->resize(
    // get original size and set width (widen) or height (heighten).
    // width or height will be set maintaining aspect ratio.
    $image->getSize()->widen( 700 )
    );
    $image->save( 'path/to/filename.jpg' );
    ---
    This could really do with a section in the docs. As 'Resize' is under 'Introduction' when it should probably have it's own section with the other 'Basics'

or 
http://stackoverflow.com/questions/25703532/imagine-with-zf2-ratio-resize
http://harikt.com/blog/2012/12/17/resize-image-keeping-aspect-ratio-in-imagine/

It would be really nice to extend out thumb plugin with an 
```
width=200px height=auto
```
and vice versa option that does the above mentioned solutions internally.

**Comment by cmfcmf** [comment]
So this is a feature request.

**Comment by espaan** [comment]
Yes I would consider it that way. Missing feature :-)

**Comment by espaan** [comment]
Followup. It's quite easy to add in the Imagine plugin where you can omiss width or height or set width or height to 'auto' and then re-calculate the dimensions from the imagesize. It works in my test install. I have to provide a PR later on.

**Comment by craigh** [comment]
Which core version should this apply to?

**Comment by espaan** [comment]
13 and 14

I'm  updating this part too in the imagine the plugin.

**Comment by Portugao** [comment]
Could be closed if i'm not wrong.

**Comment by espaan** [comment]
Yes this is solved with the updated imagine plugin

**Comment by Portugao** [comment]
:+1:
