### ISSUE TITLE
[Routes] Exposed routes not being added 

### ISSUE THREAD

**Issue by craigh** [zikula/core#2180]
JMS/I18nRoutingBundle\Router\I18nRouter::getRouteCollection() returns all routes correctly but the `expose` option is set to a value of `1` instead of `true` or `'true'`

then

\FOS\JsRoutingBundle\Extractor\ExposedRoutesExtractor::isRouteExposed compares the value like so:
```php
        return true === $route->getOption('expose')
            || 'true' === $route->getOption('expose')
            || ('' !== $pattern && preg_match('#' . $pattern . '#', $name));
```

and it fails.

**Comment by Guite** [comment]
Probably fixed in https://github.com/Guite/MostGenerator/commit/2bf19fe044cd5e5cb7b68d35b2425c91b459bbaf and e73ce8360597a2ae03b4fe1d2677746613cc6429

**Comment by craigh** [comment]
I can confirm that fix https://github.com/zikula/core/commit/e73ce8360597a2ae03b4fe1d2677746613cc6429 works but it requires a route reload first.
