### ISSUE TITLE
Enable CSRF protection in install/upgrade forms

### ISSUE THREAD

**Issue by craigh** [zikula/core#2186]
CSRF form protection is currently disabled in all CoreInstallerBundle forms (see for example:  https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/CreateAdminType.php#L74)

It needs to be re-enabled when it can be figured out why it doesn't work. I'm guessing some kind of session issue.

refs #2172 #2187

**Comment by Guite** [comment]
This is definitely related to sessions, but very difficult to find.

The token is set in `SessionTokenStorage#setToken()`:

    $this->session->set($this->namespace.'/'.$tokenId, (string) $token);
    die('AAAA: ' . print_r($this->session->all()));

In the next request it is checked in `SessionTokenStorage#hasToken()`:

        die('AAAA: ' . print_r($this->session->all()));
        return $this->session->has($this->namespace.'/'.$tokenId);

In the second `die()` statement the array is empty.

**Comment by Guite** [comment]
Moved to 1.4.6.

**Comment by Guite** [comment]
See also https://github.com/symfony/symfony/issues/13464
