### ISSUE TITLE
Post-install/upgrade login doesn't work

### ISSUE THREAD

**Issue by craigh** [zikula/core#2187]
after completing the install or upgrade process, the login doesn't work. I'm guessing this is a sessions issue.

refs #2172 #2186

**Comment by cmfcmf** [comment]
Great!

**Comment by cmfcmf** [comment]
I've just installed a fresh clone of the core and the login didn't work.

**Comment by craigh** [comment]
I assume you did a http install?

**Comment by cmfcmf** [comment]
Yes.

**Comment by craigh** [comment]
postponed to 1.4.3

**Comment by craigh** [comment]
This is still listed as fixed in the changelog

**Comment by craigh** [comment]
This still works for me...

**Comment by Guite** [comment]
It worked for me about 3 days ago, too.

**Comment by cmfcmf** [comment]
I've tried this again and it still doesn't work for me.

**Comment by craigh** [comment]
please give more details on "didn't work" if possible.

**Comment by cmfcmf** [comment]
Well, I get to this page: 
> http://localhost:8080/login?returnpage=http%253A%252F%252Flocalhost%253A8080%252Fadminpanel%252Fpanel

and see an "Access Denied" flash message. After login, I am then redirected to the admin panel as expected.

**Comment by craigh** [comment]
any more on the attempt to send email issue?

**Comment by cmfcmf** [comment]
I had disabled the sendemail check in my latest test and that's why it wanted to redirect me to the adminpanel and not to the mailer settings - which was the only notable difference.

**Comment by craigh** [comment]
I tested a "clean" build direct from CI and it works for me here. Apache on php 5.5.26

**Comment by Guite** [comment]
Just did a fresh install locally and it worked again for me.

**Comment by craigh** [comment]
@Guite environment?

**Comment by Guite** [comment]
Apache 2.4.12-2ubuntu2 with PHP 5.6.11+dfsg-1ubuntu3.1.

**Comment by cmfcmf** [comment]
Hmm weird. Maybe it really is a problem with my environment.. Close if you like.

**Comment by Guite** [comment]
@cmfcmf which environment are you using? anything "special" about it?

**Comment by cmfcmf** [comment]
I was using the Vagrant environment which is Ubuntu 14.04 + PHP 5.5.

**Comment by Guite** [comment]
I think we should ask more testers here. If it works on typical servers we can close it.
@rallek @shefik @kaik can you verify whether this works for you?

**Comment by craigh** [comment]
how to test:

1) download latest CI build from http://‎ci.zikula.org 
2) create a "clean" environment (new DB, new directory)
3) run the http install process
4) note whether after the final install step, you are directed to `/adminpanel/panel` or shown an error and asked to login again.

**Comment by craigh** [comment]
@rallek do you have time to check this also?

**Comment by rallek** [comment]
I installed a new core. There I.was logged in perfectly. I am fine with this.

**Comment by craigh** [comment]
closing this since success = 3 and fail  = 1
