### ISSUE TITLE
Installation stops at "Begin Installer"

### ISSUE THREAD

**Issue by rallek** [zikula/core#2190]
I am testing to install via web. I downloaded the zip from ci, uploaded to my webspace (all-inkl with ssh access) and unziped the file.

After changing the two folder permissions I was NOT able to install. The owner of the files is wrong. In the management console of all-inkl I am able to change the permission to the "PHP-User" recursive to all files and folders. NOW I am able to install.

But the install process stops after database and admin account settings.

Now I am on /install/ajaxinstaller#install-fieldset

clicking at "Begin Installer" is doing nothing

CI Build 389

PHP 5.4.34

**Comment by craigh** [comment]
try recursively making the entire app/config directory writable

**Comment by rallek** [comment]
tja, since the owner is the PHP-User I do not have the permission to change  to 777 :-(

**Comment by craigh** [comment]
I'm not sure how these types of issues can be solved by zikula. sometimes the user and their host will have to meet certain requirements in order to install.

can you look and see if a `app/config/custom_parameters.yml` file exists?

**Comment by craigh** [comment]
the reason it is stuck at "Begin Installer" is the javascript is not loaded. see #2192

and I checked your install and the `app/config/custom_parameters.yml` file DOES exist and it is correct for the stage you attained.

**Comment by rallek** [comment]
I did a new test. I unzipped at my home computer, uploaded all files via ftp and changed the permissions of app/cahc and app/logs.

Now I start by calling my website in a browser. The installation failed due to wrong ownership of the files. The following is coming:

Failed to copy "/www/htdocs/w012cf87/craigh.k62.org/ftp-upload/app/config/parameters.yml" to "/www/htdocs/w012cf87/craigh.k62.org/ftp-upload/app/config/custom_parameters.yml" because target file could not be opened for writing. 

for me this is a blocker for usage in shared hosting environment :-( The ownership of the ftp files is different than the PHP-user. More folders need to have write permissions I guess.

**Comment by craigh** [comment]
talk talking with your provider. I'm guessing that you will need to change owner of files, not just write permissions. I don't think this is something that zikula could fix. It seems your provider is a little different than most.

**Comment by Portugao** [comment]
After upload zikula the file app/config/custom_parameters.yml on my server has the permission 0666 so it is clear that the writing fails with this error message.....

**Comment by craigh** [comment]
> After upload zikula the file app/config/custom_parameters.yml on my server has the permission 0666 so it is clear that the writing fails with this error message.....

I'm sorry this is not clear at all. Maybe you could explain further? Are you installing? upgrading? If **installing**, there should be no `custom_parameters.yml` file before you being. If it exists, it was created by the installer and the perms should be fine. If you are **upgrading** then YOU created the file and should control the perms.

**Comment by craigh** [comment]
> the reason it is stuck at "Begin Installer" is the javascript is not loaded. see #2192

if you started an installer and it stopped at this stage, then this bug is not yet fixed and it won't work.

**Comment by Portugao** [comment]
Ok. I see.

**Comment by craigh** [comment]
this is fixed now. try build 402

http://ci.zikula.org/job/Zikula_Core-1.4.0/
