### ISSUE TITLE
CI not installing assets of bundles

### ISSUE THREAD

**Issue by craigh** [zikula/core#2192]
CI should be installing all the bundle assets and it apparently is not (I think it used to). For example, the CoreInstallerBundle has several css and js files that should be copied to `/web/bundles/zikulacoreinstaller`

refs #2190

ping @cmfcmf @Guite @rallek

**Comment by cmfcmf** [comment]
Make also sure the translation of the route works, depends on #2138.

**Comment by craigh** [comment]
command in build.cml wools like this:

```xml
        <exec command="${workspace}/source/composer.phar install --prefer-dist --no-scripts --ignore-platform-reqs" checkreturn="true" />
```

but instruction to install in the README.md are `composer update` (not install)

@cmfcmf any ideas here? I'm not really familiar enough with composer nor the CI process..

@drak?

**Comment by craigh** [comment]
maybe remove the `--no-scripts` part?

**Comment by craigh** [comment]
ok - the `--no-scripts` part is correct I think, because later there is this:

```shell
<!-- install assets -->
<exec command="php ${packagepath}/app/console assets:install ${packagepath}/web"/>
```

but the problem is that command is not running `\Zikula\Bundle\CoreBundle\Command\AssetsInstallCommand` but rather is running `\Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand` (at least I'm pretty sure). And so, some things aren't getting installed. BUT if I run `php app/console assets:install` from the CLI now, I get ONLY the ZIkula assets and none of the vendor assets! AHHH

I'd like some help please.

**Comment by craigh** [comment]
fixed by forcing timezone set in https://github.com/zikula/core/commit/108df009f35033560c70024f8b3d13f23c1c0e1c
