### ISSUE TITLE
set timezone in php.ini at CI server

### ISSUE THREAD

**Issue by craigh** [zikula/core#2196]
In order for the build to complete successfully, the timezone must be properly set at the CI server.

When this is complete, the hack added in https://github.com/zikula/core/commit/108df009f35033560c70024f8b3d13f23c1c0e1c can probably be removed.

**Comment by craigh** [comment]
drak said he set the timezone:

> [1/21/15, 4:35:01 PM] Craig Heydenburg: help
I need the timezone set for the CI server
php is failing there
[1/21/15, 6:01:59 PM] dordrak: hi
[1/21/15, 8:05:00 PM] dordrak: Done

**Comment by craigh** [comment]
but there are many Jenkins errors occurring there now for some reason.

**Comment by Guite** [comment]
I fixed the Jenkins problem.
You can now check whether this ticket is resolved or not.

**Comment by cmfcmf** [comment]
> Service Temporarily Unavailable

http://ci.zikula.org/

**Comment by Guite** [comment]
Occurs sometimes when I am restarting it. There are still some problems to be solved wrt Git.

**Comment by craigh** [comment]
@Guite you might be hitting the github access limit with repeated attempts at generating your other build (hence the 'credentials' error in the log). I ran in to that the other day as well.

**Comment by craigh** [comment]
closing this. please continue discussion on this issue on slack.
