### ISSUE TITLE
Redirect to /install.php, if Zikula is not already installed

### ISSUE THREAD

**Issue by shefik** [zikula/core#2200]
If Zikula 1.4.0 is not already installed, and you go to "/index.php", it currently redirects to "/install", when it should redirect to "/install.php".

**Comment by cmfcmf** [comment]
@shefik this is expected behaviour. The installer has been rewritten.

**Comment by shefik** [comment]
@cmfcmf Has the new installer been merged yet, because going to "/install" is not working directly. Still need to use install.php for access at the moment.

**Comment by craigh** [comment]
There is no file called install.php

**Comment by craigh** [comment]
Read the new docs
