### ISSUE TITLE
Jenkins is Failing at ci.zikula.org

### ISSUE THREAD

**Issue by shefik** [zikula/core#2203]
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.io.IOException: Unable to read /var/lib/jenkins/config.xml

http://ci.zikula.org

**Comment by craigh** [comment]
This is a Jenkins plugin problem. not us.

**Comment by cmfcmf** [comment]
Thanks @shefik for your report, though!

**Comment by shefik** [comment]
But, what happens now? ci.zikula.org is still down.

**Comment by rallek** [comment]
E.g. waiting for the Jenkins fix?
