### ISSUE TITLE
[CoreInstallerBundle] one file install routine

### ISSUE THREAD

**Issue by rallek** [zikula/core#2204]
Feature request for 2.0.0

Owncloud is offering a very simple install solution for shared hosting. 
1. You have to download a file (e.g. setup-zikula.php). -> https://download.owncloud.com/download/community/setup-owncloud.php
2. Upload to webserver root
3. call mysite.tld/setup-zikula.php
4. The script is checking all requirements.
   - If something is not fullfilled you will get an answer and install stops. 
   -  If all is fine no info is shown. The script is downloading and configuring everything. At the end you will be asked for the database (even with no database but sqlite is possible for small installation) and the initial user account. The setup-zikula.php is deleted automatically.
5. automatic login with the created account and enjoy. You will be guided to the initiall setup.

Great script! all permissions are correct everything is running perfect!

**Comment by shefik** [comment]
@rallek Would this be more efficient to execute as a command-line script via /app/console?

**Comment by rallek** [comment]
Of course. Shared hosting normally do not have a command line

**Comment by rallek** [comment]
The nice upgrade function of MediaModule might be the way we would like to see in Zikula (and its extensions)

**Comment by Guite** [comment]
Our custom installer is gone, as we will be reusing the Symfony installer. In future we will not have Zikula containing Symfony stuff anymore. Instead, we will be using Symfony requiring additional Zikula bundles. Hence, closing this as won't fix.
