### ISSUE TITLE
Categories tree bugs

### ISSUE THREAD

**Issue by Guite** [zikula/core#2206]
Follow-up from #2189: must be reviewed and fine-tuned, there are some minor bugs left.

* the different context menu actions 
* drag n drop

**Comment by craigh** [comment]
problems remaining:
 - [ ] copy node with children
 - [ ] redraw of tree graphic elements on dynamic (ajax) insert

ping @jusuff

**Comment by craigh** [comment]
note to @Guite : this was NOT an easy pick :stuck_out_tongue_winking_eye:

**Comment by craigh** [comment]
closed by #2253
