### ISSUE TITLE
Extend and improve CI builds

### ISSUE THREAD

**Issue by Guite** [zikula/core#2210]
The CI job needs some functional improvements:

* Unit tests
* Source code metrics
* Coding style and bad coding violations

**Comment by cmfcmf** [comment]
We could use CodeClimate for metrics and violations: https://codeclimate.com/github/zikula/core/

**Comment by Guite** [comment]
Unit tests are already done by Travis and coding style is checked by StyleCI. So both topics are not required for Jenkins.

Thus in theory this ticket can be closed. Going to create another one for codeclimate.
