### ISSUE TITLE
Problem Filter and Date

### ISSUE THREAD

**Issue by trichers** [zikula/core#2211]
If I use a filter with a date, it works, but this message is showed:
WARN (4): E_WARNING: strptime() expects parameter 1 to be string, object given in Date.php Zeile 194 
I used. filter=kalenderdatumende^ge^now

**Comment by Guite** [comment]
Where do you use which filter? Clip module?
Which core version?

**Comment by trichers** [comment]
I use Zikula 1.3.10 and Clip 0.9.4
I have a date-field in Clip (kalenderdatumende) and want to ask which pid is newer or older than today

**Comment by Portugao** [comment]
Please show the code!

**Comment by trichers** [comment]
I use it in a Link like: &filter=kalenderdatumanfang^ge^now 
and I tested it with an real date
&filter=kalenderdatumanfang^ge^2015-1-31

**Comment by Portugao** [comment]
Puh.
I'm not familiar with clip, so the fragments of your code does not help me.
Please show the complete code, you use. I have to understand the issue.

**Comment by Portugao** [comment]
Not an issue of the core.
Can be closed.

**Comment by matheo** [comment]
@trichers Try the latest commit to Clip 0.9 Thomas.
https://github.com/zikula-modules/Clip/tree/0.9
