### ISSUE TITLE
Incorrect Link to Installation Guide 

### ISSUE THREAD

**Issue by shefik** [zikula/core#2212]
During the installation process, there is a long to the "Insertion Guide". It is incorrectly pointing to:

/docs/en/INSTALL.md

When the existing file is:

/docs/en/INSTALL-1.4.0.md

Also, it seems unnecessary to have the link open via onclick=\"window.open('%2$s');return false;\", when target="_blank" can be used instead.

**Comment by craigh** [comment]
I can find no instances of `INSTALL.md` or `docs/en/INSTALL.md` or `insertion guide` in the core. please update your pull and provide more specific information about the location of the error.

re-open if you have more information. thanks!

**Comment by shefik** [comment]
Ok, I see that I was using an outdated POT file. After I updated, the strings I mentioned are obsolete.
