### ISSUE TITLE
Provide a release candidate

### ISSUE THREAD

**Issue by Guite** [zikula/core#2213]
A first RC could be built and published.

**Comment by Topiatic** [comment]
:)

**Comment by cmfcmf** [comment]
If it's also released and tagged at GitHub (as `prerelease`) it should fully automatically appear at the EL and http://zikula.org.

**Comment by cmfcmf** [comment]
The RC should also probably have debug set to false and env to prod.

**Comment by craigh** [comment]
we probably also need to decide on specific vendor releases instead of dev/master. there is a ticket about that somewhere?

**Comment by Guite** [comment]
Yes: #2111 - just moved to 1.4.0 again.

**Comment by Guite** [comment]
http://symfony.com/blog/symfony-2-6-4-released although it includes only bugfixes we need maybe to do a bit of retesting

**Comment by craigh** [comment]
would be auto included in the build and therefore tested as part of the QA cycle

**Comment by craigh** [comment]
This is the final remaining ticket in 1.4.0 milestone. I think we are ready!

**Comment by craigh** [comment]
closed by #2264
