### ISSUE TITLE
Unable to access Themes admin

### ISSUE THREAD

**Issue by shefik** [zikula/core#2215]
These URLs are not accessible:

/themes/admin
/themes/admin/view

**Comment by Guite** [comment]
http://localhost/src/theme/admin/view works here on my test install. Not using the latest version there though.

@craigh @cmfcmf can you reproduce the problem maybe?

**Comment by Guite** [comment]
@shefik note it seems to be `theme/foo` instead of `themes/foo`.

**Comment by craigh** [comment]
the proper path is `/theme/admin` (no 's')

**Comment by shefik** [comment]
The site currently routes to "themes".

**Comment by shefik** [comment]
These are the steps to reproduce:

1. Go to: /extensions/modules?letter=Z

2. Edit "ZikulaThemeModule" by changing "Module URL" from "theme" to "themes".

The problem also exists, if the Zikula POT file has been customized to map the string from "theme" to "themes".

This results in the module not being accessible, since the routing only allows "theme" to be accessible. Customizations are not permitted, as expected.

**Comment by Guite** [comment]
Relates to #1878 probably.

**Comment by craigh** [comment]
did you regenerate your routes after customizing them?

**Comment by shefik** [comment]
No, I did not regenerate the routes. Shouldn't that be done automatically, since an update to the URL was made?

**Comment by craigh** [comment]
I can confirm that the problem exists and that reloading routes makes no difference.

**Comment by craigh** [comment]
the base prefix (the part we are editing here *theme* -> *themes*) is not stored in the DB and therefore a reload should not be required.

**Comment by craigh** [comment]
@shefik is this the error you get also?

![screen shot 2015-02-02 at 9 46 15 am](https://cloud.githubusercontent.com/assets/350048/6002324/5beab512-aac0-11e4-9b10-471bdc857279.png)

**Comment by craigh** [comment]
this feels like an `.htaccess` problem. I've tried inserting breakpoints in `index.php` at the earliest possible time and the page load fails before reaching them, so the issue is happening earlier than that. I don't know much about what happens then. @Guite @cmfcmf your help is required.

**Comment by craigh** [comment]
interestingly, attempting to access `http://127.0.0.1/core.git/src/theme/admin` results in 404 and a proper Exception

**Comment by Guite** [comment]
Yeah, I guess the problem is that there exists a folder named `themes/`.

**Comment by craigh** [comment]
ah! so it is trying to match the filesystem first before being routed through the core!

**Comment by craigh** [comment]
confirmed! So, if I change the `$module['url']` to `themex` then it works as expected!

**Comment by craigh** [comment]
so maybe this is only a documentation problem? you cannot select a `url` that is the same as a directory name.

**Comment by shefik** [comment]
That is the error

**Comment by shefik** [comment]
Although, it worked before these changes with routes occurred.

**Comment by craigh** [comment]
that is because the url would have looked like `index.php?module=themes&type=admin&func=view` and now it is a "directory based" route. So the filesystem thinks `/themes` means a directory on the server and if that directory actually exists, you get this error. If it doesn't exist, then the php kicks in and the routing works.
