### ISSUE TITLE
remove beberlei/DoctrineExtensions

### ISSUE THREAD

**Issue by craigh** [zikula/core#2216]
It is deprecated in 1.4.0

**Comment by Guite** [comment]
Closed as dup of #2876

**Comment by craigh** [comment]
This is not the same as the extensions named in the other tickets

**Comment by craigh** [comment]
this references ["beberlei/DoctrineExtensions": "v0.3"](https://github.com/zikula/core/blob/1.4/composer.json#L91) in composer.json

not ["gedmo/doctrine-extensions": "2.4.*"](https://github.com/zikula/core/blob/1.4/composer.json#L64) or ["stof/doctrine-extensions-bundle": "~1.2.1"](https://github.com/zikula/core/blob/1.4/composer.json#L63)
