### ISSUE TITLE
Use Twig without templating sub system

### ISSUE THREAD

**Issue by craigh** [zikula/core#2221]
http://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen

investigate what we must change to take advantage of the improvements.

**Comment by Guite** [comment]
Very interesting also:
http://blog.twig.sensiolabs.org/post/108066687523/twig-1-17-0-released
http://blog.twig.sensiolabs.org/post/109117075188/twig-1-18-0-released

**Comment by craigh** [comment]
Looking into this - but sadly this cannot be done at the moment. To accomplish this we must [remove these two lines](https://github.com/zikula/core/blob/2761c1c7e0c9e764ed0d2146ab0fc29df269e36e/src/app/config/config.yml#L16-L17) of the `config.yml`  file

    # remove
    templating:
        engines: ['twig']


first - The service "bazinga.jstranslation.translation_dumper" has a dependency on the service "templating". (https://github.com/willdurand/BazingaJsTranslationBundle/issues/200)

second - `Zikula\ThemeModule\Bridge\Twig\EventEnabledTwigEngine` would need to be updated to decorate the twig environment and not the TwigEngine. This is doable I think.

These appear to be the only hold ups.

Where possible, modules/extensions should not inject the `templating` service but rather the `twig` service. But until we can get the JsBazinga vendor to update, I don't think this can be done.

**Comment by craigh** [comment]
bazinga has [changed their dependency to twig](https://github.com/willdurand/BazingaJsTranslationBundle/issues/200). So this ticket can proceed.

**Comment by Guite** [comment]
https://backbeat.tech/blog/how-to-remove-the-templating-component-from-a-symfony-project

**Comment by Guite** [comment]
Postponing to 3.0.

**Comment by Guite** [comment]
Did a few changes in 0307430f24e2985906355a5c9d2a458eb76d0d6a

Postponing changing the theme engine decorator due to https://github.com/symfony/symfony/pull/21035

**Comment by Guite** [comment]
https://github.com/symfony/symfony/pull/21035 has now been merged. I am going to continue with this issue #2221 as soon as we use Sf 4.3.
Note: test overriding capabilities and check that these still work after dropping templating component.

**Comment by Guite** [comment]
https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration

**Comment by Guite** [comment]
Also investigate whether the "new way" of implementing the theme engine decorator may allow also overriding non-module templates (from Symfony bundles and error pages etc.) on theme level.

**Comment by Guite** [comment]
Closing as completed.
