### ISSUE TITLE
remove IE7 & IE8 Browser Support

### ISSUE THREAD

**Issue by shefik** [zikula/core#2232]
Bootstrap 3 does not support IE 7 and 8, so we should stop supporting these browsers too.

For example, in the file:

@ZikulaCoreInstaller/structure.html.twig

at line 10, this this type of code should be removed:

The same applies for any modules and/or themes which might have any browser-specific code to IE 7 and IE 8.

**Comment by Guite** [comment]
IE8 is supported by Bootstrap, see http://getbootstrap.com/getting-started/#support

**Comment by shefik** [comment]
Ok, but suport for IE 7 should go.

Also, note this reference for IE 8 and IE 9:

http://getbootstrap.com/javascript/#callout-carousel-transitions

**Comment by craigh** [comment]
For Core 2.0.0 we can change things, but for now we still support what version 1.x.x always supported.

**Comment by Guite** [comment]
Closed due to #2287
