### ISSUE TITLE
[CoreInstallerBundle] Support custom installations

### ISSUE THREAD

**Issue by shefik** [zikula/core#2234]
Does the AJAX and CLI core installation code support the ability to have custom installations? Such as a means to have desired modules and its vars installed during the sequence at certain stages?

**Comment by craigh** [comment]
not really. of course, it could be extended to do so with some effort.

**Comment by shefik** [comment]
Refs. https://github.com/zikula/core/issues/2162

**Comment by Guite** [comment]
Our custom installer is gone, as we will be reusing the Symfony installer. In future we will not have Zikula containing Symfony stuff anymore. Instead, we will be using Symfony requiring additional Zikula bundles. Hence, closing this as won't fix.
