### ISSUE TITLE
Migrate Blocks to jQuery

### ISSUE THREAD

**Issue by Guite** [zikula/core#2236]
Refs #1214 

- [ ] General editing (views/Admin/modify.tpl)
- [ ] ExtMenu (views/Block/Extmenu/modify.tpl)
- [ ] MenuTree (Zikula.Menutree.Tree.js, contextmenu.js, functions.js, MenutreeTree.php)

**Comment by Guite** [comment]
@jusuff any chance you can help with MenuTree conversion?

**Comment by jusuff** [comment]
I have to check it. I'm not sure, but probably I did some partial menutree conversion to jQuery and should have it locally.

**Comment by craigh** [comment]
be sure to take a look at where we are currently and also the PR I have in progress.

**Comment by craigh** [comment]
oops. never mind that ;-) I thought this was a different ticket. :stuck_out_tongue_winking_eye:

**Comment by jusuff** [comment]
I suppose you meant categories? ;>

2015-02-13 11:44 GMT+01:00 Craig Heydenburg <notifications@github.com>:

**Comment by craigh** [comment]
of course ;-)

**Comment by jusuff** [comment]
For the record - I'm going to rewrite menutree to use jstree (the one used in categories)

**Comment by craigh** [comment]
hi @jusuff - how are you? have you looked into this at all?

**Comment by Guite** [comment]
Closing this one: general editing has no legacy JS anymore. And the two menu blocks won't be rewritten for 2.0, as we have a new menu module now.
