### ISSUE TITLE
add cache:warmup to installer

### ISSUE THREAD

**Issue by craigh** [zikula/core#2240]
add a cache warmup stage to installer so first page doesn't take so long for admin (makes it feel broken).

**Comment by cmfcmf** [comment]
Sounds like a good idea :+1:

**Comment by craigh** [comment]
note: use `cache_warmer` service.

**Comment by craigh** [comment]
I think this is done

see https://github.com/zikula/core/commit/9882cab555921315a9c7caa35c60831853d0813b#diff-2cccd7bf48b7a9cc113ff564acd802a8R147

clearing the cache also warms it.
