### ISSUE TITLE
Confusing email sending behaviour in Users administration

### ISSUE THREAD

**Issue by Guite** [zikula/core#2251]
When creating a user in the admin area you can select whether the password will be sent via email to the user's email address. If setting this to `no` one expects that no email is sent. Actually the user receives a mail in both cases though, just with a different content (admittedly there is a form note explaining that).
To make this more clear and to support the third case (sending no mail at all) I propose a select containing the following options:

* send no mail
* send mail without password (but password reminder)
* send mail with password

**Comment by Guite** [comment]
Already done in https://github.com/zikula/core/commit/04f73ee9541352042546b258df24c7d316c1f0c4

**Comment by cmfcmf** [comment]
Awesome :-D
