### ISSUE TITLE
Find an icon for the Routes module

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2252]

**Comment by craigh** [comment]
lower right of this: http://www.dreamstime.com/stock-illustration-rhombic-yellow-road-signs-arrows-directions-isolated-white-background-image42970539

**Comment by craigh** [comment]
or middle left of this: http://www.dreamstime.com/stock-illustration-rhombic-yellow-road-signs-arrows-directions-isolated-white-background-image42970522

**Comment by shefik** [comment]
+1 lower right of this: http://www.dreamstime.com/stock-illustration-rhombic-yellow-road-signs-arrows-directions-isolated-white-background-image42970539

**Comment by cmfcmf** [comment]
@rallek said:
> ![admin](https://cloud.githubusercontent.com/assets/935250/8512880/d35c4c8c-2356-11e5-9335-ded6e7491e8c.png)
>
> e.g. one with a road on it.

**Comment by Guite** [comment]
How about a very simple one, like http://fontawesome.io/icon/exchange/ ?

**Comment by cmfcmf** [comment]
:+1:
