### ISSUE TITLE
[1.3.9] POT file is not up-to-date

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2254]
POT file in tagged Zikula version 1.3.9 does not correspond to all strings in templates.

**Comment by craigh** [comment]
POT file is not kept in sync with development. It must be manually done before release.

**Comment by nmpetkov** [comment]
Yes, I realize that, but decided to create this issue, as obviously for 1.3.9 release had been forgotten.

**Comment by craigh** [comment]
gotcha :+1:

**Comment by Portugao** [comment]
How to create new pot file?

**Comment by craigh** [comment]
@Guite - did you create the pot file for the last 1.3.x release?

**Comment by Guite** [comment]
https://github.com/zikula-modules/Gettext/blob/master/Helper/xtractcore13.sh should do it

**Comment by cmfcmf** [comment]
Done in https://github.com/zikula/core/commit/7e339f39c4e55d42a462ff33d9fe9ec8c1e09c08.
