### ISSUE TITLE
Allow Github to provide data on newest release

### ISSUE THREAD

**Issue by craigh** [zikula/core#2258]
https://developer.github.com/changes/2015-02-18-new-releases-api-methods/

new methods available. Could be useful in providing info to installations. I know we already altered this some. maybe this is better?

**Comment by craigh** [comment]
@Kaik is this what you did? Or a better question - are we getting the Core releases from Github in your recent work?

**Comment by Kaik** [comment]
@craigh Yes we do get releases data from github https://github.com/zikula/core/blob/1.4/src/system/AdminModule/Helper/UpdateCheckHelper.php#L101
We are actually getting all mentioned data in link above.
Although there is one thing which may be better but it is on our side to "fix it".
As you can see on below picture there is a lots of data for already released versions
https://cloud.githubusercontent.com/assets/966910/12526281/2c1b8e56-c16c-11e5-8104-8428ed47b922.png
But when you use not released core version there is no github tag for it, and no information's I have just  added info that you use not yet released version and that is it. We may consider a pre release tag for current work or something like that I do not know if this is right thing with github workflow etc so it is up to you to decide.

Anything else is already in use.

**Comment by craigh** [comment]
thanks.
