### ISSUE TITLE
installing RC1 at shared hosting is giving trouble

### ISSUE THREAD

**Issue by rallek** [zikula/core#2266]
as shown in #2265 it is a problem, if you upload files via ftp and the owner of the files is different to the webserver.

In this cases the installation is not running well (a lot of errors of wrong ownership)

For me this is a blocker!

**Comment by Portugao** [comment]
Hmmhmm....I uploaded files per ftp ( not as zip ) and i get no issues with ownership.

**Comment by rallek** [comment]
will test at another account later again

**Comment by cmfcmf** [comment]
I also didn't have problems with FTP upload.

**Comment by rallek** [comment]
ftp-upload is working fine. trouble comes only if I upload the tar.gz and unpack with my ssh-user. Might be we can make a hint in the documentation
