### ISSUE TITLE
new permission is always shown for unregistered

### ISSUE THREAD

**Issue by rallek** [zikula/core#2268]
I am testing for #2264 

If I create a new permission (e.g. for ZikulaProfileModule) the group is listed as Unregistered. If I open the modal to change the group it is selected as Users (like I selected while creating the rule) correctly. Saving do not change the list view.

**Comment by Portugao** [comment]
For me the same.

**Comment by craigh** [comment]
s this true for all new permissions or only Profile?

**Comment by Portugao** [comment]
For all new permissions.
