### ISSUE TITLE
Allow IDN domain names (Localisation settings)

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2269]
This item is not updated if try to change.
Also seems it is not used at all in the site (```idnnames```).

**Comment by craigh** [comment]
@nmpetkov can you look into this? maybe a PR?

**Comment by craigh** [comment]
ping @cmfcmf related to #2248 ?

**Comment by nmpetkov** [comment]
Ok, of course. I searched the code and seems this is not in use.
I'll also check Zikula 1.3 for ideas.

**Comment by nmpetkov** [comment]
Result of check:

1. In Zikula 1.3.9 system setting (```idnnames```). is used at one place:
https://github.com/zikula/core/blob/1.3/src/lib/util/System.php#L214
and uses ```idna_convert.class.php``` to convert emails and urls to 8-bit notation. So, it is used at all.

2. In Zikula also I can't change the state of this setting (!).

3. In Zikula 1.4 the above class is missing, and (```idnnames```) is not used anywhere in code.
So, one option is to remove this setting.
Other option is to include updated version of the class in the core. (New core defaults to Internationalized domain names?)

**Comment by craigh** [comment]
I wonder if symfony already does anything like this somehow. @cmfcmf

**Comment by nmpetkov** [comment]
I edited my previous post to be more clear.

**Comment by craigh** [comment]
http://dunglas.fr/2014/10/internationalized-domain-name-idn-and-php/

**Comment by craigh** [comment]
I'm trying to understand what this feature does. It appears that it only validates variables - in other words, if a developer chooses to apply validation to a given variable, this will function on that variable if enabled. Is this correct? If so, then we must identify places in the code where this SHOULD be applied and fix it there as well. I don't think this is a small thing.

But maybe PHP is already doing this for us? or symfony? certainly, this is not preventing a user from having their site with an IDN, since this only filters variables. It is not at work at the apache or browser or DNS levels.

**Comment by nmpetkov** [comment]
At the end of the article:
"On the validation side, the Symfony URL validator has built-in IDN support."

**Comment by nmpetkov** [comment]
For now I can remove this setting (by commenting the respective code section), and write an issue about further investigation of how to support IDN.

**Comment by craigh** [comment]
I would like input from @Guite and @cmfcmf before proceeding

**Comment by Guite** [comment]
When 1.4 modules use Symfony validators IDN should work out of the box.
For BC the IDN class should imho still be kept though as long as `System::varValidate()` is probably still be used by several modules.

**Comment by craigh** [comment]
that sounds good. @nmpetkov if you can reimplement as it is used in 1.3.x and mark all methods as `@deprecated` that should suffice.

**Comment by nmpetkov** [comment]
oK.
On Mar 27, 2014 it seems Symfony is IDN ready, as seem from this ticket:
https://github.com/symfony/symfony/issues/4930
In PHP from 5.3 exist IDN convert function:
http://php.net/manual/en/function.idn-to-ascii.php)

So, instead of returning to 1.3 ```idna_convert.class.php```, better is to implement this function, applied on domain part of e-mails and urls.
