### ISSUE TITLE
prod-log has wrong permission (with PHP5.4)

### ISSUE THREAD

**Issue by rallek** [zikula/core#2274]
I am testing for #2264 

The day after installing via ftp I do get the following error. I have uploaded my VerySimpleDownload to Modules and tried to go to administartion.

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/logs/prod.log" could not be opened: failed to open stream: Permission denied' in /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84 Stack trace: #0 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(109): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\FingersCrossedHandler->handle(Array) #3 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Logger.php(445): Monolog\Logger->addRecord(600, 'Unc in /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84

**Comment by rallek** [comment]
After making prod.log 666 (has been 644) I do get the next trouble:

Failed to remove file "/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/cache/prod/classes.map".

This one is 644 as well

changing lasses.map to 666 or 777 do not help. I made the complete folder app/cache/prod 777 (with all sub folders and files). Now the extension list is showing up again.

**Comment by rallek** [comment]
How should this work? Which folders need to be 777? Please check this during install as well.

**Comment by rallek** [comment]
strange behavior. Yesterday I have setup my test site again and was able to use it with the original settings.

Today (a day later) I have the same failure again :-( 

I have to change the permissions again. I do not know why...

I might be wrong, but if I remember right yesterday the prod.log was owned by the php-User, today the file is owned by the ftp-User. Is this possible?

**Comment by rallek** [comment]
It seems to be an PHP issue! If I use PHP5.5 (in CGI Mode) the site is running again!

**Comment by Guite** [comment]
This is an environment issue. Different ways of running PHP cause different permissions and file ownerships.

http://forum.symfony-project.org/viewtopic.php?f=23&t=76022
http://symfony.com/doc/current/book/installation.html#book-installation-permissions
http://stackoverflow.com/questions/18496584/symfony-2-server-deploy-fatal-error-it-tries-to-open-localhost-file

Closing as `not core`.
