### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by rallek** [zikula/core#2275]
I am testing for #2264 

After installing my VerySimpleDownload module I am testing around. This module is created by modulesudio 0.6.1.

After a while I noticed the view_quickNav is not showing up (typical function in mosulestudio) and an error message:

Notice: Undefined index: properties in /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/cache/prod/ztemp/view_compiled/VerySimpleDownload/user/download/view_quickNav--t_Zikula/Theme/Andreas08Theme-l_en.inc on line 12

I enabled ``Force re-compilation of theme templates`` and ``Force re-compilation of render templates`` and the message disapperas and the view_quickNav is showing again.

Is this core related or is at a modulestudio issue?

**Comment by Guite** [comment]
Seems to be a template issue in the module.

**Comment by rallek** [comment]
any documentation available I can learn how to fix it?

**Comment by Guite** [comment]
First attempt would be recreating with 0.6.2 to see whether the error is still there. If yes, regenerate using the webgen to see whether the error is still there. If yes, create a generator ticket.

**Comment by rallek** [comment]
ok. Will go directly to webgen.
