### ISSUE TITLE
release Profile and Legal modules

### ISSUE THREAD

**Issue by craigh** [zikula/core#2280]
a release of these modules should be finalized before Core 1.4.0-RC2 and version numbers in each should be corrected.

**Comment by craigh** [comment]
this probably includes building POT files for each before release.

**Comment by craigh** [comment]
and tagging a version

**Comment by shefik** [comment]
Is there a specific list of tasks to get this "blocker" finalized?

**Comment by craigh** [comment]
> Is there a specific list of tasks to get this "blocker" finalized?

not really. There are issues in the respective repos that can be worked on - but none of these are preventing release IMO.

This ticket is here (and set as blocker) to ensure that we actually TAG a release in those modules before releasing the core. Tagging is critical so that future upgrades to those modules can occur in later core releases. It is a step that has been forgotten too many times and it simply confuses things.

but as I said, there are items that can be worked on ;-)

**Comment by shefik** [comment]
So, are we ready for another RC, since there are no more tickets for this milestone?

**Comment by cmfcmf** [comment]
Done.
