### ISSUE TITLE
Language of the translation isn't set

### ISSUE THREAD

**Issue by shefik** [zikula/core#2281]
When opening the zikula.pot file, Poedit displays the error:

"Language of the translation isn't set."

**Comment by cmfcmf** [comment]
I don't think you should open the `.pot` file but rather create a `.po` file and then import the strings from the `.pot` file.

**Comment by craigh** [comment]
is this invalid then?

**Comment by craigh** [comment]
ping @shefik @cmfcmf

**Comment by shefik** [comment]
Creating the .po file works fine. But, shouldn't .pot file have the language set anyway? Poedit is saying that the language isn't set.

**Comment by craigh** [comment]
@Guite do you know how this is supposed to work. I've never used Poedit and I never use translations.

**Comment by rallek** [comment]
I know as well :-)

After Poedit is installed you create a new translation file (e.g. zikula.po). Than you import the pot file, translate and save. While saving the .po and .mo files are stored.

Later when you want to update you translation you open your old .po file and update it by importing the pot again.

poedit is delivering a lot of translation proposals. And poedit is also learning from translations you have made already. So you get very often a good proposal for a translated string.

**Comment by rallek** [comment]
@shefik: the pot-file do not have a language. The pot-file are only the untranslated strings.

**Comment by craigh** [comment]
so if I understand you correctly, this ticket is invalid because the POT file shouldn't have a language set.

**Comment by shefik** [comment]
@rallek Thanks for clarifying. Should this info be added to the README file?

**Comment by craigh** [comment]
@rallek would you please create a wiki page at the core project and detail these steps? I don't think it should be in the main README file.

**Comment by rallek** [comment]
will do, but a native speaker should have a look at it later ;-)

**Comment by nmpetkov** [comment]
As here Poedit is commented, it is worth to know, that pro version propose translations from Internet.
I recently payed for pro, and I'm really happy to save time (actually you share, and use shared translations, also they serve google service I think)!
Sorry if this is off-topic.

**Comment by rallek** [comment]
also the free version is giving translation proposals.

**Comment by nmpetkov** [comment]
yes, but from your "database" only :-)

**Comment by rallek** [comment]
ups, you are right. I have also the pro version :-)

**Comment by rallek** [comment]
quick and dirty done. Please have a look at it.
https://github.com/zikula/core/wiki/Translating
I am not as good as native english speakers in writing english documentation

**Comment by craigh** [comment]
thanks Ralf. I'll review the language

**Comment by craigh** [comment]
reviewed: https://github.com/zikula/core/wiki/Translating/_compare/f332345^...f332345
