### ISSUE TITLE
Installer - Alignment of Form Label

### ISSUE THREAD

**Issue by shefik** [zikula/core#2283]
When at a smaller break-point, the labels for the installer form should be left-align, instead of centered.

Zikula 1.4.0 build 452

![form-label](https://cloud.githubusercontent.com/assets/274862/6322693/3b04e880-bae8-11e4-9618-63d93336cd5d.png)

**Comment by craigh** [comment]
I pushed a different (untested) solution. how about that?

**Comment by shefik** [comment]
@craigh I tested your solution. Looks fine to me. I'm closing this particular ticket I opened, and removing its pull request, since it's no longer needed.
