### ISSUE TITLE
Fatal error: Call to a member function rowCount()

### ISSUE THREAD

**Issue by shefik** [zikula/core#2284]
If you submit the Installer form without filling out the form, it throws the following error:

"Fatal error: Call to a member function rowCount() on boolean in /lib/Zikula/Bundle/CoreInstallerBundle/Validator/CoreInstallerValidator.php on line 35"

Zikula 1.4.0 build 452

**Comment by shefik** [comment]
The error occurs when you select "MySQL", but not when you select "PostgreSQL".

**Comment by craigh** [comment]
> the Installer form

which? there are 4

**Comment by cmfcmf** [comment]
@craigh See the error message: `CoreInstallerValidator.php line 35`.

**Comment by craigh** [comment]
@shefik what is the state of the database when you receive this error? Did it have tables?

**Comment by craigh** [comment]
http://stackoverflow.com/questions/1451720/equivalent-of-mysql-list-tables-in-php-pdo

this discussion seems to indicate that doing cross-platform database connection validation is quite difficult until we can use Doctrine which isn't available at this point.

**Comment by shefik** [comment]
@craigh Yes, the database was completely empty. Try submitting the form, without entering any values, and the error will occur. Perhaps more form validation can help?

**Comment by craigh** [comment]
> Perhaps more form validation can help?

the problem is that the validations are occurring in the wrong order apparently. There is already validation for NonNull values

**Comment by Guite** [comment]
@shefik can you please retest with #2310 ?

**Comment by Guite** [comment]
Fixed by #2310. @shefik please reopen in case you still experience problems.
