### ISSUE TITLE
Remove Support for IE7

### ISSUE THREAD

**Issue by shefik** [zikula/core#2287]
Is it really necessary to still support IE7?

For example, the installer is loading this IE7 file:

Zikula 1.4.0 build 452

**Comment by craigh** [comment]
> For example, the installer is loading this IE7 file:

what file?

**Comment by FRWo** [comment]
In my opinion the support for IE7 could end. Still my (administration-)company has switched to IE 9...

**Comment by shefik** [comment]
The IE7 file is for font-awesome.

**Comment by espaan** [comment]
It would be good to have it as an option for people to switch on for hte front-end if needed. Of course for the backend no need to do anything on the older browsers.

**Comment by craigh** [comment]
> For example, the installer is loading this IE7 file:

WHAT FILE?

**Comment by shefik** [comment]
@craigh You can see the file being referenced in the <head> of the installation pages:

**Comment by shefik** [comment]
Also, the installer pages are referencing this CSS file that is apparently about 6 years old! 

That particular file has very old CSS declarations that are no longer needed at all, such as declarations for IE on Mac, IE 6/7 on Windows, and so on.

```
/style/core_iehacks.css
```

**Comment by Guite** [comment]
This is done now (by #2327).
