### ISSUE TITLE
Installer Form - Create administrator's account - Label Width

### ISSUE THREAD

**Issue by shefik** [zikula/core#2289]
At a small break-point, the width of the label at the installer form "Create administrator's account" is too small. It should take 100% width, like the form field does at that particular break-point.

The Bootstrap classes used for this particular form need to be modified accordingly.

![form-classes](https://cloud.githubusercontent.com/assets/274862/6323448/3e2f592c-baf8-11e4-8f6b-9f540302d0df.png)

**Comment by craigh** [comment]
who would be installing zikula from a phone? honestly. does this really matter?

**Comment by shefik** [comment]
@craigh The break-point illustrated via the screen shot is not on a phone. And, I agree, installation of Zikula shouldn't occur on a mobile device. However, I am using a laptop, and the width of the "container" is only 840px in the screen shot. So, I think this problem is valid.

**Comment by Guite** [comment]
Fixed in #2400
