### ISSUE TITLE
Installer Form - Installing Modules and Helpers - List

### ISSUE THREAD

**Issue by shefik** [zikula/core#2290]
At smaller break-points, the list of modules and helpers should possibly be display one-per-line. Otherwise, the items within the list overlap with an incorrect layout.

Zikula 1.4.0 build 452

![form-modules](https://cloud.githubusercontent.com/assets/274862/6323473/c8393fe8-baf8-11e4-8cb0-c818755c0aab.png)

**Comment by Guite** [comment]
The patch I've commitet ensures that the list items use 100% width in the small viewport (xs).
