### ISSUE TITLE
'UserUtil::getTheme() is unable to calculate theme name

### ISSUE THREAD

**Issue by shefik** [zikula/core#2291]
The installer fails with the following error message:

Fatal error: Uncaught exception 'RuntimeException' with message 'UserUtil::getTheme() is unable to calculate theme name.' in /lib/util/UserUtil.php on line 1949

Zikula 1.4.0 build 452

**Comment by craigh** [comment]
always?

more information is required.

**Comment by shefik** [comment]
@craigh Yes, the problem always occurs for me.

**Comment by shefik** [comment]
Look like the problem might be due to this not being set via the installer:

```
define('_ZINSTALLVER', \Zikula_Core::VERSION_NUM);
```

As a result, /lib/util/UserUtil.php on line 1949 throws an exception because it doesn't know that it's installing.

**Comment by shefik** [comment]
During installation, when it gets to the route /install/complete, the "themes" table is still empty.

**Comment by shefik** [comment]
I think this issue is related:

https://github.com/zikula/core/issues/2298

Since the parameters fail during installation, the themes are not regenerated, leaving the table empty.

**Comment by shefik** [comment]
I'm closing this issue, for the reason I posted here:

https://github.com/zikula/core/issues/2298

Installation is successful for me now.
