### ISSUE TITLE
Trying to edit the root-category

### ISSUE THREAD

**Issue by porzellankompass** [zikula/core#2292]
Trying to edit the root category gets me this:

Warning: Smarty error: Error! in category_path: the id parameter must be specified. in D:\wamp\www\Zikula_Core-1.4.0\vendor\drak\smarty\Smarty\Smarty.class.php on line 1094
Call Stack
#	Time	Memory	Function	Location
1	0.0000	140312	{main}( )	..\index.php:0
2	3.4164	19109464	Symfony\Component\HttpKernel\Kernel->handle( )	..\index.php:25
3	3.4320	19264984	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	..\Kernel.php:186
4	3.4320	19265816	Symfony\Component\HttpKernel\HttpKernel->handle( )	..\ContainerAwareHttpKernel.php:64
5	3.4320	19266064	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	..\HttpKernel.php:66
6	3.7128	21812280	call_user_func_array:{D:\wamp\www\Zikula_Core-1.4.0\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:145} ( )	..\HttpKernel.php:145
7	3.7128	21812704	Zikula\Module\CategoriesModule\Controller\AjaxController->editAction( )	..\HttpKernel.php:145
8	3.9468	22683552	Zikula_View->fetch( )	..\AjaxController.php:145
9	3.9624	22688768	Zikula_View->_fetch( )	..\View.php:763
10	4.1652	23244928	include( 'D:\wamp\www\Zikula_Core-1.4.0\app\cache\prod\ztemp\view_compiled\Zikula\Module\CategoriesModule\Ajax\edit--t_Zikula\Theme\Andreas08Theme-l_de.php' )	..\View.php:2960
11	4.5552	25327128	smarty_function_category_path( )	..\Andreas08Theme-l_de.php:44
12	4.5552	25327592	Smarty->trigger_error( )	..\function.category_path.php:69
13	4.5552	25327952	trigger_error ( )	..\Smarty.class.php:1094

( ! ) Warning: Smarty error: Fehler! Eine Kategorie mit der ID 0 konnte nicht ermittelt werden. in D:\wamp\www\Zikula_Core-1.4.0\vendor\drak\smarty\Smarty\Smarty.class.php on line 1094
Call Stack
#	Time	Memory	Function	Location
1	0.0000	140312	{main}( )	..\index.php:0
2	3.4164	19109464	Symfony\Component\HttpKernel\Kernel->handle( )	..\index.php:25
3	3.4320	19264984	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	..\Kernel.php:186
4	3.4320	19265816	Symfony\Component\HttpKernel\HttpKernel->handle( )	..\ContainerAwareHttpKernel.php:64
5	3.4320	19266064	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	..\HttpKernel.php:66
6	3.7128	21812280	call_user_func_array:{D:\wamp\www\Zikula_Core-1.4.0\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:145} ( )	..\HttpKernel.php:145
7	3.7128	21812704	Zikula\Module\CategoriesModule\Controller\AjaxController->editAction( )	..\HttpKernel.php:145
8	3.9468	22683552	Zikula_View->fetch( )	..\AjaxController.php:145
9	3.9624	22688768	Zikula_View->_fetch( )	..\View.php:763
10	4.1652	23244928	include( 'D:\wamp\www\Zikula_Core-1.4.0\app\cache\prod\ztemp\view_compiled\Zikula\Module\CategoriesModule\Ajax\edit--t_Zikula\Theme\Andreas08Theme-l_de.php' )	..\View.php:2960
11	4.5552	25327128	smarty_function_category_path( )	..\Andreas08Theme-l_de.php:44
12	4.6020	25327656	Smarty->trigger_error( )	..\function.category_path.php:98
13	4.6020	25328024	trigger_error ( )	..\Smarty.class.php:1094

1.4.0 build 448 on a local wamp

**Comment by craigh** [comment]
should the root category be editable?

**Comment by Portugao** [comment]
No, i don't think so.
