### ISSUE TITLE
[1.4] Frontpage setting does not work with arguments set

### ISSUE THREAD

**Issue by espaan** [zikula/core#2293]
when Content is used as frontpage module with a certain page set it gives a 404 error. 
You set 
type: user
func: view
parameter: pid=1 for instance
This works fine in current 1.3.x, but has issues in 1.4.x.

See also https://github.com/zikula-modules/Content/issues/160

The type and func seem to pass perfectly to Content, but the argument pid=1 is not passed. 
This seems to come from this line
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/EventListener/LegacyRouteListener.php#L96 where the module is called without arguments for newType (not sure what is newType here) and that does not work with arguments that determine the page to show. When I add $arguments as argument on that specific there it works fine.
So to me that seems it is not a Content issue, but legacyrouter-Core related.

**Comment by craigh** [comment]
ping @cmfcmf

**Comment by cmfcmf** [comment]
There is something wrong in several places with the `ModUtil::getModule()` function. I cannot look at it until the weekend though.

**Comment by espaan** [comment]
@Guite did you test the frontpage display with Content ?

**Comment by Guite** [comment]
@espaan no, I only reviewed the code change. Feel free to try it out :-)

**Comment by craigh** [comment]
I tested it and it worked for me.
