### ISSUE TITLE
Menu item is rotating after adding a permission rule

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2296]
This is really funy, but not wanted behavior. This happens to me in Chrome (not in Firefox or IE).
See picture:
![image](https://cloud.githubusercontent.com/assets/628801/6381112/60039b8e-bd47-11e4-9411-53e1900b3c6c.png)
Sorry if this happens to me only :-(

**Comment by cmfcmf** [comment]
Ha. Ha. :D
N. Petkov <notifications@github.com> schrieb am Mi., 25. Feb. 2015 um 22:39:

**Comment by craigh** [comment]
what build are you using (or github)? I remember fixing this once.

**Comment by nmpetkov** [comment]
Last from Github

**Comment by rojblake** [comment]
I've seen this too using a recent git pull.

-Mark

**Comment by craigh** [comment]
I say we leave it as a "feature"

**Comment by nmpetkov** [comment]
Works, thanks!
