### ISSUE TITLE
It is not possible to edit or delete a permission rule

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2297]
This is related to ajax connection, error hidden behind it, by in my case doesn't work.
All browsers.

**Comment by craigh** [comment]
it worked for me a couple days ago.

**Comment by nmpetkov** [comment]
BTW reordering of rules also doesn't work. It is not saved (visually happens, but not in database).

**Comment by craigh** [comment]
deleting works for me in chrome and safari.

**Comment by nmpetkov** [comment]
I checked again in 3 browsers (Chrome, IE, Firefox), and can't delete, reorder, or edit. After Ctrl+F5 to reload java scripts.
I'll check again in new install soon.

**Comment by nmpetkov** [comment]
After installing from the ground build 456 I'm able to edit, reorder and delete, so I'm closing this issue.
