### ISSUE TITLE
Error loading SeaBreeze theme

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2299]
An error occurs if from theme list page attempt to view SeaBreeze theme.

I'd suggest to completely remove from Zikula core. Otherwise needs repairing.

**Comment by craigh** [comment]
I don't think it should be removed. I think it should be fixed.

**Comment by Portugao** [comment]
The error is:
``
`Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

zikula_view.template_override returned a non-existent template path themes/SeaBreezeTheme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/topnav.tpl
```

**Comment by Guite** [comment]
Fixed by #2308 , thanks @nmpetkov
