### ISSUE TITLE
When installing a module that has a dependency, the "reason" is not populated

### ISSUE THREAD

**Issue by shefik** [zikula/core#2302]
When installing a module that has a dependency, if the "reason" is populated in the module's meta data array, It doesn't output on the form:

/extensions/modules/initialize

![reason](https://cloud.githubusercontent.com/assets/274862/6423527/7973e122-beb5-11e4-9561-ec59713fa57f.png)

**Comment by shefik** [comment]
The problem is due to "ModUtil::getModule()" not populating correctly. As a result, "getReason()" in 

/lib/Zikula/Core/Doctrine/Entity/ExtensionDependencyEntity.php

is returning an empty string for "reason"

**Comment by shefik** [comment]
Zikula\Bundle\CoreBundle\HttpKernel\ZikulaKernel->getModule( )

seems to only work on extensions located in /system, and not in /modules

**Comment by cmfcmf** [comment]
This is expected behaviour. The reason field only works with the new
namespaces module structure.
Shefik <notifications@github.com> schrieb am Sa., 28. Feb. 2015 um 02:18:

**Comment by shefik** [comment]
@cmfcmf What new namespaces module structure are you referring to? The screenshot I posted is from a module coded with PRS-4. It's dependency is the Legal module which is not displaying its "reason". Furthermore, I tested again the behavior of getModule(). It is only working for modules that are already installed. So, if you are trying to install a new module, the "reason" always remain blank because the module data is not being loaded in the Zikula Kernel.

**Comment by craigh** [comment]
> Zikula\Bundle\CoreBundle\HttpKernel\ZikulaKernel->getModule( )

> seems to only work on extensions located in /system, and not in /modules

This is not true. It works for modules that are namespaced but not the Pear_Class_Name modules. For example, News would not be included, but Legal should be.

Which module are you trying to use?

**Comment by shefik** [comment]
@craigh It is a third-party module. Nevertheless, it is not working. The screenshot is from a module coded as psr-4, and its dependency is ZikulaLegalModule. You can see in the screenshot the "reason" is empty.

**Comment by craigh** [comment]
Why is the module a secret? why can't I know the module and then test this for myself?

**Comment by cmfcmf** [comment]
@shefik Please try to delete the content of the `app/cache` folder before installing the module.

**Comment by craigh** [comment]
> Why is the module a secret? why can't I know the module and then test this for myself?

@shefik I would like to test this so I can solve this ticket. What is the module?

**Comment by shefik** [comment]
@craigh There is no public module to point you to. However, if you want to replicate the issue, then use your BreakIt module as an example.

See the attached screenshot.

I tested by adding both the Profile and Legal modules as required dependencies. Nothing gets populated as the "reason". Similar issue occurs with other modules, so it appears to be broken overall.

![breakit](https://cloud.githubusercontent.com/assets/274862/6548466/fe947c2e-c5cf-11e4-800e-c31f0045350e.png)

**Comment by craigh** [comment]
please copy the code you added here. thanks

**Comment by shefik** [comment]
```
<?php
/**
 * Copyright Zikula Foundation 2014 - Zikula Application Framework
 *
 * This work is contributed to the Zikula Foundation under one or more
 * Contributor Agreements and licensed to You under the following license:
 *
 * @license MIT
 * @package BreakIt
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

namespace Zikula\BreakItModule;

use HookUtil;
use ModUtil;

/**
 * BreakIt module version information and other metadata.
 */
class BreakItModuleVersion extends \Zikula_AbstractVersion
{
    /**
     * Provides an array of standard Zikula Extension metadata.
     *
     * @return array Zikula Extension metadata.
     */
    public function getMetaData()
    {
        $result = array();
        
        $result['displayname'] = $this->__('BreakIt');
        
        $result['oldnames'] = array();
        
        $result['url'] = $this->__('breakit');
        
        $result['description'] = $this->__('BreakIt');
        
        $result['version'] = '1.1.0';
        
        $result['core_min'] = '1.4.0';
        
        $result['core_max'] = '';

        $result['capabilities'] = array();
		$result['capabilities'][HookUtil::PROVIDER_CAPABLE]['enabled'] = false;
        $result['capabilities'][HookUtil::SUBSCRIBER_CAPABLE]['enabled'] = false;

        $result['dependencies'] = array();
        $result['dependencies'][] = array(
            'modname' => 'ZikulaLegalModule', 
            'minversion' => '2.1.0',
            'maxversion' => '', 
            'status' => ModUtil::DEPENDENCY_REQUIRED,
            'reason' => $this->__('Use functionality from the Legal module.')
        );
        $result['dependencies'][] = array(
            'modname' => 'ZikulaProfileModule', 
            'minversion' => '2.0.0',
            'maxversion' => '', 
            'status' => ModUtil::DEPENDENCY_REQUIRED,
            'reason' => $this->__('Use functionality from the Profile module.')
        );
  
        $result['securityschema'] = array(
        	$this->name.'::' => '::'
        );

        return $result;
    }

}
```

**Comment by craigh** [comment]
I can confirm this is indeed broken.

I think it stems from when I changed the system to not load all bundles all the time. Currently, only installed bundles are loaded. This means that [this line of code](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Core/Doctrine/Entity/ExtensionDependencyEntity.php#L153)
```php
$bundle = ModUtil::getModule($modinfo['name']);
```
will return null every time because the bundle isn't loaded into the kernel yet.
