### ISSUE TITLE
Admin theme setting is not working

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2309]
To reproduce:
1. Go to Theme, Settings, and set "Andreas08" as Admin theme.
2. Set as default for the site SeaBreeze theme.
3. In admin panel you will see SeaBreeze layout, instead Andreas08, as shown in the picture below.

This works as expected in Zikula 1.3.

![image](https://cloud.githubusercontent.com/assets/628801/6474251/f309e1f8-c207-11e4-9e13-25283226ea90.png)

**Comment by craigh** [comment]
ping @cmfcmf thoughts on my solution?

**Comment by nmpetkov** [comment]
It works now for me, thanks.
