### ISSUE TITLE
Duplicate Routes

### ISSUE THREAD

**Issue by shefik** [zikula/core#2313]
When you reload routes, duplicates appear here:

```
/routes/routes/view?lct=admin
```

such as duplicates of:

```
/permissions/config
```

Many routes appear as duplicates

**Comment by craigh** [comment]
ping @cmfcmf

**Comment by Guite** [comment]
Just an idea, but it could be the right direction:

Please see https://github.com/Guite/core/commit/805a4e9eb177d7e96208149f61666ae823e4cb74 - specifically the first change in the second file.
I suspect that the workflow helper can not be used within an explicite transaction, because it calls the core's workflow util class which does a `flush` anyway.

**Comment by cmfcmf** [comment]
Is this fixed now @Guite?

**Comment by craigh** [comment]
I don't think @Guite pull those changes into the core

**Comment by cmfcmf** [comment]
So @Guite what's the state here?

**Comment by Guite** [comment]
@cmfcmf There isn't anything done yet. The commit above was just an initial idea in theory, nothing more.

**Comment by craigh** [comment]
I tried cherry-picking @Guite 's code in https://github.com/Guite/core/commit/805a4e9eb177d7e96208149f61666ae823e4cb74 and reloaded the routes and there were still duplicated routes.
![screen shot 2015-03-17 at 6 46 49 pm](https://cloud.githubusercontent.com/assets/350048/6699197/12792eb2-ccd6-11e4-8980-ad6d9dbab4b2.png)
![screen shot 2015-03-17 at 6 46 59 pm](https://cloud.githubusercontent.com/assets/350048/6699198/128576a4-ccd6-11e4-8a2f-1f46383056e3.png)
![screen shot 2015-03-17 at 6 46 33 pm](https://cloud.githubusercontent.com/assets/350048/6699199/12884eba-ccd6-11e4-9c8d-687d002ef2c8.png)

but as I think about it, maybe this is not an actual mistake/bug!

for example: `/search/admin/config` has TWO routes in the controller - one for `GET` and one for `POST` - same for securitycenter and permissions. among others.

So - I don't think this is a bug as much as it is a request for better information in the route list. :smile:

**Comment by craigh** [comment]
for example:
![screen shot 2015-03-17 at 7 17 33 pm](https://cloud.githubusercontent.com/assets/350048/6699635/4bed5336-ccda-11e4-9b15-02fa6e197885.png)

**Comment by craigh** [comment]
IMO this is solved. re-open if you disagree.
