### ISSUE TITLE
'AccessDeniedException' Redirects to Homepage

### ISSUE THREAD

**Issue by shefik** [zikula/core#2314]
Anytime I use:

```
throw new AccessDeniedException();
```

It just redirects to the homepage, instead of actually throwing an exception at the desired page. I don't think it should redirect, especially if a site doesn't have any alert message on the homepage. Typically alert messages are inserted on module pages instead.

**Comment by craigh** [comment]
In `prod` mode all exceptions are caught and an error should be displayed. Are you in `prod` or `dev`?

I think this is the expected behavior.

**Comment by craigh** [comment]
also, `debug` must be set to `true` to see full exceptions.

**Comment by Guite** [comment]
@shefik can you please elaborate?

**Comment by craigh** [comment]
ping @shefik 

please answer requests to provide more information more promptly. Filing tickets is great - **really, it is**. but we nearly always need more information than you provide. Please work to provide as much information as possible and also work to respond as quickly as you can to questions. Thanks.

**Comment by shefik** [comment]
All you need to do is add this line of code to any controller:

```
throw new AccessDeniedException();
```

If you are logged in, you will see that it keeps redirecting the user to the homepage, instead of leaving the user at the same page. The redirection to the homepage should not occur.

**Comment by Guite** [comment]
@shefik you still didn't tell anything about your environment setting
@craigh shouldn't the user be redirected to the login page in `prod`?

**Comment by craigh** [comment]
it behaves differently depending on whether the user is logged in. see
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/EventListener/ExceptionListener.php#L94-L103

**Comment by shefik** [comment]
@guite This occurs with the latest build of Zikula as-is. So, the setting is "prod".

**Comment by craigh** [comment]
I'm testing this using BreakIt - where I can throw an AccessDeniedException with ease. If I am logged in, then it redirects me back to the page I threw the error from. If I am not logged in, then it asks me to log in.

[this line](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/EventListener/ExceptionListener.php#L102) redirects to the `HTTP_REFERER` which should do as you are asking. It only sends to the homepage if it cannot fetch the referer.

So, I'm not seeing the problem.

**Comment by Guite** [comment]
Closed as invalid.

> In prod mode all exceptions are caught and an error should be displayed. Are you in prod or dev?
> I think this is the expected behavior.
