### ISSUE TITLE
Do not display module name in short URLs

### ISSUE THREAD

**Issue by shefik** [zikula/core#2315]
When I select a module under the options for:

```
Do not display module name in short URLs for
```

/settings/admin/config

It does not appear to be working. The module name is still required in the route.

**Comment by shefik** [comment]
It only appears to be working for the "main" function:

old:

/example/main

new

/main

But, other functions still require the module name in the route:

/example/route2

**Comment by craigh** [comment]
which module are you attempting to use?

this method only works with "old" short-urls. it doesn't (*and won't) work with the new routes.

**Comment by Guite** [comment]
@cmfcmf do you agree?

If it isn't planned to support this setting with routes maybe we should add a form note explaining that.

**Comment by craigh** [comment]
more than that, the Namespaced modules should be removed from the select box.

**Comment by cmfcmf** [comment]
Yes, this doesn't work with routes right now (but could be made working in the future).

**Comment by craigh** [comment]
isn't it already possible by simply editing the routes?

**Comment by craigh** [comment]
Please see pending PR for my solution. comments?

**Comment by craigh** [comment]
closed by #2338
