### ISSUE TITLE
Confirm registration validation is working properly

### ISSUE THREAD

**Issue by craigh** [zikula/core#2321]
#1805 was closed without merging
#1804 removed all the old prototype files and didn't replace any code.
https://github.com/zikula/core/commit/2da396f15a64e745b94fb0826bec687becfd9b0d removed same from admin side since all the files were gone anyway

it is unknown if any JS validation is occurring before a user is created.

has anyone replaced the old js validation?

@phaidon @shefik @jusuff @Guite

**Comment by craigh** [comment]
I checked on this a little. I found that PHP also validates the data so there appears to be no danger of double-registering the same username (for example) or other possible data-corruption.

The old `getRegistrationErrorsAction` method still exists in the ajax controller and could be used if needed. but nothing calls it at the moment.

@jusuff did you say you can look into re-activating ajax validation here or should we discuss another solution?

**Comment by shefik** [comment]
Just add Webshim for the HTML5 validation, as a polyfill for browser support.

**Comment by craigh** [comment]
I don't know anything about those technologies. A PR would be welcome!

**Comment by Guite** [comment]
@shefik this is not about simple checks like mandatory fields. This issue is about extended validation, like username may not be already used, password must not be equal username, email address may not be already used, and so on.

**Comment by shefik** [comment]
@Guite Webshim is still needed for browsers such as Safari on Mac, to add support for attributes such as "required". As an example, the attribute "required" works correctly on Chrome on Mac, and form does not submit via HTML5 validation.

https://github.com/aFarkas/webshim

**Comment by craigh** [comment]
@shefik did your PR only add the library? Did you implement any part of the solution? When I asked for a PR, I assumed it would be understood that you would also do that.

**Comment by shefik** [comment]
@craigh Yes, it only added the Webshim library for the moment, as well as some validation for the installer. I can submit another pull request to specifically address the registration/user forms. I've been going through much of the core in progression, so when I get fully past the installer tickets, I can move on to User and Profile mods, and so on.

**Comment by craigh** [comment]
Feel free to submit many smaller PRs instead of one large one at the end. I would rather have smaller commits anyway

**Comment by cmfcmf** [comment]
Make sure *not* to validate any hooks via Ajax, because this breaks certain modules (such as the Captcha module).

**Comment by craigh** [comment]
> Yes, it only added the Webshim library for the moment, as well as some validation for the installer.

I'm not seeing any usage of this in the installer. can you be more specific where it was added?

**Comment by craigh** [comment]
ping @shefik feedback requested ^^^

**Comment by shefik** [comment]
@craigh To see it working, use Safari on Mac, you will see that HTML5 form validation is working on the "required" fields. Without webshim, Safari did not fully support HTML 5 form validation. Therefore, the forms were able to bypass validation. The webshim displays the appropriate validation message and prevents the form from being submitted if invalid. As a comparison, view the same pages via Chrome on Mac. That particular browser already has built-in support for HTML 5 form validation. Therefore, the webshim is not used.

**Comment by jusuff** [comment]
What's about this ticket? Does anyone work on it? And I mean initial issue - validating via ajax user entries (eg - is username free to use).

**Comment by craigh** [comment]
You are :wink: ASAP :smile:

**Comment by jusuff** [comment]
Ok :)

**Comment by Guite** [comment]
Closed by #2377
