### ISSUE TITLE
Correcting System Vars

### ISSUE THREAD

**Issue by shefik** [zikula/core#2330]
With the recent multilingual changes to system vars, there are still core files which call to the old methods. For example:

/lib/util/PageUtil.php, Line 215:
System::getVar('pagetitle', '')

/lib/util/PageUtil.php, Line 218:
System::getVar('sitename', '')

The entire core should be checked, and updated to the new multilingual vars. Several files (outside of the Settings module) need to be updated accordingly in the core.

**Comment by craigh** [comment]
ping @nmpetkov

**Comment by shefik** [comment]
Particularly check these files:

/lib/legacy/Zikula/Core.php
/lib/util/ModUtil.php
/lib/util/PageUtil.php
/system/Zikula/Module/SettingsModule/Controller/AdminController.php

There might be others to check too.

**Comment by nmpetkov** [comment]
It is desired.
The idea of multilingual support is this to leave, and all templates to remain compatible.
Multilingual effect is because this variables are set to respective variables for respective current page language.

**Comment by craigh** [comment]
@nmpetkov you are saying this should not be changed? I'm struggling a little with your English today :smile:

**Comment by nmpetkov** [comment]
Please see how this is implemented here: #2316.

**Comment by nmpetkov** [comment]
Sorry. Please test multilingual support.

**Comment by nmpetkov** [comment]
To test:
Get last changes for this PR.
2. Upgrade Settings module.
Then enter Settings admin page, and enter different strings for different languages.
Then see if this takes effect on the first page of the site.

**Comment by craigh** [comment]
> 2. Upgrade Settings module.

@nmpetkov when I did this, I had an exception about the `sitename` not being set. A few reloads fixed it but this is not a desired behavior.

**Comment by nmpetkov** [comment]
@craigh It is possible to happen only if the Settings module is not upgraded yet, but system is unctional As this is a real condition, I'll make a PR to correct this.

**Comment by shefik** [comment]
@nmpetkov With the new version of the Settings module, the old vars have been removed:

System::delVar('sitename');
System::delVar('slogan');
System::delVar('metakeywords');
System::delVar('defaultpagetitle');
System::delVar('defaultmetadescription');

There are still core files which call to those old vars. So, those core files need to be updated to the new var names. So, it's not just an issue with the Settings module. The problem is with other core files.

**Comment by nmpetkov** [comment]
@shefik If you see how this is implemented, then will realize, that they are deleted, but are initialized when language is set.

**Comment by craigh** [comment]
@shefik those values are added back in a [setup function](https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L140-L154)

so that should work ok

**Comment by nmpetkov** [comment]
Now I'm preparing a PR to make upgrade process more robust, thanks for testing.

**Comment by craigh** [comment]
so, that being said.... @shefik - did you actually experience a problem/exception somewhere which prompted you to open this ticket?

**Comment by shefik** [comment]
Is this something like this still valid?

```
System::setVar('sitename')
```

Or, does it always need to have the language now?

```
System::setVar('sitename_en')
```

**Comment by nmpetkov** [comment]
``` System::setVar('sitename') ``` have to be always available, and ``` System::setVar('sitename_en') ``` is used only to init ``` System::setVar('sitename')  ``` when page language is set.

**Comment by craigh** [comment]
> I experiencing errors about a NULL value.

was this after the upgrade of the settings module?

**Comment by shefik** [comment]
New install of Zikula.
