### ISSUE TITLE
There was an error installing the module Settings

### ISSUE THREAD

**Issue by shefik** [zikula/core#2332]
The installer is now throwing this error during installation:

```
There was an error installing the module Settings.
```

**Comment by Guite** [comment]
ping @nmpetkov

**Comment by nmpetkov** [comment]
@shefik Is this in new install? And files from where?

**Comment by shefik** [comment]
New install. Files from ci.zikula.org.

**Comment by nmpetkov** [comment]
Please wait for new build, it is old now. I'll also test after see there is new build.

**Comment by shefik** [comment]
I tested with Build #479. Do you have newer code?

**Comment by nmpetkov** [comment]
No, but 479 is 16 hours  old, and last changes not there.

**Comment by shefik** [comment]
479 is the latest build. You don't have any pending pull requests

https://github.com/zikula/core/pulls

Do you have any other code that you haven't committed yet to the repository?

**Comment by nmpetkov** [comment]
This changes #2331 is not in this build.

**Comment by nmpetkov** [comment]
I checked this build, and #2331 is inside. So I'll start testing and will attempt to correct the problem.

**Comment by nmpetkov** [comment]
The error was trivial (```Can't use function return value in write context```), but for me was difficult to find, because installer now works in ajax mode, and messages are not enough to find the place.
I tested with 
```
    env:              dev
    debug:            true
```
I can suggest installer in this modes not to use ajax.
