### ISSUE TITLE
Use of undefined constant ZIKULACORE_CURRENT_INSTALLED_VERSION

### ISSUE THREAD

**Issue by shefik** [zikula/core#2333]
Executing the console via CLI:

```
php app/console
```

Throws the following error:

```
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Notice: Use of undefined constant ZIKULACORE_CURRENT_INSTALLED_VERSION - as  
  sumed 'ZIKULACORE_CURRENT_INSTALLED_VERSION' 
```

**Comment by craigh** [comment]
do verbose

```shell
php app/console -vvv
```

and post results please

**Comment by shefik** [comment]
``` 
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Notice: Use of undefined constant ZIKULACORE_CURRENT_INSTALLED_VERSION - as  
  sumed 'ZIKULACORE_CURRENT_INSTALLED_VERSION'                                 
```                                                                          

```
Exception trace:
 () at /lib/Zikula/Bundle/CoreBundle/Console/Application.php:42
 Symfony\Component\Debug\ErrorHandler->handleError() at /lib/Zikula/Bundle/CoreBundle/Console/Application.php:42
 Zikula\Bundle\CoreBundle\Console\Application->registerCommands() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /app/console:19
```

**Comment by craigh** [comment]
and how did you come to see this? What were you doing? before install? after?

**Comment by craigh** [comment]
executing the console e.g.
```shell
php app/console
```
does not throw any errors for me.

**Comment by craigh** [comment]
I'm guessing this is related to #2334 or a result of a failed install. The constant will only be defined if the core has been installed correctly.

**Comment by Kaik** [comment]
I have experienced this some time ago and indeed it was related to previous failed install. Started fresh and never seen this error again.

**Comment by shefik** [comment]
Works fine now, using Zikula 1.4.0 build 483.

**Comment by craigh** [comment]
I'm guessing you tried to run the installer when the MAMP servers were not running. I just experienced the same thing. Since the CLI accesses the DB, you need to make sure your servers are running first. I'm wondering if this is the issue with #2334 also

**Comment by Kaik** [comment]
I'm having this error every time upgrade fail I have replaced DB started upgrade again but not cleared cache.

**Comment by craigh** [comment]
please open a new ticket @Kaik . please include build information and server information.

**Comment by Kaik** [comment]
I will do all that next time I will be upgrading
