### ISSUE TITLE
Installing via CLI Fails - Could not connect to the database

### ISSUE THREAD

**Issue by shefik** [zikula/core#2334]
Installing via CLI fails, because it can't connect to the database, even though the correct credentials are entered.

```
[RuntimeException]                                                                                                                           
  Invalid data provided: ERROR: Error! Could not connect to the database. Please check that you have entered the correct database information  
   and try again. SQLSTATE[HY000] [2002] No such file or directory 
```

**Comment by craigh** [comment]
ping @Guite - probably the changes in your validation

**Comment by Guite** [comment]
@shefik can you try commenting out this line https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Validator/CoreInstallerValidator.php#L37 and see if it works then?

**Comment by shefik** [comment]
@Guite Commenting out that particular line of code didn't help.

Error:

```
 [RuntimeException]                                                                                                                                         
  Invalid data provided: ERROR: Error! Could not connect to the database. Please check that you have entered the correct database information and try again  
  . SQLSTATE[HY000] [2002] No such file or directory    
```

**Comment by shefik** [comment]
I am running the command line on Mac OS. However, I use MAMP as a development environment. Perhaps the issue is due to the CLI attempting to use the MySQL instance that ships with Mac OS, instead of the MySQL that ships with MAMP? However, when installing via the web interface, the installer correctly calls to the MySQL instance with MAMP. Installing via CLI doesn't offer an option to choose the MySQL instance.

**Comment by craigh** [comment]
I also use MAMP and the CLI installer has worked fine in the past (wrt MySQL). I haven't tested it since @Guite's changes however (which are the problem I suspect).

**Comment by craigh** [comment]
I guess I should say that I changed my local php alias to use MAMPs php though. that may matter.

**Comment by Guite** [comment]
I was wondering about the actual exception error message: `No such file or directory`. This is probably not directly related to my changes. Also it seems to be a mac os specific behaviour. Please read these links for example:

* http://stackoverflow.com/questions/1819592/error-when-connecting-to-mysql-using-php-pdo
* https://www.drupal.org/node/752856
* https://www.drupal.org/node/752856#comment-5525672
* http://www.webbykat.com/2012/05/link/fixing-drush-error-pdoconstruct-2002-no-such-file-or-directory

**Comment by craigh** [comment]
I am able to install via CLI with MAMP (on Mac). I just tested it and it works.

**Comment by Guite** [comment]
how to proceed with this one? tend to postpone it to 1.4.1 or even close it since this seems nothing Zikula specific (see links above). opinions/objections?

**Comment by craigh** [comment]
I would close it but was waiting for feedback from @shefik

**Comment by shefik** [comment]
It still does not work for me. I tried change the host from "localhost" to "127.0.0.1" and the error persists:
                                                                                                             
```                                                                                                                      
  [RuntimeException]                                                                                                    
  Invalid data provided: ERROR: Error! Could not connect to the database. Please check that you have entered the corre  
  ct database information and try again. SQLSTATE[HY000] [2002] Connection refused                                      
                                                                                                                        


Exception trace:
 () at /vendor/matthiasnoback/symfony-console-form/src/Console/Helper/FormHelper.php:46
 Matthias\SymfonyConsoleForm\Console\Helper\FormHelper->invalidForm() at /vendor/matthiasnoback/symfony-console-form/src/Console/Helper/FormHelper.php:38
 Matthias\SymfonyConsoleForm\Console\Helper\FormHelper->interactUsingForm() at /lib/Zikula/Bundle/CoreInstallerBundle/Command/Install/StartCommand.php:100
 Zikula\Bundle\CoreInstallerBundle\Command\Install\StartCommand->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /app/console:19
```

**Comment by Guite** [comment]
@shefik did you read the links I posted above carefully?

Also now you got a different error. Before it was `No such file or directory` and now it is `Connection refused`.
