### ISSUE TITLE
Endless Loop When Using the Smarty "route" plugin

### ISSUE THREAD

**Issue by shefik** [zikula/core#2336]
If a theme template uses the Smarty "route" plugin, as in the following example:

```
<a href="{route name='zikulanewsmodule_user_display' sid='3'}">Link</a>
```

The corresponding module is required to be already installed beforehand. Otherwise, the following error is thrown:

```
Unable to generate a URL for the named route "zikulanewsmodule_user_display" as such route does not exist.
```

If the user is not logged in, the error message is simply output to the screen. However, if the user is logged in as admin, an endless loop occurs, as the site keeps redirecting to this URL:

```
/routes/routes/reload?lct=admin
```

Meaning, the admin isn't even able to install the needed module, due to the endless loop. So, there currently isn't an efficient way to keep a theme functional, if certain modules aren't installed, and the "route" plugin is used within a theme.

**Comment by craigh** [comment]
refs #2142
