### ISSUE TITLE
[Discussion] Loading module variables

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2337]
Currently variables for all module and pseudo modules  are loaded when Zikula core initializes. This happens in line:
https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L117

This query loads all the table (`module_vars`) in the memory.

Rows in this table may vary from about 400 to more then 1000 from site to site. Each row can contain simple values, but often in module variables are stored big missives of data, for example HTML blocks, or modules, which use module variables to store data. 

In most cases only one module is used to generate current page (pplus core variables). So, this approach can be optimized.

What do you think?

**Comment by rallek** [comment]
From my point of view it is not true mainly one module is active. If you use Content than you have several modules in use at the same time.

**Comment by Guite** [comment]
Closed: ModUtil is legacy and not available in 2.x anymore.
