### ISSUE TITLE
Typo During Zikula AJAX Installation

### ISSUE THREAD

**Issue by shefik** [zikula/core#2340]
During the Zikula AJAX Installation process, this text is displayed briefly while the Settings module is being installed:

```
Installing the module Setings
```

Notice the "t" that is missing from "Settings".

I can't seem to find the specific file that contains the typo. Any have any ideas where it is?

ping @craigh

**Comment by craigh** [comment]
the word `setings` doesn't appear in the core anywhere (just did a global search). Maybe it is in a translation file?

`\Zikula\Bundle\CoreInstallerBundle\Stage\Install\AjaxInstallerStage::getTemplateParams`
```php
                self::PRE => __('Zikula Settings Module'),
                self::DURING => __('Installing Zikula Settings Module'),
                self::SUCCESS => __('Zikula Settings Module installed'),
                self::FAIL => __('There was an error installing Zikula Settings Module')
```

**Comment by shefik** [comment]
I checked the translation files. Couldn't find it.
