### ISSUE TITLE
[Jenkins] Unnecessary .ppt file extension added

### ISSUE THREAD

**Issue by shefik** [zikula/core#2341]
When downloading the POT files via Jenkins, the download appends the file extension ".ppt" to the file, such as:

zikula_js.pot.ppt
zikula.pot.ppt

It occurs on Mac. (I don't know if Windows has the same issue.)

**Comment by craigh** [comment]
This is the fault of your computer (mine too). The repo is correct.

**Comment by rallek** [comment]
On Windows everything is going well. .pot without .ppt
