### ISSUE TITLE
[Routing] Page not found error in viewing a theme

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2342]
To reproduce:
1. Go to admin panel, Thems.
2. Click on one non default theme, for example SeeBreeze (far left, or button preview on the right).
3. new window opens, and on the address bar:
```http://`xyz.com/ZikulaSeaBreezeTheme ``
and on page:
![image](https://cloud.githubusercontent.com/assets/628801/6565025/cbca3680-c6b5-11e4-859e-3d462f9cc548.png)

(I'm with dev/debug on).

**Comment by craigh** [comment]
my url looks like `http://127.0.0.1/core.git/src/index.php?theme=ZikulaSeaBreezeTheme` and works just fine

**Comment by nmpetkov** [comment]
This only happens if a setting is enabled:
```Enable directory-based short URLs ```
in main site settings page.

**Comment by nmpetkov** [comment]
After last commit (https://github.com/zikula/core/commit/f8bddf6a4869a59627703f74ed4e4c8b8356fc1e) link to view a theme works in shorturls enabled, bu unfortunately in disabled shorturls started not to work :-(.

Result from testing after the commite:
shorturls ENABLED: works(address bar: http://xyz.com/?theme=ZikulaSeaBreezeTheme)
shorturls DISABLED: DON'T work (address bar: http://xyz.com/theme/admin/index.php?theme=ZikulaSeaBreezeTheme)

So, I think this issue have to be re-opened.
