### ISSUE TITLE
path to polyfiller.js doesn't work in non-root environments

### ISSUE THREAD

**Issue by craigh** [zikula/core#2343]
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views/structure.html.twig#L24

and 

https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views/structure.html.twig#L27

assume that zikula is installed at the root of the website, e.g. http://mywebsite.com/ and not http://mywebsite.com/zikula/ (or similar)

the library cannot be found in these environments (although I'm not sure what it is doing at the moment anyway - but it produces an 'asset cannot be found' console error)

ping @shefik

**Comment by Guite** [comment]
How are functions like `charset` and `lang` made available to the Twig templates?

I saw https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php but there is no charset extension contained.

Basic approach: provide `System::getBaseUrl()` and prepend it to the pathes.

**Comment by craigh** [comment]
http://twig.sensiolabs.org/doc/templates.html#global-variables

**Comment by craigh** [comment]
also e.g. generated [here](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/InstallerController.php#L61)

computed [here](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Util/ControllerUtil.php#L28-L38)

assigned to template [here](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/InstallerController.php#L64)

I'm not sure what was your point?

I was hoping @shefik would solve this one.

**Comment by shefik** [comment]
I'll take a look at it.

**Comment by craigh** [comment]
the baseUri is available from the request object. I think the request object is available in the template also. you'd have to google that or search the docs. I cannot remember for sure.

**Comment by craigh** [comment]
yes - request object is in the template. see [this symfony doc](http://symfony.com/doc/current/book/templating.html#global-template-variables)

**Comment by Guite** [comment]
Proposal: prepend ```{{ app.request.getBasePath() }}/```

**Comment by craigh** [comment]
Of course. I was hoping @shefik would take care of it.

**Comment by shefik** [comment]
It's done.

**Comment by Guite** [comment]
Fixed in #2362
