### ISSUE TITLE
Gettext translations not working in themes

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2344]
Problem is ilustrated in picture below:

![image](https://cloud.githubusercontent.com/assets/628801/6598236/f97ae8c6-c80a-11e4-8437-d0f3907d1e6a.png)

In same time strings (for example "Site search") exists in POT file and is translated:

![image](https://cloud.githubusercontent.com/assets/628801/6598328/a13d44e6-c80b-11e4-9f0c-01787c27e89c.png)

Translations from other content is translated properly (blocks, modules).

**Comment by craigh** [comment]
I don't believe this to be a theme problem. I think this is works in the database that cannot be translated automatically - you would need to update your menu block.

**Comment by nmpetkov** [comment]
This strings are from ```tpl```files, not from menu block.

**Comment by nmpetkov** [comment]
Here are links to where the strings are:
SeaBreeze:
https://github.com/zikula/core/blob/1.4/src/themes/SeaBreezeTheme/Resources/views/includes/userheader.tpl#L13
Andreas08:
https://github.com/zikula/core/blob/1.4/src/themes/SeaBreezeTheme/Resources/views/includes/userheader.tpl#L13

**Comment by rallek** [comment]
@nmpetkov is the language change in the settings really done?

I tried to change to german and failed. In my case I can see there is german language available. I select the second language as defauld and press save. The language is switched back to english :-(.

So i can confirm: There is troubble with translation.

**Comment by craigh** [comment]
@cmfcmf said he had the same trouble trying to change the language. Interestingly, I mine seems to work fine and so does (obviously) @nmpetkov

**Comment by craigh** [comment]
This ticket is invalid, the translations work as they are designed. As you can see [the code](https://github.com/zikula/core/blob/1.4/src/themes/Zikula/Theme/Andreas08Theme/Resources/views/home.tpl#L4) the template code you reference only appears if the topnavblock is empty - which by default it is not, it has a block installed. You can edit this block to include your translation like so:
![screen shot 2015-03-16 at 1 37 13 pm](https://cloud.githubusercontent.com/assets/350048/6672257/9ffe15b8-cbe1-11e4-9d3c-b4c695bb9cad.png)
and it will look like so:
![screen shot 2015-03-16 at 1 33 36 pm](https://cloud.githubusercontent.com/assets/350048/6672260/a669147a-cbe1-11e4-9022-8837c379bd4a.png)
if I completely delete the block, the translation from the template takes over and it looks like this:
![screen shot 2015-03-16 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/350048/6672284/ca2245b2-cbe1-11e4-9c54-9613e50fa432.png)

While there may be other issues surrounding translation, this one is working :wink:

**Comment by nmpetkov** [comment]
Thank you for clearing this!
