### ISSUE TITLE
[1.3] Problem in changing to default language with shorturls enabled and using {getcurrenturi} in template

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2348]
It is common practice to make link for change language with placing:
```{getcurrenturi lang='bg'}```
in template (language is for example ```bg```, but can be other). In Zikula 1.3.9 changing to default language in this way with shorturls enabled is not always successful. Here is how to reproduce:

*1. Localization settings:*
    - Multilingual enabled
    - Add language to URL - only for non-default languages

*2. Short URL settings:*
    - Short URL's enabled
    - Strip entry point from directory-based URLs: Yes (recommended)

*3. Change to non-default language (here is English).* All works. Then click on a page (here in Pages module).  URL become as follows:
``` http://xyz.org/en/display/glossary-terms/ ```
This is also normal.

*4. Now change to default language with link, generated with ```{getcurrenturi lang='bg'}``` (or other language) in template.* URL goes to address bar and is:
``` http://xyz.org/en/display/glossary-terms/?lang=bg ```
Because of conflict between first part```en/``` and last one ```?lang=bg```, language failed to change. If manually remove from address bar  first fragment ```en/```, then language changes.

So, I can always change to home page, but this is not very good decision. On the other hand, changing language with "Language selector block" works very well. Quick examine of the code points, that in this block there is a procedure to handle shorturls.

My question is: are there other practice for changing language, or we need to change ```getcurrenturi ``` view-plugin to handle short URLs, or better is to write a new one, based on code in "Language selector block".

**Comment by nmpetkov** [comment]
After thinking on the problem, decided that new plugin is better solution, then to touch existing one, which is with other main functionality.

**Comment by nmpetkov** [comment]
More info. Now using above example, from:

``` http://xyz.org/en/display/glossary-terms/ ```

change to other non-default language will be:

``` http://xyz.org/de/display/glossary-terms/ ```

and change to default language:

``` http://xyz.org/display/glossary-terms/ ```

(depends on localization settins if lang code will be put).

**Comment by craigh** [comment]
> It is common practice to make link for change language with placing:
`{getcurrenturi lang='bg'}`

your PR doesn't really solve this "bug" except to add a newer (and probably better and more appropriate) solution. If this is truly a "common practice" then the bug will still exist, no?

**Comment by nmpetkov** [comment]
The bug can be solved by replacing ```{getcurrenturi)``` with ```{langchange}```.
As main purpose of ```getcurrenturi``` is to return current URI, I decided to write a new plugin, with clear purpose, instead to change existing one. And once more - problem in using ```{getcurrenturi)``` to change language appears only when shorturls are enabled.

**Comment by nmpetkov** [comment]
I'm closing this, as now it is possible to change language in template, when shorturls are enabled, by using the new plugin. Please reopen, if something is wrong.
