### ISSUE TITLE
Cannot translate routes

### ISSUE THREAD

**Issue by craigh** [zikula/core#2351]
@cmfcmf : trying to accomplish route translation according to your [docs](https://github.com/zikula/core/wiki/Release-Process)

but it fails with the following:

> [Craigs-iMac2013-2:htdocs/core.git/src] craig% php app/console translation:extract template --dir=system --output-format=po --output-dir=app/Resources/translations --enable-extractor=jms_i18n_routing --dir=lib/Zikula/Bundle -vvv
Extracting Translations for locale template
Keep old translations: No
Output-Path: app/Resources/translations
Directories: system, lib/Zikula/Bundle
Excluded Directories: Tests
Excluded Names: *Test.php, *TestCase.php
Output-Format: po
Custom Extractors: jms_i18n_routing
============================================================
Loading catalogues from "app/Resources/translations"
Extracting translation keys
Extracting messages from directory : system
Parsing file "system/Zikula"
Parsing file "system/Zikula/Module"
Parsing file "system/Zikula/Module/AdminModule"
Parsing file "system/Zikula/Module/AdminModule/AdminModuleInstaller.php"
Parsing file "system/Zikula/Module/AdminModule/AdminModuleVersion.php"
...
Parsing file "system/Zikula/Module/SearchModule/tables.php"
Parsing file "system/Zikula/Module/SearchModule/ZikulaSearchModule.php"

> [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Trying to get property of non-object               

> Exception trace:
 () at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Extractor/File/TranslationContainerExtractor.php:52
 Symfony\Component\Debug\ErrorHandler->handleError() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Extractor/File/TranslationContainerExtractor.php:52
 JMS\TranslationBundle\Translation\Extractor\File\TranslationContainerExtractor->enterNode() at /Applications/MAMP/htdocs/core.git/src/vendor/nikic/php-parser/lib/PHPParser/NodeTraverser.php:87
 PHPParser_NodeTraverser->traverseArray() at /Applications/MAMP/htdocs/core.git/src/vendor/nikic/php-parser/lib/PHPParser/NodeTraverser.php:40
 PHPParser_NodeTraverser->traverse() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Extractor/File/TranslationContainerExtractor.php:103
 JMS\TranslationBundle\Translation\Extractor\File\TranslationContainerExtractor->visitPhpFile() at n/a:n/a
 call_user_func_array() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Extractor/FileExtractor.php:165
 JMS\TranslationBundle\Translation\Extractor\FileExtractor->extract() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/ExtractorManager.php:138
 JMS\TranslationBundle\Translation\ExtractorManager->extract() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Updater.php:234
 JMS\TranslationBundle\Translation\Updater->setConfig() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/Updater.php:124
 JMS\TranslationBundle\Translation\Updater->process() at /Applications/MAMP/htdocs/core.git/src/vendor/jms/translation-bundle/JMS/TranslationBundle/Command/ExtractTranslationCommand.php:123
 JMS\TranslationBundle\Command\ExtractTranslationCommand->execute() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/core.git/src/app/console:19

**Comment by cmfcmf** [comment]
This is caused by https://github.com/schmittjoh/JMSTranslationBundle/pull/223.

**Comment by cmfcmf** [comment]
You don't have to execute the command, it will only generate the routes.pot file which I already generated for the RC1: https://github.com/zikula/core/tree/1.4/src/app/Resources/translations

**Comment by craigh** [comment]
Christian: why is the route.pot file in the /translations instead of /locale?
and how does a translator add their own?

**Comment by craigh** [comment]
updated [doc related to this ticket](https://github.com/zikula/core/wiki/Release-Process/_compare/39ca2dc187258d6a70b0a11f301e50e5f9f55620...e118f429e634e1913affc2209ec44733d997495a) and closing as not core.
