### ISSUE TITLE
Theme type in templates (and not only)

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2359]
I am working on responsive theme, and need to get specific information about the theme - if the theme is responsive or not. Currently I use a ugly solution, checking if `displayname` contains string 'bootstrap'.

After exploring the code from Zikula 1.2 to Zikula 1.4, I found, that now two fields (columns) in theme table are not in use:
`type` 
`xhtml` 
(historically they was in use, but not after Zikula 1.2)

I propose one of them to be used for that purpose. It seems `type` is more suitable, as `xhtml` can be used in future to specify which HTML standards are followed in the theme (for example HTML5 can be one option).

The problem is addressed for both Zikula 1.3 and 1.4 branches.

**Comment by craigh** [comment]
I don't see a systematic solution for this until 2.0.0

perhaps something like modules have a 'capabilities' key in the meta array.

**Comment by Guite** [comment]
Somewhen modules and themes will be merged. Then themes could reuse the capabilities field....

**Comment by Guite** [comment]
> modules and themes will be merged

refs #3644

**Comment by Guite** [comment]
The `xhtml` property has been removed.

> Somewhen modules and themes will be merged. Then themes could reuse the capabilities field....

Moving this issue to 3.0.0 because it refs #3644.

**Comment by Guite** [comment]
refs #3620, too.

**Comment by Guite** [comment]
wondering whether this has become a "won't fix"

1. @nmpetkov asked for 1.3 and 1.4
2. all themes are responsive today, aren't they?
3. I don't see the use case (anymore)

@nmpetkov do you still have an opinion about this?

**Comment by nmpetkov** [comment]
As 1.3 is not supported anymore, the issue is better to close.

**Comment by Guite** [comment]
Thanks for your feedback
