### ISSUE TITLE
[Upgrade] [CLI] Third party modules removed

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2360]
Hi, testing upgrade process for InterCom I have found that system upgrade is handlig third party module entries in modules table differently basing on if new module version is present in the system.
When module like InterCom is not present in the modules dir, information about the module is removed from the system, so there is no way to "add" module later and upgrade it later, as it was before.
When module is present in the system before system is upgraded, during system upgrade module is upgraded as well, (actually it still says new version for me but that is due to errors in module upgrade) module table is updated.
So I think this is big change since now upgrade can't be carried out in steps need to be done in one shoot?
I will test upgrade tonight carefully and see what's new.

**Comment by craigh** [comment]
IMO this is a bug in the upgrade procedure. the non-system modules shouldn't be upgraded. I'll try to take a look at this as well.

**Comment by Kaik** [comment]
I have almost finished InterCom upgrade to work with this system automatic upgrade and apart from few things at the end it is actually handy. First of all doctrine update entity do not work I chosed to do it all manually, second thing module_vars - things do not work like $this->getVars etc... and at the moment all data is migrated nicely apart from that I cannot delete old vars... and it was working like an hour ago so...i dont know...
Last thing is that during system upgrade routes are reloaded while InterCom modules needs to be reloaded just after login - I guess this might be normal behaviour.

**Comment by craigh** [comment]
please confirm that `core_max` was set to `1.4.0` or higher before the upgrade was initiated.

**Comment by craigh** [comment]
@Kaik - please check with current pull of Core. I've added some changes. thank you.

**Comment by Kaik** [comment]
Module versions all of them have max 1.3.99 apart from LuMicuLa there is no max
Clip
1.3.2
1.3.99
Thumbnail
1.3.0
1.3.99
Dizkus
1.3.2
1.3.99
LuMicuLa
1.3.0

All of them are removed from modules db after upgrade. Current core pull same issue module gets upgraded during system upgrade - module I'm talking about have no core limits.

**Comment by craigh** [comment]
I'm not sure of the best way to handle the logic of this then.

@cmfcmf @Guite, do you have any ideas?

I think the logic is the same as it is in the 1.3 branch.

**Comment by Guite** [comment]
Maybe check for modules with a too low `max core version` setting before performing the upgrade. If those are found abort with an according information?

**Comment by rallek** [comment]
Might be several options:

1. Abort
2. Keep database tables
3. Keep database and module (without installation)

**Comment by Kaik** [comment]
Upgrade is not removing module tables, it is only removing module information in modules table it is not removing old module_vars.
1.Abort or remove if someone is fine wit it. 
2. Is it possible with current modules table to keep those records? Either not touched or at least with its id, version and module name.I think module name can be altered to current naming pattern.

**Comment by craigh** [comment]
@Guite - I don't think aborting is a good plan. The current docs and practice is to upgrade the core with an empty modules folder (except profile and legal). Then upgrade each module afterwards. this is good because the core upgrader shouldn't fail if a third party module fails to upgrade. With that understanding, review the Extensions AdminApi regenerate() method. I *think* that all these modules will be skipped during the upgrade but will be immediately removed from the DB when they are not found on the first time regenerate runs post upgrade. It is quite complicated.

**Comment by craigh** [comment]
@Kaik - I made some fixes. will you please test again?

**Comment by Kaik** [comment]
Ok this is working I have tested c013. Modules are with missing files label. Now I will do some more testing I have 3 databases 1.3.5. I have tested without InterCom module present so let me do some more test and I will try to check #2367

**Comment by craigh** [comment]
closing. we can reopen if the problem reappears.
