### ISSUE TITLE
Error at zikula.org - Notice: Undefined index: owneruid

### ISSUE THREAD

**Issue by shefik** [zikula/core#2363]
The Zikula blog is throwing an error here:

http://zikula.org/blog/display/2015/3/18/jetbrains-supports-zikula

```
Notice: Undefined index: owneruid

500 Internal Server Error - ContextErrorException
```

**Comment by Guite** [comment]
This should probably be moved to https://github.com/zikula/zikula.org/issues shouldn't it? @craigh

**Comment by craigh** [comment]
i don't see any errors. and if it is the blog that would be the news module.

**Comment by Guite** [comment]
`owneruid` sounds like EZComments.

**Comment by craigh** [comment]
in either case, I see no errors.

**Comment by jguille2** [comment]
I continue with this error (like I reported at [forum](http://zikula.org/forums/topic/59848)).
  - @krator reported the trace ... it pointed to EZComments.
  - I have this problem when I'm logged. Impossible to comment a news.
  - I've seen the comments from @craigh and @espaan. You don't see any error... Do you test with standard users? Maybe admin perms hide the problem?
  - Note: My zikula.org user can't edit its profile  ('You do not have permission for that action.'). Maybe permissions must be checked.

Let's go...
Joan

**Comment by nmpetkov** [comment]
I'm also seeing this error.
It generates here:
https://github.com/zikula-modules/EZComments/blob/master/lib/EZComments/Api/User.php#L748
Obviously $args[objectid] is not set in calling function checkPermission, which is here:
https://github.com/zikula-modules/EZComments/blob/master/lib/EZComments/Api/User.php#L845

**Comment by craigh** [comment]
in any case, it is not a core issue. closing as NOT CORE. please open in EZComments.
