### ISSUE TITLE
[Upgrade] [WEB] Failed admin route not found

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2367]
Hi, I'm using cli for upgrades since quite long time because web upgrade is not working for me. Same db on cli and upgrade works fine.  Just after typing address in, it throws symfony error admin_adminpanel... route not found. I will provide error output and more information later on today.

**Comment by craigh** [comment]
build? php version?

**Comment by craigh** [comment]
> Just after typing address in

what address?

**Comment by craigh** [comment]
ping @Kaik

**Comment by Kaik** [comment]
In address bar - domain.com/upgrade.
I will pull fresh core today and will be testing everything on fresh.

**Comment by craigh** [comment]
Be sure to start with an empty cache

**Comment by Kaik** [comment]
This is the error
'''
Exception detected!

Unable to generate a URL for the named route "zikulaadminmodule_admin_adminpanel" as such route does not exist.

500 Internal Server Error - RouteNotFoundException

Stack Trace

in app/cache/dev/appDevUrlGenerator.php at line 53   -
    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }
        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];
at appDevUrlGenerator ->generate ('zikulaadminmodule_admin_adminpanel', array(), true) 
in vendor/jms/i18n-routing-bundle/JMS/I18nRoutingBundle/Router/I18nRouter.php at line 149   +
at I18nRouter ->generate ('zikulaadminmodule_admin_adminpanel', array(), true) 
in lib/Zikula/Bundle/CoreInstallerBundle/Stage/Upgrade/CompleteStage.php at line 57   +
at CompleteStage ->getResponse (object(Zikula_Request_Http)) 
in lib/Zikula/Bundle/CoreInstallerBundle/Controller/UpgraderController.php at line 62   +
at UpgraderController ->upgradeAction (object(Zikula_Request_Http), 'null')
at call_user_func_array (array(object(UpgraderController), 'upgradeAction'), array(object(Zikula_Request_Http), 'null')) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 145   +
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 66   +
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 64   +
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 186   +
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 25   +
'''

**Comment by craigh** [comment]
So the routes are apparently not being properly regenerated before this happens. During the upgrade, several text status updates are provided. Do any of them indicate problems?

**Comment by Kaik** [comment]
"During the upgrade..." there is no upgrade process at all, when you go to the upgrade address to start upgrade, above error shows straight away, there is no language no admin login etc.

**Comment by craigh** [comment]
I assumed because:

> `at CompleteStage ->getResponse (object(Zikula_Request_Http)) `

which means that it is getting to the CompleteStage somehow
