### ISSUE TITLE
installer does not allow full character set for ADMIN pwd

### ISSUE THREAD

**Issue by craigh** [zikula/core#2376]
installer does not allow full character set for ADMIN pwd - because the password is written to a yaml file temporarily, it cannot allow certain characters [without being escaped](http://symfony.com/doc/current/components/yaml/yaml_format.html)

> Strings containing any of the following characters must be quoted. Although you can use double quotes, for these characters it is more convenient to use single quotes, which avoids having to escape any backslash \:

> :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, \`

so, form values must be quoted before stored in yaml file.

**Comment by craigh** [comment]
for example, if I create the admin with the password `Bp(2%(!u%P%fT^J` then during the install process, that value is temporarily written to the `custom_parameters.yml` file but it is written without escaping it and the `!` character causes read errors.

I cannot figure out a way to force the Symfony Yaml component to quote the string so it is valid. if I add the quotes myself, then it triples or doubles them.

**Comment by craigh** [comment]
ping @Guite ideas here?

**Comment by Guite** [comment]
My idea would be removing `Zikula\Bundle\CoreBundle\YamlDumper` and using `Symfony\Component\Yaml\Dumper` instead.

**Comment by craigh** [comment]
`Zikula\Bundle\CoreBundle\YamlDumper` uses the functionality of `Symfony\Component\Yaml\Dumper` through the `Symfony\Component\Yaml\Yaml` class.
