### ISSUE TITLE
Allowed memory size exhausted 

### ISSUE THREAD

**Issue by hvorragend** [zikula/core#238]
Could it be that we have a memory problem in the core? See: https://github.com/zikula-modules/Clip/issues/70

I have a very small demo installation in German and English. And I have in various places, several error messages about not enough memory. Apparently this is not due to the number of installed and simultaneously used modules and hooks, for I have uninstalled several modules for testing purposes.

**Settings**
- Dev-mode off
- Shorturls off
- Theme/Template compiling on (same problem as 'off')

**Used modules:**
News, Pages, Clip, BBCode, EZComments, ...

**Environment:**
- PHP Version 5.3.8-nmm1
- Server API: CGI/FastCGI 
- memory_limit: 64M

.htaccess

```
AddHandler php53-cgi .php

# security options if they work in your environment.  If you get a 500 error then they wont.
# These settings are best turned off in php.ini and will be on modern hosting environemnts.
php_flag magic_quotes_gpc off

# turn the rewriting engine on
RewriteEngine On
```

**Comment by JialuZhang** [comment]
@hvorragend 

In your posted configuration,
```
# turn the rewriting engine on
RewriteEngine On
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.
More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.
The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
