### ISSUE TITLE
Single id is not allowed on composite primary key in entity

### ISSUE THREAD

**Issue by shefik** [zikula/core#2380]
I am attempting to create a module, and I have a entity defined with the following column:

```
    /**
     * @ORM\Column(type="integer")
     */
    private $content_type;
```

However, upon module installation, this error is thrown:

```
Single id is not allowed on composite primary key in entity
```

If I change "content_type" to "type", installation is successful.

```
    /**
     * @ORM\Column(type="integer")
     */
    private $type;
```

So, why is the module installation failing with that error? I don't have any other modules installed. Only the Zikula core. Is "content_type" reserved?

**Comment by Guite** [comment]
This error is not Zikula-specific, but thrown by Doctrine.

Searching for the error message shows corresponding threads, for example http://stackoverflow.com/questions/19683811/getting-issues-while-trying-to-generate-doctrine2-crud

Closing as `not core`.

**Comment by shefik** [comment]
@Guite Thanks for the link, but even though it's an error thrown by Doctrine, it still doesn't make sense why just changing the column name from "content_type" to "type" makes it work. I am not able to create a column with the name "content_type". Since I don't have any other modules installed (only the Zikula core), why would that even happen?

**Comment by Guite** [comment]
Probably this one: http://elnur.pro/how-to-enable-the-underscore-naming-strategy-for-doctrine-orm-in-symfony/

**Comment by shefik** [comment]
I tried setting this in config_prod.yml: 

```
doctrine:
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
```

But, that causes errors with Routes. Now, a message is displayed at the top of the page that says:

```
Routes must be reloaded. Click here to reload all routes.
```

Going to the URI at /routes/routes/reload?lct=admin&confirm=1 throws the error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.workflow_state' in 'field list'
```

So, is this now a Zikula bug, since that Doctrine setting that can't be set properly?

**Comment by Guite** [comment]
No, it isn't.
If you change a global Doctrine setting, then this naturally affects all modules. So in theory you would have to change all database fields from mixed case to underscores.
Better would be using the dbName attribute like this:

```
    /** @Column(type="yourtype", name="content_type") */
    private $contentType;
```

(taken from http://doctrine-orm.readthedocs.org/en/latest/reference/basic-mapping.html#property-mapping )

**Comment by shefik** [comment]
Ok, it works now, by explicitly setting the column name:

```
name="content_type"
```

Setting "doctrine.orm.naming_strategy.underscore" is not needed.

Thanks.
