### ISSUE TITLE
Localisation settings: can not set different default language

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2382]
How to reproduce:
1. Install one or two other languages (other then English).
2. Go to Settings, Localisation settings.
3. Try to change drop-down "Default language to use for this site".

In my case I can't change.

Analysis:
1. I checked in database, and it is changed, as seen in the picture below:
![image](https://cloud.githubusercontent.com/assets/628801/6919998/51d06780-d7c4-11e4-9dd4-b40e3bb5b193.png)
2. When the site is loaded, and I examine the variable, it is 'en':
![image](https://cloud.githubusercontent.com/assets/628801/6920059/ca9f091e-d7c4-11e4-99e0-1dc233e86500.png)
So, somehow the default language is not set in proper way.

System: New install, Zikula 1.4 build 515.

**Comment by craigh** [comment]
the route is being translated but the strings are not being loaded from the translated catalog. This worked properly a week+ ago. grrrr...

**Comment by craigh** [comment]
if I append `?lang=de` to my url, all the strings are properly translated and it appears to work, so this may be more simple than it appears.

**Comment by nmpetkov** [comment]
I tis not connected to routes I think, just config variable ```language_i18n``` is loaded as 'en' in this line:
https://github.com/zikula/core/blob/1.4/src/lib/i18n/ZLanguage.php#L142
But in database the value is 'de' (for example, after trying to change default language - not by URL, but in settings).

**Comment by craigh** [comment]
> https://github.com/zikula/core/blob/1.4/src/lib/i18n/ZLanguage.php#L142

that line loads from the DB and sets `en` as the default if it cannot load the value.

**Comment by nmpetkov** [comment]
As I examine back trace, this is maybe first call to ```System::getVar```.
```
#0  ZLanguage->__construct() called at [/home/cmstory/public_html/zktest/lib/i18n/ZLanguage.php:181]
#1  ZLanguage::getInstance() called at [/home/cmstory/public_html/zktest/lib/i18n/ZLanguage.php:332]
#2  ZLanguage::getLanguageCode() called at [/home/cmstory/public_html/zktest/lib/util/ModUtil.php:151]
#3  ModUtil::setupMultilingual() called at [/home/cmstory/public_html/zktest/lib/util/ModUtil.php:131]
#4  ModUtil::initCoreVars() called at [/home/cmstory/public_html/zktest/lib/legacy/Zikula/Core.php:519]

```

**Comment by nmpetkov** [comment]
I think, I found the reason. In module_vars table, I found two records for same value! 
![image](https://cloud.githubusercontent.com/assets/628801/6927175/43abf0ae-d7f4-11e4-9bd9-7c1cf8dd6991.png)
and ih this cycle:
https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L119
second one overrides first (true) one!

**Comment by craigh** [comment]
hmmmm. can you provide a PR? :stuck_out_tongue_winking_eye:

**Comment by nmpetkov** [comment]
First have to find way duplicates appear...

**Comment by craigh** [comment]
I have two also

![screen shot 2015-03-31 at 3 25 19 pm](https://cloud.githubusercontent.com/assets/350048/6927265/2f3a542e-d7ba-11e4-8491-6c3a9e0e0e56.png)

**Comment by craigh** [comment]
seems like that shouldn't be possible. I thought the modular system would have handled that. maybe the new installer?

**Comment by craigh** [comment]
oooh - I should mention that my screenshot is from a build without a second language installed.

**Comment by craigh** [comment]
this has two:

![screen shot 2015-03-31 at 3 28 13 pm](https://cloud.githubusercontent.com/assets/350048/6927328/947809da-d7ba-11e4-9d28-17a8fb92cc33.png)

**Comment by nmpetkov** [comment]
Maybe they occur  when writing values after editing Settings in the site.

**Comment by craigh** [comment]
I bet it happens on install.

**Comment by craigh** [comment]
before any changes - I'll try to reinstall build 515 and get back to you

**Comment by nmpetkov** [comment]
Apart of the reason, maybe it is good to edit this cycle:
https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L119
to get first values only.

**Comment by craigh** [comment]
yes. it is somehow set twice in the installation process. After a fresh installation, I have two instances.

here is one: https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php#L287

**Comment by craigh** [comment]
another is here: https://github.com/zikula/core/blob/1.4/src/system/Zikula/Module/SettingsModule/SettingsModuleInstaller.php#L100

**Comment by nmpetkov** [comment]
This check is based on the presumption, that every variable exist in this array, if exists in database. Safer will be to check if exist in database, to change, and  if not - to add:
https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L270

**Comment by craigh** [comment]
looks from there like if it does not exist in the array, it checks the DB, no?

**Comment by craigh** [comment]
oh - I read it wrong. maybe not

**Comment by craigh** [comment]
I fixed the main problem. the redundancy of `ModUtil::setVar()` hasn't been an issue before, so probably better not to fuss with it at this point. But it may need some improvement - maybe open a ticket and we'll assign it to 1.4.1 :smile:

**Comment by nmpetkov** [comment]
BTW I found one more duplicate. I executed in phpMyAdmin folowing query:
```SELECT modname, name, COUNT( * )  FROM module_vars GROUP BY modname, name HAVING COUNT( * ) >1```
and the result is:
![image](https://cloud.githubusercontent.com/assets/628801/6928098/68eb6f9c-d7fa-11e4-9118-7c58f411d923.png)

**Comment by nmpetkov** [comment]
@craigh , as it is visible from the picture above, and as I've just tested, Admin e-mail address also can not be changed, and the reason is the same.

**Comment by nmpetkov** [comment]
Is this needs separate issue?

**Comment by craigh** [comment]
> Is this needs separate issue?

I think it is covered by your other ticket
