### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by cordoval** [zikula/core#2383]
sorry i don't know where else to put this. I am trying to reach drak because on github it seems his account was tied to a package in packagist https://packagist.org/packages/drak/native-session and this is gone.

can we stale his account but recover it please?

**Comment by cmfcmf** [comment]
I don't know what happened either. Maybe @craigh, @Guite or @rallek know :disappointed:

**Comment by cordoval** [comment]
solved zikula/NativeSession , @drak --rip-- did it again from his grave :older_man:

**Comment by cordoval** [comment]
cc  @iambrosi

**Comment by iambrosi** [comment]
Awesome! Thanks
