### ISSUE TITLE
Duplicate values in module_vars table

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#2385]
The logic of ```ModUtil::setVar``` procedure allows to happen duplicate values for module and config variables. This is truth for both Zikula 1.3 and Zikula 1.4 branches.
Examples here:
#2382

Example for 1.3 branch:
```SELECT modname, name, COUNT( * )  FROM module_vars GROUP BY modname, name HAVING COUNT( * ) >1```
![image](https://cloud.githubusercontent.com/assets/628801/6928472/ef2c7068-d7fc-11e4-8520-4a2d34a5790d.png)

Also, logic in ```ModUtil::initCoreVars``` makes last one to override previous, and it makes impossible to edit this variables in the interface of the site.

**Comment by nmpetkov** [comment]
In 1.3 branch even if duplicates exists, they are ALL updated, as seen in this code fragment:
```
$where = "WHERE $cols[modname] = '" . DataUtil::formatForStore($modname) . "'
                         AND $cols[name] = '" . DataUtil::formatForStore($name) . "'";
$res = DBUtil::updateObject($obj, 'module_vars', $where);
```

In 1.4 branch is updated only FIRST ONE, as seen from the code:
```
$entity = $em->getRepository('Zikula\Core\Doctrine\Entity\ExtensionVarEntity')->findOneBy(array('modname' => $modname, 'name' => $name));
$entity->setValue($value);
```
(using ```findOneBy```)

**Comment by craigh** [comment]
The issue in this case is not ensuring all duplicates are updated, but preventing a duplicate from being created in the first place. As I test this code, the condition you refer to is never reached. So, while *later* updates might be fixed by changing the code you reference, it doesn't fix the initial problem.
