### ISSUE TITLE
Wrong paths to js files

### ISSUE THREAD

**Issue by jusuff** [zikula/core#2391]
Installed fresh build 515
Paths to js files defined in this manner:

    {pageaddvar name='javascript' value='@ZikulaUsersModule/Resources/public/js/Zikula.Users.Common.UserValidation.js'}

are broken. This one is evaluated to:

    http://zikula-build-515.zikula.w/%5Csystem%5CZikula%5CModule%5CUsersModule/Resources/public/js/Zikula.Users.Common.UserValidation.js

Have no idea how this work so couldn't debug this.

**Comment by shefik** [comment]
Looks like the problem might be with this function:

```
resolveSymfonyAsset()
```

Line 403 here:

```
/lib/util/PageUtil.php
```

**Comment by shefik** [comment]
@jusuff Is your Zikula installation actually encoding the result ```%5Csystem%5CZikula%5CModule%5CUsersModule```, or is that GitHub encoding it?

**Comment by jusuff** [comment]
Zikula.

**Comment by shefik** [comment]
My Zikula installation is correctly returning the path:

```
/system/Zikula/Module/UsersModule/Resources/public/js/Zikula.Users.Common.UserValidation.js
```

So, I'm wondering if it has to do with where you installed Zikula?

**Comment by jusuff** [comment]
What OS? I'm using Windows. Maybe this is the reason?
But it was ok few days ago. Got this issue yesterday after updating my working copy and today, installing RC from CI build.

**Comment by shefik** [comment]
That might be the problem then. I am using MAMP on Mac.

**Comment by jusuff** [comment]
So will try to debug this.

**Comment by shefik** [comment]
Can you take a look at lines 419 - 421 of this file:

```
/lib/util/PageUtil.php
```

The issue is with those lines.

**Comment by shefik** [comment]
@jusuff Also, it might help taking a look at this file:

```
/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php
```

Line 250 - ```function locateResource```

**Comment by craigh** [comment]
ping @cmfcmf you created the `@` notation for assets.

**Comment by craigh** [comment]
ping @jusuff have you tested this? does it work?

**Comment by jusuff** [comment]
Looks like @cmfcmf fix solved the issue. Paths are fine right now.
