### ISSUE TITLE
Ensure we use Symfony 2.6.6

### ISSUE THREAD

**Issue by Guite** [zikula/core#2392]
A security update has just been released:

http://symfony.com/blog/symfony-2-6-6-released

**Comment by craigh** [comment]
composer should automatically update to latest in 2.6.x release

**Comment by craigh** [comment]
`"symfony/symfony": "2.6.*",`

**Comment by craigh** [comment]
build [526](http://ci.zikula.org/job/Zikula_Core-1.4.0/) includes symfony 2.6.6
