### ISSUE TITLE
Doctrine ORM 2.4.x EOL, 2.5.0 released

### ISSUE THREAD

**Issue by craigh** [zikula/core#2398]
When should this be included in Zikula? (temporarily set to 1.4.0 pending discussion)

> Doctrine ORM 2.4.8 will be the last bugfix release for the 2.4.x series. Further releases will only occur in the eventuality of a security issue being discovered.

http://www.doctrine-project.org/2015/04/02/orm-2-5-0.html

BC Breaks: http://docs.doctrine-project.org/en/latest/changelog/migration_2_5.html#behavioral-changes-bc-breaks

**Comment by shefik** [comment]
How much of the Zikula core is actually effected by those BC breaks? If it's minimal, or non-existent, then I say to upgrade to the new Doctrine version, and correct the core where needed.

**Comment by Guite** [comment]
Personally I think get it into 1.4.

Especially http://docs.doctrine-project.org/en/latest/changelog/migration_2_5.html#events-postload-now-triggered-after-associations-are-loaded is a very useful feature.

**Comment by Guite** [comment]
The only problem I can see is it requires PHP 5.4.

**Comment by Guite** [comment]
On the other hand 2.4.x is EOL...

**Comment by craigh** [comment]
> How much of the Zikula core is actually effected by those BC breaks?

unknown. feel free to test :stuck_out_tongue_winking_eye: 

> The only problem I can see is it requires PHP 5.4.

This gets to an argument about philosophy in development. Should the Core 1.x release continue with the same system requirements (e.g. PHP 5.3) or can those requirements be changed during the 1.x release cycle? If change is allowed, then certainly we can bump this change to 1.4.1 right? Of course I have no idea what has already been changed with regard to system requirements and available libraries between 1.0 and 1.4. :stuck_out_tongue_closed_eyes: 

My bigger concern is the time required for proper testing and fixing. Core 1.4.0 is close to release and I don't want to delay it unnecessarily.

**Comment by craigh** [comment]
for that matter, Symfony 2.6.x is EOL in [three months](http://symfony.com/roadmap#checker)

hmmm. Maybe Core 1.4 should not be based on Symfony 2.6?

**Comment by Guite** [comment]
The version checker also shows that Symfony 2.7 will be a long term support version published in May 2015. But as you say this just delays 1.4.0.

Thus my vote is: keep existing stuff for 1.4.0.
Update to Doctrine ORM 2.5.0 and Symfony 2.7 in 2.0.0.

**Comment by craigh** [comment]
did a quick test at upgrading and found several challenging items. I think this will be more difficult than one would wish and therefore delaying until 2.0.0 is IMO required since it could significantly delay Core 1.4.0. Therefore I agree with @Guite 

> keep existing stuff for 1.4.0.
Update to Doctrine ORM 2.5.0 and Symfony 2.7 in 2.0.0.

**Comment by craigh** [comment]
Doctrine was updated to 2.5. in 78f056e3fcf45a5d39d8e3f4d5e29531101cdace
