### ISSUE TITLE
Handle mbstring.internal_encoding in ZK 1.3.x 

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2406]
like done in https://github.com/zikula/core/pull/2199

**Comment by craigh** [comment]
@Portugao did you mean to issue a PR to fix this issue? It appears you referenced this ticket in a fix you pushed to your own fork, but did not follow through with the PR.

**Comment by craigh** [comment]
fixed by https://github.com/zikula/core/commit/ceefba6ae75305ee2b0cf328aab1ae014e222bc3

**Comment by Portugao** [comment]
Sorry. Missed your question.
Yes. This was to fix the issue in the core.

**Comment by craigh** [comment]
I was able to merge it with your credit. :+1:

**Comment by Portugao** [comment]
:+1:
