### ISSUE TITLE
Unable to Set Custom Locale

### ISSUE THREAD

**Issue by shefik** [zikula/core#2407]
Custom text is not being loaded for modules. Using the module Dizkus as an example,

I tested custom locale file in the following paths:

```
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.po
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.mo
```

or

```
/config/locale/en/LC_MESSAGES/module_dizkus.po
/config/locale/en/LC_MESSAGES/module_dizkus.mo
```

However, the custom text is not being loaded. When I go to this URL:

```
/forums
```
Only the following "Search overrides" domains are loaded:

```
systemplugin_imagine
systemplugin_mapstraction
zikula
```

Line 550 of:

```
/lib/i18n/ZLanguage.php
```

**Comment by Guite** [comment]
Fixed by https://github.com/zikula/core/pull/2408
