### ISSUE TITLE
Re-think about robots.txt

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2410]
Our robots.txt currently blocks module css / js files and system javascript files. According to Google, it should not do so: 
- https://www.google.com/webmasters/tools/mobile-friendly/?url=zikula.org
- https://developers.google.com/webmasters/mobile-sites/mobile-seo/common-mistakes/blocked-resources

**Comment by Guite** [comment]
:+1: I removed the `modules` and `themes` folders in some installations. `system` should probably be removed, too.

**Comment by Guite** [comment]
Another possible solution would be installing extension assets to `web` after installation/upgrade and remove them again after uninstall.

**Comment by Guite** [comment]
Closing in favour of #3273
All assets should be delivered from `/web` which is the cleaner way.
