### ISSUE TITLE
confirm Setting module upgrade works properly.

### ISSUE THREAD

**Issue by craigh** [zikula/core#2415]
refs #2413 and https://github.com/zikula/core/commit/1b95d9689f8802ca7fd7126a9bb355571078f7f9

ping @nmpetkov please check this (upgrade 1.3.9 -> 1.3.10) and see if back porting is required.

**Comment by nmpetkov** [comment]
I know for this behavior as I upgraded 3 sites to Zikula 1.3.10, and for me it is normal. 
In fact site name, description and meta tags remain untouched for default language, and are blank for non-default languages, if any. I can make PR to fulfill them when upgrading, but only to replicate those for default language.

**Comment by craigh** [comment]
> I can make PR to fulfill them when upgrading, but only to replicate those for default language.

@nmpetkov please do

**Comment by cmfcmf** [comment]
For what I can see, this is not needed, as the default settings will be used if no multilingual page title is defined.
