### ISSUE TITLE
update/remove unneeded JS vendors

### ISSUE THREAD

**Issue by craigh** [zikula/core#2416]
Several [vendors](https://github.com/zikula/core/blob/1.4/src/docs/VENDORS.md) are included in our own repo.

Many of these, in combination with those included at by composer, are either redundant, woefully out of date, or irrelevant.

These libraries should be updated or removed as appropriate. Some others should be _justified_ for the continued inclusion in the core.

possible redundancies:
Color
1. PickyColor
2. jquery-minicolors

shim/shiv/polyfill
1. Webshim
2. Modernizer
3. html5shiv

tree
1. jstree
2. Zikula.Menutree.Tree.js

calendars
1. DHTML calendar
2. jQuery calendar

There are others probably . I realize SOME of these are present due to BC concerns and this is understandable.

For 2.0.0 we should significantly reduce this...

@shefik @cmfcmf @Guite

**Comment by shefik** [comment]
I don't think we need html5shiv anymore, since we have dropped support for older versions of IE.

**Comment by shefik** [comment]
We currently use Modernizr 2.6.2, but the latest version is Modernizr 2.8.3, so it should be upgraded. It is still useful for detecting browser features and applying custom CSS classes, based on the detected features. Modernizr is not a polyfill, so it doesn't add features to a browser. It only detects what is available. Webshim is polyfill that adds features. So, the two can work in conjunction with each other.

**Comment by shefik** [comment]
Both ```PickyColor``` and ```jquery-minicolors``` can probably be removed, because we should use the HTML5 native "color" input type. For browsers that don't currently support the "color" input type, Webshim can load its polyfill.

Demo:

http://afarkas.github.io/webshim/demos/demos/cfgs/input-color.html

**Comment by Guite** [comment]
PickyColor is for BC only.
jquery-minicolors could indeed be removed (was added in #1728).

As this issue is scheduled for 2.0.0 probably both scripts can be removed then without problems.

**Comment by Guite** [comment]
Depends on #2034

**Comment by Guite** [comment]
How about removing the following ones, too:

1. https://github.com/zikula/core/tree/master/src/javascript/jquery-plugins/jQuery-Timepicker-Addon
-> not needed as the browser (or webshim polyfill) provide a time picker

2. https://github.com/zikula/core/tree/master/src/javascript/plugins/colorbox
-> we also include magnific popup as a lightbox solution https://github.com/dimsemenov/Magnific-Popup here https://github.com/zikula/core/blob/master/src/system/ThemeModule/composer.json#L25

3. https://github.com/zikula/core/tree/master/src/javascript/plugins/jQuery-contextMenu
Bootstrap context menus are more accessible and compatible with touch devices
