### ISSUE TITLE
[Install/Upgrade] [Web/Cli][prod/dev] Tests

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2417]
Hi,
My setup is 4 local installations 3 of them are actually running sites last one is plain core.

Now this is small script to refresh db, different for each db
commented ones are for one pretty messy db 1.3.4 version 
```
#!/bin/bash
 
backup="mysql/databases/`date +%Y-%m-%d`/mysqldump-`date +%Y-%m-%d`.gz"
user="xxx"
password="xxx"
database="xxx"
theme=''
version=''

# delete database
mysql --user="$user" --password="$password" --database="$database" --execute="DROP DATABASE $database;"
# create database
mysql --user="$user" --password="$password" --execute="CREATE DATABASE $database;"

# Import database
gzip -dc < "$backup" | mysql --user="$user" --password="$password" --database="$database"

# change theme
mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:20:\"ZikulaAndreas08Theme\";" WHERE id = 20;'

# change version
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:5:\"1.3.5\";" WHERE id = 36;'

# change lang from pl/pol
# language_i18n
mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:2:\"en\";" WHERE id = 1598;'
# language
mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:3:\"eng\";" WHERE id = 48;'

# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:0:\"\";" WHERE id = 82;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:0:\"\";" WHERE id = 92;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:0:\"\";" WHERE id = 94;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:0:\"\";" WHERE id = 248;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE module_vars SET value ="s:0:\"\";" WHERE id = 1602;'

# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 160;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 35;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 28;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 106;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 184;'
# mysql --user="$user" --password="$password" --database="$database" --execute='UPDATE modules SET capabilities ="a:0:{}" WHERE id = 197;'
# mysql --user="$user" --password="$password" --database="$database" --execute="DELETE FROM objectdata_attributes WHERE attribute_name = 'dizkus_users_posts';"
```
Yesterday I have tested install and upgrade with prod env.
Install
1. web went smoothly ~~but has to be called before any cli calls because of 2~~
2. ~~cli cals config_ not found this is what I have written yesterday at night~~ Cannot log in as admin. Admin username, email and password gets corrupted somehow ref #2419 
Upgrade
1. WEB This is cool first time I have upgraded using web interface and it works but:
1.1  Theme need to be andreas08, bootstrap theme is breaking upgrade ref #2418 
1.2 Lang need to be eng #2418
1.3 Intercom module upgraded automatically with system modules
2.CLI is failing with pass/username incorrect error  ref #2419 

Now this is for prod env. All my previous upgrades were on dev and on cli, web interface was not working for me then (or I have not tested it in prod)

Today I will refresh all that once again for all installations and will provide some more details on errors.

**Comment by Kaik** [comment]
Install CLI prod
Everything goes ok 

```
*** INSTALLING ***
Symfony Bundles
Symfony Bundles persisted
Zikula Extension Module
Zikula Extensions Module installed
Zikula Settings Module
Zikula Settings Module installed
Zikula Theme Module
Zikula Theme Module installed
Zikula Administration Module
Zikula Administration Module installed
Zikula Permissions Module
Zikula Permissions Module installed
Zikula Groups Module
Zikula Groups Module installed
Zikula Blocks Module
Zikula Blocks Module installed
Zikula Users Module
Zikula Users Module installed
Zikula Security Module
Zikula Security Module installed
Zikula Categories Module
Zikula Categories Module installed
Zikula Mailer Module
Zikula Mailer Module installed
Zikula Search Module
Zikula Search Module installed
Zikula Routes Module
Zikula Routes Module installed
Activate system modules
System modules activated
Module categorization
Modules moved to their default categories
Create blocks
Default blocks created
Create admin account
Admin account created
Login
Logged in as admin
Finalize parameters
Parameters finalized
Reload routes
Routes reloaded
System Plugins
System Plugins installed
Protect configuration files
Configuration files protected
Finish
Finish
```
Viewing site in browser home page
```
Whoops, looks like something went wrong.

1/1
InvalidArgumentException in FileLocator.php line 44:
The file "/home/Kaik/public_html/core/src/app/config/config_.yml" does not exist.
in FileLocator.php line 44
at FileLocator->locate('/home/Kaik/public_html/core/src/app/config/config_.yml', null, true) in FileLocator.php line 54
at FileLocator->locate('/home/Kaik/public_html/core/src/app/config/config_.yml') in YamlFileLoader.php line 40
at YamlFileLoader->load('/home/Kaik/public_html/core/src/app/config/config_.yml', null) in DelegatingLoader.php line 45
at DelegatingLoader->load('/home/Kaik/public_html/core/src/app/config/config_.yml') in ZikulaKernel.php line 53
at ZikulaKernel->registerContainerConfiguration(object(DelegatingLoader)) in Kernel.php line 620
at Kernel->buildContainer() in Kernel.php line 533
at Kernel->initializeContainer() in ZikulaKernel.php line 306
at ZikulaKernel->initializeContainer() in Kernel.php line 128
at Kernel->boot() in ZikulaKernel.php line 85
at ZikulaKernel->boot() in bootstrap.php line 34
at include('/home/Kaik/public_html/core/src/lib/bootstrap.php') in index.php line 16
```

**Comment by Kaik** [comment]
But now new thing appeared when installed using cli installer using default values it is adding 
i٢ r as admin in users table, where i٢ is username r is email. Cannot log in as admin. Admin username, email and password gets corrupted somehow.

**Comment by Kaik** [comment]
I was updating today whole day :) and for 3 only one gets upgraded and only using web upgrade.
For 2 others web upgrade ends up with errors. Starting from "Theme  regeneration"  with ajax error that routes module is miss-configured. Everything from that point is red and finishes with mentioned ajax error, afterwards upgrade/compleated page is not accessible as well as many others with this:
```
Oops! An Error Occurred

The server returned a "404 Not Found".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Unable to find the controller for path "/pl/useraccount". The route is wrongly configured.
```
Apart from that the only one "working" is completely broken /en/login page.
Funny thing is that db that upgrades is copy of the one that not upgrades. It was copied few years ago and different site was created on it. At the moment I'm investigating ZConfig vars as I think this might cause different routes module configuration.

**Comment by craigh** [comment]
@cmfcmf can you look into this?

**Comment by Kaik** [comment]
I will try to investigate that cli problem, this might help me debug other things.

**Comment by Kaik** [comment]
Ok I'm getting closer at least in upgrading. So I was able to get the upgrade finished in cli mode then home page showed up. Log in and just after pressing log in button it redirects me to routes/reload end ending up in too many redirections.
So I could not go to redirect page because some routes inside theme (Andreas08) triggers another redirect to, same page. I have switched theme to bootstrap in phpmyadmin and that worked. I guess new admin menu will be the reason for that. For this issue I think that either this (reload routes/unknow route) exception catch should be somehow adopted to avoid that specific case when routes/reload? url is loaded or just remove all that admin theming around routes module so it looks like "Dooing something important" part.

**Comment by craigh** [comment]
which build are you testing with? or github up-to-date?

**Comment by Kaik** [comment]
github 8e4be5e0c

**Comment by craigh** [comment]
@Kaik please try with current build/pull. I have made several fixes/improvements. please try in English first and then `pl`. please report back.

**Comment by craigh** [comment]
closing this. please open a new ticket if you find the need.
