### ISSUE TITLE
upgrade requires EN and default theme

### ISSUE THREAD

**Issue by craigh** [zikula/core#2418]
this should be either documented or (preferably) compensated for in the upgrade process.

**Comment by craigh** [comment]
refs #2417

**Comment by craigh** [comment]
The theme is ***supposed*** to be reset to `Andreas08` [during the upgrade](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Stage/Upgrade/InitStage.php#L103-L104). So this *should* work. testing would be terrific.

**Comment by craigh** [comment]
also - one should be able to select language on install or upgrade as the functionality is there, but the language pack must be installed also. perhaps @kaik was attempting to upgrade in `pl` but didn't include the lang pack before running the upgrade?

**Comment by Kaik** [comment]
I was, actually after some time I have added script to change the lang to en/eng so the best I think would be to detect if language is available if not then force eng.

I will do upgrade and install test tomorrow. Need to update pl lang as well.

**Comment by craigh** [comment]
I think this is solved. please open a new ticket if you find the need.
