### ISSUE TITLE
Adding translations to app/Resources/translations

### ISSUE THREAD

**Issue by shefik** [zikula/core#2420]
According to the docs:

```
There currently are two different places where translations are stored.

1. The legacy app/Resources/locale folder: Have a look for the files zikula.pot and zikula_js.pot. Both *.pot files do have the summary of all translatable strings. These files must be translated into zikula.mo and zikula_js.mo and then placed into app/Resources/locale/{lang}/LC_MESSAGES (where {lang} is the standardized abbreviation for your language (e.g. de for german). A locale.ini is needed also. Copy the one you will find in /src/app/Resources/locale/en/locale.ini and make the appropriate changes for your language. To translate a module in Zikula 1.4.x, the file name must be in the format modulename.mo. To translate a module in Zikula 1.3.x, the file name must be in the format module_modulename.mo.

2. The new app/Resources/translations folder: Copy all contained files to <filename>.<lang>.po (for example routes.template.po => routes.de.po) and translate the .po files as usual.

```

Adding translations to `app/Resources/translations` doesn't appear to be working.

Tested by adding these files:

```
/app/Resources/translations/zikula.en.mo
/app/Resources/translations/zikula.en.po
```

Is this supposed to be working right now in Zikula 1.4.x? Or, is this a change for Zikula 2.0.0?

ping @cmfcmf

**Comment by craigh** [comment]
@shefik - why translate to English (`en`)? The core is already in English...

**Comment by cmfcmf** [comment]
Hey @shefik, the old translations must be placed inside the locale directory. Only the new translations, routes.x.po, validators.x.po, might be placed in the translations directory. That's what the documentation tries to say. You don't have a choice where to put your translations. It depends on whether or not it's a new Symfony based translation or the old Zikula translation.

**Comment by Guite** [comment]
> why translate to English (en)? The core is already in English...

For example for customising.

**Comment by shefik** [comment]
@craigh I am customizing the English, to display text that I desire.

**Comment by shefik** [comment]
@cmfcmf I’m not clear on this, because what determines an "old translation”? Aren’t all files using Gettext? How does a module determine to get the file from the new location? Is the file routes.template.po part of the Routes module, and where is validators.template.po coming from? When I use Poedit to “Update from POT File”, it creates both .po and .mo files, so in that directory, only .po files exist. What about .mo files?

**Comment by cmfcmf** [comment]
By old translation, I mean "generated with the Gettext module".

**Comment by cmfcmf** [comment]
Whereas "new translation" = "generated with Symfony command" https://github.com/zikula/core/blob/1.4/build.xml#L120

**Comment by shefik** [comment]
So, should all modules be generated with the Symfony command eventually?

**Comment by cmfcmf** [comment]
The Symfony command doesn't extract the "old Zikula translations", like `$this->__('blubb')`.

**Comment by craigh** [comment]
`_('blubb')` is how get text is currently implemented (through a sort of 'plugin') in twig templates also

this is a matter debate for the future...

**Comment by shefik** [comment]
@cmfcmf What about this question?

`When I use Poedit to “Update from POT File”, it creates both .po and .mo files, so in that directory, only .po files exist. What about .mo files?`

**Comment by craigh** [comment]
This ticket doesn't appear to have any way to "solve" it. If there is a bug or a problem, please open a ticket with a clear explanation of the problem.
