### ISSUE TITLE
isSimpleArithmeticExpression Doctrine method error

### ISSUE THREAD

**Issue by espaan** [zikula/core#2421]
HI, Im testing SimpleMedia2 (MOST 0.6) in Zikula 1.4 build550,
Calling the frontend I get an 
```
 Attempted to call method "isSimpleArithmeticExpression" on class "Doctrine\ORM\Query\AST\PathExpression".
500 Internal Server Error - UndefinedMethodException 

Stack Trace

    in vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php at line 2145
```
this seems to be an error in SQLWalker in Doctrine itself
I find also this 
https://github.com/KnpLabs/KnpPaginatorBundle/issues/67
https://github.com/beberlei/DoctrineExtensions/issues/71

Could this be related to the Paginator in Doctrine being changed ? 
@guite ?

**Comment by craigh** [comment]
I believe Zikula 1.4.0 *requires* MOST 0.7

**Comment by espaan** [comment]
Which is not released :-D 
It might work when generated for 1.4
SimpleMedia2 is generated for 1.3.x still, since that is the stable released version.

**Comment by craigh** [comment]
neither is Core 1.4.0 released.

Axel made it clear in a previous ticket that if you want core 1.4.0 compatibility, you must use MOST 0.7. The 0.6 generator has a `core_max` setting of `1.3.99` for a reason.

**Comment by craigh** [comment]
refs https://github.com/zikula/core/issues/2329

**Comment by espaan** [comment]
okido clear. 
That is still unfortunate, since it will delay people using MOST modules in early usage of 1.4.x

**Comment by espaan** [comment]
Close then ?

**Comment by rallek** [comment]
But cmf made in #2404 a promising fix.

I still think if most modules are not running under 1.3 and 1.4 the 1.4 will not have success! 1.4 is promising to extend 1.3 with 2.0 technology.

I have to accept the things as they are but I am the same unhappy than Erik.

**Comment by rallek** [comment]
A clear documentation how to fix a most 1.3 module to run under 1.4 as well would be ok.

**Comment by espaan** [comment]
Hi, I'm not really unhappy as such :-), just stating that I will jump onboard a little later if MOST modules have to be converted first. I do like 14 and all the tech, but that's how it is.

And indeed a "minor" manual fix to get it running would be fine for me too. Just to get in the 1.4 line,

**Comment by Guite** [comment]
About the minor fix: https://github.com/zikula/core/issues/2329#issuecomment-77694762

**Comment by espaan** [comment]
So if I understand correct, it should be able to do that by hand  in a MOST module ?
to update for hte Paginator I mean ?

**Comment by craigh** [comment]
closing as not core.
