### ISSUE TITLE
Reevaluate workflows

### ISSUE THREAD

**Issue by Guite** [zikula/core#2423]
Current workflow implementation has integration problems with Doctrine, since it is too decoupled from the actual entities. This makes problems with cascades, bulk imports and other activities.
Thus we should move to the Symfony workflow component instead. Here an entity only carries one field storing it's current state which is far easier to manage.

**Comment by Guite** [comment]
I propose removing the workflow table completely. Instead an entity should only carry one field storing it's current state. This should be far easier to manage.
The workflow component needs only three arguments then: name of used workflow, full-qualified entity name and the name of the state field.

**Comment by Kaik** [comment]
:+1:

**Comment by craigh** [comment]
I've never looked at the workflow code. Go ahead and implement your plan. :+1: be sure to maintain BC.

**Comment by Guite** [comment]
Is BC important when it is changed in 2.0 ?

**Comment by craigh** [comment]
I don't really know what we're dealing with here, so I can't give a proper answer. I've never used workflows and don't know the code. 

BC is not important in Core-2.0 but I'd rather not have a big jump between where we are and Core-2.0. This means implementing all changes in a BC way where possible (like Symfony did with 2.8 -> 3.0). Breaking changes should be introduced and documented ASAP and old code deprecated but left functional until scheduled removal.

**Comment by Guite** [comment]
Notes:
http://zetacomponents.org/documentation/trunk/Workflow/tutorial.html
http://knpbundles.com/yuriteixeira/WorkflowBundle

**Comment by Guite** [comment]
https://www.symfony.fi/entry/a-workflow-component-with-framework-integration-coming-in-symfony-3-2

**Comment by Guite** [comment]
http://symfony.com/blog/new-in-symfony-3-2-workflow-component

**Comment by craigh** [comment]
ping @Guite any chance you could work on this before 1.4.6?

**Comment by Guite** [comment]
no

**Comment by craigh** [comment]
https://github.com/fduch/workflow-bundle

**Comment by robbrandt** [comment]
As described in https://symfony.com/doc/master/components/workflow.html, it appears that "places" = "statuses" and "transitions" = "actions".  It seems this could completely replace the Zikula workflow engine while leaving the UI in place.  Old workflows could still work.

Maybe I lack imagination but I like the current workflow system the way it is, from a user point of view.  The only thing that would be nicer would be a UI to create the XML in administration.
