### ISSUE TITLE
[upgrade] Tests

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2427]
Hi, so I have tested latest github localhost and build 563 on external server.
It seems that lang issue is still there. I think it should completely reset lang to eng if default is not present in system during upgrade and leave it like that until lang will be installed.
I think theme is acting same after upgrade it is going back to what it was before.

Both upgrade and install do install 3party modules and this is breaking using cli as some things are not loaded or not in chain. Web install/upgrade in this case is working.

I will continue with all the test and will let you know more. I have broken few things and now need to fix it :)

**Comment by craigh** [comment]
> Both upgrade and install do install 3party modules and this is breaking using cli as some things are not loaded or not in chain. Web install/upgrade in this case is working.

this is documented. remove the modules from `/modules` and they won't upgrade.

> It seems that lang issue is still there.

which issue?

> I think theme is acting same after upgrade it is going back to what it was before.

I don't understand what you mean.

**Comment by craigh** [comment]
please add a more descriptive title to the ticket

**Comment by Kaik** [comment]
Hi, I needed to change my upgrade setup so now I have 2 upgrade installations current git no third party modules.
The upgrade process is.
1. refresh database
2. remove content of cache folder.
3. remove config dynamic generated
4. remove router request context form custom_parameters
5. sometimes remove routing js file from web if present.
Now I'm using daily snapshot of live db without any adjustments to the lang or theme.
Using cli it one succeed and one failed with 
```
PHP Fatal error:  Call to a member function setAttribute() on null in /home/Kaik/public_html/up_ml/src/system/Zikula/Module/CategoriesModule/CategoriesModuleInstaller.php on line 771
                                        
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Error: Call to a member function setAttribute() on null  
                                                           

```
This might be related to third party module that has doctrine category table, it's files are not present during upgrade but it might be somehow related I will look on this.

Now for the one that succeed using cli and prod env, when home page is viewed gives blank page. While on dev it shows that it cannot calculate theme name - changing theme in phpmyadmin everything works. So it looks like it is not changing theme. 

I will do more tests I'm upgrading few times every day. I need to upgrade 2 community sites and for both I have setup for upgrade and second setup to do all the modules themes and stuff I'm doing.

**Comment by craigh** [comment]
what version of zikula are you upgrading from?
can I get a copy of the DBs?

**Comment by Kaik** [comment]
The one with categories error is 1.3.5 (I think I have send you this db some time ago)
This categories error occurred with latest build as I newer experienced this error before.
I will look more into it by the weekend.
The one that gets upgraded is 1.3.4

**Comment by craigh** [comment]
please update this.

**Comment by Kaik** [comment]
I will close it for now. When next RC will show up I will do all the tests again.
