### ISSUE TITLE
Migrate Andreas08 to Bootstrap

### ISSUE THREAD

**Issue by Guite** [zikula/core#2428]
The following description mentions fluid960gs which has been replaced by Bootstrap:

https://github.com/zikula/core/blob/1.4/src/themes/Zikula/Theme/Andreas08Theme/Andreas08ThemeVersion.php#L11

**Comment by shefik** [comment]
@Guite But, that particular theme is still using fluid960gs. The theme itself is not based on Bootstrap.  For now, the "description" is still valid. Take a look at this file, which links to the fluid960gs files:

/themes/Zikula/Theme/Andreas08Theme/Resources/views/includes/header.tpl

So, the task should be to convert the theme to Bootstrap (or replace the theme entirely with a newer, modern, and responsive theme that uses Bootstrap).

**Comment by Guite** [comment]
@shefik Thanks for the feedback. I will update the task accordingly.

**Comment by pabloveintimilla** [comment]
Hi,

SB Admin project https://github.com/almasaeed2010/AdminLTE, is a opensource admin theme for bootstrap. If you are thinking a newer theme i recommend this.

Regrads!
