### ISSUE TITLE
Theme Cache is Not Working

### ISSUE THREAD

**Issue by shefik** [zikula/core#2437]
When you enable "theme" cache, it is not working. To test, insert this code into any theme template

```
{$smarty.now}
```

The output will be something such as `1430885316`. Subsequent page views will output a different integer every time, instead of the expected cached result.

**Comment by shefik** [comment]
After further testing, it looks like the problem only occurs on the home page, where theme caching is not working.

When there aren't any modules to exclude in the var `ModUtil::getVar('ZikulaThemeModule', 'modulesnocache')`, it returns an empty string, which is then converted to an array with a single empty item. If a site's home page is configured to not load a specific module, then the start module is empty. As a result, the caching thinks to exclude the home page, since both values match as being empty.

I'm working on a fix for this issue.

**Comment by shefik** [comment]
The fix is at pull request https://github.com/zikula/core/pull/2438.

**Comment by craigh** [comment]
closed by #2438
