### ISSUE TITLE
New Theme Version Not Detected

### ISSUE THREAD

**Issue by shefik** [zikula/core#2440]
When a new version of a theme is uploaded to a site, it is not being detected as being a new version by the core, even though the version number is incremented at the file `ExampleThemeVersion.php`.

**Comment by craigh** [comment]
Themes have versions? I've never paid attention to this. What difference does a version make? There are no upgrade routines, etc, right?

**Comment by shefik** [comment]
Themes do have versions, and they need to be there for proper tracking of code (at the very least), if third-party themes are installed.

The theme version is listed at the credits page, such as

```/themes/admin/credits/ZikulaAndreas08Theme```

**Comment by craigh** [comment]
sure, ok. but what do you mean:

> it is not being detected as being a new version by the core

and what difference does it make?

**Comment by shefik** [comment]
If I installed a new version of a theme, I would expect the new version number to be displayed (not remain at the old version number). Otherwise, site admins won't know that new code has been deployed. The assumption shouldn't be that a site admin is also the same person who deployed the code.

**Comment by craigh** [comment]
> I would expect the new version number to be displayed

where is this displayed?

so this isn't affecting the new functionality, only the display of the version?

**Comment by shefik** [comment]
Yes, only the display of the version.

The path is each theme's credits page, such as `/themes/admin/credits/ZikulaAndreas08Theme`

**Comment by craigh** [comment]
oh - sorry, I didn't actually *read* the location in your previous post... :smile: 

Seems like the theme metadata must be reloaded from the filesystem to the DB when viewing the credits page.

**Comment by craigh** [comment]
ping @shefik please test this again.

**Comment by Guite** [comment]
@shefik does this work now like you expected?
