### ISSUE TITLE
Routes Not Reloading for a Single Module

### ISSUE THREAD

**Issue by shefik** [zikula/core#2444]
When just selecting a single module to reload routes (instead of selecting all modules), that particular module's routes do not get updated. The only way to update is by selecting all modules.

`/routes/routes/view?lct=admin`

ping @cmfcmf

**Comment by craigh** [comment]
This works fine for me. I've literally been using it over and over for the last week+

**Comment by shefik** [comment]
I'm testing it locally. I have a module that is already installed. In its controller, the method for the function is set to `@Method("GET")`. Then, I change it to `@Method({"GET", "POST"})`. Then, I go to reload the routes for that particular module. It remains as just `GET`.

**Comment by craigh** [comment]
well, that's fair, I've not tested anything like that, only changing route names and requirements, etc. @cmfcmf maybe the reload function must be updated.
