### ISSUE TITLE
Override a Controller Class

### ISSUE THREAD

**Issue by shefik** [zikula/core#2448]
Previously, I was able to use the event `module_dispatch.custom_classname` to override a Controller class. Now, when using a module converted to Symfony routes, `module_dispatch.custom_classname` does not appear seem to be called anymore for the Controller. It is only being called for the Api (for the `getLinks` function).

Which event can be used instead?

**Comment by craigh** [comment]
check out

http://symfony.com/doc/current/cookbook/bundles/override.html
http://symfony.com/doc/current/cookbook/bundles/inheritance.html

**Comment by shefik** [comment]
@craigh Zikula modules uses non-service controllers, right? So, these docs won't be applicable:

http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration

**Comment by shefik** [comment]
Per the docs here:

http://symfony.com/doc/current/cookbook/bundles/inheritance.html

The sample code says `Start by registering the FOSUserBundle as the "parent" of your bundle`

```
public function getParent()
    {
        return 'FOSUserBundle';
    }
```

So, I tested by by adding the function `getParent()` to a module's controller class. However, `getParent()` doesn't get called by the module. So, some other method is needed.

**Comment by shefik** [comment]
Looks like the `getParent()` needs to be set in this file to get called - `/lib/Zikula/Core/AbstractBundle.php`.

**Comment by craigh** [comment]
I'm removing the BCBreak from this because old methods still work as they did before. it is only when using new technologies are there problems, so IMO this is not a BC Break.

**Comment by craigh** [comment]
closing. If an extension author wishes, they can use the `setParent()` method in their bundle class.
