### ISSUE TITLE
[JavaScript] Date manipulation library

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2451]
Hi, have you considered date manipulation library for javascript. I have tried to play with plain date object but, apparently this is waste of time, so now I'm going to try momentjs https://github.com/moment/moment/

**Comment by craigh** [comment]
I've read good things about MomentJs but this cannot be added until 2.0.0

**Comment by cmfcmf** [comment]
:+1:

**Comment by shefik** [comment]
+1

**Comment by pabloveintimilla** [comment]
+1

**Comment by craigh** [comment]
we do not plan to include this in the core
