### ISSUE TITLE
Using the "moduleheader" plugin when render cache is enabled

### ISSUE THREAD

**Issue by shefik** [zikula/core#2452]
Using the `moduleheader` plugin is not compatible when a module's render cache is enabled.

Example code:

```
{module header modname=$module type=$type title=$templatetitle setpagetitle=true insertstatusmsg=true}
```

The output of the plugin is being cached, which means the module links are being cached (and not respecting permissions). Also, the status message is being cached also, and being persistently displayed.

**Comment by craigh** [comment]
can you look into a solution? caching is voodoo to me.

**Comment by Guite** [comment]
Postponed to 1.4.1

**Comment by craigh** [comment]
marking this as won't fix. Solution/workaround is to use new Twig solutions.

**Comment by craigh** [comment]
refs #2793
