### ISSUE TITLE
[Translations][Theme] Custom theme - translations not working.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2457]
Hi I have created custom theme basing on Andreas08 and Bootstrap extending AbstractTheme while mentioned core themes extend AbstractCoreTheme 
In Smarty using {gt text="Custom string"} it is not translating it, of course only custom strings in themename/Resources/locale...  Common Zikula strings like "Default" "Contact" are translated.
Could you please let me know if you are experiencing same issue.

**Comment by craigh** [comment]
what core version?

**Comment by Kaik** [comment]
1.4

**Comment by Kaik** [comment]
Looks like I have old core pull and it is already fixed. https://github.com/zikula/core/commit/92b65a3f164e62a14a4e135644794e220f72502f
closing
