### ISSUE TITLE
Move Routes to correct location

### ISSUE THREAD

**Issue by Guite** [zikula/core#2458]
Routes is placed in `system/ZikulaRoutesModule` whereas it should be in `system/Zikula/RoutesModule`, because PSR-4 is used.

https://github.com/zikula/core/blob/1.4/src/system/ZikulaRoutesModule/composer.json#L16
https://github.com/zikula/core/blob/1.4/src/system/ZikulaRoutesModule/composer.json#L25

cc @cmfcmf

**Comment by craigh** [comment]
I don't understand this. It works where it is, right? I would rather avoid the entire `/system` contents being in `/system/Zikula` (eventually).

**Comment by Guite** [comment]
Moved to 2.0.0 to be reviewed with regards to #2424

**Comment by craigh** [comment]
according to the [psr-4 spec](http://www.php-fig.org/psr/psr-4/) the 'prefix' (autoload) has no relation to the base directory. See the examples at the end. With respect, I believe you are in error; the module is in an acceptable location.

**Comment by Guite** [comment]
Okay...
