### ISSUE TITLE
Theme translations not working when using new controller in legacy mode.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2459]
Hi, this issue occurs when using AbstractController in legacy mode so BreakIt Pages etc. Theme(smarty) translations are not working while they are working on home page (no start module).

**Comment by Kaik** [comment]
It seems that ZLanguage use FormUtill do get requested lang (aka locale) for new controller route url this is not set from request 
https://github.com/zikula/core/blob/1.4/src/lib/i18n/ZLanguage.php#L159
I was able to get it work like this
```
$lang = strtolower($parameters['_locale']);
$request->query->set('lang', $lang);
self::queryStringSetVar('lang', $lang);
```
https://github.com/zikula/core/blob/1.4/src/lib/util/System.php#L731

This turns on old smarty theme translations using new controller

**Comment by craigh** [comment]
https://github.com/zikula/core/pull/2461 is merged. closing this.
