### ISSUE TITLE
A new theme is not detected (documentation?)

### ISSUE THREAD

**Issue by rallek** [zikula/core#2463]
similar to #2440 I run in a problem a new theme will not be detected. This might be not a core problem, might be a lack of documentation. 

The only documentation I found is in https://github.com/zikula/core/blob/1.4/src/docs/en/dev/UPGRADE-1.4.0.md

I copied the bootstrap theme in a folder theme/Rallek/Theme and renamed the folder BoostrapTheme in RolloTheme. So my path is now ``themes/Rallek/Theme/RolloTheme``

composer.json file is as follows:
````
{
    "name": "zikula/rollo-theme",
    "description": "RolloTheme",
    "type": "zikula-theme",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Ralf",
            "homepage": "http://mysite.de/"
        }
    ],
    "autoload": {
        "psr-0": { "Rollo\\Theme\\RolloTheme\\": "" }
    },
    "require": {
        "php": ">5.3.3"
    },
    "extra": {
        "zikula" : {
            "class": "Rallek\\Theme\\RolloTheme\\ZikulaRolloTheme"
        }
    }
}
````
RolloThemeVersion.php I changed as follows:
````
<?php

namespace Rallek\Theme\RolloTheme;

class RolloThemeVersion extends \Zikula_AbstractThemeVersion
{
    public function getMetaData()
    {
        $meta = array(
            'displayname' => $this->__('Rollo'),
            'description' => $this->__("A theme for mysite.de"),
            'version'     => '0.0.1',
            'admin'       => 1,
            'user'        => 1,
            'system'      => 0,
        );

        return $meta;
    }
}

````
And ZikulaRolloTheme.php
````
<?php

namespace Rallek\Theme\RolloTheme;

use Zikula\Bundle\CoreBundle\Bundle\AbstractCoreTheme;

class ZikulaRolloTheme extends AbstractCoreTheme
{
}
````
All the rest is the same than the bootsrap theme of the latest build. I first want to see the theme before changing anything ;-)

I run ci build 568 (2nd of May) because actual build I can not install.

**Comment by Kaik** [comment]
Hi, try this and place theme in /themes/rallek/rollo-theme/
```
{
    "name": "rallek/rollo-theme",
    "description": "RolloTheme",
    "type": "zikula-theme",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Ralf",
            "homepage": "http://mysite.de/"
        }
    ],
    "autoload": {
        "psr-4": { "Rallek\\RolloTheme\\": "" }
    },
    "require": {
        "php": ">5.3.3"
    },
    "extra": {
        "zikula" : {
            "class": "Rallek\\RolloTheme\\RallekRolloTheme"
        }
    }
}
```

```
<?php

namespace Rallek\RolloTheme;

class RolloThemeVersion extends \Zikula_AbstractThemeVersion
{
    public function getMetaData()
    {
        $meta = array(
            'displayname' => $this->__('Rollo'),
            'description' => $this->__("A theme for mysite.de"),
            'version'     => '0.0.1',
            'admin'       => 1,
            'user'        => 1,
            'system'      => 0,
        );

        return $meta;
    }
}
```
 RallekRolloTheme.php
```
<?php

namespace Rallek\RolloTheme;

use Zikula\Bundle\CoreBundle\Bundle\AbstractCoreTheme;

class RallekRolloTheme extends AbstractCoreTheme
{
}

```

**Comment by rallek** [comment]
it do not change anything.

I have no idea what I am doing here :-( 

Documentation would be really helpfull. If there is someone who is explaning/teaching me I will write the docu.

**Comment by Kaik** [comment]
This is not #2440 and not routing problem. Core theme use AbstractCoreTheme class while custom theme should use AbstractTheme this is important because it will affect translations so this is first thing that should be documented. Second thing is that you mixed zikula core vendor with Rallek vendor and last thing is that PSR-0 is deprecated and we should use PSR-4.

So let me make you a template for new theme
vandor -  can be company name your nick etc
themename - anything you want
This is basic thing to do for new theme so it will show up in theme list 

Path
``` /themes/vendor/themename-theme/ ```

composer.json
```
{
    "name": "vendor/themename-theme",
    "description": "Whatever",
    "type": "zikula-theme",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Name",
            "homepage": "http://mysite.de/"
        }
    ],
    "autoload": {
        "psr-4": { "Vendor\\ThemenameTheme\\": "" }
    },
    "require": {
        "php": ">5.3.3"
    },
    "extra": {
        "zikula" : {
            "class": "Vendor\\ThemenameTheme\\VendorThemenameTheme"
        }
    }
}
```

```
<?php

namespace Vendor\ThemenameTheme;

class ThemenameThemeVersion extends \Zikula_AbstractThemeVersion
{
    public function getMetaData()
    {
        $meta = array(
            'displayname' => $this->__('Themename'),
            'description' => $this->__("A theme for mysite.de"),
            'version'     => '0.0.1',
            'admin'       => 1,
            'user'        => 1,
            'system'      => 0,
        );

        return $meta;
    }
}
```
VendorThemenameTheme.php
````
<?php

namespace Vendor\ThemenameTheme;

use Zikula\Core\AbstractTheme;
class VendorThemenameTheme extends AbstractTheme 
{
}
```

**Comment by rallek** [comment]
mmh, something is still wrong. I get the following error message:
````
Fatal error: Class 'Rallek\RolloTheme\AbstractTheme' not found in /www/htdocs/w012c698/neu.indaus.de/Zikula_Core-1.4.0/themes/Rallek/rollo-theme/RallekRolloTheme.php on line 8
````

I tried following:
in composer.json I changed ``"name": "vendor/themename-theme",`` to ``"name": "vendor/ThemenameTheme",``

and

the folder name from ``themename-theme`` to ``ThemenameTheme``

**Comment by Kaik** [comment]
Two places are wrong composer.json name should be lowercase and should be vendor/themename-theme so rallek/rollo-theme . Themename is really rollo not rollotheme! vendor is rallek not zikula!
Second place RallekRolloTheme.php use should be ```use Zikula\Core\AbstractTheme;``` rest is fine.

**Comment by rallek** [comment]
Yes! It works! Thanks!

After creating my complete theme I will try to make a documentation out of it.

**Comment by rallek** [comment]
one more thing: Now I get a notice:
````
Notice: Undefined index: themename in /www/htdocs/w012c698/neu.indaus.de/Zikula_Core-1.4.0/app/cache/prod/ztemp/view_compiled/Zikula/Module/ThemeModule/moduleheader--t_Rallek/rollo-theme-l_en.php on line 15
````

Do I have to worry about that?

**Comment by Kaik** [comment]
You need to check all your templates because you have copied them from somewhere.
