### ISSUE TITLE
Unable to generate a URL for the named route

### ISSUE THREAD

**Issue by shefik** [zikula/core#2470]
When a module is done installing, it always redirects to "/routes/routes/reload", and displays the message "Unable to generate a URL for the named route...as such route does not exist," when I have a route to the module coded within my theme template. Note that the problem occurs when I have a module’s route coded in a theme template, not when accessing the module page directly.

**Comment by craigh** [comment]
not sure this is a core issue. can you show the offending code please?

**Comment by Guite** [comment]
Maybe the reload redirect should not be done for routes which are called from templates.

**Comment by craigh** [comment]
what theme are you using when this occurs?

If core theme, try disabling the `{adminpanelmenu}` in the theme header and see if that solves it.

**Comment by craigh** [comment]
ping @shefik please respond.

**Comment by shefik** [comment]
It's not a core theme.

`Note that the problem occurs when I have a module’s route coded in a theme template, not when accessing the module page directly.`

**Comment by craigh** [comment]
> It's not a core theme.

are you using the `{adminpanelmenu}` in your theme? If so, please disable it and see if the problem continues.

**Comment by craigh** [comment]
@shefik I modified the exception handler. This may have solved this problem. please let me know if it does.

**Comment by craigh** [comment]
closing. please reopen if you can reproduce the behavior.
