### ISSUE TITLE
_ZINSTALLVER is Not Defined

### ISSUE THREAD

**Issue by shefik** [zikula/core#2471]
When installing via the web interface, `_ZINSTALLVER` is not defined.

`define('_ZINSTALLVER', \Zikula_Core::VERSION_NUM);`

It is only defined when using the CLI.

Line 116 of this file:

`/lib/Zikula/Bundle/CoreInstallerBundle/Command/AbstractCoreInstallerCommand.php`

**Comment by craigh** [comment]
Is it causing a problem?

**Comment by shefik** [comment]
No, it's not necessarily causing a problem with the core. However, I was attempting to use _ZINSTALLER in a listener, to check if Zikula is being installed. I think it was working correctly in Zikula 1.3.x. However, when the new installer was coded, it was removed. So, it might be a BC break for some developers?

**Comment by craigh** [comment]
`\Zikula_Core` is deprecated

**Comment by craigh** [comment]
maybe use `System::isInstalling()` ?

**Comment by shefik** [comment]
It's still being defined in the installer command though (but not in the installer web interface). So, it should be removed from the command too for consistency.

**Comment by craigh** [comment]
yes, I know. When I was coding the installer, my brain got tangled around all that type of stuff and I lost my way. I think if it is removed, it causes problems so I gave up trying.

**Comment by shefik** [comment]
Thanks for the suggestion, but `System::isInstalling()` is not sufficient. However, `ServiceUtil::getManager()->getParameter('installed')` is more suitable to check if the system is installed already.

**Comment by craigh** [comment]
I believe `ServiceUtil::getManager()` is also deprecated, but if you have access to the `Container` that would be the same
