### ISSUE TITLE
[Routing][Smarty] route plugin not detecting current language. 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2472]
Links generated by route plugin do not respect current locale and fall back to default site language. 
For example viewing multilingual site in Englilsh with default language Polish gives Polish url /pl instead /en.
This plugin https://github.com/zikula/core/blob/1.4/src/lib/legacy/viewplugins/function.route.php used in smarty templates should decode current lang/locale (from $request/ template vars) and add it to $params['_locale'].

I will do this.

**Comment by craigh** [comment]
I believe this ticket to be in error.

Using BreakIt, I used the translationController to change lang to `/pl`. After doing that all the links on that page now include the `/pl` in the url string. (that page is a twig pages, so all the urls are generated with symfony/twig `{{path()}}`)

Then I proceed through the menu there to the "old Controller" page which is a 1.3-type controller page using smarty. links on this page are generated using `{route}`

![screen shot 2015-06-07 at 6 58 50 am](https://cloud.githubusercontent.com/assets/350048/8023655/b2153bae-0ce2-11e5-986d-3c5ddd4435d5.png)

The links are like so:
 - **Old Controller** -> http://127.0.0.1/core.git/src/pl/breakit/old
 - **Old Controller (unrouted)** -> http://127.0.0.1/core.git/src/index.php?module=breakit&type=user&func=break&lang=pl
 - **New Controller** -> http://127.0.0.1/core.git/src/pl/breakit/new
 - **Form Demo** -> http://127.0.0.1/core.git/src/pl/breakit/form/test
 - **Translations Demo** -> http://127.0.0.1/core.git/src/pl/breakit/translations

```
// /Resources/views/User/break.tpl

<a class="btn btn-default btn-sm btn-block" href="{route name='zikulabreakitmodule_user_index'}" role="button">Old controller</a>
<a class="btn btn-default btn-sm btn-block" href="{modurl modname='BreakIt' type='user' func='break'}" role="button">Old controller (unrouted)</a>
<a class="btn btn-default btn-sm btn-block" href="{route name='zikulabreakitmodule_new_index'}" role="button">New controller</a>
<a class="btn btn-info btn-sm btn-block" href="{route name='zikulabreakitmodule_form_test'}" role="button">Form Demo</a>
<a class="btn btn-warning btn-sm btn-block" href="{route name='zikulabreakitmodule_translations_index'}" role="button">Translations Demo</a>
```

here you can clearly see that the `{route}` plugin is properly generating the url including the lang/locale parameter

**Comment by craigh** [comment]
ping @Kaik
