### ISSUE TITLE
composer no longer installing zikula-modules in /modules

### ISSUE THREAD

**Issue by craigh** [zikula/core#2483]
composer no longer installing zikula-modules (legal/profile/breakit) correctly at least not on `composer update`

Composer version 1.0-dev (e64470c987fdd6bff03b85eed823eb4b865a4152) 2015-05-28 14:52:12

it copies repos to `/vendors` and not `/modules`

**Comment by Guite** [comment]
It still works in Jenkins using a fresh workspace, so `composer install` is not affected.

Closing this one.

**Comment by craigh** [comment]
I'm not sure I agree here. I just downloaded from CI. There is a full copy of both Profile and Legal in the `/vendor/zikula` and another full copy in `/modules/zikula`. This is not correct IMO. The full copy should only be in `/modules/zikula`. (also, there are no assets in `/web/modules`)

**Comment by craigh** [comment]
and `composer update` is what the ticket is about.

**Comment by cmfcmf** [comment]
Probably fixed by https://github.com/RobLoach/component-installer/pull/87/files

**Comment by craigh** [comment]
> Probably fixed by...

if so, then some stuff must be removed from #2486 @Guite

**Comment by Guite** [comment]
Yes, #2486 contains a hacky workaround at the moment. Will remove this after the PR mentioned above works.

**Comment by craigh** [comment]
indeed https://github.com/RobLoach/component-installer/pull/87/files has solved this issue.
@Guite - please update #2486

**Comment by Guite** [comment]
done
