### ISSUE TITLE
Update to Symfony 2.7 LTS

### ISSUE THREAD

**Issue by Guite** [zikula/core#2484]
1.4 should support Symfony 2.7 because it is a LTS release.

**Comment by craigh** [comment]
symfony 2.7 was [released yesterday 30 May 2015](http://symfony.com/blog/symfony-2-7-0-released)

**Comment by craigh** [comment]
[upgrade docs](https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md)

**Comment by craigh** [comment]
closed by #2486
