### ISSUE TITLE
[Users] Registration moderation by country

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2485]
In a 1.3 based site I have I've had a real problem with Dizkus and comment spam from places like Cameroon and Pakistan.  On a previous non-Zikula site I was able to restrict user registrations based on country of origin so I decided to add this to my site.  I would like to submit this to core so that it is supported henceforth.  The gist of the changes are:
- Profile field added that stores the user's IP address at registration
- Field added to User registration settings that allows an administrator to specify by country code which countries to force moderation on ("Countries which should always be moderated" in settings).  Comma delimited list.
- During registration, $reginfo['isapproved'] adds a condition if the registration is originating from a flagged country.

In this way, registrations from a flagged country can still be approved if they look legitimate.

Is it worth submitting for the v1.3.x branch?  I have not even looked at 1.4 yet.

**Comment by craigh** [comment]
> Is it worth submitting for the v1.3.x branch?

PR's are welcome of course, but anything merged to 1.3.9 should be merged to 1.4.0 at the same time, so you would need to write that code as well.

**Comment by Guite** [comment]
Closing as this is out of scope for what default registration workflow support is going to provide.
