### ISSUE TITLE
Languages and Translations in Zikula

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2488]
This regards to how Zikula is handling multilingual features and translations and what we plan for the future.
We can have two points of view:

**User perspective**
- translations creation
- installation - web language installer?
- settings language page  - multilingual administration
- usage - additional translations in templates or multilingual metadata in setting etc...

**Programmer perspective**
- first should be the idea so we implemented gettext
- usage in php twig js etc.. gettext comes with __() notation
- extraction - should be to .pot - portable object template symfony uses wide range but not pot !?
- now here in the middle translators come and use .pot to translate and provide .po .mo - machine object
- at this point in the context of this list we have our .po .mo files in place we have loading functionality that comes with sf but we need to handle languages and languages handling comes with:
  - detecting languages config, db multilingual system status
  - providing settings language page - language administration for users
  - providing multilingual api

Lets go back now to current situation we have already merged "usage" so symfony is translating and extracting still not to .pot file but we can fix it. We all know multilingual settings page etc what we might not know that behind the scene there is ZLanguage singelton doing all the language handling and we use this as Zlanguage for example `ZLanguage::getInstalledLangNames();`etc what we want is to move all the languages handling to or new symfony wise something. Maybe it can be added to our zikula sf translator maybe something else is needed and this ticket is about to discuss that.

I will provide both Zlanguage silngelton and zikula translator dump images so we can have nicer overview.

**Comment by Guite** [comment]
As far as I see this has been largely improved in 1.4.6 (e.g. by the new locale api). Closing. Feel free to reopen if you have any objections about this.
