### ISSUE TITLE
multilang modvar problem

### ISSUE THREAD

**Issue by phaidon** [zikula/core#2492]
the following change break my zikula:

https://github.com/zikula/core/commit/dc0cd631fb935412b47d4f8bfc3f4e22ae65357c

with 
```
self::$modvars['ZConfig'][$item] = isset(self::$modvars['ZConfig'][$item . '_' . $lang]) ? self::$modvars['ZConfig'][$item . '_' . $lang] : self::$modvars['ZConfig'][$item];
```
it works. (I removed the  ```. '_en'``` at the end)

The current code looks for ```sitename_en``` in the modvars table, but i just have ```sitename```

But maybe it is just an update issue i did not do an update for long

**Comment by craigh** [comment]
please reinstall zikula. I believe you are working with an old install. I have no `sitename` var at all.

![screen shot 2015-06-13 at 12 41 03 pm](https://cloud.githubusercontent.com/assets/350048/8145136/7c5a7bf0-11c9-11e5-8a8a-b699141d394e.png)

**Comment by craigh** [comment]
you might try just running the upgrade for the Settings module.

**Comment by craigh** [comment]
see https://github.com/zikula/core/blob/1.4/src/system/Zikula/Module/SettingsModule/SettingsModuleInstaller.php#L166-L181

there should be no `sitename` without a local suffix

**Comment by phaidon** [comment]
thank you i will do that.
