### ISSUE TITLE
Last composer update broke my test website

### ISSUE THREAD

**Issue by phaidon** [zikula/core#2495]
I guess it is because of that:
https://github.com/ezyang/htmlpurifier/commit/04cf6c8739f107277b8610e3322b6efb0c514fa2

Can someone confirm it?

**Comment by craigh** [comment]
that commit is from last January. Zikula has been working fine since then.

'broke' is not enough information. please provide more.

**Comment by phaidon** [comment]
It was commit 7 day ago.

**Comment by craigh** [comment]
> It was commit 7 day ago.

you are right.

so , I updated.

![screen shot 2015-06-14 at 8 01 11 am](https://cloud.githubusercontent.com/assets/350048/8148438/9ff1d5de-126b-11e5-902f-e4b6b2482e2e.png)

and everything still works just fine.

trying deleting entire `cache/dev` and `cache/prod`

**Comment by phaidon** [comment]
that was it.

**Comment by phaidon** [comment]
The problem is again there. After a  composer update I have the problem on an other test environment, too.

Adding "HTMLPurifier": "next/vendor/ezyang/htmlpurifier/library/", to psr-0 in the main composer.json solves the problem.

**Comment by craigh** [comment]
reproduced.

> [1] Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "HTMLPurifier" from the global namespace.
Did you forget a "use" statement?
    at n/a
        in /Applications/MAMP/htdocs/core.git/src/system/Zikula/Module/SecurityCenterModule/Util.php line 149

>    at Zikula\Module\SecurityCenterModule\Util::getpurifier()
        in /Applications/MAMP/htdocs/core.git/src/system/Zikula/Module/SecurityCenterModule/Listener/FilterListener.php line 383

>    at Zikula\Module\SecurityCenterModule\Listener\FilterListener->outputFilter()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

>    at call_user_func:{/Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61}()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

>    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 164

>    at call_user_func:{/Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164}()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 164

>    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 53

>    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php line 167

>    at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
        in /Applications/MAMP/htdocs/core.git/src/lib/legacy/Zikula/EventManager.php line 99

>    at Zikula_EventManager->dispatch()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 124

>    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
        in /Applications/MAMP/htdocs/core.git/src/lib/util/EventUtil.php line 85

>    at EventUtil::dispatch()
        in /Applications/MAMP/htdocs/core.git/src/lib/util/DataUtil.php line 274

>    at DataUtil::formatForDisplayHTML()
        in /Applications/MAMP/htdocs/core.git/src/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php line 232

>    at Zikula\Bundle\CoreBundle\Twig\Extension\CoreExtension->safeHtml()
        in /Applications/MAMP/htdocs/core.git/src/app/cache/prod/twig/d/6/d627b280567f46508dcc9fb7bf75bcf307b5372c0dd0625505a1800e372f679e.php line 194

>    at __TwigTemplate_d627b280567f46508dcc9fb7bf75bcf307b5372c0dd0625505a1800e372f679e->doDisplay()
        in /Applications/MAMP/htdocs/core.git/src/vendor/twig/twig/lib/Twig/Template.php line 322

>    at Twig_Template->displayWithErrorHandling()
        in /Applications/MAMP/htdocs/core.git/src/vendor/twig/twig/lib/Twig/Template.php line 296

>    at Twig_Template->display()
        in /Applications/MAMP/htdocs/core.git/src/vendor/twig/twig/lib/Twig/Template.php line 307

>    at Twig_Template->render()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 50

>    at Symfony\Bridge\Twig\TwigEngine->render()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 72

>    at Symfony\Bundle\TwigBundle\TwigEngine->render()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 97

>    at Symfony\Bundle\TwigBundle\TwigEngine->renderResponse()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 176

>    at Symfony\Bundle\FrameworkBundle\Controller\Controller->render()
        in /Applications/MAMP/htdocs/core.git/src/lib/Zikula/Core/Controller/AbstractController.php line 96

>    at Zikula\Core\Controller\AbstractController->render()
        in /Applications/MAMP/htdocs/core.git/src/modules/Pages/Controller/UserController.php line 198

>    at Zikula\PagesModule\Controller\UserController->displayAction()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 147

>    at call_user_func_array:{/Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:147}()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 147

>    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 68

>    at Symfony\Component\HttpKernel\HttpKernel->handle()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

>    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 196

>    at Symfony\Component\HttpKernel\Kernel->handle()
        in /Applications/MAMP/htdocs/core.git/src/index.php line 25

>    at {main}()
        in /Applications/MAMP/htdocs/core.git/src/index.php line 0

**Comment by craigh** [comment]
@ezyang has reverted the change in the vendor lib and we are now waiting for packagist to register the change.

**Comment by craigh** [comment]
https://github.com/ezyang/htmlpurifier/commit/bfbf8a9da12131f41ae22b80ccf0e3ca288046a1

**Comment by craigh** [comment]
The vendor has been updated. To fix, you must `composer update` and I also recommend deleting entire `/dev` and/or `/prod` cache
