### ISSUE TITLE
[General] Organization Creds management

### ISSUE THREAD

**Issue by craigh** [zikula/core#2502]
create a way to store and manage access credentials for Zikula servers and services.

https://groups.google.com/forum/#!msg/php-fig/1poTStFu8n4/7NPbdAMS9gEJ

> 1Password vault in a shared Dropbox folder

@Guite 

> you can also use KeePass
> and share it on your own server
> KeePass runs on multiple operation systems and it does not have as much security problems as 1Password

/cc @cmfcmf

**Comment by cmfcmf** [comment]
refs #2147

**Comment by Guite** [comment]
Closing as won't fix. Let's just share stuff on demand.
