### ISSUE TITLE
Consider to introduce the "Git Flow" branching model to the core

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2504]
You can read about it here http://nvie.com/posts/a-successful-git-branching-model/, but the following graphic explained it pretty well:
![git-model 2x](https://cloud.githubusercontent.com/assets/2145092/8268469/503454b0-1787-11e5-9e43-dc70740d1a0f.png)

Our `1.4` branch would be renamed to `develop` and we already use feature branches.

It should ease the process of hotfixes.

**Comment by craigh** [comment]
Here is a video I just watched that makes this idea a little more palatable. http://codesherpas.com/screencasts/on_the_path_gitflow.mov

to be honest, the graphic is a little daunting, but the movie makes this seems a bit more approachable.

**Comment by craigh** [comment]
but....

there are many arguments online about whether this is an appropriate strategy.
http://endoflineblog.com/gitflow-considered-harmful
http://whilefalse.blogspot.com/2013/02/branching-is-easy-so.html
and more...
one obvious point is that symfony does NOT use git flow (at least not on github)

**Comment by cmfcmf** [comment]
Thank you for the arguments! They kind of convinced me to keep doing what we do already, with the addition of using release branches once the release process starts so that new features can be added to the 1.4 branch.

If you people agree to drop the Git Flow idea, we can close the issue.

**Comment by craigh** [comment]
:+1: drop/ignore git-flow
