### ISSUE TITLE
SearchModule index route not set

### ISSUE THREAD

**Issue by craigh** [zikula/core#2506]
neither the `main` nor the `index` controller actions in the **SearchModule** have an assigned route ([ref](https://github.com/zikula/core/blob/1.4/src/system/Zikula/Module/SearchModule/Controller/UserController.php#L35-L54))

This causes auto-generated urls from 'generic' creation ([for example here](https://github.com/zikula/core/blob/1.4/src/system/Zikula/Module/BlocksModule/Block/ExtmenuBlock.php#L191)) to fallback to old style urls like `index.php?module=search&type=user&func=index` which of course forward to the desired route (in this case `/search/`).

This probably can be solved by eliminating 'default' controller routes altogether and utilizing new 'capabilities:user|admin' key instead.
refs #2500 
also generic creation of routes.

This will probably be a `won't fix` because I think it should be solved with the new method, but wanted to document my concern with the 1.4.0 solution for the time being.

/cc @cmfcmf

**Comment by cmfcmf** [comment]
Yeah won't fix, at least for 1.4.0
