### ISSUE TITLE
should we commit a composer.lock file?

### ISSUE THREAD

**Issue by craigh** [zikula/core#2512]
we should discuss the idea of committing a composer.lock file.

http://stackoverflow.com/q/12896780/2600812

**Comment by oldskool** [comment]
You should always include the `composer.lock` file in your repository, so every one working on the project is ensured to have the exact same version of the dependencies. There might be differences in behavior if one dev has version 1.2.0 of a dependency, while another dev has the newer version 1.2.2. This can become very awkward when unit testing or trying to reproduce a problem that may no longer exist with version 1.2.2 of the dependency.

**Comment by Guite** [comment]
:+1: for including it

**Comment by cmfcmf** [comment]
But when do we update it?

**Comment by Guite** [comment]
Maybe something for Jenkins?

**Comment by craigh** [comment]
If the purpose is the ensure package version integrity between developers then Jenkins is not the answer

**Comment by Guite** [comment]
Then I suggest that at every change of `composer.json` also `composer.lock` should be commited.

**Comment by craigh** [comment]
Neither will this ensure the integrity of versions between developers as the composer.json settings are not specific enough.

**Comment by craigh** [comment]
Since our composer settings are typically 'ranges' and not specific versions, this is IMO not useful.
