### ISSUE TITLE
Editing of site modvars not possible

### ISSUE THREAD

**Issue by FRWo** [zikula/core#2522]
Fresh install of 1.3.10 #30 on php 5.6.3 and mysql 5.0.11 on Xampp (local)

Installation is fine but I cannot change the settings for {sitename} or {slogan}

for testing purpose I made a downgrade to 1.3.9 and all works well

**Comment by Portugao** [comment]
Could you test with another php version by using htaccess file?

I cannot reproduce.

**Comment by FRWo** [comment]
I will give it a try tomorrow

**Comment by FRWo** [comment]
I tried it with several php-versions: 5.6.8/5.6.3/5.5.24 but no effects, modvars sitename and slogan still not editable.
So I do a bit of testing and found that, if I use the
system\Settings\templates\settings_admin_modifyconfig.tpl 
from zikula 1.3.9 than all worked as it should, the modvars will be updated.
If I changed to the file from the 1.3.10 version, ther is no updating any more

**Comment by craigh** [comment]
this is likely related to https://github.com/zikula/core/commit/90718177b2b2441e2985139e029e6e82033aacd9 and @nmpetkov  's multilingual changes.

**Comment by craigh** [comment]
@FRWo do you have any locales/translations other than English present?

**Comment by FRWo** [comment]
Yes, I use the german translations from the 1.3.5 package additionally

 

Von: Craig Heydenburg [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2015 14:52
An: zikula/core
Cc: Frank
Betreff: Re: [core] Editing of modvars not possible (#2522)

 

@FRWo <https://github.com/FRWo>  do you have any locales/translations other than English present?

**Comment by craigh** [comment]
@nmpetkov - will you please look into this as soon as possible? We have an RC pending.

**Comment by craigh** [comment]
>  I cannot change the settings for {sitename} or {slogan}

can you explain more what you mean by this?

**Comment by FRWo** [comment]
I go to Adminpage -> Settings and fill in something in the fields for „sitename“ and „slogan“ -> save, Page tell me „Settings had been modified“ but no changes take effect, neither in the header nor in zdebug in the $modvars.ZConfig.sitename or $modvars.ZConfig.slogan

 

Von: Craig Heydenburg [mailto:notifications@github.com] 
Gesendet: Freitag, 3. Juli 2015 12:52
An: zikula/core
Cc: Frank
Betreff: Re: [core] Editing of modvars not possible (#2522)

 

I cannot change the settings for {sitename} or {slogan}

can you explain more what you mean by this?

**Comment by craigh** [comment]
I am unable to reproduce this problem. I installed build 30 in English only and was able to modify the settings in question. Then I deleted the install, added the German translation and installed in German and was still able to modify the settings in question.
![screen shot 2015-07-08 at 2 40 00 pm](https://cloud.githubusercontent.com/assets/350048/8578977/d4348b94-257f-11e5-9703-b1cc790934f4.png)

**Comment by FRWo** [comment]
OK, I figured out:
fresh instal of #30 locale=en => All went well
getting german-master and update locale with de and setting localzation like:
![image](https://cloud.githubusercontent.com/assets/1295226/8589930/c718efc6-261b-11e5-9e93-26a0843f79ad.png)
I get the "supposed" error:
![image](https://cloud.githubusercontent.com/assets/1295226/8589942/efc363b6-261b-11e5-9749-3096c21bc4b3.png)

If I change the language to german or to detect from browser, => the site modvars will be shown correct,   as been set before (here: german/german)

**Comment by craigh** [comment]
> I get the "supposed" error:

I don't see an error. The german/german sitename and slogan only shows if you change the language to German. You have it set as English, so it uses the English settings.

**Comment by FRWo** [comment]
I think, we can close this issue - I was a bit confused about this behaviour, because I don't thougt about the multilungual-settings and that I only had changed the german settings.

After a bit of time, but from me now it's also +1
