### ISSUE TITLE
Failed to upgrade from 1.3.10

### ISSUE THREAD

**Issue by FRWo** [zikula/core#2526]
I tested on windows (xampp) with php 5.6.8:

Fresh install of 1.4.#646 went well, but upgrade from 1.3.10 always ends with:
![image](https://cloud.githubusercontent.com/assets/1295226/8614536/b1ef6678-26ea-11e5-98f4-4005ff329ede.png)

Before start upgrading I was setting app/cache and app/logs writable (and changed the permissions for the user and authenticated user to "All")

**Comment by FRWo** [comment]
I dissabled xcache and restart the webserver => no permission problems anymore
Same error now with locales as #2528 2528

**Comment by craigh** [comment]
are you saying this ticket is therefore invalid?

**Comment by FRWo** [comment]
Yes, I can think, we can close this, because the issue about the language seems to bee the same with php 5.5.24 and 5.6.8
