### ISSUE TITLE
Consider using the bundle for HTMLPurifier

### ISSUE THREAD

**Issue by Guite** [zikula/core#2527]
I do not know how HTMLPurifier is currently installed. Maybe by a transitive composer dependency?

Just saw https://github.com/Exercise/HTMLPurifierBundle though which should be checked and eventually added to 2.0.0.

**Comment by craigh** [comment]
we currently include the HTMLPurifier lib through a dependency of phpids/phpids

https://github.com/PHPIDS/PHPIDS

https://github.com/PHPIDS/PHPIDS/blob/master/composer.json#L13

**Comment by craigh** [comment]
https://github.com/floriansemm/PhpIdsBundle

**Comment by Guite** [comment]
Closing this. I do not see any benefits in switching from our current PHPIDS integration to the PhpIdsBundle - but just work.
Reopen if you disagree.
