### ISSUE TITLE
Upgrading error with default locale

### ISSUE THREAD

**Issue by FRWo** [zikula/core#2528]
Trying upgrade from 1.3.10 on windows with php 5.5.24:

No problems with permissions (see #2526 ) but the default language in DB was set to german, without existing an de - file at locale within the install-package
Error:
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Invalid configuration at path "jms_i18n_routing.default_locale": The default locale must be one of the configured locales.' in C:\xampp5524\htdocs\vendor\jms\i18n-routing-bundle\JMS\I18nRoutingBundle\DependencyInjection\Configuration.php:49 Stack trace: #0 C:\xampp5524\htdocs\vendor\symfony\symfony\src\Symfony\Component\Config\Definition\Builder\ExprBuilder.php(231): JMS\I18nRoutingBundle\DependencyInjection\Configuration->JMS\I18nRoutingBundle\DependencyInjection\{closure}(Array) #1 C:\xampp5524\htdocs\vendor\symfony\symfony\src\Symfony\Component\Config\Definition\BaseNode.php(309): Symfony\Component\Config\Definition\Builder\ExprBuilder::Symfony\Component\Config\Definition\Builder\{closure}(Array) #2 C:\xampp5524\htdocs\vendor\symfony\symfony\src\Symfony\Component\Config\Definition\Processor.php(37): Symfony\Component\Config\Definition\BaseNode->finalize(Array) #3 C:\xampp5524\htdocs\vendor\symfony in C:\xampp5524\htdocs\vendor\jms\i18n-routing-bundle\JMS\I18nRoutingBundle\DependencyInjection\Configuration.php on line 49

**Comment by FRWo** [comment]
changed the default language to english - new DB export for testdb -> doing a fresh upgrade on testsystem:

![image](https://cloud.githubusercontent.com/assets/1295226/8615343/2cd0788a-26f2-11e5-8004-fa2c1b5fe9b6.png)

**Comment by craigh** [comment]
Frank - when you began the upgrade, did you ever select DE or change the parameters file in any way to indicate DE?

**Comment by craigh** [comment]
also - at what point in the upgrade process did it fail and produce the error?

**Comment by craigh** [comment]
I tried to run an upgrade with similar conditions and it failed. I will be back in a while to confirm and work on it.

**Comment by craigh** [comment]
OK - to begin with, the error in the OP is a product of multiple runs of the upgrader. meaning it should not occur if the upgrader runs successfully the first time. The error is dependent on the presence of an `app/config/dynamic/generated.yml` file, which is *not* present on initial placement of the files. Remove that file and the error goes away.

Removal however, doesn't solve the problem which caused the initial failed upgrade. So I am looking into that now.

**Comment by craigh** [comment]
so basically the problem here was that the upgrader was not properly detecting whether the previously selected locale was installed and available.

refs #2418 and https://github.com/zikula/core/commit/b9fd874d2ffc87c2395b3a08f6176708b894cd88

I have a PR in preparation to solve this.

**Comment by craigh** [comment]
@FRWo if you can test the PR I have submitted, I would really appreciate it!

**Comment by FRWo** [comment]
Sure, can it wait until Monday?

The testsystem is at work…

 

Von: Craig Heydenburg [mailto:notifications@github.com] 
Gesendet: Freitag, 10. Juli 2015 15:14
An: zikula/core
Cc: Frank
Betreff: Re: [core] Upgrading error with default locale (#2528)

 

@FRWo <https://github.com/FRWo>  if you can test the PR I have submitted, I would really appreciate it!

**Comment by craigh** [comment]
@FRWo 
> Sure, can it wait until Monday?

It can, but if you can help us out by testing ASAP on Monday it would be very helpful. We are trying to get a final release before Camp Zikula begins on Friday.

**Comment by FRWo** [comment]
OK, ASAP.. ;-)
I took the file from the PR and update the 1.4. zikula.
(fresh) installation -> OK.
Same package, new DB -> localhost/upgrade went to error while regenerating the themes:
![error](https://cloud.githubusercontent.com/assets/1295226/8637921/b236e672-28a9-11e5-85bb-6a8b694cda23.PNG)

**Comment by craigh** [comment]
can you zip up the DB and send it to me? or post it somewhere I can get it?

**Comment by FRWo** [comment]
Sure I try to enclose

Von: Craig Heydenburg [mailto:notifications@github.com] 
Gesendet: Sonntag, 12. Juli 2015 15:53
An: zikula/core
Cc: Frank
Betreff: Re: [core] Upgrading error with default locale (#2528)

 

can you zip up the DB and send it to me? or post it somewhere I can get it?

**Comment by craigh** [comment]
craigh@mac.com

**Comment by craigh** [comment]
@FRWo - please email me the admin creds for the database you emailed.

**Comment by FRWo** [comment]
You have mail

Craig Heydenburg schrieb am 13.07.2015 15:08:

**Comment by craigh** [comment]
:bow:

**Comment by cmfcmf** [comment]
Reopened until the fix is confirmed (by me and once the ci finished, also by @FRWo).

**Comment by cmfcmf** [comment]
Build 649 should fix all the upgrade problems (once the build has finished): http://ci.zikula.org/job/Zikula_Core-1.4.0/649/. I will try to confirm this evening and eventually release RC5 then.

**Comment by FRWo** [comment]
Tested with php 5.524 and 5.68 fresh install and upgrade:

All 4 test was ok -> :+1:

**Comment by cmfcmf** [comment]
Also works for me :-)
