### ISSUE TITLE
Symfony 2.7.2 released today 13 July 2015

### ISSUE THREAD

**Issue by craigh** [zikula/core#2531]
http://symfony.com/blog/symfony-2-7-2-released

It will automatically be included in the next build (because of [composer settings](https://github.com/zikula/core/blob/1.4/composer.json#L45))

with being so close to a release we should maybe discuss forcing 2.7.1 or not.

**Comment by Guite** [comment]
:+1:  for including 2.7.2

**Comment by craigh** [comment]
ping @cmfcmf

**Comment by craigh** [comment]
I am :+1: as well, but a little testing of the build might be in order...

**Comment by cmfcmf** [comment]
👍🏽
