### ISSUE TITLE
Route zikulasearchmodule_user_opensearch not found

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2539]
Sometimes this error occurs during upgrade. It oil seems to occur, when inserting the wrong admin credentials.

**Comment by craigh** [comment]
Maybe better if this route is hardcoded than in the db?

**Comment by cmfcmf** [comment]
It shouldn't be generated in the first place: https://github.com/zikula/core/blob/50fa05831ea2212619ef49a96d2a234ceb0e20d9/src/system/Zikula/Module/SearchModule/Listener/FrontControllerListener.php#L58-L66 I'll see what I can do.

**Comment by craigh** [comment]
I cannot reproduce :-(

I also thing the stated error:

> Route zikulasearchmodule_user_opensearch not found

is only a symptom of another issue that caused this error to later appear.

**Comment by cmfcmf** [comment]
Cannot reproduce this anymore.
