### ISSUE TITLE
Make installer / upgrader error messages more verbose

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2540]
They already pop up in an alert if you install in dev / debug mode.

**Comment by Guite** [comment]
This is about catching any PHP exceptions. Must be done both for CLI as well as Ajax mode.

**Comment by craigh** [comment]
vote we move this to 1.4.5 and accidentally forget about it. 😝

**Comment by rallek** [comment]
just implement #2204 than we are fine ;-)

**Comment by Guite** [comment]
refs #3419

**Comment by Guite** [comment]
Closing this issue, because we now use more reasonable defaults.
Of course there is still the possibility that problems occur, in these cases we need to investigate the causes.
