### ISSUE TITLE
Whitelist translations 

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2541]
Refs https://github.com/zikula-modules/Multisites/issues/17

**Comment by craigh** [comment]
@Guite how important is this? Should we implement this feature or delay to 2.1.0?

**Comment by Guite** [comment]
Can wait until 2.1.0 I think.

**Comment by Guite** [comment]
Closed as duplicate of https://github.com/zikula/core/issues/3781  (which describes more concretely what to do)
