### ISSUE TITLE
Enhance Zikula builds at the Jenkins server

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2544]
Needed preperations:
- [ ] Install Apache (or similar), PHP, Mysql at ci.zikula.org
- [ ] ...

Enhancements:
- [ ] Try to install Zikula (command line)
- [ ] wget some basic pages
- [ ] Install the latest 1.3.x build and upgrade from there
- [ ] ...

**Comment by craigh** [comment]
Some/all of this is now happening in travis instead of Jenkins. Should this be now closed?
