### ISSUE TITLE
[Security] Too open file permissions warning for wrong file

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2548]
Too open file permissions warning is triggered for config.php file while it should be personal_config.php as this file contains actual db credentials. 1.4.0

**Comment by craigh** [comment]
> Too open file permissions warning is triggered

when, where, how?

**Comment by Kaik** [comment]
In admin panel after zikula install there is warning that perms are too open (it used to be on 27 Jul) It warns you about config.php and reacts to its permission while it should be personal_config.php

**Comment by craigh** [comment]
this must be on upgrade? on install, the config.php file is never touched.

**Comment by Guite** [comment]
imo this should be reviewed after #2648 has been completed and merged

**Comment by Kaik** [comment]
I it is removed completely in #2648  https://github.com/Kaik/core/blob/admin_module_twig/src/system/AdminModule/Resources/views/AdminInterface/securityanalyzer.html.twig

**Comment by craigh** [comment]
closing since the new functionality removes this check. It will remain in existing smarty implementation until they are refactored.
