### ISSUE TITLE
Notice: Undefined index: themename... in BoostrapTheme

### ISSUE THREAD

**Issue by rallek** [zikula/core#2557]
````
Notice: Undefined index: themename in /www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/app/cache/prod/ztemp/view_compiled/Zikula/Module/ThemeModule/moduleheader--t_Zikula/Theme/BootstrapTheme-l_de.php on line 15
````
This shows up at several places. I have no idea what I can do to fix this.

I tested the BoostrapTheme of the current 1.4.1dev at a shared hosting enviroinment. All caches are emptied and theme compilation is forced.

**Comment by rallek** [comment]
Can it be a permission thing? Allinkl do have two file owners. One is my ftp-user, in this case I see the number 1583 for the user and 1103 for the group.

But the folder ``moduleheader--t_Zikula`` is owned by user 33 in group 33 and is named PHP-User. The folder is chowned 751 and can't be opend via ftp.

**Comment by rallek** [comment]
I just wanted to countercheck with Andreas08. But switching back gaves me this error message:
    
    Fatal error: Uncaught exception 'InvalidArgumentException' with message '[WARNING 1549] failed to load external entity "file:////www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd" (in n/a - line 0, column 0) [WARNING 3084] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'file:////www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd'. Skipping the import. (in in_memory_buffer - line 8, column 0) [ERROR 1845] Element '{http://symfony.com/schema/dic/services}container': No matching global declaration available for the validation root. (in /www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/ - line 5, column 0)' in /www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:96 Stack trace: #0 /www/htdocs/w0137e in /www/htdocs/w0137ee9/omi.11cv.net/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 259

:-(

**Comment by rallek** [comment]
The fatal error disappeared by doing nothing.

The undefined index is not there if I change to Andreas08.

**Comment by rallek** [comment]
Why the notice is showing up in boostrap theme but not in Andreas08?

Where the themename must be specified?

**Comment by rallek** [comment]
I am comparing Andreas08Theme and BoostrapTheme and can not find any hint where I have to define the themename :-(

@Kaik @phaidon any idea?

**Comment by craigh** [comment]
sounds like https://github.com/zikula/core/issues/2452

**Comment by rallek** [comment]
And why this happens not in Andreas08?

**Comment by rallek** [comment]
The permission posibility is eleminated. My provider teached me to use php in cgi mode. This makes only one file owner available. I did this with 1.4.0 stable and got the same notice.

No caching is enabled. All settings are at standard like delivered with Zikula. Only scribite and news are installed. Bootstrap theme is used from 1.4.0

**Comment by rallek** [comment]
at another hosting company (webgo24) I do not see the notice anymore.

nevertheless there are possibiliteis to get this notice and warnings. As long as the rootcause of this is not found it should be an open ticket.

Again: Andreas08 has no problem Bootrap-Theme do have (but it is based on Andreas08)

**Comment by Portugao** [comment]
I can reproduce this.

**Comment by AlexL777** [comment]
Hello developers and users,
I want to also use the Bootstrap Theme, get but this appears:

    Notice: Undefined index: themename in/www/htdocs/xxxxxx/zikula14.wpzweinull.ch/app/cache/prod/ztemp/view_compiled/Zikula/Module/ThemeModule/moduleheader--t_Zikula/Theme/BootstrapTheme-l_en.php on line 15

I am also at all-inkl, my German web host and have the theme activated. The default theme I have not the problems.

What can I do to eliminate the error? Thank you in advance.

**Comment by craigh** [comment]
fixed.

> And why this happens not in Andreas08?

because BootstrapTheme was using a theme override for the module header.tpl template.
