### ISSUE TITLE
[2.0 FC] Resource Override Problems

### ISSUE THREAD

**Issue by craigh** [zikula/core#2565]
As I am working on implementing the new ThemeEngine and Resource/Asset implementation, I have encountered what I believe to be two very large problems related to overriding resources.

_Terminology Check:_ A resource is a _template, css, js or image_ file that is used in the rendering of content.

### First: Theme overrides due to Response
A decision was made earlier to base full theme overrides (e.g. change to Admin theme, etc) on the Response (e.g. AdminResponse dictates a selected admin theme, etc). This is a problem from a resource override perspective because the fully rendered 'maincontent' is delivered from the module to the theme and _then_ wrapped by the selected theme. This means that the **new** theme cannot override module resources at this point (though the _original_ may have already done so). I suppose a filter could be written to scrape the html and modify some asset content but I don't think this a good idea in terms of rendering speed, and it would be too late to alter templates at that point anyway.

### Second: Override resources are not installed to `/web`
Symfony has a built in override mechanism. You place resources in the `app/Resources/<BundleName>` directory and they will be used in place of `<BundleName>/Resources`. This works well and since it is built in, it makes sense to utilize it. Symfony mentions this specifically in *template* override contexts, but other assets can be placed in `app/Resources` and it works as expected. This is all fine except that these assets are **never copied to the `/web` directory**. This of course is the _preferred_ behavior for templates, but not for other assets.

So what's the problem? Well, if the ultimate goal is to make only the `/web` directory visible/public then these other assets must be copied there, no? Apparently Symfony doesn't think so either because despite non-template assets _working_ from this directory, they are not copied.

Additionally, if we use the same directory structure when implementing **Theme** overrides, then we have the exact same problem. The assets are not copied to `/web` (`app/console assets:install` only copies the contents of the `/public` directory, not the entire `/Resources` directory.)

    ZikulaSpecTheme/
      Resources/
        public/ <-- copied to /web/themes/zikulaspec/
          css/
          js/
          images/
        views/
        ZikulaSpecModule/ <-- entire directory not copied to /web
          views/
            override_template.html.twig
          public/
            css/
              override_stylesheet.css

So - in conclusion, I'm not sure how to proceed here. As a side note, I am beginning to question the need for the **CustomBundle** because everything that is needed from a _Resources_ perspective is covered using the `app/Resources` directory. But perhaps the Custom bundle is used for overriding PHP files (Controllers, etc). I am not certain.

I welcome your thoughts and suggestions. @Kaik @phaidon @cmfcmf @shefik @Guite && everyone else!

**Comment by craigh** [comment]
@Guite summarized a slack discussion with me about this subject:

> Deciding about full theme overrides (e.g. change to Admin theme, etc) based on the Response (PrintableResponse, RssResponse, ...) leads to a chicken-and-egg problem. We need to know the overrides before processing the module, but get the response after the module is processed.

> Our basic idea was to let modules tell the core their preferred/expected response type (read theme) before the actual processing.
Craig suggested we could create an annotation (e.g. @Admin) that would be detected and maybe a flag added to the route params or something. For example MOST modules could then remove the lct parameter and use something like this instead in the entity controllers:

```php
class PersonController {
      @Route // (... responseType='admin')
      // or simply @Admin
      public function adminViewAction()

      public function userViewAction()

      // sharing common stuff
      protected function commonViewStuff($isAdmin)
}
```

> Please tell us your opinion and additional thoughts about this approach. Do you have another idea (the only other alternative which came to my mind was separating overrides from themes, but this does not seem reasonable, because overriding/inheriting Twig blocks is a much more powerful tool for site customisation than having css stylesheets only)?

> Also there are some edge cases to consider which need to be handled by the core: important is for example that only the *main module* (which owns the controller primarily called) is responsible for the decision and not another module which is only called by an event listener or something. (edited)

Craig Heydenburg
> can you give a use case for your last scenario?

Axel Guckelsberger
> for example: controller of module A performing a sub request calling controller of module B
not very common, but possible
or a template calling a controller

**Comment by craigh** [comment]
refs https://github.com/zikula/core/pull/2569

@Guite @cmfcmf 

the logical extension of this of course is other annotations, e.g. `@Printable`, `@Rss`, etc. This would be relatively easy to implement I think.

Another way to accomplish the same idea would be to use only one annotation and several values like `@Theme('admin')` `@Theme('print')` `@Theme('rss')`

I think I prefer the first since it is simpler to read. But I could be convinced either way.

**Comment by Guite** [comment]
I could live with both variations. Some thoughts:

- `@Theme('something')` seems easier to learn?
- `@Printable` and others include the advantage that they could involve other implications than selecting a theme only.

**Comment by craigh** [comment]
another advantage of the annotation method over the Response method is that you can further simplify controllers (if desired)

see: https://github.com/zikula/SpecModule/commit/51858949ae12715e90c7867a44e502314c668834

**Comment by cmfcmf** [comment]
I agree, using annotations like `@Admin` seems the best, however I would postfix them all by `@XTheme` to avoid confusion with future custom annotations.

**Comment by craigh** [comment]
if the "Theme" word is important, then I think `@Theme('admin')` seems like a better choice. The problem then becomes that we would use "aliases" for the themes, 'admin' not 'ZikulaAdminTheme'. But I suppose we could allow both formal theme names and aliases for certain types - 'admin' being the obvious one since the admin theme is set via UI. but if the value is a formal theme (bundle) name then it could be used like `@Theme('ZikulaAndreas08Theme')` thoughts?
