### ISSUE TITLE
Replace typeahead plugin by original library

### ISSUE THREAD

**Issue by Guite** [zikula/core#2566]
Currently we include https://github.com/bassjobsen/Bootstrap-3-Typeahead for bootstrap compability. During the camp I discussed with @phaidon that now it would be much better to include the original https://github.com/twitter/typeahead.js/ instead which works with bootstrap now, too.

Advantages:
* includes Bloodhound
* does not have the problem becoming outdated
* more actively maintained

**Comment by craigh** [comment]
thanks!
