### ISSUE TITLE
Upgrade to Twig 2.0

### ISSUE THREAD

**Issue by craigh** [zikula/core#2567]
So far unreleased yet, but will certainly be so by the time Core 2.0 is released.

here is an article about upgrading: http://symfony.com/blog/twig-how-to-upgrade-to-2-0-deprecation-notices-to-the-rescue

note: Twig 2 [requires php >= 5.5.0](http://symfony.com/blog/twig-how-to-upgrade-to-2-0-deprecation-notices-to-the-rescue#comment-19972)

**Comment by Guite** [comment]
Closed in favour of #3370

**Comment by craigh** [comment]
> note: Twig 2 requires php >= 5.5.0

apparently this was changed :-(
