### ISSUE TITLE
Theme-related exception when calling the installer

### ISSUE THREAD

**Issue by Guite** [zikula/core#2572]
The following exception appears when trying to do a new install:

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Theme "" does not exist or it is not enabled.' in /zikula/src/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php:155 
Stack trace:
#0 /zikula/src/lib/Zikula/Core/Theme/Engine.php(295): Zikula\Bundle\CoreBundle\HttpKernel\ZikulaKernel->getTheme(NULL)
#1 /zikula/src/lib/Zikula/Core/Theme/Engine.php(106): Zikula\Core\Theme\Engine->setActiveTheme(NULL, Object(Zikula_Request_Http))
#2 /zikula/src/lib/Zikula/Core/Theme/Engine.php(95): Zikula\Core\Theme\Engine->setRequestAttributes(Object(Zikula_Request_Http))

Bypassed this by changing line 295 of `lib/Zikula/Core/Theme/Engine.php` to:
```
        if ($activeTheme !== null) {
            $this->activeThemeBundle = $this->kernel->getTheme($activeTheme);
        }
```

**Comment by craigh** [comment]
I'm not certain that is the right solution. The $active theme shouldn't be `null` because it should pull the default theme from the System Vars.

```php
        $activeTheme = !empty($newThemeName) ? $newThemeName : \System::getVar('Default_Theme');
```

**Comment by craigh** [comment]
maybe the problem is that the value isn't set yet in the install process. maybe simply setting a core theme as the default default is the better answer? e.g.

```php
$activeTheme = !empty($newThemeName) ? $newThemeName : \System::getVar('Default_Theme', 'ZikulaAndreas08Theme');
```

**Comment by craigh** [comment]
or maybe not call the method in the Engine constructor if we are installing

```php
if ((null !== $requestStack->getCurrentRequest()) || \System::isInstalling()) {
    $this->setRequestAttributes($requestStack->getCurrentRequest());
}
```
