### ISSUE TITLE
Routing problem caused by speed improvement

### ISSUE THREAD

**Issue by Guite** [zikula/core#2593]
I got the following error when calling `/mymodule/fooBar/view?lct=admin`:
```
The _controller value "GuiteMyModule:Foobar:View" maps to a "Guite\MyModule\Controller\FoobarController" class, but this class was not found. Create this class or check the spelling of the class and its namespace.
```

The class was actually named `FooBarController` (with a capitalised `B`).

Solved by disabling this line:
https://github.com/zikula/core/pull/2519/files#diff-99827764e017f3db015ca76d386760f1R66

**Comment by craigh** [comment]
@cmfcmf please look into this when you are finishing the Routing PR

**Comment by craigh** [comment]
@cmfcmf can you please look into this when reviewing other Routing stuff

**Comment by craigh** [comment]
@Guite - please test this issue again. that code you reference in your comment has been commented out of the current codebase. (see [here](https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Routing/RouteLoader.php#L150-L209))

@cmfcmf  - is there some reason you left that code in place and not simply removed it all?

**Comment by Guite** [comment]
This issue can be closed, since default routes are not loaded from database anymore.

**Comment by craigh** [comment]
:+1:

**Comment by cmfcmf** [comment]
> is there some reason you left that code in place and not simply removed it all?

Well, it's still planned to re-enable loading custom routes from the database.
