### ISSUE TITLE
Refactor DisplayHookResponse so that you don't have to use Smarty

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2600]
Currently, you have to use Smarty:
- https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Core/Hook/DisplayHookResponse.php#L55
- https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Core/Hook/DisplayHookResponse.php#L138

This should be changed to Twig, or even better, to just "strings", so that the response isn't aware of the generation of the response.

**Comment by craigh** [comment]
I fear this will be harder than it may seem in order to maintain BC. we have made to provide two solutions: a BC and FC.

**Comment by craigh** [comment]
note to self: https://github.com/cmfcmf/MediaModule/blob/master/HookHandler/AbstractHookHandler.php#L52-L60

**Comment by Guite** [comment]
Please see my proposal at #2747
