### ISSUE TITLE
Event call in login block dependent from security level

### ISSUE THREAD

**Issue by Guite** [zikula/core#2602]
The condition in https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Resources/views/Block/login.tpl#L36 includes not only the `remember me` option, but also the event calls below. Is this on purpose?

**Comment by cmfcmf** [comment]
I don't really know, but it seems odd.

**Comment by craigh** [comment]
looked int the commits that created it and see that both parts of the code and all the logic, etc was done by the same person (@rmburkhead) and within a 3 month timespan in 2011. So my guess is that it *was* on purpose. The question then becomes if that is the desired behavior.

**Comment by craigh** [comment]
@Guite @cmfcmf what would you like to do here? I always hesitate to play too much with the Users Module because it is so much code and I worry about breaking it. Obviously, eventually, there will need to be a thorough code review and refactoring, but not in the immediate future. thoughts?

**Comment by Guite** [comment]
I think it is a bug and https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Resources/views/Block/login.tpl#L51 should be moved to line 43.

**Comment by craigh** [comment]
please go ahead and take care of it then.
