### ISSUE TITLE
Error message during update to 1.4.0 (ZIKULACORE_CURRENT_INSTALLED_VERSION)

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#2608]
Hey,
I've tried upgrading my ZK 1.3.9 install to 1.4.0 using the Upgrade.md guide.
After prep has been done I've executed the upgrade routine and got an error:

```
[user@server ~/htdocs]$ php app/console zikula:upgrade -vvv
The current installed version of Zikula is reporting (ZIKULACORE_CURRENT_INSTALLED_VERSION). You must upgrade to version (1.3.5) before you can use this upgrade.
```

Seems like the upgrade routine was not able to pull the actual installed version. I do have Zk 1.3.9 installed which I confirmed by checking database module_vars.

I've also tried the same with latest 1.4.1 build from CI, which fails the same way.
Not sure if this is a bug, or database access missconfiguration. I thought the verbose output of the app/console would spit a bit more info, but doesnt.
Is there a way to confirm the console has proper DB access?
Thanks for your help.

**Comment by craigh** [comment]
did you try the web version?

**Comment by MrMontesa** [comment]
Yes, blank page or same error message as console.

**Comment by craigh** [comment]
have you tried a fresh install on the server? does that work?

**Comment by MrMontesa** [comment]
The installer runs and sais: Porperly installed. However on redirecting to the login page at the end I do get the following error:

```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("Empty argument at:/web/1/000/027/915/75642/htdocs/eis-flamme/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php::296") in "ZikulaAndreas08Theme:Include:header.html.twig" at line 9.
```

Then I dived a bit into MySQL and saw that the DB was not on UT8 jet. After that, install works fine.
Let me test my update once more with changing to UTF8. I'll get back to you on that.

**Comment by craigh** [comment]
interesting. I wonder if there is a way for PHP to check the encoding to ensure it is utf8

**Comment by rallek** [comment]
Isn't it similar to #2603 ?

**Comment by craigh** [comment]
> Isn't it similar to #2603 ?

> After that, install works fine.

apparently not. although some similarity. Maybe you should check you DB for the encoding setting...

**Comment by craigh** [comment]
> Let me test my update once more with changing to UTF8. I'll get back to you on that.

@MrMontesa any news?

**Comment by MrMontesa** [comment]
Hey Craigh,
I did some more tests and the behavior is wired. Its not the UTF8 thingy. I confirmed that DB is on UTF before update. Then I ran the upgrade from console again with the same error as above. As a second try, I used the web upgrade, but instead of directly accessing /upgrade, I hit the default domain and got redirected to /upgrade. Then the upgrade process started. It failed at "There was an error regenerating the themes". Then all the subsequent parts also failed.

Then I tried the console updater once more and got a different error message as below:
```
[user@server]$ php app/console zikula:upgrade
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Invalid configuration at path "jms_i18n_routing.default_locale": The default locale must be one of
   the configured locales.
```
Let me know how I can assist in troubleshooting. Both pages (the zk 1.3.9 & the zk 1.4.0) are public available in case you'd like to take a look.
Thanks much

**Comment by craigh** [comment]
what languages do you have installed?

**Comment by craigh** [comment]
when you say "then I tried... then I tried....etc" did you return your DB to pre-upgraded state each time or run one upgrade on top of the other?

**Comment by craigh** [comment]
> As a second try, I used the web upgrade, but instead of directly accessing /upgrade, I hit the default domain and got redirected to /upgrade.

this is correct behavior.

**Comment by craigh** [comment]
Are you using 1.4.0 or a download from github? it is probably best to only use 1.4.0

**Comment by MrMontesa** [comment]
> what languages do you have installed?

Its en & de installed, with defaulting to DE. The new page is EN only, since I'm not sure if the DE is accurate already.

>when you say "then I tried... then I tried....etc" 

I havent reverted to the "pre upgrade" status. It was more a bit of playing around to grab more info.

>Are you using 1.4.0 or a download of a newer development build from github?

I've tested the CI of 1.4.1 which failed as well. So I got back to the official 1.4.0 release which I used for all tests.

**Comment by craigh** [comment]
As far as I know, there is no 1.4.0 DE language pack yet. The upgrader SHOULD switch you to English.

You also must revert your DB back to the original 1.3.x DB before attempting multiple upgrades. Please do so and try again with 1.4.0 and let me know what happens. Please use the web installer.

**Comment by MrMontesa** [comment]
So this is how my test looked like:
```
[user@server ~/htdocs/testbed]$ mysqldump -u 27915m16910_4 -p 27915m16910_4 > ./27915m16910_4.sql
Enter password: 
[user@server ~/htdocs/testbed]$ mysql -u 27915m16910_2 -p 27915m16910_2 < ./27915m16910_4.sql
Enter password: 
[user@server ~/htdocs/testbed_new]$ tar -xvf Zikula_Core-1.4.0.build658.tar 
[user@server ~/htdocs/testbed_new]$ cd Zikula_Core-1.4.0         
[user@server ~/htdocs/testbed_new/Zikula_Core-1.4.0]$ mv * ..
[user@server ~/htdocs/testbed_new/Zikula_Core-1.4.0]$ mv .htaccess ..
[user@server ~/htdocs/testbed_new/Zikula_Core-1.4.0]$ cd ..
[user@server ~/htdocs/testbed_new]$ rm -fr Zikula_Core-1.4.0
[user@server ~/htdocs/testbed_new]$ cp config/config.php config/personal_config.php 
[user@server ~/htdocs/testbed_new]$ cp app/config/parameters.yml app/config/custom_parameters.yml
[user@server ~/htdocs/testbed_new]$ vi config/personal_config.php (adding the MySQL connection & installed =1)
[user@server ~/htdocs/testbed_new]$ chmod 777 app/logs app/cache/
```
Then I accessed the webpage and got redirected to /upgrade and ran through the installer. Everything succeded and the page properly updated. I'm VERY confused now.
The only change In update process I've done is using mysqldump instead of phpmyadmin export/import functionality.

**Comment by craigh** [comment]
well, I'm glad to hear it worked :tada: :smile: 

not sure I have any ideas about your DB tho.
