### ISSUE TITLE
site name and home link are not working properly

### ISSUE THREAD

**Issue by rallek** [zikula/core#2609]
If I am in admin area and want to go back home I click normally on ``home`` or ``site name``. But with ci build 68 in standard theme this is always showing at the current admin site. E.G. ``settings/admin/config``

**Comment by rallek** [comment]
``<title>{{ pagevars.title }}</title>`` seems to be empty- No pagevars are set I guess

**Comment by rallek** [comment]
Has nothing to do with pagevar. I was looking at a wrong place. It is this place:
````
<h1 class="title">{{ adminPanelMenu() }} <a href="{{ app.request.baseUrl }}">{{ getModVar('ZConfig', 'sitename') }}</a></h1>
````
app.request.baseUrl semm to work in a wrong direction or is wrong at this place.

**Comment by rallek** [comment]
changing that line to:
````
<h1 class="title"> <a href="/index.php">{{ getModVar('ZConfig', 'sitename') }}</a></h1>
````
is doing the trick. Is this the right way to do in twig? will that work when Zikula is installed in a sub directory?

**Comment by craigh** [comment]
no this is not correct either. it will work for you at the moment, but is not a long term solution.

**Comment by rallek** [comment]
ok, than I found a bug :-) and wait until it is fixed in the right way by an expert

**Comment by craigh** [comment]
`{{ app.request.baseUrl }}` **should** be correct though. that's the frustration.

try `{{ app.request.getSchemeAndHttpHost() }}`

**Comment by rallek** [comment]
That is working fine. It gives me the URL of the site without ``index.php`` like ``mysite.de`` instead of ``mysite.de/index.php`` as in my (unprofessional) solution

**Comment by craigh** [comment]
`{{ app.request.getSchemeAndHttpHost() }}` doesn't work for me :-(

**Comment by rallek** [comment]
Strange

**Comment by craigh** [comment]
should be fixed by https://github.com/zikula/core/commit/de067619b1b88380162eb9693805a5997884d545

please test and report at your convenience.

**Comment by craigh** [comment]
@rallek ?

**Comment by rallek** [comment]
it is working fine now.
