### ISSUE TITLE
Update to latest DoctrineExtensions

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2612]
https://github.com/zikula/core/blob/1.4/composer.json#L63

Version 2.4.x is out already and includes a particular fix I need for a module.

**Comment by craigh** [comment]
Doctrine ORM could be updated to 2.5.0 in this also. would need to confirm no BC breaks though.

**Comment by craigh** [comment]
Doctrine 2.5.0 + 2.5.1 notes:
- http://www.doctrine-project.org/2015/04/02/orm-2-5-0.html

- http://docs.doctrine-project.org/en/latest/changelog/migration_2_5.html
  - [BC Breaks](http://docs.doctrine-project.org/en/latest/changelog/migration_2_5.html#behavioral-changes-bc-breaks)

- http://www.doctrine-project.org/2015/08/31/doctrine_orm_2_5_1_and_2_4_8_released.html
