### ISSUE TITLE
semver vendor/version

### ISSUE THREAD

**Issue by craigh** [zikula/core#2619]
consider https://packagist.org/packages/composer/semver to replace vierbergenlars/php-semver

php-semver is currently stable and latest version is 3.0.1 (and is currently in core).

https://github.com/composer/semver

**Comment by Guite** [comment]
I've no real opinion here. Looking at the readme files of both projects our current one seems more powerful.

https://github.com/vierbergenlars/php-semver
vs.
https://github.com/composer/semver

Can you elaborate about the reasoning for this discussion? Any special feature or benefit the composer semver is offering? Or do you just think that we should get nearer to composer as we use it for assembling, too?

**Comment by Guite** [comment]
If we require composer itself as part of #3388 / #3437 then composer/semver is included automatically, too. This might be a reason to drop php-semver.

**Comment by Guite** [comment]
Nice one!
