### ISSUE TITLE
managing JS/CSS dependencies

### ISSUE THREAD

**Issue by craigh** [zikula/core#2621]
#1719
#1720

here's a new idea I just found:
https://packagist.org/packages/fxp/composer-asset-plugin

we are no closer to solving this problem and IMO our current solution is the wrong one.

**Comment by Guite** [comment]
Refs #1832 (where you mentioned the same plugin also :-))

**Comment by Guite** [comment]
FYI Piwik uses composer and bower, see https://github.com/piwik/piwik

**Comment by craigh** [comment]
close in favor of #1832
