### ISSUE TITLE
Legacy stylesheet not included

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2625]
https://github.com/zikula/core/blob/master/src/lib/util/JCSSUtil.php#L147-147

The whole function is never executed. Tested with the News module and Bootstrap theme.

**Comment by craigh** [comment]
see [here](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Core/Theme/Engine.php#L344) where javascripts are prepared.

but [here](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Core/Theme/Engine.php#L355) a similar thing is not done (e.g. [JCSS::prepareStylesheets()](https://github.com/zikula/core/blob/1.4/src/lib/util/JCSSUtil.php#L132))

need to look into whether that should be the solution.

**Comment by craigh** [comment]
or maybe only add the legacy.css if needed somehow elsewhere. Is that the only missing piece?

**Comment by cmfcmf** [comment]
It is the only obvious missing piece I discovered.
