### ISSUE TITLE
consider phpStack

### ISSUE THREAD

**Issue by craigh** [zikula/core#2632]
http://stackphp.com may be a method to replace Zikula_Core for Core-2.0

ping @cmfcmf

**Comment by Guite** [comment]
Isn't this a bit overkilling?

**Comment by craigh** [comment]
I think there will be no such thing as Zikula_Core in Core-2.0. Only the ZikulaKernel and it won't need to change much.

**Comment by Guite** [comment]
Closed as won't fix.
