### ISSUE TITLE
[1.3.x] no theme translation

### ISSUE THREAD

**Issue by Portugao** [zikula/core#2635]
It seems that there is an issue with the translation of themes.
If i put the needed language files into the theme folder locale i get no translations.
I tried all possible settings in the multilanguage part, no translations.

Not sure if it is really an issue or if i do something wrong.

**Comment by rallek** [comment]
#2457 and #2459 may have the same root cause but they are 1.4.0 issues.

**Comment by craigh** [comment]
@Portugao which Core version are you using?

**Comment by Portugao** [comment]
Core version 1.3.10

**Comment by craigh** [comment]
can you check if it worked correctly in Core-1.3.6 or less?

**Comment by Portugao** [comment]
I will try.

**Comment by Portugao** [comment]
First test with core version 1.3.5:
Same issue.
It seems, that there is a problem with the path to module templates....
For the footer.tpl in the directory 'includes' of the theme (anderas08) the translation does work.

**Comment by craigh** [comment]
If you can figure out a fix, I would be happy to merge it.

**Comment by Portugao** [comment]
Where i can find the relevant code?
Samstag, 07 November 2015, 00:29vorm. +0100 von Craig Heydenburg < notifications@github.com> :

**Comment by KratorD** [comment]
Any fix / upgrade / work around for this ? @craigh  @Portugao

**Comment by Portugao** [comment]
No, at the moment there is no idea where to find the relevant code....

**Comment by KratorD** [comment]
Hello.
I'm testing with ZK 1.3.10 and custom theme. I'm using gettext from here http://zikula.org/gettext/
I'm traslating from spanish. It's working for me.
@Portugao Could you check your path, filenames, case sensitives...?

**Comment by Portugao** [comment]
@KratorD What do mean with:

> Could you check your path, filenames, case sensitives...?

**Comment by Guite** [comment]
Closing as there won't be a 1.3.13 release.
