### ISSUE TITLE
unable to find `jquery.mmenu.min.all.js` in build 104

### ISSUE THREAD

**Issue by rallek** [zikula/core#2638]
An absolutely fresh install from ci.zikula org per wget is failing. Install is running fine but after trying to log in I do get this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("Unable to find file "@ZikulaAdminModule/Resources/public/js/jQuery.mmenu-5.5.1/dist/core/js/jquery.mmenu.min.all.js".") in "ZikulaAndreas08Theme:Include:header.html.twig" at line 15.

**Comment by rallek** [comment]
The file ``jquery.mmenu.min.all.js`` is not there but ``jquery.mmenu.min.js``. Renaming seems to fix the issue

**Comment by craigh** [comment]
fixed in https://github.com/zikula/core/commit/b157d9ef9c273195aecbe1e0d16e47c0b73396cb
