### ISSUE TITLE
ContainerAware class deprecated in Symfony

### ISSUE THREAD

**Issue by craigh** [zikula/core#2639]
https://github.com/symfony/symfony/commit/807ebac08ce0c7d0e0f9d2a69dc73c7f3c934da8

investigate how this affects Zikula.

a quick search shows that the class in only used once directly:

https://github.com/zikula/core/blob/1.4/src/lib/util/ModUtil.php#L1037

but instances of ContainerAwareInterface are used elsewhere. It is not clear to me how the new `ContainerAwareTrait` should be properly used yet. Also it is not clear to me how to determine if a class requires the injection of the Container on instantiation (e.g. `MyClass->setContainer($c)`) perhaps classes employing `ContainerAwareTrait` will always implement `ContainerAwareInterface`? It is unclear.

**Comment by craigh** [comment]
refs https://www.drupal.org/node/2229183
and https://github.com/symfony/symfony/pull/16411

**Comment by craigh** [comment]
Traits require php > 5.4 so this issue cannot be backported to Core-1.x. It can only be implemented in Core-2.0

**Comment by craigh** [comment]
Core requires php 5.4+ now. so this can be done any time

**Comment by Guite** [comment]
This was already done in `master` as part of #3196

**Comment by craigh** [comment]
if done in `master` then moving to different milestone.
