### ISSUE TITLE
New composer spec is missing application dependencies

### ISSUE THREAD

**Issue by Guite** [zikula/core#2640]
The new composer specification needs an additional array for defining application (module) dependencies (name, min version, max version, dependency type (required, recommended, conflict)).

**Comment by Guite** [comment]
Initially I thought they would need to be added to the `require` section, but @cmfcmf meant that this is not possible if composer should still be usable for a module.

**Comment by craigh** [comment]
yes this is already done. just a moment.

**Comment by craigh** [comment]
this is for suggested:

https://github.com/zikula-modules/Pages/blob/master/composer.json#L19-L21

**Comment by craigh** [comment]
I can't remember now. I think requires DOES go in the `require` section.

**Comment by Guite** [comment]
Okay great! Thank you.

**Comment by craigh** [comment]
here it is 
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Bundle/MetaData.php#L160-L189

**Comment by Guite** [comment]
Implemented in https://github.com/Guite/MostGenerator/compare/a3fd9778d0e2ac5aeb067b9df5eeef4ff4960beb...796fd95bd3abbadbabb52fdd3a4b42752d5d4fa8
