### ISSUE TITLE
admin panel with german translation can not be opened

### ISSUE THREAD

**Issue by rallek** [zikula/core#2642]
after finalizing the installation I am guided to http://koester123.de/admin/panel

In the past I was request to log in. But this time I did get a message by firefox:

````
Fehler: Umleitungsfehler

Die aufgerufene Website leitet die Anfrage so um, dass sie nie beendet werden kann.

    Dieses Problem kann manchmal auftreten, wenn Cookies deaktiviert oder abgelehnt werden.
````

If I go back to homepage (deleting /admin/panel) I see the homepage and con log in. If I than try to go to admin site I am back into the same loop.

I am using ci build 113 with some German translation files (which are working in the past pretty well)

**Comment by rallek** [comment]
I switched into dev mode
````
    env: dev
    debug: true
...
    locale: en
...
````
and the locale to english. Now I can load the admin panel. After saving the settings again. I am running into the same problem than before!

Something language related I guess.

I will reinstall the complete site without the german translations and report again.

**Comment by rallek** [comment]
I did a complete reinstall with empty database and so on.
First installtion without german zikula.po and zikula_js.po. Everything is fine. Than I uploaded the po and mo files to ``/app/Resources/locale/de/LC_MESSAGES``. Went back to language settings and made german the default language. 

Same issue than reportet before! It is a blocker for me!!!

**Comment by craigh** [comment]
Is this behavior different than Core-1.4.0?

**Comment by rallek** [comment]
I have on simple site running with 1.4.0 in German: omi.11-cv.net

**Comment by craigh** [comment]
you didn't really answer the question.

**Comment by rallek** [comment]
Yes, it is different. 1.4.0 is working as expected, 1.4.1 is not working in translated mode.

**Comment by craigh** [comment]
please post the translation files that you are using to this ticket or post a link and instructions to reproduce.

one obvious difference between 1.4.0 and 1.4.1 is the theme engine has been replaced. I'm not sure if the translation is affected by this or not.

**Comment by rallek** [comment]
I am using the lang files from the german community at github. You have to use the 1.4 branch.

Uppload the app folder to a fresh install after the intallation of ci 113. Than go to language settings. There you will see the german translation. The default is still English. You have to change to German. Than the trouble began.

**Comment by rallek** [comment]
See https://github.com/zikula-communities/german/tree/core-1.4?files=1

**Comment by craigh** [comment]
@cmfcmf can you look into this? I'm wonderful night if it has something to do with routing.

**Comment by Guite** [comment]
Hmm. I am also running two sites with 1.4 which work fine also in German.
@rallek could you try the change I described in #2593 (disabling one line)? Because I can not think of another difference which could cause the misbehaviour.

**Comment by craigh** [comment]
@Guite I believe tha Ralf is talking about 1.4.1 and not 1.4.0

**Comment by rallek** [comment]
@craigh I am talking about 1.4.1 because 1.4.0 is working fine
@Guite Might be you want to test at the same test site a gave you access yesterday. I am not at home and have to work longer today. If you want to wait for me I can do it later this week myself.

**Comment by Guite** [comment]
Confirmed: the frontend works fine having the German language enabled as default language.
In the admin area only a MOST module and the News module work.

Other pages like `/search/admin` and `/securitycenter/admin` lead to a `404` error.
And the admin panel link (`/admin/panel`) leads to an endless redirect.

**Comment by rallek** [comment]
My observation: If I change inside ``custom_parameters.yml`` ``locale: de`` to ``locale: en`` I can open the setting. There still German is the default language. The translation is working. But if I save that settings it is bad again.

Now I change the settings to english and the site is working.

**Comment by Kaik** [comment]
Hi, I just started testing sorry for being late... 1.4.1 build 114 
1. First install screen before lang chooser is not loading translator at all
2. Second screen lang chooser this looks like this stage is not showing properly and this is due to this IsNesscesary function https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Stage/LocaleStage.php#L74 It should be true for cases when multiple languages are installed.

Detecting what languages are installed base on Zlanguage functions and this is only detecting lang's for old folders https://github.com/zikula/core/blob/1.4/src/lib/i18n/ZLanguage.php#L669 

3. Not saving and not changing language when chosen at least in my case need to do some more test's

**Comment by craigh** [comment]
> need to do some more tests

please let me know. I am available on slack all day.

**Comment by craigh** [comment]
Considering this a blocker for Core-1.4.1

refs #2641

**Comment by craigh** [comment]
![directory_structure](https://cloud.githubusercontent.com/assets/350048/11300669/fe50fb3a-8f5e-11e5-802a-e730408fbe4e.png)
![screen shot 2015-11-20 at 8 05 32 am](https://cloud.githubusercontent.com/assets/350048/11300674/fe543926-8f5e-11e5-9b57-4f8fd88d6e49.png)
![screen shot 2015-11-20 at 8 05 46 am](https://cloud.githubusercontent.com/assets/350048/11300672/fe53ee80-8f5e-11e5-84e8-4b47a3153102.png)
![screen shot 2015-11-20 at 8 06 09 am](https://cloud.githubusercontent.com/assets/350048/11300670/fe51ad14-8f5e-11e5-9303-fa4b9103d18d.png)
![screen shot 2015-11-20 at 8 06 39 am](https://cloud.githubusercontent.com/assets/350048/11300671/fe53d4fe-8f5e-11e5-83e8-77e167e1ba8a.png)
![screen shot 2015-11-20 at 8 07 06 am](https://cloud.githubusercontent.com/assets/350048/11300673/fe545064-8f5e-11e5-9ee5-ab498e044c05.png)
![screen shot 2015-11-20 at 8 08 09 am](https://cloud.githubusercontent.com/assets/350048/11300675/fe65710a-8f5e-11e5-9779-bda20c954d9a.png)
![screen shot 2015-11-20 at 8 09 30 am](https://cloud.githubusercontent.com/assets/350048/11300676/fe6858c0-8f5e-11e5-8175-3b2ccdef6b9f.png)
![screen shot 2015-11-20 at 8 10 45 am](https://cloud.githubusercontent.com/assets/350048/11300679/fe6f990a-8f5e-11e5-8324-e1335d95fec1.png)
![screen shot 2015-11-20 at 8 11 08 am](https://cloud.githubusercontent.com/assets/350048/11300677/fe6b1b96-8f5e-11e5-9f33-f3f7ba0b6997.png)
![screen shot 2015-11-20 at 8 15 25 am](https://cloud.githubusercontent.com/assets/350048/11300678/fe6f3a82-8f5e-11e5-8f90-97bd3f693182.png)

**Comment by craigh** [comment]
so - coming back to the OP. I think I can reproduce the error. I am simply trying to change locale from german to english. I get the following error:

> Safari Can’t Open the Page: Too many redirects occurred trying to open “‎127.0.0.1/core.git/src/de/settings”. This might occur if you open a page that is redirected to open another page which then is redirected to open the original page

I think this is the same basic error as what is in the OP.

**Comment by rallek** [comment]
Exactly

**Comment by craigh** [comment]
places where locale/lang is set:
 - `custom_parameters.yml` :: `locale: en` 
   - updated when changed via `/settings/admin/ml`
 - `config.yml` :: `translator: {fallbacks: %locale%}` (should probably be `en`)
   - `%locale%` means use parameter from `custom_parameters.yml` file
 - `config.yml` :: `default_locale: "%locale%"`
   - same. see above.
 - `dynamic/generated.yml` :: `default_locale: en`
   - updated when changed via `/settings/admin/ml`

also there are settings in the Database:
 - `ZConfig` :: `language` = `eng`
 -  `ZConfig` :: `locale` = 'en'
 -  `ZConfig` :: `language_i18n` = 'en'

I will update this comment when I know more about the DB settings and how the are used.

**Comment by Kaik** [comment]
I think ```locale``` not ```default_locale``` is changing via ```/settings/admin/ml```
default user locale (in users settings so user can select default language for himself)

**Comment by craigh** [comment]
the *user* locale isn't set at all I don't think for Symfony-type translation...

see http://symfony.com/doc/current/book/translation.html#handling-the-user-s-locale

**Comment by craigh** [comment]
so a little more testing give me this information:

after changing the language in `/settings/admin/ml` it tries to redirect to `/settings/admin/ml` but the `$router->matchRequest($request);` fails to match in `System::queryStringDecode()` and so it falls back to the `LegacyRouteListener::onKernelRequest()` where it also fails (because it is not a legacy route) and then we get the message 'Page not found' (from [line 95](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/EventListener/LegacyRouteListener.php#L95))

**Comment by craigh** [comment]
now I learned that it is succeeding once with the route and then trying to match it a second time and failing. In both cases, the locale is `en` not `de` as I had just selected.

**Comment by craigh** [comment]
but now the error is in German... ;-)

![screen shot 2015-11-20 at 5 31 32 pm](https://cloud.githubusercontent.com/assets/350048/11313662/9669820a-8fac-11e5-8d99-e9c3b2d8a016.png)

**Comment by craigh** [comment]
I think this is an issue for us:

https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Core.php#L491-L508

here, the language/locale is not set up until AFTER the url is decoded. This doesn't work for Symfony. the  locale has to be set before a route is looked up.

**Comment by craigh** [comment]
> now I learned that it is succeeding once with the route and then trying to match it a second time

This is because the first time is on form submission, the route has already been generated and rendered in the form and the controller hasn't processing of the "change" yet.

the second time is after the changes are made and the controller is trying to generate a route and this is when it fails.

**Comment by craigh** [comment]
I've learned that the `/Applications/MAMP/htdocs/core.git/src/app/cache/prod/appProdUrlGenerator.php` file is corrupt after the language switch (maybe even BEFORE)

When `_locale` is set to `en` then the route `/settings/admin/ml` is present in the file, but there are some other strange things:

```
        'zikulasettingsmodule_admin_multilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::multilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'multilingual',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/settings/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'de__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'de',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/de/settings',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'en__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'en',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/settings/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pl__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'pl',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/pl/settings/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
```

notice the end of the lines:
`zikulasettingsmodule_admin_multilingual => '/settings/admin/ml'`
`de__RG__zikulasettingsmodule_admin_updatemultilingual => '/de/settings'`
`en__RG__zikulasettingsmodule_admin_updatemultilingual => '/settings/admin/ml'`
`pl__RG__zikulasettingsmodule_admin_updatemultilingual => '/pl/settings/admin/ml'`

_you can see `/de/settings` is an incomplete route and conflicts with several other routes in the same file._

now if I switch to German (de) I have the following lines in `/Applications/MAMP/htdocs/core.git/src/app/cache/prod/appProdUrlGenerator.php`:

```
        'zikulasettingsmodule_admin_multilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::multilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'multilingual',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/konfiguration/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'de__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'de',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/konfiguration',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'en__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'en',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/en/konfiguration/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pl__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'pl',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/pl/konfiguration/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
```

`zikulasettingsmodule_admin_multilingual => '/konfiguration/admin/ml'`
`de__RG__zikulasettingsmodule_admin_updatemultilingual => '/konfiguration'`
`en__RG__zikulasettingsmodule_admin_updatemultilingual => '/en/konfiguration/admin/ml'`
`pl__RG__zikulasettingsmodule_admin_updatemultilingual => '/pl/konfiguration/admin/ml'`

_notice how all locales are using the same German translation for `settings` = `configuration ` and that the `de` route is still incomplete, and still conflicting with multiple other routes in the file._

the `configuration ` translation is coming from a **legacy** translation file. it is not present in the routes translation file at all. perhaps the routes translation is using the wrong domain? (should be 'routes' I think). 

ping @cmfcmf this is definitely a problem with how the routes "table" (cached file) is translated and built.

**Comment by craigh** [comment]
after switching to polish (`pl`) the same lines look like this:

```
        'zikulasettingsmodule_admin_multilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::multilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'multilingual',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ustawienia/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'de__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'de',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/de/ustawienia',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'en__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'en',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/en/ustawienia/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pl__RG__zikulasettingsmodule_admin_updatemultilingual' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Zikula\\SettingsModule\\Controller\\AdminController::updatemultilingualAction',    '_zkBundle' => 'ZikulaSettingsModule',    '_zkModule' => 'ZikulaSettingsModule',    '_zkType' => 'admin',    '_zkFunc' => 'updatemultilingual',    '_locale' => 'pl',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ustawienia/admin/ml',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
```

`zikulasettingsmodule_admin_multilingual => '/ustawienia/admin/ml'`
`de__RG__zikulasettingsmodule_admin_updatemultilingual => '/de/ustawienia'`
`en__RG__zikulasettingsmodule_admin_updatemultilingual => '/en/ustawienia/admin/ml'`
`pl__RG__zikulasettingsmodule_admin_updatemultilingual => '/ustawienia/admin/ml'`

so, I am now remembering that we wrote a special class to translate the module 'url' - and this is the problem with all the routes using the same translation for the url.

this doesn't however explain the problem where the German translation is always incomplete.

**Comment by craigh** [comment]
I've made some progress with this. 

The German translations were incomplete because I had a `routes.de.po` file with a bunch off empty values. Lesson to learn here is that if you copy the `.pot` file and only define one or two routes, then delete all the other keys/translations or the routes get messed up. @rallek 

The module 'url' was being included because of earlier coding mistakes which I have fixed locally. now I am working out an issue with the `options={"i18n"=false}` and then it should be all set.

**Comment by cmfcmf** [comment]
> The German translations were incomplete because I had a routes.de.po file with a bunch off empty values. Lesson to learn here is that if you copy the .pot file and only define one or two routes, then delete all the other keys/translations or the routes get messed up. @rallek

Interesting and important to know. Makes sense though.
