### ISSUE TITLE
Auto-login is not working

### ISSUE THREAD

**Issue by Guite** [zikula/core#2646]
Enabling automatic login after registration in the Users configuration leads to the following error:

```
Unable to parse the controller name "zikulausersmodule_user_login".
```

This relates to two occurances:
https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Controller/UserController.php#L670
https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Controller/UserController.php#L2234

**Comment by cmfcmf** [comment]
I reverted the milestone to 1.4.1. This should be an easy-fix. I'll look into it now.
