### ISSUE TITLE
[CI Server] auto-update composer

### ISSUE THREAD

**Issue by craigh** [zikula/core#2652]
see if there is a way to auto-update composer on a weekly basis or something. Maybe a CRON?

@cmfcmf @Guite

**Comment by cmfcmf** [comment]
Maybe do a self-update inside the build.xml file every time the core is
built?

Craig Heydenburg <notifications@github.com> schrieb am Di., 24. Nov. 2015
14:08:

**Comment by craigh** [comment]
maybe this is not necessary? does [this line] in the build file download a new version of composer for each build?

**Comment by Guite** [comment]
Seems so.
