### ISSUE TITLE
translation of MediaModule is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#2653]
I installed the MediaModule 1.0.2 into zikula 1.4.1 final release. Zikula do have the old fashion translation to German. That is working. But the translation of MediaModule is broken. There no German translation is visible.
News for example is translating fine.

**Comment by rallek** [comment]
I tried the lastest MediaModule as well. Translation is still not working. You can see here:
http://oldtimer-ig-osnabrueck.de/collections/ For me it is confirmed. Might be it has the same reason why the installer is not translated as well.

**Comment by rallek** [comment]
ich switched back from dev mode to prod mode. In prod mode the translation is working.

**Comment by cmfcmf** [comment]
Aha! Interesting. Thank you for your feedback @rallek.

**Comment by craigh** [comment]
> I switched back from dev mode to prod mode.

for the record, I rarely work in dev mode any longer. mainly because everything is so much slower. Even when I am in full development mode myself :smile:

**Comment by cmfcmf** [comment]
> or the record, I rarely work in dev mode any longer. mainly because everything is so much slower.

I disable XDebug and only enable it when I really need it. This speeds up things a lot as well.

**Comment by Guite** [comment]
Postponed, since things work well in prod mode.

**Comment by rallek** [comment]
Will do this evening.

**Comment by rallek** [comment]
due to #3197 I can not test it today

**Comment by rallek** [comment]
At the end the installation is working. Translation to german is there but not 100% complete. The completelieness is another story.

I also switched to dev mode. Also there translation is working fine.

**Comment by Guite** [comment]
Thanks for the information!

**Comment by rallek** [comment]
confirmed. News is showing again a 404.

**Comment by rallek** [comment]
ups. commented at the wrong ticket
