### ISSUE TITLE
update SensioDistributionBundle

### ISSUE THREAD

**Issue by craigh** [zikula/core#2656]
https://github.com/sensiolabs/SensioDistributionBundle/releases

current: `"sensio/distribution-bundle": "4.0.*",`

available: 5.0.3

there seems to be no documentation or changelog regarding differences between v4 and v5.

**Comment by Guite** [comment]
Seems like there were only bugfixes so far: https://github.com/sensiolabs/SensioDistributionBundle/compare/v4.0.3...master
