### ISSUE TITLE
We should not overwrite the RouterListener

### ISSUE THREAD

**Issue by craigh** [zikula/core#2657]
When I ran the composer update to Symfony 2.8, I received the following:

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
>   [Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException]  
>   Service definition validation errors (1):                                                                                                                          
> - router_listener: Argument for type-hint "Symfony\Component\Routing\RequestContext" points to a service of class "Symfony\Component\HttpFoundation\RequestStack"  
> 
> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-update-cmd event terminated with an exception
>   [RuntimeException]  
>   An error occurred when executing the "'assets:install '\''src/web'\'''" command:                                                           
> 
>  [Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException]                                                
> 
>  Service definition validation errors (1):                                                                                                
> - router_listener: Argument for type-hint "Symfony\Component\Routing\RequestContext" points to a service of class "Symfony\Component\HttpFoundation\RequestStack"

You have a note in the listener about a 3.0 change, but maybe the change has been migrated to 2.8. Can you please look into it?

**Comment by craigh** [comment]
It looks like symfony provides a BC solution in their own listener

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L60

so maybe we can just copy their constructor into ours and call it good. It looks like our current constructor mirrors the Symfony 2.6 (or so) constructor

**Comment by cmfcmf** [comment]
Fixed by https://github.com/zikula/core/commit/42efc92bc96a7564a03bda6284c465e2faee09c1. It was caused because we overwrite an internal Symfony class. I think there is a better way. Leaving this ticket open until we implement the better way.
