### ISSUE TITLE
symfony-console-form was upgraded

### ISSUE THREAD

**Issue by craigh** [zikula/core#2658]
matthiasnoback/symfony-console-form was upgraded from 1.1.* to 1.2.0 via composer. Confirm the installer still works. If not, consider downgrading the lib.

**Comment by cmfcmf** [comment]
Travis builds (which use the command line installer) still run, so it
should be fine I suppose.

Craig Heydenburg <notifications@github.com> schrieb am So., 29. Nov. 2015
23:01:

**Comment by Guite** [comment]
@rallek if you like to and have some free time, please test installation of the latest CI build. thanks in advance.

**Comment by craigh** [comment]
this requires testing the CLI install.

**Comment by rallek** [comment]
first time I did a CLI install. It seems to work even with ``mod_suexec`` module loaded in my shared hosting environment. 

I downloaded ci build 5 of 1.4.2 dev via wget. 

I did not test with language pack.
