### ISSUE TITLE
update to Symfony 2.8

### ISSUE THREAD

**Issue by craigh** [zikula/core#2659]
Current is 2.7.*

Symfony 2.8 is releasing this week (or soon)

The major benefit of updating to 2.8 (even in mid1.4.x release cycle) is that 2.8 = 3.0 + legacy. Which means, all the functionality of 3.0 is available and we can safely base Core-2.0 on Symfony 3 and pre-empt much refactoring that would need to be done if we stick with 2.7 APIs. 

@Guite do you have an opinion on this? @cmfcmf ? others?

**Comment by shefik** [comment]
Make it so.

**Comment by Guite** [comment]
:+1: for 2.8

**Comment by cmfcmf** [comment]
Additionally, symfony 2.8 is a LTS release.

Axel Guckelsberger <notifications@github.com> schrieb am Mo., 30. Nov. 2015
07:44:

**Comment by Guite** [comment]
Really? I thought that because 2.7 is a LTS release, 2.8 would not be.

**Comment by cmfcmf** [comment]
Fabien announced it at the Symfony Live.  There would be a gap between the
2.7 LTS and the 3.x LTS otherwise. It's a little difficult.

Axel Guckelsberger <notifications@github.com> schrieb am Mo., 30. Nov. 2015
12:48:

**Comment by craigh** [comment]
done in https://github.com/zikula/core/commit/7ac9a324d158a1d0ab282c75266839e91eecfcac
