### ISSUE TITLE
Use JMS vendor for Routing bundle again

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2661]
https://github.com/schmittjoh/JMSI18nRoutingBundle/pull/152 has finally been merged now.

**Comment by craigh** [comment]
is the root repo now up to date with the fork we are using or is it still behind?

**Comment by cmfcmf** [comment]
I guess so. Also this one was merged: https://github.com/schmittjoh/JMSI18nRoutingBundle/pull/151 Maybe we can remove the JMSTranslation bundle ourselves.

**Comment by craigh** [comment]
I think we are using that.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/1.4/build.xml#L132

**Comment by cmfcmf** [comment]
Hmm okay.

**Comment by Guite** [comment]
What's the state of this issue?

**Comment by Guite** [comment]
> What's the state of this issue?
Is there still something to do or can it be closed?

**Comment by cmfcmf** [comment]
>> What's the state of this issue?
> Is there still something to do or can it be closed?

The state is unchanged.

**Comment by Guite** [comment]
Can you please be more specific: what exactly needs to be done?

**Comment by cmfcmf** [comment]
It needs to be checked whether or not the JMS Routing Bundle now incorporates all the features we need from our currently used fork and if yes, we can switch back to the original repo.
