### ISSUE TITLE
Module links not compatible with bootstrap nav bars 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2662]
Hi,
I have small issue with module menu (register page) on Bootstrap theme.
Dropdown icon should not be an anchor in bootstrap.
https://github.com/zikula/core/blob/1.4/src/lib/legacy/viewplugins/function.modulelinks.php#L251
![screenshot from 2015-12-03 18-07-18](https://cloud.githubusercontent.com/assets/966910/11567759/d76e0230-99e8-11e5-8f0c-bb73eb03a826.png)

Additionally there is unneeded H4 title but that is BootstrapTheme template issue.

**Comment by craigh** [comment]
Is this because you have overridden the core's own bootstrap?

**Comment by Kaik** [comment]
No this was on untouched 1.4.1
