### ISSUE TITLE
filter incompatibility with Symfony 2.8

### ISSUE THREAD

**Issue by craigh** [zikula/core#2663]
at the route `/routes/admin` I get this error:

> [1] Symfony\Component\Debug\Exception\ContextErrorException: User Error: Passing the $deep boolean as 3rd argument to the Symfony\Component\HttpFoundation\ParameterBag::filter method is deprecated since version 2.8 and will be removed in 3.0. Remove it altogether as the $deep argument will be removed in 3.0.
    at n/a
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ParameterBag.php line 271

>    at Symfony\Component\Debug\ErrorHandler->handleError('256', 'Passing the $deep boolean as 3rd argument to the Symfony\Component\HttpFoundation\ParameterBag::filter method is deprecated since version 2.8 and will be removed in 3.0. Remove it altogether as the $deep argument will be removed in 3.0.', '/Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ParameterBag.php', '271', array('key' => 'ot', 'default' => 'route', 'filter' => false, 'options' => '513', 'deep' => array(), 'filters' => array('1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'), 'tmp' => 'callback'))
        in  line 

>    at trigger_error('Passing the $deep boolean as 3rd argument to the Symfony\Component\HttpFoundation\ParameterBag::filter method is deprecated since version 2.8 and will be removed in 3.0. Remove it altogether as the $deep argument will be removed in 3.0.', '256')
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ParameterBag.php line 271

>    at Symfony\Component\HttpFoundation\ParameterBag->filter('ot', 'route', false, '513', array())
        in /Applications/MAMP/htdocs/core.git/src/lib/legacy/Zikula/Bag/ParameterBag.php line 54

>    at Zikula_Bag_ParameterBag->filter('ot', 'route', false, '513')
        in /Applications/MAMP/htdocs/core.git/src/system/RoutesModule/Controller/Base/AdminController.php line 64

>    at Zikula\RoutesModule\Controller\Base\AdminController->indexAction(object(Zikula_Request_Http))
        in /Applications/MAMP/htdocs/core.git/src/system/RoutesModule/Controller/AdminController.php line 41

>    at Zikula\RoutesModule\Controller\AdminController->indexAction(object(Zikula_Request_Http))
        in  line 

>    at call_user_func_array(array(object(AdminController), 'indexAction'), array(object(Zikula_Request_Http)))
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 139

>    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

>    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

>    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

>    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /Applications/MAMP/htdocs/core.git/src/index.php line 25

ping @cmfcmf @Guite

**Comment by craigh** [comment]
@cmfcmf didn't https://github.com/zikula/core/commit/42efc92bc96a7564a03bda6284c465e2faee09c1 address and fix this issue? It wasn't tagged as such.

**Comment by cmfcmf** [comment]
no..

**Comment by cmfcmf** [comment]
This issue has nothing to do with routes, but with the filter method.

**Comment by craigh** [comment]
refs https://github.com/symfony/symfony/issues/17058

**Comment by craigh** [comment]
also, we are overwriting the `filter` method here: https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Bag/ParameterBag.php

Apparently at some point in Symfony history (or our own, I suppose) these arguments were changed previously. Now they are changed again - ironically BACK to something like we _used_ to use. So, we need to adjust this override class again, but I'm not sure exactly how.
