### ISSUE TITLE
Invalid arguments array received

### ISSUE THREAD

**Issue by shefik** [zikula/core#2665]
Doing a new install of Zikula 1.4.1 throws this error, after the site is successfully installed, and after I submit the login form:

```
( ! ) Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid arguments array received' in /system/ExtensionsModule/Api/AdminApi.php on line 1364
( ! ) InvalidArgumentException: Invalid arguments array received in /system/ExtensionsModule/Api/AdminApi.php on line 1364
Call Stack
#	Time	Memory	Function	Location
1	0.8129	24338120	Symfony\Component\Debug\ErrorHandler->handleException( )	../ErrorHandler.php:0```

**Comment by shefik** [comment]
The problem seems to be that during the install of Zikula core, it regenerates modules that are within the `modules` directory. But, only psr-2 and old-style modules get regenerated. Whereas, per-4 modules do not get included in the regeneration.

If you go directly to the Extensions module, it gets regenerated fine. But, somewhere in the install process, it's not correct.

This used to work fine in Zikula 1.4.0, but module regeneration is now broken in Zikula 1.4.1.

**Comment by shefik** [comment]
@craigh I found the cause of the problem. It's in your commit from August 30, 2015:

https://github.com/zikula/core/commit/ab6502c18a55435e0200c1f020dac8d9b3312a23

In the file `src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php`, line 172:

`$modApi->regenerate(array('filemodules' => $modApi->getfilemodules(array('system'))));`

needs to be changed back to this line:

`$modApi->regenerate(array('filemodules' => $modApi->getfilemodules()));`

I just tested it with the line reverted, and it works.

**Comment by craigh** [comment]
please tell me how to reproduce the problem.

**Comment by craigh** [comment]
the travis builds pass, which means core installs without error:

https://travis-ci.org/zikula/core/builds/93931462

**Comment by craigh** [comment]
I installed 1.4.1 today with no error.
