### ISSUE TITLE
Autocomplete in CLI installer

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2666]
Hi,
I was installing 1.4.1 recently, using package with vendors and github clone + composer. I have used web installer and cli. Everything works fine. I have just small issue to consider turning off autocomplete in installer forms because it is not very clean and sometimes you just do not know what was typed what is suggested and what will be set. I do often end up with https instead of http etc

Maybe its just me but it's confusing. 

Apart from that all installation works fine :+1:  later I will test with pre-installed languages.etc

**Comment by craigh** [comment]
I don't want to disable this. If I understand you correctly, you are referring to the fact that the choices and so on presented in the installer/upgrader have default values. I would like these default values to remain as they are the same forms (and default choices) used in the http installer. IMO they are useful in both situations.
