### ISSUE TITLE
Switch from LESS to SASS

### ISSUE THREAD

**Issue by craigh** [zikula/core#2670]
Bootstrap is going to SASS only I think

http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

@phaidon 

Pretty sure the core won't upgrade to Bootstrap 4 until Core-2.0 but we should look into this conversion. I'm not familiar with either LESS or SASS so I will not be doing this.

**Comment by phaidon** [comment]
> Bootstrap is going to SASS only I think.
Yes and this are good news.

> Pretty sure the core won't upgrade to Bootstrap 4 until Core-2.0 but we should look into this conversion.

Bootstrap 4 looks promising, but in the alpha there are big BC. 

> I'm not familiar with either LESS or SASS so I will not be doing this.

The differences are not very big. The conversation from LESS to SASS is not a big deal. The bigger deal is to switch to bootstrap 4.

**Comment by craigh** [comment]
@phaidon - I assume we can SASS with bootstrap 3. If so, should we do this now? If so, can you do it?

**Comment by Guite** [comment]
Moved to 3.0, refs #3530

**Comment by Guite** [comment]
Closing in favour of #3530
