### ISSUE TITLE
Removing theme from theme directory cause blank page

### ISSUE THREAD

**Issue by paustian** [zikula/core#2671]
Removing a theme from the theme  directory, once you have used the theme, causes Zikula 1.4 to break. 
This happens when the theme is not the theme in use. To recreate this bug, Set a theme as the default theme. Test the theme. Then choose another theme as the default. Finally, remove the theme from the theme directory. You will get a blank page. This happens even if you try to delete the theme before removing the files. (Btw, delete the theme has no effect) Here is the php error you will get….

> Marker - Dec 12, 2015, 1:23:14 PM
[12-Dec-2015 20:25:40 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'The "/Applications/MAMP/htdocs/Zikula_1_4_1/themes/MicrotextbookTheme/Resources/views" directory does not exist.' in /Applications/MAMP/htdocs/Zikula_1_4_1/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:94
Stack trace:
#0 /Applications/MAMP/htdocs/Zikula_1_4_1/app/cache/prod/appProdProjectContainer.php(1946): Twig_Loader_Filesystem->addPath('/Applications/M...', 'PaustianMicrote...')
#1 /Applications/MAMP/htdocs/Zikula_1_4_1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(305): appProdProjectContainer->getTwig_LoaderService()
#2 /Applications/MAMP/htdocs/Zikula_1_4_1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(431): Symfony\Component\DependencyInjection\Container->get('twig.loader', 2)
#3 /Applications/MAMP/htdocs/Zikula_1_4_1/lib/legacy/Zikula/ServiceManager.php(117): Symfony\Component\DependencyInjection\ContainerBuilder->get('twig.loader', 1)
#4 /Applications/MAMP/htdocs/Zikula_1_4 in /Applications/MAMP/htdocs/Zikula_1_4_1/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 94

**Comment by craigh** [comment]
> Set a theme as the default theme. Test the theme. Then choose another theme as the default. Finally, remove the theme from the theme directory.

I did this, in that exact order and found no error at all ;-)

**Comment by craigh** [comment]
Maybe your theme is special somehow? Do you have more than templates in it? Is it a Core-2.0 Theme? (I tested with a 1.4-type). Zip the files up and post here.

**Comment by pheski** [comment]
Similar problem here. 

I uploaded BlankTheme.  I did not set it as a default theme, but did preview it.  Or tried to - got an error.

Then I tried to remove it.  When I try to remove it using the theme list under Layout, it tells me to remove the folder first. Whether or not I remove the folder doesn't matter - it breaks the site.

**Comment by cmfcmf** [comment]
Does clearing the cache fix the issue for you? (delete the content of app/cache/prod|dev).

**Comment by pheski** [comment]
Hmmm.

I don’t have anything that looks like what you describe.  In app/cache/prod I have the following directories:
annotations
doctrine
fosjsRouting
translations
twig
ztemp
doctrinemodels
error_logs
idsTmp
purifierCache
systemplugin.imagine
Theme_cache
Theme_compiled (this had BlankTheme and I cleared it)
Theme_Config
view_cache
view_compiled



I have tried the following:
In Themes, use the Trash icon to throw away BlankTheme. I get a confirmation that tells me to discard the files first, so I discard the files, check the box, and then hit submit.  I get the following error message: "
Fatal error: Class 'Matheo\BlankTheme\BlankListener' not found in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 142”
I have done the same, without checking the box: same result.
I have discarded the theme folder before I try to discard it on the theme page: same result.

I’m guessing I will have to use phpAdmin to get rid of any traces and then trash the BlankTheme directory?  I hate mucking with the database, though.

Peter

**Comment by craigh** [comment]
He means to delete the entire directory `app/cache/prod`

**Comment by pheski** [comment]
I did. Didn't help. Thanks, though.

**Comment by craigh** [comment]
> I uploaded BlankTheme. I did not set it as a default theme, but did preview it. Or tried to - got an error.

@pheski - what was the error? How did you 'store' the theme in the `/themes` directory? I did like so:

```
  /themes
    /Andreas08Theme
    /AtomTheme
    /BlankTheme-master
      /Matheo
        /BlankTheme
````

This directory structure is because the theme is a psr-0 theme. ([psr-0](http://www.php-fig.org/psr/psr-0/)).Core themes are [psr-4](http://www.php-fig.org/psr/psr-4/) which means the directory structure is truncated somewhat.

Anyway - I was able to successfully install, preview and remove BlankTheme without error. So I still cannot duplicate this error.

@pheski / @paustian - if you can still duplicate the error, change `debug` to `true` in `app/config/custom_parameters.yml` and then the full error and traceroute will be displayed when you have an error. please post the error here.

**Comment by pheski** [comment]
Here is how the directory appears for me:

  /themes
    /Andreas08Theme
    /AtomTheme
    /BlankTheme
      /Matheo
        /BlankTheme

If I hover my cursor over BlankTheme on the left, I get a pop-up thumbnail of BlankTheme that looks fine, but I assume this is just a displayed thumbnail and does not require any of the actual theme mechanics.

If I use the eyeball icon on the right to preview the theme I get an error message: 

User Warning: Smarty error: unable to read resource: &quot;master.tpl&quot;
500 Internal Server Error - ContextErrorException

The first item in stack trace is:

in vendor/drak/smarty/Smarty/Smarty.class.php at line 1094   -
    function trigger_error($error_msg, $error_type = E_USER_WARNING)
    {
        $msg = htmlentities($error_msg);
        trigger_error("Smarty error: $msg", $error_type);
    }


I will leave it in debug and here is the link to see the entire debug output:
http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme

Peter

**Comment by craigh** [comment]
I cannot view that link without logging in. so I tried to create an account, but apparently it is pending activation?

**Comment by craigh** [comment]
> [1] Symfony\Component\Debug\Exception\ContextErrorException: User Warning: Smarty error: unable to read resource: &quot;master.tpl&quot;
    at n/a
        in /home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php line 1094

>    at Symfony\Component\Debug\ErrorHandler->handleError('512', 'Smarty error: unable to read resource: &quot;master.tpl&quot;', '/home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php', '1094', array('error_msg' => 'unable to read resource: "master.tpl"', 'error_type' => '512', 'msg' => 'unable to read resource: &quot;master.tpl&quot;'))
        in  line 

>    at trigger_error('Smarty error: unable to read resource: &quot;master.tpl&quot;', '512')
        in /home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php line 1094

>    at Smarty->trigger_error('unable to read resource: "master.tpl"')
        in /home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php line 1590

>    at Smarty->_fetch_resource_info(array('resource_name' => 'master.tpl', 'get_source' => true, 'quiet' => false, 'source_content' => null, 'resource_timestamp' => null))
        in /home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php line 1416

>    at Smarty->_compile_resource('master.tpl', '/home/mtkatahdin/petereliasmd.com/app/cache/prod/ztemp/Theme_compiled/BlankTheme/Matheo/BlankTheme/master.php')
        in /home/mtkatahdin/petereliasmd.com/lib/legacy/Zikula/View.php line 2969

>    at Zikula_View->_fetch('master.tpl', 'ed65c31bf3a6aa2c4348c0514d2ea71c', '', false)
        in /home/mtkatahdin/petereliasmd.com/lib/legacy/Zikula/View.php line 772

>    at Zikula_View->fetch('master.tpl', 'ed65c31bf3a6aa2c4348c0514d2ea71c')
        in /home/mtkatahdin/petereliasmd.com/lib/legacy/Zikula/View/Theme.php line 348

>    at Zikula_View_Theme->themefooter(object(Response))
        in /home/mtkatahdin/petereliasmd.com/lib/Zikula/Bundle/CoreBundle/EventListener/Theme/CreateThemedResponseListener.php line 66

>    at Zikula\Bundle\CoreBundle\EventListener\Theme\CreateThemedResponseListener->createThemedResponse(object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
        in  line 

>    at call_user_func(array(object(CreateThemedResponseListener), 'createThemedResponse'), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

>    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(FilterResponseEvent), 'kernel.response', object(Zikula_EventManager))
        in  line 

>    at call_user_func(object(WrappedListener), object(FilterResponseEvent), 'kernel.response', object(Zikula_EventManager))
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 158

>    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent))
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 46

>    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.response', object(FilterResponseEvent), null)
        in /home/mtkatahdin/petereliasmd.com/lib/legacy/Zikula/EventManager.php line 99

>    at Zikula_EventManager->dispatch('kernel.response', object(FilterResponseEvent))
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 124

>    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 179

>    at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(Response), object(Zikula_Request_Http), '1')
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 123

>    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

>    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

>    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/mtkatahdin/petereliasmd.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 184

>    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /home/mtkatahdin/petereliasmd.com/index.php line 25

**Comment by craigh** [comment]
@pheski - you are using the current 'master' of BlankTheme, right? You downloaded using the button on the main page:
![screen shot 2015-12-24 at 10 36 25 am](https://cloud.githubusercontent.com/assets/350048/11996073/422f7684-aa2a-11e5-8a08-949645fa267b.png)

**Comment by pheski** [comment]
Yes.

P

**Comment by craigh** [comment]
The error makes me wonder about the permission settings in your cache folder.

**Comment by pheski** [comment]
? app/cache/prod/

**Comment by craigh** [comment]
yes - and enclosed folders.

**Comment by pheski** [comment]
755, all the way down (like turtles)

But, I think I found the problems and feel pretty stupid - and apologize for the time and energy wasted.

I removed the BlankTheme directory and re-uploaded it and now the preview works fine.  I replaced it with the same one I had used originally.  Usually, the first thing I do when I have an issue like this is wonder about whether something was munged by the ftp process, and discard-replace.  It appears I didn't test that here.

My error. I apologize.  

The LAST thing I want to do is stress our small and dedicated development team.  Too many have left already (drak, Simon, others). 

Peter

**Comment by craigh** [comment]
have to get you a local development environment ;-) It is easier than you think.

It's no problem.

now we can return the ticket to its original post. @paustian send me your theme.

**Comment by paustian** [comment]
Craig,

I have a zip file. Where should I send it?

**Comment by pheski** [comment]
Yes, I had a local dev environment back a few years before my hiatus doing other things. It is on my list of things to do - but it is a long list...

**Comment by paustian** [comment]
MAMP or WAMP make it really easy. https://www.mamp.info/en/

**Comment by craigh** [comment]
@paustian I was able to reproduce the error after some messing about. I also now recognize that your traceroute is actually *two* errors (one for each theme you tried). Finally, I was able to determine that clearing the cache does indeed fix the problem.

**Comment by craigh** [comment]
@cmfcmf @Guite I am pretty sure this is a problem with the "always on" nature of themes which (unlike modules) are always loaded into the kernel (from the DB). So after a theme is removed, the cached container is trying to find the directory and cannot. Since a theme can be added/removed from the `/themes` directory at anytime, we cannot guarantee the cache can be cleared at the appropriate time.

This bug can be more easily replicated by simply doing the following:
  1. place the theme into the theme folder
  2. reload the themes list (`/themes/admin/view`) (updates DB)
    - note: shows theme incorrectly as smarty-based.
  3. remove the theme from the directory (use of GUI or not doesn't matter)
  4. reload the theme list - > WSOD

deleting `src/app/cache/prod/appProdProjectContainer.php` (or appropriate) fixes the problem on next reload.

I tried messing with clearing the `symfony.config` cache in several places without success. Maybe I just tried in the wrong places, but I think the problem is that the kernel is updated (and the themes are pulled from the DB) after the cache is built? 

we may want to consider never persisting the themes? always doing a filescan to load themes into the kernel. Maybe also check to see if the theme is in use? Anyway - I'm not sure I have a good solution here and could use some help.

@paustian Your theme had some errors that were copied from the core theme which I fixed (https://github.com/zikula/core/commit/05c79b58e7570a4ceeb51e1bb92b01d4232fdef8):
[MicrotextbookTheme.zip](https://github.com/zikula/core/files/72214/MicrotextbookTheme.zip)

**Comment by rallek** [comment]
I am not shure how to reproduce. But I run often in problems only clearing the cache by deleting /prod or /dev. This was different in 1.4.0. Might be it has to do with the new theme engine. Might be I am totally wrong. But this is my experience. I hope I can create a test case within the next days. I should have some free time than.

**Comment by craigh** [comment]
@rallek what are you talking about? A different issue? Please open a new ticket. This issue is polluted enough.

**Comment by rallek** [comment]
Sorry, I want not to confuse issues. I want to point to the idea of a bigger issue. There seams to be something wrong with caching at all. And yes, if I can bring a show case I will open a new ticket.

**Comment by craigh** [comment]
this has some similarity with #1424

**Comment by craigh** [comment]
More information:

 1. If `debug:true` then this behavior is not seen! From what I understand, symfony is hiding the fatal error in this case, but not sure.
 2. This behavior is not limited to themes. The same is true with modules.
   - set `debug:false`
   - activate a module (I tried SpecModule)
   - manually remove the module from the `/modules` directory
   - reload the modules list -> WSOD
   - (like `1` above, if `debug:true`, there is no WSOD but changes from #1424 take effect). 

So this is generally a problem with how symfony must rebuild the container and the fact that it is cached in certain config (e.g. `debug:false`). Modules and themes are symfony bundles and the state of the container cannot be changed by removing bundles without refreshing the cached container build.

One possible solution would be to somehow catch fatal errors and attempt to reload the container and then refresh the browser. I'm not sure this is even possible. (it is certainly *not* recommended - fatal errors should be, you know, *fatal*).

Another possible solution would be to check the contents of `/modules` and `/themes` on **every page load** and detect changes and refresh the container when needed. This seems like it would be a performance bottleneck and not a good solution either.

So the solution to this might only be documentation that you cannot remove bundles without refreshing the cache. This doesn't seem optimal.

**Comment by craigh** [comment]
Possible solution:

ship standard zikula with `debug:true` (currently `false`). This will force container rebuild on every page load. Document this and tell admins to set to `false` when their 'experimentation` is finished (e.g. 'production mode').

**Comment by craigh** [comment]
Possible solution:

ship standard zikula with `debug:true` (currently `false`). This will force container rebuild on every page load. Document this and tell admins to set to `false` when their 'experimentation` is finished (e.g. 'production mode').

@cmfcmf @Guite thoughts on this idea?

**Comment by cmfcmf** [comment]
> ship standard zikula with debug:true (currently false). This will force container rebuild on every page load. Document this and tell admins to set to false when their 'experimentation` is finished (e.g. 'production mode').

I don't think this can be a solution.

**Comment by pheski** [comment]
**IF** this is done, the bug/debug status needs to be wicked obvious (e.g., with an alert on the top of the admin panel) and ridiculously easy to toggle on and off (e.g., not requiring manually editing a file). Unless, Zikula wants to limit its customer base to a small niche of programmers and tech enthusiasts.

From a systems and user perspective, the right thing to do should always be the default. It should require extra effort to make a mistake.

Peter

**Comment by craigh** [comment]
So, I implemented a functionality very similar to the modules - a module should be "uninstalled" before removing the files. Now it is the same with themes. Also, themes are not immediately available upon placing the files into the directory, but must be "activated" first. Themes must be deactivated before removal.

This issue will not go away since there is simply no way to prevent an admin from removing the files without uninstalling the extension first. If they do that, they will get a WSOD and we will get a support ticket. Any other method of solving the problem brings new problems that we don't want.

**Comment by pheski** [comment]
Nice implementation.

Not sure best way to document/educate. In readme?  

P
