### ISSUE TITLE
Refactor MenuTree block

### ISSUE THREAD

**Issue by craigh** [zikula/core#2675]
refs #2674 

 - refactor block.menu.php plugin (leave for BC?)
 - MenutreeTree
 - MenutreeUtil
 - menutree plugin

**Comment by craigh** [comment]
refs #2031. we should probably fully replace Extmenu (and all menu blocks) with external libs.

**Comment by rallek** [comment]
I want to use menu tree block for my next site. Will menu tree still exist inside 1.4.x or will it disapear in favor of a better menu block system?

**Comment by craigh** [comment]
Current functionality will be maintained until Core-2.0. Newer/better menu systems may be introduced also but existing will continue in core-1.x

**Comment by Guite** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RwknNCNK&#x2F;2-menu-blocks-2031-2675-2676"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Menu blocks #2031 #2675 #2676</a>

**Comment by craigh** [comment]
Closing as This will NOT be done - MenuTree will not be updated.
