### ISSUE TITLE
Improve Travis Tests

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2679]
We can also check for syntax errors in Twig and YAML files, like done with the Media Module:

https://travis-ci.org/cmfcmf/MediaModule/jobs/96477115#L442-L447

**Comment by Guite** [comment]
Also we should maybe add PHP 7.

**Comment by cmfcmf** [comment]
PHP 7 is already added... But is still failing.

**Comment by Guite** [comment]
Is it covered by `nightly`? Would have expected something like `7.0`.

**Comment by craigh** [comment]
closed by #2032
