### ISSUE TITLE
add phpunit to require-dev

### ISSUE THREAD

**Issue by craigh** [zikula/core#2680]
Should we add phpunit to require-dev now that tests are included in the build process? It would simplify things for devs who don't have a workflow in place yet. As we work to improve the test/build workflow for the project, PRs will need to pass tests before being merged. While these will be built by travis and therefore they can be checked beforehand, a dev may need to run tests locally if they don't pass in order to know what to fix.

**Comment by cmfcmf** [comment]
I am :-1: because it adds substantially more overhead to composer update.

**Comment by craigh** [comment]
it seems that if we fixed phpunit to a specific version (e.g. 4.8.21 or something) then it would not add to the overhead because it would only happen once.

**Comment by cmfcmf** [comment]
Still, I'm not really in favour of it. Installing PHPUnit on your system isn't much work :-/

**Comment by craigh** [comment]
very well.
