### ISSUE TITLE
{% if pagetype == 'admin' %} in boostrap theme is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#2681]
There is a ``{% if pagetype == 'admin' %}`` in main_menu.html.twig what should make the following menu items appear only if you are at the admin pages. But they are shown allways, also at ``home``

**Comment by craigh** [comment]
probably not. are you assigning `pagetype`? yourself?

**Comment by rallek** [comment]
no, I am using the boostrap theme of 1.4.1 without changes

**Comment by craigh** [comment]
I can confirm this. not sure of a fix atm.
