### ISSUE TITLE
Hooks expect access via Version Class

### ISSUE THREAD

**Issue by craigh** [zikula/core#2682]
for example: https://github.com/zikula/core/blob/42c2b973187ccea6110886da18f9f659bcc6a19a/src/system/ExtensionsModule/Controller/AdminController.php#L1616-L1616

This is not possible for the Core-2.0 spec where there IS NO version file :frowning: 

I didn't see this before eliminating the Version class. Now we need a new solution.

also - \Zikula\ExtensionsModule\Util::getVersionMeta is passing back an array instead of an object for Core-2.0 spec modules. here: https://github.com/zikula/core/blob/1.4/src/system/ExtensionsModule/Util.php#L63

Looking for suggestions: @cmfcmf @Guite @Kaik

**Comment by Kaik** [comment]
We may need to refactor hooks to work with Core 2.0 spec and Utill class so it will pass array instead of a class for all cases OR create class to provide module composer.json data in a way hooks need it.

**Comment by Guite** [comment]
Can't this information be fetched from database instead of asking the Version class?

**Comment by craigh** [comment]
No - the required information include `title` and `category`. The `title` is only available in the class because it is a translated string.

**Comment by craigh** [comment]
also this: https://github.com/zikula/core/blob/fc1e5c954f9055e68dccb5476cbba4cb3ff4c331/src/system/ExtensionsModule/Api/AdminApi.php#L407-L408
