### ISSUE TITLE
Correct & Refactor LangBlock

### ISSUE THREAD

**Issue by craigh** [zikula/core#2684]
refactor to new standards and update to symfony methods.

refs https://github.com/zikula-modules/Pages/issues/50

refs http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html

**Comment by craigh** [comment]
PHP Version 5.5.14
Apache 2.4.16
OpenSuse distribution Leap 42.1 in Virtual Box

**Comment by craigh** [comment]
http://stackoverflow.com/questions/37250318/symfony-3-jmsi18nroutingbundle-set-locale

**Comment by Guite** [comment]
refs #3224

**Comment by craigh** [comment]
fixed in #3396
