### ISSUE TITLE
Drop Assetic

### ISSUE THREAD

**Issue by Guite** [zikula/core#2685]
Since we use zasset (which is built above the Symfony Asset component) we should remove Assetic from the core.

**Comment by craigh** [comment]
since it is currently included since 1.4.0 we should perhaps schedule removal for 2.0.0?

**Comment by Guite** [comment]
Wouldn't this lead to more people starting using it? I think at the moment nobody is using Assetic (yet), so it could be advantageous getting rid of it before it becomes adopted?

**Comment by craigh** [comment]
yes, that would be a concern, but we have much tech in the Core that is @deprecated. We leave it for BC. Of course there is no way to know that "nobody is using it" (until we remove and someone complains :wink: ).

**Comment by Guite** [comment]
Postponed issue to 2.0.0.

**Comment by craigh** [comment]
[here](https://github.com/symfony/symfony-standard/pull/860) is a conversation about removing ascetic from symfony-standard (which is not the same as 'symfony', apparently). just FTR
