### ISSUE TITLE
Add 'homepage' option to block filtering.

### ISSUE THREAD

**Issue by craigh** [zikula/core#2690]
somehow implement 'isHomepage' for block filtering - e.g. "I want a block to appear only on the homepage" (or never on the homepage, etc).

**Comment by rallek** [comment]
Great idea! I would like top extend the idea to the theme defined pages (default: home, master, admin). 

So a theme might define another page named "album", "shop" or "forum". In this case we can offer blocks for these pages as well.

Only as an idea

**Comment by pheski** [comment]
+1

And, if this is to be done with the 'Show/hide advanced placement options' in blocks, it should include either a pop-up with instructions, or a link to instructions on how to use the fields.  Please.

**Comment by craigh** [comment]
There is no "Show/hide..." after 1.4.2. Instructions are [here](https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Blocks.md#block-filters)

**Comment by pheski** [comment]
That looks good.  But it still leaves me struggling to have something ONLY on my Home page while I wait for 1.4.2. I'm sure there is a way to do it within the theme, but I'm not that level of coder and I go back to my day job (family doc) early tomorrow morning at which time I have much less time to play/learn.

**Comment by craigh** [comment]
in 1.3.x (and probably 1.4.0 and 1.4.1) it looks like you should use `_homepage_` as the module name in the filter settings. if that doesn't work, I haven't a clue.

**Comment by Kaik** [comment]
I don't understand it, really, some time ago(years) I have seen some very complicated theme-blocks settings. This had I think option you are talking about. What I do not understand is why not use block positions. For example all block positions on home page are with home_ prefix then you can use one block in home_center and center or only in center this way you can filter all blocks that are in positions with home_prefix - filter position select would need to be updated to multiple.
This way you can have fever blocks attached to more positions like home_ album_ master_ ... Maybe you have something different in mind.

**Comment by craigh** [comment]
This is actually currently possible (Core-1.4.2-dev) by adding a filter where `_zkModule` `==` empty

**Comment by craigh** [comment]
![screen shot 2015-12-22 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/350048/11962552/9cb35d00-a8ae-11e5-8565-08937cea4afc.png)

**Comment by cmfcmf** [comment]
> This is actually currently possible (Core-1.4.2-dev) by adding a filter where _zkModule == empty

really? Does this also work if you set module X as your startpage module in the settings?

**Comment by craigh** [comment]
haven't tested.

**Comment by pheski** [comment]
When the (holiday) dust settles, I'll make time to set up a couple local test environments so I can help by testing, since I can't help by coding.

**Comment by craigh** [comment]
> really? Does this also work if you set module X as your startpage module in the settings?

no. :disappointed:
