### ISSUE TITLE
Trouble clearing compiled templates and cache in Andreas08

### ISSUE THREAD

**Issue by pheski** [zikula/core#2692]
Here are the results when I try:

Delete compiled theme templates --  Error! Failed to clear theme engine compiled templates.
Delete compiled render templates  - works
Delete cached theme pages.  Error! Failed to clear theme engine cached templates.
Delete cached render pages - works

P

**Comment by craigh** [comment]
none of those caches matter. That's all Smarty stuff and Andreas08 is Twig-based now. I assume you are testing Core-1.4.x

**Comment by pheski** [comment]
Yes - 1.4.1, trying to figure it out.  Lot's of stuff has happened in the last 2 years! More powerful, but more complicated.

**Comment by craigh** [comment]
closing in favor of #2712 but maybe this is a non-fixer in the end anyway.
