### ISSUE TITLE
User settings changes crash site

### ISSUE THREAD

**Issue by pheski** [zikula/core#2696]
Using Zikula 1.4.1 and Andreas08, I changed User settings so that unverified email addresses would expire in 2 days. The default is 0.  I had a number of (spammy) users with unverified email addresses.

When I saved this change, I got a Server 500 error:

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'DELETE FROM users WHERE uid = ?' with params [3]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`pemdblog`.`users_attributes`, CONSTRAINT `FK_E6F031E4A76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`))") in "ZikulaAndreas08Theme:Include:header.html.twig" at line 15.

The fix was to go to the MySQL database and look at the user table and user_attributes table to identify the users with unverified email address (was pretty easy to tell), then remove them FIRST from user_attributes (they cannot be removed from the parent users table until removed from users_attributes) and then remove them from users.

Boom. Back in business.  But looks like a bug. Beyond my expertise, but sounds like changing that parameter either needs to fail gracefully ("No, I won't do this until you...") or do the task in the background. 

The same may apply to changing the password reset timelimit, though I have not checked that.

Don't know how to mark this ticket as a bug, so I put [Bug] in Subject line. Hope that is ok.

Peter

**Comment by craigh** [comment]
was this on a site that had been upgraded? what was the upgrade sequence? (e.g. 1.3.8 -> 1.4.1)

**Comment by pheski** [comment]
Not upgraded. My collection of sites had been in 1.2.8 land and I had been putting off upgrading, as other personal and family issues had priority. Then my ISP dropped support of PHP 5.3 and 5.4 (they warned me - I just was too busy to deal with it), so my 1.2.8 sites all died, without the ability to access the admin panel and do any upgrading.

Consequently I have harvested as much content as I can and this is a fresh 1.4.1 install with PHP 5.6.

P

**Comment by craigh** [comment]
I cannot view that link without logging in. so I tried to create an account, but apparently it is pending activation?

**Comment by pheski** [comment]
activated.

Here is the log file

in vendor/drak/smarty/Smarty/Smarty.class.php at line 1094   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
    function trigger_error($error_msg, $error_type = E_USER_WARNING)
    {
        $msg = htmlentities($error_msg);
        trigger_error("Smarty error: $msg", $error_type);
    }
at ErrorHandler ->handleError ('512', 'Smarty error: unable to read resource: &quot;master.tpl&quot;', '/home/mtkatahdin/petereliasmd.com/vendor/drak/smarty/Smarty/Smarty.class.php', '1094', array('error_msg' => 'unable to read resource: "master.tpl"', 'error_type' => '512', 'msg' => 'unable to read resource: &quot;master.tpl&quot;'))
at trigger_error ('Smarty error: unable to read resource: &quot;master.tpl&quot;', '512') 
in vendor/drak/smarty/Smarty/Smarty.class.php at line 1094   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Smarty ->trigger_error ('unable to read resource: "master.tpl"') 
in vendor/drak/smarty/Smarty/Smarty.class.php at line 1590   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Smarty ->_fetch_resource_info (array('resource_name' => 'master.tpl', 'get_source' => true, 'quiet' => false, 'source_content' => null, 'resource_timestamp' => null)) 
in vendor/drak/smarty/Smarty/Smarty.class.php at line 1416   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Smarty ->_compile_resource ('master.tpl', '/home/mtkatahdin/petereliasmd.com/app/cache/prod/ztemp/Theme_compiled/BlankTheme/Matheo/BlankTheme/master.php') 
in lib/legacy/Zikula/View.php at line 2969   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Zikula_View ->_fetch ('master.tpl', '783ed6aafa918ff83a203923303b649f', '', false) 
in lib/legacy/Zikula/View.php at line 772   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Zikula_View ->fetch ('master.tpl', '783ed6aafa918ff83a203923303b649f') 
in lib/legacy/Zikula/View/Theme.php at line 348   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Zikula_View_Theme ->themefooter (object(Response)) 
in lib/Zikula/Bundle/CoreBundle/EventListener/Theme/CreateThemedResponseListener.php at line 66   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at CreateThemedResponseListener ->createThemedResponse (object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
at call_user_func (array(object(CreateThemedResponseListener), 'createThemedResponse'), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php at line 61   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at WrappedListener ->__invoke (object(FilterResponseEvent), 'kernel.response', object(Zikula_EventManager))
at call_user_func (object(WrappedListener), object(FilterResponseEvent), 'kernel.response', object(Zikula_EventManager)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php at line 158   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at EventDispatcher ->doDispatch (array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php at line 46   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at EventDispatcher ->dispatch ('kernel.response', object(FilterResponseEvent), null) 
in lib/legacy/Zikula/EventManager.php at line 99   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Zikula_EventManager ->dispatch ('kernel.response', object(FilterResponseEvent)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php at line 124   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at TraceableEventDispatcher ->dispatch ('kernel.response', object(FilterResponseEvent)) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 179   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at HttpKernel ->filterResponse (object(Response), object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 123   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 62   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 184   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 25   <http://www.petereliasmd.com/index.php?theme=MatheoBlankTheme#>

**Comment by craigh** [comment]
like I did, you commented in the wrong ticket ;-)

I deleted mine and moved it.

**Comment by craigh** [comment]
> Consequently I have harvested as much content as I can and this is a fresh 1.4.1 install

> I had a number of (spammy) users with unverified email addresses.

I cannot reconcile the two statements above. How is it possible that you had a number of spammy unverified accounts if this is not an upgrade?

**Comment by craigh** [comment]
Additionally, are you using the Profile module? Else there are no user attributes, right? This could be a problem with Profile and not the core.

**Comment by pheski** [comment]
Bots registering with fake email addresses before I fixed some settings.

P

**Comment by pheski** [comment]
Nope - not using Profile.

Peter

**Comment by craigh** [comment]
I need to know the other settings you have for users, login, etc.

**Comment by pheski** [comment]
I had it set so that users who tried to register had to verify their email address (2 days) and were removed if they remained unregistered for 7 days. What (I think) was happening was that bots or people were trying to register with spoofed email addresses, which they obviously could not verify.  They stayed on the list unverified until 7 days and then, when Z tried to delete them, it caused a problem because it tried to delete the user while there was still information liked to the user in the user_attributes table.

I think that setting the ‘Registrations pending verification expire in…’ to 0 will keep Z from trying to delete them.

I also think that the coding for deleting a user needs to be tweaked so it checks for child tables and deletes the user there first.

*I think* is because I am speculating beyond my competence.

Peter

**Comment by craigh** [comment]
login settings?

**Comment by pheski** [comment]
OK:
register and login with email address
email address must be unique
PW minimum length 8
Email verification expires in 2 days
Password reset expires in 2 days
New user registration allowed
PW reminder enabled but not mandatory
Registration is moderated
Verify email address during registration - yes
Order of approval and registration - either (was verify, then approve)
Registrations pending verification expire in  - 0 ( was 4 weeks I think)

All the user login settings at the bottom are the defaults.

Did I miss anything you need?

Peter

**Comment by craigh** [comment]
I'm pretty sure I've fixed this. But of course, unless you apply this patch or use 1.4.2-dev (not recommended) you will not be able to realize the fix until 1.4.2 is released. :beer:

**Comment by pheski** [comment]
I continue to be confident that Zikula has a place in the world.  Thanks.

Peter

**Comment by pheski** [comment]
I know better than to use 1.4.2-dev, but I learned what happens if I get lazy and upload the 1.4.2-dev file that contains a few changed lines, instead of just changing the lines in question.

Not pretty, but easy to fix. And I'm just a smidgen smarter today than yesterday. :-)
