### ISSUE TITLE
search - internal server error

### ISSUE THREAD

**Issue by pheski** [zikula/core#2697]
searching in 1.4.1 gives: 

search_result_column is not an array
500 Internal Server Error - Exception

in lib/legacy/dbobject/DBUtil.php at line 704

 // build the column list
        $columnList = $tables["{$table}_column"];
        if (!is_array($columnList)) {
            throw new Exception(__f('%s_column is not an array', $table));
        }
        // build the column definition list

**Comment by craigh** [comment]
duplicate #2643
fixed in 1.4.2
