### ISSUE TITLE
[General] Doctrine Caching

### ISSUE THREAD

**Issue by craigh** [zikula/core#2699]
https://coderwall.com/p/ry1y0a/improve-doctrine-performance-up-to-100-on-your-symfony2-project

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/caching.html

http://doctrine-common.readthedocs.org/en/latest/reference/caching.html

> Doctrine provides cache drivers in the Common package for some of the most popular caching implementations such as APC, Memcache and Xcache. We also provide an ArrayCache driver which stores the data in a PHP array. Obviously, when using ArrayCache, the cache does not persist between requests, but this is useful for testing in a development environment.

Because doctrine caching is dependent on server environment, some inspection would need to be done during install and choices of cache type provided, etc. 

Additionally, some coding changes would need to take place to take advantage of the caching features.

**Comment by Guite** [comment]
https://symfony.com/doc/current/bundles/DoctrineCacheBundle/index.html

**Comment by Guite** [comment]
> https://symfony.com/doc/current/bundles/DoctrineCacheBundle/index.html

The core already includes and registers this bundle for asset caching.

**Comment by Guite** [comment]
Nothing we should care about on our side.
