### ISSUE TITLE
Category javascript files

### ISSUE THREAD

**Issue by paustian** [zikula/core#2702]
In the 1.4.1 build the categories js files categories_admin_edit.js and categories_admin_view.js are empty This is a fresh download of the zip file from the Zikula site. Putting back the text in the two files fixed the issue.

**Comment by craigh** [comment]
confirmed.

**Comment by craigh** [comment]
interestingly, the entire contents of the file is properly copied to `/web` so users in `env:prod` should be ok.

**Comment by craigh** [comment]
@Guite @cmfcmf would you please work on this? There are several errors in the build console related to the two files in question.

http://ci.zikula.org/job/Zikula_Core-1.4.2/24/console

**Comment by craigh** [comment]
@Guite The two files in this ticket are now present. there is an open ticket for the other missing file. should we close this one?

**Comment by craigh** [comment]
we need a changelog.
