### ISSUE TITLE
YUI Compressor error in Blocks module

### ISSUE THREAD

**Issue by Guite** [zikula/core#2707]
```
[ERROR] in /var/lib/jenkins/jobs/Zikula_Core-1.4.2/workspace/build/export/Zikula_Core-1.4.2/system/BlocksModule/Resources/public/js/contextmenu.js
  43:64:missing ; before statement
```

See here: https://github.com/zikula/core/blob/1.4/src/system/BlocksModule/Resources/public/js/contextmenu.js#L43

I do not really know how to fix this. It is probably related to the comment for conditional compilation.

**Comment by craigh** [comment]
Since we dropped support for ie6 some time ago, I think it is safe to delete it.

Is this why the `contextmenu.js` file is empty in the build?

I don't like how the compressor allows the build to complete with these errors.

**Comment by craigh** [comment]
fixed by https://github.com/zikula/core/commit/a6d3ccdde4905baad0e52a19ebd2f976130e39b0
