### ISSUE TITLE
Theme changes do not apply in 1.4.1

### ISSUE THREAD

**Issue by rallek** [zikula/core#2712]
I am not shure if it is a bug or not. For me it looks like one.

How to reproduce:
a fresh install of final zikula 1.4.0 and 1.4.1 without any modules or any other changes.
Now change the footer in Andreas08 theme. It is located in 1.4.0 in 
``Zikula_Core-1.4.0\themes\Zikula\Theme\Andreas08Theme\Resources\views\includes\footer.tpl`` 
and in 1.4.1 in 
``Zikula_Core-1.4.1\themes\Andreas08Theme\Resources\views\Include\footer.html.twig``
Change the line 2 in ``<p>{{ __('Powered by') }} <a href="http://zikula.org">Zikula</a> and me</p>`` (I added ``by me``)

Go to the site of 1.4.0 and refresh the browser chache. You will see the change directly. Do the same with the site of 1.4.1 and refresh the browser as well. You will see no changes.

The behavior is different at both installs.

Now I went to the theme settings and clicked the link ``Delete compiled theme templates``
In 1.4.0 I do get the message: ``Done! Deleted theme engine compiled templates.``
In 1.4.1 I do get the message: ``Error! Failed to clear theme engine compiled templates.``

I expected the same behavior.

Might be it is related to #2671

**Comment by craigh** [comment]
this is not related to #2671. It is related to #2692. But it isn't really a bug. You are manually changing a theme, but the cached template is not changed. The theme settings are not Twig based - only smarty based and so don't do anything for Twig based themes.

I'm not sure we want to maintain the same behavior for twig-based themes.

If you change `debug` to `true` in `custom_parameters.yml` then templates will be updated each page load. (i.e. you will see your changes).

**Comment by cmfcmf** [comment]
> In 1.4.1 I do get the message: Error! Failed to clear theme engine compiled templates.

@craigh Indeed, but this error should at least be silenced / smarty settings be removed.

**Comment by rallek** [comment]
Thanks! ``debug`` is ``true`` now and that is doing what I need.

so ``Force re-compilation of theme templates`` is also smarty and do not work anymore. Could be nice to have this behavior also for twig based templates.

**Comment by craigh** [comment]
> Could be nice to have this behavior also for twig based templates.

I'm not sure I agree, and IMO this is really the question of this ticket which is why I leave it open.

**Comment by craigh** [comment]
> Indeed, but this error should at least be silenced / smarty settings be removed.

it is accurate. The templates are indeed **not** cleared. So, I'm not sure it should be "silenced" but better documentation is certainly warranted. As we transition from smarty to twig we will have various changes of methods and paradigm shifts that will need to take place.

**Comment by rallek** [comment]
I now have learned how to do. But a lot of other Zikula users might expect this behavior. Not all of them are aware of these big changes.
an inline comment with this information might be also aplicable.
