### ISSUE TITLE
Reconsider cookie setting for improved security

### ISSUE THREAD

**Issue by Guite** [zikula/core#2716]
We have set `framework.session.cookie_httponly` to `false` in https://github.com/zikula/core/blob/fbf3b6e088cf0c5c115ce60d3938a12b329822a3/src/app/config/config.yml#L29

The new default value is `true` which improves security.
https://github.com/symfony/symfony/blob/v2.8.0/UPGRADE-2.8.md#frameworkbundle

**Comment by craigh** [comment]
I believe @cmfcmf set it this way for BC reasons. We can probably return to default (true) for 2.0

**Comment by cmfcmf** [comment]
> I believe @cmfcmf set it this way for BC reasons. We can probably return to default (true) for 2.0

Yes.

**Comment by Guite** [comment]
Fixed in c58ab46764688b6a732eb1cb95377d160529fe61

**Comment by craigh** [comment]
changelog?

**Comment by Guite** [comment]
added in 0c3449efbb0af7c0e1221582e4a81d8e89694e56

**Comment by Guite** [comment]
Fixed ugly typo in d1ffd91a984cadaac4bb955b40c1cdbd517457a9
