### ISSUE TITLE
Wrong field type for block position description

### ISSUE THREAD

**Issue by Guite** [zikula/core#2725]
The description field for a block position has been a textarea. It's form type uses a text field instead.

https://github.com/zikula/core/blob/1.4/src/system/BlocksModule/Form/Type/BlockPositionType.php#L27

@craigh is this on purpose?

**Comment by craigh** [comment]
I changed it on purpose. the DB column is only 255 length anyway. the description can't be too long and is only used in the admin list.

**Comment by Guite** [comment]
Okay.
