### ISSUE TITLE
Login block not functional always

### ISSUE THREAD

**Issue by rallek** [zikula/core#2729]
I have thought in the past I did type in a wrong password sometimes. But now I can confirm my observation.

I do have a naked 1.4.1 install. I am logged in. Now I log out. So far so good. I am on home. The login block is visible. I try to login with the admin account again. Login failed. I am forwared to the login page.

Next I go back to home. Login again with the admin. And now it works. I am logged in. I repeated this ten times. Always the same behavior. I can guarntee I do not type in my passwort five times wrong :-)

I also checked this behavior with the 1.4.2 ci build 48 from today. Same thing. It is also theme independant (same behavior with bootstrap theme)

What should be the expacted behavior after installing the core? Today I was always leaded to the login page with the hint my password or user has been incorrect. In former times the admin was logged in directly. Might be it is the same reason.

**Comment by craigh** [comment]
The problem is with the StripFrontControllerListener

**Comment by craigh** [comment]
Issue fixed. So you know, I *also* thought I was crazy for a while... re-entering my password each time thinking I had mistyped it. Eventually I knew there was a bug but neglected to report it. Thanks for testing/helping.

**Comment by cmfcmf** [comment]
Oh wow. Finally. I also always had this issue but neglected to report it aswell. Good fix!
