### ISSUE TITLE
Startpage + shorturls don't work if "Prepend language to URL" = always

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2732]
I have a single language installed (English) and set "Prepend language to URL" to "always" at http://localhost/~christian/zk-dev/src/settings/admin/multilingual

ShortURLs are enabled:
1. The / is 404. It should redirect to /en
2. The link to the News admin interface in the adminpanel points to http://localhost/~christian/zk-dev/src/index.php?module=news&type=admin&func=index&lang=en -> Frontcontroller is stripped -> http://localhost/~christian/zk-dev/src/?module=news&type=admin&func=index&lang=en -> 404
3. The "Submit an article" link from the user account page works: http://localhost/~christian/zk-dev/src/en/news/newitem

**Comment by craigh** [comment]
Can you fix it?

**Comment by craigh** [comment]
I get a 500 error for `/` not 404

**Comment by craigh** [comment]
how do you feel about just setting the `i18n: false` for the home route?

**Comment by craigh** [comment]
probably also for the legacy (non-shorturl) controller.

**Comment by cmfcmf** [comment]
Worth a try +1

Craig Heydenburg <notifications@github.com> schrieb am Mo., 11. Jan. 2016
21:21:

**Comment by craigh** [comment]
The issues you raised in the ticket are fixed, but there are MANY other links being generated that go 500. We must have some url generators that do not properly accommodate this setting.

**Comment by craigh** [comment]
after some further testing I believe this is fixed.
