### ISSUE TITLE
Upgrade from 1.3.5 to 1.4.1 refuses to start and insists on install

### ISSUE THREAD

**Issue by paustian** [zikula/core#2733]
The upgrade was not beginning even though the 1.3.5 build is supposed to be able to be upgraded to 1.4.1. I tracked down the bug and I think I have a fix.
In the UpgradeCommand.php file at lib/Zikula/Bundle/CoreInstallerBundle/Command/UpgradeCommand.php
Line 70. It is comparing the current installed version to the minimum upgrade version. The minimum version is stated as 1.3.5, but it is using a < sign. 

​[10:15] 
In UpgradeController. If you are at 1.3.5, the upgrade will not start. This can be fixed by changing the minimum version to 1.3.4. Then it all works.

**Comment by craigh** [comment]
This is not a bug. The upgrader **should** only work if the Core is at 1.3.6 or higher (e.g. > 1.3.5)
