### ISSUE TITLE
CI build broken

### ISSUE THREAD

**Issue by Guite** [zikula/core#2740]
```
 [RuntimeException]                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:          
                                                                                     
    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "delivery_address" under "swiftmailer.mailers.default"       
```

Possibly related to Symfony 2.8.2...

**Comment by craigh** [comment]
has to be. was the only change

**Comment by craigh** [comment]
swiftmailer bundle changed from 2.3.9 to 2.3.10 in Sy2.8.2

**Comment by craigh** [comment]
probably related to https://github.com/symfony/swiftmailer-bundle/commit/9968c18dc78113bbacd5b029e92a31fac402c0d8

**Comment by mefiblogger** [comment]
We also have this error during Jenkins build:

```[exec] 
     [exec] 
     [exec]                                                                                  
     [exec]   [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
     [exec]   Unrecognized option "delivery_address" under "swiftmailer.mailers.default"     
     [exec]                                                                                  
     [exec] 
     [exec] 
     [exec] Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
     [exec]```

**Comment by craigh** [comment]
@mefiblogger recommend you add your comment to https://github.com/symfony/swiftmailer-bundle/issues/129

**Comment by craigh** [comment]
I [forced swift mailer bundle back to 2.3.9](https://github.com/zikula/core/commit/6ba7cee13cc236a4914c647966d0f20679c3ae56) in order to allow builds to succeed again.

**Comment by craigh** [comment]
build [620](http://ci.zikula.org/job/Zikula_Core-1.4.2/62/) is successful. leave this ticket open however so we can revert the [setting I changed](https://github.com/zikula/core/commit/6ba7cee13cc236a4914c647966d0f20679c3ae56) when the vendor is repaired.

**Comment by mefiblogger** [comment]
@craigh thx!

**Comment by Guite** [comment]
Fixed by 9b13f7cbae5c30d7b56b28708fd0a406e80eb0c3
Build 63 was successful.

**Comment by craigh** [comment]
@Guite:

just ran your upgrade locally.

after upgrade this is the value:

`    delivery_addresses: {  }`

is this correct?

**Comment by Guite** [comment]
Yes, this looks not wrong.
See http://symfony.com/doc/current/components/yaml/yaml_format.html#collections

**Comment by craigh** [comment]
if `{ }` is correct why is the default value `[ ]` ?

**Comment by Guite** [comment]
The better question is why YamlDumper creates `{ }` instead of `[ ]` for an empty array. But both seem valid collections.

**Comment by craigh** [comment]
you can see what is used here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Inline.php#L169-L192

**Comment by Guite** [comment]
See https://github.com/symfony/symfony/issues/16266

**Comment by craigh** [comment]
and https://github.com/symfony/symfony/pull/16267

it looks like it may not be pulled. maybe you can adjust your code and account for an empty result.

**Comment by Guite** [comment]
Sorry I don't understand. What do I need to adjust?

**Comment by craigh** [comment]
on the upgrade, test if the value is null and simply write a `[ ]` instead of dumping.

**Comment by Guite** [comment]
Wouldn't that make the code unnecessarily complex? Because I would have to open and write the file manually...
