### ISSUE TITLE
Twig template overriding in themes

### ISSUE THREAD

**Issue by Guite** [zikula/core#2743]
Symfony allows overriding bundle templates in the `app` folder, like described at http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates
We need this on theme-level also.

**Comment by Guite** [comment]
Slightly related: https://github.com/symfony/symfony/issues/17407

**Comment by craigh** [comment]
this is already implemented.

**Comment by craigh** [comment]
https://github.com/zikula/SpecTheme/blob/master/Resources/README.md

**Comment by craigh** [comment]
you mean block overriding.

**Comment by Guite** [comment]
No I mean template overriding. But I did not test with the FQ module name, maybe this was the reason why it did not work.

**Comment by Guite** [comment]
Works.
