### ISSUE TITLE
Problem with Installing Zikula 1.4.2

### ISSUE THREAD

**Issue by shefik** [zikula/core#2744]
After installing Zikula 1.4.2 build 68, it appears to go through the installation process successfully. When I click the "Finish" button, I expect be redirected to the login form. Instead, I just get sent back to `/install`, where the page says again `ZIKULA CORE IS NOT INSTALLED!`. However, the tables were installed in the database.

When I proceed to click the button to install again, it redirects to `/install/locale`, and the message on-screen says `ZIKULA CORE IS ALREADY INSTALLED!`. However, that particular page is wrapped in the theme, and the layout is broken. See attached screenshot.

![voila_capture 2016-1-17_01-50-17_pm](https://cloud.githubusercontent.com/assets/274862/12379113/48e342bc-bd21-11e5-92e7-f5b2a3b10fc7.png)

**Comment by craigh** [comment]
I just installed build 68 with no problem. I am installing into a subdirectory (`localhost/142`). Are you?

**Comment by shefik** [comment]
No, I am not installing into a subdirectory.

**Comment by shefik** [comment]
Previously, the last build I attempted to install was 62, and that was successful.

**Comment by craigh** [comment]
will you attempt to install into a subdirectory and see if you have the same problem?

**Comment by craigh** [comment]
also please check your php log for relevant errors.

**Comment by craigh** [comment]
ping @shefik

**Comment by craigh** [comment]
Ping @shefik

**Comment by rallek** [comment]
I installed build 88 in a root directory without this problem.
