### ISSUE TITLE
ci build 88 centerblock broken

### ISSUE THREAD

**Issue by rallek** [zikula/core#2754]
````
An exception has been thrown during the rendering of a template ("Warning: Illegal string offset 'bid'") in ZikulaAndreas08Theme:Body:3col_w_centerblock.html.twig at line 6.
500 Internal Server Error - Twig_Error_Runtime
1 linked Exception:

    ContextErrorException »

````
A fresh install. No extension added, no theme changed, nothing configured. Opened the home in a second browser window is sowing the error above.

Changing from ``3col_w_centerbock`` to ``2col_w_centerblock`` do have the same. Changing the home template to one setting without center block makes the error disappearing (Theme settings for Andreas08)

same at boostrap theme

So my conclusion: something is breaking the centerblock

**Comment by craigh** [comment]
please try again.
