### ISSUE TITLE
minor warning from composer

### ISSUE THREAD

**Issue by craigh** [zikula/core#2755]
when running `composer update` I now get this warning:

> The "composer/installers" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by Guite** [comment]
This has been fixed in https://github.com/composer/installers/releases/tag/v1.0.23 see https://github.com/composer/installers/commit/6213d900e92647831f7a406d5c530ea1f3d4360e
