### ISSUE TITLE
UserUtil::getTheme() is unable to calculate theme name

### ISSUE THREAD

**Issue by shefik** [zikula/core#2768]
After installing Zikula 1.4.2 build 103, the following error is thrown at `/install/complete`:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'UserUtil::getTheme() is unable to calculate theme name.' in /lib/util/UserUtil.php on line 1983
```

**Comment by shefik** [comment]
The problem is in $themeinfo, `state` is set as `2`, when the conditional statement checks for `1` (ThemeUtil::STATE_ACTIVE).

**Comment by craigh** [comment]
This is because of recent changes to the Theme module where themes are not made active by default, but inactive.
