### ISSUE TITLE
Hooks admin menu item is missing

### ISSUE THREAD

**Issue by shefik** [zikula/core#2770]
The Hooks admin menu item is missing. Previously, it was a menu item that was added automatically to every module.

**Comment by craigh** [comment]
works for me.

![screen shot 2016-02-13 at 8 22 42 am](https://cloud.githubusercontent.com/assets/350048/13027793/fd22d422-d22a-11e5-8710-4430602b29bb.png)

**Comment by craigh** [comment]
Even on brand new install:
![screen shot 2016-02-13 at 8 31 40 am](https://cloud.githubusercontent.com/assets/350048/13027839/3eca8324-d22c-11e5-9681-48b49b6a038d.png)

**Comment by craigh** [comment]
> automatically to every module.

It is *not* automatically added to *every* module. Only to modules indicating they are hook subscribers or providers.

**Comment by craigh** [comment]
ping @shefik

**Comment by craigh** [comment]
reopen if you can confirm.
