### ISSUE TITLE
[General] Consider SymfonyBundleDependencies

### ISSUE THREAD

**Issue by craigh** [zikula/core#2771]
possible solution to the sub-dependency problem.

https://github.com/mmoreram/symfony-bundle-dependencies

@cmfcmf @Guite

**Comment by craigh** [comment]
https://blog.fervo.se/blog/2016/02/07/bundle-deps/

http://mmoreram.com/blog/2016/02/09/you-probably-need-bundle-dependencies/

**Comment by craigh** [comment]
The library references in the OP is now Symfony 3.2+ and php 7.1+ which puts it outside our version requirements so moving this to 2.1.0 only as a reference. perhaps we can use the OP bundle rec and a guide for creating something like this on our own either in 2.1.0 or later using this in 3.0.0

**Comment by craigh** [comment]
https://medium.com/@fabpot/fabien-potencier-4574622d6a7e

**Comment by Guite** [comment]
Moving to 3.0.0 again. @craigh something we should talk about in Slack.

**Comment by Guite** [comment]
could be interesting if modules require native Symfony bundles, since we do not use flex
to be looked at together with #3438

**Comment by Guite** [comment]
Closing as module dependencies will be replaced entirely by composer and Flex.
