### ISSUE TITLE
Smarty-based themes are no longer working under Zikula 1.4.2

### ISSUE THREAD

**Issue by shefik** [zikula/core#2777]
Smarty-based themes are no longer working under Zikula 1.4.2. They worked fine under Zikula 1.4.1.

Only Twig-based themes are currently working under Zikula 1.4.2.

**Comment by craigh** [comment]
I am not able to confirm this problem. Could you be specific on "no longer working"? I have a "legacy" version of SeaBreeze that I use for testing (from 1.4.0 I think) and it works fine.

**Comment by shefik** [comment]
@craigh I'll check if I can replicate the bug again on my end.

**Comment by craigh** [comment]
I downloaded all the themes from zikulathemes which includes this **Aqueous** Theme. I activated it and it worked fine. I'm actually sort of surprised it worked that well ;-)
![screen shot 2016-02-18 at 3 35 22 pm](https://cloud.githubusercontent.com/assets/350048/13157333/4795bf32-d655-11e5-8f59-1c5f69fbe4d1.png)

**Comment by shefik** [comment]
@craigh Just curious, did you try clicking around to internal pages? The problem I experienced occurred where the homepage always loaded fine. However, any internal page always loaded the home template, rather than the expected master one. Note that I was using a custom theme, not from core.

As I mentioned to you earlier on Slack, instead of troubleshooting further, I just went ahead and converted the them to Twig, since I figured I would eventually need to do that at some point. Only downside is that not all Smarty plugins are ported to Twig plugins yet.

I will need to test again, by trying another Smarty custom theme I have, to see if the issue persists.

**Comment by craigh** [comment]
Added some potential fixes. there is still some issue with the stylesheet that I cannot solve. perhaps you can give it a shot. 

you can try any theme from https://github.com/zikula/themes/ but not all have `admin.ini` files, so be sure to choose one of those.
