### ISSUE TITLE
Standardize phpdoc header blocks and let StyleCI do the work

### ISSUE THREAD

**Issue by craigh** [zikula/core#2781]
We should standardize the doc block header in php files (probably in other types also) and then let StyleCI take care of it for us. Also we should consider removing the copyright year so that remains consistent.

for example, this is symfony's header:

    /*
     * This file is part of the Symfony package.
     *
     * (c) Fabien Potencier <fabien@symfony.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */

**Comment by cmfcmf** [comment]
Also see https://github.com/zikula/core/wiki/Coding-Standards.

**Comment by Guite** [comment]
I think I've done this in #2868 - reopen if you disagree.

**Comment by craigh** [comment]
we just need to add it to StyleCI then I guess. @cmfcmf ?

**Comment by Guite** [comment]
Oh yes, indeed.

**Comment by cmfcmf** [comment]
It doesn't seem to be possible to use StyleCI for the task, because it requires a `/**` instead of `/*`: https://styleci.io/analyses/qyrEbj

**Comment by craigh** [comment]
would you consider contacting the StyleCI developer and asking about it?

**Comment by craigh** [comment]
@GrahamCampbell is there any way to configure StyleCI to allow `/**` instead of `/*` in file docblocks?

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell is there any way to configure StyleCI to allow /** instead of /* in file docblocks?

No, sorry.

**Comment by GrahamCampbell** [comment]
Using `/**` isn't allowed at file level because it doesn't document a "structural element".

**Comment by craigh** [comment]
@cmfcmf  I removed the header from StyleCI settings until we can handle this properly.

**Comment by craigh** [comment]
this was completed in https://github.com/zikula/core/commit/ce9260a54d368a13351dc9a915f36313ef2df7c7 and https://github.com/zikula/core/commit/1eb9e37e90f6a5442dd067fc9f5ec28f166167cf

**Comment by craigh** [comment]
note to @Guite @cmfcmf @Kaik and any other developer that may contribute any new PHP file. Please adjust your PhpStorm to auto-create the proper header as adjusted in https://github.com/zikula/core/commit/ce9260a54d368a13351dc9a915f36313ef2df7c7.
