### ISSUE TITLE
non-persisted hook event handlers?

### ISSUE THREAD

**Issue by craigh** [zikula/core#2784]
See if there is a way to leverage the ContainerBuilder to collect hook event handlers instead of storing them in the DB.

bindings and other dynamic information will continue to need to be persisted, but perhaps the event handler and definition could be coded into the Container.

**Comment by craigh** [comment]
refs #2262

**Comment by craigh** [comment]
refs #236

**Comment by Guite** [comment]
Fixed by #3618
