### ISSUE TITLE
Make installer/Upgrader more event driven?

### ISSUE THREAD

**Issue by craigh** [zikula/core#2785]
Consider using events to drive both the installer and upgrader. This would allow other entities to more easily 'hook' into the process as needed.

**Comment by Guite** [comment]
Could imho also be done after 2.0

**Comment by Guite** [comment]
Do we really need this? Can you provide any possible use case?

**Comment by craigh** [comment]
> Can you provide any possible use case?

if a true 'distribution' was published, events would allow extensions to be installed at the same time as the core, providing a better 'out the box' experience.

In an upgrade, events may be able to be used to drive the upgrade instead of the current method (which I think is now different than when I wrote this ticket too). This would also allow the upgrader to operate on other (unknown) things provided by extensions...

**Comment by Guite** [comment]
Fixed by #3618
