### ISSUE TITLE
implement CompilerPassInterface 

### ISSUE THREAD

**Issue by craigh** [zikula/core#2790]
> In Symfony 2.8, this code is no longer needed because if your extensions implement CompilerPassInterface they will be automatically registered and the process() method will be executed during the container compilation.

http://symfony.com/blog/new-in-symfony-2-8-dependencyinjection-improvements#simplified-registering-of-compiler-passes

**Comment by craigh** [comment]
The #2808 PR was merged and then reverted so this ticket is still open.

**Comment by Guite** [comment]
I've added some cleanup in #3150 

Beside this I can not get `LinkContainerPass` (and others) to work. Also I can't find anything about the improvement linked in the original description above in the docs: http://symfony.com/doc/current/components/dependency_injection/compilation.html

Thus I propose to close #2790 as won't fix.

**Comment by craigh** [comment]
http://symfony.com/doc/2.8/components/dependency_injection/compilation.html#execute-code-during-compilation

the blue note below the first code block says
> Prior to Symfony 2.8, extensions implementing CompilerPassInterface were not automatically registered. You needed to register them as explained in the next section.

that is the issue in this ticket.

I am ok with the postponement. I'm not sure I agree with all this auto-wiring, auto-execution anyway. We should look carefully at this before proceeding.

**Comment by Guite** [comment]
Moved to 2.0.0-beta1

**Comment by craigh** [comment]
I don't think we will implement this.
