### ISSUE TITLE
Does the Permission API use the wrong constant for "unregistered user"?

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2800]
https://github.com/zikula/core/blob/ef0338c5ebe24a57c31c6673ecf178d54c3ecdfd/src/system/PermissionsModule/Api/PermissionApi.php#L39

The ID of the unregistered user is set to `0`, although the `guest` user in the users table has the id `1`. This is the cause for https://github.com/cmfcmf/MediaModule/issues/58#issuecomment-186869135 @rallek.

**Comment by craigh** [comment]
In my view this is a result of confusion over the years of which value to use for an unregistered user (`0` or `1`).  you even made a change with this [rather recently](https://github.com/zikula/core/commit/add92b1b0a3b874cdfacee7ffeef39367beb4a96) but it is not clear which answer is correct over time.

the users module sets up `1` here: https://github.com/zikula/core/blob/7fee79e4184e1d61c62b080699aa92df960ba604/src/system/UsersModule/UsersModuleInstaller.php#L198

but the old SecurityUtil check for `0` here: https://github.com/zikula/core/blob/d493b257ce5af781ffe2eb0c3fb72a3ed7387380/src/lib/util/SecurityUtil.php#L306-L306

UserUtil checks for `0` here: https://github.com/zikula/core/blob/c5f60d2c2fa99686d483b992c76dc0252056dba2/src/lib/util/UserUtil.php#L2131-L2131

so it is a mess (I'm sure I missed many other instances).

**Comment by craigh** [comment]
ping @cmfcmf thoughts?

**Comment by craigh** [comment]
ping @Guite @cmfcmf this needs to be addressed before 1.4.2 release which means today please. what do we do?

**Comment by Guite** [comment]
How about checking for greater than 1?

**Comment by craigh** [comment]
that would need to be accomplished in modules that are looking for the guest user. that wouldn't a core solution imo. probably not the best solution?

**Comment by Guite** [comment]
I meant changing checks inside the core. Modules should be using `UserUtil::isGuestUser()`. But at least such a change would make the core consistent with regards to how it checks for guest/non-guest users.

**Comment by craigh** [comment]
can you look into it?

**Comment by Guite** [comment]
Not for 1.4.2.

**Comment by craigh** [comment]
@cmfcmf ?

**Comment by craigh** [comment]
for the record:

    /**
     * Determine if the current session is that of an anonymous user.
     *
     * @return boolean
     */
    public static function isGuestUser()
    {
        return !SessionUtil::getVar('uid', 0);
    }

so if there is no session var `uid` then this assumes `0` and returns `!0` or `true` I think. I know that somewhere there is a setting to have anonymous users utilize sessions so in that case I don't know what value it writes as a session var.

**Comment by Guite** [comment]
The `uid` in the session seems to default to `0`: https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Session/LegacyHandler.php#L77

**Comment by cmfcmf** [comment]
> ping @cmfcmf thoughts?

I am unsure what to do here. I am also hesitant to tinker with the legacy session and user management.

**Comment by craigh** [comment]
to start I think we need to clarify what types of users exist and in what context

so clearly there are normal **users** by which I mean any user that can login (this would include any admin user). When a user logs in, the session is [updated](https://github.com/zikula/core/blob/ce9260a54d368a13351dc9a915f36313ef2df7c7/src/system/UsersModule/Helper/AccessHelper.php#L116-L116) with an attribute of the `uid`

then there are **non-users** meaning **not logged in** visitors to the website. The behavior of sessions for these users is supposed to be controlled by the 'anonymoussessions' system var. At this point, _I am not sure this is actually happening._

For these _non-users_, sessions are used if `anonymoussessions` = `true`. Currently, the `uid` in the `session_info` table is set to `0` for these users. if `anonymoussessions` = `false` what should happen?

Also - with regard to sessions, I need help understanding the relationship with cookies and sessions. I also need a primer on sessions in general probably.

notes:
 - it appears that **two** rows are added to the `session_info` table for one page load.
 - #2001 shows non-db sessions no longer work. Seems like they should?
 - installation has problems with sessions in general.

**Comment by Kaik** [comment]
A few weeks ago I was recreating Zikula session table on plain Symfony I wanted to see how things work and differences. 

Because HTTP is stateless and websites need states there is cookie information on client and session information on server (It can be any kind of session information file, database etc..) This comes from PHP by default it uses files to store session information by default. You can override PHP sessions default behaviour and use it to store session into database.  

https://github.com/zikula/core/blob/1.4/src/app/config/config.yml#L25
https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Session/Storage/Legacy.php and https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Session/LegacyHandler.php

**Comment by craigh** [comment]
I guess I have derailed this ticket. but the conversations need to happen so better here than nowhere (or slack).

according to #2001 storing data in a server file doesn't work in our implementation.

**Comment by Kaik** [comment]
Yes, storing session is fixed to db. We would need to have create our own session storage handler to read the session storage setting and basing on this save it to a file or to a db.
https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Session/LegacyHandler.php#L91

>I guess I have derailed this ticket. but the conversations need to happen so better here than nowhere (or slack).

Yes but I think would be better to create separate ticket for session and leave this one for users which is  problem as well and need to be solved.

**Comment by Guite** [comment]
Also review CurrentUserApi with regards to calls for guests afterwards.

**Comment by Guite** [comment]
Also caused by this: https://github.com/Guite/MostGenerator/issues/936

**Comment by craigh** [comment]
according to http://symfony.com/doc/current/session/avoid_session_start.html it is **difficult** (at best) to avoid using sessions completely. IMO this is not a battle worth fighting within our codebase unless there is some EU privacy law that requires anonymous browsing.

so old versions of Zikula allowed three types of users:
 - anonymous (no session, `uid = 0`)
 - guest (has session, `uid = 1`)
 - standard user/admin (has session, `uid > 1`)

I don't think anonymous is an option, so we will go forward with only two user types:
 - guest (has session, `uid = 1`)
 - standard user/admin (has session, `uid > 1`)
