### ISSUE TITLE
composer installs assets twice because of custom command

### ISSUE THREAD

**Issue by craigh** [zikula/core#2801]
![screen shot 2016-03-11 at 5 42 29 pm](https://cloud.githubusercontent.com/assets/350048/13717629/b7b5f46e-e7b0-11e5-8cb4-6723a7805cdd.png)

I suspect we are loading the bundles into the kernel twice somehow?

**Comment by craigh** [comment]
This is due to the upgrade from Symfony 2.8.2 -> 2.8.3

build immediately before upgrade to 2.8.3: https://s3.amazonaws.com/archive.travis-ci.org/jobs/112315905/log.txt (or https://s3.amazonaws.com/archive.travis-ci.org/jobs/111736714/log.txt for the 1.4 branch)

build on the change to 2.8.3 https://s3.amazonaws.com/archive.travis-ci.org/jobs/112517095/log.txt

@Guite

**Comment by craigh** [comment]
so - turns our we are overriding the `assets:install` command. I don't know why.

If I delete the custom command and utilize the standard one, I get this:

![screen shot 2016-03-12 at 1 58 09 pm](https://cloud.githubusercontent.com/assets/350048/13724648/82e0dab0-e85a-11e5-8465-c99e02196577.png)

**Comment by craigh** [comment]
This seems right to me, so I am wondering why we have a custom command. Drak wrote it and I cannot tag him. @Guite @cmfcmf any ideas?

**Comment by craigh** [comment]
here is [our custom assets:install command](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Command/AssetsInstallCommand.php)

and [Symfony's command](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php)

**Comment by Guite** [comment]
I think the custom command exists to search also assets in modules and themes directories.

**Comment by craigh** [comment]
that appears to not be necessary as you can plainly see the themes and modules are shown in the pic above. The assets are not loaded by directory but by registered bundles in the kernel.

**Comment by craigh** [comment]
maybe i misunderstood your point.

It appears that the original command stores all the assets in `/web/bundles` and the custom stores in `/web/modules`, `/web/themes` and `/web/bundles`

so this is the difference. I wonder if this matters.

**Comment by craigh** [comment]
so, if we were to eliminate our own customized command, it would be a BC break but it may not matter much. As far as I can see, there is no automated method in ZIkula or Symfony that _chooses_ a `/web/module` path instead of `/modules/Resources/<asset_type>` path (if the former is available). *OR* (for that matter) a `/web/bundles` path. Apparently, these must be manually chosen, _or_ through the use of `{{ asset() }}` vs `{{ zasset() }}`.

Since the choice is of the developer, and there are very few modules in the wild using Core-2.0 tech so far, it may not matter.

I really don't know what to do here. one thing to consider is probably changing `zasset` to use a `/web` path if it exists. but I'm not sure. When I revamped the asset system a few months ago, I thought I covered that, but I guess I put it off.

**Comment by Guite** [comment]
In general I think it is very recommendable to remove the custom command.

How about naming collisions? If you have a `SomevendorFoo` module as well as a `SomevendorFoo` theme they would go into the same `/web` subfolder. Maybe it would make sense to have `/web/bundles/zikulablocksmodule` instead of `/web/modules/zikulablocks`. This way we could go without the custom directories, right?

**Comment by craigh** [comment]
Drak emailed me to say that the name conflict was the issue he might have been attempting to solve.

both your solution (custom name) and the current solution (custom directories) would require a custom command.

**Comment by craigh** [comment]
This is solved by https://github.com/zikula/core/commit/585ce3960e37a446e54a76c90b6b7b935bba9760 because the problem is that the kernel is booted more than once. Since this started in Sy2.8.3, I suspect some change in behavior at the kernel level starting at this point in Symfony.

I think we should consider other ways to eliminate the custom asset installer, so leaving this open for that discussion.

**Comment by Kaik** [comment]
This may affect me because I might have already theme name similar to module name but I think it is wrong. Both themes and modules are bundles for Symfony and this may cause problems in the future we should stick as much as we can to Symfony standard.

I do not think that restricting theme name not to be the same as module name for the same vendor, will be a problem. So I think we should remove custom command.

**Comment by Guite** [comment]
To avoid naming conflicts we need to prepend or append the bundle type somehow. So I think we won't get rid of the custom command. If you agree, please close this issue.
