### ISSUE TITLE
Unable to find template "ZikulaThemeModule:Theme:setAsDefault.html.twig".

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2805]
Error occurs when I tried to change default theme to Bootstrap.
Error is due to template name which is lower case here https://github.com/zikula/core/blob/1.4/src/system/ThemeModule/Resources/views/Theme/setasdefault.html.twig and template annotation here which is camel case https://github.com/zikula/core/blob/1.4/src/system/ThemeModule/Controller/ThemeController.php#L99

I think the easiest way of fixing it would be changing template name to camel case.

**Comment by Kaik** [comment]
Seems like this bug is in extensions as well. I will check where else.

**Comment by craigh** [comment]
Probably my Mac ignoring file casing
