### ISSUE TITLE
Flash messages not reliably shown in legacy smarty templates

### ISSUE THREAD

**Issue by craigh** [zikula/core#2822]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6ish

### Expected behavior

Flash message shown after installation is complete ("Congratulations! Zikula has been successfully installed.")

### Actual behavior

Is not seen on first page (/adminpanel/panel) but is shown when navigating to second page (/extensions/modules/list)

### Steps to reproduce

1. install core
2. note missing flash message

refs #2187 (which works for me)

ping @Kaik 

I'm wondering if in the "loop" of forwarding/pulling content from responses, etc that somehow the session data is ignored or something in the process. The command is [present in the smarty template](https://github.com/zikula/core/blob/1.4/src/system/AdminModule/Resources/views/Admin/categorymenu.tpl#L3) to show the flash message so, not sure why it isn't working.

I suspect this will be resolved when refactoring to new twig templates and functions, but creating this ticket so I don't forget the problem.

Also would be nice if others could confirm the problem.

currently scheduled for 1.4.3 - this is not a blocker.

**Comment by Guite** [comment]
Let's close this one (at least until somebody finds a reproducible example) and better concentrate on getting rid of Smarty.
