### ISSUE TITLE
Misleading update checker message

### ISSUE THREAD

**Issue by Guite** [zikula/core#2823]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2-dev
| PHP Version       | 5.5

### Expected behavior
No update message, because the current development version is _never_ than 1.4.1 stable.

### Actual behavior
Message: _Update checker: You are currently using an unreleased version of the Zikula Core._
_Stable Zikula Core available: 1.4.1_

### Steps to reproduce
Install current git version from the _1.4_ branch. Navigate through some admin pages with activated development mode.

**Comment by craigh** [comment]
IMO, this is not a critical issue because it will only affect core developers (those using a git pull)

**Comment by Guite** [comment]
Correct. If it was critical I'd have assigned the _blocker_ tag :smile: 
But maybe we could check for `less` instead for `unequal` or something, so that a newer version causes no message at all.

**Comment by craigh** [comment]
sure - I guess I just didn't even think of it as a _bug_ :smile:

**Comment by Guite** [comment]
After looking at https://github.com/zikula/core/blob/1.4/src/system/AdminModule/Resources/views/AdminInterface/updatecheck.html.twig#L18 I also do not think of it as a bug anymore. I will prepare a small PR for slight changes though.

**Comment by craigh** [comment]
ping @Kaik

**Comment by Guite** [comment]
I did several minor changes in #2824. The most important one is that the message is changed for when the latest stable core is used: _You are using the latest stable version of the Zikula core._ instead of _A new version of the Zikula core is available. Please download the new Zikula core_.

**Comment by Guite** [comment]
Also I've disabled (by commenting) an impossible case which is never reached (if not updatechecker.enabled).

**Comment by craigh** [comment]
have you tested this locally?

**Comment by Guite** [comment]
Yes, sir!

**Comment by Guite** [comment]
Closed and moved back to 1.4.2.
