### ISSUE TITLE
PageLockModule installation is broken

### ISSUE THREAD

**Issue by rallek** [zikula/core#2827]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2 with boostrap-theme branch 
|ci build| 155
| PHP Version       | 5.5.30

### Expected behavior
the installation runs with no error message

### Actual behavior
installation is broken:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

The "modules/PageLockModule" directory does not exist.

### Steps to reproduce
install a fresh 1.4.2dev

**Comment by craigh** [comment]
fixed by https://github.com/zikula/core/commit/b7ca19158418f54b1f2c2f44643531ca5d9a4880

@rallek please test again with this module and Profile and Legal

**Comment by rallek** [comment]
yes, it is working now.
