### ISSUE TITLE
missleading message in admin area (Developer notices (development mode on) )

### ISSUE THREAD

**Issue by rallek** [zikula/core#2828]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2 ci build 155 incl. boostrap-theme
| PHP Version       | 5.5.30

### Expected behavior
Developer notices (development mode off) 

### Actual behavior
Developer notices (development mode on) 

### Steps to reproduce
the ``custom_parameters.yml`` do have ``env: prod`` so the development notice is off. It is just the headline what is giving the wron impression. If I click on this headline the behavior is correct in ``prod`` and ``dev``. In dev you do get a lot more information.

By the way: a great improvement this notice line!

**Comment by craigh** [comment]
which system module are you viewing at the time?

**Comment by rallek** [comment]
e.g. extensions

**Comment by craigh** [comment]
I ask because as you said it is different in some places, right? so in Settings it would be different.

**Comment by rallek** [comment]
no. In all refactored modules it is the same (#2829).
The headline is also showing development mode on even if ``env:`` is ``prod``

**Comment by craigh** [comment]
yes - all _refactored_ modules are Extensions, Blocks and Theme. All the other should look different (hopefully correct?)

**Comment by rallek** [comment]
yes. This is correct. But the behavior of the refactored are wrong. That is this issue about.
