### ISSUE TITLE
different notices in different admin areas

### ISSUE THREAD

**Issue by rallek** [zikula/core#2829]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2 ci build 155 incl. boostrap-theme
| PHP Version       | 5.5.30

### Expected behavior
in all admin areas of all system modules I would expect the same notices

### Actual behavior
in ``settings`` I see another ``development mode`` message and only this one. in ``extensions`` I see the new development notice plus the update checker which is correctly notifying me I do have an unreleased version

### Steps to reproduce
click on ``settings`` and compare with ``extensions``

### Additional comment
it is a small issue :-)

**Comment by craigh** [comment]
This is due to refactoring and cannot be helped.

**Comment by rallek** [comment]
:-)

It is just my observation during testing. I would like to add these kind of tickets to document ``we know about this``
