### ISSUE TITLE
"begin" of template is missing if "Embed template information within comments inside the source code of pages" is selected in ThemeModule Settings

### ISSUE THREAD

**Issue by rallek** [zikula/core#2830]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.2 ci build 155 incl boostrap-theme |
| PHP Version | 5.5.30 |
### Expected behavior

in ThemeModule Settings:
if `Embed template information within comments inside the source code of pages` is selected and you look at some browser code you should be able to see the templates where the code is comming from.

```
<!-- begin system/ThemeModule/Resources/views/Admin/modifyconfig.tpl -->
```

and

```
<!-- end system/ThemeModule/Resources/views/Admin/modifyconfig.tpl -->
```

should appear in the webbrowser code.

This is the only way a user like me can figure out where to look for template changes.
### Actual behavior

only

```
<!-- end system/ThemeModule/Resources/views/Admin/modifyconfig.tpl -->
```

is there
### Steps to reproduce

switch this behavior in ThemeModule Settings on and click look at some browser code.

**Comment by craigh** [comment]
This is old smarty functionality. I'm not sure it is desired in new twig templates.

**Comment by craigh** [comment]
This will not be implemented in Twig templates because a much more powerful resource is available in the Symfony developer toolbar. This tells you all the templates in use and the parameters sent to them (in the twig panel).

**Comment by rallek** [comment]
oh! I did not expected that this function will not be available anymore. That will make things more dificult to me :-(
The Symphony toolbar is powerfull. But a simple question the toolbar is not answering:
A specific part of a page which I want to change in which template and at which place is it?

Let me give a simple example: I am on an fresh install on zikula. No modules installed. Now I want to change the bottom line "Powered by Zikula" into "Powered by Zikula and me". 

Ok I know it is in the theme home.tpl. But how a newby is able to figure this out? The toolbar is not telling this. And if I do have a new module and I have to customize this one it becomes really hard.

By the way: I have seen, the search box on the new boostrap do have ``start`` and ``end``. So this is smarty/twig mixing issue as you explaned.

**Comment by rallek** [comment]
or a more powerfull example:

site search: Click on the menu link ``site search``. You want to change the module title. Twig is not knowing you have to look into ``system/ThemeModule/Resources/views/moduleheader.tpl``

**Comment by rallek** [comment]
if it is not possible with twig templates it is a pitty but I have to live with it. But please do not drop if it is possible.

**Comment by rallek** [comment]
Thanks!

**Comment by craigh** [comment]
closed by https://github.com/zikula/core/pull/3073
