### ISSUE TITLE
[1.3.x] In the settings of search block there are problems with the checkboxes if a module has several entities

### ISSUE THREAD

**Issue by Portugao** [zikula/core#2834]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10
| PHP Version       | 5.4.45

 The block should save the changing of search options. If an option is not saved, the checkbox should be not checked.

 There are problems with modules, that have more than 1 entity. It seems, the informations does not saved correctly. Also the checkboxes are always checked; equal if saved as active or not active.

 Try to disable a search option and save. The searching for this module seems to work correctly; the checkboxes are always checked.

**Comment by Portugao** [comment]
It seems it is an issue of modules with several entities....
Have to check with other modules.....

**Comment by Portugao** [comment]
Indeed. 
@Guite @craigh @cmfcmf 
Unclear, if it is an issue of the core or of MOST....

**Comment by Guite** [comment]
Which module? How to reproduce?

**Comment by craigh** [comment]
I don't think the 'saving of the options' is saved to a DB, but rather a cookie or session

**Comment by Guite** [comment]
I think the active modules are stored as part of the search block settings.

**Comment by craigh** [comment]
I assumed @Portugao meant a user's choices from page load to page load.

**Comment by Guite** [comment]
@Portugao do you mean the block settings in the admin area or the individual changes made by a user in the frontend?

**Comment by Portugao** [comment]
If speak of the settings for an user block.

**Comment by Guite** [comment]
Then this would be a new feature.

**Comment by craigh** [comment]
user block? The ticket is about search block... now I'm confused. maybe some screenshots would help.

**Comment by Guite** [comment]
As new features will not be implemented for 1.3.x, this issue needs to be moved to a 1.4.x milestone.

**Comment by Guite** [comment]
@craigh I think he meant what you mentioned above.

@Portugao yes please post a screenshot to ensure we understand your concern correctly

**Comment by Portugao** [comment]
Sorry, i mean the search block setting.

**Comment by Portugao** [comment]
![search block](https://cloud.githubusercontent.com/assets/493707/17811813/aab94192-6624-11e6-8a5b-2cec1d5f9572.jpg)

**Comment by Portugao** [comment]
If I disable 'Registrierte Benutzer' it does get saved.
If I disable Persons (entity of a MOST module) it does not get saved.

**Comment by Portugao** [comment]
I have checked again and updated the title and description of this issue. Have no idea at the moment, what is wrong.

**Comment by craigh** [comment]
I wonder if this is a MOST issue?

**Comment by Guite** [comment]
Maybe. I can check, but not in very near future.

**Comment by Portugao** [comment]
The code around the search block is not so easy to understand for me...maybe I have a view tomorrow or the next days...

**Comment by Guite** [comment]
@Portugao can you please check whether this problem can be reproduced with one of your public MOST moduies? Then I will try to fix it with this module accordingly. Thanks.

**Comment by Guite** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VmiWJ7FG&#x2F;7-investigate-search-block-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Investigate search block issue</a>

**Comment by Portugao** [comment]
Should be possible to reproduce with MUPolls.

**Comment by Guite** [comment]
Fixed in https://github.com/Guite/MostGenerator/commit/bad6fb3c9a57cf38262e52500362fd62df5e92b3
