### ISSUE TITLE
Upgrade from 1.4.0 to 1.4.2 failed!

### ISSUE THREAD

**Issue by rallek** [zikula/core#2835]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.5.30

### Expected behavior
Upgrade went fine

### Actual behavior
After pressing finish I do get the following error:

Fatal error: Uncaught exception 'RuntimeException' with message 'UserUtil::getTheme() is unable to calculate theme name.' in /home/www/11-cv.de/Zikula_Core-1.4.2/lib/util/UserUtil.php:1985 Stack trace: #0 /home/www/11-cv.de/Zikula_Core-1.4.2/lib/legacy/util/ThemeUtil.php(297): UserUtil::getTheme() #1 /home/www/11-cv.de/Zikula_Core-1.4.2/lib/util/ModUtil.php(929): ThemeUtil::getModuleStylesheet('ZikulaSecurityC...') #2 /home/www/11-cv.de/Zikula_Core-1.4.2/lib/util/ModUtil.php(887): ModUtil::_loadStyleSheets('ZikulaSecurityC...', false, 'user') #3 /home/www/11-cv.de/Zikula_Core-1.4.2/lib/util/ModUtil.php(797): ModUtil::loadGeneric('ZikulaSecurityC...', 'user', false) #4 /home/www/11-cv.de/Zikula_Core-1.4.2/lib/legacy/Zikula/Core.php(501): ModUtil::load('ZikulaSecurityC...') #5 /home/www/11-cv.de/Zikula_Core-1.4.2/index.php(20): Zikula_Core->init(4095, Object(Zikula_Request_Http)) #6 {main} thrown in /home/www/11-cv.de/Zikula_Core-1.4.2/lib/util/UserUtil.php on line 1985

### Steps to reproduce
try an upgrade!

**Comment by craigh** [comment]
Did you start with a "fresh" install of 1.4.0? or something else?

**Comment by rallek** [comment]
upgrade of an existing 1.4.0 site with an own theme, based on the old boostrap theme of 1.4.1
The theme is now located at a different palce (two levels higher) as all themes are there now.

**Comment by craigh** [comment]
> The theme is now located at a different palce (two levels higher) as all themes are there now.

what?

**Comment by rallek** [comment]
in 1.4.0 themes are located here: ``/home/www/11-cv.de/Zikula_Core-1.4.0/themes/Zikula/Theme``
in 1.4.2 I found them here: ``/home/www/11-cv.de/Zikula_Core-1.4.2/themes`` And I placed my theme there as well

**Comment by craigh** [comment]
then you've done it wrong.

The placement has to do with the namespacing of the theme. *Core* themes were refactored from PSR-0 to PSR-4 and so their directory structure changed. I'm guessing you did not do any refactoring, so your theme should live in the same directory structure as it did before.

**Comment by rallek** [comment]
Puh, how should I know that? hard to survive...

**Comment by craigh** [comment]
> Puh, how should I know that?

you assumed something you should not - that you should change the directory structure. Since there are no instructions to do that anywhere, you shouldn't assume that.

**Comment by rallek** [comment]
yes, my lesson learned. Good to know and might be usefull for support issues that users like me can do such things...

**Comment by craigh** [comment]
Thank you for breaking things :wink: 

please test again without changing the structure and let me know what happens.

**Comment by rallek** [comment]
here you are:


Fatal error: Call to a member function getConfig() on a non-object in /home/www/11-cv.de/Zikula_Core-1.4.2/system/ThemeModule/EventListener/DefaultPageAssetSetterListener.php on line 144
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Error: Call to a member function getConfig() on a non-object

**Comment by rallek** [comment]
I switched to dev/debug mode. Now I do have the following:
````
 Error: Call to a member function getConfig() on a non-object
500 Internal Server Error - FatalErrorException
Stack Trace

    in system/ThemeModule/EventListener/DefaultPageAssetSetterListener.php at line 144  -
                    if (!empty($this->params['zikula.stylesheet.bootstrap.min.path'])) {
                        // Core-2.0 Site method
                        $overrideBootstrapPath = $this->params['zikula.stylesheet.bootstrap.min.path'];
                    } elseif (!empty($this->themeEngine->getTheme()->getConfig()['bootstrapPath'])) {
                        // Core-2.0 Theme method
                        $overrideBootstrapPath = $this->themeEngine->getTheme()->getConfig()['bootstrapPath'];
                    } else {

````

**Comment by rallek** [comment]
Now I get:
````
502 Bad Gateway
nginx/1.2.1
````
Anything I can do to get my site back and running? Or do I have to start from scratch and rebuild the site?

**Comment by rallek** [comment]
I tried to switch my theme inside the database to see if this is the reason. I switched 
````
5 	ZConfig 	Default_Theme 	s:14:"ZikulaOmiTheme";
````
to
````
5 	ZConfig 	Default_Theme 	s:14:"ZikulaBootsrapTheme";
````
But that is not doing the trick. I do get this message:
````
ContextErrorException in ExtensionVarEntity.php line 81: Notice: unserialize(): Error at offset 20 of 27 bytes
````
How can I switch back my theme to a core theme?

**Comment by rallek** [comment]
I checked on a fresh 1.4.2 install. My OmiTheme is working well there. So I can exclude my theme is the root cause. Something went wrong during upgrade.

**Comment by rallek** [comment]
I am trying to do another upgrade and I can see I did not follow the upgrade instructions propperly. So now will try to do it exactly how the upgrade instruction is demanding.

I prepared a test scenario. 1.4.0 is installed together with news/scribite/ezcomments. I created one news myself. This is my starting point.

Now I do not know how to proceed with the input for the new ``custom_parameters.yml``.
I the ``UPGRADE-1.4.md`` is demanded 
````
(all instances of "~" should be replaced with their proper values)
````

I found in the new ``custom_parameters.yml`` (copy of ``parameters.yml``) the following lines:
````
    assets_version: ~ #e.g. 'v1'
    
    # Changing the current umask to the octal "022" will set directory permissions
    # to "755", and file permissions to "644" (for directories such as
    # "app/cache" and "app/logs"). Changing the current umask to the octal "02"
    # will set directory permissions to "775", and file permissions to "664".
    # Changing the current umask to the octal "0" will set (insecure) directory
    # permissions to "777", and file permissions to "666". Note that using the ACL
    # is recommended when you have access to them on your server, because changing
    # the umask is not thread-safe. Set this value to "~" (NULL), to disable support
    # for umask.
    umask:             ~

    # the following parameter is used in the clickjacking protection listener
    # it accepts any values allowed for X-Frame-Options
    security.x_frame_options: SAMEORIGIN
````
What is needed for ``assets_version: ~`` and ``umask:  ~``? I do not know what ``propper`` is for this values. I descided for ``null`` in both cases (seen in another try run for an 1.4.2 installation).

And in my old (1.4.0) custom_parameters.yml I do found some lines which do not exist in the new one:
````
    router.request_context.host: 140.koester123.de
    router.request_context.scheme: http
    router.request_context.base_url: ''
````
Whats about this?

My expectation would have been: I copy my old custom_parameters.yml to apps/config/ of my new installation. The changes of custom_parameters.yml and the new creation of personal_config.php should be done by the upgrader.

Nevertheless, I gave it a try. Calling my site I do get the chance to start the upgrade. But the upgrade did not run propperly:
````
Upgrading Modules and Helpers

    Logged in as admin
    Modules upgraded
    Zikula Routes Module installed
    Routes reloaded
    There was an error regenerating the themes
    Upgraded to Core 1.4.1
    There was an error upgrading to Core 1.4.2
    Parameters finalized
    Caches cleared
    Finish
````
Than I can only press the button `` Finish``. This ends up with the error-message:
````
Fatal error: Uncaught exception 'RuntimeException' with message 'UserUtil::getTheme() is unable to calculate theme name.' in /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/util/UserUtil.php:1985 Stack trace: #0 /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/legacy/util/ThemeUtil.php(297): UserUtil::getTheme() #1 /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/util/ModUtil.php(929): ThemeUtil::getModuleStylesheet('ZikulaSecurityC...') #2 /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/util/ModUtil.php(887): ModUtil::_loadStyleSheets('ZikulaSecurityC...', false, 'user') #3 /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/util/ModUtil.php(797): ModUtil::loadGeneric('ZikulaSecurityC...', 'user', false) #4 /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/legacy/Zikula/Core.php(501): ModUtil::load('ZikulaSecurityC...') #5 /home/www/140.koester123.de/Zikula_Core-1.4.0/index.php(20): Zikula_Core->init(4095, Object(Zikula_Request_Http)) #6 {main} thrown in /home/www/140.koester123.de/Zikula_Core-1.4.0/lib/util/UserUtil.php on line 1985
````

Similar to https://github.com/zikula/core/issues/2845?

**Comment by craigh** [comment]
> What is needed for `assets_version` and `umask`.

nothing. they can remain as `~`

**Comment by craigh** [comment]
> My expectation would have been: I copy my old custom_parameters.yml to apps/config/ of my new installation. The changes of custom_parameters.yml and the new creation of personal_config.php should be done by the upgrader.

you are correct. the documentation is likely incorrect.

**Comment by rallek** [comment]
Do you need some more information of my test scenario (e.g. something from the databse or so)? If not I will delete my test site.

**Comment by craigh** [comment]
I'm not able to look in to any of this at the moment, so I have no idea. if you have the time and can figure out (through trial and error) the proper procedure, it would be great and very helpful. You can also submit a PR to fix the docs.

**Comment by rallek** [comment]
ok. I do my very best. But I am getting lost because I do not understand what is going on. Next I will do a naked 1.4.0 upgrade to 1.4.2.

**Comment by rallek** [comment]
So here are my results from my try outs.

The following scenario I did. I created a naked 1.4.0 site (``/home/www/140.koester123.de/Zikula_Core-1.4.0``)and a naked 1.4.2 site (``/home/www/142.koester123.de/Zikula_Core-1.4.2``). No configuration. Both sites are running. I made an export of the databases.
Now I placed the files of 1.4.2 in parallel to 1.4.0 (``/home/www/140.koester123.de/Zikula_Core-1.4.2``)
Next I copied ``custom_parameters.yml`` and ``personal_config.php`` from the 1.4.0 installation to 1.4.2 files.
Next step I changed the root of my site to the new files and went to my browser. Now I saw the upgrade button. 
I run the upgrade and got the following result
![zwischenablage01](https://cloud.githubusercontent.com/assets/935250/14762662/17ab1584-0980-11e6-93a6-d9bc0f31977a.jpg)
Next I started from beginning but I changed the default theme to boostrap before I run the upgrade.
Same result.
Pressing the finish button leads always to:
````

Whoops, looks like something went wrong.
1/1 RuntimeException in UserUtil.php line 1985: UserUtil::getTheme() is unable to calculate theme name.

    in UserUtil.php line 1985
    at UserUtil::getTheme() in ThemeUtil.php line 297
    at ThemeUtil::getModuleStylesheet('ZikulaSecurityCenterModule') in ModUtil.php line 929
    at ModUtil::_loadStyleSheets('ZikulaSecurityCenterModule', false, 'user') in ModUtil.php line 887
    at ModUtil::loadGeneric('ZikulaSecurityCenterModule', 'user', false) in ModUtil.php line 797
    at ModUtil::load('ZikulaSecurityCenterModule') in Core.php line 501
    at Zikula_Core->init('4095', object(Zikula_Request_Http)) in index.php line 20

````
I attach the database exports:
[MySql.zip](https://github.com/zikula/core/files/233046/MySql.zip)
I can not see what is wrong. A lot of tables are in different orders but I did not figure out the root cause. This number is a little bit to big for me. Experts must step into this problem.

**Comment by craigh** [comment]
> Experts must step into this problem.

wish we had a few more of those. I can't do all this myself.

I guess 1.4.2 is not upgradable then. I wish we had a few more testers before the release to prevent that. 😞 I appreciate your attempts to troubleshoot and fix.

If someone can fix this problem, we could release it immediately as 1.4.3. I don't have time at the moment.

**Comment by craigh** [comment]
@rallek I solved the problem with "There was an error upgrading to Core-1.4.2" in #2958. (pending atm) That issue was simple as it was only a lack of a `return true;` in the method.

The issues with the *theme* is really the problem that is defined by this ticket and should be the focus of the fix.

I just completed several rounds of testing proceeding through 1.4.0 -> 1.4.1 -> 1.4.2 upgrade. But I believe you have been attempting to upgrade 1.4.0 - > 1.4.2 directly here. While theoretically, there should be no difference, it is possible that there is one. I can check that next.

Please email me the theme you've been using (Omi?) and confirm that you were using that theme during all your upgrade trials above (e.g. you set the theme as Omi in 1.4.0 and then attempted the upgrade?).

**Comment by craigh** [comment]
so - as quickly as that, I was able to reproduce the error 😄 

I ran the upgrade 1.4.0 -> 1.4.2 with only core distribution files and got the same error as you `PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'UserUtil::getTheme() is unable to calculate theme name.' in /Applications/MAMP/htdocs/142/lib/util/UserUtil.php:1985`

so I will look into that further.

**Comment by craigh** [comment]
so it appears that in the upgrade process all the themes were being set to state: INACTIVE and this causes the error. I don't know why this is _not_ a problem when proceeding through 1.4.1 in the middle.
