### ISSUE TITLE
Upgrade is a mess

### ISSUE THREAD

**Issue by rallek** [zikula/core#2836]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.5.30

### Expected behavior
Much more easy to upgrade minor versions.

I do not want to manually delete everything and have to rescue some files including modules, themes and userdata.

The instruction on ``/installdoc/UPGRADE-1.4.md`` is readable after you have done all your rescue things and you are in the middle of the upgrade. This file is dificult to find. In the normal docs folder there is an upgrade 1.4.0.md. In this file you can not find anything about upgrade instructions. You have to figure out to look at ``/docs/en``. And in this file you will not find any instruction about your modules, themes and userdata.

### Actual behavior
broken. see #2835

**Comment by rallek** [comment]
I cannot find this issue. It is not duplicate. The upgrade instruction is incomplete and can not be found easily. I do not understand why you are closing it :-(

**Comment by craigh** [comment]
dup #2833 and #2835. It seems you are opening multiple tickets for the same problem.

**Comment by rallek** [comment]
no, the problem is different. The main issue in my ticket is the incomplete documetation! You are talking in your ticket about upgrade process which seems to do things for 1.3.x even if the upgrade is only from 1.4.x

**Comment by rallek** [comment]
I even can not find the file to fix the description
