### ISSUE TITLE
Twig extensions

### ISSUE THREAD

**Issue by craigh** [zikula/core#2841]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3+

feature? http://twig.sensiolabs.org/doc/extensions/index.html

we should consider how this should/should not be integrated into the core (possibly some already is?).

@Guite @cmfcmf

**Comment by Guite** [comment]
#2853 depends on this

**Comment by craigh** [comment]
Please feel free to make some decisions on this and solve the problem.

**Comment by Guite** [comment]
Fixed by #2859
