### ISSUE TITLE
Password improvements

### ISSUE THREAD

**Issue by craigh** [zikula/core#2842]
Passwords and password management must be significantly improved. 

http://stackoverflow.com/questions/401656/secure-hash-and-salt-for-php-passwords

http://www.dev-metal.com/use-php-5-5-password-hashing-functions/

php 5.5 is required for php password functions, but Symfony has polyfill loaded for 5.4 so we can begin using anytime.
- [x] update algorithm to scrypt or bcrypt
- [x] figure out way to update all existing passwords
- [x] ~allow admin to reset user password with temporary password being sent to user and force update on first login.~ (this was already implemented)
- [x] provide simple method for global 'reset' of all passwords including notification of temporary passwords to users via email in the event of site breach.
- [x] ~use native php (polyfill) where possible.~
- [x] increase standard required default length of user password to at least 8 (currently 5)
- [x] ~Password configuration - allow the admin to select 'degrees' of password security:~
  - ~require numbers yes|no~
  - ~require symbols yes|no~
  - ~require some capital and lowercase yes|no~
  - ~php `password_hash` allows a 'cost' param ([manual](http://php.net/manual/en/function.password-hash.php)) - allow user to select a value~
- [x] of course [Symfony](http://symfony.com/doc/current/components/security/index.html) has some security related features we should use where possible.
- [x] implement outsourced password meter 
  - ✅ https://github.com/ablanco/jquery.pwstrength.bootstrap
  - ❌  https://packagist.org/packages/kartik-v/strength-meter
- [x] add password generator
- [x] add option to enable [compromised password validator](https://symfony.com/blog/new-in-symfony-4-3-compromised-password-validator)

**Comment by Guite** [comment]
refs #3175

**Comment by craigh** [comment]
http://blog.michaelperrin.fr/2017/01/17/migrating-users-to-a-secure-hashing-algorithm-in-symfony/

**Comment by Guite** [comment]
https://pehapkari.cz/blog/2017/02/06/how-to-rehash-legacy-passwords-in-symfony/

**Comment by Guite** [comment]
Libsodium with state of the art crypt technology coming in PHP 7.2: https://wiki.php.net/rfc/libsodium

**Comment by Guite** [comment]
Deprecate SHA1 as it's considered insecure. (It's not used by default, but can bei selected).

**Comment by craigh** [comment]
I have re-assigned this to milestone 3 because I feel it is very important to correct these issues for this release and not delay.

**Comment by craigh** [comment]
@Guite I wonder your opinion on outsourcing the password meter. We have an effective one, but it was written before 2010. I'm not sure that matters. https://github.com/ablanco/jquery.pwstrength.bootstrap seems like a good choice for me, but we can't use composer. your thoughts?

**Comment by Guite** [comment]
:+1: for using a more modern and Bootstrap 4 compatible one

How about embedding only the [dist folder](https://github.com/ablanco/jquery.pwstrength.bootstrap/tree/master/dist) and watch the repository's releases for keeping up to date? I do it similarly with jsPlumb in ZikulaWorkflowBundle.
