### ISSUE TITLE
Update message with an Error

### ISSUE THREAD

**Issue by trichers** [zikula/core#2843]
| Q | A |
| --- | --- |
| Zikula Version | 1.2.10 and 1.3.10 |
| PHP Version | 5.x |
### BUG

**In the Admin-Panel is this error-message:**
Es ist eine neue Version des Zikula Cores verfügbar. Bitte den neuen Zikula Core herunterladen. 1737
Error 522 Ray ID: 28ff12fcdd8640fa • 2016-04-07 17:07:23 UTC
Connection timed out
You
Browser
Working
Hamburg
CloudFlare
Working
update.zikula.org
Host
Error
What happened?

The initial connection between CloudFlare's network and the origin web server timed out. As a result, the web page can not be displayed.
What can I do?
If you're a visitor of this website:

Please try again in a few minutes.
If you're the owner of this website:

Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. Additional troubleshooting information here.

CloudFlare Ray ID: 28ff12fcdd8640fa • Your IP: 85.13.133.195 • Performance & security by CloudFlare
0

**Comment by craigh** [comment]
I am seeing this error also on my 1.3.x site. I guess it is because the old site where the core updates were published is no longer functional (out of our control to fix this, btw). I'm guessing a solution would be to manually update the database to disable the automatic check of updates.

If you can do so, go to your database, to the `modvar` table and find the `ignoreinstallercheck` from the `Admin` module and change the value from `0` to `1`. This should disabled the check and return the site to functional. maybe :|

**Comment by trichers** [comment]
you have to change in table module_vars the item ZConfig - updatecheck from 1 to 0
ZConfig 	updatecheck 	i:0;

**Comment by craigh** [comment]
so it is working for you?

**Comment by craigh** [comment]
for any others with this problem: change the fields below to match

![screen shot 2016-04-14 at 3 21 43 pm](https://cloud.githubusercontent.com/assets/350048/14540741/a08b205c-0254-11e6-9029-7111cbf56efc.png)

**Comment by Portugao** [comment]
Thx

**Comment by trichers** [comment]
it works for me

**Comment by craigh** [comment]
:+1:

**Comment by kaffeeringe** [comment]
Same Problem with a very old site (1.2.5)...

**Comment by kaffeeringe** [comment]
In 1.2.5 musste ich hier die 1 auf 0 ändern: 
![db](https://cloud.githubusercontent.com/assets/367592/14705652/e444e592-07ba-11e6-9613-95cfef82acd6.png)

**Comment by Gastropex** [comment]
Hello,

on my Zikula-Site with 1.3.0 is the same problem but I only found a table named z_modules_vars on my database with ignoreinstallercheck in the admin-module. I changed the value from 0 to 1 but nothings happens. Is the any other entry in an other table, which has to be modified?

Regards from Germany
Jens
