### ISSUE TITLE
[General] consider reactPHP

### ISSUE THREAD

**Issue by craigh** [zikula/core#2848]
Consider ReactPHP http://gnugat.github.io/2016/04/13/super-speed-sf-react-php.html

**Comment by Guite** [comment]
For which purpose? Doing tests?

**Comment by craigh** [comment]
> TL;DR: Run your application as a HTTP server to increase its performances.

to increase performance of the entire application

**Comment by Guite** [comment]
quite dated but possibly still worth a look https://www.youtube.com/watch?v=Pd_AjWGNyck

**Comment by Guite** [comment]
Closing as won't fix.
