### ISSUE TITLE
Consistent usage of entity repositories

### ISSUE THREAD

**Issue by Guite** [zikula/core#2858]
Until 2.0 all DQL queries should have been moved into dedicated repository classes.

**Comment by craigh** [comment]
I think this is complete. The only "exposed" DQL queries that I can find are in `\Zikula\Bundle\HookBundle\Dispatcher\Storage\Doctrine\DoctrineStorage` and you could argue that they are appropriately placed. If not, they would need to be part of a larger refactoring of the HookBundle which relocates the entities and creates multiple repository classes. These repos would then be called by DoctrineStorage. For now, I think they are fine. I'd like to see Hooks refactored to not be persistent anyway and that would remove most of this issue (refs https://github.com/zikula/core/issues/2784)
