### ISSUE TITLE
Search Block overrides require refactoring

### ISSUE THREAD

**Issue by craigh** [zikula/core#2872]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3-dev

### Expected behavior
same appearance as 1.4.2

### Actual behavior
block appears as 'stock' appearance - no overrides in effect

### Steps to reproduce
install.

@Guite - because of your recent refactoring to twig, the old smarty overrides need to be fixed.

**Comment by Guite** [comment]
@craigh I've migrated the templates in #2873.
They are not recognised though.
This seems to be caused by the `TemplatePathOverrideListener` which is not called for `AbstractBlockHandler` instances. Maybe `KernelEvents::CONTROLLER` is not adequate for these at all.

**Comment by craigh** [comment]
I think your directory structure is wrong. Try eliminating the `/views` level so it is just like `src/themes/Andreas08Theme/Resources/ZikulaSearchModule/Block/search.html.twig`

**Comment by craigh** [comment]
hmmm. I'm still not sure about this. see https://github.com/zikula/SpecTheme/blob/master/Resources/README.md includes the `/views`

if you can't get it to work, merge it anyway and I will have to take a look later on. Keep this ticket open.

**Comment by Guite** [comment]
I added an `echo` statement to the `TemplatePathOverrideListener` and still think that it is not called at all for blocks.

**Comment by craigh** [comment]
I believe `TemplatePathOverrideListener` is legacy only

**Comment by Guite** [comment]
How/where is the override then recognised?

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php#L443-L446

**Comment by Guite** [comment]
https://github.com/zikula/SpecTheme/blob/master/README.md states that the `ZikulaKernel` applies only for `ZikulaFooBundle:Bar:index.html.twig` type notation. The search block uses the other one, see here: https://github.com/zikula/core/blob/1.4/src/system/SearchModule/Block/SearchBlock.php#L56

**Comment by Guite** [comment]
Comments in the `ZikulaKernel` method you've pointed do say the same.

**Comment by craigh** [comment]
ok (doing this from work with no code in front of me...) can you make sure `TemplatePathOverrideListener ` is firing?

**Comment by craigh** [comment]
changing

`return $this->renderView('@ZikulaSearchModule/Block/search.html.twig', $templateParameters);`

to 

`return $this->renderView('ZikulaSearchModule:Block:search.html.twig', $templateParameters);`

fixes this problem. so there is definitely something wrong with the namespaced method. I'm still looking into it.
