### ISSUE TITLE
Problems with non a-zA-Z0-9 characters in DB pass?

### ISSUE THREAD

**Issue by craigh** [zikula/core#2875]
http://zikula.org/forums/topic/59982

| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.x

**Comment by cmfcmf** [comment]
I've just installed Zikula with `foo%barö?` as database password without issues.

**Comment by craigh** [comment]
I've just installed Zikula with `stép%` as database password without issues.

closing as not-core
