### ISSUE TITLE
DoctrineExtensionsBundle -> DoctrineBehaviours

### ISSUE THREAD

**Issue by craigh** [zikula/core#2876]
don't know if this matters or not for us

https://github.com/KnpLabs/DoctrineBehaviors

**Comment by Guite** [comment]
Possibly related to #2216

**Comment by Guite** [comment]
Adding information from other issues which are related/duplicates:

From #2216:
> Remove beberlei/DoctrineExtensions, it is deprecated in 1.4.0.

From #1982:
> Remove old Doctrine extensions implementation
> Follow-up from migration to StofDoctrineExtensionsBundle - the old implementation should be removed as soon as the fallback is not required anymore.

**Comment by Guite** [comment]
Closed in favour of #3457
