### ISSUE TITLE
Fatal error: Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by shefik** [zikula/core#2880]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

List of modules, without an error

### Actual behavior

Fatal error: Maximum function nesting level of '100' reached, aborting! in /vendor/twig/twig/lib/Twig/NodeVisitor/SafeAnalysis.php on line 63

### Steps to reproduce

I have 81 uninstalled modules located in /modules. Go to this page:

/extensions/module/list

Make sure Xdebug is active in PHP to see the error output.

**Comment by cmfcmf** [comment]
This is not a Zikula issue but rather a XDebug configuration issue. Increase your maximum nesting level please.

**Comment by shefik** [comment]
ok
