### ISSUE TITLE
Module Dependencies Not Installing

### ISSUE THREAD

**Issue by shefik** [zikula/core#2881]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.2 |
| PHP Version | 5.6 |
### Expected behavior

Any required dependencies are also installed, when a module is installed.
### Actual behavior

It worked under Zikula 1.4.1.
### Steps to reproduce

Sample code in the module Installer file:

```
       $result['dependencies'][] = array(
            'modname' => 'Scribite', 
            'minversion' => '5.0.0',
            'maxversion' => '', 
            'status' => ModUtil::DEPENDENCY_REQUIRED,
            'reason' => $this->__('Transforms &lt;textarea&gt; form fields to "What You See is What You Get" (WYSIWYG) editors.')
        );
```

**Comment by shefik** [comment]
Looks like the entire controller function `initialiseAction(Request $request)` was removed in Zikula 1.4.2, when it was there in Zikula 1.4.1. That is where the check for dependencies occurred.

So, a break has occurred.

**Comment by shefik** [comment]
I see that Zikula 1.4.2 now uses `installAction(Request $request, ExtensionEntity $extension)`, the cal the call to get dependencies is there now.

However, for whatever reason, `getDependentExtensions($extension)` doesn't execute. Therefore, it always gets set as empty.

The functionality to get the dependencies doesn't execute from the class `ExtensionDependencyHelper`.

**Comment by Guite** [comment]
`getDependentExtensions` is only called in `uninstallAction`. The `installAction` calls `getUnsatisfiedExtensionDependencies` instead.

**Comment by craigh** [comment]
@shefik what module were you attempting to install. I'd like to try it.

**Comment by Guite** [comment]
Postponing to 1.4.4 due to lack of response.

**Comment by shefik** [comment]
It's a custom module.

**Comment by craigh** [comment]
@shefik - do you remember the state of the module in question? Given our recent conversation at slack, is it possible that you were working with a 'transitional' module - eg. one that was neither fully 1.3.x and also neither fully 2.0? I.e. it still has a `Version.php` file? above you wrote:

> Sample code in the module **Installer** file:

I assume you meant _Version_ file?

Is there any way for me to test this?

**Comment by craigh** [comment]
@shefik @shefik @shefik
