### ISSUE TITLE
Notice: Undefined property: Zikula\Bundle\CoreBundle\Twig\Extension\CoreExtension::$baseUrl

### ISSUE THREAD

**Issue by shefik** [zikula/core#2882]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

`/lib/util/System.php` indicates in the comments that `System::getBaseUrl()` is deprecated since 1.4.0, and see `Request::getBaseUrl()`.

Same for `System::getBaseUri()`.

### Actual behavior

Error when using `Request::getBaseUrl()` or `Request::getBasePath()`:

`use Symfony\Component\HttpFoundation\Request;`

```
An exception has been thrown during the rendering of a template ("Notice: Undefined property: Zikula\Bundle\CoreBundle\Twig\Extension\CoreExtension::$baseUrl")
```

### Steps to reproduce

Used the code in a custom Twig extension.

**Comment by craigh** [comment]
show your code. your ticket doesn't make sense to me.

**Comment by shefik** [comment]
Declare this use statement:

`use Symfony\Component\HttpFoundation\Request;`

And, try calling to this:

`Request::getBaseUrl()` or `Request::getBasePath()`

And you will see the error thrown. For a quick test, place the code somewhere in:

`/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php`

**Comment by Guite** [comment]
The methods should exist:
http://api.symfony.com/master/Symfony/Component/HttpFoundation/Request.html#method_getBasePath
http://api.symfony.com/master/Symfony/Component/HttpFoundation/Request.html#method_getBaseUrl

**Comment by Guite** [comment]
They are not static though, so `Request::` does not work. You need the current request object instead, for example by using the `request_stack` service.

**Comment by craigh** [comment]
This is not a bug. you are not using the class correctly. As I said, if you will show your actual code then I might be able to help. As it is, I still have no idea. As Guite said, the methods are not static. Please look through the core for examples using the same methods to have some idea how to do what you need.

**Comment by shefik** [comment]
Then the comments in /lib/util/System.php are wrong, because they are written as static. That is where I got the code from.

**Comment by craigh** [comment]
they are not wrong. this is a standard way for class::method to be written.
