### ISSUE TITLE
Warning: Class __PHP_Incomplete_Class has no unserializer 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2883]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

Hi, guys I'm back hopefully for a longer time now.

### Expected behavior
Clear dev cache without errors

### Actual behavior
```
php app/console cache:clear --env="dev" -vvv

 // Clearing the cache for the dev environment with debug true
 // Clearing outdated warmup directory...
 // Warming up cache...

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Class __PHP_Incomplete_Class has no unserializer  
                                                             
Exception trace:
 () at /home/Kaik/public_html/office/src/system/ExtensionsModule/Entity/ExtensionVarEntity.php:81
 Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
 unserialize() at /home/Kaik/public_html/office/src/system/ExtensionsModule/Entity/ExtensionVarEntity.php:81
 Zikula\ExtensionsModule\Entity\ExtensionVarEntity->getValue() at /home/Kaik/public_html/office/src/system/ExtensionsModule/Api/VariableApi.php:83
 Zikula\ExtensionsModule\Api\VariableApi->initialize() at /home/Kaik/public_html/office/src/system/ExtensionsModule/Api/VariableApi.php:134
 Zikula\ExtensionsModule\Api\VariableApi->get() at /home/Kaik/public_html/office/src/system/ThemeModule/Engine/Engine.php:379
 Zikula\ThemeModule\Engine\Engine->setActiveTheme() at /home/Kaik/public_html/office/src/system/ThemeModule/Engine/Engine.php:208
 Zikula\ThemeModule\Engine\Engine->getTheme() at /home/Kaik/public_html/office/src/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php:428
 Zikula\Bundle\CoreBundle\HttpKernel\ZikulaKernel->locateResource() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Config/FileLocator.php:51
 Symfony\Component\HttpKernel\Config\FileLocator->locate() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php:79
 Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator->locate() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TemplatePathsCacheWarmer.php:49
 Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplatePathsCacheWarmer->warmUp() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:144
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/Kaik/public_html/office/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /home/Kaik/public_html/office/src/app/console:44

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
```

### Steps to reproduce
clear dev cache

I have looked on ExtensionVarEntity.php:81 and I'm actually "disappointed" that doctrine field type "array" is not used to serialize, unserialize this, is this as it is because of BC ?

**Comment by Kaik** [comment]
Hi, I was able to trace this down to this entry in module_vars table 
systemplugin.imagine
presets
a:1:{s:7:"default";C:27:"SystemPlugin_Imagine_Preset":266:{x:i:2;a:8:{s:5:"width";i:100;s:6:"height";i:100;s:4:"mode";s:5:"inset";s:9:"extension";N;s:7:"options";a:2:{s:12:"jpeg_quality";i:75;s:21:"png_compression_level";i:7;}s:8:"__module";N;s:9:"__imagine";N;s:16:"__transformation";N;};m:a:1:{s:7:"*name";s:7:"default";}}}

When changed to a:0:{} clearing cache in dev mode works fine.

**Comment by Guite** [comment]
@Kaik can you elaborate about the actual state of this issue? Was this is one-time problem or is it a general bug which needs to be looked at?

**Comment by Kaik** [comment]
Still present. This is a general bug, imagine presets are objects when they are saved in our module_vars. When accessed it generates error during un serialization( Class __PHP_Incomplete_Class has no unserializer) - a possible solution is to save those presets as an array not object and then convert it back to object inside imagine plugin.

**Comment by Guite** [comment]
I wonder when (and by what) this behaviour was introduced... if somebody has a clue, please enlighten us :-)

@jusuff any proposal for an adequate fix?

**Comment by craigh** [comment]
consider http://php.net/manual/en/class.serializable.php

**Comment by cmfcmf** [comment]
This is fixed by #2969.

**Comment by craigh** [comment]
problem was that the core's autoloaders were not being loaded for the `app/console` like they were being properly loaded for http access.

**Comment by craigh** [comment]
ping @cmfcmf I am getting same error again.

**Comment by craigh** [comment]
hmmm. never mind. 

I guess 

`[Craigs-iMac2013:core.git/src/app] craig% php console debug:event-dispatcher`

is different than

`[Craigs-iMac2013:htdocs/core.git/src] craig% php app/console debug:event-dispatcher`

**Comment by cmfcmf** [comment]
Yes. Zikula must always be run from it's root directory.

**Comment by craigh** [comment]
because...

**Comment by cmfcmf** [comment]
...Zikula consists of legacy code which uses relative file paths which "think" they are relative to the Zikula root (which is of course always the case for requests from the Web, because they all enter Zikula at `index.php`, which is at the site root).
