### ISSUE TITLE
bootstrap-media-lightbox 3.*

### ISSUE THREAD

**Issue by phaidon** [zikula/core#2886]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x.x, 2.x,x

Please use 
`"bootstrap-plus/bootstrap-media-lightbox": "3.*" `
instead of
`"bootstrap-plus/bootstrap-media-lightbox": "dev-master" `

https://github.com/zikula/core/blob/1.4/composer.json#L82

The dev-master version will be soon updated to bootstrap4/sass

**Comment by craigh** [comment]
A PR is welcome 😉
