### ISSUE TITLE
Sending mails does not work

### ISSUE THREAD

**Issue by Guite** [zikula/core#2889]
### Expected behavior
Sending mails working.

### Actual behavior
No mails are sent.

### Steps to reproduce
Try at `/mailer/config/test`.

### Reason
The problem relates to `delivery_addresses: {  }` in `generated.yml`
When this is replaced by `delivery_addresses: []` mails are sent correctly.

### See also
https://github.com/symfony/symfony/issues/16266
https://github.com/symfony/symfony/issues/9870

**Comment by Guite** [comment]
There is a fix in https://github.com/symfony/symfony/pull/17578 but this has been merged into Symfony 3.1.
See also: http://symfony.com/blog/new-in-symfony-3-1-customizable-yaml-parsing-and-dumping

**Comment by Guite** [comment]
Because DynamicConfigDumper extends YamlDumper anyway we can maybe backport the fix from Symfony 3.1 to it.

**Comment by craigh** [comment]
@Guite - probably we need an upgrade routine to reformat the generated.yml file?

**Comment by Guite** [comment]
No I don't think this is required. Because earlier the default value was not `[]`, but `null`: https://github.com/zikula/core/blob/7fee79e4184e1d61c62b080699aa92df960ba604/src/system/MailerModule/Form/Handler/ModifyConfigHandler.php#L135
I checked two installations of 1.4.0 and both files contained `delivery_address: null`.

Note Symfony changed `delivery_address` to `delivery_addresses` in a recent update, so this does not affect earlier core versions :smile:
