### ISSUE TITLE
Missing link to userblock

### ISSUE THREAD

**Issue by FRWo** [zikula/core#2891]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10
| PHP Version       | 5.6

The userblock is shown on frontend (migrated from 1.2.9) but no link in /index.php?module=User&type=user&func=main to edit the entries of this block

**Comment by Portugao** [comment]
@FRWo 
Could you please describe, what you expect exactly?

**Comment by FRWo** [comment]
I've just tested on a fresh 1.3.10 install, so there is no update from 1.2x:

I make a new block "Benutzer/Benutzer Block" on a german site and want to add f.e. a link to this block. I don't know where to do this.
In former editions there was a link to edit this block in the user section, but I can't see anything of this.

**Comment by Portugao** [comment]
So it seems it is not an issue of the update......
A user block is to put own content into and edit it from the account site; is'nt it?

**Comment by FRWo** [comment]
Yes, so it is.
I'm using it for a list of preffered links  of mz own, because the block is only shown for me.

**Comment by Portugao** [comment]
Hmmhmm...if I create a user block it will not get shown....very strange

**Comment by Portugao** [comment]
I did a pull request that will fix this issue; i have to see if the pull request will pass the code checks....

**Comment by Guite** [comment]
Fixed in #2984 - thanks @Portugao

**Comment by Portugao** [comment]
:+1:
