### ISSUE TITLE
Modal for permission component overview missing

### ISSUE THREAD

**Issue by Guite** [zikula/core#2897]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10 - 1.4.3-dev

### Expected behavior
On the _add a new permission rule_ page there are two table column headers linked to a JavaScript function which should open a modal window showing all available permission components and instances.

### Actual behavior
The JavaScript function called by clicking on the table headers is currently missing. I checked a production 1.3.10 site and there the function is also not available.

### Steps to reproduce
Go to `http://localhost/src/permissions/edit` and click on either the `Component` or the `Instance` column header while having the console open.

**Comment by craigh** [comment]
this worked before the refactor (e.g. 1.4.2)

**Comment by Guite** [comment]
> I checked a production 1.3.10 site and there the function is also not available.

**Comment by Guite** [comment]
Just looked at a 1.4.0 site, doesn't work there, too.

**Comment by craigh** [comment]
Maybe I'm not clear on what you mean. There is a menu item "Permission rules information" which pops up a modal with permission information. the path `http://localhost/src/permissions/edit` is not accessible via normal links - it is only accessible in a modal itself. In bootstrap, you cannot have multiple modals.

**Comment by Guite** [comment]
The modal in the menu works. If the edit page can not be accessed without JS, then there is no problem with that.

**Comment by Guite** [comment]
Removed obsolete links in 1146932a7dacd7beb5d38bbea661b0ca7afc01b1
