### ISSUE TITLE
Permissions module admin not functional

### ISSUE THREAD

**Issue by craigh** [zikula/core#2898]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3

### Expected behavior
works

### Actual behavior
> Variable "permission" does not exist in system/PermissionsModule/Resources/views/Admin/view.html.twig at line 183

### Steps to reproduce
visit `/permissions/view`

**Comment by Guite** [comment]
> Steps to reproduce
> visit /permissions/view

Works fine on a new installation here...

**Comment by Guite** [comment]
Added some safety checks around the problematic vars in 711ff2538e5b47219ff51f39c0e752323812166f
