### ISSUE TITLE
Permission rules information - modal below overlay 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2903]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.x

### Expected behavior
Permission rules information modal shows above dark overlay or there is no overlay.

### Actual behavior
Permission rules information modal shows below dark overlay.

### Steps to reproduce
Click on Permission rules information link in Administration -> Permissions 

I do not know if this dark overlay is needed there at all.

![screenshot from 2016-06-22 22-05-42](https://cloud.githubusercontent.com/assets/966910/16281661/b17d6d3c-38c5-11e6-9b36-d0e8cb6f8775.png)

**Comment by Guite** [comment]
This problem is caused by mmenu which sets `position: relative` to the whole page. This is something Bootstrap modals do not like (see for example https://github.com/twbs/bootstrap/issues/16148 ).
I added a workaround for that to the Bootstrap theme.
