### ISSUE TITLE
removing the default controller/method routes for a module triggers exception

### ISSUE THREAD

**Issue by craigh** [zikula/core#2905]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.1+ |
| PHP Version | 5.x |
### Expected behavior

upgrading/developing modules function as expected without breaking site
### Actual behavior

site breaks. at least for admin.
### Steps to reproduce

delete the controller/method of the "user" or "admin" route set in the `capabilities` array in the `composer.json` file and the site breaks.

This is because the information is 'cached' in the DB and not refreshed unless the ExtensionsModule main page is visited. This is an issue because the information is used in the creation of the hidden admin _mmenu_. and so the site throws an exception of 'route not found'.

Perhaps the creator could wrap the route generation in a try/catch block and deal with routes not found some other way.

**Comment by craigh** [comment]
one solution here might be to create a page that does not display the mmenu. This page could be used to refresh extensions. maybe this could be done as a 'pass through' page and not display anything at all, then redirect.

**Comment by Guite** [comment]
> Perhaps the creator could wrap the route generation in a try/catch block and deal with routes not found some other way.

I think this is the way to go during creation of the mmenu. If a route is not found the mmenu could display a warning message instead.
