### ISSUE TITLE
[Users] Auto-sync email address from authenticationMethod provider

### ISSUE THREAD

**Issue by craigh** [zikula/core#2906]
on registration, a user's email address is 'harvested' from the provider. Currently, this is static and never updated.

It seems _unlikely_ but _possible_ that the email stored at the provider could change and therefore the copy maintained in the zikula user db should be updated.

perhaps this can be checked and updated based on some settings (e.g. every _30_ days) or maybe it is easy enough to check overtime.

**Comment by Guite** [comment]
closing as unneeded
