### ISSUE TITLE
Using "zikula_core.common.theme.asset_helper" to Resolve Does Not Support Absolute URLs

### ISSUE THREAD

**Issue by shefik** [zikula/core#2910]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.6

### Expected behavior

There can be certain cases where an absolute URL is needed, instead of a relative path.

### Actual behavior

Using "zikula_core.common.theme.asset_helper" to Resolve Does Not Support Absolute URLs.

**Comment by craigh** [comment]
Why does it need to?

**Comment by shefik** [comment]
It needs to support it for SEO purposes. There are cases where an absolute URL is needed to be set in a meta tag. For example, when setting the `og:image` meta tag, an absolute URL is needed, instead of a relative path.

**Comment by craigh** [comment]
I'm still not sure you are using the service for its intended purpose. please show more code and provide more explanation.

**Comment by Guite** [comment]
I am going to investigate this one within the next days.

**Comment by craigh** [comment]
ping @shefik 

> please show more code and provide more explanation.

**Comment by Guite** [comment]
@shefik can't you just prepend the base url in such cases?

Example: https://github.com/zikula/core/blob/1.4/src/system/PageLockModule/Api/LockingApi.php#L140

Could probably be changed to:
```
$this->jsAssetBag->add(\System::getBaseUrl() . $this->assetHelper->resolve('@ZikulaPageLockModule:js/PageLock.js'));
```

**Comment by Guite** [comment]
Closing due to lack of response.
