### ISSUE TITLE
Enabling "trimwhitespace" not working in Twig-based theme

### ISSUE THREAD

**Issue by shefik** [zikula/core#2911]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.2.6

### Expected behavior

Notice: The 'trimwhitespace' output filter trims leading white space and blank lines from the template source code after it is interpreted, which cleans-up the code and saves bandwidth.

### Actual behavior

Enabling "trimwhitespace" not working in Twig-based theme.

### Steps to reproduce

Try to enable "trimwhitespace" in the Settings module here:

`/theme/admin/config`

**Comment by craigh** [comment]
Twig provides functionality to [remove whitespace natively](http://twig.sensiolabs.org/doc/tags/spaceless.html) but removing it later is not as easy as it sounds. (see the second note on that page, "If you want to create a tag...")

**Comment by Guite** [comment]
Maybe using a kernel response listener?

**Comment by Guite** [comment]
Fixed in #2992
