### ISSUE TITLE
"Enable CSS/JS combination" Not Working

### ISSUE THREAD

**Issue by shefik** [zikula/core#2912]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.x |
| PHP Version | 5.6 |
### Expected behavior

CSS and JS is expected to be combined, with GZ and CSS minification enabled.
### Actual behavior

CSS and JS are not combined. Using a Twig-based theme.
### Steps to reproduce

Try to enable the settings at `theme/admin/config`.

**Comment by craigh** [comment]
I don't think this will be possible using twig.
