### ISSUE TITLE
UsersModule/ZAuthModule improvements

### ISSUE THREAD

**Issue by craigh** [zikula/core#2915]
- ~implement auto-register setting (see todo in AccessController) to allow attempts to _login_ to auto-create a registration~
- [x] send notification to pending registrations that are deleted (todo in UserAdministrationController::deleteAction)
- [x] ZAuth: make list amount display configurable (currently hardcoded to 25 in UserAdministrationController)
- ~Add ability to 'pair' (or merge) two or more accounts so that authenticating via e.g. Github can point to the same ZikulaUser as authenticating via email or any other method.~ (moved to #4197)

**Comment by rallek** [comment]
User should be able to delete himself. This would be a nice feature as well.

**Comment by Guite** [comment]
Dup of #1322
