### ISSUE TITLE
Use Bootstrap theme for jQuery UI

### ISSUE THREAD

**Issue by craigh** [zikula/core#2917]
https://cdn.rawgit.com/arschmitz/jqueryui-bootstrap-adapter/v0.3.0/index.html

**Comment by Guite** [comment]
In the meanwhile 1.12.1 is available and used by composer.

**Comment by Guite** [comment]
@craigh  In my opinion this ticket can closed. Afaik we use jQuery UI only for drag n drop. For all other aspects we utilise bootstrap components directly.

**Comment by craigh** [comment]
My interest was in the bootstrap theme for jQueryUI so to integrate it better. reschedule the ticket if you prefer.

**Comment by Guite** [comment]
Rescheduled for 1.4.5 and updated title/description above.

**Comment by Guite** [comment]
Asked for adding composer file at https://github.com/arschmitz/jqueryui-bootstrap-adapter/issues/3

**Comment by Guite** [comment]
Also check if this would make https://github.com/bootstrap-plus/bootstrap-jqueryui needless.

**Comment by Guite** [comment]
Closing as invalid: project is inactive for several years and not ready for Bootstrap 4.
