### ISSUE TITLE
Review install doc location

### ISSUE THREAD

**Issue by Guite** [zikula/core#2925]
The installation description file is expected as `/INSTALL-1.4.0.md` here:

https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/config/routing/routing.xml#L31
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/DocController.php#L63

But in the built core there is `/docs/en/INSTALL-1.4.md` as shown here:

https://github.com/zikula/core/blob/1.4/build.xml#L112

**Comment by craigh** [comment]
maybe dup #2840 (b)

**Comment by Guite** [comment]
Correct. Closing.
