### ISSUE TITLE
Use QA tools

### ISSUE THREAD

**Issue by Guite** [zikula/core#2927]
Links: see [badges here](https://github.com/zikula/core/blob/master/README.md)

Proposed order of improvement:

1. SensioLabsInsight
2. CodeClimate
3. Scrutinizer

**Comment by Guite** [comment]
For reference:

https://github.com/integrations/code-climate
https://codeclimate.com/features
https://codeclimate.com/browser-extension
https://codeclimate.com/oss

**Comment by Guite** [comment]
See also:

https://github.com/integrations/sensiolabsinsight
https://insight.sensiolabs.com/features-developers
https://insight.sensiolabs.com/pricing

**Comment by Guite** [comment]
http://fabbot.io

**Comment by craigh** [comment]
reopen if needed.

**Comment by craigh** [comment]
@Guite - tell me more of what you have in mind here

**Comment by Guite** [comment]
Eliminate errors found by the different tools. You  can postpone that to a later milestone.

**Comment by craigh** [comment]
wouldn't that just be an ongoing effort? I don't see a need to have an open ticket for that. If they tools raise specific issues, we could create tickets specific to those, but I don't see a purpose to a _general purpose_ ticket like this.

**Comment by Guite** [comment]
This issue is mainly for that somebody actually cares about the tools results. If I would now start creating specific tickets for the existing issues this would flood the issue tracker with dozens (hundreds) of tickets.

**Comment by craigh** [comment]
I agree but by the same token how do we ever know that this ticket is complete?

**Comment by Guite** [comment]
We won't know, but we will decide.

**Comment by Guite** [comment]
Enough adjustments and fixes for 2.0. Closing.
From now on we should fix remaining issues on occasion during editing a file anyway.
