### ISSUE TITLE
Charset is Not Valid

### ISSUE THREAD

**Issue by shefik** [zikula/core#2928]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.6

### Expected behavior

The charset for the meta tag should be set as UTF-8.

### Actual behavior

In the file `/system/ThemeModule/EventListener/DefaultPageVarSetterListener.php`, this line:

`$this->pageVars->set('meta.charset', \ZLanguage::getDBCharset());`

Sets the charset as `utf8`, which is incorrect.

### Steps to reproduce

Run your site through the W3C validator at https://validator.w3.org/nu/.

**Comment by Guite** [comment]
I will provide a fix for this by adding a dedicated method for mapping db charsets to output charsets. This method needs to be extended in future, because several possible db charsets are not valid in the output, too.
