### ISSUE TITLE
Legacy theme content not wrapped in helper div

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2935]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior
Legacy theme content wrapped in helper div

### Actual behavior
Helper div is not preset.

### Steps to reproduce
Install 1.3.x theme activate, set as default - check if helper div is present in source.

This is due to $this->toplevelmodule beeing always false here https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/View/Theme.php#L328

**Comment by craigh** [comment]
"Helper"?

**Comment by Kaik** [comment]
Yes styling helper ```<div id="z-maincontent" class=" z-module-zikulasettingsmodule">```

**Comment by Kaik** [comment]
For some reason, the request inside VIew does not contain needed attributes to determine $this->toplevelmodule here https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/View.php#L206 

Below there are dump's 
```    dump($masterRequest);
        dump($this->request);
```
and profiler screenshoot of a request which contain those attributies.
Both images are cropped out of the same page. 

![screenshot from 2016-08-19 12-43-37](https://cloud.githubusercontent.com/assets/966910/17807621/107a938c-660c-11e6-8b95-9700f8e790c4.png)
![screenshot from 2016-08-19 12-49-09](https://cloud.githubusercontent.com/assets/966910/17807620/1076f254-660c-11e6-9b5d-643f697a1d46.png)

**Comment by craigh** [comment]
are you only looking on the homepage (if News is set as homepage, for example) or do you mean on the News Page directly? Or do you mean in something else?

**Comment by Kaik** [comment]
Div should be present on any page that displays module content above screenshots is from http://core.desktop.local/users/account

**Comment by craigh** [comment]
While I could not reproduce the behavior you describe, I did find a separate issue* that I can fix. With my fix*, this is what I have:

![screen shot 2016-08-19 at 3 49 16 pm](https://cloud.githubusercontent.com/assets/350048/17822498/7ed02fa4-6625-11e6-9f60-f9f324851345.png)
![screen shot 2016-08-19 at 3 49 57 pm](https://cloud.githubusercontent.com/assets/350048/17822501/80cbc4a8-6625-11e6-8dd8-326eec87f091.png)
![screen shot 2016-08-19 at 3 50 35 pm](https://cloud.githubusercontent.com/assets/350048/17822503/828d9dd4-6625-11e6-8c30-290fb777b4fe.png)

* the separate issue was simply that the module name is wrong in the styling class. The fix is quite minor and not related. If I delete my fix, I still get something like `<div id="z-maincontent" class="z-module-news user view">` on every page instead of the proper class....

**Comment by Kaik** [comment]
I have checked my clone it is up to date and I still cannot see this div I will switch now to prod maybe it is due to env
![screenshot from 2016-08-19 22-05-08](https://cloud.githubusercontent.com/assets/966910/17822790/4aebd8d0-6659-11e6-935a-129841c17735.png)

**Comment by Kaik** [comment]
Same in prod no div hmm... this is crazy...

**Comment by craigh** [comment]
try `composer install`

**Comment by craigh** [comment]
make sure you are on branch 1.4

**Comment by Kaik** [comment]
```
Installing dependencies (including require-dev) from lock file
Nothing to install or update
```
I'm on 1.4 cleaned I will reinstall it again within few minutes. The only difference is that I use virtual server so instead 127.0.0.1... I have domain like core.desktop.local

**Comment by craigh** [comment]
`git status` ?

**Comment by Kaik** [comment]
```
[Kaik@KM5Desktop core]$ git status
On branch 1.4
Your branch is up-to-date with 'origin/1.4'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        nbproject/

nothing added to commit but untracked files present (use "git add" to track)
[Kaik@KM5Desktop core]$ 

```

**Comment by Kaik** [comment]
Let me reinstall this I will actually install another clone for Dizkus dev and I will test this now.

**Comment by craigh** [comment]
@Guite and @cmfcmf and @robbrandt

can you attempt to confirm this bug? I cannot, and @Kaik still gets it.

**Comment by Kaik** [comment]
Ok, I cannot reproduce this on a server so there is something wrong with my local setup. Probably with virtual servers I have no idea. I'm closing it then.

**Comment by Guite** [comment]
Awesome :100:
