### ISSUE TITLE
Unable to find template "ZikulaThemeModule:Theme:setAsDefault.html.twig"

### ISSUE THREAD

**Issue by shefik** [zikula/core#2937]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

ZikulaAndreas08Theme as the default theme.

### Actual behavior

Error thrown at `/theme/admin/makedefault/ZikulaAndreas08Theme`:

```Unable to find template "ZikulaThemeModule:Theme:setAsDefault.html.twig" (looked into: /vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).```

### Steps to reproduce

Try to set ZikulaAndreas08Theme as the default theme, if it not already the default.

**Comment by Guite** [comment]
Can not reproduce this. Changed default theme without problems.
Please check whether `system/ThemeModule/Resources/views/Theme/setAsDefault.html.twig` exists.
If yes can you please retest using 1.4.3-git?

**Comment by Guite** [comment]
ping @shefik

**Comment by craigh** [comment]
I cannot reproduce this. Please reopen if you can confirm and reproduce behavior.
