### ISSUE TITLE
Combine native uname login method with native email

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2951]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.3 |
| PHP Version | 5.6 |

Before we had three choices - login via user name, email or both.
When we activate both methods each method is displayed separately which is kind of weird... Register via user name or register via email both methods ask for same things this is very confusing.
Same for logging in. Both methods are so similar that we can (should) merge those.

The way I see it:
case: uname only 
        Registration form as it is
        Log in box - "Enter your user name" 
case email only
        Registration form as it is 
        Log in box - "Enter your email" 
case both
        Registration form as it is 
        Log in box - "Enter your username or email"

**Comment by Guite** [comment]
@craigh I suggest to move this to 1.5.0

**Comment by craigh** [comment]
hmm - I was thinking of closing it as won't implement. I'm not sure I like the idea.

**Comment by Kaik** [comment]
Hi, I was playing with FOSUserBundle and seen this option and I think it is a nice feature especially in a case when both log in via email and log in via username option in Zikula is on.
http://symfony.com/doc/current/bundles/FOSUserBundle/logging_by_username_or_email.html
When both options in Zikula are on it looks kind of confusing there are both options listed and both ask mostly for the same kind of input and it would be cleaner/less confusing when only one option is displayed in this case.
By option, I mean all the places where both ways are displayed separately so log in button with dropdown in top bar etc...

**Comment by craigh** [comment]
turns out it was easier than I expected because the Authentication system I wrote is so good. 😜

**Comment by craigh** [comment]
![screen shot 2017-04-07 at 5 45 03 pm](https://cloud.githubusercontent.com/assets/350048/24820971/f87d1ad4-1bb9-11e7-9623-559a1062f1bb.png)

**Comment by Kaik** [comment]
Awesome :+1: Thank You!
