### ISSUE TITLE
Login issues/500 Internal Error - Nesting limit of 100 exceeded

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2952]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.43
| PHP Version       | 5.55.26

### Expected behavior

Logging in keeps you logged in for more than one click

### Actual behavior

Logged out after one click

### Steps to reproduce

Haven't been able to reproduce.

This was the first login attempt after an initial installation last night.  Login failed initially due to typos or not remembering what password I used on this test installation on my local Powerbook.  However after a few tries I was able to log in.  I found the new side bar menu  and clicked on it, then selected Administration Panel.  I was presented with a login page instead.  I logged in again, used the side bar menu again, and this time received a "500 Internal Server Error Nesting Limit of 100 Exceeded" (If I remember the verbiage correctly).  I then set the debug value to be true, and noted that a full stack trace was produced.  Before copying it, I logged out and logged in again; this time however there aren't any  login issues or 500 errors, everything seems to work.

So, there is an issue here somewhere but I don't have a stack trace for you. Sorry.  Possibly an issue with cookies if there are failed logins?

**Comment by cmfcmf** [comment]
This is an issue with XDebug, also see https://github.com/zikula/core/issues/2880 or http://stackoverflow.com/questions/13213378/what-is-causing-a-maximum-function-nesting-level-error-in-symfony-2-1-and-twig.

**Comment by robbrandt** [comment]
Thanks!
