### ISSUE TITLE
Module's Route No Longer Available During Upgrade

### ISSUE THREAD

**Issue by shefik** [zikula/core#2960]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

All routes should be available at all times.

### Actual behavior

If a module needs to be upgraded, its routes are not available, if the route is in the theme directly via a Twig plugin. As a result, the entire site breaks.

### Steps to reproduce

Try to upgrade a module

**Comment by craigh** [comment]
This ticket makes no sense.

> Try to upgrade a module

upgrades work fine. I just tested several different cases. You must provide actual reproducible behaviors.

closing as not core.
