### ISSUE TITLE
1.4.2 upgrade error: There was an error upgrading to Core 1.4.2

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#2965]
I'm trying to upgrade from 1.3.10 to 1.4.2 and followed the UPGRADE.md. After some initial issues where I was not able to start the upgrade routine due to being redirected to /install instead up /upgrade, I was able to access the upgrade wizard.
After clicking upgrade I was welcomed with following screen which sais: There was an error upgrading to Core 1.4.2 but the right column sais: Upgrade to Core 1.4.1 = check

![Upgrade error](http://www.amc-idstein.de/files/zk142_upgrader_error.png)

After clicking Finish, I got eror 500 presented. Nothing happens. Any suggestions how to proceed?
Thanks much.

**Comment by craigh** [comment]
The error is expected and nothing really (a lack of a return value of true from a method). This has been corrected already in the code.

The 500 Error is probably not related.

Do you have a PHP log or something else?

Also - tell more about your environment, PHP, Apache, etc.

**Comment by craigh** [comment]
actually - now that I am thinking about it, you *DON'T WANT* to upgrade to 1.4.2.

really.

The upgrade is seriously broken - the BlocksModule content will be *_erased entirely_*. There is nothing that can be done until the release of 1.4.3. 😞 

Sorry about that. Core-1.4.2 did not receive enough testing before release.

the fix I referenced above is [this](https://github.com/zikula/core/commit/c1944f4a6a7a82c82873f9f4524479b4a27ff8cc#diff-9838480a5fa1f9889ae5e119eb71b814R181)

**Comment by craigh** [comment]
http://zikula.org/blog/display/2016/8/13/serious-core-142-upgrade-bug-discovered/

**Comment by craigh** [comment]
If you still have your (botched) upgraded DB, try this:

via PHPMyAdmin (or whatever DB client you have available), delete ALL the contents of the `blocks` table and the `blocks_placements` table.

then what happens?

**Comment by MrMontesa** [comment]
Hey Craigh,
Thanks for your swift reply and looking into this issue.
I've emptied blocks and block_placements table but nothing happens. Still the 500 error.

Unfortunatly I dont have access to apache error or PHP logs. Its my public hosted testbed. Generally the requirements should be ok, as I do run other ZK 1.4.2 installs in that environment with no issues. My PHP environment can be seen [here](http://zk12.amc-idstein.de/phpinfo.php).

Since you fixed the issue already does that mean I should give it a try with upgrading from githubs 1.4 branch?

**Comment by MrMontesa** [comment]
I gave it a try with latest build fom CI server, but ended up in error 500 as well. Then I just downloaded the latest source from Github and copied the 2 files referenced in the blocks fix into a 1.4.2 installation and ran the upgrade again.

The upgrade succeeded and I got redirected to the upgraded page. There I do get error messages like "Blocks not currently available". You can see [here](http://zk12.amc-idstein.de/zk142/).
Emptied the 2 blocks tables again with no change in behavior.

You want me to do any further troubleshooting? Or do you have an idea how to get it running?
thanks

**Comment by craigh** [comment]
can you send me a copy of your db? craigh@mac.com

**Comment by craigh** [comment]
closing as not core. the core issues have already been addressed and the main problem here is data-corruption.
