### ISSUE TITLE
Search settings or plugins not working correctly

### ISSUE THREAD

**Issue by craigh** [zikula/core#2967]
![screen shot 2016-08-14 at 6 55 31 pm](https://cloud.githubusercontent.com/assets/350048/17652671/c71aae52-6250-11e6-98ef-fea3761609fa.png)

| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior
list of modules/plugins with checkboxes

### Actual behavior
see pic.

### Steps to reproduce
visit `/search/config/config` 

I had installed News first so there are 2 checkboxes, but after disabling News, there is only one (unlabeled) checkbox.

**Comment by Guite** [comment]
Duplicate of #2861

**Comment by craigh** [comment]
![screen shot 2016-08-19 at 11 34 02 am](https://cloud.githubusercontent.com/assets/350048/17815106/dbf3dd7c-6600-11e6-98f1-bf3004fa8576.png)

seems to not be fixed :(

**Comment by Guite** [comment]
Did you clear your cache? Otherwise it uses the old Twig template.

**Comment by craigh** [comment]
yes, but will try again

**Comment by craigh** [comment]
oops. wrong branch locally...

**Comment by craigh** [comment]
![screen shot 2016-08-19 at 11 37 53 am](https://cloud.githubusercontent.com/assets/350048/17815246/6518399a-6601-11e6-891b-3ad2b47bc45f.png)
