### ISSUE TITLE
Zauth: Error: Undefined class constant 'DEFAULT_PASSWORD_REMINDER_ENABLED'

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2970]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.5.26

### Expected behavior
Loads a content page

### Actual behavior
`[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Undefined class constant 'DEFAULT_PASSWORD_REMINDER_ENABLED'
    at n/a
        in /Users/robbrandt/Documents/htdocs/Conference/system/ZAuthModule/Form/Type/ChangePasswordType.php line 80

    at Zikula\ZAuthModule\Form\Type\ChangePasswordType->configureOptions()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php line 53

    at Symfony\Component\Form\AbstractType->setDefaultOptions()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php line 253

    at Symfony\Component\Form\ResolvedFormType->getOptionsResolver()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php line 156

    at Symfony\Component\Form\ResolvedFormType->createBuilder()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php line 91

    at Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy->createBuilder()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php line 114

    at Symfony\Component\Form\FormFactory->createNamedBuilder()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php line 91

    at Symfony\Component\Form\FormFactory->createBuilder()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php line 40

    at Symfony\Component\Form\FormFactory->create()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 282

    at Symfony\Bundle\FrameworkBundle\Controller\Controller->createForm()
        in /Users/robbrandt/Documents/htdocs/Conference/system/ZAuthModule/Controller/AccountController.php line 323

    at Zikula\ZAuthModule\Controller\AccountController->changePasswordAction()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at call_user_func_array:{/Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144}()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
        in /Users/robbrandt/Documents/htdocs/Conference/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 193

    at Symfony\Component\HttpKernel\Kernel->handle()
        in /Users/robbrandt/Documents/htdocs/Conference/index.php line 23

    at {main}()
        in /Users/robbrandt/Documents/htdocs/Conference/index.php line 0`

### Steps to reproduce
Go to http://localhost/{directory}/zauth/account/change-password.  The only config changes I have made are "low" security.

**Comment by craigh** [comment]
I cannot reproduce the behavior. I changed to "low" security and loaded this page ok.

![screen shot 2016-08-15 at 8 20 35 pm](https://cloud.githubusercontent.com/assets/350048/17684014/d649d1b6-6325-11e6-94f7-a0760b4e42be.png)

**Comment by craigh** [comment]
the constant is defined [here](https://github.com/zikula/core/blob/ce9260a54d368a13351dc9a915f36313ef2df7c7/src/system/ZAuthModule/ZAuthConstant.php#L44)

if you are working from an upgraded DB and you aren't using the latest builds (maybe a few days old?) then the ZAuth module was not installed on upgrade until very recently. I just made the upgrade work over the last few days.

**Comment by robbrandt** [comment]
No, it's a fresh install.

**Comment by craigh** [comment]
I cannot reproduce. it works for me. Can you try to reinstall?

**Comment by robbrandt** [comment]
I don't see this in build 115.  I'll close.
