### ISSUE TITLE
disabling anonymous sessions nearly impossible in Symfony

### ISSUE THREAD

**Issue by craigh** [zikula/core#2976]
According to the [Symfony docs](http://symfony.com/doc/current/session/avoid_session_start.html)

It is essentially impossible to disable sessions for anonymous users. 

> Sessions are automatically started whenever you read, write or even check for the existence of data in the session. This means that if you need to avoid creating a session cookie for some users, it can be difficult: you must completely avoid accessing the session.

Because Zikula makes *extensive* use of flash messages and third-party modules cannot be expected to always check to see if a session has started before displaying flash messages, I think the better answer is to remove the option from our settings since it is essentially meaningless anyway.

removing this won't be difficult IMO. We should also document the issue.

opinions?

**Comment by Guite** [comment]
if I remember correctly disabling guest sessions hasn't worked correctly in 1.3.x anyway.

**Comment by Guite** [comment]
Solved in #2989
