### ISSUE TITLE
Two Sessions stored per page view in Safari

### ISSUE THREAD

**Issue by craigh** [zikula/core#2977]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.3 |
| PHP Version | 5.5.26 |
| Browser | Safari |
### Expected behavior

one session stored per pageview
### Actual behavior

two sessions stored
### Steps to reproduce

use Safari
clear the `session_info` table
reload any page
note there are two entries in the table
after logging in, one is updated the other orphaned.

I've traced this to the `\Zikula\SearchModule\Listener\FrontControllerListener`
if I comment out the last line:
`$this->headerAssetBag->add($headerCode);`
then the problem disappears.

I see this listener is trigger on `KernelEvents::REQUEST` but since it is modifying the RESPONSE, it seems like it should trigger on `KernelEvents::RESPONSE`.

the note in the listener states:

> Make sure to load the handler _every time_ and _before_ the routing listeners are running (32).

@cmfcmf you wrote this listener. can you explain what's going on? Why on `REQUEST` and not on `RESPONSE`? what is the note about?

**Comment by craigh** [comment]
So, it appears that for each 'normal' request, a second request is made to `/search/opensearch` and somehow a second response is sent. This doesn't seem right to me, but maybe it is.

**Comment by craigh** [comment]
My theory is that the browser finds the open search link in the page content and sends a **second request** for the xml document. I cannot find anything online about how the browser deals with it. Because the browser has to immediately add the link to its search bar my theory seems reasonable.
The problem is that it starts a second session which is undesired, but I'm not sure this is avoidable (see #2976).

**Comment by craigh** [comment]
frustratingly... visiting `/search/opensearch` directly does **not** begin a session... ⛵

**Comment by craigh** [comment]
oops - that is wrong. it does.

**Comment by craigh** [comment]
I've been playing with this now for 7 hours or so. Very frustrating. There are a few issue contributing to it. I've corrected some locally without pushing them to github. I've go it to the point where if I visit `/search/opensearch` directly and do not have a previous session cookie, that it will not begin another. But if I visit `/` then I get two sessions again and still the second is related to the same listener.

I've found a few things along the way, but it is difficult to even explain what is happening.

```
  #10     Zikula\Bundle\CoreBundle\EventListener\SiteOffListener::onKernelRequestSiteOff()               200       
  #11     Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest()                128       
  #12     Zikula\SecurityCenterModule\Listener\FilterListener::idsInputFilter()                          100       
  #13     Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest()                 48        
  #14     Zikula\Bundle\CoreBundle\EventListener\RouterListener::onKernelRequest()                       32        
```

from what I can tell, `session = null` in the request object until the `SessionListener::onKernelRequest` pulls an 'empty' (unstarted) session from the container and adds it to the request. This matters because in the `RouterListener::onKernelRequest` looks for any non-null value and if present starts the session and then the second session row is added because of that.

It's not clear to me if the container *should* have a non-started session object as a default or if this is some mistake/peculiarity of zikula. If `session == null` when `RouterListener::onKernelRequest` fires, then I think the problem would be solved. But I can't figure it out.

@cmfcmf I'm hoping you will give this a shot.

**Comment by craigh** [comment]
I pushed wheat I was doing to the PR just for discussion. It's kind of a mess.

maybe I am now seeing the relevance of your comment:
> Make sure to load the handler every time and before the routing listeners are running (32).

but I'm not sure.

maybe if the listener is moved BACK to the REQUEST event and in the place you mention - along with some of my other fixes, it would work? I don't know.

I'm tired of it today.

**Comment by craigh** [comment]
> maybe if the listener is moved BACK to the REQUEST event and in the place you mention - along with some of my other fixes, it would work? I don't know.

tried to move it back to the REQUEST event and same problem... with the downside of creating a session even when only visiting `/search/opensearch` directly...

😞

**Comment by cmfcmf** [comment]
> Expected behavior
> 
> one session stored per pageview
> 
> Actual behavior
> 
> two sessions stored

I don't see any of this. It works correctly for me with the current 1.4 branch on PHP 5.5.9 and in prod mode.

**Comment by cmfcmf** [comment]
Same in dev/debug mode.

**Comment by Guite** [comment]
Works for me, too (php 7)

**Comment by craigh** [comment]
@cmfcmf @Guite which browser did you use to test?

**Comment by cmfcmf** [comment]
I used Chrome.

**Comment by Guite** [comment]
I used Firefox.

**Comment by craigh** [comment]
I just tested with Chrome and the behavior doesn't occur. Therefore I conclude that this is unique to Safari.

**Comment by Guite** [comment]
Closed.

**Comment by craigh** [comment]
please do not close

**Comment by craigh** [comment]
One idea @Guite had was to generate and dump a static xml file for this instead of using a controller. this would possibly solve the problem. The file would need to be updated if the containing information were changed (e.g. `sitename`, etc)

**Comment by craigh** [comment]
closing this as I don't really care anymore about it. 😝
