### ISSUE TITLE
Checkbox label shown twice

### ISSUE THREAD

**Issue by craigh** [zikula/core#2994]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.5.26

### Expected behavior
only one label

### Actual be
![screen shot 2016-08-19 at 11 47 21 am](https://cloud.githubusercontent.com/assets/350048/17816830/38ddd9f4-6609-11e6-8fee-014dcdf19578.png)
havior

@Guite said
> we need a good criteria to query for deciding whether to display the right-side label or not

but I don't understand what you mean

**Comment by Guite** [comment]
There are checkboxes where we don't want the right-side label (like the one shown above). There are other checkboxes where we need the right-side label though (like search plugins shown at the Search settings page).
Thus we need to decide whether we show this label or not in https://github.com/zikula/core/commit/54fe71ae4b72e5412b6fd00e49caf4edbf4bf019#diff-932fed25e8fdecd9614e912892f68375 And this decision needs some well-defined criteria.

**Comment by craigh** [comment]
I guess my point was where the logic of such a decision would occur and therefore where any flag might be located.

**Comment by Guite** [comment]
If I only knew that :-)

**Comment by Guite** [comment]
Fixed in #3008

**Comment by Guite** [comment]
![screenshot_20160820_103251](https://cloud.githubusercontent.com/assets/277531/17830072/79ff60f2-66c1-11e6-9fd5-33adefcdf580.png)

:smile:
