### ISSUE TITLE
Legacy hooks URLs are broken

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2999]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 build 129
| PHP Version       | 5.5.26

### Expected behavior
Should show hook config UI

### Actual behavior
500 error 

### Steps to reproduce
Install Content and Scribite
Go to http://{domain}/hooks/content
http://{domain}/hooks/scribite

These COULD be module issues but since it shows up in more than one module, a core fix would be helpful.

**Comment by cmfcmf** [comment]
This is a miracle. The problem is that the module name in the url is lowercased and should be uppercased. _However_, if I visit `http://{domain}/hooks/Formicula`, the generated hook link is correct. On all other Formicula admin pages, it is lowercased.

**Comment by craigh** [comment]
> This is a miracle

Miracles are using a very positive thing... but your description sounds more negative. Does this have to do with my legacy routes in CoreBundle?

**Comment by cmfcmf** [comment]
I have no idea :(

**Comment by craigh** [comment]
might be a good place to start looking?

**Comment by robbrandt** [comment]
Using uppercase does help.

http://localhost/zcs1/hooks/AdvancedPolls loads the page
http://localhost/zcs1/hooks/Content loads the page
http://localhost/zcs1/hooks/News loads the page
http://localhost/zcs1/hooks/Scribite loads the page.

All of those give a 500 error unless manually altering case.

**Comment by Guite** [comment]
@robbrandt can you please test the solution in https://github.com/zikula/core/pull/3003 and confirm if it works for you?
