### ISSUE TITLE
This is issue #3000 !

### ISSUE THREAD

**Issue by craigh** [zikula/core#3000]
Congratulations to everyone that has ever contributed to Zikula in **any** way! PRs, bug reports, feature requests - all that has lead to 3000!

THANK YOU!

**Comment by cmfcmf** [comment]
We're also pretty close to 10000 commits since Zikula 1.2.0.

**Comment by Guite** [comment]
:balloon: :balloon:

**Comment by craigh** [comment]
refs comments in #2000

**Comment by craigh** [comment]
and #1000

**Comment by Guite** [comment]
ZCS continues :construction_worker:
