### ISSUE TITLE
js alerts popup when configuring hooks

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#3004]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 build 129
| PHP Version       | 5.5.26

### Expected behavior
To be able to use the UI without OK-ing a bunch of meaningless errors

### Actual behavior
OK-ing a bunch of meaningless errors.  They were something like "error:0" in as js popup.

### Steps to reproduce

Kind of unpredictable.  I installed these modules: Content, News, Advanced Polls, Scribite, EZComments.  I first experienced the errors when configuring hooks in Scribite (/hooks/Scribite) clicking on checkboxes and reading options.  I also experienced them in News while setting a hook for EZComments.

**Comment by Kaik** [comment]
I'm working on this but I'm experiencing other errors. Please provide versions of the modules you are using.

**Comment by craigh** [comment]
rob won't be available for a few hours I think.

**Comment by Kaik** [comment]
I cannot replicate this it might be fixed by #3003 @robbrandt  could you check if error still occurs and if so could you please add ``` console.log(result); ```
In ```/web/bundles/zikulahook/js/hookui.js``` below or above lines 175 and 315 then post console output.
If you have any problems with it let me know on slack. 
This might be a timeout error - machine dependent where there is lots of providers and subscribers.

**Comment by Kaik** [comment]
In addition, you can rise Time-out for Ajax connections (10 000) in General Settings and see if errors are still present.

**Comment by Kaik** [comment]
Just checked and it does show 0:timeout error for Time-out for Ajax connections (50)  so it's not it I guess.

**Comment by robbrandt** [comment]
Uses:
Advanced Polls 3.0.0
EZComments 3.0.1
Content 4.2.1
News 3.1.1
Scribite 5.0.1

Not a lot of extensions, really. This is a new installation for ZCS, and I selected a combination of recently updated (in git), or very important, or hook provider modules.

**Comment by robbrandt** [comment]
However it is installed on localhost and it's not particularly fast, so it could be a timeout issue of sorts.

**Comment by robbrandt** [comment]
I will do a fresh Zikula install shortly and try again.

**Comment by Kaik** [comment]
Timeout will result in ```0:timeout``` you write that error text was ```error:0``` this is different so something else caused those errors. Let me know if the issue is still present on fresh install.

**Comment by robbrandt** [comment]
I couldn't remember the error exactly because I didn't write it down when I saw it.  I assumed I'd be able to reproduce it.  So it may in fact be 0:timeout. As I said, it was 'They were something like "error:0""

**Comment by craigh** [comment]
can you test now and see if you still get errors attempting to do the same tasks?

**Comment by craigh** [comment]
@robbrandt can you test this? I'd like to close it if it has been fixed! 😄

**Comment by craigh** [comment]
I've just been testing this. I installed, Scribite (nearly 5.0.2) and current versions of News, EZComments, Content. I had no trouble in adding and subtracting hooks from both the provider page (e.g. from `/hooks/Scribite`) or from a subscriber page (`/hooks/News`).

I was also VERY pleasantly surprised how well these modules are functioning in a 1.4.3 environment. Everything is working! Sure there are some layout issues - especially in Content, but it still works.

Closing this. @robbrandt if you test and find problems, please reopen.

**Comment by robbrandt** [comment]
I couldn't replicate this in build 155.
