### ISSUE TITLE
upgrade documentation is confusing

### ISSUE THREAD

**Issue by craigh** [zikula/core#3012]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3

`UPGRADE-1.4` states in one location (pre upgrade routine):
  - copy from your backup ``/userdata``, ``/modules`` and your theme to your new upload. The folders of your modules and themes should be at the exact same place like your backup.

and then later says (post upgrade routine):
  - Return any 1.3.x-compatible modules, themes and plugins to the appropriate directory and run each
    upgrade independently.

it should say one or the other. I think it is supposed to be the latter...

**Comment by Guite** [comment]
The latter is probably correct unless the Extensions module drops any information if the modules can not be found?

**Comment by craigh** [comment]
I cannot remember what happens, but I have always told users in support requests to not add their module back until the core upgrade is complete.
