### ISSUE TITLE
automate updating of translations in core

### ISSUE THREAD

**Issue by craigh** [zikula/core#3020]
in the build add

`php app/console translation:extract template --dir=system --output-format=po --output-dir=app/Resources/translations --enable-extractor=jms_i18n_routing --dir=lib/Zikula/Bundle`

**Comment by craigh** [comment]
update https://github.com/zikula/core/wiki/Release-Process afterwards

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/401c6edf4af54b8f797f61994c6f52b92c4ef491/build.xml#L127

shows
`        <exec command="php ${packagepath}/app/console translation:extract --enable-extractor=jms_i18n_routing --dir=${packagepath}/app/logs --output-dir=${packagepath}/app/Resources/translations template" checkreturn="true" passthru="true" />`

so maybe just needs adjustment?

**Comment by Guite** [comment]
Yes, probably.

**Comment by craigh** [comment]
Ive done this and builds are successful again. http://ci.zikula.org/job/Zikula_Core-1.4.3/162/

Should we then remove and .gitigore the current translation files in the repo?

Ping @cmfcmf @guite @phaidon @kaik

**Comment by Guite** [comment]
:+1:

**Comment by craigh** [comment]
if we remove the files, how will translators work? If we do not remove the files, how do we keep them automatically updated? maybe we can move this to a composer command instead?

**Comment by Guite** [comment]
Even if we remove them, they will still be part of CI builds, right? So we could point translators to these?

**Comment by craigh** [comment]
Yes but my thinking was that they will not be available when pulling from github and maybe translators would prefer that?

**Comment by Kaik** [comment]
Ok, so I think translations should be added as the last thing before release.

**Comment by Kaik** [comment]
Something to consider. What if now devs will be changing all the sentences and might not bother that it will generate huge work for translators. On the other hand, some of the sentences are ancient or wrong and we want them to be updated. We need to keep a close eye now on how translations are changing.

**Comment by craigh** [comment]
with respect, I disagree. We need to develop what is appropriate and not worry about "backward-compatible translations".

**Comment by craigh** [comment]
translation files are now removed from the repo and generated and add to the distribution. closing.
