### ISSUE TITLE
Redirect after login is not working

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3021]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior
Redirect to requested url after log in

### Actual behavior
Redirect to home page after log in

### Steps to reproduce
Log out.
Enter secured url like domain.com/zauth/account/change-email 
Log in.

**Comment by craigh** [comment]
pull and test please.

**Comment by Kaik** [comment]
Works when logging in using the form but not working using top bar login. Before both methods failed.

**Comment by craigh** [comment]
closed by #3022
