### ISSUE TITLE
define currently installed version in custom_parameters.yml

### ISSUE THREAD

**Issue by craigh** [zikula/core#3025]
currently we only use the parameter `installed: true|false`. We should expand this to indicate the currently installed version - so something like `installed: 1.4.2` or stay with the boolean and add another parameter of the currently installed version. This would make core upgrade simpler as currently the installed version can only be pulled from the DB.

**Comment by Kaik** [comment]
>or stay with the boolean and add another parameter 

:+1:

**Comment by craigh** [comment]
closed by #3023
