### ISSUE TITLE
Console should not attempt to login

### ISSUE THREAD

**Issue by craigh** [zikula/core#3026]
refs https://github.com/zikula/core/blob/ce9260a54d368a13351dc9a915f36313ef2df7c7/src/lib/Zikula/Bundle/CoreBundle/Console/Application.php#L98-L125

refs #1908, #2093, #2101, https://github.com/zikula/core/commit/71c509bdde0c2210d46809ac438d7cb0f21586cb

I am questioning the appropriateness of attempting to 'login' (inherently an HTTP process) when using zikula via the CLI.

I understand the arguments presented #1908

> - Let's say you execute a console command. 
> - The command calls a `ModApiFunc`. 
> - In there, for some reason, a security check is made.
> - Every security check will fail, as no Zikula user is logged in / no session exists.
> - @shefik wants that Zikula thinks the current user is Admin, when executing a command.

But I think this is wrong moving forward for Core-2.0

This code should be entirely removed from Core-2.0 as the `session` is not available when using CLI and therefore 'logged in' is meaningless.

perhaps some other accommodation will be required to address the initial complaint.

**Comment by robbrandt** [comment]
It may be helpful to look at what other apps do.  We use an open source CRM system called CiviCRM, which installs as a module under Drupal, Wordpress or Joomla.  In CiviCRM, external API access is handled via an API Key, and each CMS user may (or may not) have a key.  When the API is called, the key is passed as a parameter (using php, javascript or smarty) and the calling code inherits the permissions of the owner of the API key used.  It works very nicely.  For exploring the rich API via web browser, there's a nice demo site at http://dmaster.demo.civicrm.org/civicrm/api#explorer.

The API is pretty mature (at v3) but they are working on v4, which will allow complete control of CiviCRM via API; you could actually run "headless" from another web site entirely.

**Comment by craigh** [comment]
The _login_ code has been removed from master and that is enough to close this ticket. Should we implement some other kind of authentication method for use via CLI? I don't know, but that is not the realm of this ticket.
