### ISSUE TITLE
broken module link in admin section after changing module URL setting

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3028]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x.x
| PHP Version       | 5.x

### Steps to reproduce
- Fresh install 1.4.3.
- install module (News, postCal, etc)
- edit module via extensions/module/list
- and rename URL param to someting else (in my case: "PostCalendar" to "kalender")
- save
klick in "PostCalendar" link on adminpanel/panel/5

### Actual behavior
Link is: module=**PostCalender**&type=admin&func=listevents and ends up in error 500.

stacktrace:

```
Error: Call to a member function getName() on null

500 Internal Server Error - FatalErrorException

Stack Trace

in lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php at line 78   -
    {
        $moduleUrl = $request->query->get('module');
        $moduleEntity = $this->extensionRespository->findOneBy(['url' => $moduleUrl]);
        $module = $moduleEntity->getName();
        $type = $request->query->get('type');
        $func = $request->query->get('func');
        $arguments = $request->query->all();
Logs   -

Stack Trace (Plain Text)   -

[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getName() on null
    at n/a
        in /data/web/1/000/027/915/75642/htdocs/zk13.amc-idstein/zk143/lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php line 78

```
### Expected behavior
Link should open correctly as when manuall changing link to: 
Link works when changing to: module=**kalender**&type=admin&func=listevents

**Comment by craigh** [comment]
When I do this the "main" link for PostCalendar is converted to the 'home' (main site home) page link. not to `module=PostCalender&type=admin&func=listevents`. but either is wrong.

@MrMontesa the issue template is there for a reason - please include things like PHP and Core versions in your tickets...

**Comment by craigh** [comment]
This ink in `adminpanel/panel/5`
![screen shot 2016-08-23 at 8 45 25 am](https://cloud.githubusercontent.com/assets/350048/17892190/f8d233ac-690d-11e6-8624-2ecbf5b4f8cf.png)

The link in the slide out menu
![screen shot 2016-08-23 at 8 46 00 am](https://cloud.githubusercontent.com/assets/350048/17892204/0c3f212a-690e-11e6-93bd-b690c1079f7a.png)

**Comment by MrMontesa** [comment]
sorry, here u go:

| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.21
|Administration panel | 2.0.0 
| Symfony     | 2.8.9
