### ISSUE TITLE
Can Smarty be loaded dynamically?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3035]
Is it possible to have Smarty now load only when needed and not be loaded all the time?

**Comment by Guite** [comment]
Would be great for php 7 :+1:

**Comment by Guite** [comment]
Maybe move the `include` statements for Smarty into `Zikula_View`?

**Comment by Guite** [comment]
@craigh @cmfcmf @Kaik any opinion about my proposal here?

**Comment by Guite** [comment]
Not that easy, because Zikula_View is referenced in several classes, like `System` and `DisplayHookResponse`.

**Comment by craigh** [comment]
I now think this is unnecessary. Core-1.4 should behave as it always has. Smarty is deleted from Core-2.0, so no problem. there. closing this.
