### ISSUE TITLE
Twig output filter for protecting mail addresses

### ISSUE THREAD

**Issue by Guite** [zikula/core#3041]
We should consider providing a replacement for this functionality:
https://github.com/zikula/core/blob/1.4/src/lib/util/DataUtil.php#L199

**Comment by craigh** [comment]
how do you consider this a BC Break? The old DataUtil function remains and is functional. I would consider adding this as a feature. IMO.

**Comment by Guite** [comment]
As `DataUtil` is deprecated, it would be a BC break if it was removed without offering a successor ;-)

**Comment by craigh** [comment]
closed by #3041
