### ISSUE TITLE
User Registration minor bugs

### ISSUE THREAD

**Issue by craigh** [zikula/core#3051]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3-rc2
| PHP Version       | 5.6.24-1+deb.sury.org~xenial+1

### Expected behavior
user cannot re-register

### Actual behavior
if attempting to register a second time with the same uname, a new record is created in Users table. And a cascade delete error is shown

![screen_shot_2016-08-28_at_5 32 40_pm](https://cloud.githubusercontent.com/assets/350048/18048472/3c3aec00-6db0-11e6-91b8-bf108b7d55f9.png)

Also a welcome email was sent

When registering properly with a new uname, I received two welcome emails, one had email confirmation link, the other didn't. After confirming, I received the other again.

I think this is intentional because in a way you are registering twice - first in ZAuth and second as a User. I think that is why there are two. But not sure.

### Steps to reproduce

**Comment by Guite** [comment]
@craigh would you please split this into several atomic issues? it unnecessarily raises the hurdle to challenge issues if they mix up multiple concerns

**Comment by Guite** [comment]
The double email thingy is #2089 isn't it?
