### ISSUE TITLE
1.4.3 RC testing: translations missing

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3053]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 RC
| PHP Version       | 5.6.21

### Expected behavior
Proper translation for _UREALNAME, _UFAKEMAIL, etc

### Actual behavior
Seems like no default translation is available for some parts of new zauth module. Specially "User Information" area.

### Steps to reproduce
New RC installed
access: zauth/admin/user/create
All entries in "User Information" section dont have default translation. Only _VARIABLE is displayed.

**Comment by craigh** [comment]
This is an issue with the profile module. And it isn't really a "bug" as much as it is the way it was designed. There are instructions in Profile how to correct this I think.

**Comment by MrMontesa** [comment]
Hey Craigh, 
since Profile module is delivered by Core, it somehow alignes with Core. Would you be able to point to "There are instructions in Profile how to correct this I think"?
I've checked modules/zikula/profile-module for more info but had tough luck. Only found the [Github repo](https://github.com/zikula-modules/Profile) but was unable to get more detailed info.

In regards to user experince it would be good to have this properly set even though it is understandable that this is not a show-blocker.
Thanks for your help.

**Comment by craigh** [comment]
the instructions are at `/profile/admin/help`

**Comment by MrMontesa** [comment]
Thank you!
