### ISSUE TITLE
[1.4.x] With userdata not writable other error messages

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3054]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.4

### Expected behavior
The messages above should be marked as ok.

### Actual behavior
I get messages about missing json and so on

### Steps to reproduce
set all neccessary permission, only userdat to 775. If you set userdata to 777 you can enter your database settinngs
![userdata](https://cloud.githubusercontent.com/assets/493707/18079000/d8769996-6e8e-11e6-8a9b-23d27d6769e6.png)

**Comment by craigh** [comment]
This appears to be exactly how it *should* behave. It is throwing warnings before you install that your environment is not prepared for an installation. Is there something more than the screenshot happening? If not, this is the proper behavior.

**Comment by Guite** [comment]
If I understand correctly the problem is that these warnings appear only if `userdata` has `775` permissions. If the folder has `777` no warnings appear.

**Comment by craigh** [comment]
yes, that is expected. If the web server cannot write to the directory, the warning *should* appear.

**Comment by Guite** [comment]
But other warnings (like about missing json) should either appear always or never, but not depending on the userdata permissions.

**Comment by Portugao** [comment]
Like Axel said, if I set the folder userdata to 777, i can procede the install process. So the other warnings are not correct.

**Comment by craigh** [comment]
please confirm that date.timezone is set, etc. check all the errors

**Comment by craigh** [comment]
I can replicate this error.
