### ISSUE TITLE
1.4.3 RC testing: Admin cannot add user

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3055]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 RC
| PHP Version       | 5.6.21

### Expected behavior
Successfully save new user

### Actual behavior
When saving new user error message pops up:
`Error: Call to a member function register() on null`

Full stack trace from debug:

Stack Trace

    in system/ZAuthModule/Controller/UserAdministrationController.php at line 164   -
                    $this->addFlash('error', implode('<br>', $notificationErrors));
                }
                $mapping->setUid($user->getUid());
                if (!$authMethod->register($mapping->toArray())) {
                    $this->addFlash('error', $this->__('The create process failed for an unknown reason.'));
                    $this->get('zikula_users_module.user_repository')->removeAndFlush($user);
                    $this->get('event_dispatcher')->dispatch(RegistrationEvents::DELETE_REGISTRATION, new **GenericEvent($user->getUid()));**

### Steps to reproduce
install RC
access: /zauth/admin/user/create
populate fields: User name, Email, Repeat Email, tick "set password" and enter password info
click save

**Comment by craigh** [comment]
we need confirmation of this bug. anyone?

**Comment by craigh** [comment]
I can confirm this. It occurs if you leave **Login method** set to "User name or email". If you select either other option, it works correctly.

**Comment by craigh** [comment]
> [1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function register() on a non-object
    at n/a
        in /Applications/MAMP/htdocs/143/system/ZAuthModule/Controller/UserAdministrationController.php line 164

>    at Zikula\ZAuthModule\Controller\UserAdministrationController->createAction()
        in /Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

>    at call_user_func_array:{/Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144}()
        in /Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

>    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
        in /Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

>    at Symfony\Component\HttpKernel\HttpKernel->handle()
        in /Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

>    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
        in /Applications/MAMP/htdocs/143/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

>    at Symfony\Component\HttpKernel\Kernel->handle()
        in /Applications/MAMP/htdocs/143/index.php line 23

>    at {main}()
        in /Applications/MAMP/htdocs/143/index.php line 0

**Comment by craigh** [comment]
Is this a Blocker?

**Comment by craigh** [comment]
I think this is not a blocker because there is a workaround -> choose either EMAIL or UNAME options.
