### ISSUE TITLE
1.4.3 RC testing: edit user view spits HTML code instead of form

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3056]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 RC
| PHP Version       | 5.6.21

### Expected behavior
There should be a form displayed to edit a user

### Actual behavior
On fieldset "Site policies" the form is broken and only HTML code is printed.
`fieldset> <legend>Site policies</legend> <input type="hidden" id="acceptpolicies_csrftoken...`
### Steps to reproduce
install 1.4.3 RC
access: zauth/admin/user/modify/2 or users/admin/user/modify/2

**Comment by craigh** [comment]
sounds like #3046
