### ISSUE TITLE
Is the Core booted twice in the CLI?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3067]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.5.26

It appears that possibly the core is booted twice in the CLI.

@cmfcmf please see https://github.com/zikula/core/blob/1.4/src/app/console#L43 which includes https://github.com/zikula/core/blob/1.4/src/lib/core.php and this boots the core

also see 

https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Console/Application.php#L69-L94 which also boots the Core

but I do not see anywhere in the CLI where the core is `init` e.g. https://github.com/zikula/core/blob/1.4/src/index.php#L18

will you please look into it?

**Comment by cmfcmf** [comment]
Going to look into it.

**Comment by cmfcmf** [comment]
Thank you Craig.

Craig Heydenburg <notifications@github.com> schrieb am Mi., 26. Okt. 2016,
22:14:
