### ISSUE TITLE
Source comments for block always included in markup

### ISSUE THREAD

**Issue by Guite** [zikula/core#3068]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4-dev
| PHP Version       | 7.0

### Expected behavior

Source comments for blocks included only if *Embed template information within comments inside the source code of pages* is activated at `/theme/admin/config`.

### Actual behavior

Comments do always appear.

### Steps to reproduce

Call the main page with bootstrap theme without being logged in. You will find `<!-- Start Top Navigation Block -->` and `<!--  End Top Navigation Block  -->` in the markup.

@Kaik could you please look at this?

**Comment by craigh** [comment]
I've removed the hard-coded comments in the theme templates. This should resolve this ticket. 

> Source comments for blocks included only if Embed template information within comments inside the source code of pages is activated at /theme/admin/config.

this is ancient smarty-related debugging solution and may no longer be needed as the developer toolbar provides some of this information. In any case, it is not (to my knowledge) implemented in any way for twig templates. I'm not sure it _can_ or _should_ be done. I remember elsewhere that @rallek had requested such a feature. How important is this to anyone?

**Comment by craigh** [comment]
OK - so I have created a way to enable exposing the template name in twig templates. It is **not** enabled by the flag in theme settings however, but rather enabled when the `env` is set to `dev`. See pending [PR](https://github.com/zikula/core/issues/3073).

**Comment by craigh** [comment]
closed by #3073
