### ISSUE TITLE
Add documentation for Extension API 

### ISSUE THREAD

**Issue by Guite** [zikula/core#3074]
The extension api defined at https://github.com/zikula/core/blob/1.4/src/system/ExtensionsModule/Api/ExtensionApi.php is not documented in https://github.com/zikula/core/tree/1.4/src/docs/Core-2.0/Api yet.

**Comment by craigh** [comment]
removed Easy Pick because really, this should be refactored to remove several methods. Also, the getModuleInstanceOrNull is deprecated, so there is really only one method there...

**Comment by Kaik** [comment]
getModuleInstanceOrNull is used in ExtensionsModule and I was considering using it in Dizkus but because of that deprecated tag I used a different way.

**Comment by Guite** [comment]
@Kaik see also https://github.com/Guite/MostGenerator/commit/e53d749b50366b66e5a120dc2c75efc319eb8e50
