### ISSUE TITLE
No Login while Site is disabled

### ISSUE THREAD

**Issue by DirkThiele** [zikula/core#3075]
Admin Login is not possible while site is disabled.

| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.5 as well as 5.6

### Expected behavior
Login as Administrator on a disabled site.

### Actual behavior
Login does not work - Redirection to entry point

### Steps to reproduce
Disable site, log-out, log-in

**Comment by craigh** [comment]
I think this was already fixed for Core-1.4.4 in https://github.com/zikula/core/pull/3065/commits/e70f30857315b5ff2f180f55671f40007837a50a

**Comment by craigh** [comment]
If possible, please download http://ci.zikula.org/job/Zikula_Core-1.4.4/lastSuccessfulBuild/ and test this issue

**Comment by craigh** [comment]
this works for me with latest build.
