### ISSUE TITLE
Site Theme Loads at Bottom of "Site Currently Offline" Page

### ISSUE THREAD

**Issue by shefik** [zikula/core#3087]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.3 |
| PHP Version | 5.x |
### Expected behavior

The site theme is loading at the bottom of the "Site Currently Offline" page.
### Actual behavior

Only the "Site Currently Offline" message should display.

**Comment by shefik** [comment]
<img width="1116" alt="offline" src="https://cloud.githubusercontent.com/assets/274862/18839209/28a72c2e-83d8-11e6-97e1-770e43375770.png">

**Comment by shefik** [comment]
<img width="1337" alt="upgrade-theme" src="https://cloud.githubusercontent.com/assets/274862/18842412/e87aad28-83e2-11e6-8063-7da4d703d96c.png">

**Comment by craigh** [comment]
### Steps to reproduce

**Comment by Guite** [comment]
ping @shefik  please explain how to reproduce

**Comment by Guite** [comment]
Not able to reproduce, postponing.

**Comment by Guite** [comment]
Closed to lack of response.

**Comment by craigh** [comment]
this was fixed by https://github.com/zikula/core/commit/f171d66521830017bdb9777c57e1a1825e7c46ba. injecting a PlainResponse() was required.
