### ISSUE TITLE
htaccess rules 

### ISSUE THREAD

**Issue by shefik** [zikula/core#3088]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.3 |
| PHP Version | 5.6 |
### Expected behavior

Matched files should be allowed.
### Actual behavior

Matched files are not allowed.
### Steps to reproduce

The htaccess files have rules for both Apache 2.2 and 2.4. However, even when I have Apache 2.4 installed with the module `mod_authz_core.c`, only the rules for 2.2 work (removing the wrapped conditional statement). The rules for 2.4 block the matched files.

**Comment by Guite** [comment]
Can you please provide a concrete example: which files are blocked? On my local host for example JS files are correctly loaded from both `system` and `web` folders.

**Comment by Guite** [comment]
ping @shefik

**Comment by Guite** [comment]
Closing due to lack of response.
