### ISSUE TITLE
PageLock popup grayes out so cannot proceed

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3095]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

After implemeting fix for #3093, I was able to edit Content pages. On saving the page I get a PageLock Popup where I cant proceed as it is gryed out. Screenshot:
![pagelock_popup](https://cloud.githubusercontent.com/assets/600125/18950884/8157d730-8642-11e6-8350-cbf238910154.png)

### Expected behavior
I'm the only one accessing that Zikula installation as its test-bed. In fact I wont expect any pagelocks since I do have the one and only active session.

### Actual behavior
PageLock popup occured and is grayed out. So I cant even ignore the page lock. I have to log-off in a different tab to get rig of the message. But when editing page again, the popup appears instantly again.

### Steps to reproduce
- edit a page in Content and click save

**Comment by Guite** [comment]
Going to investigate this asap. In the meanwhile you could disable the PageLock module so you can continue working.

**Comment by Guite** [comment]
@MrMontesa can you please check if #3096 fixes the problem for you? After this change content page editing worked fine for me.

**Comment by MrMontesa** [comment]
Can I somehow delete old Locks? I still get the popup stating the lock from an hour ago. I logged off and on again, which did not change anything.

**Comment by Guite** [comment]
> Can I somehow delete old Locks? I still get the popup stating the lock from an hour ago.

You should clean your `pagelock` table in the database. Maybe the old lock has some invalid date set caused by one of the bugs solved earlier today.

**Comment by MrMontesa** [comment]
Thank you. At first it seemed to work fine. But now when cloning text-boxes, adding new ones, editing existing ones, I do receive the grayed-out popups again. After deleting the entries from DB I can then continue to work.

**Comment by Guite** [comment]
Added more fixes to #3096 
I think it works now without problems. Please retest to verify this before I merge it. Thanks!

**Comment by MrMontesa** [comment]
Great. I havent been able to force any PageLock screens any more.
All database entries are cleaned up. No left-overs.
