### ISSUE TITLE
Permission Rule Information popup ends up in grayed-out page

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3097]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

### Expected behavior
accessing /permissions/instance-info should display a popup with the permissions you can assign being able to copy them to clipboard

### Actual behavior
When accessing the page the popup appears but the front is grayed out so that you cant copy or click anything. Also backspace to go back does not work.

### Steps to reproduce
- Install ZK 1.4.3
- access admin / Permissions
- click on link: Permission Rule Information

Let me know if I can be of any help solving this.
Thanks

Edit:
Same applies when I try to delete an existing rule. The Popup for deleting the rule appears but is greyed-out so you cant click YES or NO
adding screenshot
![delete_permission_greyed_out](https://cloud.githubusercontent.com/assets/600125/18994525/81952752-8728-11e6-9ea3-c0b23f26a625.png)

**Comment by Guite** [comment]
Can't reproduce this using 1.4.3 final on my local host. Would it be possible for you to mail me your login credentials (site and ftp) so I can fix it on your server?

**Comment by MrMontesa** [comment]
Thanks for your offer. Login credential provided via email. Let me know if I can be of any help!

**Comment by Guite** [comment]
This is the same problem as in #2903, but for another theme. I will add the same workaround to Andreas08 for now and create another issue about finding a better (central) solution for 2.0.
