### ISSUE TITLE
cant get phpmail() feature to work

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3101]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

### Expected behavior
I've isntalled a zk 1.4.3 testbed as a subdomain of my prod site. So from server perspective everything i hould be identical. I confiured testbed the same way as I have it in prod site with phpmail() function.
Prod site works fine for several years now, but I cant get it working within 1.4.3.

Is there any documentation how to set things up?
Are there more detailed logs as the error message in the frontend just sais: Wasnt able to send mail.

The link to the swiftmailer module seems additional info. All swiftmailer settings are done via frontend, right? Or am I supposed to manually maintain generated.yml file?

### Actual behavior
Cant get phpmail() to work in my environment

Thanks for any hint that may help to get mail feature enabled.

**Comment by craigh** [comment]
> Cant get phpmail() to work in my environment

what is your environment. I use MAMP on a Mac - *NO* mail works - ever. It's not ZIkula's fault though.

**Comment by MrMontesa** [comment]
Hey Craigh,
Its an external site hosted with goneo.de a german hosting company. Prod site and testbed are running on the same server and configured mostly identical. Only difference is that testbed is running in a subdomain and prod site runs on the main site.
It may be related to the subdomain. I found app/logs/mailer.log which sais that my sending address is subdomain.domain.de, but the webserver can only be configured to mail from domain.de.

Is it possible to set that "from" tag? Or which function creates that id?

Thanks for looking into this.

**Comment by MrMontesa** [comment]
After digging deeper into mailer.log I found that the issue was due to the "admin's email address" set in /settings/ page.
Once this was the same as set in the webserver configs "from" address, it started working.
Closing this ticket.
