### ISSUE TITLE
update DB config for mysql 5.5+

### ISSUE THREAD

**Issue by craigh** [zikula/core#3104]
| Q | A |
| --- | --- |
| Zikula Version | 2.0.0-alpha1 |
| PHP Version | 5.5.9+ |

http://symfony.com/doc/current/doctrine.html#configuring-the-database

The charset needs to be updated to `utf8mb4` when mysql 5.5+ is required.

**Comment by craigh** [comment]
I don't think we need to require mysql 5.5+ anytime soon. Doctrine appears to support mysql 5.0+

http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/platforms.html

**Comment by Guite** [comment]
refs #3784

**Comment by Guite** [comment]
Closing in favour of #3784.
