### ISSUE TITLE
Editing children of main menue called Start gives error message

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3113]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.4

### Expected behavior

I wish to see the site if I call the domain
### Actual behavior
I get an error:
```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("The menu "Start" is not defined.") in "@ZikulaMenuModule/Block/menu.html.twig" at line 1.
```

### Steps to reproduce
Edit the name of a children of the mainmenu and try to call the start page.

**Comment by craigh** [comment]
This is not enough information. Please tell me how you edited the menu. Also, did you change the block to match?

**Comment by Portugao** [comment]
Seems I did not have understand the logic completely. I close this and will be free to reopen if nessecary.
