### ISSUE TITLE
Overlaping in menu bar images for legacy modules

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#3114]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.24

### Expected behavior
Normal bar with images and text for legacy modules like News.

### Actual behavior
See picture:
![image](https://cloud.githubusercontent.com/assets/628801/19519459/cc4d57ec-9614-11e6-96f6-d5727cd7e522.png)

### Steps to reproduce
Install News module and go to either front end or back end.

One way to resolve this issue is to add some style to file style/legacy.css:
```
.z-icon-es-add, .z-icon-es-back, .z-icon-es-cancel, .z-icon-es-config, .z-icon-es-copy, .z-icon-es-cubes, .z-icon-es-cut, .z-icon-es-delete, .z-icon-es-display, .z-icon-es-edit,
.z-icon-es-error, .z-icon-es-export, .z-icon-es-gears, .z-icon-es-filter, .z-icon-es-group, .z-icon-es-help, .z-icon-es-home, .z-icon-es-hook, .z-icon-es-import, .z-icon-es-info,
.z-icon-es-locale, .z-icon-es-locked, .z-icon-es-log, .z-icon-es-mail, .z-icon-es-new, .z-icon-es-ok, .z-icon-es-options, .z-icon-es-preview, .z-icon-es-print, .z-icon-es-profile,
.z-icon-es-regenerate, .z-icon-es-remove, .z-icon-es-save, .z-icon-es-saveas, .z-icon-es-search, .z-icon-es-url, .z-icon-es-user, .z-icon-es-view, .z-icon-es-warning, .z-icon-es-rss {
    padding-left: 20px !important;
}
```
and in file modules/News/style/style.css:
```
.z-icon-es-archive, .z-icon-es-insertrow {
    padding-left: 20px !important;
}
```

Then the result is:
![image](https://cloud.githubusercontent.com/assets/628801/19519634/6fe670b4-9615-11e6-9afd-ccd9cd8a3555.png)

**Comment by Guite** [comment]
Would you please create a PR for the 1.4 branch as well as the News module?
