### ISSUE TITLE
translation extraction does not contain all strings

### ISSUE THREAD

**Issue by Guite** [zikula/core#3117]
| Q | A |
| --- | --- |
| Zikula Version | 1.4.4-git |
| PHP Version | 7.0.8 |
### Expected behavior

All strings should be contained in the translation catalog.
### Actual behavior

While most strings are recognised, some are not. For example in a form type class, label texts are included, but help texts are not. See this screenshot from the Legal module:

![screenshot_20161021_164025](https://cloud.githubusercontent.com/assets/277531/19602307/152389fc-97ad-11e6-9593-0c73f0a81dfa.png)
### Steps to reproduce
1. Install the Legal module
2. Open a console in the Zikula root folder
3. Execute `php app/console translation:extract en --bundle=ZikulaLegalModule --output-format=pot`
4. Check if the resulting POT file is larger than the one which is currently [in Git](https://github.com/zikula-modules/Legal/blob/master/Resources/translations/zikulalegalmodule.en.pot).

**Comment by craigh** [comment]
I suspect the [extractor](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Translation/ZikulaPhpFileExtractor.php) is the problem.

**Comment by craigh** [comment]
@Guite can you please post the file(s) that you have and also tell me where you located them in order for them to work as they do in the screen shot? (refs #3132)

**Comment by Guite** [comment]
@craigh see here: https://github.com/zikula-modules/Legal/tree/master/Resources/translations

**Comment by craigh** [comment]
please explain the workflow which produced these files.

Also - if you could find an example of a string that is NOT translated and provide the location/context of that compared to strings that ARE being translated, I think that would help.

I am working on some tests for the extractor which will help this I hope.

**Comment by Guite** [comment]
> please explain the workflow which produced these files.

I followed https://github.com/zikula-modules/Pages/compare/b9a5bcb8e9...89ccb5c753

> if you could find an example of a string that is NOT translated

This works: https://github.com/zikula-modules/Legal/blob/master/Form/Type/ConfigType.php#L82
But this not: https://github.com/zikula-modules/Legal/blob/master/Form/Type/ConfigType.php#L90
(see screenshot above)

**Comment by craigh** [comment]
This works for me if I do

`php app/console translation:extract en --bundle=ZikulaLegalModule --output-format=po`

it produces `translations/zikula.en.po` (note the domain)

but if I do

`php app/console translation:extract en --bundle=ZikulaLegalModule --output-format=po --domain=zikulalegalmodule` 

it produces `translations/zikulalegalmodule.en.po` and that catalogue doesn't contain all the strings...

so not sure how to proceed here.

**Comment by craigh** [comment]
ok - I did this:

`php app/console translation:extract en --bundle=ZikulaLegalModule --output-format=pot --domain=zikulalegalmodule` (note I changed from `.po` to `.pot`)

A pot file includes comments to indicate where the original string is located.

This confirms that when specifying the domain that ONLY the `twig` files are extracted. Hence the missing strings.

then I did `php app/console translation:extract en --bundle=ZikulaLegalModule --output-format=pot` and this contains all the strings.

So this issue is that when specifying the domain, it doesn't extract strings from the `php` files. I'm not certain why this is for now.

**Comment by cmfcmf** [comment]
Can you give me an example line which is not extracted when a domain is used?

**Comment by craigh** [comment]
> Can you give me an example line which is not extracted when a domain is used?

ALL strings from php files in the requested bundle.

e.g. https://github.com/zikula-modules/Legal/blob/master/Form/Type/ConfigType.php#L82

This could be different than the behavior a couple days ago (from the OP) because I just changed some of this in my recent review of translations.

**Comment by cmfcmf** [comment]
> e.g. https://github.com/zikula-modules/Legal/blob/master/Form/Type/ConfigType.php#L82

It is pretty clear to me why this string is not extracted. How shall the PHP Parser, which is used to extract the strings, know that the string is of the `zikulalegalmodle` domain? It can't. Solution would be to use 

```php
$this->translator->trans('fosdf', [], 'zikulalegalmodule')
```
consistently.

Another solution would be to try to tell the extractor that the default domain inside a module folder should be the module name. No idea how this could be done right now.

**Comment by craigh** [comment]
> Another solution would be to try to tell the extractor that the default domain inside a module folder should be the module name. No idea how this could be done right now.

this is done in the twig extractor: https://github.com/zikula/core/blob/0d3a183dfb17c9579413db830415ba53595d948a/src/lib/Zikula/Bundle/CoreBundle/Translation/ZikulaTwigFileExtractor.php#L73-L91

**Comment by craigh** [comment]
in the php file extractor, the namespace of the file is (supposed to be) used to determine the translation domain:

https://github.com/zikula/core/blob/0d3a183dfb17c9579413db830415ba53595d948a/src/lib/Zikula/Bundle/CoreBundle/Translation/ZikulaPhpFileExtractor.php#L116-L135

**Comment by craigh** [comment]
quite sure I've fixed this, but can only test with core stuff atm. please test with legal and other bundle-type modules (@cmfcmf MediaModule)

**Comment by cmfcmf** [comment]
The MediaModule can't really be used to test this, because it is (almost)
consistently using 'cmfcmfmediamodule' as third domain parameter.

Craig Heydenburg <notifications@github.com> schrieb am Di., 15. Nov. 2016,
01:48:

**Comment by craigh** [comment]
> because it is (almost) consistently using 'cmfcmfmediamodule' as third domain parameter.

a quick look at some of the php and twig files indicates otherwise.

**Comment by rallek** [comment]
I am not shure if this is fixed already. I have to do further analysis. But not this week.
