### ISSUE TITLE
remove Mapstraction library

### ISSUE THREAD

**Issue by craigh** [zikula/core#3121]
Mapstraction doesn't seem to have a general use-case but is rather specific. If required, it should be provided by the module that requires it. In addition, it is quite old and left undeveloped for some time now.

https://github.com/mapstraction/mxn

I would like to remove it entirely at Core-2.0 and not replace the functionality at all (as will be done with the other core plugin - Imagine)

opinions?

**Comment by robbrandt** [comment]
I think a common map library would be a good thing though. Leaflet might be a good alternative.

**Comment by Guite** [comment]
While modules can express their own dependencies using composer, in my opinion the core should provide solutions for recurring requirements to avoid redundant libraries wasting disk space. I see three points:

1. Images
Imagine definitely needs to be central. Many many modules need it.

2. Maps
Interesting for every module working with some kind of addresses (for example calendars) or other geo location functionality.
Yes, leaflet is a very good replacement for mapstraction and also recommended by @gfr (who has good experience in geo applications). See also https://github.com/Guite/MostGenerator/issues/340 which is exactly about replacing mapstraction by leaflet in the generator, which is blocked by that leaflet is not in the core.

3. PDF
Some tool for creating PDF documents. For example https://github.com/SlikNL/DompdfBundle for http://dompdf.github.io/ or https://github.com/KnpLabs/KnpSnappyBundle -> see http://jayroman.com/blog/how-to-export-any-symfony-route-to-pdf also

**Comment by craigh** [comment]
I agree with Images and PDF. I don't see Maps as a general use case.

**Comment by gfr** [comment]
I would really suggest to add the leaflet library to the core as maps are often part of modern websites (e.g. Where to find us etc.)

**Comment by Portugao** [comment]
I'm with @gfr .

**Comment by Guite** [comment]
Just an additional idea for bundle integration:
As many Symfony bundles require configuration on application level (`/app/config`) is would possibly be helpful providing a dedicated module (for example named `BundleIntegrationModule`) which users can use to add arbitrary bundles. This module would be almost empty, it's purpose would just be holding bundles and their configuration in order to provide their functionality to the system.

**Comment by craigh** [comment]
I don't think this will work since adding bundles requires manual manipulation of the `ZikulaKernel` and doing this will require the config be in the zikula config. I'm not sure there is a better way at the moment.

**Comment by craigh** [comment]
mapstraction was removed from the master branch some time ago. therefore closing this. I still feel any replacement should not be in the core but rather in the module that requires it.

**Comment by Guite** [comment]
> I still feel any replacement should not be in the core but rather in the module that requires it.

This requires #3438 then.
