### ISSUE TITLE
Error if using DBUtil::selectObjectArray('users')

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#3126]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4.build65
| PHP Version       | 5.6.24

### Expected behaviour
No error if using `DBUtil::selectObjectArray('users')`

### Actual behaviour
If using `DBUtil::selectObjectArray('users')`, an error occurs:
```
User owner Error in DBUtil::executeSQL: SELECT uid AS "uid",uname AS "uname",email AS "email",pass AS "pass",passreminder AS "passreminder",activated AS "activated",approved_date AS "approved_date",approved_by AS "approved_by",user_regdate AS "user_regdate",lastlogin AS "lastlogin",theme AS "theme",ublockon AS "ublockon",ublock AS "ublock",tz AS "tz",locale AS "locale" FROM users AS tbl ORDER BY tbl.uname 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ublockon' in 'field list'
```

### Steps to reproduce
Any use of `DBUtil::selectObjectArray('users')`
Also any use of `UserUtil::getUsers('', '')` (string in first 2 argument).
Also any use of `HtmlUtil::getSelector_User`.
Also Any module if using `{selector_user}` in template.
(Same modules using `{selector_user}`: Banners, News, AddressBook

### Comment:
The reason for the error is because fields `ublock` and `ublockon` are missing in created table `users`, but they still exist in definitions in file `system/UsersModule/tables.php`.
To resolve this error, just comment all lines in above file, which contain ublock and ublockon.

**Comment by craigh** [comment]
@nmpetkov please confirm fix in latest build.

**Comment by nmpetkov** [comment]
Yes, I confirm all is OK now.
