### ISSUE TITLE
move /userdata to /web/userdata? eliminate entirely?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3127]
we should consider moving `/userdata` to `/web/userdata` for core-2.0

we should also clearly define the purpose for its use. is it a 'cache' directory? assets? 

perhaps it should be eliminated altogether? cache files should be in `app/cache` the `/web` directory can be used directly be each bundle as needed.

**Comment by Guite** [comment]
iirc userdata was primarily intended for files uploaded by users

**Comment by craigh** [comment]
Symfony's design implies that the only publicly accessible directory is the `/web` directory. So - a module would need to take that into account. So, if the module wants to 'serve' the files directly, it would need to place the files in `/web`. otherwise, the files would need to be loaded and delivered in a different manner (if I recall, Downloads is designed the right way, but stores the files elsewhere...)

**Comment by Guite** [comment]
When I did MediaAttach several years ago I also designed it in a way that all files were delivered using a controller action. This was nice for configurability (for example permissions), but very bad with regards to performance for bigger files. This is why I gave this up when I did the more lightweight SimpleMedia.

**Comment by Guite** [comment]
> performance for bigger

and performance for pages with many files of course!
