### ISSUE TITLE
{pageaddvar} löst nicht mehr auf

### ISSUE THREAD

**Issue by trichers** [zikula/core#3131]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10
| PHP Version       | 5.6

### Expected behavior
Ein ganz seltsames Phänomen macht sich auf einmal bei manchen Zikula 1.3 Installationen bemerkbar. Von heut auf morgen greift die Smarty Funktion {pageaddvar} nicht mehr.
Beispiel
{pageaddvar name="stylesheet" value="$stylepath/style.css"}

wird nicht zu einem Stylesheet-Link gewandelt, sondern erscheint überhaupt nicht im html-Code.

Was könnte das sein?
Gruß
Thomas

**Comment by Guite** [comment]
It should be:

    {pageaddvar name="stylesheet" value="`$stylepath`/style.css"}

(note the backticks)

**Comment by trichers** [comment]
the problem is the same, with or without the backticks.

**Comment by trichers** [comment]
Ich hab mir mal das Plugin function.pageaddvar.php angeschaut und es scheint ein Übergabe-Problem an PageUtil zu geben. Der Eintrag PageUtil::addVar($name, $value); greift scheinbar nicht oder in PageUtil werden die Werte nicht sauber verarbeitet?

**Comment by Guite** [comment]
The error was caused by a missing `</thead>` in the theme.
