### ISSUE TITLE
Use newer syntax for used form field types

### ISSUE THREAD

**Issue by Guite** [zikula/core#3139]
We should use the newer syntax when defining the form field types used in a form type. Of course this requires at least PHP 5.5.

**Comment by craigh** [comment]
please be more specific or give an example.

**Comment by Guite** [comment]
Old:

```
->add('transport', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [...]);
```

New:

```
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

->add('transport', ChoiceType::class, [...]);
```

**Comment by craigh** [comment]
FYI this is not a symfony thing, but a PHP >= 5.5 thing.
