### ISSUE TITLE
Consider Cache Component for AssetCombination

### ISSUE THREAD

**Issue by craigh** [zikula/core#3140]
http://symfony.com/doc/current/components/cache.html

currently, Asset merger uses DoctrineCacheBundle/DoctrineCommonCache to cache the combined files. Consider moving this to Symfony's Cache Component.

https://github.com/zikula/core/blob/1.4/src/system/ThemeModule/Engine/Asset/Merger.php

**Comment by Guite** [comment]
Closing as this has been done in 51d6fe2b1c5935149c9bf0b9f110e7c74145f935
