### ISSUE TITLE
observations & enhancement ideas for 1.4.4 upgrade

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3141]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

Tried build 89 for the upgrade. WebFe Upgrade seems to be broken. At least I was not able to get past that screen:
![zk144_upgrade](https://cloud.githubusercontent.com/assets/600125/20037599/0dacc440-a423-11e6-8143-600fa5ac2427.png)

Then I tried the console upgrade which seens to rely on $(pwd) to properly function. I got different results when executing either both ways:
```
cd ~/app; php ./console zikula:upgrade
cd~; php ./app/console zikula:upgrade
```
Specially the checks related to folder existance, etc. Would be easier for the enduser if the console does not care about pwd.
The related folders that were in scope are:
```
  [InvalidArgumentException]                     
  The "config/locale" directory does not exist.  
  [InvalidArgumentException]                            
  The "app/Resources/locale" directory does not exist.  
```

Then I got confused what I shall have entered here:
`The host where you install Zikula, e.g. "example.com". Do not include subdirectories. [localhost]: `

After receiving an error here I added the databaese host there and was able to proceed. I would recommend to rephrase the sentence to something more related to the database rather than the webserver.

Summary:
- WebFe for installer should work
- console should not depend on pwd
- missing folders or permissions could be created or chmod'ed automatically
- re-phrase installer question: Possible wording: `The host [IP or FQDN] where Zikula database is running [localhost]:`

**Comment by craigh** [comment]
> console should not depend on pwd

this is an issue which is addressed elsewhere. This cannot be fixed in Core-1.4 and maybe not even later. The core is dependent on certain paths being accurate. 

> missing folders or permissions could be created or chmod'ed automatically

this is done where it can be done. It is also documented. I don't know how else to help this.

**Comment by craigh** [comment]
> Then I got confused what I shall have entered here:
The host where you install Zikula, e.g. "example.com". Do not include subdirectories. [localhost]:

this is not the database host. this is the request root. The database host is request in a different form.

it becomes a parameter:

    router.request_context.base_url: /path/to/my/base_url

**Comment by craigh** [comment]
> WebFe for installer should work

just successfully ran the web installer.
![screen shot 2016-11-12 at 9 22 52 am](https://cloud.githubusercontent.com/assets/350048/20238440/9e7a4d40-a8b9-11e6-90f9-39c4dfb7f228.png)

**Comment by craigh** [comment]
The issue with the web upgrader is valid. I am attempting to fix.

**Comment by craigh** [comment]
basic problem here is that the upgrader cannot login the admin because the ZAuth module is not yet installed.

**Comment by MrMontesa** [comment]
> missing folders or permissions could be created or chmod'ed automatically
> this is done where it can be done. It is also documented. I don't know how else to help this.

I have to admit, I havent tested this thoroughly. For me it looks like few folders are not included in the installer tarball. In fact I guess those should have been created during installation, right?
Since installer complains about missing permissions on those newly created folders, should be easy to do a chmod() on them.
I will test again and file a more detailed ticket on this matter.

**Comment by craigh** [comment]
please retest with new builds from CI

**Comment by MrMontesa** [comment]
I can confirm console and WebFe Upgrade do both work.
Only observation was that admin credentials were asked twice during WebFe upgrade. First when pressing the blue "Proceed to upgrade" button. And once more a bite later during regular upgrade wizard.

**Comment by craigh** [comment]
unavoidable.
