### ISSUE TITLE
Module icon is not shown in the admin drop down

### ISSUE THREAD

**Issue by rallek** [zikula/core#3154]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4dev build 98
| PHP Version       | 5.5.30

### Expected behavior
The icon of the module ``News Publisher`` should appear in the drop down

### Actual behavior
the name of the module is showing up twice

### Steps to reproduce
![news_icon_missing](https://cloud.githubusercontent.com/assets/935250/20223221/d9b1851c-a838-11e6-8eab-ba89f7a48c72.jpg)

**Comment by Guite** [comment]
This is fixed by #3158

**Comment by Guite** [comment]
Fixed in #3163
