### ISSUE TITLE
documentation for normal admins for new menu block

### ISSUE THREAD

**Issue by rallek** [zikula/core#3160]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4 dev
| PHP Version       | 5.5.30

### Expected behavior
description for normal user should be at the docs/Core-1.x
Some examples would be very welcome. At the moment a normal site admin without programming skills gets lost.

### Actual behavior
Developer documentation is available at https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Blocks.md

### Steps to reproduce
n/a

**Comment by craigh** [comment]
this doesn't go in Core-1.x it will go in `/Admin`
