### ISSUE TITLE
upgrade 1.4.1 to 1.4.4 is failing

### ISSUE THREAD

**Issue by rallek** [zikula/core#3170]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5.30

### Expected behavior
upgrade runs well

### Actual behavior
I am forwarded to mysite.tld/upgrade but I see this:
![upgrade 1 4 4](https://cloud.githubusercontent.com/assets/935250/20239560/77d0bc02-a903-11e6-9bc5-69cf028dc878.jpg)

### Steps to reproduce
follow the upgrade procedure (delete all, copy the two config files, userdata and theme)
go to webbrowser and visit your site

**Comment by rallek** [comment]
if I change to dev mode I do get this:
````
502 Bad Gateway

nginx/1.2.1
````

**Comment by craigh** [comment]
This is a duplicate

**Comment by craigh** [comment]
See #3141

**Comment by craigh** [comment]
closed by #3173

**Comment by rallek** [comment]
Upgrade via Browser is working now

One additional observation: I directly changed my custom_parameters.yml to ``dev`` and ``debug true``. With this settings I got ``502 bad gateway``. Changing this to ``prod`` ``debug false`` let me upgrade (what should be the normal case)
