### ISSUE TITLE
No authentication mapping record for admin

### ISSUE THREAD

**Issue by Guite** [zikula/core#3177]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4-git
| PHP Version       | 7

### Expected behavior
Admin can use lost password functionality like other users.

### Actual behavior
The user is not found (neither by username nor by email address).

### Steps to reproduce
Try to start a lost password process.
The `zauth_authentication_mapping` table does not contain an entry for the admin user after a fresh installation. After I inserted a record manually into the database the process starts properly.

**Comment by craigh** [comment]
the record is migrated when the admin logs in the first time after the new system.

**Comment by craigh** [comment]
so this is not specific to the admin. This issue will occur to anyone that hasn't logged in since the upgrade past 1.4.3 and forgotten their password. Your new system will need a BC layer for this possibility.

**Comment by Guite** [comment]
Also for new installations?

**Comment by craigh** [comment]
yes.

we could back port code from master if you wish I suppose.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php#L247

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/master/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php#L245-L262

**Comment by Guite** [comment]
looks reasonable for me. any objections about backporting this?

**Comment by craigh** [comment]
no objection
