### ISSUE TITLE
Uprade to 1.4.4 gives problems for modules upgrade

### ISSUE THREAD

**Issue by rallek** [zikula/core#3182]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5.30

### Expected behavior
after successfull upgrade of the core the modules should be able to activate

### Actual behavior
````
Page not found.
404 Not Found - NotFoundHttpException
````
additional I see the following message in the extension list:
![invalid pages](https://cloud.githubusercontent.com/assets/935250/20280281/3070cba4-aaac-11e6-9260-2ea9d7e552e3.jpg)
but Pages is recognized:
![pages](https://cloud.githubusercontent.com/assets/935250/20280322/5b3d89e4-aaac-11e6-8591-3bc7d2c45d5c.jpg)

### Steps to reproduce
* Upgrade from 1.4.1 to 1.4.4dev build 116
* modules are listed with files missing (fine!) 
* copy missing files from your backup to modules folder
* click on activate for a module

### Stack trace
````
[1] Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Page not found.
    at n/a
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php line 128

    at Zikula\Bundle\CoreBundle\Controller\LegacyController->shortUrlAction(object(Zikula_Request_Http))
        in  line 

    at call_user_func_array(array(object(LegacyController), 'shortUrlAction'), array(object(Zikula_Request_Http)))
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/index.php line 23
````

**Comment by rallek** [comment]
I tried to delete the files for Pages so the red information is disappearing. But that do not change anything for the reported problem

**Comment by MrMontesa** [comment]
Found the same on fresh 1.4.4Build 117 install when adding modules for the first time. Tested with News & PostCalendar.

**Comment by craigh** [comment]
@Guite will you please look into this. I guess it has something to do with your composer validation.
