### ISSUE TITLE
Problem sending a test email

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#3186]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4.build100
| PHP Version       | 5.6.24

### Expected behavior
Test mail sending works with any recipient name

### Actual behavior
Mail is not sent if enter some UTF-8 names in recipient name

### Steps to reproduce
Go to admin panel, mailer module, Test mailer settings. Fulfil the form. In ```Recipient's name``` enter ```Иван Иванов```. Press ```Send test mail``` button.
The email is not sent and you receive a message:
```It looks like the message could not be sent properly```
If you enter name in ASCII, for examle ```Ivan Ivanov```, then the mail is sent properly.

This issue is first reported in #3052, then moved as new issue.

### Comments
After debugging I found php mail() function is working properly, but Swift-mailer puts strange to me formatting (I echoed just before the line with call to php mail() function in file ```/home/cmstory/public_html/zktest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SimpleMailInvoker.php```:
![3b69a4aa-a907-11e6-8825-f5e12b42c946](https://cloud.githubusercontent.com/assets/628801/20303343/a0e89c90-ab33-11e6-960a-1cbde17e5e84.png)

Same test in Zikula 1.3.10 work well, no problem to send test mail with any recipient name - I used same name, to compare. Also looked - in Zikula 1.3.10 is used other mailer class (not SuiftMailer), and that means the problem is not in php mail() function, but encoding of strings or generated header in Zikula 1.4 SuiftMailer.
![3b69a4aa-a907-11e6-8825-f5e12b42c946](https://cloud.githubusercontent.com/assets/628801/20303397/d71cc692-ab33-11e6-926d-d653dd1e79cf.png)

Configuration when tested:
![7ddd9260-a8ee-11e6-97f8-3306f91f42bf](https://cloud.githubusercontent.com/assets/628801/20303122/9f212bda-ab32-11e6-9b51-c2f14924a492.png)
![1ed10b8e-a8f4-11e6-8b14-97a375f04987](https://cloud.githubusercontent.com/assets/628801/20303137/b360f648-ab32-11e6-954d-33a977454500.png)

**Comment by nmpetkov** [comment]
It seems there is a problem in Swiftmailer encoding:
https://github.com/swiftmailer/swiftmailer/issues/58

**Comment by craigh** [comment]
are you saying this is a vendor problem and we should close this ticket?

**Comment by nmpetkov** [comment]
In Swiftmailer project there is no reaction on this issue, and looks like there is workaround. Please leave for now open
It needs some more tests and is possible the problem to arise in other languages, not only Cyrillic.

**Comment by craigh** [comment]
closing as NOT CORE
