### ISSUE TITLE
Consider Removing "Keywords" Meta Tag

### ISSUE THREAD

**Issue by shefik** [zikula/core#3187]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

The use of the `keywords` meta tag has been documented to no longer be effective SEO practice for a while now. We should consider removing support from the Zikula core.

Discussion:

http://cohlab.com/blog/stop-using-keywords-meta-tag.html
http://cohlab.com/blog/meta-tags-google-recognizes.html

**Comment by Guite** [comment]
cohlab.com seems broken

**Comment by craigh** [comment]
this seems easily done by customizing one's theme. Do we need to remove the ability in the core entirely?

**Comment by Guite** [comment]
Yes.
Having one central keywords tag for the whole website is not very helpful anyway. If one would want to use this properly, it would need to be unique for every single page. This is still possible using Content and/or MUSeo also if the core does not provide a field anymore.

@rallek @portugao @gfr any input or objections?
