### ISSUE TITLE
activation of modules after upgrade is not passible

### ISSUE THREAD

**Issue by rallek** [zikula/core#3197]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4dev ci.build129
| PHP Version       | 5.5.30

### Expected behavior
modules should be able to activate

### Actual behavior
404

### Steps to reproduce
failure #3182 is back

**Comment by rallek** [comment]
fresh stack trace:
````
[1] Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Page not found.
    at n/a
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php line 128

    at Zikula\Bundle\CoreBundle\Controller\LegacyController->shortUrlAction(object(Zikula_Request_Http))
        in  line 

    at call_user_func_array(array(object(LegacyController), 'shortUrlAction'), array(object(Zikula_Request_Http)))
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.4/index.php line 23
````

**Comment by rallek** [comment]
same to new install

**Comment by Guite** [comment]
Can you tell us which module you used?

**Comment by rallek** [comment]
Upgrade was News, Captcha, Content, EZComments and so on.

New install at a new ZK installation was MediaModule. But now I want to check if I can install legal. I now see MediaModule is installed fine! But first I got the 404 page while I was clicking at the install button.

**Comment by Guite** [comment]
As your stack trace contains `LegacyController` I'd guess this affects only legacy modules. So no surprise it works with MediaModule.

**Comment by rallek** [comment]
let my try news

**Comment by rallek** [comment]
mmh, news is installing well. But on my upgrade not. On my upgrade even MediaModule (1.1.0) is not installing.

Will restart my complete upgrade procedure.

**Comment by rallek** [comment]
I can confirm. After a second try with an upgrade from scratch the 404 is still there when I try to activate e.g. News module

**Comment by MrMontesa** [comment]
I think I do have the same issue in my setup. Tried upgrading 1.4.3 with some modules to 1.4.4 which went fine.
On re-activating some modules end up in 404 or 500. News was one of them. Formicula and Postcalendar might be affected as well. Not too sure though.

**Comment by craigh** [comment]
> As your stack trace contains `LegacyController` I'd guess this affects only legacy modules. So no surprise it works with MediaModule.

This isn't true. LegacyController kind of "catches" what appears to be shorts urls that cannot be found. So the question is more about what was the originally request route.

Again - the composer validator needs to be disabled for non-bundle modules. I'll bet that is the problem here.

**Comment by Guite** [comment]
I do not think that this is related to the composer validator, as for example the News module does not contain a composer file at all.

**Comment by craigh** [comment]
I need a set of reproducible steps for this ticket or we will need to close it.

@MrMontesa - Ralf cannot be available for a while. Will you please test this again after #3204 is merged.

**Comment by Guite** [comment]
:+1:  never imagined that the asset merger is related to this issue.

**Comment by MrMontesa** [comment]
Will do some tests today

**Comment by MrMontesa** [comment]
Ok, testen and upgrade from 1.4.3 to 1.4.4-dev build140 which worked nicely.
Then reactivated News, Postcalendar, Content, Formicula, Mediamodule, Scribite, Addresbook one by one with no issues, but havent done much app testing. Just the upgrade/re-active part which works wuite well.

**Comment by rallek** [comment]
I tested Upgrade from1.4.1 to 1.4.4

Can you tell me exactly your upgrdae procedure so I can check it the same way? What did you upgrade? A copy of an existig site? Subfolder or Subdomain?

**Comment by MrMontesa** [comment]
It didnt work for you?
I'm  running my pages/subdomains with a dedicated DocRoot on Linux. I'm doing updates like this:

```
cd htdocs
wget zikula from CI
mv site site.bac
tar -pxvf zikula.tar.gz
mv Zikula site
mysqldump site.db > site.db
mysqldump site_test.db < site.db
cp site.bac/config/personal site/config/
cp site.bac/app/config/custom site/app/config
cd site
sed 's#site.db#site_test.db#g' config/personal_
sed 's#site.db#site_test.db#g' app/config/custom_
php app/console zikula:upgrade OR WebFe
```

This is more a logic approach rather than executing those command on the shell.
The idea is to do the update in the main place but have the ability to rollback easily. Feel free to PM me in case you'd like to talk about this in more detail.

**Comment by Guite** [comment]
@MrMontesa what stands `WebFe` for?

**Comment by MrMontesa** [comment]
:smile: **WebF**ront**E**nd

**Comment by craigh** [comment]
@rallek whichever way you test it is OK. The goal of testing is not to duplicate how others perform their tests, but to test it your way.

This ensure that the product performs in the way that you would expect as well as someone else. Perhaps in your own version of test the product doesn't perform, or reveals a bug that their model would not. Therefore, you should perform the tests as you best can according to the directions and experience you have. If you make mistakes, you reveal your own misunderstandings or poorly written instructions 😉 and help make the product better.

**Comment by rallek** [comment]
I do have another problem at the moment. I copied my 1.4.1 site into another subdomain. But the routes are damagend than. Some days ago I did the same but thereof I do have a normal runnig backup site, still 1.4.1. I must have made something different but can not remember what.

Never the less, do not wait for my test. I will not be available for testing within the next days.

**Comment by craigh** [comment]
If you change your subdomain from an existing install, you have to adjust `app/config/custom_parameters.yml` and change the `router.request_context.base_url` value to match your new subdomain. Also manually remove the `app/cache/prod` directory.

**Comment by rallek** [comment]
@craigh I changed it to
````
    router.request_context.host: test.oldtimer-ig-osnabrueck.de
    router.request_context.scheme: http
    router.request_context.base_url: ''
````
But nothing changed :-(

Remeber, I am still cloning a 1.4.1 site

**Comment by craigh** [comment]
Cache

**Comment by rallek** [comment]
Nope. Deleted prod and used a device where I never before opended this site. Please try to open the following link:
http://test.oldtimer-ig-osnabrueck.de/pages/display/vorstand

I do have a 404 :-(

I know, I do something wrong. But what?
