### ISSUE TITLE
upgrade with german language pack is not working (1.4.1 to 1.4.4)

### ISSUE THREAD

**Issue by rallek** [zikula/core#3198]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x.x
| PHP Version       | 5.x

### Expected behavior
Upgrade should work

### Actual behavior
````
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Unable to generate a URL for the named route "upgrade" as such route does not exist.
````

### Steps to reproduce
start upgrade with german language pack installed.

**Comment by craigh** [comment]
upgrade from what to what?

php version?

please always fill in the header

**Comment by craigh** [comment]
please also explain what you 'installed' and exactly where you installed it.

if possible provide a link to obtain your translation

**Comment by rallek** [comment]
I installed an incomplete translation like I did for 1.4.1 and 1.4.3. I placed the ``zikula.mo, zikula.po`` and ``zikula_js.mo, zikula_js.po`` in ``app/Resources/locale/de/LC_MESSAGES``
The first (new) page for upgrade (zauth) was in English but the second one with the message that this site must be upgraded was in German. When I started the upgrade I got the 500 error. 

Might be it has to do with translated routes? 

My work around was. rename the language folder from ``de`` to ``de.bak`` and delete the ``app/cache/prod`` and the Browsercache as well. With this setting I was able to upgrade. 

After this I enabled the language again by renaminig the ``de.bak`` to ``de``. When I than tried to upgrade the modules I saw again a 500. I have had some trouble to make it disappear (the 500 error was shown now always) by renaming the language folder again, deleting prod and browser cache. But finally the modules can not be upgraded as already reported in the other ticket. But now the 500 disappeared during opening the extension list.

The starting point was an 1.4.1 page. The used language pack is exactly the same. The difference what I did before: I normally set up my site in english, add all my modules and activate them and than I added my language.

Upgrading is a copy of the old site in a new database, changing the two config files than installing the latest zikula, copy over the config files, my theme and the userdata folder. Than run the upgrade script but under a new subdomain (does that matter?). Without language pack the upgrade is running with language pack I get the 500 error.

**Comment by craigh** [comment]
there are so many variables in this process it is quite complicated to troubleshoot in this manner.

> I placed the zikula.mo, zikula.po and zikula_js.mo, zikula_js.po in app/Resources/locale/de/LC_MESSAGES

This should work for now, but ideally, you should be using the `translations` directory now instead. Unfortunately, not all the old translations are in the new `.po` (`zikula.template.po`) and so if you only use that, they won't all work. This will be true until the entire core is finally transitioned to the new translator. Mainly a problem currently in the Categories module. btw - the `.mo` files are pointless. they are not used afaik.

> The first (new) page for upgrade (zauth) was in English

this doesn't make sense to me. What does ZAuth have to do with anything? I do expect the page to be in English, but what page exactly are we talking about?

> the second one with the message that this site must be upgraded was in German

second one? Again, I don't understand.

> Might be it has to do with translated routes?

you should translate your routes also. copy `translations/routes.template.po` to `translations/routes.de.po` and make changes. I don't know if this will solve the problem but it is worth a try.

your workarounds make me think the routes are the problem. It is trying to use German routes and not finding them I guess. 

I recommend:
 - copy 1.4.1 DB to backup
 - remove all old files
 - copy old `custom_parameters.yml` and `personal_config.php` to new installation
 - copy translations - **including routes file**
 - attempt to load the new site - should redirect to upgrade - possibly in German.

**Comment by rallek** [comment]
what do you mean with **including routes file**?

I hope I will find time this evening to redo the tests

**Comment by craigh** [comment]
I mean be sure to also translate the routes file and include it.

**Comment by rallek** [comment]
sorry, I did not get your point. Where can I find the routes file? I only know a routes module.

**Comment by Guite** [comment]
> you should translate your routes also. copy translations/routes.template.po to translations/routes.de.po and make changes.

**Comment by rallek** [comment]
I found ``app/Resources/translations/routes.template.po**t**`` But before that I run now into another problem what might be the real root cause.

I copied my 1.4.1 site in another parallel folder. I named the folder already 1.4.4 (because that is the target of upgrade). Now I also copied the database db8 in the new database db20 which I want to use for my upgrade. In both config files I changed the database, password is the same in both cases. I also deleted the cache/prod which I accidentaly copied as well.

Now I open my site which is now the sub domain test.mysite.tld. This test sub domain is targeting at the 1.4.4 folder. The site is shoing up as usual. The front page is a list of news. But if I try to login via test.mysite.tld/login (or /index.php/useraccount) I do get  a 404 Not Found :-(

Where is my mistake while cloning my site?

In the past I skipped the cloning. I directly tried to upgrade with new core and old database. This time I want to be shure the site is running as a clone.

**Comment by craigh** [comment]
I believe I have fixed this.
![screen shot 2016-11-21 at 3 04 28 pm](https://cloud.githubusercontent.com/assets/350048/20499136/15bb0d36-affe-11e6-975a-79c617f7a299.png)
![screen shot 2016-11-21 at 3 13 03 pm](https://cloud.githubusercontent.com/assets/350048/20499142/1c039ea6-affe-11e6-91a4-960de16f1fb4.png)
![screen shot 2016-11-21 at 3 13 21 pm](https://cloud.githubusercontent.com/assets/350048/20499143/1c503392-affe-11e6-9ad4-c452c91eda3c.png)
![screen shot 2016-11-21 at 3 13 30 pm](https://cloud.githubusercontent.com/assets/350048/20499144/1c511168-affe-11e6-93e7-1e05c723cb9c.png)
![screen shot 2016-11-21 at 3 16 35 pm](https://cloud.githubusercontent.com/assets/350048/20499145/1c526b9e-affe-11e6-92d6-94a70ad96453.png)

**Comment by craigh** [comment]
@rallek please set up your translations as I did in the screenshot above.

using `/app/Resources/locale/de/LC_MESSAGES/zikula.po` may also work, but will not work for the routes.

**Comment by craigh** [comment]
in my screenshots the `en-` prefix indicates an english translation (from the `zikula.en.po` file) and the `de-` prefix indicates a German translation `(from the `zikula.de.po` file)

**Comment by rallek** [comment]
I will not be able to try during the next days. But do I understand right. Upgrade from 1.4.1 to 1.4.3 is working with the old translation file. Now I have first to change the translation method to be able to upgrade to 1.4.4 correctly?

Might be I am to much confused by all this upgrade testing.

**Comment by craigh** [comment]
> change the translation method

I don't understand your question either ;-) I don't see any change in translation method here but I don't do any translating, so I'm not sure.

**Comment by rallek** [comment]
using old path ``Zikula_Core-1.4.4/app/Resources/locale/de/LC_MESSAGES`` instead of new path ``Zikula_Core-1.4.4/app/Resources/translations``
