### ISSUE TITLE
Problem with imagine Plugin an unserialize

### ISSUE THREAD

**Issue by trichers** [zikula/core#3205]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10
| PHP Version       | 5.6

### Actual behavior
This error comes:
Uncaught exception Error at offset 249 of 266 bytes in /homepages/20/d261212531/htdocs/zikula/lib/util/ModUtil.php line, 119
#0 [internal function]: ArrayObject->unserialize('x:i:2;a:8:{s:5:...')
#1 /homepages/20/d261212531/htdocs/zikula/lib/util/ModUtil.php(119): unserialize('a:1:{s:7:"defau...')
#2 /homepages/20/d261212531/htdocs/zikula/lib/Zikula/Core.php(426): ModUtil::initCoreVars()
#3 /homepages/20/d261212531/htdocs/zikula/index.php(16): Zikula_Core->init()
#4 {main}

### Steps to reproduce
Use http://neu.baggerdoktor.de/

**Comment by Portugao** [comment]
Why do you use 1.3.2?
You should use 1.3.10.....

**Comment by trichers** [comment]
sorry, it is 1.3.10

**Comment by Guite** [comment]
> Steps to reproduce
> Use http://neu.baggerdoktor.de/

This is not how to reproduce it, but just a link to your site having this problem. We need to know what you did to cause this situation.

**Comment by trichers** [comment]
Yesterday it worked and over night it didn´t.

**Comment by Portugao** [comment]
Is the php version new?

**Comment by trichers** [comment]
I checked it but no change.

**Comment by trichers** [comment]
in the MySQL DB in the table module_vars unter the item systemplugin.imagine stands:
a:1:{s:7:"default";C:27:"SystemPlugin_Imagine_Preset":266:{x:i:2;a:8:{s:5:"width";i:100;s:6:"height";i:100;s:4:"mode";s:5:"inset";s:9:"extension";N;s:7:"options";a:2:{s:12:"jpeg_quality";i:75;s:21:"png_compression_level";i:7;}s:8:"__module";N;s:9:"__imagine";N;s:16:"__transformation";N;};m:a:1:{s:7:"�*�name";s:7:"default";}}}

If I change the last entry {s:7:"�*�name";s:7:"default";} to {s:5:"*name";s:7:"default";} I get the following message:

WARN (4): E_WARNING: Insufficient data for unserializing - 266 required, 266 present in ModUtil.php line 119
WARN (4): E_WARNING: session_start(): Cannot send session cookie - headers already sent by (output started at /homepages/20/d261212531/htdocs/zikula/lib/vendor/Zend/Log/Writer/Stream.php:130) in Legacy.php Zeile 107
WARN (4): E_WARNING: session_start(): Cannot send session cache limiter - headers already sent (output started at /homepages/20/d261212531/htdocs/zikula/lib/vendor/Zend/Log/Writer/Stream.php:130) in Legacy.php Zeile 107
WARN (4): E_WARNING: session_regenerate_id(): Cannot regenerate session id - headers already sent in SessionUtil.php Zeile 263
WARN (4): E_WARNING: Cannot modify header information - headers already sent by (output started at /homepages/20/d261212531/htdocs/zikula/lib/vendor/Zend/Log/Writer/Stream.php:130) in SystemListeners.php Zeile 828
WARN (4): E_WARNING: Cannot modify header information - headers already sent by (output started at /homepages/20/d261212531/htdocs/zikula/lib/vendor/Zend/Log/Writer/Stream.php:130) in SystemListeners.php Zeile 830

**Comment by Portugao** [comment]
Misunderstanding.....
Did you or someone else change the running php version?

**Comment by trichers** [comment]
I tried a complete new Zikula Installation 1.3.11
but the same Problem.
Bin echt ratlos

**Comment by Portugao** [comment]
Deine Aussage, über Nacht geht es nicht mehr, läßt mich vermuten, dass es eine Umstellung bzgl. PHP beim Hoster gab???

**Comment by cmfcmf** [comment]
Ich würde mal einwerfen, dass vielleicht das Datenbank Encoding nicht mehr stimmt (es sollte UTF-8 sein).

**Comment by trichers** [comment]
das war mein erster Gedanke, auch daran liegt es nicht. Habe jetzt die Seite komplett bei meinem Provider gespiegelt und da kommt der gleiche Fehler.

**Comment by trichers** [comment]
in the database item is the value �*�name
does somebody know what letter should original stand at the � ?

**Comment by trichers** [comment]
Cloud this Information be relevant?
http://www.securityfocus.com/bid/93577

**Comment by craigh** [comment]
unlikely. those only affect PHP7 (it appears).

**Comment by trichers** [comment]
I have now rebuilt the database manuel again. Now it works. But I don´t know why the bug came.
But we can close the issue.
