### ISSUE TITLE
Refactor remaining legacy API usages

### ISSUE THREAD

**Issue by Guite** [zikula/core#3208]
Any dependency to `Abstract_Api` must be removed.

If changes are not too extensive maybe backport to 1.4.5.

**Comment by craigh** [comment]
`Zikula_AbstractApi`

This must be a 1.4.5 ticket. These dependencies must not be "backported" but rather "front ported" (that's not a word). They *must* be merged into 1.4.x **first**. Then merged in to 2.0.

The changes will be extensive - especially in Categories. But that is the order that must happen. This will keep the 1.4 and 2.0 branches the most similar. We don't want them too far from each other.

**Comment by Guite** [comment]
> it *really* should include refactoring the CategoryUtil to a service
> and also CategoryRegistryUtil
> which of course means converting MOST of those to repository methods

**Comment by craigh** [comment]
Also a new Public facing API class should be created that modules can utilize to manage the categories for their module. This also replaces the Util classes.

**Comment by Guite** [comment]
Fixed in #3215
