### ISSUE TITLE
No Postcalendar access as long as Profile module is activated

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3211]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4-dev-buil140
| PHP Version       | 5.6.25

### Expected behavior
Postcalendar Frontend & Backend should be accessible

### Actual behavior
As long as Profile module is installed one cannot access any Postcalendar page. Wou will be redirected to your user profile instead of Postcalendar

### Steps to reproduce
Install 1.4.4-build140
install Profile module
set Profile to be used as main Profile module in "general settings"
Install Postcalendar
try accessing postcalendar module from admin area: uncategorized > Postcalendar

**Comment by MrMontesa** [comment]
This seems to be related to Profile. Just checked and its not only Postcalendar. Checked with Content and News as well.

Even worse, when "not registered" users now access the calendar for example they get redirected to /members/view which reveals registered user ids. This conerns me a bit so that I have disabled my testbed.

**Comment by craigh** [comment]
This is a routing problem.

from `app/cache/prod/appProdProjectContainerUrlMatcher.php`:

        // en__RG__zikulaprofilemodule_user_index
        if (rtrim($pathinfo, '/') === '') {
            if (substr($pathinfo, -1) !== '/') {
                return $this->redirect($pathinfo.'/', 'en__RG__zikulaprofilemodule_user_index');
            }

            return array (  '_controller' => 'Zikula\\ProfileModule\\Controller\\UserController::indexAction',  '_zkBundle' => 'ZikulaProfileModule',  '_zkModule' => 'ZikulaProfileModule',  '_zkType' => 'user',  '_zkFunc' => 'index',  '_locale' => 'en',  '_route' => 'en__RG__zikulaprofilemodule_user_index',);
        }

means this matches anything not already matched with only `'/'` in the url which is basically any legacy url (like `index.php?module=postcalendar&type=admin&func=index` or similar)

I'm not sure yet if this is a problem with what Profile is configuring the route to be or if there is some kind of error in how the UrlMatcher file is being generated.

however, in addition to that problem I see issues with other profile routes:

        // de__RG__zikulaprofilemodule_user_view
        if ($pathinfo === '/de//view') {
            return array (  '_controller' => 'Zikula\\ProfileModule\\Controller\\UserController::viewAction',  '_zkBundle' => 'ZikulaProfileModule',  '_zkModule' => 'ZikulaProfileModule',  '_zkType' => 'user',  '_zkFunc' => 'view',  '_locale' => 'de',  '_route' => 'de__RG__zikulaprofilemodule_user_view',);
        }

other system modules do not have the double slash problem in the route. I'll assume this is a problem with the route not being translated or something - it should be `/de/profil/view` or similar I suppose, but the path translation isn't falling back to english.

that may or may not be related.

**Comment by craigh** [comment]
this maybe was a translation (of routes) problem. I think I have fixed it. but you need the newest version of Profile to confirm

**Comment by MrMontesa** [comment]
Just tested and its working properly in build156.
Thanks much
