### ISSUE TITLE
cant re-add user "guest" to any group

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3213]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

### Expected behavior
Ability to add user "guest" to a group again.

### Actual behavior
Its possible to remove user guest from the default users group by editing via Admin panel > Users > groups > edit groupmembership of user **guest**.
After this is done, one cant revert the change as Adminpanel > Users > User Module does not contain a link to maintain **guest** user. All others can be maintained.

This was encountered during permission testing while @Guite was so kind to remove the group for me and I wanted to re-add it now.

### Steps to reproduce
Access: Admin panel > Users > groups > edit groupmembership of user guest
remove group **Users** from user **guest**
Try re-adding again by accessing: Adminpanel > Users > User Module
All users will have a "edit user" link at the end of the row, but **guest** user doesnt.

**Comment by craigh** [comment]
I wonder if the proper solution to this might be that the guest user should not be able to be removed from the group in the first place...

**Comment by MrMontesa** [comment]
For my use case this would be an option as well. As I understood,  this might also obsolete any permission rule targeting unregistered users. As the guest is part of users group. 
Just a best guess from users perspective possibly not knowing all the bits and pieces.

**Comment by Guite** [comment]
refs https://github.com/zikula/core/issues/2800

**Comment by craigh** [comment]
@MrMontesa this becomes part of a much larger discussion about the roles of users. Therefore it is moved to 1.4.5 in order to resolve some long-standing issues (e.g. all the way back to 1.3.x)

**Comment by craigh** [comment]
@MrMontesa please explain how you are using the guest user and the groups/roles/rights you are configuring.

**Comment by craigh** [comment]
Also - it is already possible to add the guest user to a group from the group membership UI (the same place you removed the user).

**Comment by MrMontesa** [comment]
Sure,
I try to not use guest user at all. Beside admin users I have 3 different permission levels.
1. Non-authenticated users
2. Authenticated users (club members)
3. Elevated authenticated users (club members also being editors)

When one joins our club one is asked to create a user on our webpage. After manual approval the new club member has access to certain "club-only" features like phone lists, internal image galleries, certain news categories, etc.
In case a club member likes to help with our page, they are allowed to also add content/news/galleries/etc. This is the elevated group.

I dont use guest user and/or group at all as robots/non-club members sometimes create accounts. Those should NOT have more rights than a non-authenticated user. In fact, a guest user is treated as a non-authenticated one.

I was testing some scenarios with guite and he asked me to remove the guest user from a certain group. Once testing was done, I wasnt able to revert the changes. Thus I created the ticket.
As you an see from my use-case I dont need to distinguish between non-authenticated and guest users at all.

One thing I noticed during testing was that I have to add my club-members to "Users" group even though I dont have special permissions for them. without this group membership I always encounter strange behavior. In fact, my club-members are in Users-group and a self created club-group. Plus the optional club-editors-group.
Hope this helps to clarify my use-case. Any questions, let me know.

**Comment by craigh** [comment]
I appreciate the very quick response.

I am going to make this a "won't fix" but I'm adding a note to the UI:

![screen shot 2017-05-08 at 4 24 09 pm](https://cloud.githubusercontent.com/assets/350048/25823676/d157db92-340a-11e7-955d-0654938849b6.png)
