### ISSUE TITLE
Complete refactoring of GroupsModule

### ISSUE THREAD

**Issue by craigh** [zikula/core#3214]
complete refactoring of GroupsModule. remove use of Util classes

**Comment by Guite** [comment]
I already have a bit for that in the pipeline as part of #3208.

**Comment by rallek** [comment]
I found several old tickets around GroupsModule. Might be some of them are done within the refactoring:
#1572, #1535, #1530, #261, #123

**Comment by craigh** [comment]
completed through several commits
