### ISSUE TITLE
Migrate service definitions to YAML

### ISSUE THREAD

**Issue by Guite** [zikula/core#3217]
I'd like to migrate service definitions from XML to YAML as it is more concise if there are no objections.
This includes not only the core, but also 3rd party extensions where I've used XML so far.

- [x] lib #3269
- [x] System modules #3269
- [x] Legal https://github.com/zikula-modules/Legal/pull/65
- [x] Profile https://github.com/zikula-modules/Profile/pull/64
- [x] Piwik
- [x] Formicula

**Comment by craigh** [comment]
please delay this until I have some time to consider it.

**Comment by craigh** [comment]
http://stackoverflow.com/questions/11741947/symfony2-why-use-xml-for-settings-config

**Comment by Guite** [comment]
Seems like PHP Storm is also able to provide auto completion for YAML: http://symfony2-plugin.espend.de/languages/yaml/index.html

**Comment by Guite** [comment]
Closed as done.
