### ISSUE TITLE
deactivating page lock is not possible

### ISSUE THREAD

**Issue by rallek** [zikula/core#3221]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4. build 147
| PHP Version       | 5.5.30

### Expected behavior
If I activate PageLock a deactivation should be passible

### Actual behavior
there is no button for deactivation for PageLock after activation

### Steps to reproduce
install 1.4.4dev and activate PageLock. 

Is this a bug or is this a feature?

**Comment by Guite** [comment]
It's a bug. Probably all core modules are prevented to be disabled. But this shouldn't be done for PageLock.
