### ISSUE TITLE
changing language requires deleting of 'hl' cookie

### ISSUE THREAD

**Issue by craigh** [zikula/core#3224]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.6

### Expected behavior
immediate change of language on the site?

### Actual behavior
nothing appears to change - but in reality the routes become localized based on the *past* cookie value. Deleting the cookie and then returning to home route seems to force the site to change to new language value.

### Steps to reproduce
Install more than one locale. Attempt to switch between them using General Settings > localization settings > Default language to use for this site

**Comment by craigh** [comment]
refs #1985

**Comment by rallek** [comment]
I do not understand :-( 

Do I have to delete a cookie? Where, How and which one?

**Comment by rallek** [comment]
With ci build 152 I made the install with German language pack. As known some phrases are not translated but most phrases are in German. The site language was set to German. Switching back to english the language switched immediately to english (as expected). Switching to German again it tooks a while until German is back. This happend while I made a new setting for time zone. After this change the site was immediately in German.

Trying around a bit more leads to the following observation:
* Site is in English and all things are correctly translated
* next you switch to German and save -> translation of strings are incorrect
* stay in localisation settings and save once more without changing anything -> translation is changed to German

Is that cookie relevant?

**Comment by craigh** [comment]
probably. find the cookie named `hl` ("home language") and delete it after changing the language. you should see the change immediately after that (plus reload).

**Comment by rallek** [comment]
But this is a bug than. That behavior is new. How that will work with the possibility to choose the language by the user?

**Comment by craigh** [comment]
I'm guessing this hasn't worked (or worked well) since 1.4.0, so sure, it is a bug - but it is one we've been dealing with for more than a year. There are several bugs which are still outstanding. It won't prevent a release. That is why this is scheduled for 1.4.5

**Comment by rallek** [comment]
Until 1.4.2 It has worked like it should. I do have two live sites, one with 1.4.1 and one with 1.4.2. By upgrading my 1.4.1 site into 1.4.3 the bug is occuring. So the bug is not that old. Might be we can fix it more easy with this information.

**Comment by rallek** [comment]
Language change in the users account is also not possible.

**Comment by craigh** [comment]
It is difficult to explain, but the bug has existed before. The reason you didn't see it before and you see it now is that in previous versions the core was not fully transitioned to the new (symfony-based) translation component. You were using the old system - which worked because it worked in 1.3.x. Now the core is (nearly) fully transitioned and therefore it no longer works as you expect.

I don't see this getting fixed before 1.4.5. I'm sorry for you (and your friend).

**Comment by rallek** [comment]
Do I have to expact any issues due to this if I am working with a german site and upgrade this one from 1.4.3 to 1.4.4? Do I have to teach all my users they have to delete a cookie? That would be a nightmare because I do have already a site up and running with 1.4.3.

**Comment by rallek** [comment]
Currently I do have the issue, even if I delete the cookie somehow the new cookie is set with the old language again. I do have to change the cookie itself from de to en to make the switch happening. 

Observed in 1.4.4

**Comment by rallek** [comment]
In 1.4.5 I am not able to login again due to language issues. See slack for details.

**Comment by rallek** [comment]
see my language settings:
![grafik](https://cloud.githubusercontent.com/assets/935250/21573072/a8944fea-cee0-11e6-8a4c-d3b26b6931ad.png)

**Comment by rallek** [comment]
This one is still painfull. The deleting of the cookie is no option. I want to ask you to fix this asap after 1.4.5 is released.

**Comment by craigh** [comment]
fixed in #3396
