### ISSUE TITLE
Make system module descriptions consistent

### ISSUE THREAD

**Issue by Guite** [zikula/core#3228]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 7.x

### Expected behavior
A consistent set of module descriptions in the extensions list.

### Actual behavior
Different notations, like `Blocks Administration Module`, `Categories administration`, `User group administration module.` or ` Create, modify and destroy menus.`

### Proposal
Use a brief description with the first word capitalised only, without the `module` suffix and without a dot at the end. Example: `User group administration`.

**Comment by Guite** [comment]
Opinions?

**Comment by craigh** [comment]
👍 

be aware that upgraded systems will not change unless you force the updates in the Upgrader

**Comment by Guite** [comment]
I do not care for upgraded systems here, just want to provide a better out of the box experience for new installations (in particular of 2.0)
