### ISSUE TITLE
Use include function instead of include tag

### ISSUE THREAD

**Issue by Guite** [zikula/core#3230]
### Expected behavior
All Twig templates should only use the include function.

### Actual behavior
Some theme templates still use the include tag (observed in Andreas08).

**Comment by Guite** [comment]
Also the namespaced path notation should be used.

Example:

Before:
```
{% include 'ZikulaAndreas08Theme:Include:footer.html.twig' %}
```

After:
```
{{ include('@ZikulaAndreas08Theme/Include/footer.html.twig') }}
```

**Comment by Guite** [comment]
Please explain why you closed this.

**Comment by craigh** [comment]
Accidental
