### ISSUE TITLE
Cannot install Pages 3.0.1

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3231]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6.25

### Expected behavior
 The module Pages is installed

### Actual behavior
I get the message 
```
You have requested a non-existent service "zikula.doctrine.schema_tool".
Initialization of ZikulaPagesModule failed!
```

### Proposal
Put the module into the folder 'modules/zikula/pages-module' and try to install clicking the install icon in extenions module.

Activating dev mode does not give more informations

**Comment by Guite** [comment]
PR: #3232
