### ISSUE TITLE
Upgrade might break Theme/CSS

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3236]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4build156
| PHP Version       | 5.6.26

I have to admit I'm not too sure if this is related to core or the re-enablement of a module after the upgrade. On first sight everything was fine after the update. Also after re-enabling the modules. But suddenly Theme broke. First the main menu did not show its cascades any longer. While doing some more tests I saw that Postcalendar was broken too.
Did the same test on a fresh install and was not able to reproduce the issue.
Screenshot of the upgraded page:
![zk144-theme-broken](https://cloud.githubusercontent.com/assets/600125/20827066/a52fdf4a-b86f-11e6-9945-20206aa9c49a.png)

Screenshot of the new installed page:
![zk144-theme-ok](https://cloud.githubusercontent.com/assets/600125/20827070/a8b96154-b86f-11e6-86d2-13e8463d8288.png)

Only obvious difference is that I dont have german language pack installed on new site and not using extmenue to display the menue.

### Expected behavior
Site's theme should look ok after upgrade

### Actual behavior
Theme broke.

**Comment by Guite** [comment]
Looks similar to https://github.com/zikula-modules/Content/issues/176
On your site some assets (CSS / JS files) are not included in the output markup.

**Comment by craigh** [comment]
Steps to reproduce ?

**Comment by MrMontesa** [comment]
Hey Craigh, I think reproducing is a tough one right now, as it only appears on my upgraded page. It might be related to some Content/Formicula change. I'm testing with @Guite right now.
I can partially reproduce it in a new install by:
- install zk1.4.4build156
- copy master of Content & Formicula into ./modules folder

**Comment by craigh** [comment]
what does "partially reproduce" mean?

**Comment by MrMontesa** [comment]
Sometime it works, sometime it doesnt.
Somtime admin-panel-meue is affected, sometimes not.
Sometimes admin area Users/Uncategorized/etc sub menues are affected, sometimes not
Sometimes only Chrome is affected because Firefox still works

I'm now focusing on a fresh install rather than my upgrade in order to better advise on how to reproduce.

**Comment by Guite** [comment]
Closed in favour of https://github.com/zikula-modules/Profile/issues/62
