### ISSUE TITLE
remove Andreas08 and SeaBreeze

### ISSUE THREAD

**Issue by craigh** [zikula/core#3247]
remove Andreas08 and SeaBreeze from Core-2.0

they are dated and add support costs. They should be moved to own repos and developed independently.

**Comment by Guite** [comment]
Personally I am fine with SeaBreeze, but love Andreas08.

**Comment by craigh** [comment]
it isn't so much about preferences, simply reducing the maintenance load from the core. It is the same reason Legal, Profile and so on are not part of the core. They all should be 'outsourced' and released more often as needed.

**Comment by MrMontesa** [comment]
As long as they are integrated during ci build the same way like profile and legal, this would be fine with me. 
I use Andreas a lot. It's easily customizable and looks individually with just changing a few colors. 
Could imagine to also add some colors as variables and such changes are indeed unrelated from core.

**Comment by Guite** [comment]
> As long as they are integrated during ci build the same way like profile and legal, this would be fine with me.

:+1: 

I think we can do this for 1.4.5 already - no need to wait for 2.0 with that. @craigh ?

**Comment by craigh** [comment]
let me think about it.

**Comment by craigh** [comment]
@Guite - let's do this for 1.5 - can you take care of it?

**Comment by Guite** [comment]
Ok.

**Comment by craigh** [comment]
I'd like to remove these from the 2.0 distribution entirely. we need to retain them in 1.x for BC

**Comment by craigh** [comment]
please move to `zikula/ZikulaAndreas08Theme` and `zikula/ZikulaSeaBreezeTheme`
