### ISSUE TITLE
Disable POT generation

### ISSUE THREAD

**Issue by Guite** [zikula/core#3251]
Starting with 1.4.5 Jenkins will not generate a POT file anymore, as the entire core uses the new translation extractor now. The job for that can be disabled.

**Comment by craigh** [comment]
>  as the entire core uses the new translation extractor now

this *may* not be true (unsure). Anything using the old controllers or AbstractApi, etc will continue to only the in the POT I think... I'm just not sure...

**Comment by craigh** [comment]
maybe it is irrelevant how the .po file is generated for then legacy code as long as a PO file exists with the string, maybe it should work. Would merit some testing before completely disabling it.

**Comment by craigh** [comment]
Also - the `.mo` file is never needed. ever. it is not loaded.

**Comment by rallek** [comment]
Unfortunately I do not know enough about the new translating system I would ask to create somthing what we can translate. Might be we do get the English files with the correct paths. So we are able to copy our translating result over the core.

As far as I know the language is now part of the file name. Something like ``filename.de.po``. Might be the translation job can create files with the name ``filename.lang.po``. That makes clear what to change within the file name. Just my thoughts. If there is a better workflow already available I should be pointed to a place how to learn (zikula related)

**Comment by rallek** [comment]
Forget my comment. I found https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/TranslationAndLanguage/Translation.md. That should help (I hope).

**Comment by Guite** [comment]
@craigh disable pot creation or not? If yes, I can do it directly after 1.4.4 is finally released. If not, we can close this as *won't fix*.

**Comment by craigh** [comment]
I would like to yes. We need to confirm that all the required strings are present in the file generated by the extractor. I think we can compare to the CI generated file or maybe find a few that are in legacy files (eg. AbstractApi, etc) and confirm they are present where needed in the new file. I don't think anything legacy will be loaded properly (in the core) but this must be fixed elsewhere (by refactoring the legacy files away). The old Translator should continue to work for legacy type modules.

**Comment by rallek** [comment]
I will countercheck the pot generation files with the new translation files this evening.

The zikula.template.po schould mainly have the same content than the generated pot files I guess.

**Comment by rallek** [comment]
the current ``.pot`` seems to be significant different from the ``.po``
![grafik](https://cloud.githubusercontent.com/assets/935250/21057794/4f8d99f2-be3b-11e6-940f-ce4b52c80bff.png)
and
![grafik](https://cloud.githubusercontent.com/assets/935250/21057849/884984c2-be3b-11e6-9733-d47b7a9bd46e.png)

**Comment by craigh** [comment]
this is good to learn. can you please explain how you did it? I cannot read the German :-)

**Comment by rallek** [comment]
First I created a new translation by using poedit and opening the zikula.template.po. I saved it as zikula.de.po. Next I updated the translation by using zikula.pot. That gives a total different picture. I did not expect this huge difference. What did I wrong?
Clear, some of the translation strings are in other files but not 1218 new and 772 outdated.

**Comment by Guite** [comment]
Postponed to 2.0.0-beta, because in 1.4.x we stil need the old pot, too, in order to catch translation strings in legacy files.

**Comment by craigh** [comment]
@Guite we need to disable the POT generation for the master branch only - and adjust the scripts to not copy the files into the package. can you do that?

**Comment by Guite** [comment]
yes

**Comment by Guite** [comment]
This is already properly configured in Jenkins.
