### ISSUE TITLE
Account information recovery is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#3254]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4 beta 2
| PHP Version       | 5.5.30

### Expected behavior
an email will be sent with further information after using the recovery function

### Actual behavior
the field for username and email is visible. If I try one of both an click the button to send the informations nothing happens the page is still the same.

I tested my mail settings. Emails are sent imediately from the mailer module email test 
Profile and Legal are deactivated

### Steps to reproduce
try to recover your password after upgrading to 1.4.4beta 2

**Comment by Guite** [comment]
please write `rc2` instead of `beta2` in future

**Comment by Guite** [comment]
did you use the `admin` user or another one?

**Comment by Guite** [comment]
can you create me a user and send me credentials by mail?

**Comment by Guite** [comment]
The process works as designed.

**Comment by rallek** [comment]
Root cause: #3256
