### ISSUE TITLE
Not possible to open the backend of Pages

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3267]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6.25

### Expected behavior
That I'm able to open the backend of Pages 3.0.1

### Actual behavior
I get an error callling Pages in the extensions module overviev.
```
The type name specified for the service "zikula.form.type.locale" does not match the actual name. Expected "zikula_locale", given "Zikula\Bundle\FormExtensionBundle\Form\Type\LocaleType"
```
### Steps to reproduce
Install Pages and call it in the extension module overview

**Comment by craigh** [comment]
@Portugao please try [build 179](http://ci.zikula.org/job/Zikula_Core-1.4.4/lastSuccessfulBuild/) and see if it works for you

**Comment by Portugao** [comment]
I'll try tomorrow.

**Comment by craigh** [comment]
@Portugao now you will need build >180

**Comment by Portugao** [comment]
It works in build 181.
