### ISSUE TITLE
Move assets to CoreBundle

### ISSUE THREAD

**Issue by craigh** [zikula/core#3270]
All Javascript in `/javascript`, stylesheets in `/style`, and images in `/images` must be evaluated and either declared as deprecated or moved to `CoreBundle/Resources/public/*`.

Most can be left I think but declared as deprecated in changelog. It would be best if the files we wish to keep in the distribution get moved immediately, but this will cause BC issues I think - Is there a way to create file aliases? maybe we could include the same file in both locations... a waste of diskspace, but BC. perhaps there is another way...

The core would need to be refactored to include the files from the new location.

#### Javascript:
 - `src/javascript/helpers/bootstrap-zikula.js`
 - `src/javascript/jquery-plugins/jQuery-Timepicker-Addon`
 - `src/javascript/js-webshim`
 - `src/javascript/plugins/colorbox`
 - `src/javascript/plugins/jQuery-contextMenu`
 - `src/javascript/polyfills`
 - `src/javascript/underscore`
 - ???
#### Images:
 - ???
#### style:
 - `src/style/bootstrap.less`
 - `src/style/bootstrap-font-awesome.less`
 - `src/style/bootstrap_variables.less`
 - `src/style/font-awesome.less`
 - ???

**Comment by Guite** [comment]
Let's deprecate `src/javascript/polyfills`, too. These scripts are quite old.

Images not to deprecate: `images/avatar`, `images/logo*`, `images/zk-power.png`.

**Comment by craigh** [comment]
wondering if these shouldn't be moved elsewhere instead - maybe ThemeModule

**Comment by Kaik** [comment]
Underscore and probably other ones can be installed via components installer in /web directory

**Comment by Guite** [comment]
We can also deprecate the following:

- jQuery-Timepicker-Addon
- jquery-minicolors
- picky_color

All these are superceeded by HTML5 input types and webshims as fallback.
See https://github.com/Guite/MostGenerator/compare/738cee863f0c5fa960012691bfa6fd9ad7d1a0f3...e7ee31dc931b792663727aef4e34cadc70eb7a48
