### ISSUE TITLE
Publish extension assets during installation

### ISSUE THREAD

**Issue by Guite** [zikula/core#3273]
When an extension is installed, it's assets should be copied into the appropriate subfolder of `web`.

**Comment by shefik** [comment]
And when an extension is upgraded? Removed when uninstalled?

**Comment by Guite** [comment]
Yes.

**Comment by Guite** [comment]
This needs to be done for modules as well as themes.

**Comment by craigh** [comment]
the difficulty here is that the web user (php?) may not have rights to the `/web` directory. The assets are typically installed by composer being run at the CLI by a user with rights to the directory. The php user typically has rights only to the cache directory.

If the rights issue is worked out, then this is pretty straightforward, I think. 

https://github.com/zikula/core/blob/1eb9e37e90f6a5442dd067fc9f5ec28f166167cf/src/lib/Zikula/Bundle/CoreBundle/Command/AssetsInstallCommand.php#L68-L68

**Comment by Guite** [comment]
Modules should also be able to perform custom push/copy operations. For example if images are dynamically generated they need to be copied into the `web` folder again after they have been updated.

**Comment by craigh** [comment]
again - I don't see how this can be done as there will be a rights/access issue to the `/web` directory

**Comment by Guite** [comment]
possible if we depend that on #3438 ;-)

**Comment by craigh** [comment]
actually, this was originally implemented
https://github.com/zikula/core/blob/68f862e07a0688eea776221e32c889d7c436bd70/src/system/ExtensionsModule/Controller/ModuleController.php#L350-L350
but it is commented because the feature takes too long.

**Comment by craigh** [comment]
refs #3804

**Comment by Guite** [comment]
Moved to 3.0.0 because index.php will be moved into public folder!

**Comment by craigh** [comment]
FYI - this is now done 'on the fly' when the asset is needed and not found, it is [copied](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/Asset.php#L132-L135) from the bundle `public` directory to the project `public` directory and served from there. This could be sped up further (maybe) by

1. symlink instead of full copy
2. do not [check files for existence](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/Asset.php#L97-L99) (and similar later in class)

**Comment by Guite** [comment]
Proposal for a first solution of this task:

An event handler should remove all assets from `public/modules/acmefoomodule/` when AcmeFooModule is updated (to ensure renewal) or removed (to cleanup).

**Comment by craigh** [comment]
agreed
