### ISSUE TITLE
User unknown in password recovery (zauth)

### ISSUE THREAD

**Issue by rallek** [zikula/core#3274]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4 RC5
| PHP Version       | 5.5.30

### Expected behavior
password recovery is working

### Actual behavior
The user is not know anymore if he not logged in one time after the zauth is introduced (after upgrade the core).

### Steps to reproduce
Upgrade from 1.4.1 to 1.4.4 and try to recover password of an already registered user.

#3256 is not solved completely. It is only solved 70%. But this is not a blocker for RC5

**Comment by Guite** [comment]
@rallek can you please test whether #3277 fixes this issue for you? It aims not only on *lost password*, but also on *lost user name*. If it works, we can still put that into 1.4.4.

**Comment by rallek** [comment]
tested both. Great job! That is working well now for both cases.

**Comment by Guite** [comment]
@craigh put into 1.4.4?
