### ISSUE TITLE
Consider outsourcing PageLock

### ISSUE THREAD

**Issue by craigh** [zikula/core#3283]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0
| PHP Version       | n/a

I think we should consider outsourcing PageLock for Core-2.0

**Comment by Guite** [comment]
Could also be done for 1.4.5, similarly to Andreas08 and SeaBreeze, refs #3247

**Comment by Guite** [comment]
We could even stop having PageLock in `system`, but put it into `modules` instead. This would also solve #3379.

**Comment by craigh** [comment]
yes - that's exactly what would be done (like Profile, Legal, etc)

the only question is **when**, not **if**

**Comment by craigh** [comment]
refs https://github.com/zikula/core/commit/46c43cc472872719f108ed6e015d2b36c4e6b883

**Comment by craigh** [comment]
@Guite - let's do this for 1.5 - can you take care of it?

**Comment by craigh** [comment]
there are some spots in the core that would need to be adjusted here also...

**Comment by Guite** [comment]
Ok.
