### ISSUE TITLE
Updating "database_server_version" in custom_parameters.yml

### ISSUE THREAD

**Issue by shefik** [zikula/core#3285]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.2.6

### Expected behavior

The version of MySQL should be accurate.

### Actual behavior

If this were a new install of Zikula, the value for `database_server_version` would get correctly set to the version of MySQL installed. However, if this were an upgrade, the value for `database_server_version` does not get modified in the file `app/config/custom_parameters.yml`.

What is the specific purpose for setting the MySQL version in this file? Does this mean that every time MySQL is upgraded on the server, you must remember to manually update this file (even if it's a minor incremental upgrade to MySQL)?

What happens if this value is not accurate to the actually installed version of MySQL? For example, if you are on a shared host, and the host doesn't notify you beforehand that MySQL was upgraded to a new version. Seems like we should rethink having to set a value for the MySQL version in the file.

### Steps to reproduce

Perform an upgrade to Zikula 1.4.4.

**Comment by Guite** [comment]
maybe refs #2185 @craigh ?

**Comment by craigh** [comment]
> Seems like we should rethink having to set a value for the MySQL version in the file

it is required.

**Comment by craigh** [comment]
closing as NOT CORE
