### ISSUE TITLE
login "remember me" is not functioning

### ISSUE THREAD

**Issue by rallek** [zikula/core#3290]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 and 1.4.4
| PHP Version       | 5.5.30

### Expected behavior
if I use the checkbox for remember me during login I should be remembered

### Actual behavior
next time I visit my page I have to login again

### Steps to reproduce
use the remeber me function during login, close the browser window without logging out, and go to you website again. You are not logged in anymore.

It doesn't matter which setting I do have in security setting (tested medium and low)

**Comment by rallek** [comment]
I compared the behavior of the cookie. In 1.4.2 the live time of the cookie is changing after login to the following:
![grafik](https://cloud.githubusercontent.com/assets/935250/21285850/7337f24e-c444-11e6-88b6-2d17914c7051.png)
But since 1.4.3 the behavior is different. Before I logged in the cookie is looking as follow:
![grafik](https://cloud.githubusercontent.com/assets/935250/21285856/a092895c-c444-11e6-861c-03272773d363.png)
Valid until end of the session. That is right. But after logging in it is unchanged. It doesn't matter if I have the setting in the security settings to low or middle. And it doesn't matter if I am checking the remeber me function at login or not.

**Comment by rallek** [comment]
next observation: The _zsid cookie is marked as ``Sitzungscookie`` (session cookie). If I uncheck "session cookie" and add another date in future I am still logged in when leaving the site an come back.

**Comment by rallek** [comment]
Next observation: I do have two similar sites one is my live site with URL ``mysite.tld`` and the other one is my testing site with the URL ``testing.mysite.tld``.

For the testing site I already manually unchecked the session cookie but not for the live site. I now logged in into the live site and opend in another tab my testing site. I was not logged in into my testing site anymore automatically. I looked for the cookies and can see two _zsid cookies. The one from the live site was still a sessions cookie and the one for my testing site do have still the longer valid time.

My conclusion: Both sites choose the same cookie with session is disabled.

There is something mixed up with the session handling. Might be it is also the same root cause for the language setting cookie.

**Comment by Guite** [comment]
Just a guess in the wild: @rallek please check in the SecurityCenter config page which value the settings `Garbage collection probability` and `Periodically regenerate session id` have. Maybe try changing the second one to `false` and see if this makes a difference.

**Comment by Guite** [comment]
There is also a third setting `probability of regeneration` which may be relevant, too.

**Comment by rallek** [comment]
Might be. But when I change somethinge here I do get the following message:
````
Fehler! Die Datei /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/system/SecurityCenterModule/Resources/config/phpids_zikula_default.xml mit den PHPIDS-Regeln existiert nicht oder ist nicht lesbar.
````
Why this is looking for 1.4.1? It should be a different path :-(

**Comment by rallek** [comment]
found it. Because in the database there is the absolute path instead of relative for several module variables. Will try to change them

**Comment by rallek** [comment]
changed ``Periodically regenerate session id`` to ``false`` but with no effect to the problem.

**Comment by Guite** [comment]
Probably related:

http://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-cookie-lifetime

We do not specify a `cookie_lifetime` anywhere in the core.

cc @craigh

**Comment by craigh** [comment]
Gültig bis = Date of Expiry
Am Ende der Sitzung = At the end of the session

**Comment by rallek** [comment]
Correct translated
