### ISSUE TITLE
cannot deactivate menu module after installation

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3296]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5.26

### Expected behavior
One should be able to de-activate menu module after it got installed

### Actual behavior
Cannot deactivate menue-module after installation.
I'm about to troubleshoot some wired behavior with my menues which appeared after I activated menu module. So I wanted to de-activate the module in order to do some tests. There's no deactivate button for menu module while Profile/Legal/etc do have one.
### Steps to reproduce
- Install zk 1.4.4
- install menu module
- try to disable menu module

**Comment by Guite** [comment]
I guess the menu module can not be disabled on purpose because it is a system module. The only exception here is PageLock which can be disabled like a normal module.

@craigh can probably confirm that

**Comment by craigh** [comment]
right.
