### ISSUE TITLE
Update wizard and generator-bundle

### ISSUE THREAD

**Issue by Guite** [zikula/core#3297]
As part of #3196 the wizard I've forked and updated the generator-bundle components to work with Symfony 3. These changes must be merged back.

Afterwards the composer file needs to be updated again removing the virtual repositories for my forks:
```
        {
            "type": "vcs",
            "url": "https://github.com/Guite/GeneratorBundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/Guite/Wizard"
        }
```

**Comment by craigh** [comment]
If you can, please merge the `array()` -> `[]` and any other BC changes into the master branch of both. Tag that version at `1.0` or something appropriate. then create a `2.0` branch and merge the other changes there. modify the composer.json settings in each version to set the dependency on the correct version and it should be all set.

**Comment by craigh** [comment]
The generator needs some major updates because I believe it was built to generate modules that are no longer compatible.

**Comment by craigh** [comment]
btw - the generator bundle is currently disabled. https://github.com/zikula/core/blob/fa040913bf1a4b13583d54b4feb69aed21de9e0a/src/app/ZikulaKernel.php#L87-L87

**Comment by craigh** [comment]
probably should be located in `require-dev` in composer file.
