### ISSUE TITLE
Refactor remaining calls of legacy util classes

### ISSUE THREAD

**Issue by Guite** [zikula/core#3307]
Both `/lib` and `/system` still contain many calls of deprecated util classes. These need to be replaced. This should not be done by one huge PR, but split into several smaller ones.

- [ ] lib
- [x] Admin
- [x] Blocks
- [x] Categories
- [x] Extensions
- [x] Groups
- [x] PageLock
- [x] Routes
- [x] Search
- [ ] SecurityCenter
- [x] Settings
- [x] Theme
- [x] Users
- [x] ZAuth

**Comment by craigh** [comment]
refs https://github.com/zikula/core/issues/3214

**Comment by craigh** [comment]
Util class usage is allowed to remain in classes/files that are marked legacy and then removed from `master`.

Util class usage is also allowed in non-legacy classes/files if the code is marked as `// @todo @deprecated remove at Core-2.0` and then removed from `master`

**Comment by craigh** [comment]
Groups is complete. calls remain in the Api classes which are already removed from master.

**Comment by craigh** [comment]
ZAuth is complete.

Users completion is dependent upon updates to Api in Profile for searching DUD

**Comment by craigh** [comment]
closing this because the remaining issues are solved by other tickets.
