### ISSUE TITLE
Date Format Uses Current Date, Instead of Date Passed to Filter

### ISSUE THREAD

**Issue by shefik** [zikula/core#3308]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.2.6

### Expected behavior

Insert this code in a Twig template:

`{{ app.request.attributes.get('month')|date('F') }}`

It takes the month passed from the GET request, assumably a 2-digit year, such as `12`. Then, formats it to the string `December`.

### Actual behavior

When using the filter, the month always returns as `December`, even if a different month is passed to the GET request, such as `11`. In this case, `November` is expected as the result, by `December` always returns, regardless of the month. Without using the filter, the correct 2-digits for the month returns correctly.

### Steps to reproduce

Insert this code in a Twig template:

`{{ app.request.attributes.get('month')|date('F') }}`

**Comment by shefik** [comment]
I suppose it's working as expected, since the date filter expects a format supported by `strtotime`, such as `2016-11`, instead of just passing the month `11`?

**Comment by craigh** [comment]
The variable `{{ app }}` is [provided by symfony](https://symfony.com/doc/current/templating/app_variable.html). Please file a ticket with [them](https://github.com/symfony/symfony).
