### ISSUE TITLE
User Name Allows Spaces to be Registered

### ISSUE THREAD

**Issue by shefik** [zikula/core#3312]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

User names should not be allowed to have spaces in the name, when registering.

### Actual behavior

You can register a name such as `Test User`.

### Steps to reproduce

Register a new account, using `Test User` as the user name.

**Comment by craigh** [comment]
Yes. This is now allowed.
