### ISSUE TITLE
Implement MenuModule permissions

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3314]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5build31
| PHP Version       | 5.5.26

### Expected behavior
Surpress displaying of MenuModule block by permission

### Actual behavior
Menu is still displayed

### Steps to reproduce
create a new MenuModule menu name it as you like
create a new block containing this Menu (use Andreas08 and choose topnav as position for example)
cross check that you have "dummy child" entry now in your topnav
add permission as per docu:

```
Group: all groups
Component: ZikulaMenuModule::
Instance: ::
Level: no access
```
Sign off
Remove cache to be on the safe side and...
You still see the "dummy child" entry

**Comment by MrMontesa** [comment]
Not sure if already implemented as MenuModule is quite new. But would make sense to hav more granular options for Instance to set permission level.
E.g: MenuModule ID::
to be able to restrict on menu level an not over all.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Menu/Permissions.md

**Comment by MrMontesa** [comment]
It was listed in the `Permission rules information` tab so for the end-user it seemed to be implemeted.
Then you might want to keep this ticket as a feature request.
