### ISSUE TITLE
New permission can not been edited anymore

### ISSUE THREAD

**Issue by rallek** [zikula/core#3317]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5.30

### Expected behavior
A new permission should be able to be edited

### Actual behavior
A click at the pen do not show up the edit form. The pen is also not turning around. Older permission from the time before upgrade can be edited.

### Steps to reproduce
upgrade a site to 1.4.4, add a new permission and try to change it. Deleting and moving arround is now problem.

**Comment by Guite** [comment]
Is editing still impossible after a reload?

**Comment by Guite** [comment]
Maybe related with #3311

**Comment by rallek** [comment]
Thats it, a reload is doing the trick!
