### ISSUE TITLE
Registration Fails, If Dropdown Form Field Is Required

### ISSUE THREAD

**Issue by shefik** [zikula/core#3318]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

New registrations should be successful.

### Actual behavior

A new user is not registered.

### Steps to reproduce

Install the Profile module. Then, go to `/profile/admin/edit/4` and set the Time Zone Offset field to `required`. Then, attempt to register a new account at `/register`.

If you reset the field back to option, then registration is successful.

You can also repeat the error, if you create a `country` dropdown field and make it required.

**Comment by shefik** [comment]
Possibly related. Seems to be a a couple issues with dropdown form fields at user registration.

Refs. https://github.com/zikula/core/issues/3319

**Comment by Guite** [comment]
Isn't this a profile issue rather than a core one?

**Comment by craigh** [comment]
yes. please reopen at Profile.
