### ISSUE TITLE
New Registration - Dropdown Selections not Retained

### ISSUE THREAD

**Issue by shefik** [zikula/core#3319]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

The selected option should populate.

### Actual behavior

The selected option does not populate.

### Steps to reproduce

Create a new user, and select a time zone. Then, as an admin, to modify the user at a URL like `/users/admin/user/modify/16`. You will see that the selected time zone from registration is not selected in the dropdown.

**Comment by Guite** [comment]
Isn't this a profile issue rather than a core one?

**Comment by shefik** [comment]
Not sure where the bug is coming from, cause the error can occur with just the Time Zone dropdown and not any other custom fields.

**Comment by craigh** [comment]
yes. please reopen at Profile.
