### ISSUE TITLE
Problems with CategoriesType

### ISSUE THREAD

**Issue by Guite** [zikula/core#3320]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior
Category selection working like other form fields.

### Actual behavior
The following behaviour has been observed for `multiple=false`:
When an existing entity is edited no category is preselected in the dropdown value. If then another category is selected, the entity has both categories assigned afterwards. If one of the assigned categories are selected, an error message appears:
```
An exception occurred while executing 'INSERT INTO
rk_downlo_file_category (registryId, categoryId, entityId) VALUES (?, ?, 
?)' with params [9, 10009, 3]: SQLSTATE[23000]: Integrity constraint 
violation: 1062 Duplicate entry '9-10009-3' for key 'cat_unq'
```

### Steps to reproduce
Use `CategoriesType` with `multiple` set to `false`. Try to edit an entity multiple times.

**Comment by craigh** [comment]
be sure to check any changes with usage in Pages also. This FormType took a lot of effort to get to where it currently is (which I thought was pretty functional). So - it is quite complex. We should probably create some tests to ensure it behaves as expected always.

**Comment by rallek** [comment]
if you are using ``multiple`` set to ``true`` you can also only add categories. If you select another category the unselected former category is still there. So the problem is indipendant of ``CategoriesType``.

**Comment by rallek** [comment]
If I try to change an item in my MOST module without changing anything at the categories I do get the following error message:
````
Sorry, but an error occured during the update action. Please apply the changes again! An exception occurred while executing 'INSERT INTO rk_downlo_file_category (registryId, categoryId, entityId) VALUES (?, ?, ?)' with params [10, 33, 2]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10-33-2' for key 'cat_unq'Error! Update attempt failed.
````

**Comment by craigh** [comment]
My assumption with this ticket would be that it is a problem with the entity and it's implementation of Categories. It is very complex.

in Pages, it is used as described: https://github.com/zikula-modules/Pages/blob/master/Form/Type/FilterType.php#L37

here, it works correctly. In addition it is also used in the edit form: https://github.com/zikula-modules/Pages/blob/master/Form/Type/PageType.php#L75-L81

The entity must contain proper setters https://github.com/zikula-modules/Pages/blob/master/Entity/PageEntity.php#L497-L534

**Comment by Guite** [comment]
I think the missing magic is in the setter method. In Pages it removes all categories which are not given before adding the ones given as argument: https://github.com/zikula-modules/Pages/blob/master/Entity/PageEntity.php#L502

Closed as not-core.

**Comment by Guite** [comment]
Yep - this was the missing part.
