### ISSUE TITLE
Unable to modify English (en) strings

### ISSUE THREAD

**Issue by shefik** [zikula/core#3323]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

The English (en) strings should be modified.

### Actual behavior

The English (en) strings are not modified.

### Steps to reproduce

Create these files, and modify strings:

`/app/Resources/translations/zikula.en.mo`
`/app/Resources/translations/zikula.en.po`

If you do not set a translation, it does not default to the source text. As a example, place this in your site theme `{{ __('Account Settings') }}`, without setting a translation. The result will be empty. If you then set a translation (even set it again as-is in English `Account Settings`, then you will see the output on the page.

Refs. https://github.com/zikula/core/issues/3132

**Comment by craigh** [comment]
changing the values requires refreshing the cache. did you clear it after?

**Comment by craigh** [comment]
> place this in your site theme `{{ __('Account Settings') }}`, without setting a translation.

what does "without setting a translation" mean?

**Comment by craigh** [comment]
**I added this to `/src/themes/BootstrapTheme/Resources/views/Body/3col_w_centerblock.html.twig`**

![screen shot 2017-02-01 at 7 14 48 pm](https://cloud.githubusercontent.com/assets/350048/22532099/26e736f0-e8b3-11e6-8bbb-ba35c59887c0.png)

**I changed nothing in the translation files, so it looks like this (at the bottom):**

![screen shot 2017-02-01 at 7 15 00 pm](https://cloud.githubusercontent.com/assets/350048/22532100/26f39f08-e8b3-11e6-9886-ed471c42b573.png)

**Then I changed the `/src/themes/BootstrapTheme/Resources/translations/zikula.en.po` file:**

![screen shot 2017-02-01 at 7 17 21 pm](https://cloud.githubusercontent.com/assets/350048/22532098/26dd5d9c-e8b3-11e6-9928-ed814e79cfa3.png)

**Now it looks like this:**

![screen shot 2017-02-01 at 7 17 11 pm](https://cloud.githubusercontent.com/assets/350048/22532097/26c8bd2e-e8b3-11e6-987c-50adbbf447f8.png)

-----
conclusion - it appears to work.
