### ISSUE TITLE
Decide about ZLanguage

### ISSUE THREAD

**Issue by craigh** [zikula/core#3328]
Either remove and replace or continue usage somewhow

**Comment by Guite** [comment]
I guess the only "interesting" method it contains is `getInstalledLanguages()`??

**Comment by Guite** [comment]
We are using `$request->getLocale()` already instead of `ZLanguage::getLanguageCode()`, right?

Symfony offers better selectors for countries and language, so we might consider using these instead of the old countryMap/languageMap stuff.

But I think two things from `ZLanguage` are useful:

1. Determining a list of installed languages. Maybe we can provide a form type for that as a replacement :thinking: 
2. Detecting the browser language. Don't know whether Symfony offers something similar we could use :question:

**Comment by Guite** [comment]
> Maybe we can provide a form type for that as a replacement :thinking:

This would be consequent, as we do so for locales, too.

**Comment by craigh** [comment]
looks like we can use PHP's Intl component. Since it is a php extension, it requires the server to have it installed (or the user to work with their provider to do so). Symfony provides a compatibility layer if the extension isn't installed, but this only works for the default locale of `en`. So, the Core wouldn't break if it wasn't installed - it simply wouldn't provide proper information if the desired locale is not `en`.

We would still need to provide a method to determine the installed languages. I see two options for this:
  1. the same as now - scan the `/locale` dir for locale definitions.
  2. scan the `/translations` directory and parse the domain names for the locales.

Because I **think** that the Intl component takes care of all the "other" stuff that the locale definitions was used for, it makes sense to me to eliminate that and use the second option. But because I don't know anything about how that data was used before, or the need for this data in the future, I don't really know.

I need more input about this.

@cmfcmf @rallek @shefik @Guite @Portugao

**Comment by Guite** [comment]
If `Intl` is not available the core could at show a notification about this to the admin.
As Symfony pushes the usage of this PHP component I vote :+1: for adopting it, too.

**Comment by craigh** [comment]
interesting discussions: https://github.com/silverstripe/silverstripe-framework/issues/6194
https://github.com/silverstripe/silverstripe-framework/issues/6207

**Comment by rallek** [comment]
I can not really add something important in this discussion. One advantage I cann see myself in the locale.ini what is configured for the laguage. But I do not know if that is used somewhere else than gettext.

Might be I do not get the point. In this case you can forget my thoughts ;-)

**Comment by craigh** [comment]
closed by #3366
