### ISSUE TITLE
Decide about StreamReader

### ISSUE THREAD

**Issue by craigh** [zikula/core#3330]
at `/src/lib/StreamReader` there is a Pear-style named class.

decide to keep or remove. if keep, probably need to refactor and alias for BC

seems related to concepts here:
http://php.net/manual/en/ref.stream.php
http://php-and-symfony.matthiasnoback.nl/2012/04/php-setting-up-a-stream-wrapper-for-manipulating-the-dom/
http://php-and-symfony.matthiasnoback.nl/2012/04/php-a-custom-stream-wrapper-part-2-reading-and-seeking/

**Comment by Guite** [comment]
Seems to be used by the old Gettext stuff.
Personally I'd be glad to get rid of it.
