### ISSUE TITLE
smarty blockposition do not work anymore

### ISSUE THREAD

**Issue by rallek** [zikula/core#3336]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5.30

### Expected behavior
use a block position like ``{blockposition name='news'}`` should work like usual

### Actual behavior
nothing is shown in the output

### Steps to reproduce
create a new blockposition in a news template e.g. ``News\templates\user\menu.tpl`` with the name ``news``. Than use the plockposition with a normal block.

I tried also the new twig notation ``{{ showblockposition('news') }}`` But that leads into a smarty error.

**Comment by craigh** [comment]
Is the theme twig or smarty based?

**Comment by craigh** [comment]
I don't think it ever worked like you have described. I think in the old system you have to create the block position in the admin interface also.

**Comment by craigh** [comment]
> create a new blockposition in a news template e.g. News\templates\user\menu.tpl with the name news. Than use the plockposition with a normal block.

this is not enough information. **how** did you 'create a new block position'? How did you 'use' it?

**Comment by Guite** [comment]
He both created the block position in the blocks module and assigned a block to that position.

**Comment by rallek** [comment]
The theme is based on the BootstrapTheme. Blocks with twig notation are working fine within templates of ZikulaPagesModule.

**Comment by craigh** [comment]
This ticket still makes no sense to me. Bootstrap theme is a twig theme. Why would it throw smarty errors? Are you attempting to create a block position within a module (News) template? If so, I'm pretty sure that has *never* been supported.

**Comment by rallek** [comment]
yes I do so. The news template do have this blockposition and I am pretty shure it works in former times but I can not say how long ago. As I do not have a running 1.3.x site anymore I am not able to demonstrate.

**Comment by craigh** [comment]
This is not how the system is designed to work. block positions belong in the theme templates.

**Comment by Portugao** [comment]
I work with this feature on a site with 1.3.10. I have a block position created in the blocks module and call the position within a template of clip and it works.
