### ISSUE TITLE
groups are not working correct with 1.4.5RC1 on multilingual sites

### ISSUE THREAD

**Issue by rallek** [zikula/core#3341]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Expected behavior
when I go to admin groups I want to see all groups

### Actual behavior
I do see only my public group even if the route is /groups/admin/list
![grafik](https://cloud.githubusercontent.com/assets/935250/21572613/7b2ce24c-cedb-11e6-83e5-fb447e97c074.png)

### Steps to reproduce
use a site with another language than english and go to the groupsModule

As of the language cookie bug it is difficult to switch bak to english I did it the following way: I changed the site settings to english, saved it and changed the cookie by hand from de to en. That is not working alsway in the right way. It is flipping back to german or the site settings are going back to german. Never the less. After a while trying to get the page back in english I was able to go via admin menu to the groupsModule. Now I am seein all groups within the admin surrounding
![grafik](https://cloud.githubusercontent.com/assets/935250/21572731/e08c31d2-cedc-11e6-8c70-80c7268270f5.png)
The URL ist still the same!
![grafik](https://cloud.githubusercontent.com/assets/935250/21572735/fb48e97a-cedc-11e6-85b7-f941601a25af.png)

**Comment by craigh** [comment]
offhand, this makes no sense, since there are no restrictions on the fetch operation for groups:

https://github.com/zikula/core/blob/1.4/src/system/GroupsModule/Controller/GroupController.php#L91

**Comment by rallek** [comment]
``unconfirmed`` sounds allways hard to me. Is that necessary?

**Comment by craigh** [comment]
**unconfirmed** simply means that whomever has tested it (in this case me) is unable to reproduce it or it seems illogical and therefore difficult to assume it is a bug. It isn't a personal attack and you shouldn't be offended. If I close the ticket and label it **discarded** then you can be offended if you like 😜

**Comment by rallek** [comment]
can not reproduce anymore. See my upgrade experience documented within #3345 

after this new upgrade I do have this issue not anymore.
