### ISSUE TITLE
Groups 2.4.1 (zk 1.4.5) can not be saved with unchecked check boxes

### ISSUE THREAD

**Issue by rallek** [zikula/core#3342]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Expected behavior
I should be able to save groups setting with some checkboxes unchecked.

### Actual behavior
![grafik](https://cloud.githubusercontent.com/assets/935250/21572772/5c6c5fd4-cedd-11e6-8edb-f3c64f1a4c33.png)
check boxes are mandatory. That is nonsens because I only can save the form if I select them :-)

### Steps to reproduce
try to change the groups setting yourself ;-)

**Comment by craigh** [comment]
works for me.

Groups 2.4.1 / Zikula 1.4.5 / Symfony 2.8.15 / PHP 5.5.26

**Comment by craigh** [comment]
I am using Apple Safari browser. You?

**Comment by rallek** [comment]
Firefox. Tried to use chrome as well but I can not login anymore. see #3343

**Comment by rallek** [comment]
But how make it sence to have a bool field mandatory. If it is mandatory it must be checked.

**Comment by Portugao** [comment]
There is no sense.
@craigh 
You can save with one checkbox disabled?

**Comment by cmfcmf** [comment]
> But how make it sence to have a bool field mandatory. If it is mandatory it must be checked.

Think of a "I accept the terms of service" field.

**Comment by craigh** [comment]
I clicked one box:
![screen shot 2016-12-30 at 6 53 12 pm](https://cloud.githubusercontent.com/assets/350048/21574467/4adc331e-cec1-11e6-8490-dc8859e28a30.png)
Then clicked save:
![screen shot 2016-12-30 at 6 53 23 pm](https://cloud.githubusercontent.com/assets/350048/21574468/4c688fca-cec1-11e6-9260-1581425913d5.png)

**Comment by craigh** [comment]
@rallek what error do you get?

**Comment by Guite** [comment]
@craigh shouldn't there a `'required' => false` be added?
https://github.com/zikula/core/blob/1.4/src/system/GroupsModule/Form/Type/ConfigType.php#L44

**Comment by Guite** [comment]
Otherwise the browser may prevent the submit if the checkbox is not enabled

**Comment by Guite** [comment]
See #3344

**Comment by craigh** [comment]
> Otherwise the browser may prevent the submit if the checkbox is not enabled

it doesn't prevent my submission. I would like to know why.

**Comment by Guite** [comment]
Check if the checkboxes contain a `required` attribute in the html markup.
Also you can check http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_checkbox_required for example.

**Comment by craigh** [comment]
![screen shot 2016-12-31 at 7 02 32 am](https://cloud.githubusercontent.com/assets/350048/21577407/48ae1ca4-cf27-11e6-9982-177b0f1b210b.png)

**Comment by craigh** [comment]
notice how the checkboxes in my screenshots do not have any red border but in Ralf's they do. I wonder why?

**Comment by rallek** [comment]
But with #3344 it is working fine. Just tested.

**Comment by Guite** [comment]
@craigh which browser are you using?

**Comment by Guite** [comment]
it seems that Safari doesn't support the required argument at all.

**Comment by craigh** [comment]
> I am using Apple Safari browser. You?

**Comment by Guite** [comment]
it is a browser deficite... Firefox, Chrome, Opera, Edge - they all support it

**Comment by craigh** [comment]
ok

**Comment by Guite** [comment]
http://stackoverflow.com/questions/23261301/required-attribute-not-work-in-safari-browser

**Comment by Guite** [comment]
Wondering whether this works if polyfills are used... could you try it?

**Comment by craigh** [comment]
how? I thought polyfills were used already

**Comment by Guite** [comment]
only if the Twig extension is used in the form's template

And yes, polyfills fix it: http://stackoverflow.com/questions/32684657/safari-is-not-acknowledging-the-required-attribute-how-to-fix-it#answer-34090932

**Comment by Guite** [comment]
See #3348
