### ISSUE TITLE
several problems during upgrade my site

### ISSUE THREAD

**Issue by rallek** [zikula/core#3345]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Pick out what you want and see parts of this experience as issues.

My observations during upgrade:
- preparing as usual before upgrading: copy database, rescue both config files, userdata, theme, modules
- unpack build 101 in a new directory
- create a new database, update both config files with the new login, and the new sub-domain (as I want to keep my testing site for other tests and development). Attention! no other changes are made in the config file. locale remains ``locale: de`` as there is no instruction how to handle languages in the upgrade instruction.
- load data into the database
- open in webbrowser the new url (``router.request_context.host: upgrade.oldtimer-ig-osnabrueck.de``)
- the site was offline, thats ok, the admin do have to login first. done
- Upgrade start was shown, and again the admin has to login
- begin upgrader, no problems, finish
- 
![grafik](https://cloud.githubusercontent.com/assets/935250/21577036/2683bb78-cf4c-11e6-8c71-f4218094c7a8.png)
- clicking on the menu for left admin menu (by the way: great thing! I love it)
- 
![grafik](https://cloud.githubusercontent.com/assets/935250/21577046/879d153a-cf4c-11e6-8754-33ec532a044a.png)
- opening ``Routes``
![grafik](https://cloud.githubusercontent.com/assets/935250/21577068/a9dd1374-cf4d-11e6-8cbc-957b3c34f249.png)
- reload routes
![grafik](https://cloud.githubusercontent.com/assets/935250/21577075/da6cb120-cf4d-11e6-86fa-c3070ab9041b.png)
- hl cookie looks like following: 
![grafik](https://cloud.githubusercontent.com/assets/935250/21577082/01f24002-cf4e-11e6-9920-2bbd20bb16f7.png)
- locale in config file change to ``locale: en`` (rememeber: Until now I do not have copied the german language pack back to the upgrade)
- countercheck what happens if I now would login. So I used chrome instead of Firefox and opened the upgrade site:
````
[2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Classname RK\WebsiteHelperModule\Block\ItemListBlock does not exist.").   +

[1/2] RuntimeException: Classname RK\WebsiteHelperModule\Block\ItemListBlock does not exist.   +

Logs   -
````
- next I will upload my modules
- going to extensions and see, all missing modules are now marked as active, nice. let us go back to the chrome instance and reload the page (remember: main configuration is not checked right now, also not the language settings as there are no additional language right now)
- the site is showing up well, but English of course. Let us first try to login with the test user
- login is working, but the following question is showing up (legal and profile are avtive):
![grafik](https://cloud.githubusercontent.com/assets/935250/21577118/ae613450-cf4f-11e6-8bea-2735119a0ffe.png)
**But there is no link!**
- I canceled and logged out
- Now I will upload translations and want to see what happens
- First upload legacy translation of Mr. Montesa, went to location settings, changed to german, dlete the hl-cookie, and save
- location settings is still showing up in english but menu is changing a bit:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577175/6fa4fea2-cf51-11e6-80bf-a9f0866bcbf8.png)
the ``sitename`` is now the german one, but there is still ``home`` instead of ``startseite``
- let us see what experience the test user on chrome is now having
- login seems possible but in english:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577182/d0d5f03c-cf51-11e6-8913-058b0520362d.png)
but I did not login now.
- now I will upload my translation files I am using within my 1.4.4 
- going back to firefox and the admin login into the language settings and relod the browser page:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577194/bfe530a2-cf52-11e6-9935-8edca92fd73f.png)
- let us see what the cookie is doing:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577196/d91565ba-cf52-11e6-9ae8-60198f9c5f8f.png)
- it flipped back to en :-(. Ok, will delete it again
- result: now it is in German language.
- let us see what the test user is doing on chrome
- site was still in English. Because I can not figure out in short time how to delete the cookie in chrome I am using the incognito session to be shure there is no cookie involved anymore. nice, the site is in German and login went fine (but what shall I tell my users??? How should they proceed?)
- But have a look now:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577231/f87c80cc-cf53-11e6-93af-6b25d264cd9e.png)
- suddenly the ``home`` is showing again. On my login site it was still the german:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577236/3739718a-cf54-11e6-8bd0-0fa54525d264.png)
- all the other menu items are hard coded and untranslated.
- the test user is now opening an untranslated most module:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577250/97fb7478-cf54-11e6-92f6-d3392631597b.png)

That are my experience while upgrading zu far.

Next I will delete everything and do everything with translation in one step. Let see what happens than.

**Comment by Guite** [comment]
schedule to 1.4.6... you might restest this after #3224 and #2684 have been done

**Comment by craigh** [comment]
closing this as it is too many things for one ticket. As @Guite said above, please retest with 1.4.6-dev and if possible report individual issues as necessary. Thanks.
