### ISSUE TITLE
[Groups] make group description/responses translatable

### ISSUE THREAD

**Issue by rallek** [zikula/core#3346]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Expected behavior
I want to make a description in german and english but there is only an not translatable field available

**Comment by rallek** [comment]
also the answers if you deny a group membership should be possible in different languages:
![grafik](https://cloud.githubusercontent.com/assets/935250/21577408/965bb3bc-cf59-11e6-8e9a-51e17a44422c.png)

**Comment by Guite** [comment]
Closing as won't fix as applications are to be removed.
