### ISSUE TITLE
[Groups] make the email address for emailing configurable

### ISSUE THREAD

**Issue by rallek** [zikula/core#3349]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Expected behavior
I currently can only check a ceckbox to send email notification when a user applies a private/open group. But I want to configure also who should get this email. Best would be to be able to configure more than one user/email.

### Actual behavior
not possible. And nor information who will get this info (the admin?)

**Comment by Guite** [comment]
Closing as won't fix since applications are to be removed.
