### ISSUE TITLE
/profile/members/view leads to an error

### ISSUE THREAD

**Issue by rallek** [zikula/core#3350]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30
|language            | de default

### Expected behavior
no error, a users list is expected

### Actual behavior
let a user open this link ``/profile/members/view`` in his users area leads to following error
````
Stack Trace
in lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php at line 342   -
        }
        // @todo replace with ProfileInterface usage
        $userDisplayName = \ModUtil::apiFunc($profileModule, 'user', 'getUserDisplayName', ['uid' => $user->getUid()]);
        if (empty($userDisplayName)) {
            $userDisplayName = $user->getUname();
        }
Logs   -
Stack Trace (Plain Text)   -
[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getUid() on a non-object
    at n/a
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.5/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php line 34
````

**Comment by rallek** [comment]
ups. Is this an profile error?

**Comment by Guite** [comment]
Yes. Please resubmit it at https://github.com/zikula-modules/Profile/issues/

**Comment by Guite** [comment]
Sorry. This is indeed a core issue.

**Comment by craigh** [comment]
I cannot solve this without more information.

My guess is that that uid is not passed correctly as a method argument.

**Comment by Guite** [comment]
This is fixed now.
