### ISSUE TITLE
Permission check for guests does not work

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3352]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior
If I set permission for guests like
```
Unregistered | MUEternizerModule:: | .* | Edit access
```
I should get access to edit in this module as guest.

### Actual behavior
I get this error message:
```
 An exception has been thrown during the rendering of a template ("Invalid arguments array received") 
```
```
        {
            if ((!isset($args['uid']) && !is_numeric($args['uid'])) ||
                (!isset($args['gid']) && !is_numeric($args['gid']))) {
                throw new \InvalidArgumentException(__('Invalid arguments array received'));
            }
            // Security check

```
### Steps to reproduce

Set a permission for any module like above and try to get access as guest.
The reason is, that there is no valid value for $args['uid'], if I'm a guest.
If I take a code to show the actual user Id per Logutil I get an empty return. So the permission check fails.

**Comment by craigh** [comment]
@Portugao what file/class is the code above from?

**Comment by Guite** [comment]
@craigh Groups UserApi

**Comment by Guite** [comment]
method `isgroupmember`

**Comment by Guite** [comment]
@Portugao I am going to fix this in the generator.

**Comment by Portugao** [comment]
You think it's a MOST issue? I'm not sure...

**Comment by Guite** [comment]
it is; we just discussed it in detail

**Comment by Portugao** [comment]
Ok?

**Comment by Portugao** [comment]
Yes it is! I tried formicula. I'm surprised.

**Comment by Guite** [comment]
The fix is here: https://github.com/Guite/MostGenerator/commit/fdbd25541d8ae1f0b0fa6efaed4fbf25dd139fea

**Comment by Portugao** [comment]
Thx, Axel.
