### ISSUE TITLE
Bundle meta data not updated

### ISSUE THREAD

**Issue by Guite** [zikula/core#3358]
### Expected behavior
Current capabilities are reflected in the database.

### Actual behavior
Record for groups module still contained old `admin` and `user` routes.

### Steps to reproduce
1. Update from 1.4.4 to latest core.
2. In the admin panel click on the groups module.
3. You end up in the user view instead of the admin page.

**Comment by rallek** [comment]
same as #3341

**Comment by craigh** [comment]
you have to go to the extensions list page to update bundle metadata

**Comment by craigh** [comment]
this could perhaps be added to the core update ;-)

**Comment by Guite** [comment]
> this could perhaps be added to the core update ;-)

If it is not much work this would be the best solution.
Otherwise including an additional step to the upgrade instructions (like *Visit the extensions list page to update the system modules metadata") would also be enough.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/f135c7bd4ee6fad3c1cfa0466afe0eecab8bfa2c/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AbstractController.php#L112-L113

this _should_ have synced this information already 🙁

**Comment by craigh** [comment]
oh - I just figured that it isn't called in the upgrader after v1.4.4

**Comment by Guite** [comment]
Thanks!
