### ISSUE TITLE
Long Names for Block Positions Break Layout

### ISSUE THREAD

**Issue by shefik** [zikula/core#3359]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

The table should be able to scroll horizontally, within the theme container.

### Actual behavior

The table width breaks the layout, id there are long names for block positions

### Steps to reproduce

Create a block position with a long name, such as `zikulaexamplemodule_this_is_just_an_example`

**Comment by Guite** [comment]
In addition to #3360 maybe a `|truncate()` filter would make sense.

**Comment by craigh** [comment]
one or the other, but not both.
