### ISSUE TITLE
Better script for viewing images

### ISSUE THREAD

**Issue by Guite** [zikula/core#3362]
The currently included media-lightbox script from https://github.com/bootstrap-plus/bootstrap-media-lightbox/ has issues with different browsers.
Thus, I propose to replace it by something more matured, like:

https://github.com/lokesh/lightbox2/
http://lokeshdhakar.com/projects/lightbox2/

**Comment by rallek** [comment]
+1

**Comment by Portugao** [comment]
👍

**Comment by craigh** [comment]
BC concerns?

**Comment by Guite** [comment]
Not sure. The script to bei replaced was introduced in 1.4 iirc.

**Comment by rallek** [comment]
Both in parallel results in problems on my site.

**Comment by rallek** [comment]
I would love to see this in 1.4.6. Is there anything I can help?

**Comment by Guite** [comment]
Atm this is blocked by missing composer support, see https://github.com/lokesh/lightbox2/issues/467

**Comment by rallek** [comment]
whats about: https://github.com/dimsemenov/Magnific-Popup?

**Comment by Guite** [comment]
See #3435 

The bootstrap-media-lightbox should be removed in the master branch after this has been merged to both `1.4` and `master`.

**Comment by craigh** [comment]
So the plan is that both are avaialable until 2.0 yes?

**Comment by Guite** [comment]
This is the easiest way I guess.

**Comment by craigh** [comment]
well it's the **_only_** way to maintain BC within the current branch
