### ISSUE TITLE
Upgrade to Twig 2.0

### ISSUE THREAD

**Issue by craigh** [zikula/core#3370]
https://github.com/twigphp/Twig/blob/2.x/CHANGELOG#L5

**Comment by Guite** [comment]
> dropped support for PHP 5.x

**Comment by craigh** [comment]
ooh - that might not work then..

**Comment by craigh** [comment]
nice!

**Comment by Guite** [comment]
@craigh seems they waited for us :smile: 
https://symfony.com/blog/new-in-twig-namespaced-classes
