### ISSUE TITLE
remove *.class parameters

### ISSUE THREAD

**Issue by craigh** [zikula/core#3371]
apparently at one time symfony considered it "best practice" to parameterize all class assignments. This apparently creates unnecessary overhead and degrades performance for no reason.

https://github.com/symfony/symfony/issues/11881

We are inconsistent in our definitions - sometimes using parameters and sometimes not.

So - we should eliminate the parameters (`*.class`) and use the classnames directly in the definition.

Using these class parameters , we override these **symfony** services that I know of:
  1. [EventDispatcher](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Resources/config/services.yml#L2)
  2. [ControllerResolver](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Resources/config/services.yml#L3)
  3. [Sessions](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Resources/config/session.yml#L2-L4)
  4. [Translator](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Resources/config/translation.yml#L2) (or [maybe not?](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Resources/config/translation.yml#L10))

There may be additional definitions I am unaware of. We would need to thoroughly check.

In Symfony 3 these no longer work (although I cannot find documentation of this in the upgrading documents...) We need to explicitly define the service, thus overriding the class or [decorate](http://symfony.com/doc/current/service_container/service_decoration.html) them instead.

**Comment by Guite** [comment]
> eliminate the parameters (*.class)

nice :+1: I dislike these anyway :smile:

**Comment by craigh** [comment]
fixed in #3374
