### ISSUE TITLE
Routes generated in JavaScript files always use English

### ISSUE THREAD

**Issue by Guite** [zikula/core#3376]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5
| PHP Version       | 7

### Expected behavior
Generated routes always consider translated routes.

### Actual behavior
Calling `Routing.generate()` in JavaScript always generate the original (English) routes. This results in a 404 error because the system expects the translated route.

### Steps to reproduce

* Translate a module including the routes file (e.g. `routes.de.po`).
* Call `Routing.generate('myroute')` in a JavaScript file
* See that the generate route is not the translated one.

**Comment by craigh** [comment]
refs and maybe dup #1985

**Comment by craigh** [comment]
will you please retest this after my recent locale changes?

**Comment by Guite** [comment]
Yes I can do this next week.

**Comment by Guite** [comment]
Can you please point me to the changes that are needed to be applied to a 1.4.5 installation in order to test this?

**Comment by craigh** [comment]
it wasn't one small change. there were dozens of changes. basically, you need to update to 1.4.6

**Comment by Guite** [comment]
It is fixed :smile:
