### ISSUE TITLE
Upgrade to Symfony 5.x

### ISSUE THREAD

**Issue by craigh** [zikula/core#3377]
Upgrade to Symfony 4.x

**Comment by Guite** [comment]
Note Symfony 3.4 has the longest support at the moment: https://symfony.com/roadmap

**Comment by craigh** [comment]
found this by accident. thought it might be useful.

https://codereviewvideos.com/course/upgrade-symfony-3-to-symfony-4

**Comment by Guite** [comment]
Note: refactor deprecated usage of `ContainerAwareCommand` (GeneratorBundle + Core)

**Comment by craigh** [comment]
should consider going directly to Symfony 5 since it will be out in a few weeks

**Comment by Guite** [comment]
Fixed by #4018
