### ISSUE TITLE
isBundle('ZikulaPageLockModule') returns always true

### ISSUE THREAD

**Issue by Guite** [zikula/core#3379]
### Expected behavior
The method should return only `true` if PageLock is installed.

### Actual behavior
`$this->kernel->isBundle('ZikulaPageLockModule')` returns `true` even if PageLock is not installed.

### Additional remarks
This is related to `/app/ZikulaKernel.php`: there PageLock is contained in the `$coreModules` array which is added to the container in the `registerCoreModules` method.
If I remove PageLock from this array `isBundle` returns `false`.

**Comment by Guite** [comment]
See https://github.com/zikula/core/issues/3283#issuecomment-271797176

**Comment by craigh** [comment]
can't we just remove PageLock from the CoreModules list?

**Comment by Guite** [comment]
This is what I've done at the site I am currently working on.

**Comment by craigh** [comment]
hopefully this solution works properly.
