### ISSUE TITLE
LastLogin - Wrong time is being stored

### ISSUE THREAD

**Issue by DirkThiele** [zikula/core#3383]
| Zikula Version    | 1.3.x
| Zikula Version    | 1.4.x
| PHP Version       | 5.x

The time information of the LastLogin field (user table) is set 1 hour behind.

Changing time zone settings (Admin panel or .htacces file) does not help.

**Comment by Guite** [comment]
Please provide the following additional information:

- time zone the server uses
- `date.timezone` set in the `php.ini` file

**Comment by craigh** [comment]
> | Zikula Version | 1.3.x
| Zikula Version | 1.4.x
| PHP Version | 5.x

also this makes no sense. please supply the proper information

**Comment by DirkThiele** [comment]
| Zikula Version | 1.3.11
| Zikula Version | 1.4.5
| PHP Version | 5.6.29-nmm1

I am not using a php.ini file for configuration.
I have set date.timezone in the .htacces file as follows:
**php_value date.timezone "Europe/Berlin"**

In the Zikula Administration (Localisation settings) is mentioned, that the Server is set to "CET".

PHP-Configuration (General settings) says: "Europe/Berlin"

**Comment by craigh** [comment]
you were correct that there were mistakes in the storage of the lastlogin datetime. This is corrected now and is seen below:

![screen shot 2017-04-03 at 7 00 27 pm](https://cloud.githubusercontent.com/assets/350048/24635160/dbea773a-189f-11e7-84ac-d2b89ecc8a34.png)

please note that the lastlogin (and other datetimes in the User object) are stored in UTC so the time will appear to be different than your own local time or that of the server. You must format the time (as shown above) to your timezone.

**Comment by Guite** [comment]
@craigh is this `utcdatetimetype` maybe something for `lib/Zikula/Doctrine`? I wonder why Doctrine isn't offering this by default to prevent problems with timezones.

**Comment by craigh** [comment]
sure - go ahead and move it.
