### ISSUE TITLE
Drop messaging support

### ISSUE THREAD

**Issue by craigh** [zikula/core#3384]
in researching #3322 I see no real reason to support such an interface. While profile modules are provided with a couple Core twig filters to link to a user profile, there is no such provision for a messaging module - even in the legacy smarty plugins.

In a short conversation with @shefik and @rallek this seems to be a supported decision. I would like further input before making a decision. @cmfcmf @Guite @Kaik 

The https://github.com/zikula-modules/InterCom InterCom module is the only _reasonably_ current messaging module and it has no apparent Core connection

**Comment by craigh** [comment]
I found this is 1.3.x

    {if $msgmodule}
    {modurl modname=$msgmodule type='user' func="inbox" assign="messageslink"}
    <p>{if $messages.unread eq 0}{gt text="You have no new messages." domain='zikula'}{else}{gt text='You have <a href="%1$s">%2$s</a> new message.' plural='You have <a href="%1$s">%2$s</a> new messages.' count=$messages.unread tag1=$messageslink tag2=$messages.unread domain='zikula'}{/if}</p>
    {/if}

**Comment by craigh** [comment]
AH - so the current Profile module has some dependence on the messaging module which I did not detect earlier.

expectations to be able to fetch `getmessagecount` (probably all, or only unread),  a link to the main **inbox** and the link to send a new message to the displayed user (by uid)

**Comment by craigh** [comment]
now I am reconsidering...

**Comment by Guite** [comment]
There are use cases for this. For example Dizkus (or other modules) could want to add a "send message to this user" link without having a hardcoded dependency to InterCom.
