### ISSUE TITLE
Implement Composer Merge plugin

### ISSUE THREAD

**Issue by craigh** [zikula/core#3388]
https://github.com/wikimedia/composer-merge-plugin

@cmfcmf @Guite 

this could be an answer to dynamically including the `composer.json` files from included bundles/modules/themes.

e.g.

            "include": [
                "composer.local.json",
                "system/*/composer.json"
                "modules/*/composer.json"
                "themes/*/composer.json"
            ],

**Comment by craigh** [comment]
another idea would be to fire an event in the `getBundles()` method of the kernel (is the event dispatcher available then?) to get additional bundles that must be included in the container.

**Comment by craigh** [comment]
since the container is not available at that point, I'm guessing the event dispatcher is not. Another solution would be to add "bundle dependencies" to the composer "extra" field. Parse that and add the dependencies to the kernel.

**Comment by craigh** [comment]
Drupal related issues
 - https://www.drupal.org/node/2444459
 - https://www.drupal.org/node/2609568
 - https://github.com/paul-m/drupal-merge-plugin
 - https://bojanz.wordpress.com/2015/09/18/d8-composer-definitive-intro/
 - https://glamanate.com/blog/managing-your-drupal-project-composer
 - http://drupal.stackexchange.com/questions/203525/managing-module-library-dependencies-with-composer

**Comment by Guite** [comment]
Is this about automatically including vendors required in modules/themes?

**Comment by craigh** [comment]
yes.

it could solve a great many problems for us in terms of vendor dependencies, but it could also solve other problems with module dependencies and even allow us to further modularize the core and build it simply with composer. 

it also raises as many questions as it solves. Some that I can think of: this will require running `composer update` on module install/upgrade/remove. this is a **very** long process and not easily done in a browser. Is this possible? Is there a way to avoid it (for example if the module has no unresolved dependencies). Will we have to ship composer with zikula then? (seems so).

**Comment by Guite** [comment]
Possibly related:
https://github.com/dflydev/dflydev-embedded-composer
https://github.com/shadiakiki1986/composer-wrapper

**Comment by craigh** [comment]
this could also allow quickly customized downloads with preconfigured modules installed based on a generated composer.json file. Could easily lead to several options for a "CMS" package for example.

**Comment by cmfcmf** [comment]
This was also related: https://github.com/zikula/core/issues/909#issuecomment-148917664
PageKit is already using Composer to install dependencies on the fly, IIRC.

**Comment by Guite** [comment]
After having read a bit about this topic I think we need to see two concerns separately:

1. Initial composer execution (e.g. by developers or the CI server): this is where this issue and the merge plugin are basically about. Interesting for creating customised downloads and distributions as @craigh pointed out above.
2. PHP-driven composer execution during runtime: this is required for on-demand installation of additional modules.

**Comment by Guite** [comment]
First part is ready in #3437 
Second part involves some other things which are collected in #3438

**Comment by Guite** [comment]
But after the first part is merged this issue (#3388) can be closed.
