### ISSUE TITLE
Zikula 1.3.12 Nach Installation bei Strato kein Login mehr möglich

### ISSUE THREAD

**Issue by trichers** [zikula/core#3390]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.12
| PHP Version       | 5.6.27

### Actual behavior
Ich habe eine neue Zikula Installation (1.3.12, PHP 5.6 MySQL 5.6.35) bei Strato eingerichtet. Nach der Installation erscheint in der Admin-Obfläche folgende Fehlermeldung:

WARN (4): E_WARNING: array_key_exists() expects parameter 2 to be array, string given in Admin.php Zeile 680
WARN (4): E_WARNING: array_key_exists() expects parameter 2 to be array, string given in Admin.php Zeile 680

Will ich einen Benutzer anlegen, der Vorgang läuft wie bisher, aber der Benutzer wird nicht angelegt.
Logge ich mich aus, kann ich mich nicht mehr einloggen.

Bisherige Lösungsversuche:
Error-Logfiles gesichtet - keine Einträge
Mit Strato-Support über eine Stunde nach Fehler gesucht, aber sind nicht weiter gekommen.

Wer hat eine Anhnung woran das liegen kann.
Tests bei anderen Providern (1und1 und Hosteurope) haben keine dieser Probleme ergeben.

Das Phänomen habe ich bei zwei Kunden, die bei Strato einen Account haben.

**Comment by Portugao** [comment]
Are you able to give more informations with dev mode enabled?

**Comment by Guite** [comment]
Closed due to lack of response.
