### ISSUE TITLE
[Menu] Add MenuModule translation for dynamic menus

### ISSUE THREAD

**Issue by craigh** [zikula/core#3397]
https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Menu/Translation.md

probably will require Gedmo/Translatable

**Comment by rallek** [comment]
A simple way would be a kind of locale usage. Similar to e.g. the sitename. That would be consistent to the complete core.

For each language installed an own title filed. If a language will be added later the string of the first language will be used until it is translated real.

**Comment by Guite** [comment]
Closing as won't fix as dynamic menus are removed.
