### ISSUE TITLE
[Blocks] Add Translatable Block titles / Review concept of block permissions

### ISSUE THREAD

**Issue by craigh** [zikula/core#3398]
Add Translatable Block titles

probably will require Gedmo/Translatable

**Comment by Guite** [comment]
This should include a new convention for block permission instances. Currently often the block title is used, but maybe the ID would be more appropriate then.

**Comment by Guite** [comment]
> This should include a new convention for block permission instances.

As part of this the concept of how block permissions are usually done should be reviewed as a whole.

The blocks module declares these generic permission rules:

- `"ZikulaBlocksModule::": "Block key:Block title:Block ID"`
- `"ZikulaBlocksModule::position": "Position name::Position ID"`

1. Check if these are actually used / checked for.
2. Maybe many block-specific permission schemes can be dropped entirely. So there would be no need for every block having its own permission component etc.

**Comment by Guite** [comment]
Closing as won't fix as the block system will be removed.
