### ISSUE TITLE
TemplateNameExposeListener and Bazinga Js Translator in dev mode.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3400]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5+
| PHP Version       | 5.x

### Expected behavior
No javascript errors in dev mode.

### Actual behavior
``` Uncaught SyntaxError: Unexpected token } zikula_javascript:5 ```

### Steps to reproduce
Load any page in dev mode and check errors in console.

### Reason 
TemplateNameExposeListener comments are breaking generated javascript 
```
<!-- BazingaJsTranslationBundle::getTranslations.js.twig -->(function (Translator) {
    Translator.fallback      = 'en';
    Translator.defaultDomain = 'zikula_javascript';
    // en
})(Translator);
<!-- /BazingaJsTranslationBundle::getTranslations.js.twig -->
```

**Comment by craigh** [comment]
works for me.

![screen shot 2017-01-24 at 5 13 23 pm](https://cloud.githubusercontent.com/assets/350048/22269228/81f220d4-e258-11e6-9340-d9bbd50e7b43.png)
