### ISSUE TITLE
Account settings icon not consistent.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3403]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.x

### Expected behavior
Same icon for account settings in core modules

### Actual behavior
ZikulaUsersModule uses wrench while ZikulaZAuthModule uses cubes

### Steps to reproduce
https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Container/LinkContainer.php#L165
https://github.com/zikula/core/blob/1.4/src/system/ZAuthModule/Container/LinkContainer.php#L152

I can fix it let me know which icon will stay btw both looks awful :)

**Comment by craigh** [comment]
don't care.

**Comment by Guite** [comment]
How about user, user-o, user-circle or user-circle-o?

**Comment by Kaik** [comment]
@Guite user-circle or user-circle-o are nice ones.
Btw I just realized that text is also different in ZikulaUsersModule is "Account Settings" while in ZikulaZAuthModule is "Menu". I think personally Account Settings sounds old to me while Menu is not precise - maybe something like User menu or Account menu? I will change it to whatever you will agree.

**Comment by craigh** [comment]
choose what you like and make a PR

**Comment by Kaik** [comment]
Ok then I will do research (my ux sister ;) will think about it and will do PR's tomorrow.
