### ISSUE TITLE
Add template option for moduleLinks

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3405]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.x

https://github.com/zikula/core/blob/1.4/src/system/ExtensionsModule/Controller/ExtensionsInterfaceController.php#L144

There should be a possibility to use different template same as here https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Twig/Extension/PagerExtension.php#L92

I will do PR if you have no problem with it.

**Comment by craigh** [comment]
why not just a standard template override?

**Comment by Kaik** [comment]
Standard theme overrides it globally for every module while this twig function could be used in cases when you want to display different links type in your module in a different template - similar to pager.
