### ISSUE TITLE
Update modernizr

### ISSUE THREAD

**Issue by Guite** [zikula/core#3406]
The modernizr versions is quite old. The script should be updated.

The latest version (as of today) is **3.3.1**.

**Comment by craigh** [comment]
available as a component: https://github.com/components/modernizr

**Comment by Guite** [comment]
Nice! We should embed this using composer then. But removing the old version from `/javascript` would be a BC break, wouldn't it?

**Comment by Guite** [comment]
OTOH modernizr is not part of 1.3.x.

**Comment by Guite** [comment]
> available as a component: https://github.com/components/modernizr

Seems obsolete.

**Comment by craigh** [comment]
do we want to maintain Modernizr into Core-2.0?
