### ISSUE TITLE
upgrade from 1.4.4 to 1.46 issue with page lock

### ISSUE THREAD

**Issue by rallek** [zikula/core#3424]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci build 87
| PHP Version       | 5.5

### Actual behavior
After upgrade the page lock is not installed. I am not shure what was the situation before upgrade. In most cases I activate it. I can have a look in my backup if needed.

Nevertheless after trying to install I do get the following failure report:
````
[1] InvalidArgumentException: The "modules/PageLockModule" directory does not exist.
    at n/a
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php line 656

    at Symfony\Component\Finder\Finder->in(array('modules/PageLockModule'))
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/lib/Zikula/Bundle/CoreBundle/Bundle/Scanner.php line 34

    at Zikula\Bundle\CoreBundle\Bundle\Scanner->scan(array('modules/PageLockModule'), '1')
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/system/ExtensionsModule/Helper/ExtensionHelper.php line 277

    at Zikula\ExtensionsModule\Helper\ExtensionHelper->forceLoadExtension(object(ExtensionEntity))
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/system/ExtensionsModule/Helper/ExtensionHelper.php line 79

    at Zikula\ExtensionsModule\Helper\ExtensionHelper->install(object(ExtensionEntity))
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/system/ExtensionsModule/Controller/ModuleController.php line 330

    at Zikula\ExtensionsModule\Controller\ModuleController->installAction(object(Zikula_Request_Http), object(ExtensionEntity))
        in  line 

    at call_user_func_array(array(object(ModuleController), 'installAction'), array(object(Zikula_Request_Http), object(ExtensionEntity)))
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /home/www/www.oldtimer-ig-osnabrueck.de/test/Zikula_Core-1.4.6/index.php line 23
````
The PageLockModule is still in System folder.

**Comment by craigh** [comment]
was Pagelock installed before upgrade or not?

**Comment by rallek** [comment]
Have to look into database backup this evening.

**Comment by rallek** [comment]
Page Lock was not installed before upgrade!

I now did the upgrade again with current ci build 93 with the same issue. This time I did not get an error for upgrading modules but for upgrading from 1.4.5 to 1.4.6.

I now will activate Page Lock before my next try of upgrading and report back what happens.

**Comment by rallek** [comment]
Situation before upgrading now (I installed Page Lock)
![grafik](https://cloud.githubusercontent.com/assets/935250/22479102/d6514c74-e7ec-11e6-80b5-f26ff75210d0.png)

Situation after upgrade (several modules are now inactive). But see also #3428 
![grafik](https://cloud.githubusercontent.com/assets/935250/22479281/7641a6b6-e7ed-11e6-82f0-451317f76afc.png)

**Comment by rallek** [comment]
But see my tree. Will page lock work propperly? I thought it should be moved into modules. Is this the error of #3428?
![grafik](https://cloud.githubusercontent.com/assets/935250/22479436/036bb11c-e7ee-11e6-9a32-3b95521ff353.png)

**Comment by rallek** [comment]
If I upgrade without german language pack the page lock issue is still there

**Comment by craigh** [comment]
so...

 - the page lock module was NOT installed before the core upgrade and then it was NOT installed after the upgrade. this is of course the expected behavior.
 - installation following the upgrade fails and leads to the trace route posted in the OP.
 - the PageLock module WAS installed previous to upgrade and was ALSO installed post-upgrade. This behavior is also the expected behavior.

Do I have this right? please confirm.

for the record, the PageLock module is _supposed_ to be in the `/system` directory still.

**Comment by rallek** [comment]
Yes, you are right. Only if the page lock module was not installed I do have the posted error message.

I was not shure if the page lock module should be moved into modules. But as you explained now, it is correct in system.

**Comment by rallek** [comment]
Fix confirmed. Even with not installed Page Lock I can install Page Lock after upgrade.
