### ISSUE TITLE
broken Link in Upgrader instruction

### ISSUE THREAD

**Issue by rallek** [zikula/core#3431]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci.build98
| PHP Version       | 5.5.30

### Expected behavior
The link should work

### Actual behavior
A small missue:

During upgrade there is an instruction to look at the link ``%inst%``

I found this string in zikula.template.po:
````
You are seeing this message because Zikula requires upgrade. You can upgrade Zikula by clicking
                    on the upgrade button, but before doing so please read the %inst%. Further information can be found in the %docs%.
````
The link behind %inst% is pointing to: ``http://146.oldtimer-ig-osnabrueck.de/installdoc/UPGRADE-1.4.md``. Clicking on that I do not get the instruction. I do get 
````
The file you requested (UPGRADE-1.4.md) could not be found.
````

UPGRADE-1.4.md is available in Zikula root.

**Comment by rallek** [comment]
Link to installation guide is also not working. The link is pointing to: ``http://146.oldtimer-ig-osnabrueck.de/installdoc``

**Comment by craigh** [comment]
is this a download from the ci server or a pull/install from github?

**Comment by rallek** [comment]
I allways use the download from ci (see table on top)

**Comment by craigh** [comment]
are you running the installation in German?

**Comment by rallek** [comment]
yes, I run the upgrade in German. But today I run a new install in english and the links are still broken :-(
