### ISSUE TITLE
non-core modules are deactivated after upgrade

### ISSUE THREAD

**Issue by rallek** [zikula/core#3432]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci.build 98
| PHP Version       | 5.5.30

### Expected behavior
All modules should have the same state after upgrading as before

### Actual behavior
All non-core modules are deactivated after upgrade from 1.4.4 to 1.4.6. Activating is not a problem. So this is just a minor issue. If it is on purpose the hint should be inside the upgrade documentation.

**Comment by craigh** [comment]
Did you have the modules present in the `/modules` directory before reloading and being redirected to `/upgrade`?

**Comment by rallek** [comment]
yes I have.

**Comment by craigh** [comment]
can you please test [these changes](https://github.com/zikula/core/commit/a8937e0c1b661c37103b0565d6df08dc65b913d3) and see if that fixes the problem?

**Comment by Guite** [comment]
> can you please test these changes and see if that fixes the problem?

Wouldn't this activate all modules, including those which were not installed before?

**Comment by craigh** [comment]
no I don't think so.

@rallek, can you please test this?

**Comment by rallek** [comment]
will do this evening

**Comment by rallek** [comment]
Perfect!
