### ISSUE TITLE
fresh installation of 1.4.6 ci.build 105 failed if German language selected

### ISSUE THREAD

**Issue by rallek** [zikula/core#3436]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci.build105
| PHP Version       | 5.5

### Expected behavior
Installation should work like always

### Actual behavior
I do get this error message:

> Warning: DateTime::modify(): Failed to parse time string (- minutes) at position 0 (-): Unexpected character in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/system/UsersModule/Entity/Repository/UserSessionRepository.php on line 80

> Warning: DateTime::modify(): Failed to parse time string (- days) at position 0 (-): Unexpected character in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/system/UsersModule/Entity/Repository/UserSessionRepository.php on line 82

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd024ff5d.session_info' doesn't exist' in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL) #1 /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php(55): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM ses...', Array, Array) #3 /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleTableDeleteUpdateExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array) #4 /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 131

On this server I did my last install with ci.build 74 which worked fine.

**Comment by rallek** [comment]
Have to add: I made the installation with german language. Do I install it in english this error do not occur.

**Comment by rallek** [comment]
Funny: Some strings are translated even if I do the installation in english while german translations files are available. See for example this screen shot:
![grafik](https://cloud.githubusercontent.com/assets/935250/22562309/4543e098-e97c-11e6-98a5-69a570bbee1d.png)

**Comment by rallek** [comment]
No problem if this issue is moved to 1.4.7

**Comment by craigh** [comment]
please attach your translation files

**Comment by rallek** [comment]
Might be I did a mistake. Do I need anything in locale? There I did nothing.

[translations.zip](https://github.com/zikula/core/files/748844/translations.zip)

**Comment by craigh** [comment]
when did this error occur?

**Comment by rallek** [comment]
When I have to set the admin name and password

**Comment by craigh** [comment]
in the core installer?

**Comment by rallek** [comment]
yes. A fresh one. Build 105.

**Comment by craigh** [comment]
I think this is not truly related to the locale choice. The error is a result of a "random" choice to perform "garbage collection" on the session table.

I bet you could try with the same build (in German) and it would work the second time.

could you?

**Comment by rallek** [comment]
I acn try.

**Comment by craigh** [comment]
or you can wait for build 106

**Comment by rallek** [comment]
tried with success! I used build 106.

**Comment by craigh** [comment]
👍

**Comment by rallek** [comment]
1.4.6 becomes really good!
