### ISSUE TITLE
Verifying new account leads to an error

### ISSUE THREAD

**Issue by rallek** [zikula/core#3440]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci 107
| PHP Version       | 5.5

### Expected behavior
A new user is able to verify his new accout

### Actual behavior
after using the verify URL the new user do get this error message
````
[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Method Doctrine\ORM\Query\Expr\Comparison::__toString() must not throw an exception
    at n/a
        in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Expr/Composite.php line 0

````
The stack trace is that short

**Comment by craigh** [comment]
how do I get here?

**Comment by rallek** [comment]
http://2017.pggo.de
wait a second I will switch the site to English

**Comment by craigh** [comment]
no - I mean how do I recreate this error?

**Comment by rallek** [comment]
go there, create an account and try to verify :-)

**Comment by craigh** [comment]
disable legal and try it again

**Comment by rallek** [comment]
makes no difference. I deleted your user. You may also want to try it again

**Comment by craigh** [comment]
I am having difficulty reproducing this error.

**Comment by rallek** [comment]
How can I help?

**Comment by craigh** [comment]
I cannot reproduce this error at all. I even tried with @rallek 's translation and theme.

**Comment by craigh** [comment]
@Guite can you try this locally please?

**Comment by Guite** [comment]
@rallek can you check if https://github.com/zikula/core/commit/4ede24f4510f78b9f79262a5b49a56a33ba57d6e fixes this problem?

**Comment by rallek** [comment]
while I want to delete my testuser I do get this error:
````
[1] Symfony\Component\Debug\Exception\FatalErrorException: Parse Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)
    at n/a
        in /www/htdocs/w0158c4d/Zikula_Core-1.4.6/system/ZAuthModule/Entity/Repository/UserVerificationRepository.php line 63
````
This is exactly the changed file

**Comment by Guite** [comment]
https://github.com/zikula/core/commit/69fd1ef25920e27692dac824dc5502cad1511325

**Comment by rallek** [comment]
fixed! Great job!

**Comment by craigh** [comment]
@Guite > @craigh
