### ISSUE TITLE
translation of site policies during registration is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#3441]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci 107
| PHP Version       | 5.5

### Expected behavior
the chapter ``site policies`` should be translated if a new user want to register a new account

### Actual behavior

![grafik](https://cloud.githubusercontent.com/assets/935250/22618981/a1d382cc-eaea-11e6-9165-ae358aeb192c.png)

I expect these translations are comming from the legal-module
see also https://github.com/zikula-modules/Legal/issues/66

**Comment by Guite** [comment]
@rallek can you please test whether https://github.com/zikula-modules/Legal/pull/67/files fixes this problem?

**Comment by rallek** [comment]
it is not fixing the problem. 

I exchanged the file ``acceptedPolicies.html.twig``

**Comment by Guite** [comment]
Interestingly some strings are translated while others are not - also if the translation domain is explicitly set.
I've no further idea at the moment though.
Maybe this is the same as https://github.com/zikula-modules/Legal/issues/66

**Comment by craigh** [comment]
> Maybe this is the same as zikula-modules/Legal#66

pretty sure that's why he linked them...

**Comment by craigh** [comment]
@rallek please explain to me how to reproduce this.

**Comment by craigh** [comment]
![screen shot 2017-05-13 at 8 21 22 am](https://cloud.githubusercontent.com/assets/350048/26025574/0b1583c8-37b9-11e7-9bd4-d4183fdff664.png)
![screen shot 2017-05-13 at 7 45 17 am](https://cloud.githubusercontent.com/assets/350048/26025575/0c6320c8-37b9-11e7-9a75-2b728c950132.png)
