### ISSUE TITLE
QA testing for release of 1.4.6-rc1 build #111

### ISSUE THREAD

**Issue by craigh** [zikula/core#3446]
Please test build [#111](http://ci.zikula.org/job/Zikula_Core-1.4.6/111/) and decide if it should become the next official release.
__Anyone may participate in the testing process.__

Testing guidelines can be found in [Release Testing Guideline](https://github.com/zikula/core/wiki/Release-Testing-Guidelines)

**_Altered Quality Assurance Cycle_**
Two "-1" votes (with reason) will cause the build to fail. If this build fails, __votes cannot be transferred__ to the new release candidate, __testing must resume from the beginning__.
If the negative threshold is not reached before 10 February 2017, then the build passes automatically.

Positive votes are welcome and encouraged. ✅ 

Please **do not** report bugs in this ticket, only register your approval or disapproval. You must give a reason and reference if appropriate (e.g. link to a ticket) for negative votes.

**Please report issues in a separate ticket.**

Notes, References, and/or Special Instructions
---------------------------------------------------------

Do not vote negatively if you find non-release blocking bugs.  Minor and major bugs may be scheduled in a future version.

**Comment by craigh** [comment]
@rallek @Kaik @gfr @rmburkhead @nmpetkov @cmfcmf @jusuff @matheo @tfotis @shefik @phaidon @espaan @marcpare4 @trichers @ccandreva @rojblake @paustian @MrMontesa @portugao

**Comment by rallek** [comment]
I tested intensively the last weeks the upgrade process from 1.4.4 to 1.4.6. My focus have been the language issues. Tons of issues came up. And tons of issues are solved mainly by Axel and even more Craigh. Thanks a lot for your work!

I would say this is the best release since years! 

I vote +1 and can't wait for the next release where I will set the focus in testing the new MenuModule ;-)

**Comment by Kaik** [comment]
:+1:

**Comment by Sozialarchiv** [comment]
With php 7.* I could not install it. But I think this is a known issue https://github.com/zikula/core/issues/2766.

The installer looks really awesome. 

I found some smaller design design issues but nothing really important.

+1

**Comment by craigh** [comment]
@Sozialarchiv - Hi Fabian - thanks for testing! Core-1.4.x is not compatible with PHP7 :disappointed:  because of vendor issues (as you pointed out). Core-2.0 will be! Glad you like the installer. thanks for the positive feedback!

**Comment by ccandreva** [comment]
If you have access to php.ini you can try adding "& ~E_DEPRECATED" to error_reporting, ie:
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`

**Comment by rallek** [comment]
might be there is one issue: https://github.com/zikula/core/issues/3450

can someone else have a look?

**Comment by phaidon** [comment]
@craigh you are right. wrong account  ;)

**Comment by craigh** [comment]
@phaidon I thought so but wasn't sure... ;-)

**Comment by rallek** [comment]
https://github.com/zikula-modules/Content/issues/181
This issue is fresh with 1.4.6. I do not know if this is core related or Content alone.

**Comment by craigh** [comment]
failing due to #3450

**Comment by craigh** [comment]
those that voted in favor of RC1 please consider testing RC2 and voting again at https://github.com/zikula/core/issues/3456. Votes cannot be carried from one build to the next. thank you!
