### ISSUE TITLE
Admin top menu has a margin if the sidebar is visible

### ISSUE THREAD

**Issue by Sozialarchiv** [zikula/core#3449]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.x

### Expected behavior

Top menu has no margin

### Actual behavior

Top menu has a margin

### Steps to reproduce

<img width="1206" alt="admin-menu" src="https://cloud.githubusercontent.com/assets/17063042/22663229/249f8c9c-ecac-11e6-913a-5e46efa3a980.png">

**Comment by craigh** [comment]
Any ideas how to fix that?

**Comment by phaidon** [comment]
The reason is 

`body {padding-top: 70px;}`
https://github.com/zikula/core/blob/ee5246623d15911a39fff3679c25556b464bfdf3/src/themes/BootstrapTheme/Resources/public/css/style.css#L2

I think the 70px has to be placed in another element.

**Comment by craigh** [comment]
Open to PRs 😃

**Comment by Guite** [comment]
It's not really an easy pick, because the nav bar is fixed. Refs http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html

**Comment by craigh** [comment]
@paustian this might be a good one to tackle

**Comment by paustian** [comment]
Bug fixed. It was the addition of this code to the style.css file of the bootstrap theme. It took a while to track down, but I tracked it down.
`body {
    padding-top: 70px;
}
`
