### ISSUE TITLE
hooks are making problems under 1.4.6

### ISSUE THREAD

**Issue by rallek** [zikula/core#3450]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci 111
| PHP Version       | 5.5

### Expected behavior
Scribite hook shoud be applicable to any module

### Actual behavior
after applying the Scribite hook I do get a 550 error:
![grafik](https://cloud.githubusercontent.com/assets/935250/22665735/2280f4d2-ecb6-11e6-8af1-bae2f390812e.png)
Tested with content, a most module and news

### Steps to reproduce
Install a module and scribite and try to apply the hook

**Comment by rallek** [comment]
counter checked on a site with fresh zk1.4.6 plus content plus scribite
No languages and other modules or configuration. Boostrap theme.

**Comment by craigh** [comment]
try disabling asset combination in `custom_parameters.yml`

**Comment by craigh** [comment]
Also try with [1.4.5](http://ci.zikula.org/view/All/job/Zikula_Core-1.4.5/)

**Comment by craigh** [comment]
@Guite can you please look at this today?

**Comment by Guite** [comment]
I still suspect that in 1.4.6 the csrf check now works also for places where it did not correctly work before. Which means that the correct fix would be adding correct tokens to the ajax requests which currently not carry a csrf token.

**Comment by Guite** [comment]
I assume this because of the session refactoring.

**Comment by craigh** [comment]
> I assume this because of the session refactoring.

while new classes were implemented for sessions, their functionality should not have changed (at all). So I would personally not come to that same conclusion without some evidence to point to that issue.

**Comment by craigh** [comment]
@Guite may be right, but I still cannot figure this out.

I've traced that [here](https://github.com/zikula/core/blob/7b1c8fdeaade4cf5e85c0843425351314712e163/src/javascript/jquery_config.js#L30-L30) the value for `document.cooke` is empty and in Core-1.4.5 it is has the expected value. Because my JS-fu is very weak, I cannot figure this out. help!

**Comment by craigh** [comment]
ok - based on some [reading](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)

> To prevent cross-site scripting (XSS) attacks, HTTP-only cookies aren't accessible via JavaScript through the Document.cookie property, the XMLHttpRequest and Request APIs. Set this flag when you don't need your cookies available in JavaScript. In particular, if you use cookies only to define a session, you don't need it in JavaScript and the HttpOnly flag should be set.

I had done this (used HTTP-only cookies) in the refactor. So this would apparently be the problem. now I have to remember how to reverse it.

**Comment by Guite** [comment]
:1st_place_medal:

**Comment by Guite** [comment]
@rallek checked this again and it is working fine now.

**Comment by craigh** [comment]
👍

**Comment by craigh** [comment]
wait - so #3455 isn't because of this fix?

**Comment by craigh** [comment]
oops - that was the other ticket. nm

**Comment by rallek** [comment]
The above shown issue 500 is now also occuring sometimes in Menu module. But I can not reproduce it when and why. Today it is working like it should, yesterday not. As soon as I can reproduce I will open a new ticket with refference to this one.

**Comment by rallek** [comment]
But in content this problem is back on stable 1.4.6

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/Content/commit/e1c0adcb49d657a3fe17971e912141459be4e679 and https://github.com/zikula/core/commit/344033b402f7ad15d8af76684666bc67337544c7
