### ISSUE TITLE
configure method to auto-set _locale param in js routes

### ISSUE THREAD

**Issue by craigh** [zikula/core#3453]
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/84 (basically says try the master branch...)
http://stackoverflow.com/questions/11433166/fosjsroutingbundle-with-locale
http://stackoverflow.com/questions/25842418/symfony-fos-js-routing-and-problems-with-locale

**Comment by Guite** [comment]
This does indeed work (now).

Closing :smile:

**Comment by Guite** [comment]
fyi I tested this thoroughly using a similar example as shown in https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/84 - it is possible to omit the `_locale` argument and the current locale will be used automatically then.
