### ISSUE TITLE
second cookie for ajax?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3454]
refs 
 - https://github.com/zikula/core/commit/9f1b4489cf264605f9c73a0ff8ee85cbc55b2519
 - https://github.com/zikula/core/issues/3450#issuecomment-278561864
 - https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

is there a way to make the session cookie http only and create a second (non http only) cookie that could be used by ajax thus making the session cookie more secure?

**Comment by craigh** [comment]
This is related to https://github.com/zikula/core/issues/3206

**Comment by Guite** [comment]
@craigh as this is a FR: move to 1.5.0 or 2.1.0?

**Comment by craigh** [comment]
https://gist.github.com/Burgov/7300028

**Comment by craigh** [comment]
Files involved:
 - ThemeModule/EventListener/DefaultPageAssetSetterListener.php
 - ThemeModule/EventListener/AddJSConfigListener.php
 - ThemeModule/Resources/views/Engine/JSConfig.html.twig
 - Bundle/CoreBundle/Resources/public/js/jquery_config.js

**Comment by Guite** [comment]
@craigh if you think this is important please move back to 1.5

**Comment by craigh** [comment]
refs `\Zikula\Bundle\HookBundle\Controller\HookController::checkAjaxToken`

**Comment by Guite** [comment]
refs `cookie_httponly` see https://github.com/zikula/core/blob/master/src/app/config/config.yml#L31

**Comment by Guite** [comment]
Fixed by #3895

Other related tasks are covered by #3206 and #3505
