### ISSUE TITLE
QA testing for release of 1.4.6-rc2 build #119

### ISSUE THREAD

**Issue by craigh** [zikula/core#3456]
Please test build [#119](http://ci.zikula.org/job/Zikula_Core-1.4.6/119/) and decide if it should become the next official release.
__Anyone may participate in the testing process.__

Testing guidelines can be found in [Release Testing Guideline](https://github.com/zikula/core/wiki/Release-Testing-Guidelines)

**_Altered Quality Assurance Cycle_**
Two "-1" votes (with reason) will cause the build to fail. If this build fails, __votes cannot be transferred__ to the new release candidate, __testing must resume from the beginning__.
If the negative threshold is not reached before 12 February 2017, then the build passes automatically.

Positive votes are welcome and encouraged. ✅ 

Please **do not** report bugs in this ticket, only register your approval or disapproval. You must give a reason and reference if appropriate (e.g. link to a ticket) for negative votes.

**Please report issues in a separate ticket.**

Notes, References, and/or Special Instructions
---------------------------------------------------------

Do not vote negatively if you find non-release blocking bugs.  Minor and major bugs may be scheduled in a future version.

**Comment by rallek** [comment]
can't find a new issue right now. But I will be creative :-)

I vote with +1

**Comment by craigh** [comment]
released 12 February 2017
