### ISSUE TITLE
Elements Missing from Page During Upgrade

### ISSUE THREAD

**Issue by shefik** [zikula/core#3460]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

Elements should be on the page

### Actual behavior

Elements are missing on the page. See attached screenshot.

<img width="860" alt="missing elements" src="https://cloud.githubusercontent.com/assets/274862/22871645/c9ff2066-f180-11e6-9b59-62f4f0ee8875.png">

### Steps to reproduce

Attempt to upgrade from Zikula 1.4.5 to 1.4.6. Error occurs at `upgrade/ajaxupgrader`.

**Comment by shefik** [comment]
Seems to just be a language translation issue, because the actual functionality still works, without throwing an error.

**Comment by Guite** [comment]
Looks like related to https://github.com/zikula/core/commit/ab48f9d435564f04a43b49b7ef3b24fca9a58028

Do you have a custom translation which has not been updated?

**Comment by shefik** [comment]
I am using a custom English translation file. I did update with the POT file included in 1.4.6. So perhaps there are strings missing the POT file?

**Comment by Guite** [comment]
Note there are more than 1 file to be translated.
`/app/Resources/locale/` for old stuff
`/app/Resources/translations/` for new stuff

The strings are contained in `/app/Resources/translations/zikula.template.po` one (I just checked).

**Comment by shefik** [comment]
Actually, I just tried updating from `/app/Resources/translations/zikula.template.po`, and that seemed to load strings into my existing file. However, perhaps `/app/Resources/locale/zikula.pot` is incomplete?

**Comment by Guite** [comment]
This is how it looks for me:

![screenshot_20170213_101439](https://cloud.githubusercontent.com/assets/277531/22877328/43c2703e-f1d5-11e6-9adf-cfce5a593b36.png)

**Comment by shefik** [comment]
But, are the latest strings missing from `/app/Resources/locale/zikula.pot`?

**Comment by Guite** [comment]
as written above: `/app/Resources/locale/` is only for old stuff

**Comment by shefik** [comment]
Okay, so does that mean that I should only be updating from the template file at `/app/Resources/translations/zikula.template.po`?

**Comment by rallek** [comment]
I am translating all files in ``app/Resources/translations``. But you do not have to translate the ``foo.template.po``. Your result should be ``foo.en.po`` or in my case ``foo.de.po``

Be carefull with the ``routes.translate.po``. I currently only copy this one to ``routes.de.po`` (in your case ``routes.en.po``). Routing is very sensible.

And some strings are in the themes and modules.

**Comment by shefik** [comment]
@rallek My issue is that I already have an existing `zikula.en.po` file. When Zikula has new releases, where do I obtain updates from? Apparently, I can't use the POT file since it's legacy now, so the only file that contains the updated strings is `zikula.template.po`.

**Comment by rallek** [comment]
That is the right way. I also do an update from these files after each upgrade/test of my site.

POT files I do not care about anymore.

**Comment by Guite** [comment]
Is it possible to update an existing po file from another po file in poedit?

**Comment by rallek** [comment]
yes. In my windows version you have to switch in the open dialog from pot to po.

**Comment by nmpetkov** [comment]
Recently I olso learned in depth Poedit UI, thanks to @rallek for the help few days ago. Poedit have in the menu
Update from POT file, but in fact right is "POT or PO", as shown in the pictures below.

It is annoying missing translations to leave empty, opposite to old Zikula versions. Is this is Zikula or Symphony issue?

![image](https://cloud.githubusercontent.com/assets/628801/22883232/d6a20654-f1f7-11e6-876a-81177759e948.png)
![image](https://cloud.githubusercontent.com/assets/628801/22883250/faf4f016-f1f7-11e6-964b-37d79a1cd347.png)

**Comment by rallek** [comment]
@nmpetkov As far as I know it is a consequece from symphony. an emty string is also a valid result.

I found a workaround what seems to work fine. If in poedit a translation is marked unclear the complete string (original and translation) is not used. But that is not tested in detail. I might be wrong.

**Comment by nmpetkov** [comment]
@rallek It is uncomfortably that missing translations have to move to right tab manually. I found a workaround as shown in the picture, using first option. But I am not sure if this is right way. I checked few, and left and right side was equal.

![image](https://cloud.githubusercontent.com/assets/628801/22898067/9e3db678-f22e-11e6-8e38-71274521f74f.png)

**Comment by rallek** [comment]
I am using the third one often (if you have the paid version). I am quite happy with the result.
After a while you have in your own translation database a lot of similar translations. I am curretly working at several Modulestudio Modules. There I do recognize that the pre translation is becomming better and better.

**Comment by nmpetkov** [comment]
I have paid version also. It is worth. You are happy with German automatic translation, but I am not very happy with Bulgarian:-) Anyway it is very useful for manual suggestions particularly.

**Comment by rallek** [comment]
I have to adjust 90% as well. In Zikula we do have very specific strings often. But you will see. After a while it is becomming better and better. But at the end it is a hell of work... That is true.
