### ISSUE TITLE
JavaScript Is Duplicated in <head>

### ISSUE THREAD

**Issue by shefik** [zikula/core#3463]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

JavaScript should only appear once in the `<head>`.

### Actual behavior

The JavaScript appears twice in the `<head>`:

```<script type="text/javascript">/* <![CDATA[ */
    document.location.entrypoint="index.php";
    document.location.pnbaseURL="http://example.com/";
    document.location.ajaxtimeout=180000;
if (typeof(Zikula) == 'undefined') {var Zikula = {};}
Zikula.Config = {"entrypoint":"index.php","baseURL":"http:\/\/example.com\/","baseURI":"","ajaxtimeout":"180000","lang":"en","sessionName":"_zsid","uid":"0"};
/* ]]> */</script>
```

### Steps to reproduce

Load any page of the site.

**Comment by craigh** [comment]
I see no duplication.

**Comment by shefik** [comment]
Okay, not a core issue. The problem is with my theme.
