### ISSUE TITLE
pagevars.langdirection Returns Empty

### ISSUE THREAD

**Issue by shefik** [zikula/core#3464]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

Inserting `dir="{{ pagevars.langdirection }}"` should return ``dir="ltr"`.

### Actual behavior

It returns empty as `dir=""`.

### Steps to reproduce

 Insert `dir="{{ pagevars.langdirection }}"` in your theme's `<html>` tag.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/TranslationAndLanguage/MigrationFromZLanguage.md#replacing-zlanguage

https://github.com/zikula/core/blob/1.4/src/app/config/config.yml#L41

won't fix

**Comment by Guite** [comment]
possible to let `pagevars.langdirection` return `auto`?

**Comment by craigh** [comment]
`pagevars.langdirection` now returns `auto`

**Comment by Guite** [comment]
Great :+1:
