### ISSUE TITLE
Google Fonts Need to Load First

### ISSUE THREAD

**Issue by shefik** [zikula/core#3465]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

Google Fonts (or any other third-party font stylesheets) need to load first, before other CSS files, when the CSS assets are combined into one file, since the combined files reference required fonts.

### Actual behavior

The combined CSS file is loaded first, then the Google Fonts stylesheets are loaded afterwards, even though the weight for the Google Fonts stylesheets is set to `0`.

### Steps to reproduce

In your theme add the following:

```
{{ pageAddAsset('stylesheet', '//fonts.googleapis.com/css?family=Montserrat:400,700', 0) }}
{{ pageAddAsset('stylesheet', '//fonts.googleapis.com/css?family=Raleway:100,300,600,800', 0) }}
```

Set your config to combine the CSS asset files. the output will be something like:

```
<link rel="stylesheet" href="/templates/combined_asset/css/1da10173c7b129a09bbcedafd07bfd441186400.css" type="text/css">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Raleway:100,300,600,800" type="text/css">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700" type="text/css">
```

**Comment by craigh** [comment]
of course, the faster answer here would have been to manually use a 'normal' reference instead of using the zikula method, but I've accommodated the request. I've also added more docs
