### ISSUE TITLE
remove build number from ci build filenames to facilitate 'latestBuild' functions

### ISSUE THREAD

**Issue by craigh** [zikula/core#3468]
https://github.com/Guite/MostGenerator/commit/5d8f23e8936b90ccec34f83eb4108eac4c389269#commitcomment-20944566

**Comment by craigh** [comment]
perhaps the build number could be added to a text file or something somewhere, so it is available for reference by users like @rallek when testing.

**Comment by Guite** [comment]
The build number is still transparent within Jenkins. So if somebody downloads a package there it is visible. Downloading from GitHub is primarily done for pre-releases or releases anyway.

**Comment by craigh** [comment]
maybe you meant "apparent" and not "transparent" ?

**Comment by rallek** [comment]
Is there any chance to see in an installation which build it is? In the past I kept my download file in my webspace and was able to see which build it was (e.g. via ftp). But might be there is another way to see it.

This is only interesting during development phase. It would make it more easy to give better feedback.
