### ISSUE TITLE
Unable to parse the controller name for News Publisher

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3480]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 7.0.x

### Expected behavior
I have expected that I as Zikula 1.4.6 home the news publisher. Unfortunately something is wrong with the controller name and "News" as controller name is not recognized by the system.

How do I enter the controller name for the news publisher?

### Actual behavior
Currently it is with me on the home of this:

`Unable to parse the controller name "News".`

What's wrong?

### Steps to reproduce

You can set the news publisher as the start page and take "news" as the controller name. Then it either comes to the fault or it works.

Thanks in Advance!

**Comment by rallek** [comment]
I sent you an invitation for skype. Might be we can talk there a little bit.

**Comment by AlexL777** [comment]
Thanks, but unfortunately I do not use Skype.

**Comment by rallek** [comment]
Slack is fine as well :-)

**Comment by Guite** [comment]
Controller should be user for News.
