### ISSUE TITLE
How can I show all modules in MainMenu

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3481]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 7.0

### Expected behavior

I would like to display all modules in MainMenu. How can I add more modules to the main menu?

Even in the earlier versions of Zikula there was such an option in the settings. But with the Zikula 1.4.6 I can not find it yet.

**Comment by craigh** [comment]
At the moment, the only answer is to manually add each module as you need. There is no general setting to add all modules at this time.
