### ISSUE TITLE
Zikula 1.4.6 - Edit Profile Issue

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3483]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior
Hello Developers,

I noticed today when editing my userprofile that the fields have no proper names. Here it is screenshot.

![zikula-edit-profile-issue](https://cloud.githubusercontent.com/assets/7885632/23335819/a3c91162-fbbd-11e6-94cf-54e77a67f3ac.jpg)

I use the last Zikula version and in English.

Can you have a look at this?

Also my subdirectory `/src` is not recognized or routed by the system at http://zikula/wpzweinull.ch/src . Therefore, the gravatar is not found. This problem I have also in the Diskuz forum. The Ranks images can not be found and are not displayed in the forum because I can not use `/src` in the path.

There are equal errors in the diskuz front-end. How can I make it better?

Thanks in advance.

**Comment by craigh** [comment]
This is a Profile module problem. can you resubmit the same ticket [at that repo](https://github.com/zikula-modules/Profile)
