### ISSUE TITLE
Tasks for upgrade to 2.0

### ISSUE THREAD

**Issue by Guite** [zikula/core#3484]
This issue collects things which need to be done for upgrading 1.x installations to 2.0

### Remove database tables

- [x] objectdata_attributes (https://github.com/zikula/core/commit/509e16f9323c0b222f38040f7747aeb518f9f11b)
- [x] objectdata_log (https://github.com/zikula/core/commit/509e16f9323c0b222f38040f7747aeb518f9f11b)
- [x] objectdata_meta (https://github.com/zikula/core/commit/509e16f9323c0b222f38040f7747aeb518f9f11b)
- [x] workflows (https://github.com/zikula/core/commit/bc2611e7c4ac47d3ad99bbd554a60814d172caa4) (https://github.com/zikula/core/commit/cacbf0036a8b6378a80e57b1d7528c042fdabd72)

### Other things

 - [x] remove metakeywords system var (06a35fb28f22206fd32cf0d856441fa4a9b9abac)
 - [x] move files from `/userdata` to `web/uploads` #3127 #3525
 - [x] change value of `datadir` in `custom_parameters.yml` to `web/uploads`
 - [x] User Migration 'This action MUST be complete before upgrading to Core-2.0.' #3535

 - [ ] finalize and tag/release dependent modules and other dependencies
- [ ] correct dependencies to actual version in the relative composer.json files in dist
  - LegalModule
  - ProfileModule
  - OAuthModule
  - PageLockModule
  - Andreas08Theme
  - SeaBreezeTheme
  - generator bundle
  - wizard
  - jquery-bundle
  - jquery-ui-bundle
  - bootstrap-bundle
  - fontawesome-bundle

...

**Comment by craigh** [comment]
refs bc2611e7c4ac47d3ad99bbd554a60814d172caa4
refs cacbf0036a8b6378a80e57b1d7528c042fdabd72

**Comment by Guite** [comment]
@craigh any hook tables to remove from the database?

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/master/src/lib/Zikula/Bundle/HookBundle/HookBundleInstaller.php#L73-L82

**Comment by craigh** [comment]
for [this](https://github.com/zikula/core/blob/1a6f21abe2af81527878fa78f0e92d7808c92ec7/src/lib/Zikula/Bundle/CoreInstallerBundle/Util/VersionUtil.php#L34-L34) reason, I think the minimum upgrade version must be 1.4.3 @Guite

**Comment by Guite** [comment]
Agreed.

**Comment by craigh** [comment]
I do not know how to handle the user migration requirement. The method to manually migrate the users is only added in 1.5.0. If we are to _require_ these users to be manually upgraded, then we must minimally require 1.5.0 as upgrade starting point. (in addition to requiring the migration be manually completed).

**Comment by craigh** [comment]
closed byhttps://github.com/zikula/core/issues/3630

**Comment by craigh** [comment]
reopening to remind for tagged versions of deps

**Comment by craigh** [comment]
we should consider running `composer update --no-dev` to generate a "no dev" composer.lock file before release

**Comment by Guite** [comment]
> we should consider running composer update --no-dev to generate a "no dev" composer.lock file before release

Doesn't Jenkins do this anyway?

**Comment by craigh** [comment]
> Doesn't Jenkins do this anyway?

no I don't think so. perhaps you refer to the `--no-dev` shown [here](https://github.com/zikula/core/blob/1.5/build.xml#L53) but this is after the composer.lock file has been generated so `composer install` will simply install everything in composer.lock

**Comment by craigh** [comment]
maybe I'm incorrect about this.

**Comment by craigh** [comment]
I've tagged most of the concerned packages, but cannot complete this task until packages 'catches up' to the changes. then I'll update vendors

**Comment by Guite** [comment]
> until packages 'catches up' to the changes

what do you mean? packagist?

**Comment by craigh** [comment]
this is done for 1.5 but I still need to do 2.0 later today...

**Comment by craigh** [comment]
done
