### ISSUE TITLE
Consider CaaS

### ISSUE THREAD

**Issue by Guite** [zikula/core#3485]
We should think about whether we should use controllers-as-services, as it makes dependencies more explicite and improves testability.

**Comment by javiereguiluz** [comment]
Don't forget the drawbacks: it requires more work and it makes the controller more verbose (they contain more code that you must maintain forever).

**Comment by craigh** [comment]
I think we should continue to utilize symfony's supplied controllers and their features. Third party modules of course (e.g. MOST) can create their own abstract controllers, etc if desired.
