### ISSUE TITLE
HTML Info in security center is broken

### ISSUE THREAD

**Issue by rallek** [zikula/core#3489]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.5.30

### Expected behavior
klick the link and see the correct Homepage with information for this html tag

### Actual behavior
404

### Steps to reproduce
The link is currently pointing to e.g. ``https://www.w3schools.com/html5/html_iframe.asp`` but it should link to ``https://www.w3schools.com/html/html_iframe.asp``

**Comment by Guite** [comment]
Seems they changed their URL structure. Looking at it.

**Comment by Guite** [comment]
The correct link for the example above is `https://www.w3schools.com/tags/tag_iframe.asp` btw.
