### ISSUE TITLE
composer build problems

### ISSUE THREAD

**Issue by craigh** [zikula/core#3526]
jenkins is having trouble with the build

 - no zip file is created in 1.5.0 or 2.0.0
 - assets are installed three times in 2.0.0 and twice in 1.5.0

can anyone have a look? @cmfcmf ? @Guite

**Comment by Guite** [comment]
I can not check this week.

**Comment by Guite** [comment]
The zip creation is fixed. No idea though why all `scripts` are executed multiple times.

**Comment by rallek** [comment]
the latest build of 1.5.0 is ``Build # 49 (08.04.2017 05:45:37) ``. There should be a newer one I guess.

**Comment by Guite** [comment]
The jenkins build trigger is probably fixed now. The POT creation job still listened on the 1.4 branch instead of 1.5. So on next commit into 1.5 it should be started again.

**Comment by rallek** [comment]
1.5 is now running but 1.4.7 as well even without any changes

**Comment by Guite** [comment]
Yes, because both are downstream job of the POT creation.

**Comment by craigh** [comment]
@Guite can you look into this further?

**Comment by craigh** [comment]
@Guite can you look into this again? there is something in the build process (not only jenkins but travis also) that causes multiple runs through cache clearing, assets installed, etc.

perhaps @cmfcmf would find some time to look?

**Comment by Guite** [comment]
The problem is not related by any build scripts. I had two asset installations today too when I executed `composer install --no-dev` for installing 1.5 on my local webserver.

**Comment by Guite** [comment]
I just performed `composer install --no-dev` as well as `composer install` and `composer install -o` in our legacy branch (using Symfony 2.8) and in our master branch (using Symfony 3.3). All attempts executed the scripts only one time.
But Travis executes it two times and our Jenkins even three times: http://ci.zikula.org/job/Zikula_Core-2.0.0/466/console
Odd :confused:

**Comment by craigh** [comment]
@Guite did you start with a clean git pull? I'll guess you didn't clear `vendors` or `web` - probably need to do that too. Also remove `custom_parameters.yml` and `dynamic/generated.yml`

when I do that, here you can see part of my output

![screen shot 2017-07-17 at 8 01 18 am](https://user-images.githubusercontent.com/350048/28267028-28724b32-6ac6-11e7-94c1-9d7ef0656edd.png)

installing, installing installing...

![screen shot 2017-07-17 at 7 58 45 am](https://user-images.githubusercontent.com/350048/28267009-11dfd312-6ac6-11e7-8f04-7a03ce0b2b91.png)

see the second **Loading composer repositories with package information** after `Compiling component files` - I think this is the problem. Something to do with **component installer**

**Comment by craigh** [comment]
this is finally fixed ✅ 

There were a few issues:

1. scripts were running multiple times because of composer issues. this was solved by forcing the composer install to run with no scripts and then running the scripts manually _one time_. 

2. The jenkins build command (in the config) was like so:
> phing -f $WORKSPACE/source/build.xml clean prepare build build_delete -Dworkspace=$WORKSPACE -Djob_name=$JOB_NAME -Dbuild_number=$BUILD_NUMBER -Dbuild_tag=$BUILD_TAG -Dbuild_id=$BUILD_ID -Dsvn_revision=$SVN_REVISION

this caused the `prepare` stage to run twice because the `build` stage ['depends on prepare'](https://github.com/zikula/core/blob/1.5/build.xml#L58).

Therefore I removed it from the build command.
> phing -f $WORKSPACE/source/build.xml clean build build_delete -Dworkspace=$WORKSPACE -Djob_name=$JOB_NAME -Dbuild_number=$BUILD_NUMBER -Dbuild_tag=$BUILD_TAG -Dbuild_id=$BUILD_ID -Dsvn_revision=$SVN_REVISION
