### ISSUE TITLE
eliminate legacy abstract doctrine classes

### ISSUE THREAD

**Issue by craigh** [zikula/core#3529]
can we deprecate and remove in Core-2.0

\Zikula\Core\Doctrine\Entity\AbstractEntityAttribute
\Zikula\Core\Doctrine\Entity\AbstractEntityMetadata

@Guite

**Comment by craigh** [comment]
if so, this would also be removed 
https://github.com/zikula/core/blob/69f2498af636736cbf38eab0e777e54ad14b8c23/src/app/config/config.yml#L77-L82

**Comment by Guite** [comment]
No.

Personally I do not use meta data anymore, but attributes.

**Comment by Guite** [comment]
Close?

**Comment by craigh** [comment]
> Close?

not yet

can I see some code where this is used?

**Comment by Guite** [comment]
https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/models/entity/extensions/Attributes.xtend
https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/view/extensions/Attributes.xtend

**Comment by craigh** [comment]
any chance I could see a _generated_ php file? 😁

**Comment by Guite** [comment]
See https://github.com/Guite/ProductsWithAttributes

**Comment by craigh** [comment]
THANK YOU for taking the time to generate a demo. It helps me understand.

I wonder if we can still remove https://github.com/zikula/core/blob/69f2498af636736cbf38eab0e777e54ad14b8c23/src/app/config/config.yml#L77-L82 because the classes at that location are not entities and don't need to be loaded by themselves. Could you try removing the config and see if your app performs as expected?

Also - I think we should deprecate the MetaData class - thoughts?

finally - is this the best location for this Attributes class? Any other ideas?

**Comment by Guite** [comment]
> Could you try removing the config and see if your app performs as expected?

Yes, still working.

> Also - I think we should deprecate the MetaData class - thoughts?

Fine for me. Do it.

> finally - is this the best location for this Attributes class? Any other ideas?

Sorry, no idea. Why not just leave it where it is?

**Comment by craigh** [comment]
This is complete except that I didn't remove the config code because there is still a WorkflowEntity there which is needed in 1.5.0 I think @Guite ? It is removed from master already though.

**Comment by Guite** [comment]
Correct.
