### ISSUE TITLE
Upgrade to Bootstrap 4.0

### ISSUE THREAD

**Issue by craigh** [zikula/core#3530]
Upgrade to Bootstrap 4.0

See PR at #4037

**Comment by Guite** [comment]
BS4 beta arrived:
https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta

Symfony 3.4 will get a BS4 form theme:
https://github.com/symfony/symfony/pull/21751

**Comment by Guite** [comment]
http://symfony.com/blog/new-in-symfony-3-4-bootstrap-4-form-theme

**Comment by robbrandt** [comment]
I am working with a bootstrap 4 theme now and have found that 4 breaks many bs 3 plugins, and bs 4 plugins haven't been developed yet. It may be wise to proceed slowly.

**Comment by craigh** [comment]
> It may be wise to proceed slowly.

that is why this ticket is assigned to the 3.0.0 milestone. which is (at best) several years away.

**Comment by craigh** [comment]
Bootstrap 4 released 18 January 2018
https://blog.getbootstrap.com/2018/01/18/bootstrap-4/

**Comment by Guite** [comment]
http://symfony.com/blog/new-in-symfony-4-1-improved-bootstrap-4-form-theme

**Comment by Guite** [comment]
4.1.0 arrived today https://github.com/twbs/bootstrap/releases/tag/v4.1.0

**Comment by craigh** [comment]
http://upgrade-bootstrap.bootply.com

https://designmodo.com/migrate-bootstrap-4/

**Comment by Guite** [comment]
Fixed in #4037
