### ISSUE TITLE
Custom title in profileLinkByUserId and probably in profileLinkByUserName

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3534]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x
| PHP Version       | 5.x

### Expected behavior
Be able to set a custom title.

### Actual behavior
Title is hard coded here https://github.com/zikula/core/blob/1.5/src/system/UsersModule/Twig/Extension/ProfileExtension.php#L155

I will do it just want to know if it is ok with you.

**Comment by craigh** [comment]
please explain what you have in mind

**Comment by Kaik** [comment]
Well, I would like to use profileLinkByUserId/name with custom title in Dikzus for example Online users in the footer. Some of them are moderators (different color) and for them, tooltip should be something like  "Username is moderator click to go to profile" etc... hope you understand....:)

**Comment by craigh** [comment]
submit a PR please

**Comment by craigh** [comment]
ping @Kaik this will be moved to Core-2.1 if you forget

**Comment by Kaik** [comment]
@craigh Sorry I'm busy with Dzikus done not tested should work...
