### ISSUE TITLE
Update Profile to Core-2.0

### ISSUE THREAD

**Issue by craigh** [zikula/core#3542]
Profile must be updated to Core-2.0 standards

**Comment by paustian** [comment]
Craig,
I would be willing to take this on. I assume this means getting rid of all the deprecated code. I can pretty easily find it, but are there any tips you have for finding it using PhpStorm?
Let me know if you want to me attack it.

**Comment by craigh** [comment]
I have a lot of ideas here. I had considered using MOST to generate a completely new module but ran into some roadblocks and lack of understanding. @Guite I'm not sure how to proceed yet.

**Comment by Guite** [comment]
> lack of understanding

You might send me your questions to get them answered.

**Comment by craigh** [comment]
of course. eventually :-)

**Comment by craigh** [comment]
I've been working on some ideas with this and pushed some to the 3.0 branch at Profile. I like where it's headed and the module will be much simpler when finished I believe.

**Comment by Guite** [comment]
This is almost done:

- @craigh overhauled property management and added several new property types
- I just solved https://github.com/zikula-modules/Profile/issues/80

There only remains https://github.com/zikula-modules/Profile/issues/81 but I guess this is a rather small one.
