### ISSUE TITLE
Include OAuthModule

### ISSUE THREAD

**Issue by craigh** [zikula/core#3544]
https://github.com/zikula/OAuth

I think we should include OAuth module with Core-2.0 because the Auth module _should_ be *de-emphasized* as an authentication solution for zikula. It is the least secure option.

**Comment by craigh** [comment]
@Guite @cmfcmf @rallek @shefik @Kaik @paustian and anyone I forgot

**Comment by craigh** [comment]
to be clear, I don't mean make it a core module, just include it like we are including PageLock or Andreas08Theme

**Comment by shefik** [comment]
What is the status of this module? Is it functional right now? If not, what else needs to be completed?

**Comment by craigh** [comment]
it works

**Comment by craigh** [comment]
> alpha status - do not use.

I understand this might be disconcerting. To be fair, I haven't tried it since 1.4.3, but it _should_ work 😄 it only has two methods Facebook and Github (I think). it would be good to add a few more.

**Comment by shefik** [comment]
I'll test the module and report my findings. If other methods are considered to be added, I would like LinkedIn and Google.

**Comment by craigh** [comment]
yeah - Google is there already

**Comment by Guite** [comment]
Although I do not use Facebook personally I think this is a must have for many sites.

Does the module  allow enabling/disabling the different providers? So can I for example use GitHub, but not Google? Or GitHub and Google. but not LinkedIn?

**Comment by craigh** [comment]
yes, Facebook would be a must have

UserModule handles enabled/disabling any auth method

**Comment by Guite** [comment]
Then: are the different providers independently provided to the Users module? :-p

**Comment by craigh** [comment]
yes - give it a try, you will see

**Comment by shefik** [comment]
FYI - Here is a library for implementing an OAuth2 Server in php. Maybe this can be included in the module.

https://github.com/bshaffer/oauth2-server-php

**Comment by shefik** [comment]
I installed the module, then went to `/users/admin/config/authentication-methods`, but there aren't any options to enable Facebook. Only Github and Google.

**Comment by craigh** [comment]
> only has two methods ~Facebook~ Google and Github ~(I think)~.

**Comment by shefik** [comment]
There are already libraries available in the vendor folder for Instagram, LinkedIn, and Facebook. They need to be implemented in the module though.

**Comment by craigh** [comment]
really? gosh, I never thought of that.

PRs are welcome.

**Comment by shefik** [comment]
@craigh Yeah, you may already know that. But I'm indicating the note, in case anyone else watching this thread is wondering if functionality is available or not. They may not know this information.

**Comment by paustian** [comment]
@craigh I tested on 1.5 on my system (MacOS) using MAMP. It worked just fine. 
It looks like adding other implementations isn't too bad.

**Comment by robbrandt** [comment]
Including a server library would be awesome!

**Comment by craigh** [comment]
@robbrandt this is not a server library. this is only a client.

**Comment by robbrandt** [comment]
I was referencing @shefik's comment about a server library above.

**Comment by craigh** [comment]
OAuth module will not include the server component. A separate module will need to be created.

**Comment by craigh** [comment]
@paustian are you interested in implementing the other methods?

**Comment by paustian** [comment]
@craigh, I can give it a shot.

**Comment by paustian** [comment]
I took a look. I think this is beyond me without someone explaining what needs to be done.

**Comment by craigh** [comment]
I've updated OAuth module to newest vendors, modified to FC code and added both Facebook and LinkedIn as AuthenticationMethods.

**Comment by Guite** [comment]
:+1:

**Comment by Kaik** [comment]
:+1:

**Comment by craigh** [comment]
closed by 		3a1009d
