### ISSUE TITLE
Theme stylesheet should be automatically included

### ISSUE THREAD

**Issue by craigh** [zikula/core#3548]
currently the front module's stylesheet is automatically included with no additional coding. But Theme stylesheets are required to be [added manually](https://github.com/zikula/core/blob/1.5/src/themes/BootstrapTheme/Resources/views/Include/header.html.twig#L9)

perhaps we should automatically added theme stylesheets also.

**Comment by shefik** [comment]
I agree.

**Comment by paustian** [comment]
I agree too. There are almost always styles you want to include. Is there also a mechanisms to avoid adding it twice? In case someone adds in manually
