### ISSUE TITLE
change JMSTranslationBundle dev to actual version when possible

### ISSUE THREAD

**Issue by craigh** [zikula/core#3550]
see https://github.com/schmittjoh/JMSTranslationBundle/pull/405

currently dev is set at `dev-master` in `composer.json` in order to include this compatibility code with recent versions of Symfony. If a release is ever tagged, switch to the release

**Comment by craigh** [comment]
closed by https://github.com/zikula/core/commit/9ef554d24f2a9942f4877e43665ad0ecee186da2

**Comment by rallek** [comment]
is #2820 possible with the current version?

**Comment by Guite** [comment]
No, blocked by https://github.com/schmittjoh/JMSTranslationBundle/issues/355 / https://github.com/schmittjoh/JMSTranslationBundle/pull/411
