### ISSUE TITLE
Deactivation of search plugin does not work.

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3564]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior
If I deactivate a search plugin, it should sleep.

### Actual behavior
If I try a search by default search block, it does not sleep, it seems.

### Steps to reproduce
Install Pages, deactivate the plugin for Pages and try a search. You get the issue, I submitted in the PagesModule(https://github.com/zikula-modules/Pages/issues/66).
I think this issue should not appear, if the plugin is deactivated; don't know.

**Comment by craigh** [comment]
to be clear, you are deactivating the plugin in the global settings for the module, not the specific block settings, right?

**Comment by Portugao** [comment]
Yes. In the global settings.

**Comment by craigh** [comment]
@Guite can you look into this one?

**Comment by Guite** [comment]
This is fixed already.
