### ISSUE TITLE
Problem with modAvailable()

### ISSUE THREAD

**Issue by shefik** [zikula/core#3567]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

Code should not run, because the module does not exist on the server.

### Actual behavior

Code is run, even if the module does not exists on the server.

### Steps to reproduce

Insert this sample code in a module template:

```
{% if modAvailable('ZikulaExampleModule') %}
     Code to run, only if module exists.
{% endif %}
```

The code should not run, but it does anyway.

**Comment by paustian** [comment]
I will take a try at fixing this.

**Comment by paustian** [comment]
I tested this in 1.5 and it works just fine. I also checked in 1.4.6 and it seems to be working well there too. Could there be a problem with your template?

**Comment by craigh** [comment]
Works for me:
![screen shot 2017-04-29 at 1 21 44 pm](https://cloud.githubusercontent.com/assets/350048/25557420/e5560e08-2cde-11e7-9346-73383149e68c.png)
