### ISSUE TITLE
Deprecate FilterUtil?

### ISSUE THREAD

**Issue by Guite** [zikula/core#3569]
Maybe we should drop FilterUtil completely.

While it seems quite handy, it's power is rather limited (despite it could be enhanced by implementing more plugins) and it is not really maintained.

Opinions? Objections?

**Comment by rallek** [comment]
Is the filter inside the blocks module related to this? The fliter in blocks module is used by me several times.

**Comment by Guite** [comment]
No.

**Comment by craigh** [comment]
I think it is already removed from Master?

**Comment by Guite** [comment]
It isn't:
https://github.com/zikula/core/tree/master/src/lib/Zikula/Component/FilterUtil
https://github.com/zikula/core/tree/master/src/docs/FilterUtil

**Comment by craigh** [comment]
:+1:
