### ISSUE TITLE
Login problem with PHP 7

### ISSUE THREAD

**Issue by Guite** [zikula/core#3573]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x and 1.5.0
| PHP Version       | 7

### Expected behavior
Login working.

### Actual behavior
After executing the login one is still not logged in.

### Workaround
Login works when disabling this line: https://github.com/zikula/core/blob/1.5/src/system/UsersModule/Helper/AccessHelper.php#L112

**Comment by Guite** [comment]
A fix for that should also be backported to 1.4 if possible.

**Comment by Guite** [comment]
Maybe "not core": https://github.com/symfony/symfony/issues/18574

**Comment by craigh** [comment]
Zikula Core <2.0 _does not support php 7+_

**Comment by Guite** [comment]
Then this should be made transparent in readme, installation instructions and all release announcements.

**Comment by craigh** [comment]
I have stated it to you personally multiple times.

**Comment by Guite** [comment]
I am not the only person in the world using PHP 7. Thus if the project does not support it it should make this clear.

**Comment by craigh** [comment]
PRs welcome
