### ISSUE TITLE
Missing implementation block handler interface

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3580]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.dev
| PHP Version       | 5.6

### Expected behavior
Coming in the backend of the blocks module

### Actual behavior
Calling the backend I get this error:
```
Block class Zikula\BlocksModule\Block\MenutreeBlock must implement Zikula\BlocksModule\BlockHandlerInterface.`
```
```
            throw new \RuntimeException($this->translator->__f('Block class %c does not exist.', ['%c' => $blockClassName]));
        }
        if (!is_subclass_of($blockClassName, BlockHandlerInterface::class)) {
            throw new \RuntimeException($this->translator->__f('Block class %c must implement %i.', ['%c' => $blockClassName, '%i' => BlockHandlerInterface::class]));
        }
        $serviceNameHelper = new ServiceNameHelper();
```

### Steps to reproduce
Call the blocks module from the top nav in bootstrap menu.

**Comment by craigh** [comment]
confirmed, but I don't think this has anything to do with the interface. must be some recent change as it was previously working.

**Comment by Portugao** [comment]
I hope, someone will find the reason in a few days or faster. 😉

**Comment by Portugao** [comment]
Nice to see. Thanks a lot. 👍
