### ISSUE TITLE
Not able to create new menu

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3588]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.dev
| PHP Version       | 5.6

### Expected behavior
If I enter a name for a new menu and press save, the new menu should get saved.

### Actual behavior
I get a return to the edit page and a small error message:
The selected item does not exist

### Steps to reproduce
Open the edit function to create a new menu, enter a name and try to save.

**Comment by craigh** [comment]
![screen shot 2017-05-12 at 9 05 01 pm](https://cloud.githubusercontent.com/assets/350048/26021185/b55c18aa-3756-11e7-89d8-faba19e25b49.png)

**Comment by Portugao** [comment]
👍
