### ISSUE TITLE
Not able to edit registry of categories

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3593]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5 dev
| PHP Version       | 5.6

### Expected behavior
Getting the list of registry entries

### Actual behavior
I get this error:
```
An exception has been thrown during the rendering of a template ("Notice: Undefined index: de").
```
Stack trace:
in system/CategoriesModule/Resources/views/Registry/edit.html.twig at line 40
```
                    <td headers="hModule">{# dModname #}{{ registry.modname }}</td>
                    <td headers="hEntity">{% if registry.entityname|default %}{{ registry.entityname }}{% endif %}</td>
                    <td headers="hProperty">{{ registry.property }}</td>
                    <td headers="hCategory">{{ registry.category.display_name(app.request.locale) }}</td>
                    <td headers="hActions" class="actions">
                        <a class="fa fa-pencil tooltips" href="{{ path('zikulacategoriesmodule_registry_edit', { id: registry.id }) }}" title="{{ __('Edit') }}" ></a>
                        <a class="fa fa-trash-o tooltips" href="{{ path('zikulacategoriesmodule_registry_delete', { id: registry.id }) }}" title="{{ __('Delete') }}"></a>
```
in system/CategoriesModule/Entity/CategoryEntity.php at line 418 

    public function getDisplay_name($lang = null)
    {
        if (!empty($lang)) {
            return $this->display_name[$lang];
        }
        return $this->display_name;

### Steps to reproduce
Have multilingual active and try to call the edit function of the category registry.

**Comment by craigh** [comment]
> Steps to reproduce

I'm guessing you left out the fact that English is not the selected language?

also - what you have shown is not a stack trace. A stack trace is not the _location_ of the error, but the series of function calls which produced the error. In this case - the stack trace looks like this:

![screen shot 2017-06-02 at 4 56 18 pm](https://cloud.githubusercontent.com/assets/350048/26744622/b2e8889c-47b4-11e7-83a0-4021c50afe37.png)

**Comment by Portugao** [comment]
> I'm guessing you left out the fact that English is not the selected language?

I checked with english as selected language and get the same message with 'en' at the end.

I was not sure, if I should provide the complete collection of called functions......
