### ISSUE TITLE
Workflow config needs correction for Sy3.3

### ISSUE THREAD

**Issue by craigh** [zikula/core#3596]
@Guite this needs your attention please. you can see that the travis and ci builds are broken after upgrading symfony to 3.3. This has to do with the workflow config. 

> php bin/console clear:cache
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '"supports" or "support_strategy" should be configured.' in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/ExprBuilder.php:204
Stack trace:
#0 /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/ExprBuilder.php(256): Symfony\Component\Config\Definition\Builder\ExprBuilder->Symfony\Component\Config\Definition\Builder\{closure}(Array)
#1 /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(309): Symfony\Component\Config\Definition\Builder\ExprBuilder::Symfony\Component\Config\Definition\Builder\{closure}(Array)
#2 /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(203): Symfony\Component\Config\Definition\BaseNode->finalize(Array)
#3 /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/S in /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php on line 313

**Comment by Guite** [comment]
Update to Symfony 3.3.2 as part of this.

**Comment by Guite** [comment]
Fixed in 2e2edc0a9fdde8a4292a5b950f3b185414e5e8db
