### ISSUE TITLE
[adminmodule] Add icon field for module category

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3598]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x.x
| PHP Version       | 5.x

Feature request and/or discussion.

It would be good to have in the AdminModule option where you can specify an icon for a category.  I'm playing now with different administration designs and need to do dirty hacks like using category name in icon class.

I know that this is not important atm, small feature request just leaving here to see what do you think.

**Comment by Guite** [comment]
https://farbelous.io/fontawesome-iconpicker/ would be a nice addition for this (and maybe for other places, too).

**Comment by Guite** [comment]
- [ ] Use icon picker shown above
- [ ] Add new icon field to `AdminCategoryEntity`
- [ ] Add picker also to menu module
- [ ] Add icon field and icon picker also to Categories module (maybe)
- [ ] Add new string field role to ModuleStudio DSL allowing arbitrary *icon fields*

**Comment by Kaik** [comment]
Icon picker could be "in optional mode" so custom icon class can be entered manually.

**Comment by Guite** [comment]
Done.
