### ISSUE TITLE
[composer] Enable merge-scripts let module handle its dependencies assets

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3599]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.x.x
| PHP Version       | 5.x

Since we use https://github.com/wikimedia/composer-merge-plugin#composer-merge-plugin we could use 
>A "merge-scripts": true setting enables merging the contents of the scripts section of included files as well. 

This would allow running a custom script from inside a theme or module that will "copy" assets from installed module/theme dependencies into /web folder. This happens after composer solved dependencies and installed them into /vendor folder. RobLoach/component-installer component installer does exactly that when you install a component.

Is this a good idea? I made a small theme that is only for admin atm and it is based on AdminLTE which has composer but is not a component so the component installer cannot install it to /web.

Normally we have to place 3party assets into Resources/public so it can be accessed from web dir which is really annoying...

With merge-scripts true and small script in theme, I can download any repo on GitHub even if it is not meant to be used with composer to /vendor and then handle copying/installing/compiling those assets to /web

I will do an example that you can check soon. This is a feature to discuss.

**Comment by Kaik** [comment]
Hi, I had some time to do a simple example. It might not work yet, composer part was not tested yet it was refactored from working theme. This is most important part https://github.com/Kaik/KaikmediaAdminLTETheme/blob/master/Composer/InstallAdminLteAssets.php

it reacts to ``"merge-scripts": true`` just after composer processed installation and check(version) on required asset. At that moment assets are in vendor dir. Above script is copying/deploing required stuff to web/  

You do not need component installer then and you can do much more than only copy files from one place to another.

**Comment by craigh** [comment]
Hi @Kaik 

thanks for the ideas. This is not something we are prepared to include in Core-2.0, so it is currently scheduled for 2.1 which is at least a year away.

In the end though, this gets back to a question of building a custom distribution for any end-user. This is not something we have an infrastructure for at the moment. The core can only build the core as a generic usage for anyone. There is no way to include custom extensions (modules, themes) with our current model. Certainly an advanced developer like yourself can build their own distribution locally and run various scripts, etc. but this is not (yet) a general use-case.

Therefore, I see something like this more probably in Core-3.0 where symfony's new web pack-encore or flex might be useful to us.

refs #3438

**Comment by Kaik** [comment]
Hi, I kind of understand what you are saying this "feature" is not for our "target" at the moment. I think apart from "general use case target" we can start building semi dev target where we can, at least explain the way core build is composed from source its not really that hard.

When I will have some time I can prepare a doc introduction to composer really basic and really basic information how to build and deploy your own distribution.  To be honest a real website developer should know this as well as git and some other basic web dev related stuff like LAMP, ... 

Anyway, in the mean time, there is one thing that can make life a bit easier could you consider adding `` merge-scripts: false `` it works same as it is now, it will just be easier to point people to switch it to true than add whole bit ;) I will do PR.

**Comment by Kaik** [comment]
Ok, this does not work anymore something has changed I have traced it a bit but not all. I have decided to add that script directly to zikula's composer.json. I do not have much time to investigate it now. If someone is interested then commits on Jul 17, 2017 are the ones that are changing the way it works.
Anyway I'm happy with current solution and I wait for #3438

**Comment by craigh** [comment]
closing this as composer-merge-plugin is no longer used.
