### ISSUE TITLE
refactor \Zikula\Core\AbstractBundle::getRelativePath() to remove

### ISSUE THREAD

**Issue by craigh** [zikula/core#3604]
refactor \Zikula\Core\AbstractBundle::getRelativePath() to remove

**Comment by Guite** [comment]
```
probably need to use getPath method instead and refactor
but…
I think this is also used with other code that could be pointless
for example:
one example of getRelativePath is to calculate and store the relative directory of an extension
then later, this is **probably** used to calculate the directory including decision about core/not core module (e.g. system/modules dir)
this is dumb
just store the full path or the path from project dir
but that directory value in ExtensionEntity
but be used many times elsewhere
so would be dangerous
```

**Comment by Guite** [comment]
Postponing to 3.0: this should be done together with merging module and theme management and #3438.

**Comment by craigh** [comment]
I am concerned about leaving `getRelativePath()` as accessible in the core.

**Comment by Guite** [comment]
Why? It is marked as `@deprecated`, so any usage inside modules is officially discouraged.

The point is: if we persist the complete path in ExtensionEntity this is actually a start of merging modules and themes and thus a part of a bigger refactoring which will be done anyway with #3438 and the removal of the Theme module later.

**Comment by craigh** [comment]
this must be done. I'm taking care of it

**Comment by craigh** [comment]
note to self: These are the only usages that matter:

- https://github.com/zikula/core/blob/446cc97b3ac72a64b3ffb7f698fc12aa45c542d5/src/lib/Zikula/Bundle/CoreBundle/Bundle/MetaData.php#L276-L276
- https://github.com/zikula/core/blob/f135c7bd4ee6fad3c1cfa0466afe0eecab8bfa2c/src/system/ThemeModule/Helper/BundleSyncHelper.php#L134-L134
   - https://github.com/zikula/core/blob/f135c7bd4ee6fad3c1cfa0466afe0eecab8bfa2c/src/system/ThemeModule/Entity/Repository/ThemeEntityRepository.php#L105-L105
   - https://github.com/zikula/core/blob/67c9c95ac57a3387e71b6d128b6067be0b56884f/src/system/ThemeModule/Resources/views/Theme/credits.html.twig#L28-L28

everything else is deprecated and already removed in master.
