### ISSUE TITLE
correct stylesheet images

### ISSUE THREAD

**Issue by craigh** [zikula/core#3606]
in several places in the core, it is assumed that the old global images `/src/images` directory will be present and contain old images. this must be corrected. example:

    background: url("/images/global/arrow_down_white.png") no-repeat scroll 95% 50% transparent;

I recommend the required image be placed in the module/bundle 's `Resources/public/images` dir and the css be corrected to match. For 1.5, the image should be also left in the global images dir.

**Comment by Guite** [comment]
Two questions about this:

1. Should the images be references at the `web/bundles/core/` or `web/modules/zikulathememodule` folder?
2. Should we assume the stylesheets also being loaded from `web`?

**Comment by craigh** [comment]
1. depends on where the source image is moved to. either could be appropriate for any image

2. yes
