### ISSUE TITLE
remove use of Global translation functions

### ISSUE THREAD

**Issue by craigh** [zikula/core#3607]
There are some use of old global translation methods in the code, e.g.

`__('my string')`

as opposed to 

`$translator->__('my string')`

these must all be corrected.

IMO, any translation of an error message that will only be displayed to a developer can be removed so the message is simply in English. There is no sense injecting a translation service for this.

**Comment by craigh** [comment]
also `__f()` `_fn()` `_n()` although these will be less common

**Comment by craigh** [comment]
`(?<!->)__\(`

**Comment by rallek** [comment]
@craigh wrote: ``IMO, any translation of an error message that will only be displayed to a developer can be removed so the message is simply in English. There is no sense injecting a translation service for this.``

I would like to see the possibilities to translate these strings also.
