### ISSUE TITLE
Security issue with Swift Mailer

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3616]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.dev
| PHP Version       | 5.5

### Expected behavior
If I edit an item, I wish to have a normal redirect to the adressed page.
### Actual behavior
During the redirect I get this message:
```
Warning: escapeshellcmd() has been disabled for security reasons in /domain/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php on line 259
```
### Steps to reproduce
Not so easy I think, because I get this message in the mailer module:
```
Mail Transport Mechanismen SMTP und SENDMAL sind abgeschaltet, da deine PHP die "proc_*" Funktion nicht unterstützt. Entweder musst du diese von den "disabled_functions" in der php.ini entfernen, oder du musst PHP komplett neu kompilieren. Danach starte deinen Webserver neu.
```
That means SMTP and SENDMAIL are disabled, because of the my php version and its configuration.

And you have to have a notification function in your extension. Each MOST module with a standard workflow has it.

So I'm not sure if it is an issue of the core or a misconfiguration of my hosting company.

**Comment by Guite** [comment]
This is not a security issue, but just a problem with your php configuration. You will need to remove `escapeshellcmd()` from the `disabled_functions` setting in your php.ini file.

**Comment by Portugao** [comment]
Have to connect my hosting support.
