### ISSUE TITLE
Decide about capabilities

### ISSUE THREAD

**Issue by Guite** [zikula/core#3620]
We need to decide whether capabilities are still needed or completely replaced by tagged services (actually many capabilities were already replaced and only remain for BC). In the latter case the capability api should be deprecated in 1.5 and removed in 2.0.

**Comment by craigh** [comment]
I think most of the capability keys are handled via DI tags now with the exception of `user` and `admin` route identifiers. Not sure about this though.

**Comment by craigh** [comment]
also yet sure about \Zikula\ExtensionsModule\Api\ApiInterface\CapabilityApiInterface::CATEGORIZABLE

**Comment by Guite** [comment]
As the others are already deprecated we could also postpone this to 2.1.0.

**Comment by Guite** [comment]
@sstok suggests https://github.com/rollerworks/RouteAutowiringBundle for auto-wiring user and admin routes.
Postponing to 2.1.0.

**Comment by Guite** [comment]
Moving to 3.0.0 again. @craigh something we should talk about in Slack.

**Comment by Guite** [comment]
Closing as we still need capabilities as well as CapabilityApi.
