### ISSUE TITLE
remove \Zikula\Core\FilterUtil\CategoryPlugin

### ISSUE THREAD

**Issue by craigh** [zikula/core#3632]
I think \Zikula\Core\FilterUtil\CategoryPlugin should be removed? from master

check for usage

**Comment by Guite** [comment]
Yes.

**Comment by Guite** [comment]
Fixed.

**Comment by craigh** [comment]
it should be @deprecated in 1.5

**Comment by Guite** [comment]
Done. Changelog entry is not necessary because FilterUtil deprecation is already mentioned there.

**Comment by craigh** [comment]
ty 🙇
