### ISSUE TITLE
implement all commands as 'lazy'

### ISSUE THREAD

**Issue by craigh** [zikula/core#3642]
http://symfony.com/blog/new-in-symfony-3-4-lazy-commands

**Comment by Guite** [comment]
https://symfony.com/doc/current/console/lazy_commands.html

Possible candidates:

- `Zikula\Bundle\CoreBundle\Command\AssetsInstallCommand`
- `Zikula\Bundle\CoreBundle\Command\BootstrapBundlesCommand`
- `Zikula\Bundle\CoreInstallerBundle\Command\AbstractCoreInstallerCommand`

**Comment by craigh** [comment]
https://symfony.com/doc/current/console/commands_as_services.html#lazy-loading
https://symfony.com/doc/current/console/lazy_commands.html
