### ISSUE TITLE
Run composer schema validation helper on all extensions during build cycle

### ISSUE THREAD

**Issue by craigh** [zikula/core#3645]
Run composer schema validation helper on all extensions during build cycle

**Comment by Guite** [comment]
Composer validation is done during bundle sync here:
https://github.com/zikula/core/blob/master/src/system/ExtensionsModule/Helper/BundleSyncHelper.php#L172-L184

@craigh 
Does this ticket refer to the core's CI jobs instead?
Worth the effort?

**Comment by craigh** [comment]
> Does this ticket refer to the core's CI jobs instead?
yes
> Worth the effort?
your effort. your choice.

**Comment by Guite** [comment]
Closing as "won't fix".
