### ISSUE TITLE
namespace extension javascript translation

### ISSUE THREAD

**Issue by craigh** [zikula/core#3650]
currently all translations are stored in a `zikula_javascript` namespace. If possible, change this so that extensions use their own namespace.

- `\Zikula\Bundle\CoreBundle\Translation\...\ZikulaJsFileExtractor::JAVASCRIPT_DOMAIN`
- `\Zikula\Bundle\CoreBundle\Translation\...\ZikulaJsFileExtractor::visitFile`
- `\Zikula\ThemeModule\EventListener\DefaultPageAssetSetterListener::addJsTranslation`

Also consider option of dumping translations to `/web`

**Comment by Guite** [comment]
We are not using the `<extensionname>_javascript` convention anymore. Instead, JavaScript can use arbitrary domains and even the same one as PHP.

Slightly refs 2d01c898a30b23282e0201607315c02f20ffc33d

Closing.
