### ISSUE TITLE
`users.search.process_edit` event is no longer dispatched

### ISSUE THREAD

**Issue by craigh** [zikula/core#3652]
the `users.search.process_edit` event is no longer dispatched with this method. could it be done in a Transformer?

see `\Zikula\UsersModule\Controller\UserAdministrationController::searchAction`

**Comment by Guite** [comment]
What is the purpose of this event? Enable other parties filtering out specific results?

**Comment by craigh** [comment]
unknown atm

**Comment by Guite** [comment]
Closed as won't fix. If a concrete need occurs we can add something new.
