### ISSUE TITLE
purpose of MetaTagExtension

### ISSUE THREAD

**Issue by craigh** [zikula/core#3655]
`\Zikula\Bundle\CoreBundle\Twig\Extension\MetaTagExtension`

not sure why we have this

it performs this:

        $this->container->setParameter('zikula_view.metatags', $metaTags);

which I don't think will work in Sy3.3+

**Comment by craigh** [comment]
@Guite

**Comment by Guite** [comment]
Yes this looks odd indeed. We might use a page var instead (like it was until 1.3)?

**Comment by Guite** [comment]
@craigh 

I've searched the codebase for `zikula_view.metatags`: the only occurence is this `MetaTagExtension` class. Afterwards I searched for `setMetaTag` (name of the Twig function) and found no usage of it (it is documented within `docs/` though).

I propose to remove it in favour of the `pageSetVar` function.

If you agree I can do this in both `1.5` and `master`.

**Comment by Guite** [comment]
Update: it should only be removed in `master` because in `1.5` it is used indeed, but only by legacy stuff.

**Comment by craigh** [comment]
> If you agree

sounds good ✅

**Comment by Guite** [comment]
Deprecated in 1.5, removed in master. Closing.

**Comment by craigh** [comment]
I just noticed this is used in Pages... do we care? obviously it can be removed there if needed.

> I propose to remove it in favour of the pageSetVar function.

is functionality required to be added to allow this? Did you check?

**Comment by Guite** [comment]
Maybe let's challenge this one together tomorrow if you have time. Afterwards freeze and RC of both 1.5 and 2.0 :tada:

**Comment by Guite** [comment]
Just tested this:
```
{{ pageSetVar('meta.description', 'My description') }}
{{ pageSetVar('meta.keywords', 'My keywords') }}
```
works fine.

**Comment by Guite** [comment]
Updated Pages in https://github.com/zikula-modules/Pages/commit/df378833660b88c4f772dbc28fb46869ce94ffed

Closing.

**Comment by Portugao** [comment]
👍 
Indeed. Works.
