### ISSUE TITLE
Wrong entered filter causes Blocks module not reachable

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3672]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.dev
| PHP Version       | 5.6.31

### Expected behavior
If I enter wrong filter, I would like to be able to edit the block again

### Actual behavior
If I enter not correct filter, the blocks module is not available with SQL error.

### Steps to reproduce
Enter a wrong filter and save the block. Then try to edit.

**Comment by craigh** [comment]
> Enter a wrong filter

can you give me an example?

**Comment by Portugao** [comment]
In the filter you have enter something like "tbl.yourfield = 'something'".
Try to enter "yourfield = 'something' or "tbl.yourfield == 'something'.

**Comment by craigh** [comment]
![screen shot 2017-07-17 at 3 51 39 pm](https://user-images.githubusercontent.com/350048/28286930-d9f0c69a-6b07-11e7-8b86-c5ddbafd05ef.png)
Are we talking about the same thing?

![screen shot 2017-07-17 at 3 53 33 pm](https://user-images.githubusercontent.com/350048/28287002-1a4d87be-6b08-11e7-8262-843e32f8b26c.png)
This works fine for me.

not sure what this has to do with `tbl.yourfield` ? I must be misunderstanding.

**Comment by Portugao** [comment]
Hmmhmm, sorry... I see now by opening a html block, that it is not a core issue. Because I have seen now, that the filter field I mean is only supported in MOST module blocks.
Sorry again; I open this in MOST.
