### ISSUE TITLE
Readd event for uninstalled hook subscribers

### ISSUE THREAD

**Issue by Guite** [zikula/core#3677]
The `installer.subscriberarea.uninstalled` event is deprecated and apparently not contained in the new hook dispatcher.
How can a provider react for a removed subscriber binding now (for example to remove assignment data)?

**Comment by craigh** [comment]
Use case?

**Comment by craigh** [comment]
fyi - subscriber areas cannot be uninstalled as they are not persisted in the first place ;-) possibly a module.uninstalled event would fit your use case?

**Comment by Guite** [comment]
Yes, the uninstalled event is perfect. Because I could remove a binding, but re-add it later again. Then I still have all object attachments available until the subscribing module is finally entirely uninstalled.

**Comment by craigh** [comment]
al bindings are deleted on module install/uninstall
