### ISSUE TITLE
move additional sub packages to packagist

### ISSUE THREAD

**Issue by craigh** [zikula/core#3680]
these repos should be moved to packagist

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/zikula/symfony-service-definition-validator/"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula-modules/Legal"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula-modules/Profile"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula-modules/PageLock"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula/OAuth"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula/ZikulaAndreas08Theme"
        },
        {
            "type": "vcs",
            "url": "https://github.com/zikula/ZikulaSeaBreezeTheme"
        }
    ],

**Comment by Guite** [comment]
This is done. Closing.
