### ISSUE TITLE
link to upgrade instruction is broken

### ISSUE THREAD

**Issue by rallek** [zikula/core#3690]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 RC1
| PHP Version       | 5.6

### Expected behavior
the link to the upgrade instruction should show something usefull

### Actual behavior
an error message

### Steps to reproduce

Upgrade with the german language pack (from 1.4.6 translation! That might be the issue).
When you can start the upgrade there is a link to further instruction. This is pointing to ´´http://2017.oldtimerigosnabrueck.de/de/installdoc/UPGRADE-Core1.x.md´´

If you click it you will get an error message:
´´´´
Fatal error: Uncaught exception 'ReflectionException' with message 'Class Zikula\PageLockModule\Api\ApiInterface\LockingApiInterface does not exist' in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php:38 Stack trace: #0 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(38): ReflectionParameter->getClass() #1 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentsValidator.php(20): Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator->validate(Object(ReflectionParameter), Object(Symfony\Component\DependencyInjection\Reference)) #2 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/MethodCallsValidator.php(50): Matthias\SymfonyServiceDefinitionValidator\ArgumentsVali in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php on line 38
´´´´

Not shure if this is an error of the current core or of the translation file. Will investigate the po files.

**Comment by rallek** [comment]
the fatal error is not there anymore (can be I did not empty the cache). A German Translation is have a similar result than without any translation. I do get 
´´´´
The file you requested (UPGRADE-Core1.x.md) could not be found.
´´´´

**Comment by craigh** [comment]
> Class Zikula\PageLockModule\Api\ApiInterface\LockingApiInterface does not exist

This issues was fixed in https://github.com/zikula/core/commit/1f0029701ac5fd743c0f5660f4ab731c2bc42005

**Comment by Guite** [comment]
This issue is about a wrong link to the upgrade docs.

> When you can start the upgrade there is a link to further instruction. This is pointing to 
> ´´http://2017.oldtimerigosnabrueck.de/de/installdoc/UPGRADE-Core1.x.md´´

> The file you requested (UPGRADE-Core1.x.md) could not be found.

**Comment by craigh** [comment]
apologies. can you fix this then?
