### ISSUE TITLE
Upgrade from 1.4.6 to 1.5.0 failed

### ISSUE THREAD

**Issue by rallek** [zikula/core#3691]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 RC1
| PHP Version       | 5.6

### Expected behavior
Upgrade went fine

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/28502015-77d0e9d6-6fe9-11e7-9fa5-9582d333b375.png)
after clicking "abschließen" I get this error message:
´´´´
Fatal error: Uncaught exception 'ReflectionException' with message 'Class Zikula\PageLockModule\Api\ApiInterface\LockingApiInterface does not exist' in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php:38 Stack trace: #0 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(38): ReflectionParameter->getClass() #1 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentsValidator.php(20): Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator->validate(Object(ReflectionParameter), Object(Symfony\Component\DependencyInjection\Reference)) #2 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/MethodCallsValidator.php(50): Matthias\SymfonyServiceDefinitionValidator\ArgumentsVali in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php on line 38
´´´´

### Steps to reproduce

use the german translation and follow the upgrade instructions

**Comment by rallek** [comment]
Now I try with no translation. 
I deleted the databse and copied the 1.4.6 version into it. Now I start the upgrade and do get a similar result:
![grafik](https://user-images.githubusercontent.com/935250/28502167-a25f7a70-6fec-11e7-9ee5-de6ced72f6e3.png)

at the end the same error message

**Comment by Portugao** [comment]
Did you clean the folder of your installation before your upgrade?

**Comment by rallek** [comment]
I started with a ci download. In this foldet I copied the files (modules, theme, userdata, app/resources, config files). Than I changed the directory for my site.

That is more or less the same than empty folder.

**Comment by Portugao** [comment]
Hmmhmm...that's not so good. It is a blocker for the build, I think.

**Comment by craigh** [comment]
send me your DB

**Comment by rallek** [comment]
you have mail

**Comment by Guite** [comment]
@craigh two possibly related issues:

- the zip file of 1.5 rc1 is broken at GitHub: it does not contain any modules folder at all; at GitHub it has only 24.5 MB, but in Jenkins 41.2 MB; maybe a timeout during the asset copy process? For 2.0 rc1 it seems fine.
- the PageLock module is contained in version 1.2.0 instead of 1.2.2, hence the PageLockApiInterface is missing

**Comment by craigh** [comment]
![screen shot 2017-07-24 at 6 41 02 am](https://user-images.githubusercontent.com/350048/28519877-454011f2-703b-11e7-8d42-125bd653b3d1.png)

@Guite which zip file are you referring to?

@rallek I will need your admin login creds also. Which of the above did you download?

**Comment by Guite** [comment]
The corrupt file is https://github.com/zikula/core/releases/download/1.5.0-rc1/Zikula_Core-1.5.0.zip

**Comment by craigh** [comment]
yeah, oops. I screenshot the wrong release, but you are essentially pointing to the "1" ("2" is known problem). I thought these assets were copied from jenkins. does http://ci.zikula.org/job/Zikula_Core-1.5.0/lastSuccessfulBuild/artifact/build/archive/Zikula_Core-1.5.0.zip have the same problems?

> the PageLock module is contained in version 1.2.0 instead of 1.2.2

why didn't composer update this?

**Comment by Guite** [comment]
> I thought these assets were copied from jenkins

Yes. Thus I assumed:

> at GitHub it has only 24.5 MB, but in Jenkins 41.2 MB; maybe a timeout during the asset copy process?

> why didn't composer update this?

You obviously discovered it already: https://github.com/zikula-modules/PageLock/compare/9cbf1b0468...64974be844

**Comment by craigh** [comment]
@rallek said:
> I started with a ci download.

did you download really from CI? (e.g. http://ci.zikula.org/job/Zikula_Core-1.5.0/lastSuccessfulBuild/artifact/build/archive/Zikula_Core-1.5.0.zip) 

or

did you download from the release on github? (e.g. https://github.com/zikula/core/releases/download/1.5.0-rc1/Zikula_Core-1.5.0.zip)

**Comment by craigh** [comment]
@rallek please try build 228 http://ci.zikula.org/job/Zikula_Core-1.5.0/228/

**Comment by Guite** [comment]
Doesn't matter. The error @rallek experienced was caused by the old PageLock version:

> Uncaught exception 'ReflectionException' with message 'Class Zikula\PageLockModule\Api\ApiInterface\LockingApiInterface does not exist'

**Comment by craigh** [comment]
right. build 228 solves that

**Comment by rallek** [comment]
I am always using http://ci.zikula.org/job/Zikula_Core-1.5.0/lastSuccessfulBuild/artifact/build/archive/Zikula_Core-1.5.0.tar.gz

Will test as soon as I am at home. Everything is prepared already.

**Comment by rallek** [comment]
with ci build 231 it is fixed
