### ISSUE TITLE
a private/closed group can not be applied to join a group

### ISSUE THREAD

**Issue by rallek** [zikula/core#3696]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 231
| PHP Version       | 5.6

### Expected behavior
After clicking the ``apply to membership of ' Groupname' group`` I should get a form where I can apply to join for that group

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/28537407-05f70918-70ab-11e7-9263-760cb9891ee7.png)

**Comment by Guite** [comment]
I don't know exactly how it works, but I guess that this is intential. A private group isn't public so it can not be joined.
@craigh how should it be?

**Comment by Portugao** [comment]
@rallek the group must be open!

**Comment by craigh** [comment]
> that this is intential

right

**Comment by rallek** [comment]
sorry. Tested it out. was a misunderstanding. It works perfectly.

**Comment by rallek** [comment]
but I do not receive any email that some applies to join the group. Do I have to configure something for groups? The system is sending other emails.

**Comment by rallek** [comment]
found it. Sorry.
