### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by rallek** [zikula/core#3697]
From slack:

Ralf Köster [9:21 PM] 
Question to oauth module. If I have a user registered in the classic zauth method and will now login via facebook. The Username is different in both cases but the email address is the same. Is that the reason why I do get the error message "User is not locally registered. " And "Login failed"? Or is it a failure and I should create a ticket? Where? oauth or core?

[9:25] 
Now login is not possible anymore! When the user is trying to click on "log in" he is redirected to a strange URL: /#_=_
And is getting the same Error message. At the end that is a Bug. I will report it as an issue on github.

At the end was able to fix it:
The only solution is to delete the cookie.

**Comment by craigh** [comment]
I believe this is fixed. some of it is just misunderstanding of new processes. Some of it is poor feedback in the modules. Please test with the newest builds and see if that is clearer. reopen the ticket if we still need work.

for the record, I was not able to reproduce the `strange URL: /#=` part, but I think I have an idea what was happening and I tried to fix it.

**Comment by rallek** [comment]
![grafik](https://user-images.githubusercontent.com/935250/28587143-6efa8d60-7176-11e7-9adf-c2ae7020b1c0.png)
This happend after first login with facebook. But the user was not registered that time. After register everything is working fine.
