### ISSUE TITLE
Most modules made for 1.4.6 are not working under 1.5.0

### ISSUE THREAD

**Issue by rallek** [zikula/core#3698]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 231
| PHP Version       | 5.6

### Expected behavior
MOST modules generated for 1.4.6 should work with 1.5.0

### Actual behavior
````

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

$categoryAssignments must be an array of AbstractCategoryAssignment
````

### Steps to reproduce
Upgrade a site from 1.4.6 with MOST modules (that have categories enabled). After upgrade try to enter something of the module.

**Comment by Guite** [comment]
I think this has already been solved by https://github.com/Guite/MostGenerator/commit/6adbd13f5a5b210f7e24b5c7f67ba1282395be63 so you would need to regenerate...

**Comment by rallek** [comment]
will try this evening

**Comment by craigh** [comment]
This is not a core issue, but a MOST issue. closing here.

**Comment by rallek** [comment]
confirmed. regenerating is solving this issue
