### ISSUE TITLE
Travis failure master branch

### ISSUE THREAD

**Issue by craigh** [zikula/core#3703]
This has something to do with both the internal (hopefully) Travis issue and also there is a problem with phpunit which I've tried to fix and failed.

first it referenced https://github.com/symfony/symfony/issues/19532

but I've tried first `bin/pnpunit` then `./src/vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit`
(see https://github.com/zikula/core/blob/master/.travis.yml#L40) but still some tests fail that pass on my local machine. 

atm I have no ideas.

**Comment by craigh** [comment]
The internal errors seem to have disappeared but the pnpunit failures continue

**Comment by craigh** [comment]
I changed the phpunit to `./bin/phpunit` again
Current status:

![screen shot 2017-07-25 at 1 25 10 pm](https://user-images.githubusercontent.com/350048/28584987-c155a4da-713c-11e7-8d83-b15545c1ff5f.png)

**Comment by craigh** [comment]
so I removed some config that was trying to load api.so and memcache.so and this removed the errors above, but did not solve the problems with the tests failing (see travis-ci.org/zikula/core/builds/258167616). So apparently the php errors have nothing to do with the tests failing.

opened question and SO https://stackoverflow.com/questions/45353543/symfony-3-unit-tests-pass-locally-but-not-at-travis

**Comment by craigh** [comment]
I made some progress with this and have a branch in the works

https://github.com/zikula/core/compare/master...travis

but still issues with several tests failing. basically the problem is that the test expects an exception, but the exception is not thrown, or not thrown at the right time

**Comment by Guite** [comment]
Maybe it would help if we update phpunit to a newer version?

**Comment by craigh** [comment]
actually, if you look at the build logs, the version changes to newer versions automatically in the php7+ builds

**Comment by Guite** [comment]
Fixed by #3717
