### ISSUE TITLE
Users module should show the authentication method

### ISSUE THREAD

**Issue by rallek** [zikula/core#3704]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 139
| PHP Version       | 5.6
|feature request | yes

### Expected behavior
I the admin  is looking at the details of a user he should see how the user is registered (e.g. via Facebook)

### Actual behavior
No information is visible

**Comment by craigh** [comment]
I am not sure I agree with this request. The Users module is not responsible for authentication and therefore not technically "aware" of how the user is created. ZAuthModule and OAuth modules do list which method was used.

In order for user module to "know" this information, it would also need to fetch all the authentication modules and check everyone for that user id. This would need to be done independently for each user in the table (potentially thousands?)

**Comment by Guite** [comment]
Two ideas:

1. When the Users module creates a users it stores the authentication method in a user attribute:
```php
$user->setAttribute(UsersConstant::AUTHENTICATION_METHOD_ATTRIBUTE_KEY, $mapping->getMethod());
```
This could be used as an entrypoint I guess.

2. We could use a new event which sends a query around like "Who is responsible for this user id?". First listener/subscriber returning an answer stops propagation.

3. Both could/should be combined. So the new event should not only contain the user id, but carry the authentication method alias, too. This could be helpful if for example an alias changed or a user has been created programmatically (without using a "real" auth method).

**Comment by craigh** [comment]
I dislike both ideas.
#1 would only work for new users and break SOC
#2/3 would not be performant. Every user in the list would require a full scan of the mapping table PER USER.

**Comment by rallek** [comment]
what will be the way an admin is able to see how the user account is created or how the user is logged in?
In my case I do have a lot of older users (my church site). They log in some times a year and when something do not work they ask me for help. This is why I want to know what way they logged in.

**Comment by rallek** [comment]
The performance is not that important if there would be a button in the user view: "tell me what login method this user is using"

**Comment by Guite** [comment]
> #1 would only work for new users and break SOC

Maybe this was lost in translation: what I meant is this is already done by the Users module.

https://github.com/zikula/core/blob/master/src/system/UsersModule/Controller/RegistrationController.php#L162

**Comment by craigh** [comment]
> what will be the way an admin is able to see how the user account is created or how the user is logged in?

> ZAuthModule and OAuth modules do list which method was used

**Comment by craigh** [comment]
![Screen Shot 2020-03-10 at 7 20 21 PM](https://user-images.githubusercontent.com/350048/76367752-58db2f80-6304-11ea-84c5-07b807d0dbfa.png)
