### ISSUE TITLE
wrong login leads to bad results

### ISSUE THREAD

**Issue by rallek** [zikula/core#3705]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 239
| PHP Version       | 5.6

### Expected behavior
is a user logged in incorrectly via User Name and his facebook password he should get a info. E.g. ``the user is registered already via facebook``

### Actual behavior
error message:
````
[1] InvalidArgumentException: 
    at n/a
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/system/ZAuthModule/Api/PasswordApi.php line 86

    at Zikula\ZAuthModule\Api\PasswordApi->passwordsMatch('phantasy', '')
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/system/ZAuthModule/AuthenticationMethod/AbstractNativeAuthenticationMethod.php line 115

    at Zikula\ZAuthModule\AuthenticationMethod\AbstractNativeAuthenticationMethod->authenticateByField(array('either' => 'Ralf Köster', 'pass' => 'phantasy', 'rememberme' => false, 'uname' => 'Ralf Köster'), 'uname')
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/system/ZAuthModule/AuthenticationMethod/NativeEitherAuthenticationMethod.php line 75

    at Zikula\ZAuthModule\AuthenticationMethod\NativeEitherAuthenticationMethod->authenticate(array('either' => 'Ralf Köster', 'pass' => 'phantasy', 'rememberme' => false))
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/system/UsersModule/Controller/AccessController.php line 81

    at Zikula\UsersModule\Controller\AccessController->loginAction(object(Zikula_Request_Http))
        in  line 

    at call_user_func_array(array(object(AccessController), 'loginAction'), array(object(Zikula_Request_Http)))
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/index.php line 23
````

**Comment by rallek** [comment]
if a user tries to login with an unknown user he will just be redirected to home without showing anny message. After the next click the red information about the unknown user is displayed.

**Comment by craigh** [comment]
HOW TO REPRODUCE?

**Comment by rallek** [comment]
you may want to test it via my testsite: 2017.oldtimerigosnabrueck.de
## First try: 
Login with the username ``foo`` and a password you want e.g. ``bar``. 
http://2017.oldtimerigosnabrueck.de/login?authenticationMethod=native_either
I am pretty shure the user ``foo`` is not registered yet.
The result is nothing but seeing the start page in the same way than you are logged in correctly. 
Next you click the user account again (in my case "Benutzerkonto"). Than you see the red notices that the login was not successfull.
But I expected after sending the login a redirect to a page what is telling the user that his username is unknown or the password is incorrect (a kind of web standard).
## second try
register first via facebook at that site
http://2017.oldtimerigosnabrueck.de/register?authenticationMethod=facebook
right after registering logout again
Next try in to login with the user name you created for the facebook user by using this link:
http://2017.oldtimerigosnabrueck.de/login?authenticationMethod=native_either
The password can be choosen whatever you want.
In this case you do get the error message shown above in the first post.
The difference to the first try: The User is known but do not have a password.

Now clear enough?
Yesterday I was very tiered ;-)

**Comment by craigh** [comment]
the reason the error/success messages do not show until a secondary page viewing is because you do not show flash messages on your home template. You need to add a line like this:

https://github.com/zikula/core/blob/1.5/src/themes/BootstrapTheme/Resources/views/Body/3col_w_centerblock.html.twig#L13

that part of these issues is not a core problem, but your theme.

> But I expected after sending the login a redirect to a page what is telling the user that his username is unknown or the password is incorrect (a kind of web standard).

this would be true if the flash messages showed on your homepage

**Comment by craigh** [comment]
> is a user logged in incorrectly via User Name and his facebook password he should get a info. E.g. the user is registered already via facebook

I'm not sure this is a secure solution. Consider a worst case scenario: A (really dumb) hacker is trying to brute force login by guessing passwords. In this case, you want the hack to know as little as possible. So, unsuccessful login attempts should result in only that information ("The login was unsuccessful") Telling them the username or email or any part of the information is valid, tells them information (e.g. telling them that the account exists and works if you use Facebook). So I do not agree that this kind of message should be given to the user. @Guite thoughts on this?

**Comment by Guite** [comment]
> unsuccessful login attempts should result in only that information ("The login was unsuccessful")

Yes. Expose no details about why a login fails.

**Comment by craigh** [comment]
I pushed a change which I believe fixes the remaining problem with this ticket (and #3708). please re-test your sequence and see if the problem persists.

**Comment by rallek** [comment]
facebook not tested yet wrong user and wrong password are working fine. Will test facebook next but have to configure that first
