### ISSUE TITLE
problem with changing email address

### ISSUE THREAD

**Issue by rallek** [zikula/core#3707]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 239
| PHP Version       | 5.6

### Expected behavior
the email should be changed when using the change process in user account

### Actual behavior
I changed the email address of the admin account. The new email address did get the confirmation mail. I  used the link inside the mail. If I now change into the ZAuth module I can not see the change. There is still the old email address. I confirmed that in the database.

**Comment by Guite** [comment]
@craigh it looks like here https://github.com/zikula/core/blob/1.5/src/system/ZAuthModule/Controller/AccountController.php#L334 only the UserEntity is updated, while the AuthenticationMappingEntity is not.

For password changes the authentication mapping is updated instead: https://github.com/zikula/core/blob/1.5/src/system/ZAuthModule/Controller/AccountController.php#L375

**Comment by Guite** [comment]
Fixed in #3710
