### ISSUE TITLE
Remove all remaining inline JS and CSS

### ISSUE THREAD

**Issue by Guite** [zikula/core#3711]
Required for proper support of CSP (Content-Security-Policy).

- [x] VA modules
- [x] `Zikula` namespace
- [x] System modules
- [x] Generator + Routes

**Comment by craigh** [comment]
@Guite if this isn't already done, couldn't it be quite easy? and therefore a 3.0.0 task or 3.1 at least?

**Comment by Guite** [comment]
Note for myself: search not only for `<script` but also for `" on`.

**Comment by Guite** [comment]
- [x] VA modules
- [ ] `Zikula` namespace
- [ ] System modules
