### ISSUE TITLE
use simple-phpunit

### ISSUE THREAD

**Issue by craigh** [zikula/core#3719]
the master branch should be using simple-phpunit

https://symfony.com/doc/current/components/phpunit_bridge.html

instead of regular `./bin/phpunit`

this will require some changes in tests. currently some issues implementing this

https://github.com/zikula/core/compare/master...travis

so all tests fail with these changes still.

refs #3703

**Comment by Guite** [comment]
Currently Travis builds for 2.0 and master fail caused by the "self typehint" change by StyleCI. Interestingly they fail only for PHP 7. Guess simple-phpunit (or a more recent version of phpunit) would fix that.

**Comment by Guite** [comment]
I just rebased the branch and fixed the test issues.

**Comment by Guite** [comment]
https://github.com/zikula/core/commit/2a982c0567a994a9da5500c6687fca153cb406f3

Background: php errors that are no exceptions but warnings or notices are converted into an instance of `PHPUnit_Framework_Error`.
