### ISSUE TITLE
2.0.0-rc1 is shown as a stable release in the update checker

### ISSUE THREAD

**Issue by rallek** [zikula/core#3722]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci build 248
| PHP Version       | 5.6

### Expected behavior
No release candidate should show up in the update checker

Should be the message different if in 1.5 the stable 2.0.0 will show up in some days?
e.g: ``2.0.0 is also available`` and add a link where to find the difference between both branches (e.g. github wiki).

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/28731026-9c85384e-73d2-11e7-97bb-6ef573837494.png)

**Comment by Guite** [comment]
Maybe a CoreManager problem?

**Comment by Guite** [comment]
Fixed in #3727
