### ISSUE TITLE
The message of an account information recovery should be a bit more friendly

### ISSUE THREAD

**Issue by rallek** [zikula/core#3723]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci build 248
| PHP Version       | 5.6
| feature request|yes

### Expected behavior
The message of an account information recovery should be a bit more friendly. e.g.:
``A user with this email address do not exist at this site. Do you want to register?`` where ``register`` is a link to the register form.

### Actual behavior
``Unable to send email to the requested address. Please contact the system administrator for assistance.``
or
``Email Address not found. Please contact the system administrator for assistance.``

### Steps to reproduce
Try the account information recovery or password recovery with an unregistered email

**Comment by Guite** [comment]
`Do you want to register?` needs to consider a check for whether registration is enabled or not.

**Comment by craigh** [comment]
most sites simply declare "there is no user with this email address" or something. I'm not sure we need to do more than that.

**Comment by craigh** [comment]
technically, this is a Feature Request. moving.
