### ISSUE TITLE
emails not well formatted for HTML

### ISSUE THREAD

**Issue by rallek** [zikula/core#3724]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 248
| PHP Version       | 5.6
|release blocker|no

### Expected behavior
An email should be shown as html if the email software is configured to show emails in html (e.g. thunderbird)

### Actual behavior
The mail is shown textual formated and not in html
as an example the pending approval mail is showing up like this:
![grafik](https://user-images.githubusercontent.com/935250/28732026-95f8174a-73d6-11e7-9e8d-9fb2263b553c.png)

### Steps to reproduce
save the mail locally and look at the mail with an editor (e.g. notepad++) and compare it with another email showing correctly in HTML. Than you will see in our email the HTML surrounding is missing. e.G.:
````
...
<html lang=3D"de-US"> <head>  </head> <body> <div> ...
...
````

**Comment by Guite** [comment]
Both the welcome and email verification emails are shown fine here. Actually these are multipart emails containing both text and html variants. My mail client allows switching between both versions.

**Comment by Guite** [comment]
So maybe the problem isn't a problem or it is limited to the admin emails...

**Comment by rallek** [comment]
what are the standars for a well formated multipart email?

**Comment by rallek** [comment]
see this example: https://stackoverflow.com/questions/15024039/how-do-i-properly-format-this-multipart-email

In our emails is a link as html included but the complete html head and body construct is missing. If you take a text file with html link inside but nothing else than plain text and the browser is interpretating this as a link that browser is not working in a correct way. All other browsers may not show up with the link.

If your email client is showing the html in the expected way that does not mean that it is correct.

**Comment by rallek** [comment]
Might be this is helpfull: https://gist.github.com/tylermakin/d820f65eb3c9dd98d58721c7fb1939a8

**Comment by craigh** [comment]
this is not a blocker. It is currently scheduled for 1.5.1

**Comment by Guite** [comment]
Simple proposal for Mailer API:

```
if (false === strpos($htmlBody, '<html>') && false === strpos($htmlBody, '<body>')) {
    $htmlBody = '<html><body>' . $htmlBody . '</body></html>';
}
```

**Comment by craigh** [comment]
probably would be simpler just to add the proper tags to the template. but again - 1.5.1 please.

**Comment by Guite** [comment]
> to the template

It could affect many many templates. My approach is central and could therefore also help other modules...

**Comment by rallek** [comment]
additional information. 
If I create a multipart test mail in the MailerModule Setting the HTML is shown correctly without head/body construct. So it seams to be just a small issue.
But as stated in the issue description: This is not an important thing. 1.5.1 would be ok.

**Comment by rallek** [comment]
mmh, I guess we can close this. There is nothing wrong with the mail. I might be improved, but it is not an issue.

During my registration tests I got a lot of mails and I saw "some" html are showing up as expected. What makes me creating this issue is the missing clickable links. But now when I am looking into the raw email I can see there is no <a> Tag arround the url. So it depends on the mail client to interpretate the url as a link or not.

The only thing to improve would be to make the <a> tag around the url. That is that minor so I will close the issue. Feel free to reopen if that is enough for an ticket.
