### ISSUE TITLE
pending registration mail is not sent out if registration is moderated

### ISSUE THREAD

**Issue by rallek** [zikula/core#3725]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x5.0 ci 249
| PHP Version       | 5.6

### Expected behavior
a pending registration mail for the admin is sent out if a user registered but the registration process is moderated.

### Actual behavior
No mail is sent.
After approving by the admin the user do get that mail.

### Steps to reproduce

- setting:

![grafik](https://user-images.githubusercontent.com/935250/28744077-f3c6525a-7459-11e7-8838-76d8a6e06579.png)

- register via oauth/facebook or zauth (both tested)

Is there somewhere else a setting to sent these pending registration emails?

**Comment by craigh** [comment]
closed by #3787
