### ISSUE TITLE
Migrate Jenkins build to multibranch pipelines

### ISSUE THREAD

**Issue by Guite** [zikula/core#3735]
- [x] master
- [x] 2.0
- [x] 1.5

**Comment by Guite** [comment]
It is now working in the `jenkins-pipeline` branch, based on `master`.

![screen_1](https://user-images.githubusercontent.com/277531/28822652-5b5ca6d2-76ba-11e7-8916-f2e5bf454db3.png)
![screen_2](https://user-images.githubusercontent.com/277531/28822653-5b5e9a0a-76ba-11e7-9756-c22be50b966b.png)

**Comment by Guite** [comment]
I am going to continue after 1.5.0 and 2.0.0 are released.

**Comment by craigh** [comment]
do we need to worry about this with other branches? I don't think it will be worth the effort with 1.3 and 1.4 as I expect those builds to stop. 1.5 and 2.0 might be worth the time.

**Comment by Guite** [comment]
[xml_diffs.zip](https://github.com/zikula/core/files/1190382/xml_diffs.zip)

**Comment by Guite** [comment]
[13-14.diff.txt](https://github.com/zikula/core/files/1193179/13-14.diff.txt)
[14-15.diff.txt](https://github.com/zikula/core/files/1193178/14-15.diff.txt)
[15-master.diff.txt](https://github.com/zikula/core/files/1193180/15-master.diff.txt)

**Comment by craigh** [comment]
what are the purpose of these files. I don't understand.

**Comment by Guite** [comment]
They show the differences of the old `build.xml` file. These are helpful for backporting the new `Jenkinsfile` from `master` to earlier versions.

**Comment by Guite** [comment]
This is done.
