### ISSUE TITLE
Update Symfony in master branch

### ISSUE THREAD

**Issue by Guite** [zikula/core#3737]
After 2.0.0 is out, update Symfony from 3.3.5 to 3.3.6.

**Comment by craigh** [comment]
this will actually get merged to the 2.0 branch. which will branch from the release commit. Then bug fix PRs will merge to 1.5 -> 2.0 -> master

**Comment by craigh** [comment]
done

**Comment by Guite** [comment]
commit for reference: https://github.com/zikula/core/commit/5c08f6f5123e894cc54439f8723798475edd7f1f
