### ISSUE TITLE
[security] User should not be informed which credential is wrong.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3743]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 7.x

### Expected behavior
Information about wrong credentials, not specifying which one is wrong.

### Actual behavior
Incorrect password

### Steps to reproduce
Enter the wrong password.

**Comment by Guite** [comment]
> Zikula Version | 1.4.6

Can you please check whether this behaviour is still the same in 1.5? It may have been changed already.

**Comment by Kaik** [comment]
1.5 and 2.0 ok ``Incorrect login credentials. Login failed.`` So it is only in 1.4

**Comment by Guite** [comment]
Closing as there won't be a 1.4.7.
Update to 1.5.0 instead.
