### ISSUE TITLE
Hooks issues

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3745]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4, 1.5, 2.0
| PHP Version       | 7.x

## Mixed notify hooks displaying methods
This one does not work. https://github.com/zikula/core/blob/1.5/src/system/ZAuthModule/Resources/views/Authentication/UnameLogin.html.twig#L26

### Expected behavior
Modify user display hooks informed about object id and object url
### Actual behavior
Modify user display hooks not informed about object id and object url
### Steps to reproduce
... long story short
https://github.com/zikula/core/blob/master/src/system/UsersModule/Resources/views/UserAdministration/modify.html.twig#L50

**Comment by Kaik** [comment]
I will try all core modules that provide hook capabilities if hooks calls are working during Dizkus hooks refactor. So please do not close this ticket yet.

**Comment by craigh** [comment]
status on this? I don't understand the ticket at all.

**Comment by Guite** [comment]
> This one does not work.
Assigning `notifyDisplayHooks` and iterating over it is not possible. See also https://github.com/Guite/MostGenerator/commit/eb08e3b212394711284888e23ec726b194ca72a9

> not informed about object id and object url
urlObject parameter is missing on some calls

**Comment by craigh** [comment]
closed by #3790
