### ISSUE TITLE
Remove Foundation references

### ISSUE THREAD

**Issue by craigh** [zikula/core#3747]
We should consider removing all references to the so called "zikula foundation" as it is unclear if the organization ever truly existed. If we can find any documentation instantiating such an organization and its continued existence, then we should add this information to appropriate websites and or repositories. If not, requiring CLA agreements to such an organization is irresponsible at best and illegal at worst.

The question then becomes, what (if anything) is this to be replaced? "Zikula Project" ? Should this have any meaning? Research into other significant organizations would be appropriate.

**Comment by shefik** [comment]
If there is no legal entity name, then it should just be `Zikula`.

**Comment by rallek** [comment]
see https://euipo.europa.eu/eSearch/#basic/1+1+1+1/50+50+50+50/Zikula for Europe

**Comment by craigh** [comment]
https://trademarks.justia.com/850/90/zikula-85090330.html

**Comment by Kaik** [comment]
So L601A \: Notification of the need to renew an EUTM registration | 16/06/2017 means that someone received info about renewal... and it is due Jan 2018... looks like there was no such thing like "zikula foundation" there was only Postnuke Software Foundation registered in EU. That one @craigh posted looks like done 2 years later and hmm there is zikula fundation... and here is another one :) https://trademarks.justia.com/773/70/zikula-77370426.html

**Comment by craigh** [comment]
I've attempted to contact Vanessa L Haakenson via facebook

**Comment by Guite** [comment]
>  She is looking for the information she may have and will let me know.

did she?

**Comment by craigh** [comment]
no. she never did
