### ISSUE TITLE
Translation files are missing

### ISSUE THREAD

**Issue by rallek** [zikula/core#3748]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.x
| PHP Version       | 5.x

### Expected behavior
in ``app/resources`` should be a folder ``translations``

### Actual behavior
no translations are available

**Comment by craigh** [comment]
![screen shot 2017-08-05 at 1 41 48 pm](https://user-images.githubusercontent.com/350048/28997485-da4b1f60-79e3-11e7-8d75-87e1225584ce.png)

**Comment by craigh** [comment]
![screen shot 2017-08-05 at 1 43 10 pm](https://user-images.githubusercontent.com/350048/28997492-0cdcb268-79e4-11e7-84d9-def63fd77599.png)

**Comment by craigh** [comment]
They are present in the builds.

**Comment by rallek** [comment]
ups, looked at the wrong place. Sorry :-)
