### ISSUE TITLE
Menu in not standard language has problems

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3750]
| Q                 | A
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
Icons also in not standard language.
Correct handling of class 'current'.

### Actual behavior
Icons does not get shown in not standard language(for me english)
The link Home and a second link, that I have clicked have the class current.

### Steps to reproduce
Place 2 menus in the navbar with the same links and the same icons. Have a look to them with the standard language ( for me german) and another one ( for me english).

**Comment by craigh** [comment]
screenshots please.

**Comment by Portugao** [comment]
German view. Icons are there and only the link 'Seiten' has the class 'current'.

![menumodule_de](https://user-images.githubusercontent.com/493707/29018245-b323e782-7b5a-11e7-82fd-b005100b0dd7.jpg)

English view. No icons and both links, 'Home' and the current link 'Pages', have the class 'current'.

![menumodule_en](https://user-images.githubusercontent.com/493707/29018276-cdc7abf0-7b5a-11e7-8fa2-573cda90813d.jpg)

**Comment by Kaik** [comment]
Hi, are you 100% positive that both menus settings are same? Because German version has additional ``<i>`` inside ``<a>`` while English version does not have that additional ``<i>`` and since it is the only relevant difference I think that you might have used slightly different settings for both menus where in one of them you have added icon to li element and for the other one to anchor element.

**Comment by Portugao** [comment]
Yes, the settings of both menus are the same.

**Comment by rallek** [comment]
you may want first to delete (or move it somewhere) ``app/Resources/translation/routes.de.po`` and clear the zikula cache ``app/cache/prod`` or ``app/cache/dev``. See, if that helps. 
If not give us your settings of both menues so we can try it too.

**Comment by craigh** [comment]
> Place 2 menus in the navbar with the same links and the same icons. Have a look to them with the standard language ( for me german) and another one ( for me english).

this is not enough information to produce your screenshots. You obviously have at least one setting different in order to hide one menu and show the other. What else is required here?

**Comment by craigh** [comment]
> You obviously have at least one setting different 

I'll guess you've added a `_locale` filter?

any chance the `options` differ from this in either?

    {"template": "ZikulaMenuModule:Override:bootstrap_fontawesome.html.twig"}

**Comment by Portugao** [comment]
There is on standard top menu and its standard block in bootstrap theme.
You have to build another similar pair with a similar menu and block.
Have 2 items in the menu, 'Home' and 'Pages'. Give them icons per 'attributes' option.
For the standard block you set locale to your standard language, for the new one locale to another possible language, maybe 'german'; for me it is english.
If you call the site with standard language and the other language, you should get the issue. Or there is no issue and I have done something wrong, I think.
But we talk about a fresh install without any work on templates or anything else.
@rallek 
Deleting the german po files does not help.

**Comment by craigh** [comment]
@Portugao @rallek someone please attach german translation files

**Comment by rallek** [comment]
[translations.zip](https://github.com/zikula/core/files/1257810/translations.zip)
there is no route.de becase that causes several trouble in the past.
Also not everything is translated yet.

**Comment by craigh** [comment]
thank you @rallek for the files!

OK @Portugao I was able to test this and to get it to work. I also think I know what you did wrong. Admittedly, the MenuModule is a bit fragile and not very user friendly. It could use some love, but it can work with some persistence.

First create a new Root menu and **be sure to give it `childrenAttributes` = `{"class":"nav navbar-nav"}`** (this is where I believe you made your mistake).
![screen shot 2017-08-28 at 7 18 14 pm](https://user-images.githubusercontent.com/350048/29797603-29151836-8c26-11e7-9f63-e5aab0ec1e5c.png)

second create children. Be sure to give each child a `_route` and `attributes` = `{"icon":"fa fa-home"}` (please note that the `fa` is repeated, "fa fa-home" - this is another potential error spot)
![screen shot 2017-08-28 at 7 18 45 pm](https://user-images.githubusercontent.com/350048/29797616-400353c8-8c26-11e7-8289-660fd90330e0.png)

Create a new block, assigning it to the **topnav** position and creating a new `_locale` filter for your locale. (notice the `{"template": "ZikulaMenuModule:Override:bootstrap_fontawesome.html.twig"}` option!)
![screen shot 2017-08-28 at 7 25 03 pm](https://user-images.githubusercontent.com/350048/29797694-b451c4f8-8c26-11e7-8af1-f80eb9a7db30.png)

set a locale filter on your other existing block
![screen shot 2017-08-28 at 7 26 23 pm](https://user-images.githubusercontent.com/350048/29797716-cedfd076-8c26-11e7-85da-bb812023b4f5.png)

This will result in two menus appearing based on locale:
![screen shot 2017-08-28 at 7 16 39 pm](https://user-images.githubusercontent.com/350048/29797862-8d633330-8c27-11e7-9a81-444c6bbca1fc.png)
-----
![screen shot 2017-08-28 at 7 16 50 pm](https://user-images.githubusercontent.com/350048/29797863-8d650944-8c27-11e7-8dc6-be611e7160cc.png)
-----
Therefore, I am closing this ticket. best wishes!

**Comment by Portugao** [comment]
Thx a lot for looking at this.
The reason for my problems was the missing block option.
