### ISSUE TITLE
Is a composer.json file required in the distribution?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3773]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.0
| PHP Version       | 7.x
| OS                       | Windows

### Expected behavior
no errors

### Actual behavior
see https://github.com/Guite/MostGenerator/issues/1115

### Steps to reproduce

@Guite what do you think about this then?

**Comment by Guite** [comment]
I think we need to ask the Symfony guys about it.

**Comment by craigh** [comment]
here is one place where the project_dir is requested. 

https://github.com/zikula/core/blob/a8e18e19a4af42a691ef5fde1e853d67a7926ce1/src/system/ThemeModule/Resources/config/theme_engine.yml#L49

This isn't working properly atm and so assets are not combined in 2.0

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/cf7c4e10eebbc7341dbc1cb5aaf3991165f9fa68/src/system/RoutesModule/Helper/RouteDumperHelper.php#L67

https://github.com/zikula/core/blob/fe90e339826300b1e92d98ef2afd81f98e70408d/src/app/config/imagine.yml#L5

https://github.com/zikula/core/blob/fe90e339826300b1e92d98ef2afd81f98e70408d/src/app/config/imagine.yml#L10

and of course it is used throughout symfony

**Comment by craigh** [comment]
I think this actually works:

```
// add to \ZikulaKernel
public function getProjectDir()
{
    return dirname(__DIR__);
}
```

but the cache has to be cleared and that is why I thought it didn't work before. still uncertain.

**Comment by craigh** [comment]
https://github.com/zikula/core/commit/bb28a3a0bc7204812eb9a340fa546394a434f3b2

maybe solves this
