### ISSUE TITLE
edit category registry of a legacy module not possible

### ISSUE THREAD

**Issue by rallek** [zikula/core#3775]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0
| PHP Version       | 5.6

### Expected behavior
I am able to edit registry of legacy modules

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/29486234-42b17e70-84e1-11e7-9dc1-23f0e1d1a8c8.png)
Under ``select module`` no legacy modul is listed (e.g. News)

### Steps to reproduce
have 1.5.0 and latest News-master installed
go to categories an choose category registry
try to edit the registry for News

might be related to https://github.com/zikula-modules/News/issues/172

**Comment by rallek** [comment]
at a second installation the ``edit category registry`` is even not opened (same server same Zikula 1.5.0 but not my test site)

**Comment by rallek** [comment]
after deleting the routes.de.po I can open the ``edit category registry`` also in German language setting.
the app/cache/prod was deleted. But the issue itself is stil remaining.
Also if you are trying to add a new registry entry you can not select e.g. News or Content!

**Comment by craigh** [comment]
@Guite was this fixed by #3777
