### ISSUE TITLE
Category registry editing: entity selection builder seems broken

### ISSUE THREAD

**Issue by Guite** [zikula/core#3776]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0
| PHP Version       | any

### Expected behavior
Adding new category registries allows selecting an entity for a selected module.

### Actual behavior
Entity selection is empty.
Inspecing the ajax response shows that the field is empty there already.

### Steps to reproduce

1. Visit `/categories/registry/edit`
2. Choose a module at the `Select module` dropdown list
3. Notice no entity is available in the entity dropdown list

This happens for both new-style modules as well as legacy modules.

### Additional information
Possibly involved classes: `CategoryRegistryType`, `EntitySelectionBuilder`

**Comment by craigh** [comment]
this works properly for me on 2.0

![screen shot 2017-08-23 at 8 54 51 am](https://user-images.githubusercontent.com/350048/29616872-d2bb8e64-87e0-11e7-9a69-a85f975eb217.png)
![screen shot 2017-08-23 at 8 55 02 am](https://user-images.githubusercontent.com/350048/29616873-d45bc054-87e0-11e7-849f-67279be44ba2.png)
![screen shot 2017-08-23 at 8 55 13 am](https://user-images.githubusercontent.com/350048/29616875-d700b13e-87e0-11e7-867d-02389b9079a1.png)

**Comment by Guite** [comment]
On a 1.5 page from @rallek the dropdown list was empty. There were new-style modules installed (e.g. CmfCmfMediaModule) and also legacy modules (e.g. News), but none were included.

**Comment by craigh** [comment]
CmfCmfMediaModule is technically not fully a '2.0-type' module yet. It was written with the most current tech of its time to be sure (1.4.3 I think) but many APIs were yet to be fully implemented or invented, so It is using much legacy code still. I am hoping @cmfcmf is updating it 😄

**Comment by Guite** [comment]
It uses the categorizable capability though. So from the Categories module's point of view it is "new-style".
