### ISSUE TITLE
Profile and Legal translation not working propperly during registration

### ISSUE THREAD

**Issue by rallek** [zikula/core#3779]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0
| PHP Version       | 5.6

### Expected behavior
translated lables during registration

### Actual behavior
labels are still in english

### Steps to reproduce
have a German translation of profile and a German language setting
[profile-module.zip](https://github.com/zikula/core/files/1237006/profile-module.zip)
try to register. There you will see this:
![grafik](https://user-images.githubusercontent.com/935250/29493995-9532b360-85a1-11e7-8818-9ad33cd6fd81.png)
after registration you can go to your profile. There are the same labels in use:
![grafik](https://user-images.githubusercontent.com/935250/29494000-b977dd4a-85a1-11e7-9cf8-ff4afd4fa98b.png)
Not shure if it is core or profile module issue.

I do have another issue with profile translation. this I will open at the profile module and reference it here.

**Comment by rallek** [comment]
For real name I configured the profile as following:
![grafik](https://user-images.githubusercontent.com/935250/29494086-3ba17c8a-85a3-11e7-9cb9-bf27330ce3eb.png)
And for Avatar:
![grafik](https://user-images.githubusercontent.com/935250/29494094-610e22fc-85a3-11e7-8bfc-c901bb037aa5.png)

**Comment by rallek** [comment]
Will now translate the English the same as the German so it will work for my German speaking site.
I observe these issues now because I am doing a klick documentation for my unexerienced users.

**Comment by rallek** [comment]
Same Problem occurs in legal-modules:
![grafik](https://user-images.githubusercontent.com/935250/29494175-a9e90d74-85a4-11e7-953c-42442656a155.png)
Only partly translated during registration.
[legal-module.zip](https://github.com/zikula/core/files/1237013/legal-module.zip)

**Comment by craigh** [comment]
this may be because the translations are not extracted properly during the build process. I think the extractor may only extract from installed bundles and profile and legal are not installed during the build. Keys are _are_ working may work because they are common with another module possibly.

**Comment by craigh** [comment]
refs #3517 because installing modules during the build would require a CLI command for doing so

**Comment by craigh** [comment]
@rallek you can test my theory by installing both Profile and Legal and then extracting the translations with this command:

    php -dmemory_limit=2G app/console translation:extract en --output-format=po --output-dir=app/Resources/translations --enable-extractor=jms_i18n_routing --dir=system --dir=lib/Zikula/Bundle --dir=module

but this will extract everything all to one location (in `en`) then you must translate of course.

**Comment by craigh** [comment]
now that I am looking at the original translation command in the build, I don't think it will every extract the translations in Profile or Legal since they are located in `modules`. (the extractor only pulls from `system` and `lib/Zikula/Bundle`) So maybe this is more of an issue with manually extracting both Profile and Legal before releasing them...

**Comment by craigh** [comment]
This theory could be tested by installing Profile and then running the command

    php app/console translation:extract en --bundle=ZikulaProfileModule --output-format=po

this will extract all the translations to Profile's _own_ `Resources/translations` dir and then you can translate **there**. In other words, the translations for profile live in profile - not in the core.

same for legal.

If the problem still persists, then it would seem that the domain is not loaded properly for modules when they are used as hooks. This was a problem in the pre-symfony days too.

**Comment by rallek** [comment]
Found out today I have to do something here!
I recreated the translation by: 
````php app/console translation:extract en --bundle=ZikulaProfileModule --output-format=po````
A lot of new strings have to be translated. Two small issues are left:
The text ``Once used, do not change the ID value or all profiles will lose their connection!`` is not available in the translation po file and ``Weight`` is translated in po file but not in the template. ``app/cache/prod`` is deleted.

![grafik](https://user-images.githubusercontent.com/935250/33515229-8792793c-d760-11e7-8476-9f049f60279d.png)

**Comment by Guite** [comment]
@rallek fixed in https://github.com/zikula-modules/Profile/commit/e2d2eb8e325b2a5e028acc56cba2917f8d7af90d

But this is not related to this issue...

**Comment by rallek** [comment]
I know. I will check out the registration next. But found two other very small issues I want to report first

**Comment by rallek** [comment]
Now all strings are translated but during registration I do not see the translation:
![grafik](https://user-images.githubusercontent.com/935250/33515495-cc99ecd2-d764-11e7-8c2f-1a01d5ca92a9.png)
Allways the englisch label is used as you can see here:
![grafik](https://user-images.githubusercontent.com/935250/33515511-002bf478-d765-11e7-852a-030b9c013b4b.png)
This is not coming from the translated po files but from the created field.

**Comment by Guite** [comment]
> it would seem that the domain is not loaded properly for modules when they are used as hooks

Seems hook providers need a similar domain setting functionality as controllers.

**Comment by Guite** [comment]
Legal: fixed in Legal 3.1.2 https://github.com/zikula-modules/Legal/releases/tag/3.1.2 which is included in Zikula 1.5.4 https://github.com/zikula/core/commit/53f1eec4a5aa7f865cb096c0264d87b5b3af37b7

Profile: not fixed, but should be treated in a Profile ticket https://github.com/zikula-modules/Profile/issues/99

Closing.
