### ISSUE TITLE
correct db driver value to pgsql

### ISSUE THREAD

**Issue by craigh** [zikula/core#3783]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.1.0

### Feature Request

~On Core installation, allow the user to set the DB driver (e.g. mysql, pgsql, etc) from a ChoiceType as part of their initial DB set up.~

correct the value of the choice in the installer from `postgres` to `pgsql`

refs #2036

**Comment by craigh** [comment]
FTR - this can be set manually by editing `parameters.yml` before proceeding with install for now.

**Comment by Guite** [comment]
Isn't this already available at https://github.com/zikula/core/blob/master/src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/DbCredsType.php#L31 ?

**Comment by craigh** [comment]
yes, I suppose it is. 😀 

that is good news I guess, but the `postgres` value is incorrect I think - it should be `pgsql`

**Comment by Guite** [comment]
Changelog?

**Comment by craigh** [comment]
done in https://github.com/zikula/core/commit/8888c9fa5c99c2cd2c111b1bbb4ae0a93d296524

**Comment by Guite** [comment]
Changelog entry was lost during upmerge to 2.x

**Comment by craigh** [comment]
fixed in 2.0 will merge up next time
