### ISSUE TITLE
Change DBAL charset setting

### ISSUE THREAD

**Issue by craigh** [zikula/core#3784]
MySQL's utf8 character set does not support 4-byte unicode characters, and strings containing them will be truncated. Instead `utf8mb4` should be used.

Newly installed extensions already have `utf8mb4_unicode_ci` set. So new tables are already using it.

Of course, migration still remains to be approached: existing tables need to be updated. Because encoding and collation are not only set for the database, but also for each table and alphanumeric column.

- charset: utf8mb4
- collate: utf8mb4_unicode_ci

Resources:

- https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5
- https://mathiasbynens.be/notes/mysql-utf8mb4
- https://florian.ec/blog/mysql-doctrine-utf8/

**Comment by craigh** [comment]
@Guite opinions?

**Comment by shefik** [comment]
I agree changing to `utf8mb4` by default.

**Comment by Guite** [comment]
Any recoding required for existing installations?

**Comment by craigh** [comment]
> Any recoding required for existing installations?

I suppose the value could be updated on upgrade.

I'm just wondering if this should be placed in 2.0.1 or 2.1.0 milestone instead

**Comment by Guite** [comment]
The question was about whether existing tables need to be updated. Because encoding and collation are not only set for the database, but also for each table and alphanumeric column.

**Comment by shefik** [comment]
https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5

**Comment by Guite** [comment]
IMO 2.1.0 then.

**Comment by craigh** [comment]
if full db migration is required I don't think this should be in 1.5.1 but 2.1.0

**Comment by craigh** [comment]
perhaps the settings could be changed for the installer, but leave the upgrader changes until 2.1.0

**Comment by Guite** [comment]
> perhaps the settings could be changed for the installer, but leave the upgrader changes until 2.1.0

I prefer doing both for 2.1.0 to avoid different behaviours in the same version (< 2.1.0).

**Comment by Guite** [comment]
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by Guite** [comment]
refs #3104

**Comment by craigh** [comment]
@Guite maybe 3.0?

**Comment by Guite** [comment]
Just saw that the tables of a MOST module I installed about 10 days ago have `utf8mb4_unicode_ci` set. So maybe new tables are already using it. Of course, the migration topic still remains to be approached.
