### ISSUE TITLE
JavaScript Alert When Updating Categories

### ISSUE THREAD

**Issue by shefik** [zikula/core#3789]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0
| PHP Version       | 5.x

### Expected behavior

There should not be a JavaScript alert, if updating a category is successful. 

### Actual behavior

When updating categories at `/admin/category/list`, anytime a category is updated, a JavaScript alert appears with a 200 success code.

### Steps to reproduce

Go to `/admin/category/list`.

**Comment by Guite** [comment]
Unable to replicate. Closing.
