### ISSUE TITLE
Upgrade from Zikula 1.5 to 2.0 not worked

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3794]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5
| PHP Version       | 7.0

### Expected behavior

Hello Developers,

I have learned that Zikula 2.0 is out there and would like to upgrade from Zikula 1.5 to 2.0. But there are complications.

### Actual behavior

I have the new files from Github and uploaded them to the server. After that I had to update the composer from the root directory. Then I went to the browser and wanted to upgrade the upgrade under `/upgrade`.

But unfortunately this error is displayed.

    Fatal error: Class 'ZikulaKernel' not found in /xxxxxxxxxxxxxxxxxx/zikula15.wpzweinull.ch/src/lib/bootstrap.php on line 42

How can fix the problem?

Thanks in advance.

### Steps to reproduce

To reproduce the error, you need a github version of Zikula 1.5 and then have to upload the new files and directories of Zikula 2.0.

Then make the upgrade in the browser. Before updating the composer. These were my steps and the procedure.

**Comment by craigh** [comment]
you should not be running composer at all. please follow the [upgrade instructions](https://github.com/zikula/core/blob/master/UPGRADE-2.0.md) using a [proper package](https://github.com/zikula/core/releases/tag/2.0.0)
![screen shot 2017-08-30 at 6 15 46 am](https://user-images.githubusercontent.com/350048/29867794-b791e786-8d4a-11e7-9ec7-1f0e8c58b192.png)

**Comment by craigh** [comment]
@AlexL777 please update

**Comment by AlexL777** [comment]
Hi,

I wanted to reinstall Zikula 2.0 from scratch and it worked very well with PHP 7.0 / 7.1. However, I have other issues, such as the last version of the Dizkus Forum Modules. The issue I have already created in the respective repo and were on feedback.

Thank you.
