### ISSUE TITLE
Upgrade general issues

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3799]
I have done lots of upgrades. Zikula 1.3 should be upgraded in order so if you have 1.3.6 you should go thru all stages what I see is that some 1.3 dbs have some important module vars missing. Apart from that dbs especially big old ones tend to have corrupted data - that is why I will place here some of the things I check before upgrade.
1. Basics
- theme - s:20:"ZikulaBootstrapTheme";
- locale variables - set to en eng add missing 
- basically ZConfig  - check with version you upgrading to:
2. some 1.3 dbs might contain non existing or duplicate entries in tables
- object_attributies
- group_membership
- module_vars
I have sql's that can fix it somewhere.. 
3. Modules table may contain illegal data or missing data for example capabilities etc... 
4. If there is theme_change set to 1 upgrade will look for theme specified users settings not global theme better set to 0

I do install Zikula before upgrade (to check basic stuff like db connections and be sure environment is working) then remove db content, remove cache, remove config/dynamic/generated.yml and part about zikula version in custom_parameters. Then upgrade.

SQL's PhpMyAdmin
```
// duplicated data in obj table
// check
SELECT o1.`id`, o1.`attribute_name`, o1.`object_type`, o1.`object_id`, o1.`value`
FROM `objectdata_attributes` AS o1
INNER JOIN (SELECT `id`, `attribute_name`, `object_type`, `object_id`
               FROM  `objectdata_attributes`
               GROUP BY `attribute_name`, `object_type`, `object_id`
               HAVING COUNT(*) > 1) AS dup
           ON o1.`attribute_name` = dup.`attribute_name`
           AND o1.`object_type` = dup.`object_type`
           AND o1.`object_id` = dup.`object_id`  
ORDER BY `o1`.`object_id` ASC, `o1`.`value` ASC
```
```
// remove deleted users data
//check
SELECT `objectdata_attributes`.* FROM `objectdata_attributes` LEFT JOIN `users` ON `users`.`uid` = `objectdata_attributes`.`object_id` WHERE `users`.`uid` IS NULL AND `objectdata_attributes`.`object_type` LIKE 'users'
```
```
// duplicated entries in group membership table
// check 
SELECT `gid`, `uid`, COUNT(*) FROM `group_membership` GROUP BY `gid`, `uid` HAVING COUNT(*) > 1
```
I have created this issue as a replacement for forum so we can discuss upgrade problems.

**Comment by KratorD** [comment]
Great job, I hope that this can be fixed in next releases.
I have others errors how this: [Old modules are duplicates in the upgrade](https://github.com/zikula-modules/Profile/issues/91).

Thanks.

**Comment by craigh** [comment]
while this is interesting and probably useful, I do not see what can be done with this ticket. What do you hope will be done as a result of this ticket? Data corruption is not something the core can fix.

**Comment by Kaik** [comment]
I know, well ticket needs to be closed that is for sure, I'm going to do that now. If you find this useful enuff to be placed somewhere else like docs or wiki or whatever I can move it there... actually it does not have to be moved at all, closed ticket still can be mentioned in docs for additional information, and more info can be still added to this ticket. I wasn't hoping anything like additional core features or something I just wanted to share some information that might be helpful for others and this is the only place I could do that.
