### ISSUE TITLE
Unable to get subcategories

### ISSUE THREAD

**Issue by shefik** [zikula/core#3811]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.1
| PHP Version       | 5.6

### Expected behavior

The subcategories should be populated in the array.

### Actual behavior

The array is empty. This worked in Zikula 1.5.0, but is now broken in 1.5.1.

### Steps to reproduce

Use this line of code:

```\ServiceUtil::get('zikula_categories_module.api.category')->getSubCategories($cid);```

**Comment by craigh** [comment]
[several changes](https://github.com/zikula/core/commits/1.5/src/system/CategoriesModule/Api/CategoryApi.php) have been made to the CategoriesApi since this ticket. Please test with a current release and report whether the problem still exists.

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/commit/5c0fbb16276c5760b422f658f2e5ef9685b9eb8f
