### ISSUE TITLE
Categories Error: The route "zikulacategoriesmodule_node_contextmenu" does not exist.

### ISSUE THREAD

**Issue by shefik** [zikula/core#3814]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.1
| PHP Version       | 5.6

### Expected behavior

Right clicking opens the contextual menu to Edit a category. Clicking the "Edit link should allow you to actually Edit a category.

### Actual behavior

JavaScript error: 

```Error: The route "zikulacategoriesmodule_node_contextmenu" does not exist.```

### Steps to reproduce

Attempt to edit a category at `/categories/admin/category/list`.

**Comment by craigh** [comment]
prob dup #3807
