### ISSUE TITLE
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Zikula\NewsModule\Listener\ThirdPartyListene

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3816]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.1
| PHP Version       | 7.1

### Expected behavior

With the Zikula 2.0.1 errors come in the news administration. I have Zikula 2.0.1 by the update of v2.0.0 and have installed the compatible news module version.

But some things do not work. The hooks can be added already times.
### Actual behavior

The following errors are displayed.

`Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Zikula\NewsModule\Listener\ThirdPartyListener' does not have a method 'getEditorHelpers' in /xxxxxxxxxxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php on line 212`

### Steps to reproduce

You install the new news module version for Zikula 2.0.1 and you will find the above errors.

Maybe you can help me solve the problem. Thanks in advance.

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/News/commit/323b64cac047e7ccdf92a85a7d7678b4360d8336
