### ISSUE TITLE
Can not log in to the Backend - Zikula 2.0.1 with SSL/https

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3818]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.1
| PHP Version       | 7.1

### Expected behavior

I have blocked myself from the Zikula 2.0.1 backend, because this CMS is extremely complicated. Since I had probably saving the files for the database activated or something.

My website under https://zikula.wpzweinull.ch also not available. But in the browser I still have the path to the login, but login is no longer.

I could make a screenshot. It looks like this.

![zikula-2-0-1-login-error](https://user-images.githubusercontent.com/7885632/30740398-198715c6-9f91-11e7-9b0c-6de3ee5b66c7.jpg)

Active are PHP 7.1, Managed Server, MySQL 5.7, Zikula 2.0.1.

NewsModule as startpage to activate, worked out in the settings, but I can not test it yet if the website is not accessible.

Can you help me, as I can change or fix the MySQL database.

Thanks in advance.

P.S. Error is "session object destruction failed .... path /tmp/phpfpmsessions"

**Comment by craigh** [comment]
There is no released version of News that is Core-2.0 compatible. you are using non-production software. This is not supported.
