### ISSUE TITLE
Keep Getting Logged Out

### ISSUE THREAD

**Issue by shefik** [zikula/core#3821]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5
| PHP Version       | 5.6

### Expected behavior

I should stay logged in.

### Actual behavior

I am logged out of the after after the set amount of minutes of inactivity.

### Steps to reproduce

Click the checkbox to stay logged in. Set your set to "Medium" at `/security-center/config/config`.

**Comment by craigh** [comment]
I cannot confirm this to be true. I have the following settings:
![screen shot 2017-12-29 at 10 26 42 am](https://user-images.githubusercontent.com/350048/34440384-cfea63de-ec82-11e7-8b5d-bb2514600199.png)

After four minutes I reload the main page and am still logged in.

remember if you are using file-based sessions (default) then deleting cache will delete your session files and log you out. I suspect this is your problem.

**Comment by rallek** [comment]
I do have my settings store session in database. If I delete the cache I am logged out too. Is that normal?

In the past the behavior was different (not logged out). But I do not remember since when this behavior changed.

**Comment by rallek** [comment]
I now looked into my database. The last entry in sessions_info is 2017-11-05. I can reproduce my upgrade to zk1.5.3 happened at 2017-11-06. I will open a new ticket for that.
