### ISSUE TITLE
Allow Search URLs to be Sharable

### ISSUE THREAD

**Issue by shefik** [zikula/core#3831]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.x
| PHP Version       | 5.6

### Expected behavior

The result of the search URL should be able to be shared. A user should be able to copy and paste a URL and have it directly return results from the GET request.

### Actual behavior

The result of the search returns a URL contains the parameter `zikulasearchmodule_search[_token]`, which means that it is only valid for the current user. Therefore, the token via GET request should not be required in the form validation.

### Steps to reproduce

Search any queries.

**Comment by Guite** [comment]
This can be achieved by setting `csrf_protection` to `false` in the search form options like described at the bottom of http://symfony.com/doc/current/form/csrf_protection.html .
Could you please submit a PR for this?

**Comment by shefik** [comment]
Where are the search form options located?

**Comment by Guite** [comment]
https://github.com/zikula/core/blob/1.5/src/system/SearchModule/Form/Type/SearchType.php#L83

**Comment by Guite** [comment]
Added new PR in #3854
