### ISSUE TITLE
[WAMP] Module list sql error

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3842]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.2
| PHP Version       | 5.6.25
| Mysql Version     | 5.7.14

### Expected behavior
No error when browsing extension list

### Actual behavior
SQL error when extension list requested

> An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT m0_.id AS id_0, m0_.name AS name_1, m0_.type AS type_2, m0_.displayname AS displayname_3, m0_.url AS url_4, m0_.description AS description_5, m0_.directory AS directory_6, m0_.version AS version_7, m0_.capabilities AS capabilities_8, m0_.state AS state_9, m0_.securityschema AS securityschema_10, m0_.core_min AS core_min_11, m0_.core_max AS core_max_12 FROM modules m0_) dctrn_result ORDER BY displayname_3 ASC LIMIT 40 OFFSET 0': SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.displayname_3' which is not in SELECT list; this is incompatible with DISTINCT

### Steps to reproduce
Windows 10 WAMP server fresh install prod env log in as admin and go to extension list.

**Comment by Kaik** [comment]
I have found that it is common problem with few solutions https://github.com/doctrine/doctrine2/issues/5622
Should we care about it?

**Comment by craigh** [comment]
This is a vendor issue. not zikula
