### ISSUE TITLE
Tests Failing in build

### ISSUE THREAD

**Issue by craigh** [zikula/core#3855]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0
| PHP Version       | 7.x

### Expected behavior
All tests pass

### Actual behavior
https://travis-ci.org/zikula/core/jobs/303400972

> Zikula\CategoriesModule\Tests\Form\DataTransformer\CategoriesCollectionTransformerTest::testTransformSingleAssociation
Symfony\Component\Debug\Exception\ContextErrorException: Warning: Declaration of Mock_CategoryEntity_a5b32490::setParent(Mock_CategoryEntity_a5b32490 $parent = NULL) should be compatible with Zikula\CategoriesModule\Entity\CategoryEntity::setParent(Zikula\CategoriesModule\Entity\CategoryEntity $parent = NULL)
/home/travis/build/zikula/core/src/system/CategoriesModule/Tests/Form/DataTransformer/CategoriesCollectionTransformerTest.php:43

**Comment by Guite** [comment]
Probably fixed by https://github.com/zikula/core/commit/f43976d964366c1d36052d829efed7f8b107cc89  (just waiting for Travis to verify).

Background is that phpunit uses reflection, details can be read at https://github.com/sebastianbergmann/phpunit-mock-objects/issues/107
