### ISSUE TITLE
Users Module can not sent mail

### ISSUE THREAD

**Issue by rallek** [zikula/core#3863]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.3
| PHP Version       | 5.6

### Expected behavior
Via ``Find/Mail/Delete Users`` a mail should be sent to a user

### Actual behavior
mail is not send

### Steps to reproduce
![grafik](https://user-images.githubusercontent.com/935250/33288264-f2df0e24-d3bb-11e7-82e9-89bd779ad8e2.png)

leads to 
![grafik](https://user-images.githubusercontent.com/935250/33288315-13cbd2b6-d3bc-11e7-834e-1f68ec63f5e7.png)

**Comment by craigh** [comment]
this is likely a server configuration or mail configuration problem. not zikula. Zikula uses swift mailer which is a well-tested third party vendor.

**Comment by rallek** [comment]
I am on shared service. The test mail is running well. What can I do to make it running?

**Comment by Kaik** [comment]
I just checked and it does not send mail... localhost, 1.5.2 same setup/install where Dizkus is sending, well at least profiler is saying mail was sent.

**Comment by Guite** [comment]
This looks like a logical issue in `MailHelper#mailUsers()`:

In https://github.com/zikula/core/blob/1.5/src/system/UsersModule/Helper/MailHelper.php#L194 `$mailSent` is initialised with `false`. Afterwards there are several assignments like `$mailSent = $mailSent && ...`. So `$mailSent` never becomes `true`.

@craigh please confirm

**Comment by Guite** [comment]
Proposed fix: initialise the variable with `true` in line 194.

**Comment by Guite** [comment]
Fixed by #3865

**Comment by Kaik** [comment]
That $mailSent marker why is it needed at all?

**Comment by Guite** [comment]
It just determines if the _entire_ operation worked or not. Having a more comprehensive feedback (like which mails to which users were sent correctly and which not) would be a new feature.
