### ISSUE TITLE
Hook problems while configure

### ISSUE THREAD

**Issue by rallek** [zikula/core#3866]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.3
| PHP Version       | 5.6

### Expected behavior
Hooks should be configurable always

#### Problem one
e.g. in Scribite you may want to click on ``hooks`` to configure the hook system. But this is leading to an error message:
![grafik](https://user-images.githubusercontent.com/935250/33519492-f5db9350-d7a7-11e7-96b1-56604ea6aa5c.png)

#### Problem two
all other modules where clicking on hooks do not bring this error you can not drop a new hook to the module. 

#### Problem one
go to scribite backend and click on ``hooks``. I do have another simple fresh generated MOST module with the same behavior. Therfor I post it at the core.

#### Problem two
If you drop a hook to the module the frame is sticking somewhere but it is not creating the hook. After dropping it is not movable anymore. Normally the frame is flipping back to its position and the hook is registered. But that do not work.

**Comment by Guite** [comment]
fixed in https://github.com/zikula/core/commit/04c73213d983e4a44ceaeea2ea5d786af7190b0b

**Comment by rallek** [comment]
Not everything is solved. For probhlem two I do have now the output from the web developer console:
````Error: The route "zikula_hook_hook_togglesubscribeareastatus" does not exist.````

**Comment by Guite** [comment]
Did you try deleting `web/js/` ?

**Comment by rallek** [comment]
of course not :-/
That was it.
