### ISSUE TITLE
Consider simpler injection of tagged services

### ISSUE THREAD

**Issue by Guite** [zikula/core#3872]
Check if http://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services can be used for our compiler passes.

**Comment by craigh** [comment]
I thought there was another ticket about implementing auto wiring, but couldn't find it. this article may be helpful.
https://www.tomasvotruba.cz/blog/2018/12/27/how-to-convert-all-your-symfony-service-configs-to-autodiscovery/

**Comment by Guite** [comment]
Closed in favour of #3940
