### ISSUE TITLE
Bad Page when signing in as admin with site disabled

### ISSUE THREAD

**Issue by marcpare4** [zikula/core#3873]
I am still working with my new instance of Zikula 2.0.4. I have disabled the site, and, when I log in as admin I get the following page (link included). When I click on "Home" I am then taken back to the correctly drawn landing page for the site (in admin mode). http://boydmcdonald.com/files/Screenshot_after_logging_in_as_admin.png  I seem to remember having seen this happen with other new instances of Zikula in the 1.4 and 1.5 family. For some reason, the page that you are taken to after logging in is now adopting the designated theme parameters.
| Zikula Version    | 2.0.4
| PHP Version       | 5.6.32

**Comment by marcpare4** [comment]
Just to add, it looks like this only happens on the firs loggin when the theme is not cached (I am guessing). When I logged in a second time, the page drew correctly.

**Comment by Guite** [comment]
> I have debug set to true, and when trying to access some of the admin pages (for example "extensions") I am getting the following error message: " (1/1) OutOfMemoryException
Error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 476737 bytes)  in Merger.php (line 299)" Any ideas on this? Zikula 2.0.4

> the asset combination runs out of memory... either increase your memory or set `zikula_asset_manager.combine` to `false` in `app/custom_parameters.yml`

**Comment by Guite** [comment]
Problem solved.
