### ISSUE TITLE
Missing remove action for modules with missing files

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3877]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.x, 1.5.x, 2.0.0
| PHP Version       | NA

### Expected behavior
Ability to delete module from extensions list when files are missing

### Actual behavior
Module is listed with "missing files" unable to remove from extensions list

### Steps to reproduce
Upgrade from 1.3.x with modules that are not supported in 1.4, 1.5, 2.0 etc..
I have found that this action "disappeared" between 1.3 and 1.4 I think it disappeared for a reason that you cannot fully delete module if files are missing (module tables) but still having lots of modules that probably will never be refactored with missing files status is kind of annoying... I know I can remove them manually from the modules table but still, this is kind of risky behavior and since modules table belongs to Extensions I think this kind of "cleaning" feature should be available.

This is more feature request than a bug perfect solution would be to have separate remove action with information about consequences (what is removed, what is not and that there will be no way to upgrade this module in the future) if not at least mention in upgrade procedure that unused/unsupported modules need to be removed before the upgrade or manually deleted from modules table.

**Comment by craigh** [comment]
https://github.com/zikula/core/issues/1278

This idea was discussed and rejected some time ago (2013).

not sure how I feel about it now.

**Comment by craigh** [comment]
after discussion with @Guite we have decided to not implement this request.
