### ISSUE TITLE
image lightbox is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#3879]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.4
| PHP Version       | 5.6

### Expected behavior
a MOST generated module should use the magnific popup lightbox of the core

### Actual behavior
clicking on an image is not using the magnific popup lightbox anymore. In 1.5.3 it was working.
if you look into the source code of the browser magnific popup is included.

### Steps to reproduce
use a module created by most or add the ``class="image-link"`` to the link around the image. Than click on the image and a lightbox should be used.

**Comment by Guite** [comment]
This is not related in any way to the core. The core just provides the library, not more.

**Comment by rallek** [comment]
But why it was working in 1.5.3 and not in 1.5.4? The only thing I changed is the core!

**Comment by rallek** [comment]
sorry, you are right. It is MOST related.
