### ISSUE TITLE
sessions are not stored in database anymore (since 1.5.3)

### ISSUE THREAD

**Issue by rallek** [zikula/core#3881]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.4
| PHP Version       | 5.6

### Expected behavior
session should be visible in database session_info table if the following settings are done:
![grafik](https://user-images.githubusercontent.com/935250/34447197-f75cd050-ece1-11e7-9300-f93aa2787501.png)

### Actual behavior
last entry in database is from 2017-11-05. at 2017-11-06 I updated to zk 1.5.3!
I deleted my cache for several testings. Since some weeks I recognized I am always logged out. That was new to me. Now I saw #3821 where I saw the answer.

### Steps to reproduce
Do the same settings as in my installation and delete the cache. Immidiately you will be logged out.
Or look into your database when you last time have been logged.

**Comment by Portugao** [comment]
Sorry, Cannot reproduce.
I just tested with 1.5.4 after an update from 1.5.2. and Php 5.6.

**Comment by rallek** [comment]
Any differences in the settings?

**Comment by Portugao** [comment]
No

**Comment by rallek** [comment]
I changed my settings to files and changed it back to database. Now it is working again. Strange! Same thing at two sites.
