### ISSUE TITLE
Orphan Block Properties Might Exist

### ISSUE THREAD

**Issue by shefik** [zikula/core#3892]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.4
| PHP Version       | 5.6

### Expected behavior

When updating a block, all properties should be updated, and any non-exisiting properties should be removed

### Actual behavior

Orphan block properties may exist.

### Steps to reproduce

Create a new block with custom properties. Then, modify the code of your block to remove an existing property and add a new one. Once you update your block, all new properties get updated as expected. However, the previous property you removed in the new version of the block still remains
in the database table.

**Comment by Guite** [comment]
Which block do you refer to? Concrete use case? New style or legacy system?

**Comment by shefik** [comment]
New style.

**Comment by Guite** [comment]
In new style implementations the properties are not defined inside the block class, but in the referenced form type class. Please elaborate: concrete use case? Expected vs. actual. Feel free to add/share code snippets.

**Comment by Guite** [comment]
ping @shefik

**Comment by Guite** [comment]
ping @shefik
