### ISSUE TITLE
JavaScript Console Error - zikulacategoriesmodule_node_contextmenu Not Found

### ISSUE THREAD

**Issue by shefik** [zikula/core#3893]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.5
| PHP Version       | 5.6

### Expected behavior

The context menu for categories should appear when clicking "Edit" at `/categories/admin/category/list`.

### Actual behavior

The JavaScript console throws the error `Uncaught Error: The route "zikulacategoriesmodule_node_contextmenu" does not exist.`.

### Steps to reproduce

Attempt to add or edit a category at `/categories/admin/category/list`.

**Comment by Guite** [comment]
Did you try deleting `web/js/`? See also #3804

**Comment by shefik** [comment]
Deleting the file worked.
