### ISSUE TITLE
Search "Extra" Column is Too Small

### ISSUE THREAD

**Issue by shefik** [zikula/core#3900]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.6
| PHP Version       | 7

### Expected behavior

In the table `search_result`, the column `extra` is set to `varchar(1000)`. The value is too low. Recommend to change to `longtext`. Attempting to save associated meta data to use within search results.

### Actual behavior

Serialized may get corrupted, since the field if limited to 1000 characters.

### Steps to reproduce

Add serialized extra data.

**Comment by Guite** [comment]
@shefik please test #3901 and report if it fixes the problem

**Comment by shefik** [comment]
@guite I see that you increased the`varchar` value from `1000` to `20000`. That should be able to fix my particular issue for the time being. However, can't we change the column to be `longtext`, instead of `varchar`? That will make it more consistent with similar structures in other tables that store serialized data.

For example, look at the `modules` tables, for the columns `capabilities` and `securityschema`.

**Comment by Guite** [comment]
Doctrine chooses the concrete type automatically depending of the DBMS used. If the length is > 255 it should use some `TEXT` type instead of `VARCHAR` (example for MySQL).

`capabilities` and `securityschema` are array fields which looks not appropriate for the `extra` column.

**Comment by shefik** [comment]
@Guite I don't understand what you mean. Both `capabilities` and `securityschema` store serialized data, and it is set to `longtext`. Why can't `extra` also be set to use `longtext`, since it also stores serialized data? Just change `extra` to be an array column then, instead of increasing the varchar to an arbitrary value.

**Comment by Guite** [comment]
> Just change extra to be an array column then

Can you provide a PR for the change you proposed and successfully tested?

**Comment by Guite** [comment]
ping @shefik

**Comment by Guite** [comment]
> Just change extra to be an array column then

Possible. Did you test it including the update (should be equal to the code in #3901)?

> Can you provide a PR for the change you proposed and successfully tested?

**Comment by shefik** [comment]
@Guite I'll take a look.

**Comment by Guite** [comment]
@shefik please see also #3397 which is related or even a duplicate.

**Comment by Guite** [comment]
Sorry I meant #3619
