### ISSUE TITLE
Do we need a blank theme?

### ISSUE THREAD

**Issue by Guite** [zikula/core#3905]
### Expected behavior
Zikula should provide a way to deliver output without the layout frame.

### Actual behavior
If plain response is used, page vars are not processed.
That is fine for non-html output, like XML, CSV, PDF etc.
But what to do if you for example want to output standalone HTML, e.g. for a pop-up window or the result of an ajax controller action?

**Comment by shefik** [comment]
Yes

**Comment by Guite** [comment]
@craigh @cmfcmf @gfr 

Quite ugly workaround in generator is using a separate raw page template which manually embeds all assets instead of relying on page vars at all: https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/view/Layout.xtend#L237

**Comment by craigh** [comment]
IMO we do not need to provide a blank theme. This is overkill for a small problem.

perhaps we can create a new plain response that includes needed items. or a simpler answer may be to simply inject the needed parameters into your response.

**Comment by Kaik** [comment]
I agree with @craigh  I do not have much time now to work on Zikula atm :( btw I know it is a different thing but kind of similar error pages there should be a special theme realm for error... actually @Guite maybe you could use theme realms to achieve what you need maybe it will help take a look here https://github.com/zikula/core/blob/master/src/system/ThemeModule/EventListener/CreateThemedResponseListener.php#L63 and here https://github.com/Kaik/KaikmediaAdminLTETheme/blob/master/Resources/config/theme.yml

If you will play with above listener to add some sort of new response please take a look at errors maybe all errors could have their own "error.html.twig" page/layout/realm not only 500 one... this could solve error pages customization within theme now error page is using realm of the module which caused the error...

**Comment by craigh** [comment]
I guess I don't understand the problem. here is an example in the core where a PlainResponse is used:

https://github.com/zikula/core/blob/0becdf0fa5b51bd0dcdd814bfb265236c4091cb4/src/system/UsersModule/Controller/UserAdministrationController.php#L123-L126

How is this not meeting your needs again?

**Comment by Guite** [comment]
@craigh this is a slightly different use case: in your example the controller action is called by JavaScript and the result is updated into the existing page's DOM.
Another use case (where this issue is about) is a controller action which renders a whole page (to be shown in a pop-up window for example). Inside this page you typically need Bootstrap, jQuery as well as other assets, but no site header, site footer, left column, main navigation etc. This means that the theme engine needs to be called (in order to process page vars for embedding the assets) but should not add the whole site layout (theme stuff). Similar to the Printer theme I guess.

**Comment by craigh** [comment]
how about this?

https://github.com/zikula/core/blob/0becdf0fa5b51bd0dcdd814bfb265236c4091cb4/src/system/SearchModule/Controller/SearchController.php#L150-L172

As for pop ups (modals), I thought we had standardized on utilizing Bootstrap popup windows which are rendered (but hidden) in the main page and then shown. like this:

https://github.com/zikula/core/blob/ae6089665a895edf6e72793625466fade337d1a5/src/system/CategoriesModule/Resources/views/Category/list.html.twig#L48-L63

I guess I'm still not understanding.

**Comment by Guite** [comment]
The opensearch function returns xml which does of course not need any assets.

The standardized modal approach is fine, but can not always be used. Best example: implement a plug-in for a Scribite editor. This is a (completely separated) pop-up window opened by an editor button. In this case you need to return a complete HTML page in your response (and often you require bootstrap jquery fontawesome and other assets for that), but you don't want any theme layout being part of it.

**Comment by Kaik** [comment]
@craigh all your examples are "living" inside already loaded page you are just adding/refreshing a part of the dom via js. What @Guite has in mind is completely separated page dom. For example to place in an iframe. The problem is that when you use PlainResponse it does not use page assets and vars this code is not called 
https://github.com/zikula/core/blob/999b5babd4058a4e23298e4cb580bf7e5e186fc7/src/system/ThemeModule/Engine/Engine.php#L320-L334
etc as the response is not wrapped in theme.  https://github.com/zikula/core/blob/999b5babd4058a4e23298e4cb580bf7e5e186fc7/src/system/ThemeModule/EventListener/CreateThemedResponseListener.php#L60-L75

I guess we could create a new response type "RawResponse" then catch it in theme listener and process it like it would be a themed one but without actual theme template... 

Other way using normal response but mark it somehow via annotations as some kind of dummy theme that is "internal" with dummy realm. Theming process will go all the way down but will not load any template files and will not wrap in anything. 
By dummy internal theme I mean no additional theme in themes directory but a situation where theming engine is swicthed into its own internal hardcoded 'theme' which just returns response as it is but adds assets.
Btw response from controller would need to be full page with head and stuff so it can add css and other assets.

**Comment by craigh** [comment]
I looked into solutions for this. In my opinion the best solution is to leave it as is. Creating a new response type would only confuse the options and force the system into assumptions which would be difficult to enforce. Creating a whole theme wouldn't work for each situation.

If you take a look at the **CoreInstallerBundle**, you can see a good indication how how I have solved this problem in the past. The installer uses no theme and all `PlainResponse`s. 

https://github.com/zikula/core/blob/5adfa39e7e133445c736a49f877b1088229224ca/src/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AbstractController.php#L188-L197

All the assets mentioned above are loaded in the base template:

https://github.com/zikula/core/blob/4118c1fa49e298b872f635e041869e5aef352219/src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views/structure.html.twig#L12-L23

And the more traditional "symfony way" of using twig and templates is utilized. If I were building a module that required many non-themed pages, this is how I would handle it. If only one page was needed, I would simply combine the laters of templates into one.

**Comment by Guite** [comment]
> All the assets mentioned above are loaded in the base template:

This is the same approach as I am currently doing in the generator: https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/view/Layout.xtend#L237

So as I understand correctly no further changes are desired. Closing.

**Comment by Guite** [comment]
FYI: I now changed the generator implementation to make things less static: the solution is to call the `Zikula\ThemeModule\Engine\AssetFilter#filter()` manually in order to add all assets to the page output.
