### ISSUE TITLE
travis builds failing for master

### ISSUE THREAD

**Issue by craigh** [zikula/core#3907]
Travis builds are failing for 2.0 branch. it appears that php-unit is missing.

**Comment by craigh** [comment]
https://travis-ci.org/zikula/core/jobs/390874379

**Comment by Guite** [comment]
> failing for 2.0 branch

No, 2.0 is fine.
Only master is failing where simple-phpunit is used instead of phpunit.

https://travis-ci.org/zikula/core/branches

**Comment by Guite** [comment]
Fixed by baca61f7bcc1768e6fb50fd5fd569891d205fbad

**Comment by craigh** [comment]
thanks @Guite !
