### ISSUE TITLE
[General] Replace component-installer

### ISSUE THREAD

**Issue by Guite** [zikula/core#3908]
From https://github.com/RobLoach/component-installer :

> Component Installer has been deprecated. Use Asset Packagist or Component Installers Extender instead.

**Comment by craigh** [comment]
constant warning in composer now:

```Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.```

**Comment by Guite** [comment]
refs #4032

**Comment by craigh** [comment]
it appears that these are the only packages we are installing with component-installer

> src/system/ThemeModule/composer.json

        "components/jquery": "3.*",
        "components/jqueryui": "1.*",
        "components/bootstrap": "4.*",
        "components/font-awesome": "5.*",

**Comment by craigh** [comment]
`Zikula\ExtensionsModule\Composer\RequireJsConfigGenerator::regenerateRequireJs` also uses component-installer classes/processes to build js files. it was built by @Kaik

**Comment by craigh** [comment]
This now becomes a larger problem with the release of Composer 2.0. The plugin doesn't work any longer, so we must stay with Composer 1

**Comment by Guite** [comment]
Yes, IMHO we should stay with Composer 1 for now.

The proper solution is outlined in #4032 - but getting into https://github.com/fxpio/foxy and including it with Symfony Encore and making that work with dynamic extensions (modules / themes) should be part of a major release (4.0.0).

**Comment by craigh** [comment]
This was completed here: https://github.com/zikula/core/pull/4558
