### ISSUE TITLE
Preview of theme seabreeze causes error

### ISSUE THREAD

**Issue by Portugao** [zikula/core#3910]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.6
| PHP Version       | 5.6

### Expected behavior
no error

### Actual behavior
Key "keywords" for array with keys "charset, description" does not exist.
```
in themes/zikula/seabreeze-theme/Resources/views/Include/head.html.twig (line 4)
<meta charset="{{ pagevars.meta.charset }}" /><title>{{ pagevars.title }}</title><meta name="description" content="{{ pagevars.meta.description }}" /><meta name="keywords" content="{{ pagevars.meta.keywords }}" /><meta http-equiv="X-UA-Compatible" content="chrome=1" />
```

### Steps to reproduce
Call the preview for seabreeze

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/ZikulaSeaBreezeTheme/commit/b0218ba91cf1a83fa70095165134b232c2fc1bb3 and https://github.com/zikula/core/commit/abb4ca9bbc288a388fd4bbe2f53362f2b6be4ac6
