### ISSUE TITLE
ZikulaBlocksModule Admin js

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3911]
I know @craigh warned me that when I disable wrapper div in the theme it will happen but - this is because of wrong/old design. Block module js is tied to "external" stuff like z-admin class which is not part of Blocks module. I will look for those and will try to fix them.

https://github.com/zikula/core/blob/0d7dc3d29cb47259403d522b0842ce6554a74149/src/system/BlocksModule/Resources/public/js/Zikula.Blocks.Admin.Common.js#L8-L9

**Comment by craigh** [comment]
I disagree that the ZikulaBlocksModule must be self contained. It is an integral part of the Zikula Core. It cannot function without the other modules and core files and they cannot function properly without it. If there is a better way for fire the JS, then fine, but you cannot make all the modules in the Core independent of each other entirely.

**Comment by Kaik** [comment]
Ok, I used wrong words 'self contained' is too vague in this case. I think core module functionality should not rely on things (like admin header) that belong to other core module and can be customised via themes...

**Comment by Kaik** [comment]
How about:
``<a class="block-state-switch label label-success ``
``<a class="block-state-switch label label-danger ``
and
`` $('.block-state-switch').click( function(e) { ``

@Guite your solution is ok just wondering, btw if considering how it is addressed at the moment this should would work too `` $('.label[data-bid]').click( function(e) { `` but it is to open as label[data-bid]

How about making this switch one-liner so instead of two ``a`` elements add only one and toggle class, title and text

```
                        <a class="block-state-switch label {% if block.active %}label-danger {% else %} label-success {% endif %} tooltips"
                            href="#"
                            title="{{ block.active ? __('Click to deactivate block') : __('Click to activate block')  }}"
                            data-bid="{{ block.bid }}"
                            >
                            {{ block.active ? __('Active')  : __('Inactive') }}
                        </a>

```

```
            .done(function(response) {
                // toggle label
//                a.parent().find('a').toggleClass('hide');
		if (a.hasClass('label-success')) {
		    a.removeClass('label-success')
			.addClass('label-danger')
			.text(Translator.__('Inactive'))
			.attr('title', Translator.__('Click to activate block'));
			;
		} else {
		    a.removeClass('label-danger')
			.addClass('label-success')
			.text(Translator.__('Active'))
			.attr('title', Translator.__('Click to deactivate block'));
			; 
		}
            })
```

**Comment by Guite** [comment]
Yes x2.
