### ISSUE TITLE
Cleanup Users and ZAuth redundancies

### ISSUE THREAD

**Issue by Guite** [zikula/core#3913]
Review validators and check which ones make sense to exist in both modules and which not.

https://github.com/zikula/core/tree/2.0/src/system/UsersModule/Validator/Constraints
https://github.com/zikula/core/tree/2.0/src/system/ZAuthModule/Validator/Constraints

The email validator is exactly identical.

Also a modvar is used at https://github.com/zikula/core/blob/2.0/src/system/ZAuthModule/Validator/Constraints/ValidEmailValidator.php#L66 but never initialised at https://github.com/zikula/core/blob/2.0/src/system/ZAuthModule/ZAuthModuleInstaller.php#L71

cc @craigh

**Comment by craigh** [comment]
the validators are _intentionally_ duplicated

consider - ZAuth may not be the module which authenticates the user (e.g. OAuth, etc). The Authentication module must validate its own values. In addition, the core must validate users as they are added. 

The modvar being used should be obtained from the `ZikulaUsersModule` not `ZikulaZAuthModule` that appears to be a mistake.

https://github.com/zikula/core/blob/0becdf0fa5b51bd0dcdd814bfb265236c4091cb4/src/system/UsersModule/UsersModuleInstaller.php#L195

**Comment by Guite** [comment]
I understand that each authentication module may use it's own validation logic. But why can't ZAuth reuse the email validator from the Users module if it utilises the same validation approach?

**Comment by craigh** [comment]
I wrestled with all these decisions some time ago. At the time, I determined this was the best approach. I cannot recall all my thoughts, but suffice to say that all options were carefully considered. Self-containment was certainly part of the thought process. Obviously, I am typically not in favor of code duplication... but at the time, it made sense for me to do so.

**Comment by Guite** [comment]
Okay. I will then just fix the wrong modvar reference.
