### ISSUE TITLE
mmenu custom width not working

### ISSUE THREAD

**Issue by craigh** [zikula/core#3915]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.8
| PHP Version       | 5.6.30

### Expected behavior
custom width of mmenu

### Actual behavior
standard menu width

when this happened before it was because the vendor introduced a BC break and this required changes in the core. custom styles are designed by changing .scss files that are stored in Admin module.

**Comment by Guite** [comment]
Vendor has rewritten that so the scss files referenced in https://github.com/zikula/core/blob/master/src/system/AdminModule/Resources/public/css/mmenu-hiddenpanel-customwidth.scss are not available anymore.

**Comment by Guite** [comment]
Tests with BS4 have shown that we can remove this because the [original issue](https://github.com/zikula/core/issues/3449) does not happen anymore. Done in https://github.com/zikula/core/commit/cdde003955ea571036eed249b07e0266bfe9c1d9 - closing as this is part of #4037

**Comment by craigh** [comment]
I'm not clear that this is fixed. My issue is that the menu is too wide for my taste, the original solution to this was a custom css file to override the width. by removing all customization, I'm not clear that the issue is solved.

**Comment by Guite** [comment]
To customise the width we can also just override this one:
```
.mm-menu_offcanvas {
 width:80%;
 min-width:240px;
 max-width:440px
}
```
in our core.css or in another css file.

**Comment by craigh** [comment]
you must have commented and then deleted? (e.g. about override?) so the comment was incorrect?

**Comment by Guite** [comment]
I became unsure about whether it was correct so I resetted :recycle:

**Comment by craigh** [comment]
let's keep it for the record

> To customise the width we can also just override this one:

```
.mm-menu_offcanvas {
 width:80%;
 min-width:240px;
 max-width:440px
}
```
> in our core.css or in another css file.
