### ISSUE TITLE
Can't move or delete categories

### ISSUE THREAD

**Issue by DirkThiele** [zikula/core#3920]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.9
| PHP Version       | 7.2

### Expected behavior
Dragging or deleting a category

### Actual behavior
500: Internal Server Error
Memory limit has been raised to 2G without success
Ajax timout x3 = 15 seconds without success

### Steps to reproduce
Dragging or deleting a category

**Comment by Guite** [comment]
for a quickfix/workaround add `return true;` after https://github.com/zikula/core/blob/2.0/src/system/CategoriesModule/Helper/CategoryProcessingHelper.php#L67
this disables the whole check

**Comment by paustian** [comment]
I can confirm that that fix works

**Comment by paustian** [comment]
@Guite I think I have a partial fix. I found that the issue is that it creates an infinte loop. The code assumes that when you call getParent you will get null if it is a top directory. That is not the case, you get the same object back. I don't know if this is a bug in how the entity works, but that is what it does. Here is a fix I put in to fill the array I think with what you want....
`$isOnTop = false;
        $parentIds = [$category->getId()];
        while (false === $isOnTop) {
            $directParent = $category->getParent();
            $pId = $directParent->getId();
            if ($pId === end($parentIds)) {
                $isOnTop = true;
            } else {
                $parentIds[] = $pId;
            }
        }`

**Comment by DirkThiele** [comment]
@paustian 
This solution is working for me but with restrictions.

1. Deletion - **Works**
2. Sorting entries inside of a container - **Works**
3. Moving entries (end nodes) from one container to another in the same hierachy level - **Works**
4. Moving entries (end nodes) down in the hierachy level into another container - **Works**
5. Moving entries (end nodes) upwards in the hierachy - **_Does not work_**
6. Moving containers (no matter if empty or not) downwards - **Works**
7. Moving containers (no matter if empty or not) upwards - **_Does not work_**

Can anyone confirm this behaviour?

**Comment by Guite** [comment]
Thanks for the proposal @paustian. Currently working on it.
