### ISSUE TITLE
Can't log in after upgrade 2.0.5 to 2.0.9

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3922]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.9
| PHP Version       | 7.x

### Expected behavior
Be able to log in

### Actual behavior
Unable to log in error 500 

Error
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\ResourceNotFoundException: "" at
var/www/vhosts/mojeleicester.pl/httpdocs/var/cache/prod/appProdProjectContainerUrlMatcher.php line 5548 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/vhosts/mojeleicester.pl/httpdocs/var/cache/prod/appProdProjectContainerUrlMatcher.php:5548)"} []                                             
```

### Steps to reproduce
I was able to trace it to UsersModule set locale listener. I'm using zikula 2.0.9 with two languages. 

When I disable https://github.com/zikula/core/blob/master/src/system/UsersModule/Listener/UserEventListener.php#L74-L77
I'm able to log in...

**Comment by craigh** [comment]
try clearing the cache?

**Comment by Guite** [comment]
> a missing route translation

Likely

**Comment by Kaik** [comment]
![screenshot from 2018-08-10 22-26-49](https://user-images.githubusercontent.com/966910/43979965-bd5aa3a8-9cec-11e8-9165-9c768bbd26fd.png)
Hmm this might take some time to trace which one is empty... I will but for now I'm just disabling it.

**Comment by craigh** [comment]
does it work in english?

**Comment by Guite** [comment]
Try replacing https://github.com/zikula/core/blob/2.0/src/system/UsersModule/Listener/UserEventListener.php#L68-L77 by:

```
            $url = $event->getArgument('returnUrl');
            if ('' != $url) {
                $request = $this->requestStack->getCurrentRequest();
                $httpRoot = $request->getSchemeAndHttpHost() . $request->getBaseUrl();
                if (0 === strpos($url, $httpRoot)) {
                    $url = str_replace($httpRoot, '', $url);
                }
                $pathInfo = $this->router->match($url);
                if ($pathInfo['_route']) {
                    $event->setArgument('returnUrl', $this->router->generate($pathInfo['_route'], ['_locale' => $locale]));
                }
        }
```

**Comment by Kaik** [comment]
@craigh no same error in English...
@Guite works! Thx

**Comment by Guite** [comment]
Two aspects:
1. I do not assume that a missing translation is the only possible cause for a missing return url.
2. A missing route translation will cause an exception anyway, but should not block the login.
