### ISSUE TITLE
How to structure next iteration?

### ISSUE THREAD

**Issue by Guite** [zikula/core#3923]
After Content and Media modules are out, I want to focus on core development again in order to make a step forward (for instance halve (or at least significantly reduce) the amount of open issues).

Proposal:

- create a `2.1` branch based on current `master`
  - `2.1` is for 2.1.x
  - `master` is for 3.0
- if things become obsolete (example: #3772, #3801)
  - deprecate them in 2.1
  - remove them in 3.0
- aim on simultaneous releases (like 1.5 was in parallel with 2.0)
- technical proceedings
  - major vendor updates (for example Symfony 4, Twig 2, Bootstrap 4, FontAwesome 5)
  - PHP 7 as new minimum (e.g. Twig 2 requires it)
  - are only done in 3.0?

Does that make sense?
Or should we - given that time is running and manpower is limited - rather directly aim on 3.0 without a 2.1 series at all? Because as soon as we use PHP 7 features and migrate to new vendor major versions 2.1 and 3.0 will drift apart from each other making parallel maintenance expensive.

@craigh @portugao @rallek @gfr @shefik @Kaik @nmpetkov @cmfcmf

**Comment by Guite** [comment]
But would you prefer having a 2.1 and 3.0 simultaneously with more costs (time/energy) or the quicker way of doing 3.0 only?

**Comment by Guite** [comment]
3.0 only means things may be removed before having been deprecated before.

**Comment by shefik** [comment]
I would be fine with just moving on to 3.0.

**Comment by gfr** [comment]
+1 for just 3.0

**Comment by Portugao** [comment]
👍 3.0
