### ISSUE TITLE
[HookBundle] Hooks - Available areas - Sliding possible?

### ISSUE THREAD

**Issue by DirkThiele** [zikula/core#3924]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.11
| PHP Version       | 7.2

NOT SURE WHETHER IT IS A CORE TOPIC !!!

### Behavior desired
`Available areas` on the right hand side should slide vertically if the list of `Attached areas` is too large for being displayed without scrolling.

Grabbing an UI hook and dragging it down into one of the `Attached areas` is a challenge if you need to scroll down at the same time.

Scrolling down to the `ui_hooks` first while the box with all `Available areas` is moving downwards at the same time would be of great help. 

### Actual behavior
`Available areas` remain on top of the page and are out of sight for the user.
Dragging and scrolling is tricky, as same as in Excel. ;-)

### Steps to reproduce
Try it with a large list of `Attached areas` ;-)

**Comment by Guite** [comment]
> Try it with a large list of Attached areas ;-)

Can you give an example for that?

**Comment by Portugao** [comment]
Doesn't matter which modules. I you have a specific number of modules, you have to scroll. If so, it will be complicated to put the provider container into a subscriber container.

**Comment by Portugao** [comment]
Especiallay if the provider container is on the top and the subscriber container on the bottom.

**Comment by DirkThiele** [comment]
It would just be a feature, yes!

My module built with MOST comes with 8 entities. This, multiplied by three (filter_hooks, form_aware_hook and ui_hooks) results in a large list on the left hand side.

As I said, it just would be some kind of a 'nice to have' feature. ;-)

**Comment by Guite** [comment]
> with 8 entities

Do you need hook subscribers for all these? If not, there is a `skipHookSubscribers` property you can use ;-)

**Comment by DirkThiele** [comment]
Thanks for the hint, I will have a look...
