### ISSUE TITLE
E-Mail verification - Confirmation Mail - Formatting

### ISSUE THREAD

**Issue by DirkThiele** [zikula/core#3927]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.2.11
| PHP Version       | PHP 7.1.19-nmm1
| Mailbrowser       | Thunderbird 52.9.1 (32-Bit)

### Expected behavior
Clickable link inside of the E-Mail that refers to the "verify-registration" form:

https://myDomain.de/zauth/verify-registration/USERNAME/CODE

### Actual behavior
Link needs to be copied manually, even if other links in the same E-Mail are formatted properly and clickable.

This is nothing serious, it's just inconvenient.

### Steps to reproduce
Create account and read the E-Mail that is being send.

**Comment by craigh** [comment]
if I recall, the message is sent in both html and text formats. your client may be choosing the wrong one.

**Comment by DirkThiele** [comment]
But does it display the other links in the same E-Mail properly?

Maybe it is related to the german translation only?

I guess your installation is set to english.

I will check and let you know.

**Comment by Guite** [comment]
> I will check and let you know.

any update @DirkThiele ?

**Comment by Guite** [comment]
any update @DirkThiele ?

**Comment by DirkThiele** [comment]
Sorry,
yes I can confirm that the verification link in the E-Mail is broken if the Site is running with the german language pack.

**Comment by Guite** [comment]
> with the german language pack.

Interesting.
Can you please check whether there exists a file `app/Resources/translations/routes.de.po`? If yes, please delete it and check if the link works then.

Could you also post the different links:
1. In German language and with `routes.de.po` in place.
2. In German language and with `routes.de.po` being removed.
3. In English language

This would help us spotting the problem.

Thank you!

**Comment by Guite** [comment]
Rescheduled for 3.0.0.

**Comment by DirkThiele** [comment]
Again, sorry for the delay, as every year the external audit in my company is challenging and time consuming.

I have noticed that my initial error description could have been a bit better.

So, in the german verification message there is a space character missing and therefore the e-mail client does not interpretate the link as such. The english verification message is correct and the link is working

**DE**
`Bitte über den folgenden Link die Registrierung 
abzuschließen.https://YourDomain.de/zauth/verify-registration/YourUserName/QneR2`

**EN**
`Please click on the following link to complete the e-mail address check: 
http://YourDomain.de/zauth/verify-registration/YourUserName/c%283nr`

**Comment by Guite** [comment]
Thanks for reporting.

You can fix this by upgrading your German translation files to this version: https://github.com/zikula-communities/german/tree/core-2.0/app/Resources/translations

Closing.
