### ISSUE TITLE
Add a displayName field to the usertable

### ISSUE THREAD

**Issue by phaidon** [zikula/core#393]
I would like to have a displayName field in the usertable. We could use it for the user search, intercom, Dizkus and similar tasks. Imho that is much nicer, then just show the $userName. 

Of course there is a realName field in the profiles, but for the search functions like in intercom I think a implementation in the usertable would be better.

**Comment by craigh** [comment]
closing this. Unames can now include spaces and capital letters - e.g. "Craig Heydenburg". Anything further should be handled by Profile.
