### ISSUE TITLE
Plural forms do not work properly

### ISSUE THREAD

**Issue by Guite** [zikula/core#3941]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.11
| PHP Version       | 7.x

### Expected behavior
Gettext strings with plural forms are correctly translated.

### Actual behavior
1. Gettext strings with plural forms are not translated at all.
2. The plural form is always used (also if the singular form should be used).

### Steps to reproduce
1. Install an additional locale
2. Enable multi language support
3. Navigate to `/menu/admin/list`
4. See the `mainMenu` has `2 direct children` instead of (German example) `2 direkte Kinder`

### Additional information

The extractor concatenates plural forms using a pipe character, see https://github.com/zikula/core/blob/master/src/lib/Zikula/Bundle/CoreBundle/Translation/ZikulaPhpFileExtractor.php#L189-L192

This leads to this structure:

```
msgid "%c direct child|%c direct children"
msgstr "%c direct child|%c direct children"
```
and
```
msgid "%c direct child|%c direct children"
msgstr "%c direktes Kind|%c direkte Kinder"
```

So it seems the catalog does not even know there are plural forms used.
An indicator for this is that the tooling, e.g. poedit, does not provide multiple input fields at all.

An old example from Zikula 1.3 looks like this:

```
#, php-format
msgid "There is %s offer waiting for approval:"
msgid_plural "There are %s offers waiting for approval:"
msgstr[0] "Es wartet %s Angebot auf eine Freigabe:"
msgstr[1] "Es warten %s Angebote auf eine Freigabe:"
```

### To be checked

Maybe just simplify things by dropping our own translation system in favour of Symfony's native stuff.

**Comment by Kaik** [comment]
I think I mentioned that somewhere... hmm

**Comment by Guite** [comment]
refs #3551

**Comment by Guite** [comment]
kaik [07:54]
> I remember someone asked, about plural translations in zikula and that it does not work using _fn
> Please use transchoice
> For example in tremplate
>  ```{{ '{0} Messages|{1} You have one unread message|]1,Inf[ You have %unread_count% unread messages'|transchoice(unread_count,{}, 'zikulaintercommodule') }}``` 
> and in .po.pl
> ```msgid "{0} Messages|{1} You have one unread message|]1,Inf[ You have %unread_count% unread messages"
> msgstr "{0} Wiadomości|{1} Masz jedną nieprzeczytaną wiadomość|]1,Inf[ Masz %unread_count% nieprzeczytanych wiadomości"```

**Comment by Guite** [comment]
Works like a charm :-)

**Comment by Kaik** [comment]
So, this is proper transchoice thingy thing straight from symfony it does work with Zikula and I guess it is more future proof than _fn()
]1, Inf [ means from 1 to infinity 
you can have really complex plurals and other stuff like different string based on count... we do have a hyperlink in our docs to trans method and sf translator documentation -> translations -> usage
