### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by craigh** [zikula/core#3942]
https://travis-ci.org/zikula/core/builds

>$ ./bin/simple-phpunit
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Could not find https://github.com/sebastianbergmann/phpunit/archive/4.8.zip' in /home/travis/build/zikula/core/src/vendor/symfony/phpunit-bridge/bin/simple-phpunit:70
Stack trace:
#0 {main}
  thrown in /home/travis/build/zikula/core/src/vendor/symfony/phpunit-bridge/bin/simple-phpunit on line 70
Fatal error: Uncaught exception 'RuntimeException' with message 'Could not find https://github.com/sebastianbergmann/phpunit/archive/4.8.zip' in /home/travis/build/zikula/core/src/vendor/symfony/phpunit-bridge/bin/simple-phpunit:70
Stack trace:
#0 {main}
  thrown in /home/travis/build/zikula/core/src/vendor/symfony/phpunit-bridge/bin/simple-phpunit on line 70
The command "./bin/simple-phpunit" failed and exited with 255 during .
Your build has been stopped.

**Comment by Guite** [comment]
> Could not find https://github.com/sebastianbergmann/phpunit/archive/4.8.zip

They removed the branch apparently.
So we are urged to upgrade (finally).

**Comment by Guite** [comment]
Depends on #3935 and therewith includes #3370 as well as other upgrades.

**Comment by Guite** [comment]
Fixed in 8bed29503679593130a0f927bbd8cca5c4eff608
