### ISSUE TITLE
unknow zikulalegalmodule_inlineLink 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3948]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2x
| PHP Version       | 5.x

When zikulalegalmodule is not installed zikulalegalmodule_inlineLink twig function generates an error even when "if-ed out"

When used in theme breaks freshly installed site - and for some reason cannot be disabled dynamically, I had to comment it out or install the legal module.

**Comment by Guite** [comment]
Why should this be a core issue?

**Comment by Kaik** [comment]
I was thinking about it and I feel like it belongs to the core but I do not have a strong argument yet :) Anyway I think there is a flaw somewhere if you cannot make a theme that will work normally when the legal module is not installed and provide legal links when it is, apart from that thing like T&C or privacy policy are somewhat parts of the core.
It just doesn't feel right. I know it is a minor issue but still. Btw I do not think that we can solve it within the legal module. The problem is that twig functions are not registered for modules that are not installed so the only option is to make it same way profile module or messages module is done via a bridge.

**Comment by Guite** [comment]
Closing as won't fix.

Suggestion: add a Twig function to your admin theme which checks for Legal module availability and returns the functionality you need.
