### ISSUE TITLE
Translate twig date_diff

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3951]
To enable |date_diff translations:
1. pass translator to twig date service definition
2. add translations for English as strings are in diff.ago.minutes format when the translator is present.
I do have en translation po files I will push en version hopefully soon.

**Comment by Guite** [comment]
Shouldn't the go into a wiki page instead of an issue?

**Comment by Kaik** [comment]
Well no, I do not think so, at the moment it is a list of things that I need to do - push to the core and then we may add information to the wiki about the need for translations.

**Comment by Guite** [comment]
@Kaik can this be closed (since we are dropping our custom translation system see #4042)?

**Comment by Kaik** [comment]
Not yet I promise I will do PR for that by tomorrow...
Actually this has nothing to do with our custom system. It is generic twig sf stuff, but it needs to be enabled and translated at least to English as it uses default ids 
something like ``` diff.ago.year ```

**Comment by Kaik** [comment]
So looks like extension that provided time_diff filter is abandoned and there is no equivalent.
This time_diff filter allowed to create texts like "2 minutes ago" or "20 days ago" etc... I'm now thinking, about recreating this functionality for Zikula as our own time_diff filter... but a lot of things changed and need to see how to do it now.

Closing this issue then.
