### ISSUE TITLE
Error when removing user

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3953]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.11
| PHP Version       | 7.x

### Expected behavior
No error

### Actual behavior
Error 503 serivice not available

### Steps to reproduce
Production server - plesk + cent os php 7.2.13 apache
Go to users admin remove pending registration confirm - error 503

Logs were saying something regarding iterating over the sessions... and allowed memory exhausted...
Funny thing on local dev installation where everything is the same there is no error - it takes time to do remove it tho...

I will investigate this error furthermore.... at the moment my best type is that sessions is somehow involved during user delete and since on production I do have more sessions than locally it fails...

**Comment by Guite** [comment]
note: when working on this see also #4071

**Comment by craigh** [comment]
I am unable to replicate this behavior.
I created a user, logged in as that user, logged out. logged in as admin, then deleted that user with no trouble.

**Comment by Kaik** [comment]
@craigh how big is your users table? Because it is related. Please can you check it with considerably large (10k+) users table - size depends on your dev hardware.

**Comment by craigh** [comment]
my user table has 3 users. my dev machine is 1 computer. an iMac.

I can't test things I don't have with computers I don't own.

feel free to test the current master and let me know what you find.

**Comment by craigh** [comment]
@Kaik I tested this fix with >20K users in my DB. I did experience the error you described before fixing it. Since this fix eliminates the 'reloading' of all the entities (which you pointed out as the problem), I'm quite sure it solves the problem.
