### ISSUE TITLE
multilingual start controller

### ISSUE THREAD

**Issue by rallek** [zikula/core#3955]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.12
| PHP Version       | 7.1

### Expected behavior
In the start setting the start controller should be multilingual as well

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/52237579-376e6f80-28ca-11e9-9d49-7301326ced9e.png)
only meta keywords are multilingual

### Steps to reproduce
install ContentModule and try to setup a page for German and a translation for English

**Comment by rallek** [comment]
ups, If I use the same slug for german and english it seems to work propperly.
But nevertheless it would be a nice feature to be able to have a different start module setting for each language

**Comment by Guite** [comment]
Of course this issue is a valid feature request.

**Comment by rallek** [comment]
the value for this page is in both cases ``seiten/startseite`` and it is always showing the English page.

**Comment by Guite** [comment]
@rallek please add the patch from https://github.com/zikula/core/commit/67b78dcbe7673f3c54c0d11906ed600d413f5f40 and try again...

**Comment by Guite** [comment]
seems I added this during last camp btw ;-)

**Comment by rallek** [comment]
same behavior. 

What should have changed? equal slug should language sensitive?

I deleted the folder ``prod`` inside cache after uploading the file.

**Comment by rallek** [comment]
I am using zk 2.0.12. There this fix is already included. So I am able to set content as a startmodule.

**Comment by rallek** [comment]
rechecked it right now. Might be it is working. Need further tests! Please keep this ticket open for some days until I can confirm.

**Comment by rallek** [comment]
It is working fine now for ContentModule. But nevertheless it would be great to have the setting also multilingual.

**Comment by craigh** [comment]
@Guite I don't understand this ticket. If you want to implement, please go for it.

**Comment by Guite** [comment]
I am going to add the following changes:

- add support for GET, POST and Request parameters (like in Content's controller type, see [here](https://github.com/zikula-modules/Content/blob/master/extensions/Zikula/ContentModule/ContentType/Form/Type/ControllerType.php#L30-L57))
- add the possibility to enter this for each installed/available language with first fallback to default language and second fallback to nothing (static home page)

**Comment by Guite** [comment]
Probably create a dedicated form type for centralising/grouping these four fields (controller, query, request, attributes) to simplify repeated usage.
