### ISSUE TITLE
Error 500 when accessing Extensions in admin panel 

### ISSUE THREAD

**Issue by shoshia** [zikula/core#3958]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.12
| PHP Version       | 7.2

### Expected behavior
open extensions administration page

### Actual behavior
error 500

### Steps to reproduce
from admin panel click extensions
or
when click 'SyStem:Administration Panel'
[prod.log](https://github.com/zikula/core/files/2886608/prod.log)

**Comment by shoshia** [comment]
Hi  all :).
I' very old zikula user since zikula started from php nuke :) ...
Some developers know me from emails and zikula forums..
Will be forums back again?

Now about problem.
I don't have mod_rewrite enabled. Maybe this is a problem?
Can I use zikula without mod rewrite enabled?

I remember old versions had 'use short url' option. Is this gone?

**Comment by Guite** [comment]
This is a vendor problem. See also:
https://github.com/zikula/core/issues/2852
https://github.com/zikula/core/issues/3746
https://github.com/zikula/core/issues/3842

Until Doctrine is upgraded (issue #3878) you will need to change your sql_mode to bypass the issue. Read for example https://stackoverflow.com/questions/36829911/how-to-resolve-order-by-clause-is-not-in-select-list-caused-mysql-5-7-with-sel

**Comment by shoshia** [comment]
and same mysql problem for zikula 2 versions right?

**Comment by shoshia** [comment]
2 years problem...seems it never will be fixed if it is not fixed in 2 years :( ...

**Comment by Guite** [comment]
It is already fixed in Doctrine ORM 2.6. But this requires PHP 7.1+.
Since Zikula 1.x and 2.x also work with PHP 5.5 this upgrade can only be done for Zikula 3. And this is will be done with #3935 and #3878.

**Comment by shoshia** [comment]
Thank you....I see release planned in July.
So no temporary solution besides changing mysql config?
and one more question.
I use 1.3.x version on another site...
will 1.3.x or 1.4 version work with  mysql version 5.7.25

**Comment by Guite** [comment]
> So no temporary solution besides changing mysql config?
Try this: open the file `lib/Zikula/Bundle/CoreBundle/Bundle/Bootstrap.php` end before `return DriverManager::getConnection($connectionParams, new Configuration());` insert something like

```
        $connectionParams['driverOptions'] = [
                \PDO::MYSQL_ATTR_INIT_COMMAND => "SET sql_mode=''"
        ];
```

> I use 1.3.x version on another site...
> will 1.3.x or 1.4 version work with mysql version 5.7.25
Probably. I have 1.3 sites running with it.

**Comment by shoshia** [comment]
I added code, but it does not help

**Comment by Guite** [comment]
Maybe ask your provider about how to do it then.

**Comment by shoshia** [comment]
Can you put 1.3 and 1.4 builds somewhere for download?
I'm on windows :(

**Comment by shoshia** [comment]
I have old 1.3.5 core and installer gives error

> Error in DBUtil::executeSQL: INSERT INTO users (uid,uname,email,pass,passreminder,activated,approved_date,approved_by,user_regdate,lastlogin,theme,ublockon,ublock) VALUES (1,'guest','','','',1,'1970-01-01 00:00:00',0,'1970-01-01 00:00:00','1970-01-01 00:00:00','',0,'')
> SQLSTATE[HY000]: General error: 1364 Field 'tz' doesn't have a default value

same with 1.3.7

**Comment by Guite** [comment]
Downloads are available at https://github.com/zikula/core/releases
But instead of trying older versions better try to change your sql_mode...

**Comment by shoshia** [comment]
sysadmin changed config and everything is fine now :)

**Comment by Guite** [comment]
Fine. Closing then.
