### ISSUE TITLE
Login not possible after upgrade ZK1.4.6 to 2.0.12

### ISSUE THREAD

**Issue by KratorD** [zikula/core#3961]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.12
| PHP Version       | 5.6.31

### Expected behavior
Login to admin

### Actual behavior
Login is not possible

### Steps to reproduce
Upgrade ZK1.4.6 to 2.0.12. Fill login page with credentials. CSRF error is launched. 
If I edit the file: `system/ZAuthModule/Form/Type/UnameLoginType.php`  with `'csrf_protection' => false`, the login is not possible either

No errors retrieved, not more information...After fill login, the login page is loaded again.

**Comment by KratorD** [comment]
The problem is before to ZK2 and is presented in upgrade from 1.3.x to 1.4.6. The error like relationship with upgrade process of Users module (using profile?). 
So, this ticket could be closed.

**Comment by Guite** [comment]
Deleting cookies helped.

**Comment by craigh** [comment]
![0 vwtme6kzfo0riq9o](https://user-images.githubusercontent.com/350048/53987239-70c71480-40ee-11e9-86fa-a7fb55a6bd83.jpeg)

**Comment by KratorD** [comment]
Perhaps it would be interesting to leave the advice in the file UPGRADE-2.0.md
