### ISSUE TITLE
Use Flex for custom composer tasks

### ISSUE THREAD

**Issue by Guite** [zikula/core#3962]
https://github.com/sensiolabs/SensioDistributionBundle is deprecated in favour of Symfony Flex

Currently composer correctly installs vendors, but scripts fail afterwards.
```
Compiling component files
PHP Fatal error:  Class 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler' not found in /.../src/lib/Zikula/Composer/CopyRequirementsFile.php on line 18
```

This includes #3908

**Comment by craigh** [comment]
the error is about copy the requirements checking file from the old symfony installer. (there is no relation to the component installer which is front end assets only).

You could probably use this instead

https://github.com/symfony/requirements-checker

**Comment by Guite** [comment]
You are probably right about this specific script. The issue is bigger though. With Sf4 Flex is used for doing several tasks. So basically everything shown in https://github.com/zikula/core/blob/master/composer.json#L29-L35 is deprecated.

**Comment by craigh** [comment]
well, I certainly haven't kept up with anything. I don't really understand flex at all. But it seems to me that composer will still run scripts. So I don't think you have to replace those lines but only find a replacement for the scripts from SensioDistributionBundle (because it is deprecated). But it is entirely possibly I don't know what I'm talking about.

**Comment by craigh** [comment]
so - just to keep kicking this... I think what I am suggesting is that Zikula shouldn't be using flex (at least in Core 3). You can still use Symfony 4 without it. See Xabbuh's comment here:

https://stackoverflow.com/questions/48410209/where-are-docs-for-symfony4-without-flex

**Comment by Kaik** [comment]
I think it is time to switch to encore and webpack and manage all Zikula assets via webpack. It will handle all of those scripts and more apart from the clear cache one.

It is really easy to install it can be installed in various ways and it can handle all assets, files, css, js, images, sass... We can do it now with legacy jquery and everything else in legacy mode.

**Comment by craigh** [comment]
flex is about backend scripts (php) not front-end assets.

**Comment by Kaik** [comment]
Yes, I know I meant those scripts in composer.json are about assets processing (bootstrap, js etc..), so everything apart from cache clear can be done by encore/webpack.

**Comment by craigh** [comment]
I am looking into solutions for this ticket.

**Comment by craigh** [comment]
@Guite closing this issue as fixed. The issues with SensioDistributionBundle are resolved. Further use of Flex is outside the scope of this ticket.
