### ISSUE TITLE
Drop support for old persisted hooks

### ISSUE THREAD

**Issue by Guite** [zikula/core#3965]
Use only non-persisted hooks.
Remove `hook_binding` and `hook_runtime` tables.
Also remove `HookHandlerPass` compiler pass.
Also do not forget `ExtensionsModuleInstaller` which needs amendments.

**Comment by Guite** [comment]
Closing as invalid. Bindings and runtime information need to remain.

**Comment by craigh** [comment]
hmmm. of course bindings and runtime info must remain. Is there still support for the old persisted hooks in 2.0? I guess I doubt it. It was probably removed at 2.0 right?

**Comment by Guite** [comment]
yes I confused things :)

**Comment by Guite** [comment]
but I removed `HookHandlerPass` which is accidently still in the master branch

going to commit exciting changes very soon, give me just a few more days ;)
