### ISSUE TITLE
Upgrade to 3.0

### ISSUE THREAD

**Issue by Guite** [zikula/core#3967]
Collecting things to consider for core upgrade implementation:

- [x] (https://github.com/zikula/core/issues/3967#issuecomment-622446575) Sync extensions to read themes into `extensions` table
- [x] (https://github.com/zikula/core/issues/3967#issuecomment-622446575) fill new `icon` field for all existing extensions. (@Guite said: "this should happen automatically when extensions are synchronised")
- [x] (https://github.com/zikula/core/commit/91aa98f41c642db2fc53e273385b842a89be99d2) Menu module: block options may contain old template paths (e.g. `{"template": "ZikulaMenuModule:Override:bootstrap_fontawesome.html.twig"}` needs to become `{"template": "@ZikulaMenuModule/Override/bootstrap_fontawesome.html.twig"}`).
- [x] (https://github.com/zikula/core/commit/4aa7832268d3a50824b85afda5ff9acdaa28e91e) Menu module: `menu_items` table `options` column may contain old font-awesome icons (e.g. `fa fa-search`). Could be ignored as non-critical. Just showing a hint to the admin could be enough.
- [x] (https://github.com/zikula/core/commit/91aa98f41c642db2fc53e273385b842a89be99d2) BlocksModule: `properties` column may contain template paths in old style
- [x] (https://github.com/zikula/core/commit/5f327d30aa9d50fbe1287c5ab27780e482fbbdb8) Theme: set default theme to `Bootstrap` (Andreas08 and SeaBreeze are removed, custom ones could break).
- [x] (https://github.com/zikula/core/commit/85a69ad5544b6ec23d770e35cb17062f5a289b0b) Parameter changes:
    - The parameters `temp_dir`, `system.chmod_dir`, `url_secret` and `umask` have been removed without any replacement.
    - Some other parameter have been removed in favour of environment variables
      - `env` became `APP_ENV`.
      - `debug` became `APP_DEBUG`.
      - `secret` became `APP_SECRET`.
      - `database_*` became `DATABASE_URL`.
      - mailer settings now in `MAILER_DSN` (convert from swift mailer)
    - use `Zikula\Bundle\CoreBundle\Helper\LocalDotEnvHelper`
- Fix docs
  - install (e.g. web root _must_ point to `public/` according to [Symfony docs](https://symfony.com/doc/current/setup/web_server_configuration.html))
  - upgrade (e.g. web root _must_ point to `public/` now according to [Symfony docs](https://symfony.com/doc/current/setup/web_server_configuration.html); mention charset recoding process for MySQL)
    - add note to double check fontawesome icons in menu module options
- [x] (https://github.com/zikula/core/commit/cdf5a990760d12ca588f01a6f8ee3385a48117be) Remove all permission schemes for `ZikulaThemeModule::ThemeChange` component.
- Note from DoctrineBundle v2: _When no charset parameter is defined, it now defaults to `utf8mb4` on the MySQL platform and to `utf8` on all other platforms._ -> So ideally nothing should be defined in `config/packages/doctrine.yaml` and `.env.local` (refs #3784, #4246).

**Comment by Kaik** [comment]
I always wondered what is a disadvantage of an upgrade via import strategy. So install fresh version first and then import all data. We could have a way to import data from other systems.

The only disadvantage that comes to my mind is speed, but there are advantages like:
- data verification
- possibility to import huge databases
- control over the import process speed etc...

I know it would require lots of work I just wonder what you think about it.

**Comment by craigh** [comment]
issue with modules table fixed here: e26afea04402b0fd62022fe758f58c88bdea89f7

**Comment by craigh** [comment]
resync of all core modules occurs in `\Zikula\Bundle\CoreInstallerBundle\Helper\CoreInstallerExtensionHelper::executeCoreMetaUpgrade` which is called in the [AjaxUpgraderStage](https://github.com/zikula/core/blob/1fb47b35336660ed2f95bf1aad2f7063606f8642/src/Zikula/CoreInstallerBundle/Helper/StageHelper.php#L175)

**Comment by craigh** [comment]
> So ideally nothing should be defined in config/packages/doctrine.yaml and .env.local (refs #3784, #4246)

@Guite - should we remove something from `services_custom.yaml`? this could be easily done.

**Comment by Guite** [comment]
Before the upgrade the `services_custom.yaml` file doesn't exist at all. So the information about that no charset related setting should be defined is rather meant for that those values should not be included in case some old settings get migrated during the upgrade process.
