### ISSUE TITLE
Refactor page title handling

### ISSUE THREAD

**Issue by Guite** [zikula/core#3969]
Reevaluate: maybe page title should be done independently of page vars.

See discussion at https://github.com/zikula/core/commit/2b9c55db208f0d3bd4183d9ebefa8f41bc607c44#r32873764

**Comment by Guite** [comment]
Slightly refs #519

**Comment by craigh** [comment]
I very much would like that entire method and related stuff `\Zikula\ThemeModule\Engine\ParameterBag::prepareTitle` moved to a helper class or something. that ParameterBag class should be a service. A Bag is an object, not a service.
