### ISSUE TITLE
Add logo/branding support in core

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3972]
Maybe consider adding logo/branding support as a core feature. It is impossible to create a separate admin theme that will use the main theme logo without hardcoding it. 
Branding is some sort of a central feature similar to site name and description. It could be used as well as a default image for opengraph in modules like news articles etc...

**Comment by Guite** [comment]
Can you please give a concrete example for how this could/should look like?

**Comment by Kaik** [comment]
Well, the first problem is that a single file will not be sufficient, because most of the logos or are logotypes and logomarks. Apart from that, we may want to implement favicon/appicon as well and there can be lots of them in different sizes (icons for Web, Android, Microsoft, and iOS (iPhone and iPad) Apps )

So ad 1. Logotype and logomark. I imagine it as a separated "branding" page. Two files (preferably vector ones) could be uploaded and then those would be available as a twig function for example 
```
{{ logotype('300', '150'...other imagine options) }}
{{ logomark('100', '100'...) }}
``` 
So let's say I'm crating, a theme for everyone something like AdminLTETheme and I know that on desktops I want to display the logotype with max size lets say 300x150 and with img-responsive but for very small devices, I want to show only the logomark. I would use the above twig calls so I do not have to hardcode anything.

Ad 2. favicon/appicon hmm well this is a bit different thing. So we could gather all the information like sizes, colors etc and create generate those same ways as online generators like this one https://realfavicongenerator.net/favicon_checker?protocol=http&site=realfavicongenerator.net#.XJzrMXVKiV4

**Comment by craigh** [comment]
It seems like a lot of work for the benefit. When creating a custom theme all this is quite simply done with normal markup. The graphic asset files would be part of that theme. This only seems useful if one site was using multiple themes with one logo - which is hardly ever done.

**Comment by Kaik** [comment]
Yes @craigh I agree but I just asked maybe you will have some other ideas or solutions
Now I think in both cases(themes/modules) it can be solved via variables. 
I would like to make my own themes public but there is my branding hardcoded that is why I thought we may need this feature.

**Comment by craigh** [comment]
variables = DB look-ups which slow down the site if they are needed for every page.

an idea in your case would be to include a placeholder graphic "logo.jpg" (or similar) and then people can simply change the graphic as needed without renaming.

**Comment by Kaik** [comment]
Hmm you are right... in my case, I would have to place it in the web/uploads folder or something so it can be shared it is especially for admin themes I want to make a few of those AdminLte is one but I have other in mind as well.

**Comment by Guite** [comment]
I think it would be advantageous to have a central upload possibility for the following branding files:

- site logo
- site logo (mobile version)
- favicon (260x260 pixels for generating different variants, like apple touch, mstile, android etc. refs [realfavicongenerator](https://realfavicongenerator.net/))

opinions?

**Comment by Guite** [comment]
Maybe we also could automatically provide a `site.webmanifest` file then.

**Comment by Guite** [comment]
https://github.com/RealFaviconGenerator/rfg-api-php-demo

**Comment by Guite** [comment]
First steps done in #4105 by introducing a site definition.

**Comment by Guite** [comment]
@Kaik please see #4240

**Comment by Kaik** [comment]
@Guite it looks awesome :+1:
