### ISSUE TITLE
Consider control user for installer

### ISSUE THREAD

**Issue by Guite** [zikula/core#3975]
We could consider rewriting the installer/upgrader to use a hardcoded superuser instead of something from the DB.
This would base on separate credentials: username and password could be encrypted and stored in a yaml file, php file or something.
it maybe would make everything smoother in the process.

cc @craigh

**Comment by craigh** [comment]
in addition, a small CLI application to reset the user/password would likely be needed in case the site admin cannot remember their username and/or password

**Comment by Guite** [comment]
https://www.webfactory.de/blog/storing-secrets-for-symfony-applications

**Comment by Guite** [comment]
Opinions? @craigh @rallek @gfr @Kaik @paustian

**Comment by gfr** [comment]
I don't think that this feature is necessary and in my opinion there should not exist an user anywhere else than in the database.

**Comment by craigh** [comment]
thanks for the feedback!

**Comment by craigh** [comment]
I no longer feel this is a good option.
