### ISSUE TITLE
Upgrade of hooks fails in 1.4.3 to 2.0.13 upgrade

### ISSUE THREAD

**Issue by paustian** [zikula/core#3977]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
think I found another bug in the upgrade process. I was upgrading two sites, one from 1.4.5 and one from 1.4.3 to 2.0.13. It mostly went fine, but I may have found a bug in the hook upgrade code. The database structure changes and I don’t think this is completely taken care of during the upgrade process.

There are three tables that are eliminated and those are removed. However, the structure of hook_binding and hook_runtime changes and that is not updated.
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 7.3.1

## Expected Behavior
When hooks are attached they should then be able to communicate

## Current Behavior
If you attack any provider and subscriber the site then crashes and complains that the service Id is incorrect or missing.

## Possible Solution
This is an incompatibility in the way the tables are updated. The three tables that are no longer needed are removed. (hooks, hook_area, hook_provider), however the structure of hook_runtime and hook_binding also need to be updated and they are not. 
Here is the old structure of each table:
CREATE TABLE `hook_binding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `subsowner` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `powner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `subpowner` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sareaid` int(11) NOT NULL,
  `pareaid` int(11) NOT NULL,
  `category` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `sortorder` smallint(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `hook_runtime` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `subsowner` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `powner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `subpowner` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sareaid` int(11) NOT NULL,
  `pareaid` int(11) NOT NULL,
  `eventname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `classname` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `method` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `serviceid` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
  `priority` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

Here is the new structure
CREATE TABLE `hook_binding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `powner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `sareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `pareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `sortorder` smallint(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `hook_runtime` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `powner` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `sareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `pareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `eventname` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `classname` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `method` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `serviceid` varchar(120) COLLATE utf8_unicode_ci DEFAULT NULL,
  `priority` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

I was able to fix the issue just by changing the structure of the table manually.
## Steps to Reproduce
Do an upgrade from a 1.4.3 site to 2.0.13. Then try to hook any provider to any subscriber.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

**Comment by craigh** [comment]
The core was never intended to upgrade from 1.4.x -> 2.0.x. It was always expected to upgrade the core first to 1.5.x and then to 2.0.x

Additionally, the nature of _most_ hooks is pretty dramatically different in 2.0.x than in the 1.x series so a complete upgrade is essentially impossible. It will require some manual work at the admin level once the core is fully upgraded.

**Comment by craigh** [comment]
I guess I was wrong to say "The core was never intended to upgrade from 1.4.x" Since clearly the docs say otherwise. But I still feel that hooks are not supported in upgrade. Especially since new modules use a completely new hook system

**Comment by Guite** [comment]
Proposal: drop and recreate these tables during upgrade.

**Comment by craigh** [comment]
The breaking change was made a Core-2.0.0 so the upgrade should be pack ported to that stage of the upgrade path

**Comment by craigh** [comment]
@paustian said:

Changing the table solved the problem. Here is the sql code I used:
```sql
DROP TABLE IF EXISTS `hook_binding`;
CREATE TABLE `hook_binding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `powner` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `sareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `pareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `sortorder` smallint(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
# Dump of table hook_runtime
# ------------------------------------------------------------
DROP TABLE IF EXISTS `hook_runtime`;
CREATE TABLE `hook_runtime` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sowner` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `powner` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `sareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `pareaid` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `eventname` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `classname` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `method` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `serviceid` varchar(120) COLLATE utf8_unicode_ci DEFAULT NULL,
  `priority` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

I put this in a text file and then issued this command on the server:
`mysql --user="useronsite" -p --database="zikuladatabasename" < "sqlTextFile.sql"`
