### ISSUE TITLE
Javascript load order is ignoring negative weights

### ISSUE THREAD

**Issue by paustian** [zikula/core#3978]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.13
| PHP Version       | 7.2

## Expected Behavior
When you put in javascript pageAddAsset commands they should pay attention to negative weights.

## Current Behavior
The weighting works for the most part, but local files are accumulated into a combined file and this file is always placed at the top. Items with negative weights should go first and they don't. Here is some twig code that breaks:
`{{ pageAddAsset('javascript', "https://code.createjs.com/createjs-2015.11.26.min.js", -100) }}`
`{{ pageAddAsset('javascript', jlink, 1000) }}`
jlink is a link to a local file. The CDN needs to be loaded before the code in jlink for it to work. But the final file looks like this:
`<script type="text/javascript" src="/2_0_13/theme/combined_asset/js/0bc8645b10df9b6e40d1bc08b4efe6b11186400.js"></script>
<script type="text/javascript" src="https://code.createjs.com/createjs-2015.11.26.min.js"></script>` 
The jlink file is in the combined assests.

## Possible Solution
A proposed fix that involved three changes: 
Line 125 of Zikula\ThemeModule\Engine\Asset\Merge.php
`$outputFiles = array_merge($preCachedFiles, $outputFiles);`
And adding a new function to Zikula\ThemeModule\Engine\AssetBag.php
`public function all_with_weight(){
        return array_flip($this->assets);
    }`
And then finally using this at line 54 of Zikula\ThemeModule\Engine\Asset\JsResolver.php
`$assets = $this->bag->all_with_weight();`
With these fixes the pageAddAsset code works.

## Steps to Reproduce
See above
## Context
I was trying to use the createjs library with some javascript code that uses it in a template in Zikula and it was not loading.

**Comment by Guite** [comment]
Thank you @paustian

**Comment by paustian** [comment]
Happy to help any way I can.
