### ISSUE TITLE
Increase amount of letters in EMAIL_DOMAIN_VALIDATION_PATTERN

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3980]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1/2/3?
| PHP Version       | NA

## Expected Behavior
Be able to block new TLD's like .website

## Current Behavior
Current TLD are restricted to max 6 chars

## Possible Solution
Already mentioned I think the problem is because of this regex
https://github.com/zikula/core/blob/de34bc2943a69d3cdbc5726ef35bd59185e890e8/src/system/UsersModule/Constant.php#L259

**Comment by Kaik** [comment]
Now I wonder if this is a bug or feature :)

**Comment by Kaik** [comment]
Since TLD's can be really long I think we should remove mentioned length condition.
https://stackoverflow.com/questions/9238640/how-long-can-a-tld-possibly-be

**Comment by Guite** [comment]
@Kaik so your proposal ist removing `{2,6}` entirely?
@craigh any opinion about this issue?

**Comment by craigh** [comment]
I have no opinion. I believe I just copied old work, so it is not my pattern. Even 1.3 is the same I think:

    /**
     * The PCRE regular expression fragment used to validate e-mail addresses.
     */
    const EMAIL_VALIDATION_PATTERN = '(?:[^\s\000-\037\177\(\)<>@,;:\\"\[\]]\.?)+@(?:[^\s\000-\037\177\(\)<>@,;:\\\"\[\]]\.?)+\.[a-z]{2,6}';

**Comment by Guite** [comment]
Following the discussion linked above I guess we might change it to `{2,64}`?

**Comment by Kaik** [comment]
@Guite :+1: I guess that would be the best solution.
@craigh That pattern might be, really really old thing like postnuke old...
