### ISSUE TITLE
Broken Tests

### ISSUE THREAD

**Issue by craigh** [zikula/core#3984]
Please fix broken tests in travis build for 2.0 branch.

https://travis-ci.org/zikula/core/jobs/612255094

I'm guessing you broken them with recent changes in translation stuff.

**Comment by Guite** [comment]
> recent changes in translation stuff

no, this is not related (tests were broken earlier)

the error message is:
> Unable to find template "TestBundle:Apple:view.html.twig"

I will take a look...

**Comment by Guite** [comment]
Fixed by 28dd690

**Comment by craigh** [comment]
excellent. thank you!

**Comment by Guite** [comment]
fyi: another possibility would have been changing `@Template` like shown here: https://github.com/zikula-modules/Legal/commit/b3ea3642fa021936c807e0587eb694dac35f54ad
But since it is only a test bundle I didn't mind.
