### ISSUE TITLE
Remove bundle states

### ISSUE THREAD

**Issue by Guite** [zikula/core#3996]
First changes were done here:

- https://github.com/zikula/core/commit/57b9971b5de5d9d6c93d89ef5b6e82471ad17725
- https://github.com/zikula/core/commit/777bf3a91cb5662c4205ef246111a1b91dd393a0

Slightly refs #3644

@craigh can you elaborate a bit about the motivation?

**Comment by craigh** [comment]
I don't see that states have been used (for bundles not modules/themes) at all, so it makes sense to remove them.

**Comment by craigh** [comment]
@Guite I think this is finished as is. We could just remove all the state stuff immediately (would need to alter the bundles table) at Core 3.0 if you prefer. Or we can leave as is until 4.0. WDYT?

**Comment by Guite** [comment]
Maybe as part of #3644 ? :thinking:

**Comment by craigh** [comment]
for me this question is more about 3.0 vs 4.0 for this specific thing

#3644 should _probably_ happen in 3.0 but I'm unsure if we want to do that yet

**Comment by Guite** [comment]
> We could just remove all the state stuff immediately (would need to alter the bundles table) at Core 3.0 if you prefer. Or we can leave as is until 4.0.

I've no real preference but tend to "let's do it now", because Symfony 5 and Twig 3 bring several BC breaks anyway. 4.0 should rather focus on functional enhancements again.

**Comment by craigh** [comment]
some work done in 1c11c0e44b6845eddf1bd7a250dab7b6b4f0821b

**Comment by craigh** [comment]
closed with c2307b151d7462ae95b9d1769b029236f1270680
