### ISSUE TITLE
[General] HTML5 Application cache for admin interface

### ISSUE THREAD

**Issue by jusuff** [zikula/core#400]
Utilize html5 application cache mechanism for admin (and similar) interfaces.

Implementation should include:
- caching static content via application cache
- using local/session storage for saving data

Application cache (https://developer.mozilla.org/en/Using_Application_Cache) is more persistent than a regular browser cache, so we can avoid loading unnecessary elements (css, js, images). It also work offline, but we wont be able to use this.
We should also think about caching all static content (including HTML) as wrapper and loading dynamic contents via Ajax (eg using something like pjax: https://github.com/defunkt/jquery-pjax)

Local/session storage (https://developer.mozilla.org/en/DOM/Storage) could serve as temporary data storage. Right now I could imagine using it for saving drafts - for example News module could implement mechanism for autosaved in 1 minute interval drafts, which do not need serve-side code.

Both these elements are intended to improve performance of admin interfaces.

**Comment by Guite** [comment]
refs https://github.com/zikula-ev/Formicula/issues/35

**Comment by Guite** [comment]
Closing as won't fix.
