### ISSUE TITLE
Convert to Symfony Mailer Component

### ISSUE THREAD

**Issue by craigh** [zikula/core#4000]
remove SwiftMailer and use Symfony Mailer Component

**Comment by craigh** [comment]
https://symfony.com/blog/new-in-symfony-4-3-mailer-component

https://symfony.com/doc/current/components/mailer.html

https://symfony.com/doc/current/mailer.html

**Comment by Guite** [comment]
:four: :zero: :zero: :zero:

**Comment by Guite** [comment]
Also relevant:
https://speakerdeck.com/fabpot/mailer (recommended)

https://symfony.com/blog/new-in-symfony-4-3-mime-component

https://github.com/twigphp/inky-extra (already included in the core)
https://github.com/foundation/inky

https://symfony.com/blog/new-in-symfony-4-4-notification-emails (nice!)

https://symfony.com/blog/new-in-symfony-4-4-signing-and-encrypting-email-messages

provocative question: do we still need our Mailer module? we could move configuration and test pages to Settings and drop our mailer api in favour of direct usage of `TemplatedEmail` and `NotificationEmail`. But, one nice aspect of our api is that it dispatches several events, which can for example be used to add a common header/footer to emails or similar use cases.

**Comment by Guite** [comment]
For reference: this should be done in 3.0.0 because: it could be that MailerApi will change; also there are BC breaks with mailer transports anyway - see #3967 - because SwiftMailer removed some transports, so let's do the big/whole break in 3.0.0 then.

**Comment by craigh** [comment]
I'm doing this next.

**Comment by craigh** [comment]
> we could also think about installing more transports on demand

all the available transports are installed when doing `require symfony/symfony` (unless there are third party transports, but we shouldn't include those anyway)
