### ISSUE TITLE
Support migrating sessions

### ISSUE THREAD

**Issue by Guite** [zikula/core#4009]
Symfony allows migration when switching between session handlers.
Information and example can be found here: https://symfony.com/blog/new-in-symfony-4-1-session-improvements#allow-to-migrate-sessions

**Comment by craigh** [comment]
why is this valuable?

**Comment by Guite** [comment]
Currently all users are enforced to be logged out when sessions are switched between filesystem to database.
Of course this is a very low priority.

**Comment by craigh** [comment]
is this related to #3898 ?

it appears this was solved in an intentionally hacky way - perhaps this is the proper solution?

**Comment by Guite** [comment]
No #3898 and #3986  are related to stricter rules in PHP 7.2+ while #4009 is only about switching between filesystem and database.

**Comment by Guite** [comment]
Decided with @gfr that the effort does not pay off for our use case. Closing as "won't fix".
