### ISSUE TITLE
Replace JMS Translation Bundle by php-translation

### ISSUE THREAD

**Issue by craigh** [zikula/core#4012]
JMS Translation Bundle appears to be left undeveloped and is currently disabled in travis builds. 

here is a potential replacement

https://github.com/php-translation/symfony-bundle

Since I don't use translations, I'm not sure how to proceed. Perhaps we need nothing, if we will be removing all custom translation mechanisms. 

Maybe we should begin a different ticket outlining the exact needs and potential package solutions for all Translation issues.

@Guite

**Comment by Guite** [comment]
Like the idea.

With it's [WebUI](https://php-translation.readthedocs.io/en/latest/symfony/webui.html) it can also cover/replace https://github.com/zikula/core/issues/2425#issuecomment-437568828

Refs also #3551 and #3941 - possible drop of custom stuff.

Give me a few days to eliminate some other topics. Will reflect this.
