### ISSUE TITLE
Github action should fail when buildReleaseArtifacts.sh fails

### ISSUE THREAD

**Issue by craigh** [zikula/core#4024]
The GitHub action should fail the build when buildReleaseArtifacts.sh ends with Fatal errors, etc. Currently it seems to ignore such errors and continue with the build and claims success.

**Comment by Guite** [comment]
From what GitHub states in [this doc](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference) it looks like exit codes are processed.

From what I've experienced this usually works. But it could be that some specific commands return no specific error codes or something.

Closing this for now.
We'll investigate any concrete problems when/if they occur.
