### ISSUE TITLE
twig/string-extra v3.0.1 requires php ^7.2.9

### ISSUE THREAD

**Issue by craigh** [zikula/core#4030]
scrutinizer reported:
> twig/string-extra v3.0.1 requires php ^7.2.9 -> your PHP version (7.2.5) does not satisfy that requirement.

we currently only require 7.2.5 (same as Symfony min)

**Comment by Guite** [comment]
Created a PR at https://github.com/twigphp/Twig/pull/3233

**Comment by Guite** [comment]
The PR has been merged. So this change will be part of the next Twig release.
