### ISSUE TITLE
Custom makers instead of GeneratorBundles

### ISSUE THREAD

**Issue by Guite** [zikula/core#4034]
[ZikulaGeneratorBundle](https://github.com/zikula/GeneratorBundle) is currently not included in the CoreBundle anymore. Also the docs [have been removed](https://github.com/zikula/core/commit/73bc630701be758c1d4840a600a210fde69b3d6a).

We need to decide about whether it will be continued (not probable) or replaced by an extension of Symfony's new maker bundle (probable). The old repository needs to be archived then.

Reading material:

- https://symfony.com/blog/introducing-the-symfony-maker-bundle
- https://symfony.com/blog/new-and-improved-generators-for-makerbundle
- https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html  (particularly "Creating your Own Makers")

**Comment by craigh** [comment]
making some progress on this one.

**Comment by craigh** [comment]
closed by https://github.com/zikula/core/pull/4226
