### ISSUE TITLE
[RFC] Drop custom Translation system

### ISSUE THREAD

**Issue by craigh** [zikula/core#4042]
we should completely remove all customized Translation system and migrate immediately to only using Symfony in all files (PHP, Twig, etc)

This would mean (at least) 
 - removing all calls to `__()` `__f()` `_n()` and `_fn()`
 - remove references to `\Zikula\Common\Translator\TranslatorInterface`
 - remove references to `\Zikula\Common\Translator\Translator`
 - remove references to `\Zikula\Common\Translator\IdentityTranslator`
 - remove references to `\Zikula\Common\Translator\TranslatorTrait`
 - removing all custom extractors
 - moving all translations to `.xliff` format (or another if desired)

This _could also_ mean changing all translation keys to unique identifiers instead of English language strings. But I would prefer that this ticket focus only on removal and making translation functional. Changing keys is also a gigantic job and should be separate (and further discussed please)

refs (and probably closes or replaces)
#4012
#3955 
#3951 
#3941 
#3650 
#3397 
#2425 
#1895 
#3551

**Comment by Guite** [comment]
:+1: 

#3397  seems not related though because this is about multilingual data (Doctrine translatable extension).

**Comment by craigh** [comment]
replacing translation functions in twig templates may be be as easy as hoped with rector: https://github.com/rectorphp/rector/issues/2554

**Comment by Guite** [comment]
Here are some recent articles about translation news in Symfony which could perhaps be helpful.

- https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md
- https://symfony.com/blog/new-in-symfony-4-2-intlmessageformatter
- https://symfony.com/blog/new-in-symfony-4-2-translation-related-improvements
- https://symfony.com/blog/new-in-symfony-4-3-improved-form-translation
- https://symfony.com/blog/new-in-symfony-4-3-extracting-translation-contents-from-php-files
- https://symfony.com/blog/new-in-symfony-4-4-misc-improvements-part-1#allow-to-sort-translation-messages

**Comment by Guite** [comment]
About `translations/`: personally I like using `yaml` instead of `xliff` :+1:

**Comment by Kaik** [comment]
```xliff``` is sooo bad I have no idea why would someone even consider using it

**Comment by craigh** [comment]
well the upside of switching to native symfony is that if someone wants a different format, they can extract it themselves and they're all set. :smile:

**Comment by Kaik** [comment]
@craigh I think we can do it with our current system as well, I do not remember but since I like overengineering things it is highly probable I have added support for other formats as well :) I might be wrong but as far as I remember actual format is irrelevant... it was our file naming that was relevant...

I'm not sure where but I read somewhere on syfmony blog/git or somewhere there that they do not like ```xliff``` format as well and prefer ```yaml``` ...hmm maybe it was related to service definitions where I prefer ```yaml``` over ```xml``` as well :)

**Comment by craigh** [comment]
closing this. most of the work is complete. other issues with need addressing separately I think
