### ISSUE TITLE
Replace system module icons

### ISSUE THREAD

**Issue by craigh** [zikula/core#4044]
replace system module icons with something more 'flat' and contemporary looking.

**Comment by Kaik** [comment]
An example form https://github.com/Kaik/KaikmediaAdminLTETheme
![dark neon](https://user-images.githubusercontent.com/966910/71788947-84e9e400-3027-11ea-9aa6-b72d7339b6ed.jpg)

**Comment by craigh** [comment]
![Screen Shot 2020-01-12 at 1 48 57 PM](https://user-images.githubusercontent.com/350048/72223932-4df16200-3542-11ea-8303-e18b8c205f6e.png)
