### ISSUE TITLE
Consider using twig-inspector

### ISSUE THREAD

**Issue by Guite** [zikula/core#4051]
Development tool:
https://github.com/oroinc/twig-inspector

Docs:
https://github.com/oroinc/twig-inspector/blob/master/Bundle/Resources/doc/usage.md

Looks interesting. Don't need it personally though.

Opinions?

**Comment by Guite** [comment]
Opinions? @craigh @rallek @gfr @Kaik @paustian

**Comment by Kaik** [comment]
:+1: looks like it can speed up debugging templates in some cases I wonder how it works with complicated stuff...

**Comment by Guite** [comment]
Will do a quick test whether this would be an adequate replacement for our `TemplateNameExposeListener`.

**Comment by Kaik** [comment]
From gifs and pictures it looks like it is a whole template inspector similar to chrome dev tools but for twig templates...

**Comment by Guite** [comment]
Added PR at #4100

**Comment by Guite** [comment]
Fixed by #4100
