### ISSUE TITLE
[General] Utilise String component

### ISSUE THREAD

**Issue by Guite** [zikula/core#4053]
We should use the string component of Symfony 5 to make string operations both more readable and more solid (less prone to errors).

https://symfony.com/blog/new-in-symfony-5-0-string-component
https://symfony.com/doc/current/components/string.html

We should wait until Symfony 5.1 is available though so that we can rely on the API.

**Comment by craigh** [comment]
Where would this be useful/appropriate (as an example?) Or what is the ideal use case?

**Comment by Guite** [comment]
The ideal use case for me is simplifying string operations (like [here](https://symfony.com/blog/new-in-symfony-5-0-string-component#object-oriented-strings)), especially when multiple ones are combined. One candidate is [the Merger class](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/Asset/Merger.php) for example, but we will have several others.

**Comment by Guite** [comment]
Some interesting sections:
https://symfony.com/doc/current/components/string.html#methods-to-append-and-prepend
https://symfony.com/doc/current/components/string.html#methods-to-search-and-replace
https://symfony.com/doc/current/components/string.html#methods-to-join-split-and-truncate

**Comment by Guite** [comment]
https://symfony.com/blog/new-in-symfony-5-1-string-improvements
