### ISSUE TITLE
Setup subtree split

### ISSUE THREAD

**Issue by Guite** [zikula/core#4059]
After #4052 and #3644 at least.

Motivation: ability to target system modules/themes individually with composer in order to treat them as vendors.

Example:
- https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Cache
- https://github.com/symfony/cache

Resources:
- https://stackoverflow.com/questions/31910365/how-does-symfony-manage-component-sub-packages-with-git-and-composer
- https://getcomposer.org/doc/04-schema.md#replace
- https://getcomposer.org/doc/05-repositories.md#path
- https://github.com/symfony/symfony/blob/master/link
- https://github.com/splitsh/lite
- https://www.subtreesplit.com/

Additional notes:
- `wikimedia/composer-merge-plugin` can probably be removed afterwards.

**Comment by craigh** [comment]
more possibility: https://getcomposer.org/doc/05-repositories.md#path

**Comment by Guite** [comment]
`wikimedia/composer-merge-plugin` can probably be removed afterwards.

**Comment by craigh** [comment]
https://getcomposer.org/doc/04-schema.md#replace

**Comment by Guite** [comment]
https://github.com/symfony/symfony/blob/master/link

**Comment by Guite** [comment]
Collected links above and added brief summary of motivation behind this.

**Comment by craigh** [comment]
implemented partially.

 - [x] slave repos created.
 - [x] account/project created at subtreesplit.com
 - [x] webhook installed at zikula/core
 - [x] test push was successful to push to slave zikula/core-bundle

but subsequent pushes were not successful. I am working with @nyholm (the author) to resolve.

**Comment by craigh** [comment]
the subtree split is complete.
