### ISSUE TITLE
Add an option member variable to the Hooks class

### ISSUE THREAD

**Issue by paustian** [zikula/core#4060]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.0
| PHP Version       | >7

## Summary
Add a class member variable to the Hook class that can be accessed by class children.

## Desired Behavior
During the use of a Hook in a template a new variable, options, would be added that could then be accessed by the HookProvider. For example:

`{{ notifyDisplayHooks(constant('HookSubscriberClass::ARTICLE_DISPLAY'), article.aid|default(null), return_url, **options**) }}`

This should be as flexible as possible to allow the passing of variables. Maybe an array?

## Possible Solution

1. Add a new class member variable to Hook.php
2. In Zikula\Bundle\HookBundle\Twig\Extension\HookExtension add another parameter to the Twig Extension that adds an options variable.

## Context
I am working on the EZComments module. A requested feature is to have the ability to post the number of comments somewhere in the template of the module that is Hooked to this module. If I had an options parameter I could have the UI hook test the options parameter and either return the number of comments or the comments depending upon what was requested.

**Comment by Kaik** [comment]
This is not the way it works. I remember when Drak schooled me on this as well...
So hooks do not work this way, they are agnostic which means sides do not know about each other...
Options you have are:
hook settings - when you bind provider to a subscriber in a specific area you can have settings for that area and there you/user can specify if this should be count only or display full.

separate areas - we (devs) use only default areas but actually we could/should use more than one area... so for example in news, for display  ```comments area```, ```comments count area```, ```last comment area``` - this is some sort of - it is not my problem solution but this is how it should work. News module designer do not have to worry about comments or any other additional module he just place hook area where he expects comments or only comments count... etc...

**Comment by Guite** [comment]
So better would be if Ez comments would offer different provider areas for the amount of comments (summary) and the list of comments (detail)?

**Comment by Kaik** [comment]
Yes this is the best way, these are technically different things to show, so should be represented as different areas.

**Comment by Guite** [comment]
Closed the issue following @kaik
