### ISSUE TITLE
Add the ability to delete stale pending registrations

### ISSUE THREAD

**Issue by paustian** [zikula/core#4069]
This should also be something the Core does automatically if the time to register expires.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.15
| PHP Version       | all

## Summary
Deleting all users should be a simple sql call to the database and implemented in UserRegistry. Since they are pending users, they should have no attachment to any other modules so removing them should not cause any consequences.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Have a button in the interface for users would be the simplest implementation. Pressing it gets rid of the users.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
After pressing it, an Are you Sure dialog would be nice. If yes, all stale pending users are deleted.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
My sites accumulate a ton of pending users. It woudl be nice to get rid of them.

**Comment by Kaik** [comment]
I think this feature should come with additional options like search options and pagination.
1. there might be huge amount of "pendings" and simple delete all will end up with 500...
2. search because sometimes you do want to filter by domain or date etc..
3. some modules can work on pending registrations so delete event will probably be fired anyway...

btw @paustian I guess your pendings are spam you can try to reduce them via banned email domains feature in settings module...

**Comment by Guite** [comment]
> via banned email domains feature in settings module...

-> Users module

**Comment by Kaik** [comment]
yes sorry

**Comment by Kaik** [comment]
since pending is "just" a status and 3party modules are handled by events anyway it may also be just an upgrade - improvements in users list #3953 

Main problem is that there is no proper way to target a specific group of users(including or not pendings) and then perform delete action on them.

**Comment by craigh** [comment]
I'll take this one (eventually)

**Comment by Kaik** [comment]
take a look on #3953 too and please consider databases like 40k+ users

**Comment by craigh** [comment]
@paustian. When we initially talked about this, I thought you were talking about automatic removal based on an expiry date. Your ticket indicates a more manual approach. which do you prefer?

**Comment by craigh** [comment]
ping @paustian

**Comment by paustian** [comment]
Craig, automatic woudl be best, but I would be happy with either. Sorry for the slow response, I am frantically getting my classes on for next week.

**Comment by craigh** [comment]
refs #3928
