### ISSUE TITLE
[UsersModule] [MultiDelete] Review current code responsible for user removall

### ISSUE THREAD

**Issue by Kaik** [zikula/core#4071]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.x.x
| PHP Version       | x.x.x

## Expected Behavior
Be able to search, then select(chose) then delete selected users (ajax)

## Current Behavior
manual user delete works, multiple user deletion does not work
error 500 when there is a lot of users in the database

## Possible Solution
Redesign user search and users list to one view with ajax capabilities selects and delete action.

## Steps to Reproduce
try to delete multiple users in 10k+ userbase, by email domain etc..., without an error

**Comment by Guite** [comment]
Basically duplicate of #3953

**Comment by Kaik** [comment]
So, I think I have already mentioned this somewhere or it was only in my mind ;)
The user deletion process for multiple users is bad, and it is bad because it uses sf forms with entity field which is getting filled with whole users table.

Apart from that deleting lots of users in one batch on page reload is another bad idea, perfectly we could delete all o them one by one in loop via ajax calls so even if one fails you could still carry on with other ones.

I have this thing semi working and in some sort of a "hack".

I think whole user ui could be improved and procedures specially delete users should be reviewed.

**Comment by Kaik** [comment]
@Guite lol true...
