### ISSUE TITLE
Reinvestigate design problem with session handling

### ISSUE THREAD

**Issue by Guite** [zikula/core#4078]
In `ZikulaSessionStorage` we still suppress warnings because of #3898.

refs https://github.com/symfony/symfony/issues/28577 and #3986

Detail description of the problem: https://github.com/zikula/core/issues/3898#issuecomment-398817307 -> "2. Clean but not that easy" section

A proper fix is required to make "remember me" functionality working again.

**Comment by craigh** [comment]
fixed for me!

**Comment by Guite** [comment]
:tada:
