### ISSUE TITLE
Errors in prod env

### ISSUE THREAD

**Issue by craigh** [zikula/core#4082]
# following install, these errors prevent normal execution

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3-dev
| PHP Version       | 7.3+

## Current Behavior
![Screen Shot 2020-01-25 at 10 04 27 AM](https://user-images.githubusercontent.com/350048/73123127-65751580-3f5a-11ea-827f-58dfea850ab1.png)

ALSO

> [2020-01-25T10:04:05.464813-05:00] request.INFO: Matched route "zikulathememodule_combinedasset_asset". {"route":"zikulathememodule_combinedasset_asset","route_parameters":{"_route":"zikulathememodule_combinedasset_asset","_controller":"Zikula\\ThemeModule\\Controller\\CombinedAssetController::assetAction","_zkBundle":"ZikulaThemeModule","_zkModule":"ZikulaThemeModule","_zkType":"combinedAsset","_zkFunc":"asset","type":"js","key":"bootstrap.bundle.min.js.map","_locale":"en"},"request_uri":"http://127.0.0.1/core.git/src/theme/combined_asset/js/bootstrap.bundle.min.js.map","method":"GET"} []
> [2020-01-25T10:04:05.533358-05:00] request.CRITICAL: Uncaught PHP Exception Exception: "Combined Assets not found" at /Applications/MAMP/htdocs/core.git/src/system/ThemeModule/Controller/CombinedAssetController.php line 40 {"exception":"[object] (Exception(code: 0): Combined Assets not found at /Applications/MAMP/htdocs/core.git/src/system/ThemeModule/Controller/CombinedAssetController.php:40)"} []

**Comment by Guite** [comment]
Fixed by #4091
