### ISSUE TITLE
Utilise locale field in UserEntity

### ISSUE THREAD

**Issue by Guite** [zikula/core#4098]
We have a locale field in the UserEntity, but it seems this is not used consistently yet. Well, at least the LocaleListener uses the property already ([source](https://github.com/zikula/core/blob/master/src/system/SettingsModule/Listener/LocaleListener.php#L33-L34)).

Check and extend the system for the following functionality:

- [x] persist the locale a user used during his registration (if he for example registered on a German version of a site, then the system should remember that this user prefers German)
- [x] update the locale preference whenever a user changes the language in his account panel (this is already done)
- [x] automatically switch to the preferred language after login (already done)

**Comment by Guite** [comment]
> not used yet

At least the LocaleListener uses the property already ([source](https://github.com/zikula/core/blob/master/src/system/SettingsModule/Listener/LocaleListener.php#L33-L34)).

**Comment by Guite** [comment]
maybe if an admin creates a user it should just be the default lang to save the effort; the user can select a custom language after logging in

**Comment by craigh** [comment]
@Guite please feel free to complete this if you are motivated to do it. I Think 3.0 is a good milestone for this ticket.

**Comment by Guite** [comment]
It turns out that only the first point of the list above was missing (added that in e1330d6). The other two points were already in place.
