### ISSUE TITLE
javascript loading too slowly

### ISSUE THREAD

**Issue by craigh** [zikula/core#4104]
![Screen Shot 2020-02-02 at 2 50 35 PM](https://user-images.githubusercontent.com/350048/73614304-c1c7dd00-45cb-11ea-910a-09ead6f58c11.png)

`routing` and `translations` take up to 15 seconds to load. We need to figure out a way to dump theses to a file or cache or something. (I tried the RoutesModule -> dump... and nothing changed)

**Comment by craigh** [comment]
maybe this is because I am in `dev` mode. `prod` had better be faster.

**Comment by Guite** [comment]
if these are sub requests the profiler listener consumes time in `dev` I guess

**Comment by Guite** [comment]
`routing` is prepared but waits for a vendor fix: https://github.com/zikula/core/blob/master/src/system/ThemeModule/EventListener/DefaultPageAssetSetterListener.php#L147-L152

`translation` has a dumper which would probably need to be enhanced to be used for several bundles
  - https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md#the-dump-command
  - https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Dumper/TranslationDumper.php
  - it uses a TranslationFinder receiving resource file paths from the framework bundle: 
https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/config/services.xml#L13

**Comment by craigh** [comment]
after dumping js translations with the dump command, it _feels_ faster.
I also have a `public/js/fos_js_routes.en.js ` file. I'm not sure why

**Comment by Guite** [comment]
Because Routes module dumps the routes files. They are not loaded yet though to avoid vendor issues with routes having i18n not disabled (remember your workaround change in cb9454816112e612ceabbb7f1185b11644765af0).

**Comment by craigh** [comment]
I think this problem became apparent because I was working with the Extensions list over and over. As shown in #4264, the cache is deleted and reloaded too many times there. I see in my local testing now (in prod env) that it still takes 15+ seconds to load but I suspect the real problem is that the translation and routing files are deleted (along with everything else) and this causes the delay. So from this perspective, I think this ticket can be closed.

If there is anything we can do to speed up either of these things, then we should do it. We can leave this ticket open in order to do that. I leave that up to @Guite

**Comment by Guite** [comment]
Closing for now.

Routing is prepared but waits for a vendor patch or #4027 - so it _will_ be done, just not now.

The JS translation topic will come up again when we start working on encore, webpack etc.
