### ISSUE TITLE
more NS changes

### ISSUE THREAD

**Issue by craigh** [zikula/core#4108]
As a result of both modules and themes becoming extensions, I would now also like to make the following moves:

```php
\Zikula\Bundle\CoreBundle\AbstractBundle -> \Zikula\ExtensionsModule\AbstractExtension
\Zikula\ThemeModule\AbstractCoreTheme ->  \Zikula\ExtensionsModule\AbstractCoreTheme
\Zikula\ThemeModule\AbstractTheme ->  \Zikula\ExtensionsModule\AbstractTheme
```

note that `AbstractBundle` is also a name change to `AbstractExtension`

@Guite opinions?

**Comment by Guite** [comment]
okay for me
