### ISSUE TITLE
A module should let the core know if it supports categorization and on which Doctrine Entities

### ISSUE THREAD

**Issue by tfotis** [zikula/core#411]
During the Categories refactoring to Doctrine 2, i came upon some issues regarding Category registry that need to be dealt with in the future.

First of all, not all modules support categorization, but in Category registry -> Choose module, the user can see all the installed modules. This is bad usability. So in order to solve this, a module should let the core know if indeed it supports categorization. If it does, it will be listed inside the select box. If it doesn't, it will not.

Second, not all entities of the module support categorization, but in Category registry -> Choose entity, the user can see all entities of the module. bad usability again. The module should let the core know, which of it's entities support categorization. If they do, they will be listed inside the select box.

**Comment by craigh** [comment]
I believe this was complete in Core-1.4.0

**Comment by Guite** [comment]
Yes: https://github.com/zikula/core/blob/1.4/src/system/CategoriesModule/Controller/AdminController.php#L279
