### ISSUE TITLE
Extension Filter doesn't work

### ISSUE THREAD

**Issue by craigh** [zikula/core#4110]
The extension filter doesn't appear to do anything.

![Screen Shot 2020-02-05 at 5 40 27 PM](https://user-images.githubusercontent.com/350048/73889918-bdefc100-483e-11ea-96de-83ccce27a877.png)
![Screen Shot 2020-02-05 at 5 40 33 PM](https://user-images.githubusercontent.com/350048/73889919-bf20ee00-483e-11ea-85b1-f3e004b61193.png)
![Screen Shot 2020-02-05 at 5 40 40 PM](https://user-images.githubusercontent.com/350048/73889921-c0eab180-483e-11ea-8fac-622bc4d4fd22.png)
![Screen Shot 2020-02-05 at 5 40 49 PM](https://user-images.githubusercontent.com/350048/73889924-c2b47500-483e-11ea-9324-76d22c467e8e.png)

correction - 'hide modules' hides only 3rd party modules.

imo - 'hide modules' should hide ALL modules. 'hide themes' should hide ALL themes. `hide core extensions` should hide ALL core extensions (modules and themes)

**Comment by Guite** [comment]
> imo - 'hide modules' should hide ALL modules. 'hide themes' should hide ALL themes. hide core extensions should hide ALL core extensions (modules and themes)

I already anticipated the current buttons will lead to different expectations.

imo - 'hide modules' should hide all 3rd party modules for 'show core extensions' but hide all modules for 'hide core extensions'.

Both variants contain contradictions. Open for suggestions.

**Comment by craigh** [comment]
They should be exclusive. not combineable. when a second is selected it should turn off other selections and only do its one thing. 

> imo - 'hide modules' should hide ALL modules. 'hide themes' should hide ALL themes. hide core extensions should hide ALL core extensions (modules and themes)
