### ISSUE TITLE
normalize line endings to unix `\n`

### ISSUE THREAD

**Issue by craigh** [zikula/core#4112]
I would like to normalize all our line endings to unix-style and then attempt to keep them that way.

here is a script that can do this

https://gist.github.com/ajdruff/16427061a41ca8c08c05992a6c74f59e

opinions?

**Comment by craigh** [comment]
also I would do the va extensions

**Comment by Guite** [comment]
do it

**Comment by craigh** [comment]
This could be done. I'm not sure.

**Comment by Guite** [comment]
Ref: 1d4f77a4b3a0bb0061608edbc4524a8e08b28de0
