### ISSUE TITLE
make more public services private?

### ISSUE THREAD

**Issue by craigh** [zikula/core#4115]
https://github.com/zikula/core/blob/0e09cf99c2947552b5382a5e5ec6cb11e9eac763/src/system/ExtensionsModule/Resources/config/services.yaml#L22

is there any way to test some of these again? I think many of them no longer need to be public anyway due to refactoring since the original conversion.

**Comment by Guite** [comment]
search for `get(TheType::class)` in whole `src/` directory?

**Comment by craigh** [comment]
how did you figure it out in the first place when you refactored all that?

**Comment by Guite** [comment]
Exceptions where thrown like "could not access xy service using container because it is private".

**Comment by Guite** [comment]
A service can be made private again if it is only injected, but not accessed via container anymore.
