### ISSUE TITLE
move icon out of capabilities

### ISSUE THREAD

**Issue by Guite** [zikula/core#4116]
Now that extensions have a dedicated icon field in their database table, how about reflecting this in `composer.json`? This would also make the `BundleSyncHelper` a bit less complex again.

Current:

```
    "extra": {
        "zikula": {
            "class": "Zikula\\MenuModule\\ZikulaMenuModule",
            "core-compatibility": ">=3.0.0",
            "displayname": "Menu Module",
            "capabilities": {
                "admin": {
                    "route": "zikulamenumodule_menu_list",
                    "icon": "fas fa-compass"
                }
            },
            "url": "menu",
            "securityschema": {
                "ZikulaMenuModule::": "::",
                "ZikulaMenuModule::id": "::id"
            }
        }
    }
```

Proposed:

```
    "extra": {
        "zikula": {
            "class": "Zikula\\MenuModule\\ZikulaMenuModule",
            "core-compatibility": ">=3.0.0",
            "displayname": "Menu Module",
            "icon": "fas fa-compass",
            "capabilities": {
                "admin": {
                    "route": "zikulamenumodule_menu_list"
                }
            },
            "url": "menu",
            "securityschema": {
                "ZikulaMenuModule::": "::",
                "ZikulaMenuModule::id": "::id"
            }
        }
    }
```

**Comment by Guite** [comment]
In the same step I would change all PHP requirements to `">=7.2.0"` and reorder fields where appropriate (e.g. above the `url` should be moved above `capabilities`).

**Comment by Guite** [comment]
In the same step I would change all PHP requirements to `">=7.2.5"` and reorder fields where appropriate (e.g. above the `url` should be moved above `capabilities`).

**Comment by craigh** [comment]
would `icon` be required? The composer.json file validator (and schema) would also need to be updated. Not settled on my feelings about this yet.

**Comment by Guite** [comment]
We decide whether it is required or not.

**Comment by craigh** [comment]
> We decide whether it is required or not.

I'm wondering what you thought/planned about that.

**Comment by Guite** [comment]
I've not really a preference.

We could make it required, because the icon is not only used for admin pages, but also in the module header which is included in user pages (for example `/public/groups/list` or `/public/profile/display/2`).

We could also have it optional, because we could fall back to a default icon.

I tend a bit to requiring it.

**Comment by craigh** [comment]
Yes. let's do this. The icon should be required.
> The composer.json file validator (and schema) would also need to be updated.

**Comment by Guite** [comment]
Remove these old permission rules:

- https://github.com/zikula/core/blob/master/src/system/BlocksModule/composer.json#L38
- https://github.com/zikula/core/blob/master/src/system/BlocksModule/composer.json#L42-L44
