### ISSUE TITLE
BootstrapTheme UX and visual improvements 

### ISSUE THREAD

**Issue by Kaik** [zikula/core#4120]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.x.x
| PHP Version       | x.x.x

## Summary
I have not seen BootstrapTheme for a while and when I saw current master I think things are off... like font sizes and weights both user and admin view... something is not right there...

but this is not important one just what I think happened during core3 dev

**Comment by craigh** [comment]
"things are off..." is not a valid ticket.

**Comment by Kaik** [comment]
Well I cannot describe it better, it is like design feels it is not consistent "things are off" like menu items optically are not aligned, font sizes and weights are all "screaming" hmm hard to describe what is "off" because I'm not a graphic designer. I know it looks "wrong" generally.

**Comment by Guite** [comment]
Some aspects about this:

1. Naturally some things might not look ideal after the migration from Bootstrap 3 to Bootstrap 4.
2. Bootstrap 4 looks different in and of itself compared to Bootstrap 3.
3. Please understand that a general statement about this does not help us to improve this.
4. When you switch between all the different Bootswatch designs that are now included in the Bootstrap theme you will see that things become even more complex. For example _United_ looks pretty well while _Darkly_ does not yet.
5. So please create concrete tickets about concrete issues. Ideally describe current and excepted UI using screenshots.
