### ISSUE TITLE
ignore tests in release

### ISSUE THREAD

**Issue by craigh** [zikula/core#4128]
https://symfony.com/blog/new-in-symfony-4-4-misc-improvements-part-1#added-gitattributes-to-remove-tests

when we build a release we should ignore our tests like symfony does

**Comment by craigh** [comment]
This isn't working as I expected despite https://github.com/zikula/core/commit/674594a99d6a35b8248ae299a8a498782a42f457

maybe this is impossible?

**Comment by Guite** [comment]
Actually it *does* work.

Here is what I did:

```shell
git clone git@github.com:zikula/distribution.git
cd distribution/
composer install --prefer-dist
```

Afterwards there are no test artifacts in `vendor/zikula/`.

To make composer using `prefer-dist` by default we would need to change `"zikula/core-bundle": "dev-master",` in the distribution's `composer.json` file to a stable version.

From https://getcomposer.org/doc/03-cli.md :

> For stable versions Composer will use the `dist` by default.

**Comment by craigh** [comment]
closing in favor of https://github.com/zikula/distribution/issues/10
