### ISSUE TITLE
admin layout issues

### ISSUE THREAD

**Issue by craigh** [zikula/core#4136]
I would prefer the `label` for radio buttons please show on the left like other labels.

Also - I think we should replace all the fieldsets with bootstrap cards. but this is a big job

![Screen Shot 2020-02-17 at 12 58 31 PM](https://user-images.githubusercontent.com/350048/74676945-36cb1300-5185-11ea-9d78-23b3e986b8e1.png)

**Comment by craigh** [comment]
here is using a card instead of fieldset

![Screen Shot 2020-02-20 at 5 23 44 AM](https://user-images.githubusercontent.com/350048/74924844-2c856080-53a1-11ea-84f0-07e6c6f2d71f.png)

**Comment by Guite** [comment]
Maybe it would be both a bit less work and beneficial to combine both things to something like this:

```html
<fieldset class="card">
    <div class="card-body">
        <h5 class="card-title">Fieldset title</h5>
    </div>
</fieldset>
```

*If that works* it would also have the advantage that we keep the (more semantic) `fieldset` tag instead of using only `div` elements.

**Comment by craigh** [comment]
Problem with the legend tag

**Comment by craigh** [comment]
![Screen Shot 2020-03-08 at 2 27 27 PM](https://user-images.githubusercontent.com/350048/76168766-01dd2b00-6149-11ea-880c-4f9ed5acea44.png)

icons are not set properly on install any longer

**Comment by craigh** [comment]
![Screen Shot 2020-03-22 at 8 53 52 AM](https://user-images.githubusercontent.com/350048/77249898-a9af2a00-6c1a-11ea-89f9-99c531ddf286.png)

this is the minor change I made. no more stripe under the legend.
