### ISSUE TITLE
Gmail uses port 25, no option to change

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#4142]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.15
| PHP Version       | 5.6.40

## Expected Behavior

After configuring the gmail option in Mailer, I expect it to send mail successfully in test mode.

## Current Behavior

There is not a field to set the port in the Gmail option. I presumed it was hard coded to Gmail's preference, 465.

However when sending a test message, I get an error that the server could not be contacted.  I believe the stack trace showed that a variable for "port" showed 25.

## Possible Solution

Either set a default value to 465, or preferably expose the port variable to the Gmail configuration page so that it can be set manually.

Workaround: Switch to smtp and set the port to 465.  Switch back to Gmail and fill everything out again.  This time it works.  So apparently it is using the smtp port variable even though it's not configurable on the gmail page.

## Steps to Reproduce

1. Start with a clean install of Zikula with debug = true.  Never had mailer configured before.
2. Configure Gmail option
3. Send test mail to prove it fails.
4. Configure SMTP option with port = 465
5. Configure Gmail option again.
6. send test mail to prove it works.

## Context

I am aware the Swiftmailer has been deprecated.  Perhaps this would still be an issue anyway.

**Comment by Guite** [comment]
Fixed in  ff01407
First I added a new form field, but then I switched to just setting the correct port without possibly confusing the user.

**Comment by robbrandt** [comment]
Thanks!
