### ISSUE TITLE
Review bundle creation state

### ISSUE THREAD

**Issue by Guite** [zikula/core#4148]
Check if the `bundles` stage (`$this->createBundles()`) may be removed from the installer, since all core bundles are hard-coded & loaded in kernel.

See https://github.com/zikula/core/blob/master/src/Zikula/CoreInstallerBundle/Helper/StageHelper.php#L107-L108

It *could* be interesting to keep it for custom distributions maybe?
Refs #2234 and #2130

**Comment by craigh** [comment]
$this->bundlesSchemaHelper->load();

creates the table (if it hasn't been). So if the entire routine is removed, we would still need to run the part that creates the table.

**Comment by Guite** [comment]
Then simply close this issue?
