### ISSUE TITLE
Remaining permission scheme for theme change

### ISSUE THREAD

**Issue by Guite** [zikula/core#4195]
Currently we define [this permission scheme](https://github.com/zikula/core/blob/master/src/system/ThemeModule/composer.json#L57) and create [example data here](https://github.com/zikula/core/blob/master/src/system/PermissionsModule/PermissionsModuleInstaller.php#L94-L101) and [here](https://github.com/zikula/core/blob/master/src/system/PermissionsModule/PermissionsModuleInstaller.php#L49-L58).

It isn't used yet/anymore though.

Re-implement permission check or remove it?

**Comment by craigh** [comment]
I vote for removal, but have no strong feelings. do as you wish.
