### ISSUE TITLE
admin user search not currently working

### ISSUE THREAD

**Issue by craigh** [zikula/core#4208]
`users/admin/search` doesn't work. related to recent changes with Paginator.

**Comment by Guite** [comment]
When trying to search for a part of a user name I get:

> Argument 1 passed to Zikula\UsersModule\Listener\UserEventListener::clearUsersNamespace() must be an instance of Zikula\UsersModule\Event\UserPostLogoutSuccessEvent, instance of Symfony\Component\HttpKernel\Event\ExceptionEvent given, called in /home/axel/projects/zikula/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php on line 117

**Comment by Guite** [comment]
It seems to be caused by that two different event types point to the same method:

```php
            UserPostLogoutSuccessEvent::class => ['clearUsersNamespace'],
            UserPostLoginSuccessEvent::class => ['setLocale'],
            KernelEvents::EXCEPTION => ['clearUsersNamespace']
```

**Comment by craigh** [comment]
that issue is not related to the actual problem, but is solved by https://github.com/zikula/core/commit/c1ad76dae510e300ea4326a3b372ed3eba2c2133
