### ISSUE TITLE
zauth_authentication_mapping not in sync with user table

### ISSUE THREAD

**Issue by paustian** [zikula/core#4218]
The zauth_atuthenticaion_mapping table will keep users in it that are unverified, but they get lost from the users table. This causes two results. One, said user can't log in. Two, the route /zauth/admin/list breaks.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.15
| PHP Version       | 7.3.5

## Expected Behavior

The zauth_atuthenticaion_mapping and users table should always be in sync

## Current Behavior

I am not sure how, but these two tables come out of sync. I think it has to do with verification because the failure only occurs for users that have not verified. In the below image, Ahaddad will show up in the user table and work just fine, but jdewitte, lmigliano, yarrington, and lrkoehler will not.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1325585/78458385-73d85f80-7676-11ea-8315-c0bf7615bb5a.png">

## Possible Solution
After doing some digging I found another bug that may be related to this. If I try to pull up the admin interface to the ZikukaNativeAuth it crashes with an error at Line 119 of AdministrationActionsHelper because this call is returning null.
$userEntity = $this->userRepository->find($mapping->getUid());

You can fix this error by checking for null.
if($userEntity != null) {do stuff}
However, that does not fix the issue. I think I brought this up before, but I could not find the related bug.

## Steps to Reproduce
I am not sure how to reproduce this.

**Comment by craigh** [comment]
@paustian how were these users created? did each person register on their own? admin created? imported? Are you using only ZAuth? (e.g. no other custom authentication modules?)

**Comment by craigh** [comment]
Looking into this. I believe I know the problem and will push a PR to fix it.

Ironically, I think the issue is directly related to #4069. There _was_ a routine to delete stale pending users, but it didn't delete **users** it only deleted the verification record... so in #4192, I thought I fixed that, but in reality, it was still only deleting the verification record. So, my PR fill take care of that as well.
