### ISSUE TITLE
[Blocks] theme install should add new blockpositions

### ISSUE THREAD

**Issue by craigh** [zikula/core#4228]
When a theme is installed, it should scan the theme.yaml file for blockpositions and then make sure those block positions are added to the available positions. On uninstall, maybe unique positions could be removed if they are not used by other themes (this could be more difficult tho).

**Comment by Kaik** [comment]
I think modules could use install block positions as well. Install own blocks as too... maybe it is possible now? is block api private?
I think manually removing positions would not be, a problem if you could select them and remove in batch all via js no page refresh just one confirmation, or mark unused etc... the js action to recreate missing positions form theme config etc... 

It is a very good idea, I have started using a lot of positions and blocks and creating them is a bit pain.
For example my news module uses like dunno 10+ positions news home page, news list page, news topic page, news display page each with at least 3-5 positions. 

And that is just one module...
