### ISSUE TITLE
[General] Use doctrine/migrations

### ISSUE THREAD

**Issue by craigh** [zikula/core#4241]
Consider using doctrine/migrations for upgrades

Have to wait until 3.0 is released.

https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/

**Comment by Guite** [comment]
https://odolbeau.fr/blog/doctrine-migrations-rollup.html

**Comment by Guite** [comment]
Closing as migrations can/will be used per bundle as part of replacing the old extension installer interfaces.
