### ISSUE TITLE
Cleanup public directory

### ISSUE THREAD

**Issue by Guite** [zikula/core#4257]
The subfolders in the `public/` directory should be grouped.

Proposal:
```
- bundles/
- components/
  - bootstrap/
  - bootswatch/
  - font-awesome/
  - fontawesome-iconpicker/
  - jquery/
  - jquery-ui/
  - jstree/
  - magnific-popup/
  - mmenu/
  - require/
- js/
- media/
- modules/
- overrides/
- themes/
- uploads/
```

**Comment by craigh** [comment]
why?

**Comment by Guite** [comment]
Because it looks sloppy.

Example from shopware:

```
- bundles/
- css/
- fonts/
- js/
- media/
- recovery/
- sitemap/
- theme/
- thumbnail/
```

**Comment by Guite** [comment]
I don't see that as critical. If you think it's unnecessary, we can drop it. But if we're gonna clean it up, we do it now, not after 3.0.0.

**Comment by craigh** [comment]
adding an additional layer of organization means altering `asset()` and other functioning items. I don't see a reason to do this.
