### ISSUE TITLE
improve ZikulaThemeModule.JSConfig.js or remove?

### ISSUE THREAD

**Issue by craigh** [zikula/core#4279]
currently ZikulaThemeModule.JSConfig.js is only defaults and doesn't appear to be overwritten or updated anywhere.

At the very least, the setting for ajax timeouts should be dynamic (or it should be removed from General settings) and the sessionName should be dynamic (from security settings). Or these will break anything using these vars. 

the other values seem to need either **updating** or removal. the UID is set to 2! that seems like a security risk.

I'm not sure the purpose of this file. perhaps the whole file can be removed?

@Guite will you please take this one when you can?

possibly refs https://github.com/zikula/core/issues/3908#issuecomment-619550320

**Comment by Guite** [comment]
Either I don't understand or this ticket is invalid.

- Default values for fallbacks are defined [here](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Resources/public/js/ZikulaThemeModule.JSConfig.js#L7).
- They are overridden [here](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Resources/public/js/ZikulaThemeModule.JSConfig.js#L20).
- The data used for override is defined [here](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Resources/views/Engine/JSConfig.html.twig#L1) (assigned from [here](https://github.com/zikula/core/blob/master/src/system/ThemeModule/EventListener/AddJSConfigListener.php#L96))

Please elaborate.

**Comment by craigh** [comment]
ok.

I completely misunderstood and did not see the overrides.

so, all is well, I suppose.
