### ISSUE TITLE
duplicate vendors

### ISSUE THREAD

**Issue by craigh** [zikula/core#4295]
we have two installs of `symfony/contracts` and two installs of `symfony/phpunit-bridge` in our vendor file. There may be other duplicates but I didn't look too carefully. I'm sure this isn't good.

refs https://github.com/symfony/symfony/issues/36730

**Comment by craigh** [comment]
![image](https://user-images.githubusercontent.com/350048/81293161-da1c1d80-903a-11ea-8368-c24fe2a2431f.png)

**Comment by craigh** [comment]
![Screen Shot 2020-05-07 at 8 15 34 AM](https://user-images.githubusercontent.com/350048/81293217-ef914780-903a-11ea-9e93-fd24a7dd47a3.png)

**Comment by craigh** [comment]
since we do not require either in `/src` this must be a result of the reconciliation of required vendors from other packages we do require. Therefore this is either a problem with composer directly or (more likely) with wikimedia/composer-merge-plugin

**Comment by craigh** [comment]
I was wrong above - in our main `composer.json` file we do require `phpunit-bridge`

    "require-dev": {
        "symfony/phpunit-bridge": "5.*"
    },

**Comment by craigh** [comment]
removing the above code from our main `composer.json` file therefore removes `bin/simple-phpunit` which is needed...

**Comment by craigh** [comment]
Xabbuh said
> There's nothing wrong with that. You have two packages coming with the classes/functions for the contracts (symfony/contracts and symfony/symfony). But only the classes provided by symfony/contracts will be registered for the autoloader.

https://github.com/symfony/symfony/issues/36730#issuecomment-625249897

**Comment by Guite** [comment]
https://github.com/zikula/core/pull/4298/files
https://github.com/symfony/contracts/compare/b3b9b70bfacfd204d352e7e7350e02c02c0fff78...cf1da70384da0d4e98593760955c4397a22175cc

**Comment by craigh** [comment]
closing this as it doesn't seem to be a real problem.
