### ISSUE TITLE
Default bootstrap never loaded with bootstrap theme

### ISSUE THREAD

**Issue by Guite** [zikula/core#4307]
## Expected Behavior

When setting bootstrap style to `default` plain bootstrap is used.

## Current Behavior

Cerulean is used instead.

Because for `default` the custom listener returns [here](https://github.com/zikula/core/blob/master/src/system/BootstrapTheme/Listener/BootstrapAssetSetterListener.php#L75-L77) and so Cerulean (defined in the theme's YAML file) is never removed.
Also [this check](https://github.com/zikula/core/blob/master/src/system/ThemeModule/EventListener/DefaultPageAssetSetterListener.php#L164) returns `false` so the default bootstrap file is never loaded.

**Comment by Guite** [comment]
Proposal:

move [this](https://github.com/zikula/core/blob/master/src/system/BootstrapTheme/Listener/BootstrapAssetSetterListener.php#L75-L77) below [this](https://github.com/zikula/core/blob/master/src/system/BootstrapTheme/Listener/BootstrapAssetSetterListener.php#L78-L80)

**Comment by craigh** [comment]
I was wrong. sorry. 🤷🏻‍♂️
