### ISSUE TITLE
Too large key

### ISSUE THREAD

**Issue by Guite** [zikula/core#4343]
`Specified key was too long; max key length is 767 bytes' while executing DDL: CREATE TABLE `groups` (gid INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, gtype SMALLINT NOT NULL, description VARCHAR(200) NOT NULL, state SMALLINT NOT NULL, nbumax INT NOT NULL, UNIQUE INDEX UNIQ_F06D39705E237E06 (name) ...`

temporary workaround: change 255 to 150 in https://github.com/zikula/core/blob/master/src/system/GroupsModule/Entity/GroupEntity.php#L44-L45 before starting the installer

**Comment by craigh** [comment]
related to https://github.com/zikula/core/issues/3784?

**Comment by craigh** [comment]
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by Guite** [comment]
same problem in Profile:
`user_property (id VARCHAR(255) NOT NULL`

**Comment by craigh** [comment]
I cannot see the issue in [Profile](https://github.com/zikula-modules/Profile/blob/master/Entity/PropertyEntity.php) Where is it?

it should only be a problem if a `key` is being created (primary key, unique key, etc)

**Comment by Guite** [comment]
`id` is a primary key
