### ISSUE TITLE
Avoid URL field for themes

### ISSUE THREAD

**Issue by Guite** [zikula/core#4353]
The URL field should be hidden (and not required) for themes.

![grafik](https://user-images.githubusercontent.com/277531/85264481-09fb7500-b471-11ea-8167-dbc2b630b3e8.png)

cc @gfr

**Comment by craigh** [comment]
why? you are even using one in the bootstrap theme.

**Comment by Guite** [comment]
Right. But it shouldn't be required then, should it?

**Comment by Guite** [comment]
If it should be required, then we need to add it to the theme's `composer.json`, like we do it for modules, too.

**Comment by craigh** [comment]
so, I **don't** think you actually used one in BootstrapTheme. (it appears the route is simply `/ajax/foo` instead of `/bootstrap/ajax/foo`

I don't see this as a bug. It is functional as is.

What case brought this up?

**Comment by Guite** [comment]
No specific case. It is just confusing if you want to edit the theme data and don't know what you need to input in the field which is empty but required.

**Comment by craigh** [comment]
ah - I see. then it is **not** functional as is.

still, the problem is bigger than a UI concern.

**Comment by Guite** [comment]
This will be done in two steps:

1. make the URL input field optional in 3.0.1 (but only for themes) in order to make the input form less confusing for people editing a theme.
2. postpone the issue for making the URL a requirement for themes meta data in 4.0.0
