### ISSUE TITLE
[Extensions] move Abstract Content classes to ContentModule

### ISSUE THREAD

**Issue by craigh** [zikula/core#4355]
\Zikula\ExtensionsModule\ModuleInterface\Content\AbstractContentType
    \Zikula\ExtensionsModule\ModuleInterface\Content\Form\Type\AbstractContentFormType

belong in the ContentModule

_Interfaces_ are welcome but any implementation should be in the proper module.

**Comment by craigh** [comment]
@Guite I wonder if this may be a reason to file Core RC2 and move them now.

**Comment by Guite** [comment]
This does **not** work.
See #4354 for how it works.

**Comment by craigh** [comment]
summary of @Guite's concerns:

 - The Interface must be present in the core or extensions containing concrete implementations are broken unless the ContentModule is present/installed. (This is true for other core contracts like BlockInterface)
 - The Abstract must be present because it is a lot of code which would be redundant in multiple implementations throughout multiple Content-providing modules.
 - Therefore ContentModule becomes a non-required dependency for modules like News.

I believe we need a better solution. I'm not sure that a **Contracts** package (refs #4354) is an appropriate solution as _Contracts_ are _Interfaces_ only.

**Comment by Guite** [comment]
Closing as unneeded as content stuff is gone.
