### ISSUE TITLE
improve initialize check in VariableApi

### ISSUE THREAD

**Issue by Guite** [zikula/core#4360]
Inside `VariableApi` check if the system is installed.
This check can then be removed from some listeners that only do it to prevent access to the `module_vars` table.

**Comment by Guite** [comment]
Already done.

**Comment by craigh** [comment]
I'd like to make some modifications to VariableApi based on this.

for example - currently, it makes this check in most methods:

        if (!$this->isInitialized) {
            $this->initialize();
        }

but if core is not installed, then the initialize fails, but the method continues as if it succeeded.

If initialize fails, the method should not continue.
