### ISSUE TITLE
Add handling for missing case in Asset class

### ISSUE THREAD

**Issue by Guite** [zikula/core#4366]
If a normal asset (non zasset) path does not exist in the public folder yet we run into a problem because [this check](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/Asset.php#L96) returns `false`. Afterwards we have an undefined/wrong behaviour because then it proceeds with the bundle resolving sections although a normal path is given. As a result, [this line](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/Asset.php#L101) results in `Notice: Undefined offset: 1`.
So the least we should do is throwing an exception in line 99 then. Or if possible copy the missing file (as a fallback) and return its path afterwards.

**Comment by craigh** [comment]
closed by #4392
