### ISSUE TITLE
[CoreBundle/CoreInstallerBundle] refactor routes to annotations

### ISSUE THREAD

**Issue by craigh** [zikula/core#4370]
Currently CoreBundle routes are via XML

I think I did this at first because I was under the impression that XML was better/faster.

https://symfony.com/doc/current/routing.html#creating-routes indicates "All formats provide the same features and performance"

It would be more convenient to use annotations.

**Comment by Guite** [comment]
Same for CoreInstallerBundle?

**Comment by craigh** [comment]
yes I suppose so.
