### ISSUE TITLE
[Routes] refactor to allow Single Action Controllers

### ISSUE THREAD

**Issue by craigh** [zikula/core#4376]
It is currently impossible to implement single action ([invokable](https://symfony.com/doc/current/controller/service.html#invokable-controllers)) controllers because the routing module expects standard stuff.

 - src/system/RoutesModule/Routing/RouteLoader.php:283
 - create a custom route requires the controller and action, etc...

**Comment by Guite** [comment]
Closing as won't fix as we are about to remove the custom routing system.
