### ISSUE TITLE
[Routes] Cannot edit route

### ISSUE THREAD

**Issue by craigh** [zikula/core#4380]
When trying to edit a route, an alert is always present saying "It looks like you created or updated a route with a path which already exists. This is an error in most cases." Changes are never saved.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.0
| PHP Version       | 7.3.9

## Expected Behavior

Route edits should be saved.

## Current Behavior

When trying to edit a route, an alert is always present saying "It looks like you created or updated a route with a path which already exists. This is an error in most cases." Changes are never saved.

![Screen Shot 2020-07-07 at 8 29 27 AM](https://user-images.githubusercontent.com/350048/86781500-fbde5480-c02b-11ea-8f08-6bb78b66aa5a.png)

**Comment by Guite** [comment]
fixed in #4394
