### ISSUE TITLE
[Routes] bundle prefix not removed as expected

### ISSUE THREAD

**Issue by craigh** [zikula/core#4381]
In creating a custom route, the option exists to "Prepend bundle prefix" (or not). If this is disabled, the route still requires the prefix.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.0
| PHP Version       | 7.3.9

## Expected Behavior

The prefix is not required.

## Current Behavior

![Screen Shot 2020-07-07 at 8 30 40 AM](https://user-images.githubusercontent.com/350048/86781826-60011880-c02c-11ea-93d1-081c3d1b90cf.png)

![Screen Shot 2020-07-07 at 8 33 06 AM](https://user-images.githubusercontent.com/350048/86781911-7e671400-c02c-11ea-9efa-9c6bf63fc2ce.png)

**Comment by Guite** [comment]
Note: [https://github.com/zikula/core/blob/d1d60e556fe2e081d5487c73543ec2a1dab8992b/src/system/RoutesModule/Helper/PathBuilderHelper.php#L38-L42](this) uses but seems to ignore `$route->getPrependBundlePrefix()`; possibly both should be checked and considered.

**Comment by Guite** [comment]
Same for https://github.com/zikula/core/blob/1c44dbc6c19fc12f31459577ed22204e7a9ae960/src/system/RoutesModule/Translation/ZikulaPatternGenerationStrategy.php#L119-L128

**Comment by Guite** [comment]
@craigh said:

> problem is here

https://github.com/zikula/core/blob/1c44dbc6c19fc12f31459577ed22204e7a9ae960/src/system/RoutesModule/Translation/ZikulaPatternGenerationStrategy.php#L119-L128

**Comment by craigh** [comment]
fixed by #4389
