### ISSUE TITLE
[JS] Cannot manage block placement 

### ISSUE THREAD

**Issue by craigh** [zikula/core#4400]
Cannot manage block placement. Javascript error

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.0

e.g. at `blocks/admin/placement/edit/1`
cannot drag & drop block placements. 

Javascript error in console on page load:
> TypeError: undefined is not a function (near '...$('#assignedblocklist tbody').sortable...')

**Comment by craigh** [comment]
current workaround is to simply edit the block and change position placement there.

**Comment by Guite** [comment]
I improved a dropdown menu display in cb3df047a7a2ee24f654777e31047046dd643e50

But I can not reproduce the issue. Works for me with asset combination disabled and enabled.
Opened `/blocks/admin/placement/edit/7` and changed some block placements using drag n drop without any issue.

**Comment by craigh** [comment]
✅ I have asset combination disabled

I also can see this warning.

![Screen Shot 2020-07-13 at 11 53 11 AM](https://user-images.githubusercontent.com/350048/87325450-752fe880-c4ff-11ea-920f-a02a5652f60f.png)

**Comment by craigh** [comment]
OK - I have determined that it isn't working when using [my theme](https://github.com/craigh/SimpleScrollTheme)

do you have any idea what might cause that?

**Comment by craigh** [comment]
> do you have any idea what might cause that?

it appears that jquery-ui is not being included

**Comment by Guite** [comment]
:+1:
