### ISSUE TITLE
[Theme] disable asset combination

### ISSUE THREAD

**Issue by craigh** [zikula/core#4419]
I think we should consider shipping with
   `zikula_asset_manager.combine: false`

I am consistently running into issues where I need to disable it in order for things to work as expected. Especially when developing - including installing/uninstalling extensions. It seems like a standard site-admin would experience these same issues.

We could then document converting to true as a performance improvement that should be done only after the site is "done" (e.g. all modules and themes decided and installed, etc)

not sure if this could/should be done on 3.0.1 or 3.1.0 since it is technically a significant change...

**Comment by Guite** [comment]
:100:

**Comment by craigh** [comment]
which milestone?

**Comment by Guite** [comment]
I am fine with 3.1.0.

**Comment by craigh** [comment]
this was completed in #4433 
more specifically [here](https://github.com/zikula/core/pull/4433/files#diff-bba0f72af64bd7eea95da9a6bb489651R42)
