### ISSUE TITLE
[Releng] make github action workflows branch-aware

### ISSUE THREAD

**Issue by craigh** [zikula/core#4420]
both the `build-archives` and `update-dependencies` workflows must be updated to be **branch-aware**.

It appears at the moment that `update-dependencies` works only with the master branch

    steps:
    - name: Checkout sources from master branch
      uses: actions/checkout@v2
      with:
        ref: master

the `build-archives` workflow works with all branches (except `gh-pages`) but should be possibly modified to behave differently per branch? At current there is a [warning](https://github.com/zikula/core/actions/runs/181224501) in the output:
![Screen Shot 2020-07-24 at 9 57 05 AM](https://user-images.githubusercontent.com/350048/88398989-2f431200-cd94-11ea-86a5-e2bd18c74c10.png)

**Comment by craigh** [comment]
this is from similar changes in the `copy-to-dist` workflow and could be useful

    steps:
      - name: Set env
        run: echo ::set-env name=BRANCH_NAME::${GITHUB_REF##*/}

**Comment by craigh** [comment]
be sure to update similar actions in zikula/distribution

**Comment by Guite** [comment]
- `update-dependencies`: changed in https://github.com/zikula/core/commit/17fc38c4677af0996fd54dd9c61a0ba75cd8a9f0 - we do not want this for all branches, but only for the "lowest" active branch, because we merge from `3.0` to `master`
- `build-archives`: no action required

IMO this can be closed

**Comment by Guite** [comment]
distribution commit: https://github.com/zikula/distribution/commit/8f588612e70c15d65bde74e62bc6b0a84ab4f089

**Comment by craigh** [comment]
> we do not want this for all branches, but only for the "lowest" active branch, because we merge from 3.0 to master
I disagree. The composer.json files are currently different. We dealt with this some when we were working with the 2.0 and master branch as well. When merging up, you have to run composer update each time.

> build-archives: no action required
Again, I disagree. We want a 3.0.x archive and (eventually) a 3.1.x archive. So we need the script to operate independently in both branches.

> IMO this can be closed
so, again. disagree.

**Comment by Guite** [comment]
> When merging up, you have to run composer update each time.
This won't change, also if `composer.json` in `master` is independently updated by an additional job in addition.

> So we need the script to operate independently in both branches.
This is already done.

Example 3.0.2: https://github.com/zikula/core/actions/runs/183061392
Example 3.1.0: https://github.com/zikula/core/actions/runs/183128212

You can download, extract and verify the contained files. I did that and it works as it should. First example contains 3.0.2-dev and second example contains 3.1.0-dev including StaticContent extensions.

Is there any additional requirement I do not see?
