### ISSUE TITLE
[Extensions] Do not translate MetaData

### ISSUE THREAD

**Issue by craigh** [zikula/core#4436]
In `\Zikula\Bundle\CoreBundle\Composer\MetaData` we attempt to translate several properties:
 - description
 - displayName
 - url

In addition, we also dynamically set these properties in the Extensions UI and then reset them when MetaData is constructed (currently [here](https://github.com/zikula/core/blob/3cca1f4e46c6ba7f1217d7e7aa5a5c7027ed792a/src/system/ExtensionsModule/AbstractExtension.php#L134-L137) but PR moves to [here](https://github.com/zikula/core/pull/4433/files#diff-ab967780960c74280c155c2f4f71bc47R49-R52))

This seems bad practice. we should not be doing _both_ translation and dynamic replacement. I suggest removal of the translation.

Technically this would be a BC break. But in userland, I doubt very much that the translation is being used by anyone because the strings are not (can not?) be extracted. so they are likely not available as translations unless a user manually sets it up (which seems unlikely). Additionally this data is not user-facing, but rather admin viewable only, I believe. Therefore, I suggest for removal at 3.1.0.

@Guite ?

**Comment by Guite** [comment]
Fine with dropping translation.

> rather admin viewable only

One exception for that: the display name is (or at least was) often used as heading in the user area.


Premium solution would be an ability to enter these values for each language in UI. Could be postponed as a separate issue for 4.0

**Comment by Guite** [comment]
Closing as won't fix as state-based extensions handling will be entirely removed in favor of Composer and Flex.
