### ISSUE TITLE
Module Dependencies are not working correctly

### ISSUE THREAD

**Issue by lmm-git** [zikula/core#445]
If you have an module that requires a module which is available but not installed and this module (available, not installed) has a dependency to another module which is not available in the modules directory Zikula will only give you an errormessage, but not which module Zikula is searching for (There is no list entry).

**Comment by craigh** [comment]
I'm closing this because the code has so dramatically changed since the ticket was written that there is no way to know if the behavior is remotely the same. Module dependencies are a bit flakey anyway and I'm sure they could be improved, but this ticket isn't representative of the actual issues.
