### ISSUE TITLE
Assets not found on Windows with Zikula in a subdirectory

### ISSUE THREAD

**Issue by Fraddy** [zikula/core#4480]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.3
| PHP Version       | 7.4.10

## Current Behavior

Apologies!
Error Code: -1
Could not find asset "C:\PUBLIC_DIR/PUBLIC_PATH"

_(please notice the backward and forward slashes)_

## Possible Solution

Update:  vendor\zikula\theme-module\Engine\Asset.php
Line 87:  `$publicDir = $this->kernel->getProjectDir() . '/public';`
Replace with:  `$publicDir = str_replace('\\', '/', $this->kernel->getProjectDir()) . '/public';`

`$this->kernel->getProjectDir()` returns basically `__DIR__` and contains backslashes on Windows.

This causes line 89 to fail on the replacement as $basePath contains forward slashes:
   `$httpRootDir = str_replace($basePath, '', $publicDir);`

## Context

This issue will only occur on Windows webservers when Zikula is not installed in the document root but in a subdirectory.

**Comment by Guite** [comment]
Thank you very much for reporting :+1: 
We are going to include this into the next update.

**Comment by Guite** [comment]
Fixed in #4482
