### ISSUE TITLE
Error when removing old locale parameter

### ISSUE THREAD

**Issue by Guite** [zikula/core#4489]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.1.0-dev
| PHP Version       | 7.4.3

## Expected Behavior

Site loads when removing `locale: en` from [here](https://github.com/zikula/core/blob/master/config/services.yaml#L10)

## Current Behavior

I get this exception:

`You have requested a non-existent parameter "locale".`

![Screenshot_20200923_073446](https://user-images.githubusercontent.com/277531/93970891-4b9d0400-fd6f-11ea-8e54-4c1fb8d0c382.png)

## Insights

I've seen this parameter is set [here](https://github.com/zikula/core/blob/master/src/system/SettingsModule/DependencyInjection/ZikulaSettingsExtension.php#L63). But the exception occurs before this code is executed.

When I search for `%locale%` in `src` I find these occurances:

- https://github.com/zikula/core/blob/master/src/system/SettingsModule/Resources/config/services.yaml#L20
- https://github.com/zikula/core/blob/master/src/system/RoutesModule/Resources/config/services.yaml#L64
- https://github.com/zikula-modules/Profile/blob/master/Resources/config/services.yaml#L29
- https://github.com/zikula/core/blob/master/src/Zikula/CoreInstallerBundle/Resources/config/services.yaml#L9

## Context

This occured after I updated my 3.0.4-dev site to 3.1.0-dev. So very probably I am overseeing something, similarly to
https://github.com/zikula/core/commit/7f43a4cee498ee93d1967639ac3c9057ea5a93ae#commitcomment-42646759

**Comment by craigh** [comment]
> But the exception occurs before this code is executed.

This doesn't make sense to me. The Dependency Injection code runs when the container is built. This is before any page is loaded.

Can you be more specific on how you created the error - or when the error manifests?

**Comment by craigh** [comment]
please post your contents of `config/packages/translation.yaml` and compare to https://github.com/zikula/core/blob/master/config/packages/translation.yaml

**Comment by Guite** [comment]
Good suggestion  :+1: 

Replaced whole `config/` folder by `master` version and things worked again!
Thanks.
