### ISSUE TITLE
Error when removing assets_version parameter

### ISSUE THREAD

**Issue by Guite** [zikula/core#4490]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.1.0-dev
| PHP Version       | 7.4.3

## Expected Behavior

Site loads when removing `assets_version: ~ #e.g. 'v1'` from [here](https://github.com/zikula/core/blob/master/config/services.yaml#L7)

## Current Behavior

I get this exception:

`You have requested a non-existent parameter "assets_version".`

![Screenshot_20200923_073802](https://user-images.githubusercontent.com/277531/93971111-b9e1c680-fd6f-11ea-9170-d96f54bf394a.png)

## Insights

I did not find any occurance of `assets_version` in `src`.

So apparently this parameter is not set by any configuration at the moment. Should it be part of the Theme module? Or should we keep it in `/config/services.yaml`?

## Context

This occured after I updated my 3.0.4-dev site to 3.1.0-dev. So very probably I am overseeing something, similarly to
https://github.com/zikula/core/commit/7f43a4cee498ee93d1967639ac3c9057ea5a93ae#commitcomment-42646759

**Comment by craigh** [comment]
You have fully removed the old `services_custom.yaml` file? It should be gone. Also the the old `config/generated` dir - remove it.

**Comment by Guite** [comment]
I didn't remove `config/dynamic/` yet. After I did that, I now receive:
`You have requested a non-existent parameter "zikula.session.name".`

**Comment by craigh** [comment]
none of this makes sense to me. to be honest, I did not work with upgrades much when I did the initial work and I acknowledge that it was incomplete, but at the code-level, **none** of these parameters should be required. Sadly, I don't have time atm to work on it.

**Comment by Guite** [comment]
no hurry, we can talk about it in Slack in a few days... maybe I find something in the meanwhile

**Comment by craigh** [comment]
my new install of 3.1.0 was working fine after full removal of everything.

**Comment by craigh** [comment]
please show the contents of your `config/packages/framework.yaml`

**Comment by craigh** [comment]
also compare it to https://github.com/zikula/core/blob/master/config/packages/framework.yaml

**Comment by Guite** [comment]
Good suggestion  :+1: 

Replaced whole `config/` folder by `master` version and things worked again!
Thanks.
