### ISSUE TITLE
Changing session storage type doesn't appear to work

### ISSUE THREAD

**Issue by craigh** [zikula/core#4495]
this is a problem in 3.1.0 ONLY

when changing session storage type, the value is properly updated in the config but it doesn't switch the type of storage actually. 

I suspect the cache simply must be properly cleared so the config is reloaded.

**Comment by craigh** [comment]
If I delete the `cache/prod/sessions` dir then the method changes

**Comment by craigh** [comment]
I'm not sure the previous comment is actually true.

The problem I think lies in my lack of understanding of the container and the rebuild process. The same problem that affects module installation and other container-related operations. Before Sy5 it was pretty clear how the container worked - everything worked from the files in the cache folder... delete the cache and it rebuilds and changes the operation/behavior. Since Sy5, that seems changed - the container seems held in memory and doesn't seem to affect change very quickly... sometimes several page loads or leaving a site and returning are required before the cached files are rebuilt and change the operation/behavior. This seems random and unpredictable and makes changing the container very difficult.

**Comment by Guite** [comment]
> seems held in memory

Possibly this is related to opcache... 

https://github.com/deployphp/deployer/issues/1439
https://github.com/deployphp/deployer/blob/master/contrib/cachetool.php
https://gordalina.github.io/cachetool/

**Comment by craigh** [comment]
![Screen Shot 2020-09-26 at 9 30 08 AM](https://user-images.githubusercontent.com/350048/94341861-e0f00080-ffda-11ea-8a69-833a7cd1ae05.png)

it appears I am using OPcache without understanding it. So perhaps the problem is that and not Sy5...

**Comment by craigh** [comment]
indeed. disabling OPcache seems to have cleared the problem. behavior is now as expected...

the problem of course is how to deal with this in a generic way in production for zikula installations.

this seems promising https://ma.ttias.be/how-to-clear-php-opcache/

`opcache_reset();`

**Comment by craigh** [comment]
closed by #4507
