### ISSUE TITLE
[Users/ZAuth] Change default sorting in user lists

### ISSUE THREAD

**Issue by Guite** [zikula/core#4502]
In both Users and ZAuth modules the `UserAdministrationController` methods have a default sorting by _uid DESC_. It would be more convenient to use _uname ASC_ here.

Opinions?

**Comment by craigh** [comment]
I'm not sure I agree. _uid DESC_ would put the most recently added user at the top. Often if I am looking for a user it is someone that added recently. If I am looking for someone else and the list is long, then I am using the search feature anyway, not sort.

**Comment by Guite** [comment]
We could also add the possibility to change sorting using the table column headers.

**Comment by craigh** [comment]
![Screen Shot 2020-09-30 at 3 07 46 PM](https://user-images.githubusercontent.com/350048/94728752-b41b5080-032e-11eb-9157-ffa156f6aefc.png)

this is already implemented.

**Comment by Guite** [comment]
:+1: 
Closing then.
