### ISSUE TITLE
[Vendor] Update Doctrine extensions

### ISSUE THREAD

**Issue by Guite** [zikula/core#4505]
- https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.0.0
  - https://github.com/doctrine-extensions/DoctrineExtensions/pull/2174/files
  - https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.0.3
- https://github.com/stof/StofDoctrineExtensionsBundle/releases/tag/v1.5.0
- https://github.com/antishov/StofDoctrineExtensionsBundle/issues/22
- https://github.com/stof/StofDoctrineExtensionsBundle/issues/422#issuecomment-771026242

**Comment by craigh** [comment]
we aren't using stof's branch we are using a different branch
https://github.com/zikula/core/blob/master/composer.lock#L10

I'm not sure we should switch back to the original branch.

**Comment by Guite** [comment]
I will observe both for a while I think.

**Comment by Guite** [comment]
https://github.com/antishov/StofDoctrineExtensionsBundle/issues/22

**Comment by Guite** [comment]
https://github.com/stof/StofDoctrineExtensionsBundle/issues/422#issuecomment-771026242
https://github.com/doctrine-extensions/DoctrineExtensions/pull/2182
