### ISSUE TITLE
[Routes] Review potential relicts from action suffix removals

### ISSUE THREAD

**Issue by Guite** [zikula/core#4517]
- [ ] `src/system/RoutesModule/Helper/SanitizeHelper.php`: `sanitizeAction` method
- [ ] main controller - selecting controller/action for the main page in "general settings > start page"
- [ ] Routes module - creating custom routes - update code needed?
- [ ] Content module - selecting controller/action for controller elements - update code needed?

**Comment by craigh** [comment]
you created a select method for the start page selector which seems like it could be useful in the routes module at least if not elsewhere.

**Comment by craigh** [comment]
refs #4376
