### ISSUE TITLE
\Zikula\ExtensionsModule\AbstractExtension::getRelativeAssetPath returns incorrect value

### ISSUE THREAD

**Issue by craigh** [zikula/core#4551]
\Zikula\ExtensionsModule\AbstractExtension::getRelativeAssetPath returns e.g. `zikulathem` instead of `zikulatheme`

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.1.0-dev

        $name = s($this->getName())->trimEnd($this->getNameType());

seems to be cutting off an additional character in all cases.

@Guite can you please solve.

**Comment by Guite** [comment]
Seems a vendor issue. Will do a partial revert for `trim*` usages.

**Comment by craigh** [comment]
Link to vendor ticket?

**Comment by Guite** [comment]
Vendor ticket: https://github.com/symfony/symfony/issues/39181
