### ISSUE TITLE
[Releng] Update dependency updater workflow

### ISSUE THREAD

**Issue by Guite** [zikula/core#4573]
The action that creates pull requests for vendor updates needs to be enhanced to check all `composer.json` files for all included bundles and system modules.

**Comment by craigh** [comment]
I'm not sure I understand here. Please help?

The `zikula/core` repository includes a master `composer.json` which _must_ include all dependencies. Therefore, any dependency listen in the sub packages, must be included in the master.

Perhaps you mean the `zikula/distribution` repository? This would be fully dependent on the sub packages, but I don't think we have such a workflow there.

Again, I do not understand :smile:

**Comment by Guite** [comment]
This issue is about extending the action for updating vendors in order to cover also the `composer.json` files of all single bundles, e.g. https://github.com/zikula/core/blob/master/src/system/ThemeModule/composer.json#L16 and https://github.com/zikula/core/blob/master/src/Zikula/HookBundle/composer.json#L14

**Comment by craigh** [comment]
> Now that I re-think about it I see it doesn't make sense

😉
