### ISSUE TITLE
ext-ldap dependency on purpose?

### ISSUE THREAD

**Issue by Guite** [zikula/core#4574]
As the `master` branch's `composer.json` does now require `"symfony/ldap": "^5.2",` this transitively requires `"ext-ldap": "*"`. Do we want that? If yes, we need to document that this PHP extension is needed starting with Zikula 3.1.0. If not, we might remove the `symfony/ldap` dependency.

**Comment by craigh** [comment]
If `symfony/ldap` was not required (included) previously, then we should remove it.
