### ISSUE TITLE
Consider event for renaming users

### ISSUE THREAD

**Issue by Guite** [zikula/core#4577]
Some vendor-oriented concepts are based on user names instead of user IDs (e.g. Loggable behaviour). Hence, it would be useful if an extension could react on a changed user name. Therefore this issue proposes introducing a new event that communicates the user ID, the old user name and the new user name, so subscribers can execute subsequent actions.

**Comment by craigh** [comment]
There are already more generic versions:
 - UserEntityChangedEvent
 - ActiveUserPostUpdatedEvent

**Comment by Guite** [comment]
You are right. Please leave this issue open though. Assigning to myself.

**Comment by Guite** [comment]
Close in favour of https://github.com/Guite/MostGenerator/issues/1251
