### ISSUE TITLE
Folder var/cache/prod/purifier does not exist in dev mode

### ISSUE THREAD

**Issue by KratorD** [zikula/core#4620]
I have in my theme a Twig Extension that generate an HTML. I call to my twig extension in my template
{{ getBanner(size="728x90", product="33530")|safeHtml }}
I'm using dev mode. I got the errror
`An exception has been thrown during the rendering of a template ("User Warning: Base directory C:\xampp\htdocs\zk3fresh/var/cache/prod/purifier does not exist,
 please create or change using %Cache.SerializerPath").`
If I create the directory, the code work successfully.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.3
| PHP Version       | 7.3.14

## Expected Behavior

We dont need `var/cache/prod/purifier` in dev mode

## Current Behavior

We need the directory.
![imagen](https://user-images.githubusercontent.com/5812569/112601530-d9d36f00-8e12-11eb-8024-08bcf7d2d757.png)

**Comment by Guite** [comment]
Closing because HTML Purifier is being removed.
Symfony offers other solutions, like for example https://github.com/Exercise/HTMLPurifierBundle and/or https://symfony.com/blog/new-in-symfony-6-1-htmlsanitizer-component
