### ISSUE TITLE
EUCookie translations missing for the Legal module

### ISSUE THREAD

**Issue by ThiloWitt** [zikula/core#4695]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.3.
| PHP Version       | 7.4.21

## Expected Behavior

Below translation strings in `ZikulaLegalModule.Listener.EUCookieConfig.js` shall be translatable:
```
            message: Translator.trans('We use cookies to track usage and preferences.'),
            acceptText: Translator.trans('I Understand'),
```

## Current Behavior

Both translation strings do not exist in Zikula `messages.yaml` and there are no specific translation files in the Zauth module

## Possible Solution

Add the translations strings to Zikula `messages.en.yaml` and for any other language.

**Comment by Guite** [comment]
Please report at https://github.com/zikula-modules/Legal
