### ISSUE TITLE
[DefaultTheme] new layout

### ISSUE THREAD

**Issue by Kaik** [zikula/core#4803]
### Summary

Refresh admin layout - use consistent layout design typography, colours, sizes, cards etc... 
Redesign admin area - use dedicated admin block positions, notifications, tabs, menus, override current module templates, provide reusable stimulus components for common admin elements...

### Desired behaviour

Proposed layout "idea" https://www.bootstrapdash.com/demo/star-admin2-free/template/index.html
Layout should be simple - preferably fluid.
Base should contain side menu on the left, top bar, footer and content.
Content can be 1col 2cols or 3 cols with dedicated admin block positions

### Menus

Side bar on the left/block position- tabs/categories or modules list or both

Tabs - can be changed to pills or shortcuts (feature) - it is an remnant of old design...

### Blocks
Theme can provide additional simple blocks that can be placed in admin block positions and react on admin category that is viewed displaying information like last logged in users or general configuration status, shortcuts etc.. 

### Zikula version

3/4

### PHP version

NA

**Comment by Guite** [comment]
Closing as basically done (just in a much more simple way)
