### ISSUE TITLE
Adding cron

### ISSUE THREAD

**Issue by lmm-git** [zikula/core#573]
Please add a cron util or module to the Zikula core or something similar.

**Comment by cmfcmf** [comment]
Interesting read: http://wordpress.stackexchange.com/a/169088

**Comment by Guite** [comment]
:-1: 

This is not a job for the core.
Either use a 3rd party module or a Symfony bundle or just a cron function on your server or your hoster's control panel.

Closing. If you have any objections about it feel free to reopen.
