### ISSUE TITLE
Change permission level for plugins admin interface

### ISSUE THREAD

**Issue by jusuff** [zikula/core#577]
Right now, when accessing plugins admin interface ACCESS_ADMIN permissions level is required. What's more - it's checked for "Extensions::" compontent.
This check is performed in Extensions_Controller_Adminplugin::dispatch

        if (!SecurityUtil::checkPermission('Extensions::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }

Do we really need so hight restriction? Setting permission level to ACCESS_EDIT would be consistent with level required to access admin panel.
And maybe we should set some more specific instance? For example "Extensions::Adminplugin" compotent and "PluginName::" instance?

This would allow to grant access to plugin configuration for non "superadmin" users.

**Comment by craigh** [comment]
System/module plugins are deprecated and this will not be implemented.
