### ISSUE TITLE
[Menutree] Add option for SSL/HTTPS url in the menu

### ISSUE THREAD

**Issue by espaan** [zikula/core#600]
Hi,
it would be good if menutree has a general option for all urls to be ssl/https or specific parts to be ssl/https.

For example userlinks and adminlinks could be https.
Or menuitems to forms with client data could be ssl encrypted.
- So a general option to make all URLS https
- An option to specify ssl yes/no on all menuitems
- current not specified way

See for example in Wordpress that has done stuff to ensure SSL encryption:
http://codex.wordpress.org/Administration_Over_SSL

**Comment by craigh** [comment]
MenuTree has been deprecated and will be removed from Core-2.0. closing won't fix.
