### ISSUE TITLE
Add SSL/HTTPS options in the Core for certain areas

### ISSUE THREAD

**Issue by espaan** [zikula/core#601]
Hi,
it would be good to have the option to turn on SSL/HTTPS for specific parts of the Core.
- Login and Registration
- Admin area
- Specific modules
- ?

See for example 
http://codex.wordpress.org/Administration_Over_SSL
or
http://www.wpbeginner.com/wp-tutorials/how-to-secure-your-wordpress-pages-with-ssl/

**Comment by Guite** [comment]
Wondering whether this should be considered as done/possible, given that routes can require certain schemes. However, today most sites use https for everything so the whole issue seems obsolete...

**Comment by Guite** [comment]
Closed.
