### ISSUE TITLE
[Search] [RFC] Replacing the Search Module

### ISSUE THREAD

**Issue by craigh** [zikula/core#634]
It is time to start discussing replacing the search module. We need a more robust and easily implemented solution for third party modules.

here are some resources to begin the discussion:

https://github.com/doctrine/search

http://www.opensearch.org/Home

http://www.elasticsearch.org/ (JAVA server side app)

http://lucene.apache.org/solr/ (JAVA server side app)

http://framework.zend.com/manual/1.12/en/zend.search.lucene.html (PHP based - Zend_Search_Lucene)

I've not looked into this in any great detail and am not prepared to work on it at the moment. But we need to discuss a future solution and work out a timeline.

I think the PHP solution above seems like the obvious choice. It doesn't seem like  JAVA solution would be a good one for a PHP Framework. Also the Doctrine Search can use the Lucene project. Seems like a good fit. The Opensearch suggestion comes from a suggestion from drak on an earlier ticket.

In the end, I would like a third party module to either provide an ID and fields to search and leave the rest to the Search module or come up with some kind of Abstract class that modules inherit from that clearly defines the module's role/responsibility.

**Comment by craigh** [comment]
http://symfony.com/blog/the-new-symfony-documentation-search-engine

https://github.com/algolia/AlgoliaSearchBundle

**Comment by shefik** [comment]
Note fees involved for Algolia.

**Comment by Guite** [comment]
Adding some reading materials:

* https://github.com/doctrine/search
* https://www.strangebuzz.com/en/blog/implementing-a-search-engine-with-elasticsearch-and-symfony
* https://www.strangebuzz.com/en/blog/implementing-a-search-engine-with-elasticsearch-and-symfony-part-2
* https://www.strangebuzz.com/en/blog/implementing-a-search-engine-with-elasticsearch-and-symfony-part-3
