### ISSUE TITLE
In modules with plugin(s). in admin panel links - add easy acces to plugin(s) configuration

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#703]
Now if a module have hooks, in admin panel appears a "Hooks" link.

If module have plugins - nothing appears there.

Un example is Scribite module (version 5). To access configuration page for given editor, user have to click 2 more times, and after save edits - user is redirected to wrong place, not to module panel.

**Comment by craigh** [comment]
based on https://github.com/zikula/core/issues/1948#issuecomment-252481701 I think this will become a won't-fix

**Comment by craigh** [comment]
changed to milestone 1.4.4 - close when #1948 is closed.
