### ISSUE TITLE
Consider Renaming the Files for Country Image Flags

### ISSUE THREAD

**Issue by shefik** [zikula/core#732]
There are country flags available here:

images/flags

However, the file names do not fully correspond to the array populated here:

ZLanguage::countryMap();

If the file names are changed to match the country map array, then it will be easier to code image tags dynamically, instead of having to conditional code for certain cases.

For example, for the United States, I would expect there to be a flag named "us.png", but there isn't one currently available. However, the United States flag is currently incorrectly named "flag-en_US.png", which corresponds to a language code (and not a country code).

I suggest renaming the country flags, as well as moving them to this new path:

images/flags/countries

If any additional flags are need for other purposes (based on language codes, etc.), then organize them in subdirectories accordingly, such as:

images/flags/languages

**Comment by craigh** [comment]
flags are removed
