### ISSUE TITLE
Add OExchange for Service Providers

### ISSUE THREAD

**Issue by shefik** [zikula/core#823]
OExchange makes it possible to share any URL-based content with any service on the web. It defines:
- A common way for services to receive content, removing any and all service-specific integration requirements
- A discovery feature so services can publish themselves and their endpoints, making it possible to integrate with services you didn't even know about at development time
- A decentralized, user-centric model for saving preferred services, making sharing more personal

As a Service Provider, Zikula can receive more content by allowing anyone to integrate easily.

http://www.oexchange.org/guide/#service-providers
http://www.oexchange.org

**Comment by Guite** [comment]
Any reason why this should be part of the core?
Looks like this is rather something for a 3rd party module, like https://github.com/zikula-ev/Formicula/issues/35
