### ISSUE TITLE
jQuery forward compatibility layer for Zikula 1.4.x

### ISSUE THREAD

**Issue by phaidon** [zikula/core#844]
**Starting position**
Zikula 1.4 and all later version will use jQuery as standard. By technical reason there is no noconflict for prototype.js. This means we have to drop prototype.js and all prototype.js javascript in Zikula (core, modules, ...)

**The problems**
1. Because there is no big motivation to program in prototype anymore more and more modules are using jQuery. This means both frameworks (prototype.js and jQuery) has to be loaded.
2. IMHO the release of 1.4 is far away (IMHO more the year). The replacement of prototype scripts in Zikula core is a huge work and it is difficult because it is to be done as hole step. Partly steps are not possible.

**My suggestion**
Add a jQuery forward compatibility layer to Zikula 1.4

**How will it work**
1. There will be a possibility in the system settings to select the preferred framework (jQuery/prototype) 
2. There will a jQuery check in pageaddvar. If prototype is activated as preferred framework nothing will happen. If jQuery is activated as preferred framework pageaddvar will check if there is a jQuery version of a script which should be loaded. For example if pageaddvar has to add xxx/test.js it will test if a xxx/test.jQuery.js is available. If a jQuery is available it will load this file otherwise it will load the original file.

**Questions**
1. Can I still use prototype if chosed jQuery as preferred framework.
Yes jQuery will use (like now) noConflict. So a mixture is still possible. This is also valid for the other way around.
2. How can I provide a jQuery version for inline code?
There are two possibilities: 1. By a smarty if or by using an external js.

**Benefits of this solution**
1. It will be possible to run 1.3.x without prototype loading.
2. We do the jQuery migration work of Zikula 1.4. already step by step in Zikula 1.3.x.

**Comment by phaidon** [comment]
I would to discard this idea. 

I think the only good way to offer an prototype compatibility (without any problems) is to use jQuery noConflict. 

IMHO I would use noConflict even in Zikula 2.0.0. This would allow to offer an prototype/zikula-helpers package.

So I suggest to close this topic.

**Comment by Guite** [comment]
I agree!
Does anybody have objections?

**Comment by craigh** [comment]
I agree also, but I wish someone would tackle the work of migrating existing needed scripts from prototype to jquery...

**Comment by cmfcmf** [comment]
:+1:

**Comment by Guite** [comment]
I can't promise anything at the moment, but I will try to proceed on #1214 soon.
