### ISSUE TITLE
Extend authentication module API to allow for automatic creation of local accounts

### ISSUE THREAD

**Issue by rojblake** [zikula/core#901]
Following on from a discussion surrounding the OpenID module and my own development of a module to authenticate against Active Directory it's become clear that there is a missing element to the authentication module API.

The existing API is limited in that it offers no functionality to handle either automatic or prompted creation of accounts when the user doesn't have an account already. The user must go through the account sign-up process. While this is fine for the public accessible site it doesn't meet the requirements for any closed site where the administrator is wanting to authenticate users against an existing user  source (e.g. in may case active directory).

In this use case the local account in the zk database purely serves the purpose of providing zk something to map sessions, permissions etc against. The user shouldn't even know they have a local account. This should be completely transparent.

-Mark

**Comment by Guite** [comment]
@craigh This is solved by new authentication interfaces, isn't it?

**Comment by craigh** [comment]
no, I don't think so.

**Comment by craigh** [comment]
The Core-2.0 refactoring of the 1.0-era abstraction of authentication basically solved this. And certainly, the improvements made for 3.0 now fully implement it. ZikulaOAuthModule is a prime example of the exact workflow described above. Really - this was all done in 1.0 by @rmburkhead 's remake of the Users module. Further improvements have refined this and frankly, the implementation is not too difficult.
