### ISSUE TITLE
[Extensions] Search and download extensions via Zikula admin interface.

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#909]
Definitly something for the future :grinning: 

It would be great if one does not have to search an AppStore / github but could be able to search and download extensions via the Zikula admin interface.

**Comment by cmfcmf** [comment]
Composer could be used to do all of this. PageKit seems to do it this way. It needs to be looked into, but this might be a starting point: https://github.com/pagekit/pagekit/blob/develop/app/installer/src/Helper/Composer.php.

**Comment by Guite** [comment]
Closing since we are now jusing Composer and Flex like Symfony default.
