### ISSUE TITLE
Send usage statistics

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#913]
See #876 for the start of the discussion.

Thoughts:
- Do not send if developement is on
- Add a checkbox to the installer to enable/disable sending
- Send every seven days:
  - modules (names and version)
  - themes (names and version)
  - plugins (names and version)
  - Zikula version
  - Number of users
  - default theme
  - if mobile theme is used
  - …

**Comment by rallek** [comment]
Piwik is doing well

**Comment by Guite** [comment]
> I dont think this is important and should have high priorities. But if someone want to do it can be done by module.

Exactly :+1: 

Closing this.
