### ISSUE TITLE
It should be clear what legacy settings in config.php means in zk136 

### ISSUE THREAD

**Issue by espaan** [zikula/core#945]
Hi, there are these settings in config.php

```
$ZConfig['System']['development'] = 1;      // development mode 1/0 for on or off.  Disable in production mode.
$ZConfig['System']['legacy_prefilters'] = true; // enable legacy template prefilters
$ZConfig['System']['compat_layer'] = true;  // enable loading of compat layers
```

it should be made clear what they are doing and how to set them up in the various environments that are possible. 

So 1.3.5 modules, 1.2.x modules, 1.3.6 symfony modules etc.

**Comment by nmpetkov** [comment]
One important impact of setting:
```$ZConfig['System']['compat_layer'] = false; ```
is theme overriding changes dramatically, because all overriding template files have to be specified in ```yml``` files, as described in documentation, but is also clear from this issue:
#318: ```No theme overriding with compat_layer = false```

**Comment by espaan** [comment]
Ah ok, didnt realize that. I have it on since it's not a big performance penalty in 1.3.x core. You might do a small PR to add that to as a comment in config.php

**Comment by nmpetkov** [comment]
@espaan Ok, but before making PR, one more think. In View.php there is piece of code
```
        if (System::isLegacyMode()) {
            $this->assign('stylepath', $this->baseurl . 'themes/' . $theme . '/style')
                 ->assign('scriptpath', $this->baseurl . 'themes/' . $theme . '/javascript')
                 ->assign('imagepath', $this->baseurl . 'themes/' . $theme . '/images')
                 ->assign('imagelangpath', $this->baseurl . 'themes/' . $theme . '/images/' . $this->language);
        }
```
Searching this variables, I found, that ```$stylepath``` is used in tpl files in Zikula 1.3. Is this is a bug?

**Comment by espaan** [comment]
I don't use the stylepath/imagepath any more myself. But I thought they were still supported in 1.3.x. But I'm not sure actually.

**Comment by nmpetkov** [comment]
As seen from above code, if you install Zikula 1.3, and change legacy mode to ```false```, then style sheets are not loaded (explore master.tpl files for all themes, plus ```system\Permissions\templates\permissions_admin_viewinstanceinfo.tpl```). So, I think this is a bug, as the system have to work with this mode set to '''false```.

**Comment by nmpetkov** [comment]
Edit: In fact they are again init in Theme.php, so they *are* available in tpl files.
